### ISSUE TITLE
[Bug] Occasional mistaken "Failed to load" warning

### ISSUE THREAD

**Issue by twwn** [ankidroid/Anki-Android#10033]
###### Reproduction Steps

1. Have a card with `<audio src="foo bar.mp3"></audio>` on them
2. Review it

###### Expected Result

Card renders without issue (if the file exists) and the webview does with the audio whatever the deck creator scripted it to.

###### Actual Result

Occasionally (no discernible pattern) AnkiDroid will throw a `"Card Content Error: Failed to load 'foo bar.mp3'"` warning, despite the file being handled just fine.

###### Debug info
v2.16a29 on Android 11

I'm not sure if this is related to certain Anki desktop shenanigans, like it (I'm on git/2.1.50) rewriting/HTML escaping the spaces in `src`ed files to `%20`. (Something that AnkiDroid does to, such as by rewriting the `<br[/]>`s placed by Anki to newline characters.)

**Comment by silidev** [comment]
Hi! I use the JS API a lot and recently I see <string name="card_viewer_could_not_find_image">Card Content Error: Failed to load ‘%s’</string> a lot, without using any media files. Instead %s is xxx.bin, with xxx being a name referring to an element of the JS API. I am pretty sure this began with JS-API 0.2 or 0.3. 
For me this is quite maddening because while the error message is on the screen I cannot use the buttons beneath it. I can make the button bigger, but then I lose a part of my precious display real estate to this.
