### ISSUE TITLE
Add support for hierarchical tags

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#10095]
Anki Desktop has native support for hierarchical tags for the last several releases. Please add the feature to AnkiDroid for compatibility.

**Comment by mikehardy** [comment]
PRs happily accepted! :-)

**Comment by RogerDTZ** [comment]
Anki Desktop scans the hierarchy through separating a tag by double colons `::`. The tag is displayed as pure string with colons in AnkiDroid.

Two parts need to be adapted, the finder part and the tag picker part.
The finder in card browser can be implemented by adding another DB query. The tag picker however needs UI update (i.e. adding tree hierarchy to tag list). 

I think it's good to add an option to decide whether to search only the tag itself, or its child tags as well. Anyway I'm trying to work on it.

**Comment by RogerDTZ** [comment]
I have a question about sorting. In the tag picker of note editor, `TagList` always puts the checked tags at the front. In hierarchy context this means a checked tag's relavant tags (children, ancestors, and brothers) should be moved ahead as well.

Should I reserve the checked-first sorting after implementing the folding feature? That is to say, sorting children (or roots) so that a child (or a root) whose subtree contains checked tag is displayed first. Or, is it OK to disable it?
