### ISSUE TITLE
[Bug] Anki deletes media files

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#10324]
When I use the following code there is no issue
![Screenshot_20220209-221135_1](https://user-images.githubusercontent.com/73913963/153336103-8f364452-5eb0-4ac0-98b6-1e2a065eb4b4.png)
However when I use the following code:
![Screenshot_20220209-221209_1](https://user-images.githubusercontent.com/73913963/153336180-d2066357-2111-47b0-afec-b14c3af23719.png)
I check the media
![IMG-20220209-WA0001](https://user-images.githubusercontent.com/73913963/153336635-db5f6b04-c839-4075-89a1-c5720a63c49f.jpg)
Tells me that there are files that are not being used.
if I press delete files not used it deletes the audio.

**Comment by mikehardy** [comment]
I believe that is expected behavior. Anki is not a general purpose HTML parser, and you could also conceivably refer to audio files in a number of other ways that Anki could not correctly figure out.
In order for Anki to understand you are using a media file you need to refer to it using the ank-specific (not html) tags.
I am going to guess that Anki Desktop behaves the same way, can you confirm that (if you use Anki Desktop)?

**Comment by mikehardy** [comment]
Video files are supposed to be attachable and playable on AnkiDroid as well, though there is some related issue there where video files may not be attached. Doing something like `[sound:foo.mp4]` should actually play a video :thinking:

**Comment by javiercl2020** [comment]
I dont like the sound:;$;$.mp4 tag because it plays videos on another window and cannot control the progress.
