### ISSUE TITLE
[Bug]Can't correctly render the mermaid flowchart

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#10330]
There is a flowchart package called [mermaid](https://mermaid-js.github.io/mermaid/#/usage). After I put `mermaid.min.js` in the folder :`**\Anki2\user\collection.media`

I add a code in my **Back Template**:

```
<script src="mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```
This is my content of card:

```
Here is another:
<div class="mermaid">
	graph TD 
	A[Client] --&gt;|tcp_123| B(Load Balancer) 
	B --&gt;|tcp_456| C[Server1] 
	B --&gt;|tcp_456| D[Server2]
</div>
```
I should reasonably be able to use this third-party packages successfully, but there is something strange going on now. But the format rendering is problematic：
![552cf30a097b0d7fea232b14b1b78c0](https://user-images.githubusercontent.com/10048069/153662027-ffddc728-7bed-443b-acbb-c8b3851c738c.jpg)

But this rendering is fine on the Anki Desktop

**Comment by mikehardy** [comment]
Hi there! There may be some rendering differences though we should be rendering the same, it is likely they (Desktop and AnkiDroid) are both using the Chrome. Have you tried https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection ?

**Comment by krmanik** [comment]
### 1. On Desktop
**a) Card template**
Note: Use `mermaid.init();` instead of `mermaid.initialize({startOnLoad:true});`

```html
<script src="mermaid.min.js"></script>

<div class="mermaid">{{Front}}</div>

<script>mermaid.init();</script>
```

**b) Note data in front**
```
graph TD A[Client] -->|tcp_123| B(Load Balancer) B -->|tcp_456| C[Server1] B -->|tcp_456| D[Server2]
```
**Result**
![image](https://user-images.githubusercontent.com/12841290/153712424-5b89b2a9-b903-4e90-a336-734b20c2404d.png)

**Now add note by turning on html** 
![image](https://user-images.githubusercontent.com/12841290/153712521-0acef439-d848-45e0-b884-cdb2fed83d51.png)

**Result**
![image](https://user-images.githubusercontent.com/12841290/153712494-ce9b8857-328a-4c8f-8a76-5439d46186c7.png)

<br><br>

### 2. On AnkiDroid
a) Export deck or test this sample deck
Extract zip file and import in AnkiDroid, the result is fine.

[Test Graph.zip](https://github.com/ankidroid/Anki-Android/files/8053661/Test.Graph.zip)

![image](https://user-images.githubusercontent.com/12841290/153715927-29b048ef-4156-4204-bdd2-459db64e4106.png)


b) Now add new note with slight change to original card, add this to `Front`
456 changed to 678 in following card

```
graph TD 
A[Client] --&gt;|tcp_123| B(Load Balancer) 
B --&gt;|tcp_678| C[Server1] 
B --&gt;|tcp_678| D[Server2]
```

The result is error.

![image](https://user-images.githubusercontent.com/12841290/153713445-79658183-e875-4b34-807b-e9bef4a1b481.png)

The same error will happen if note is edited without changing any content.
So, it only works when notes is added using AnkiDesktop with `HTML Editor` toggled on.
New cards is not rendered when added in AnkiDroid.

**Comment by Juddd** [comment]
@krmanik Thanks very much. I don't know why I cannot render successfully in ankidroid:
```
flowchart TD 
A[Client] --&gt;|tcp_123| B(Load Balancer) 
B --&gt;|tcp_678| C[Server1] 
B --&gt;|tcp_678| D[Server2]
```
![image](https://user-images.githubusercontent.com/10048069/153724566-af3684ca-229d-4a38-8fd6-f2f5cedcb538.png)

But cannot render this:
```
graph TD 
A[Client] --&gt;|tcp_123| B(Load Balancer) 
B --&gt;|tcp_678| C[Server1] 
B --&gt;|tcp_678| D[Server2]
```
![image](https://user-images.githubusercontent.com/10048069/153724617-1f215cba-ae6b-4551-897b-73c181113295.png)

Excuse me, where did you see the use of `mermaid.init();` instead of `mermaid.initialize({startOnLoad:true});`? It save me..

**Comment by Juddd** [comment]
Thanks for [krmanik](https://github.com/krmanik)'s solution

**Comment by Juddd** [comment]
Thanks for [krmanik](https://github.com/krmanik)'s solution

**Comment by Aich8868** [comment]
Just replace <br> to \n
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mermaid Diagram</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
</head>
<body>
    <div id="mermaid-container">
        
        <div class="mermaid">{{Front}}</div>
    </div>

    <script>
        // 查找 Mermaid 的所有元素并替换 <br> 为 \n
        document.querySelectorAll('.mermaid').forEach(function(el) {
            // 替换 <br> 为 \n 并设置为元素的文本内容
            el.textContent = el.innerHTML.replace(/<br>/g, '\n');
        });

        // 初始化 Mermaid.js
        mermaid.init();
    </script>
</body>
</html>`
