### ISSUE TITLE
[Bug] Problem when moving from an old Xiaomi phone to a new Xiaomi phone using Mi Mover

### ISSUE THREAD

**Issue by eu2021** [ankidroid/Anki-Android#10361]
Moving from an old Xiaomi phone (Mi5sPlus with Ankidroid 2.16alpha25) to a new Xiaomi phone (POCO X3 GT MIUI 12.5.7, with Ankidroid 2.16alpha44) using Mi Mover (the official app by Xiaomi to move to a new phone) gives a problem in the sync and it doesn't sync at all (gives a generic error message). Notice that Mi Mover did not install Ankidroid on the new phone, it only moved the Ankidroid folder.

I then uninstalled Ankidroid, and installed the playstore version and the sync was successful.

After this, I tried installing again 2.16alpha44 over the playstore version and the sync failed with this:
![image](https://user-images.githubusercontent.com/77707706/154772454-50292b91-7fc0-45a6-86e5-2cdc249860e6.png)

I solved doing this:

1. Uninstalled Ankidroid
2. Deleted Ankidroid folder
3. installed 2.16alpha44
4. sync worked

So, Mi Mover moves the Ankidroid folder to the new phone, and Ankidroid alpha can't open it. I'm reporting because Mi Mover is used by a lot of people (it's super highly rated), so it can be of general interest. Maybe the issue also happens when moving using other methods too.

BR,

**Comment by BrayanDSO** [comment]
Translation for anyone else trying to diagnose this:

`Coleção sincronizada` -> `Collection synced`

`Erro ao sincronizar dados de mídia` ->  `Error while syncing media`

**Comment by mikehardy** [comment]
Have you reported this to Xiaomi? This looks like a Xiaomi issue somehow 🤔 
That said, this may also be resolved once we use scoped storage, as it appears to be related to collection location on disk and permission to access the same.

As a possible workaround it might be possible to do more thorough checking on permissions prior to accessing the files you mention, but that would have to go on 2.15 release branch, and that is specifically not release-able any longer, so that's a dead-end.

So the best / only (?) solution is likely to add it to the list of FAQs - "After using Xiaomi Mi Mover to switch phones I cannot sync", followed by the steps you took to resolve?

**Comment by eu2021** [comment]
> That said, this may also be resolved once we use scoped storage, as it appears to be related to collection location on disk and permission to access the same.

If I understood correctly, the solution is already planned. So, I will close the bug here, and transcribe the text from the image, to help people searching for it:
java.io.FileNotFoundException:/storage/emulated/0/AnkiDroid/tmpSyncFromServer.zip (Permission denied)
