### ISSUE TITLE
Tests: Use hamcrest.io matchers for files

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10387]
http://hamcrest.org/JavaHamcrest/javadoc/2.2/org/hamcrest/io/FileMatchers.html is now usable in the codebase. Let's use it to improve tests. 

<details><summary>old</summary>

I'd really like to see more custom Hamcrest matchers in the codebase

For example: "file exists" would be useful, so we can reduce the verbosity of error messages.

And something along the lines of `hasSingleElementEqualTo`

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10385#issuecomment-1049199502_

</details>

**Comment by BrayanDSO** [comment]
@david-allison hamcrest 2.x+ has [io.FileMatchers](http://hamcrest.org/JavaHamcrest/javadoc/2.2/org/hamcrest/io/FileMatchers.html) which have a `anExistingFile` matcher and some others already.

AnkiDroid current version is `org.hamcrest:hamcrest-all:1.3`

Assuming staying with hamcrest 1.3 was not a decision of the mantainers, the dependency bot probably didn't catch the update because now all classes are packaged as `hamcrest` instead of `hamcrest-all`

**Comment by david-allison** [comment]
Awesome! I'd accept that as a change. Hamcrest was introduced well before my time. Check with @mikehardy, but definitely an oversight here

**Comment by mikehardy** [comment]
Irony that dependabot lost the plot there. In general I am probably too obsessive/compulsive with keeping dependencies up to date so now I'm already anxious that we're not ;-). Please update as possible/needed!

**Comment by BrayanDSO** [comment]
Some places where this issue can be applied: [BackupManagerSimpleTest](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt) and [NoteServiceTest](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java)

**Comment by david-allison** [comment]
I'm happy to say @BrayanDSO has set a precedent and this can be closed as 'Done'
