### ISSUE TITLE
[JS API]: Know if `{{tts}}` is supported.

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10443]
As a developer, I would like to know if `{{tts}}` is supported so I can determine whether to use `AnkiDroidJS.ankiTtsSpeak`, or rely on the system TTS.

I would like to be able to call this functionality from the JavaScript API in a card

**Comment by krmanik** [comment]
I think the proposed PR does not solve the current problem.
The problem is to check if `{{tts}}` is supported or not.
But it also use android's `TextToSpeech` so the return value about status should be from `ReadText.kt`

https://github.com/ankidroid/Anki-Android/blob/fd654e8c18c9cfdabe1b7a39fa356e5f89c8b190/AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt#L251

**Comment by david-allison** [comment]
I specifically want to know if the `{{tts}}` field modifier is supported (AnkiDroid doesn't use this yet). 2.16 should return "no" until I've completed and enabled it from the Rust Backend.

This will allow people to use `ankiTtsSpeak`, and have it disabled once the Anki-compatible `{{tts:}}` is available

**Comment by krmanik** [comment]
_I thought it would be easy to implement but I don't think so now._

First it needs to check if the card template contains `{{tts:}}` string or not, if contains then return  false. 
Is any other implementation idea?

**Comment by david-allison** [comment]
> _I thought it would be easy to implement but I don't think so now._
> 
> First it needs to check if the card template contains `{{tts:}}` string or not, if contains then return  false, or we know which version of AnkiDroid it is supported, so may be the version should be used.
> Is any other implementation idea?

Just return false for now

**Comment by krmanik** [comment]
I have pushed the changes to the PR.
