### ISSUE TITLE
[Bug] language change not properly in AnkiDroid(Activity) Toolbar 

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#10575]
###### Reproduction Steps

1. change the app language 
2. Go to AnkiDroid(Activity) see at Toolbar 
3. min word do not change according to langauge 
4. close the app and reopen the app   then see at Toolbar min word change according to language 

###### Expected Result
Language change 

###### Actual Result
language change after reopen the app

###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha51

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi Y3

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Y3 Build/QKQ1.191008.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.70 Mobile Safari/537.36

ACRA UUID = 90e27e37-0c05-486f-9e51-42406bd8de0f

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
<img width="179" alt="Screenshot 2022-03-19 193415" src="https://user-images.githubusercontent.com/65972015/159124229-396e32e0-9714-4736-8013-95712f97f097.png">

<img width="162" alt="Screenshot 2022-03-19 193554" src="https://user-images.githubusercontent.com/65972015/159124427-d56e9294-b25b-4eb5-a0f5-7fbff43213fc.png">

**Comment by Prince-kushwaha** [comment]
@david-allison can i work on this issue

**Comment by mikehardy** [comment]
This is I think a limitation of android for some API levels.
You did not include the debug info for the device you reproduced this on, that's really important

**Comment by david-allison** [comment]
We might as well restart the app on language change. 

There's so many potential issues with a lot of overhead, and little benefit from getting it perfect.

**Comment by mikehardy** [comment]
Sure, except that's basically impossible to do reliably: https://stackoverflow.com/questions/6609414/how-do-i-programmatically-restart-an-android-app (and ProcessPhoenix doesn't appear to work well on Android 12 real devices etc)

Perhaps just a dialog to the user?

**Comment by Prince-kushwaha** [comment]
@mikehardy i added the debug info in  issue

**Comment by Arthus** [comment]
> There's so many potential issues with a lot of dev overhead, and little benefit from getting it perfect.

Exactly. If I remember correctly (it has been a few years ago that I "fixed" the language setting :) ) this is on top activity and it needs to be restarted for the new strings to be used. So restarting the whole app instead of just this activity would be nearly the same amount of work/code.
And as this is a single string that needs a restart once after changing the language I didn't think it was worth it. Most (all?) people only change Ankidroids language once or at least very rarely.

And immediately restarting the app on language change might also be unwanted by many users. So instead a popup dialogue would still be necessary. ("AnkiDroid needs to be restarted. Do you want to restart now?")
The easiest thing imho would be to just give a notice in (both? old and new) language, that the app needs to be restarted manually for the change to take full effect.

**Comment by mikehardy** [comment]
>  The easiest thing imho would be to just give a notice in (both? old and new) language, that the app needs to be restarted manually for the change to take full effect.

This is a nice practical solution, in my opinion, emphasis on "full" effect if we do a dialog, because most stuff does work, but of course a few strings don't (as this issue indicates)
