### ISSUE TITLE
[Bug] Card browser loads filtered/custom study decks only if previously selected

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10684]
###### Reproduction Steps

1. Have a filtered/custom study deck
2. Go to card browser
3. Tap the Deck spinner

https://user-images.githubusercontent.com/69634269/161396487-d3ffd3a9-0a8d-4336-98b8-eaf7967d1a35.mp4

###### Expected Result

Filtered decks and (maybe) custom decks dialog to appear on the deck selection dialog (anki desktop behavior)

![2022_04_02-15_30_43](https://user-images.githubusercontent.com/69634269/161396539-65e162ff-4b53-401d-b023-e743159fc3cf.png)

###### Actual Result

They only appear initially if selected on the deck picker, but not on the deck selection options, so it vanishes if user select another deck

![2022_04_02-15_28_40](https://user-images.githubusercontent.com/69634269/161396699-8cbce847-a2d6-4e08-8e7d-cffd440912a8.png)

###### Debug info
```
AnkiDroid Version = 2.16alpha54

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 037bbc86-38a4-4ad7-9c42-05870e9b6086

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
This happens because in [`DeckSpinnerSelection.displayDeckSelectionDialog()`](https://github.com/ankidroid/Anki-Android/blob/9e344fd9453b76e4deb4378f8ae2c5b5a8c3ef37/AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt#L228) we declare a non dynamic filter for the list of decks displayed and a filtered deck is dynamic so it is removed. I don't have sufficient domain knowledge to know if this filter is really needed or is some leftover. The method `DeckSpinnerSelection.displayDeckSelectionDialog()` is also called from `NoteEditor`.
@mikehardy @david-allison Any thoughts on this?

**Comment by MrPenguins** [comment]
Hi, I would like to work on this issue!
