### ISSUE TITLE
Natural Sorting for DeckList

### ISSUE THREAD

**Issue by theHamsta** [ankidroid/Anki-Android#10695]
**Is your feature request related to a problem? Please describe.**
I have a lot of decks numbered by lesson name in my deck list (`DeckPicker.java`). I would like them sorted using natural sort order https://en.wikipedia.org/wiki/Natural_sort_order instead of no sorting or alphabetical sorting. It would be nice if there were an option to enable this.

I understand the `dueList` is sorted in the order I ought to do them. A sorting option would be nice though.

**Describe the solution you'd like**
DeckList UI should sort the decks.

**Describe alternatives you've considered**
N/A I could live with unsorted lists.

**Additional context**

I've created a draft PR to describe what I would like to change (no experience with any Android project). Likely not the best solution.

I would like to have my deck list sorted like
![anki_with_natsort](https://user-images.githubusercontent.com/7189118/161443675-47c2955d-751a-47a9-bbb2-a1f4d29ff4ff.png)
and not like
![anki_before](https://user-images.githubusercontent.com/7189118/161443676-d2db47bc-cceb-4637-a83b-4ed649891162.png)

**Comment by mikehardy** [comment]
I'm not closing this because I don't like the idea, I'm closing this because it's not actionable here. It appears based on commentary in related PR (thanks for proposing it! sincerely) that this needs to be discussed at https://forums.ankiweb.net and would be a lower-level change. Also per-commentary if it is accepted like that upstream in Anki Desktop's rust library, then we would get the change here later as we move forward ever so slowly with new schemas / new rust code ingestion
