### ISSUE TITLE
[Suggestion] Show "Deck options" icon on Actionbar of Deck overview screen instead of its three dot menu icon

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10868]
**Is your suggestion related to a problem? Please describe.**

AnkiDroid has already had the icon for "Deck options" by #10735, and there is enough space on Actionbar of Deck overview screen to add some more icons; nevertheless, the item of "Deck options" has still been imprisoned solely in the three dot menu of the screen.
![image](https://user-images.githubusercontent.com/10436072/163572902-1dede600-bd55-47d6-8f89-230533468323.png)

**Describe the solution you'd like**

Show "Deck options" icon instead of the three dot menu icon.
![image](https://user-images.githubusercontent.com/10436072/163574216-8aabcfc5-96e5-4a69-a4a9-89eacff3e6d2.png)

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by siddharthsingh025** [comment]
pls can you suggest me" Deck overview " activity file name .......i m new to this codebase , so it seems complex to me to find something

**Comment by david-allison** [comment]
`StudyOptionsFragment`

**Comment by siddharthsingh025** [comment]
# Error : #10868  *SOLVED ✅ * : Show "Deck options" icon on Actionbar of Deck overview screen instead of its three dot menu icon

## Output i get : 

<img width="430" alt="Screenshot 2022-04-17 at 4 54 57 PM" src="https://user-images.githubusercontent.com/87073574/163713426-77fcea1b-7960-4773-8c61-32caa9ed6937.png">

<img width="450" alt="Screenshot 2022-04-17 at 4 55 06 PM" src="https://user-images.githubusercontent.com/87073574/163713423-75643cd8-9ad4-478a-95fc-a3389e2ca255.png">


###  **Changes i do :** 
_1. Define new style with New icon_  { https://github.com/siddharthsingh025/Anki-Android/blob/c43ae29e1ad9155e0587789534b8aa9250773b31/AnkiDroid/src/main/res/values/styles.xml#L196 }

    
    <style name="MyOverflow" parent="android:style/Widget.Holo.ActionButton.Overflow" >
    <item name="android:src">@drawable/ic_baseline_tune_24</item>
    </style>

_2.Then copy old actionbar style and ADD our new overflow style_  { https://github.com/siddharthsingh025/Anki-Android/blob/c43ae29e1ad9155e0587789534b8aa9250773b31/AnkiDroid/src/main/res/values/styles.xml#L121 }

    
    
    <style name="OverflowStyle" parent="Base.ThemeOverlay.AppCompat.ActionBar">
    
    <item name="android:textColorPrimary">@color/white</item>
    
    <item name="android:textColorSecondary">@color/white</item>
    
    <item name="popupTheme">@style/ActionBar.Popup</item>

    
    <item name="android:actionOverflowButtonStyle">@style/MyOverflow</item>

    </style>


_3.  Add our new theme {"OverflowStyle "}  to  fragment page of DeckOverview like :_  {https://github.com/siddharthsingh025/Anki-Android/blob/c43ae29e1ad9155e0587789534b8aa9250773b31/AnkiDroid/src/main/res/layout/studyoptions_fragment.xml#L5}

    android:theme="@style/OverflowStyle”

**Comment by snowtimeglass** [comment]
Thanks for the fix!
