### ISSUE TITLE
Changing the color of toggle switches to blue, from dark green which is the default color now in preferences library

### ISSUE THREAD

**Issue by UvrajSB** [ankidroid/Anki-Android#10909]
I was trying to change the color of the toggle switches but wasn't able to find a way through the preferences library yet and then I observed that even the checkboxes we were using didn't have the Ankidroid blue color

_Originally posted by @UvrajSB in https://github.com/ankidroid/Anki-Android/pull/10857#discussion_r851192164_

**Comment by TacoTheDank** [comment]
I'm pretty sure that the preference stuff is themed according to the colorAccent.

**Comment by BrayanDSO** [comment]
Yep. I think changing the whole `colorAccent` to blue would make things more beautiful.
<details><summary>Current colorAccent</summary>

![Screenshot_20220417-180751_AnkiDroidH](https://user-images.githubusercontent.com/69634269/163732222-a6788498-7e9a-4226-a8af-e44075a3b4ca.png)


</details>

<details><summary>@color/material_light_blue_700</summary>

![Screenshot_20220417-180705_AnkiDroidH](https://user-images.githubusercontent.com/69634269/163732183-9d1ff994-ebf7-424d-ad3c-ebf0fdc9ae4a.png)

</details>

<details><summary>@color/material_light_blue_800</summary>

![Screenshot_20220417-181003_AnkiDroidH](https://user-images.githubusercontent.com/69634269/163732217-a16bdf8b-3c0f-424f-a898-53ba82111d5d.png)

</details>

I'd vote for `@color/material_light_blue_800` since it passes accessibility scanner

**Comment by UvrajSB** [comment]
> Yep. I think changing the whole `colorAccent` to blue would make things more beautiful.
> 
> Current colorAccent
> @color/material_light_blue_700
> @color/material_light_blue_800
> I'd vote for `@color/material_light_blue_800` since it passes accessibility scanner. Changes to the other themes need to be assessed as well, if `colorAccent` is going to be changed

I feel for other themes the colorAccent is well and good,

**Comment by TacoTheDank** [comment]
Still waiting, I suppose.
