### ISSUE TITLE
Can one change the Anki Design (not card design) with CSS?

### ISSUE THREAD

**Issue by pat-richter** [ankidroid/Anki-Android#11360]
Question is self explaining, I think.

I know there are some options in Settings > Appearance, but these are minimal.

Forking and rebuilding with changed options is possible, of course. But I hope there is a solution with less afford.

Kind regards
Patrick

**Comment by mikehardy** [comment]
Question is not self-explanatory actually - you need to specify what elements you want to change.
If you mean "the reviewer experience", you might like the combination of JS/CSS capabilities along with our JS API, when used in "immersive / full-screen" mode. That lets you program a completely different reviewer if you like.

Here's a handle on that https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-want-add-ons-in-ankidroid

Otherwise, the general answer to the question "can I change the anki design" is "nope" - those are android screens specified with XML layouts in the app and you'll have to fork+modify+build if you want to really change things up.

Or, you could use the AnkiDroid API (a more low-level android system thing then the JS API loaded in the reviewer) and you can make a whole separate app that just uses AnkIDroid for scheduling / collection management, like the app AnkiReview on our list of API apps

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API
https://github.com/ankidroid/Anki-Android/wiki/Third-Party-Apps

Hope this helps!
