### ISSUE TITLE
Very slow debug builds - contains solution sketch, needs dev

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#11575]
On my Linux machine with the latest main, adding a comment to a file and building again takes close to a minute, making the code/build/test cycle painful:

```
Time metrics:
  GRADLE_TASK_ACTION: 0.16 s
  GRADLE_TASK: 48.76 s
    CLEAR_OUTPUT: 0.03 s
    BACKUP_OUTPUT: 0.03 s
    CLEAR_JAR_CACHE: 0.00 s
    NON_INCREMENTAL_COMPILATION_IN_PROCESS: 48.37 s

Build attributes:
  REBUILD_REASON: IN_PROCESS_EXECUTION

Total time for Kotlin tasks: 48.62 s (99.7 % of all tasks time)
Time   |% of Kotlin time|Task                               
48.62 s|100.0 %         |:AnkiDroid:compileAmazonDebugKotlin
```

If I remove the in-process change in f5ecb05efc3117238cbd42935542176d4436ee5f, small changes like adding a new function are dramatically faster:

```diff
diff --git a/gradle.properties b/gradle.properties
index b0c4f10e4..5975d5d88 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -9,7 +9,7 @@

 # Specifies the JVM arguments used for the daemon process.
 # The setting is particularly useful for tweaking memory settings.
-org.gradle.jvmargs=-Xmx2048M -Dkotlin.compiler.execution.strategy=in-process -Dfile.encoding=UTF-8
+org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

 # AndroidX package structure to make it clearer which packages are bundled with the
 # Android operating system, and which are packaged with your app's APK
```

```
Time metrics:
  GRADLE_TASK_ACTION: 0.19 s
  GRADLE_TASK: 2.77 s
    BACKUP_OUTPUT: 0.05 s
    CONNECT_TO_DAEMON: 0.00 s
    CLEAR_JAR_CACHE: 0.00 s
    CALCULATE_OUTPUT_SIZE: 0.00 s
    RUN_COMPILER: 0.26 s
      INCREMENTAL_COMPILATION: 0.25 s
        STORE_BUILD_INFO: 0.00 s
        IC_CALCULATE_INITIAL_DIRTY_SET: 0.02 s
          IC_ANALYZE_CHANGES_IN_DEPENDENCIES: 0.02 s
          IC_ANALYZE_CHANGES_IN_JAVA_SOURCES: 0.00 s
          IC_ANALYZE_CHANGES_IN_ANDROID_LAYOUTS: 0.00 s
          IC_DETECT_REMOVED_CLASSES: 0.00 s
        IC_UPDATE_CACHES: 0.01 s
        INCREMENTAL_ITERATION: 0.20 s
        IC_WRITE_HISTORY_FILE: 0.00 s
  CODE_ANALYSIS: 0.12 s
  CODE_GENERATION: 0.02 s

Build performance metrics:
  CACHE_DIRECTORY_SIZE: 5563721
  SNAPSHOT_SIZE: 447

Total time for Kotlin tasks: 0.82 s (29.7 % of all tasks time)
Time  |% of Kotlin time|Task                               
0.82 s|100.0 %         |:AnkiDroid:compileAmazonDebugKotlin
```

Tested with

```diff
diff --git a/gradle.properties b/gradle.properties
index 26b3c271c..5975d5d88 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -30,3 +30,6 @@ org.gradle.vfs.watch=true

 # Opt in to gradle 8 behavior, silence warning for now. Remove with AGP8+
 android.disableAutomaticComponentCreation=true
+kotlin.build.report.enable=true
+kotlin.build.report.verbose=true
+
```

**Comment by BrayanDSO** [comment]
I've noticed a build lag as well  recently and the timing fits with f5ecb05efc3117238cbd42935542176d4436ee5f

**Comment by mikehardy** [comment]
Yes - I noticed that myself while working on the change. I'm struggling to balance the ability to fit in CI machines now that we have so much Kotlin we're blowing up the JVMs running the build in CI completely (total CI failure) vs the speed here.

I swung the pendulum away from "CI unit tests fail" which is nice but seem to have gone too far in the "but the consequence is crap performance" direction.

I'll see if I can retune, or perhaps only use the in-process kotlin compile for CI and leave it out-of-process for non-CI

If someone had walked up to me as a comp sci student in 1995 and said "yeah but just building your code will take maybe 7GB of RAM to have acceptable performance" I would have told them they are ridiculous. And they are...

**Comment by mikehardy** [comment]
Okay, a quick mitigation (or perhaps final solution) sketch is:

- switch from defining kotlin execution strategy in gradle.properties to configuring it in groovy for compile task - https://kotlinlang.org/docs/gradle.html#defining-kotlin-compiler-execution-strategy

> The compilerExecutionStrategy compile task property.

Do that conditionally based on our CI variable that already exists 
https://github.com/ankidroid/Anki-Android/blob/167a21e180e4b3924bfedecce390db4ad66b0488/build.gradle#L113

It's possible to instrument a touch while testing to make sure the conditional is working https://github.com/ankidroid/Anki-Android/blob/167a21e180e4b3924bfedecce390db4ad66b0488/build.gradle#L107 so if you force ciBuild to be true you get positive confirmation, and if you `./gradlew --stop` so there is nothing gradle running then you run the build you should be able to see the kotlin separate JVM start up (or not) to make sure the compile task (or in groovy terms "task with property KotlinCompile" or something) is targeted correctly

Following that, success is defined by monitoring test runs of windows unit test to make sure timing is same as before (and it's not flaky) indicating we haven't blown up system available memory though, in combination with local runs that indicate kotlin incremental compile is working again

I would love if someone took this up, I won't have time for a while - but since I created the problem I wanted to at least write down what the domain knowledge was, now it's just implementation + testing, anyone should be able to :pray:
