### ISSUE TITLE
Individual preferences analytics

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11642]
Briefly mentioned in Discord by @BrayanDSO

This hasn't been accepted yet

**Comment by david-allison** [comment]
I'm in favour of this, as long as we're only tracking taps to understand usage data. 

As an extension, we may also want to track 'value changed'. I tap 'Custom Sync Server', but never set it.

An initial tap implies interest in the setting. A value change implies that it's useful and the UX is reasonable.

We need to ensure that this is only fixed preference keys, that the keys are not dynamic, and are not personally identifiable.

My initial preference would be to limit this to keys defined in: https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/values/preferences.xml

**Comment by BrayanDSO** [comment]
> I'm in favour of this, as long as we're only tracking taps to understand usage data.
> 
> As an extension, we may also want to track 'value changed'. I tap 'Custom Sync Server', but never set it.
> 
> An initial tap implies interest in the setting. A value change implies that it's useful and the UX is reasonable.
> 
> We need to ensure that this is only fixed preference keys, that the keys are not dynamic, and are not personally identifiable.
> 
> My initial preference would be to limit this to keys defined in: https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/values/preferences.xml

Agreed with all points

**Comment by mikehardy** [comment]
Likewise - as long as we are not tracking PII it meets my personal mission statement for analytics (and what we tell users) which is "steering development by discovering what is actually used".

It appears currently we are logging "screen" hits with a screen name override for the different fragments.
I think it would be reasonable to log a Preferences Event 

(https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#events) with category preferences, label the specific preference and action either "view" or "customize" or similar

The most important thing once a decision has been made to gather analytics is that it is *reportable* (and thus, actionable) which implies that analytics hit information design is important up front, then making sure things are constants is the code result, so that the hits do not change over time ever, and are thus reportable / aggregate correctly over time.

That may be obvious, but since it's the only really important thing, it's worth stating. Anything reasonable that meets the requirement for good reporting works for me

**Comment by BrayanDSO** [comment]
How much should we track the changed preference values?

Of course we won't track any text preferences, e.g. custom sync server, in order to keep privacy.

But we could track which option is selected in a ListPreference, such as themes. This could help deciding if an option like putting the answer buttom at the top is a popular option. Since an [event value](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ev) must be an integer, the value could be the list index. 

If the items of a preference ever change, the preference key can be changed so the results are separated from the old ones and  more updated

Boolean and numeric values are easy to track as well
