### ISSUE TITLE
All uses of legacy schema conditionals need investigation and elimination so only V16+ schema remains

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#11737]
We need to eliminate the use of conditionals that switch between two different implementations of the same functionality (one based on older Java / Ankidroid/libanki code, one based on new Rust / Anki-Android-Backend code)

The expectation here is that each instance of the conditional usage is likely going to need it's own PR, similar to how we fix KotlinCleanup annotations

Just note the one you are looking into here in a comment then propose a PR that re-focuses that implementation area so it's Rust-based only through the Anki-Android-Backend

###### Reproduction Steps

1. grep code for RustCleanup, RustV1Cleanup or BackendFactory.setDefaultLegacySchema or BackendFactory.defaultLegacySchema
2. 
3. 

###### Expected Result

There should be no hits, because all the necessary work to move on to the V16+ schema (from #11644) is complete

###### Actual Result

There are quite a few hits because we have not fully integrated V16 schema functionality

###### Debug info

Any version after integration of #11644 today

**Comment by dae** [comment]
We can't start stripping out those lines just yet I'm afraid. The new backend code is all-or-nothing - users can't incrementally opt into it, since it requires DB upgrades that the legacy AnkiDroid code does not understand. The first step will be identifying the remaining areas of the app that fail or are not fully functional when the new schema is activated (eg card template editor), and fixing those issues by adding more code behind extra BackendFactory.legacyDefaultSchema checks.

Once AD is fully functional with the new schema activated, we'll want to encourage further testing, and eventually get a play store release out where the new schema is the default. Once you're sufficiently happy that there's no need to go back to the old path, only then will it be possible to start removing the old code (and it will be a sea of red - there will be lots of code in libanki that can be cut, and all the legacy paths on the GUI end).

**Comment by mikehardy** [comment]
:thinking: Hmm - perhaps we need a new annotation that is more like "RustNewSchemaMinimum" to mark the cases where we simply must do something before we can even start deploying the new schema / toggling it on by default. There are a few areas where I think both can coexist, but for the areas where we have to forward-port or it just breaks, that's a good list to know + mark up, isn't it?

**Comment by dae** [comment]
Yes, that would be more useful in the short term - maybe `@BlocksSchemaUpgrade`?

**Comment by mikehardy** [comment]
works for me, yeah

**Comment by dae** [comment]
Suggest this is closed in favour of #11882

**Comment by mikehardy** [comment]
Happy to do so - we were considering making a `@BlocksSchemaUpgrade` annotation per comments above, is that still useful? If so, it's not indicated in 11882 so it might be nice to be prescriptive in the checklist on an annotation like this being used. If you're already past that, then ignore me and I need to get that anki PR merged then the backend PR merged and a release kicked out so your second batch of work sees the light

**Comment by dae** [comment]
Annotation is added in #11740

**Comment by mikehardy** [comment]
Nice! Going to say "you're already past that" then...
