### ISSUE TITLE
migrate to material design 3

### ISSUE THREAD

**Issue by andsofine** [ankidroid/Anki-Android#11755]
productivity apps usually have a fresh design that has a positive impact on the user experience so I thought this would be a great improvement

**Comment by mikehardy** [comment]
We're in the middle of a lot of cross-cutting (whole app) changes and UI changes are not the highest priority unfortunately.
Typically UI changes in particular here receive lower priority because while new users want a "fresh" look, existing users resist change.

That said, if you were willing to do the work and kept the changes as minimal as possible, accepting a PR doing this (starting with one screen perhaps?) would be interesting to see what it means on one screen with screenshots before/after etc

**Comment by dae** [comment]
Can be closed?

**Comment by dae** [comment]
(in case it's not clear, the latest code has already updated to MD3)

**Comment by david-allison** [comment]
I believe we're still on Material Design 1. The recent update was material dialogs.

https://github.com/ankidroid/Anki-Android/blob/1fb9cac4c7d3b5746f573ec8b5056068c9e1716e/AnkiDroid/build.gradle#L264

**Comment by mikehardy** [comment]
Hi there! Agreed on productive comments - sarcasm is corrosive in text-only environments, and attempts at humor backfire. And that's assuming the best on the comment.

So to business: it's important not to conflate "material design 3" with "version of material design library dependency"

The material design library is at 1.6 and will go to 1.7 shortly: https://github.com/material-components/material-components-android/releases

That's independent of what Google launched in 2022 Google I/O as "Material Design 3" aka, "Material You" or however they want to brand it: https://m3.material.io/

For the original poster I want to emphasize that this is brand new, and even major ecosystems like react-native are just now getting their libraries worked up for it - the ones that are *all about design* like, react-native-paper: https://callstack.github.io/react-native-paper/introducing-v5-with-material-you.html / note still in release candidate phase https://github.com/callstack/react-native-paper/releases

...which should help to just set some perspective

And I want to reiterate:

> We're in the middle of a lot of cross-cutting (whole app) changes and UI changes are not the highest priority unfortunately.
Typically UI changes in particular here receive lower priority because while new users want a "fresh" look, existing users resist change.
> 
> That said, if you were willing to do the work and kept the changes as minimal as possible, accepting a PR doing this (starting with one screen perhaps?) would be interesting to see what it means on one screen with screenshots before/after etc

There should be no expectation there will be progress here without effort put in to it. It's just "nice to have" versus the other work in progress here - no current developers have expressed an interest or done any work, so currently there's nothing planned here

The way to move it forward is to examine a screen for differences between it's current design and whatever Material Design 3 proposes, then tweak the layout to conform to Material Design 3. Propose the PR that implements the changes along with screen shots before and after. Layout a plan to convert the rest of the screens similarly, then do the work. A series of PRs like that would be amazing

**Comment by iAyyham** [comment]
Hello..

It's been 3 years since this issue was closed. Are there any plans of repoening it?

Someone on the forums also expressed interest in this and seems to have already tried implementing it. I was just wondering if we can have it (at least for now) as something complementary, cuz tbf it's a very smooth UI in comparison with the current UI.

Thanks

**Comment by david-allison** [comment]
We're using Material 3. We had significant pushback with using Material You on the widgets due to manufacturers not supporting it.

In general, the scope of this issue is too wide to be workable

If there are specific improvements we should make, we can tackle them on a case-by-case basis in the forums: 

https://forums.ankiweb.net/c/ankidroid/suggestions/23

**Comment by iAyyham** [comment]
I apologize for any confusion. I meant material 3 expressive :)

**Comment by david-allison** [comment]
Even Google haven't fully transitioned to Material Expressive.

We'll likely gradually move there, picking & choosing components which make sense

**Comment by iAyyham** [comment]
Oh alright that makes perfect sense. Thank you for your response!
