### ISSUE TITLE
study reminders/ notifications/ notification cards

### ISSUE THREAD

**Issue by jaxxor44** [ankidroid/Anki-Android#11949]
I have a hard time dedicating a BLOCK of time to studding a bunch of cards in a row.
Its far easier for me to study a card here, a card there, in the moments in between my life events.

Ideally, Id get a notification when a card comes due (if the deck has notifications enabled).
The notification can open to the due card in Anki-droid, or
The notification displays the card, with buttons for "Good","again" and so on.

Thanks for making and supporting this great system.
Anki in general has saved my bacon with studying.

**Comment by mikehardy** [comment]
Hi there! Unfortunately this isn't practical, the notification display options provided by the system are not capable of handling the full set of Anki card formatting and there's no way to map between them.

The same applies to requests for a card on lock screen or similar, they don't offer sufficient display capacity

**Comment by mikehardy** [comment]
If you enabled notifications it should open to the deck that's got the card due, in review mode though?

**Comment by ShootingKing-AM** [comment]
> Hi there! Unfortunately this isn't practical, the notification display options provided by the system are not capable of handling the full set of Anki card formatting and there's no way to map between them.
> 
> The same applies to requests for a card on lock screen or similar, they don't offer sufficient display capacity

Maybe render the card html -> picture (png) -> show png as notification. If clicked on png, open card, else if clicked on difficulty buttons, save answer ?

This feature can take learning truly to another level, since its common to find people nowadays with low disicipline and low attention span and immersed in their phone. Also makes learning thorughout the day instead of blocking some time for memorization.

Thanks !
