### ISSUE TITLE
Crop experience got worse

### ISSUE THREAD

**Issue by zorandz** [ankidroid/Anki-Android#11955]
Hi, I love the app, using it for years extensively, but new version has a different grid type crop that disables me from cropping intended part of the picture, it allows to shrink only so much. This is a rare case of an app in my experience that has gotten worse...

Anyway, great job overall, keep doing what ya doin'

**Comment by mikehardy** [comment]
Hey there! There was a reason for that, the old crop functionality had become unmaintainable with a lot of changes in the underlying Android system APIs, and there's a new crop library which actually *improves* things in that for new android versions it actually works (the old system did not work at all for new android versions!). #8072 / #9159

But I'm not saying your use case or complaint is invalid - just that now that we are using a separate library instead of busted internal code, you should bring this up over at the related library: https://github.com/ArthurHub/Android-Image-Cropper - if they don't have an issue tracking it already. And there is always the possibility that library actually allows really tight zoom+crop but maybe we aren't using it correctly? If so obviously we can reopen here and adjust our API usage

**Comment by taurit** [comment]
Hi! I also use the _crop_ functionality in AnkiDroid a lot, and find the experience annoying. When I cannot crop pictures to the intended size, the quality of the created deck suffers. So, I dug a bit...

## The problem

The size of cropped image is limited by several parameters, for example [the default values in the library used](https://github.com/ArthurHub/Android-Image-Cropper/blob/2a4a425668bfff1329dd5bfb1b80b0829bb4cc67/cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageOptions.java#L257) are:

```
    minCropWindowWidth = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 42, dm);
    minCropWindowHeight = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 42, dm);
    minCropResultWidth = 40;
    minCropResultHeight = 40;
```

On my smartphone, the cropping window in the crop activity cannot be smaller than 168px * 168px, regardless of the zoom. It corresponds to 168px=42*4. The experience is visible in the screenshot-I cannot crop to a smaller fragment, even though the area covers much more pixels than 40px * 40px at that zoom level:

![crop-limit-400](https://user-images.githubusercontent.com/7702278/210855145-2ac50754-f36e-46eb-81ee-18b82766a286.png)


This is especially annoying when users want to crop to a wide or a high fragment. It might be impossible to crop the exact part of image they want.

## Root cause

AnkiDroid uses the default parameter value for [MinCropWindowWidth/Height](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Visual-Customization#mincropwindowwidthheight), which results in the limit.

## Possible solution

AnkiDroid could choose to change the parameter value, which would mean a tradeoff:

- Advantage: users would be able to crop the image to any size they want
- Disadvantage: the crop window might be rendered "ugly" if cropped width or height is too small. This would look like below. (I'd personally prefer that than not being able to crop, though!)

The default limit ensures the box renders without artifacts:

![crop-with-constraints](https://user-images.githubusercontent.com/7702278/210854793-005b448c-f0c3-427d-bf5a-c27679307377.png)

But if we reduce the limit, it might render like this (though it seems still functional):
![crop-with-constraints-removed](https://user-images.githubusercontent.com/7702278/210854567-935a97d4-82c4-4153-8bee-e75a665c3fc1.png)

## Next steps

Maybe this issue could be re-opened with the new knowledge?

I cannot code in Kotlin, but the proof-of-concept worked. This seems to require change of just few lines in **BasicImageFieldController.kt** to override the default value of parameter in the `CropImageOptions()` object. And testing properly, of course.
