### ISSUE TITLE
[Bug] Long Synchronization, then failure

### ISSUE THREAD

**Issue by the-nilosch** [ankidroid/Anki-Android#11967]
###### Reproduction Steps

Happens also on a freshly installed version:

1. I synchronize my flashcards with AnkiWeb
2. It downloads all the media files, even though they should be already on the phone. It also takes ages (ca 20 mins for my flashcards) 
3. If not aborted, the following error is shown:
Collection synchronized. 
Problems with synchronizing media files
java.io.IOException: write failed: ENOENT no such file or directory

![20220802_103830](https://user-images.githubusercontent.com/67461666/182331305-3300a2e3-f7d2-4556-bfb1-47387773b9b3.jpg)

###### Expected Result

Short Synchronization

###### Actual Result

See above

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi @the-nilosch ! Sorry this is happening.

For others where this has happened, this has been fixed by making sure that you have one client with all the data correct, abandoning your old AnkiWeb account, making a new AnkiWeb account, syncing up to that, then syncing down from (the new account) to AnkiDroid.

However, you have skipped the debug info part of the issue template so I'm not sure of your version. There is also a chance this is helped by using a test / .A release of our 2.16alphas https://github.com/ankidroid/Anki-Android/releases

At the same time, until #5304 is fixed there will be very slow performance on the media sync. That's unfortunate and there is no good workaround right now, you just have to sync quite a few times until all the media is down. Once the media actually is in sync (it could take quite a few times but will get closer each time...) then sync will be fast

**Comment by kodovanie** [comment]
@mikehardy Hi, I would like to ask, are the new version also going to be available on Google Play? I have the latest version from there 2.15.6 (it says it is the last update from 14/07/2021). Using Android version 12. Thank you.

**Comment by mikehardy** [comment]
@kodovanie yes, but not for some time yet. When #5304 is done we will start releasing betas through Google then an official release, yes

**Comment by kodovanie** [comment]
@mikehardy Thanks for letting me know. I was afraid that I could have an issue with my phone.
