### ISSUE TITLE
Better internal database

### ISSUE THREAD

**Issue by reyaz006** [ankidroid/Anki-Android#12025]
It appears the performance is still not fixed after many years. PC app is miles ahead of Android app. Importing, syncing, even deleting decks - all take literally hours on Android and seconds on Windows (after playing with a few 100~200 MB decks).

`"This may take a long time"` message is something that should not be there (it's also not displayed before some of the longest operations are executed). Syncing from the internet appears to be x2~x10 faster than importing from the local deck. The Wi-Fi is not slow, the smartphones are not slow, RAM is not the problem, CPU is not the issue. It seems like the real issue is unnecessary repeating of several operation loops. Maybe the app tries to unpack the whole .apkg every time it fetches a single file from it, or it rebuilds the database on each commit, or something like that.

Would it be possible to build a prototype version that relies on files alone instead of the database? I feel it would work much faster because it will leave much less room for mistakes.

**Comment by mikehardy** [comment]
I find this issue mildly combative versus collaborative

> It appears the performance is still not fixed after many years

This despite your voluminous contributions on the same, oh wait: https://github.com/reyaz006 there are none. I guess it does not just fix itself!

> RAM is not the problem

Ironically, this is one of the problems. Did you know that each app on the Android operating system receives very limited RAM despite the system potentially having bunches? It's true

> CPU is not the issue

Interestingly, this is one of the problems. Otherwise why would anyone *have* a laptop instead of just a screen they attach to their phones? Perhaps the CPUs on phones are not actually that fast?

> t seems like the real issue is unnecessary repeating of several operation loops. Maybe the app tries to unpack the whole .apkg every time it fetches a single file from it, or it rebuilds the database on each commit, or something like that.

It appears you have made no actual effort to profile the operations you find slow, or you would not posit what the real issue is without then doing a "maybe" then a "or something like that"?

We'll appreciate your help adopting the very desktop code whose performance you prize, since we are well on our way to doing so. Importing, syncing are done. Deck deletion may or may not be done.

Just download the newest 2.16 alpha, go to settings --> advanced and enable the V16 schema (using the new feature just added in 2.16alpha77)

Please let us know your results.

In general though recall that in an open source volunteer application, *collaboration* and *personal effort* is a baseline expectation. You are a participant, not a spectator. And a participant that posts issues like this is generally not well liked by their fellow team members

**Comment by reyaz006** [comment]
>I find this issue mildly combative versus collaborative

>In general though recall that in an open source volunteer application, collaboration and personal effort is a baseline expectation. You are a participant, not a spectator. And a participant that posts issues like this is generally not well liked by their fellow team members

I know very well what you mean. But I also expect you to understand what I mean. The app is used by millions of people, not just by team members. You have to accept the fact that it looks like a glaring issue and the fix would greatly help many users.

>This despite your voluminous contributions on the same

I wish I could have the time to contribute to so many projects.

>I guess it does not just fix itself!

With a project of this scale, one would expect that developments will focus on somewhat critical issues. Not being able to use the app for several hours because it's busy importing a few decks is kind of a critical issue if you ask me.

>Did you know that each app on the Android operating system receives very limited RAM despite the system potentially having bunches? It's true

Did you know there is a huge amount of other apps that process tons of data at a time on Android? It's true. As someone with minimal coding and development experience, it doesn't look like AnkiDroid will perform any better if the OS will give it terabytes of RAM. It looks like it just doesn't use it effectively.

>Perhaps the CPUs on phones are not actually that fast?

Perhaps. But perhaps you are overestimating the difference. An app that deals with text and visual/audio data shouldn't need desktop-graded CPU to do things adequately fast. E-mail clients for example can sync gigabytes of data in minutes (yes full sync, not on-demand IMAP style).

>Just download the newest 2.16 alpha, go to settings --> advanced and enable the V16 schema (using the new feature just added in 2.16alpha77)
>
>Please let us know your results.

Thanks, going to try that. As soon as current version completes the syncing that is in progress. It's been 4 hours, it shows 250 mb is downloaded and counting. That's after 100 mb deck imported via PC app.

**Comment by reyaz006** [comment]
Enabling "the new backend" helped quite a lot. A full sync took about 10 minutes. Though after that I got "[anki:play:q:0]" text instead of a play sound button in one deck, and "Card content error" in another. Guess I'm expected to re-import all decks from scratch after enabling "the new backend".

**Comment by mikehardy** [comment]
> Though after that I got "[anki:play:q:0]" text instead of a play sound button in one deck

Fixed by this - currently in review: #11849 (specifically https://github.com/ankidroid/Anki-Android/pull/11849/commits/363607009f64d31c31c30712d8291689f07bbe4c)

Hopefully merging in a day or three. Glad import + sync works as expected now with regard to performance.

**Comment by dae** [comment]
The 'card content error' hasn't been reported before - if it still happens in the next alpha, please provide more details in a new issue. You shouldn't need to re-import anything.

Please note that while AnkiDroid's legacy code does have some room for performance improvement, the main cause of import/sync slowdowns is a change that was made in recent Android versions. Work is in progress to deal with that, and there is a workaround in the mean time. https://github.com/ankidroid/Anki-Android/issues/8925#issuecomment-976337268
