### ISSUE TITLE
Linter: ensure that Timber's call are trivial

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12022]
Each call to Timber should be trivial. That is, it must take a string and its arguments. Timber should be the one that create the String to log if it decides to log it. 
This is important because currently `Timber.i("string with $variable")` takes some computing time to create the actual string to print, even when we don't want to Timber informations. 

So we should get a Linter warning that let us know whether the first argument of Kotlin is anything else than a simple string. In particular a kotlin format string.

Currently, they are 35 format strings in Timber. It would be also nice to clean them too. That can be done by someone who don't know how linter work

**Comment by david-allison** [comment]
https://github.com/JakeWharton/timber#lint

`StringFormatInTimber`

This issue was likely introduced in 0d9df62371152be9c93bbb4989ba690eb5d11009. My bad

**Comment by Arthur-Milchior** [comment]
No big deal.
Then I guess this issue can be rephrased as "correct the errors and reenable it"

**Comment by mikehardy** [comment]
I'm all for using lint rules when possible, so I like the idea, what I don't understand is how with the commit linked above https://github.com/ankidroid/Anki-Android/commit/0d9df62371152be9c93bbb4989ba690eb5d11009 (which was removing an ignore on the timber's lint rules) would result in warnings not showing up (StringFormatInTimber)?

Anyway, the whole goal of the issue is good (do not do string interpolation manually, let Timber do it) I just don't follow the comment thread

**Comment by david-allison** [comment]
[The lint checks were disabled due to an issue with AGP](https://github.com/ankidroid/Anki-Android/commit/0a696b1b5126a855f5723a2819af002de5fc9c38), which was resolved. I believe the resolution should have been moving the issues to 'fatal' rather than removing the ignores.

I also don't think this is an issue for our repository. This should be a lint check in the Timber repo, which we should enable.
