### ISSUE TITLE
[Bug] Toolbar menu disappears after dismissing the Sync error dialog

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#12368]
###### Reproduction Steps

1. Be offline or have the server otherwise inaccessible
2. Tap sync
3. Dismiss the Sync error dialog by tapping outside of it

###### Expected Result

Menu stays

###### Actual Result

Menu is yeeted off the toolbar

###### Debug info

AnkiDroid Version = 2.16alpha83

Android Version = 11

Manufacturer = Xiaomi

Model = Mi A2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A2 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = f2c7cd5b-d365-4506-bb65-04b755fb6ba0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I am not sure, but this may be related to a cluster of issues around the app bar (is that what you mean by toolbar? https://material.io/components/app-bars-top) where they do not redraw correctly in a few cases. If toolbar == appbar and you search the issues list, there are a few, and at least one of them has cross-links to most of the others in an attempt to collect them, on the hunch it is single root cause

**Comment by oakkitten** [comment]
Pressing Ok in the dialog works fine though. Pressing Ok should do the same as dismissing it, so I suppose some sort of a callback isn't getting called somewhere or something. (App bar, yes. I hate the term because it's super confusing to anyone who's not a dev so I call it a toolbar. It _is_ a `Toolbar`, anyway.)

**Comment by mikehardy** [comment]
I hear ya - but for any UI elements if they have a material.io name, it's handy to use it so we can all reference the same thing in the documents that we use as our official arbiters for correctness (and we do that - use them as official arbiters for correctness) because otherwise as a consensus-drive project UI/UIX stuff turns into a bike-shed timesync of no progress)
