### ISSUE TITLE
Create a ManageSpaceActivity

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12366]
Android offers user to manage the space used by an app. By default, "manage space" actually means "delete everything", which is clearly not acceptable, so we need to replace it by our own activity. 

First step is going to be create such an activity. You can find a quick explanation on https://medium.com/@_foso_/what-is-a-managespaceactivity-on-android-26530ba4117b .This activity can be very minimal at first. Maybe just a single text message stating that there is no way to manage data, appart from deleting the app and loosing all progress.

Then later we can use it to add various options, such as syncing, actually allowing to delete the whole app (with huge warning if not synced) and so on. The details of this menu can be discussed, we should be able to add each option one after the other in separate PR and have distinct discussions for each element of the settings.

@david-allison suggested
![](https://cdn.discordapp.com/attachments/847123004059549718/1016056200808382534/Screenshot_2022-09-04_at_19.43.54.png)

# Sub-issues

I'm creating separate issues for each entry of this menu. If you have ideas not yet listed, please add them. This issue will be closed when all sub-issues are either implemented or rejected.

* #12538
* #12539
* #12540

**Comment by Noxor11** [comment]
Hi. I would like to work on this.

**Comment by BrayanDSO** [comment]
Downgrade collection → IMO, low priority and hard to get right, because you can't downgrade without uninstalling the app, which means that your collection will be deleted along with it

---

`Reset preferences` → `Reset settings`. Inside the app, we call them settings

---

`erases your AnkiDroid collection & media from your phone` → `erases your AnkiDroid collection & media`. AnkiDroid can be installed on tablets and TVs (smartwatches too I guess)

---

I believe that a "Error reporting" section doesn't fit an activity with the goal of managing storage, but seems useful, especially being able to copy debug info if the app always crashes when opened, and I can't think of a better option.

My main concern about it is that those options should be bullet-proof and currently they are far from it. `getDebugInfo` doesn't have any tests and depends on a collection, which means that the user can't get the debug info if there is an error while getting the collection

**Comment by Arthur-Milchior** [comment]
Thinking more about it, I believe the most obvious actions one should be able to do is :
* reduce the number of back-up
* delete the back-ups
* check media (deleting unused ones)

That's the only thing that takes space and can be deleted without içpatsimh sfe tojjetsiom

**Comment by mikehardy** [comment]
> That's the only thing that takes space and can be deleted without içpatsimh sfe tojjetsiom

:thinking:

**Comment by Arthur-Milchior** [comment]
Corrected.

**Comment by mikehardy** [comment]
For a second I was worried for you - either your health with some stroke or similar, or perhaps an out of control cat on the keyboard :laughing:

**Comment by Arthur-Milchior** [comment]
I created three sub issues for three actions that relates to managing spaces.
None of the other items suggested above are related to managing spaces. I really don't believe we have any reason to do more than what we are asked for by Android. That'll be more work to maintain, more risk of bugs, and don't add values compared to doing the same tasks in AnkiDroid.

**Comment by mikehardy** [comment]
Agreed - thanks @Arthur-Milchior
