### ISSUE TITLE
Decide which assertions to use

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12384]
Currently we use:
* kotlin.test.assertNotNull
* org.junit.Assert.assertNotNull
* kotlin.test.junit.JUnitAsserter.assertNotNull
* kotlin.test.junit5.JUnit5Asserter.assertNotNull

I believe we should decide which one to use and create a lint ensuring we don't use other assertion.

For recall, in March, @david-allison created the lint rule JUnitNullAssertionDetector that appears if one uses `assertNotNull` or `assertNull` from `org.junit.Assert` and suggest  
> Use kotlin.test.assert[Not]Null OR kotlin.test.junit5.JUnit5Asserter instead of JUnit in Kotlin

I personally have a preference for the first one, because it's the only one having contract. That means that we don't need to add !! on the value, since the assertion had proven that the value is non null after the function returned.
As another example, functions which takes a block have contract that state the block is called exactly once.

`kotlin.test.junit5.JUnit5Asserter` is simple to remove since we only use its basic null/notNull/equals assertion, which exists in other assertion too. And it's used in 7 files.

`kotlin.test.junit.JUnitAsserter` is used only twice for assertNotNull, so even simpler. For some reason it's only used in AndroidTest, not in test

`import kotlin.test.assertFoo` is used in 27 files, using assertNull/notNull/Equals so it would not be that hard to remove (even if I believe it would be a bad idea)

`import org.junit.Assert` is used 88 files, so it may takes more work to change it. Worse. It is imported with .* and without specifying the method imported, so I can't even check that everything is easily available from kotlin.test.

**Comment by BrayanDSO** [comment]
AFAIK, kotlin.test.junit and kotlin.test.junit5 have contracts as well

**Comment by Arthur-Milchior** [comment]
Assuming 

In kotlin.test.junit5.JUnitSupport.kt
```kotlin
    override fun assertNotNull(message: String?, actual: Any?) {
        Assertions.assertNotNull(actual, message ?: "actual value is null")
    }
```

In org.junit.jupiter.api.Assertions.java
```java
	public static void assertNotNull(Object actual, String message) {
		AssertNotNull.assertNotNull(actual, message);
	}
```

in org.junit.jupiter.api.AssertNotNull.java
```java
	static void assertNotNull(Object actual, String message) {
		if (actual == null) {
			failNull(message);
		}
	}
	private static void failNull(Object messageOrSupplier) {
		assertionFailure() //
				.message(messageOrSupplier) //
				.reason("expected: not <null>") //
				.buildAndThrow();
	}
```

I see no contract. 
Also, you can just test manually. For example in the test `nameOfNewBackupsCanBeParsed`, if you replace `assertNotNull` from `import kotlin.test.assertNotNull` by `kotlin.test.junit5.JUnit5Asserter.assertNotNull`, then you see that `backupName` remains nullable, and you must add `!!`.

**Comment by Arthur-Milchior** [comment]
`kotlin.test.junit.JUnitAsserter` seems to be used only in AndroidTest. I don't believe it's relevant to add it to test.
Also, you can test it the same way and see that it does not ensure a contract

**Comment by BrayanDSO** [comment]
+1 for kotlin.test

**Comment by Arthur-Milchior** [comment]
> +1 for kotlin.test

In this case, it's done in #12353

**Comment by david-allison** [comment]
> import kotlin.test.assertFoo is used in 27 files, using assertNull/notNull/Equals so it would not be that hard to remove (even if I believe it would be a bad idea)

It's an assertion. It works. We gain no benefit by changing this code.

> import org.junit.Assert is used 88 files, so it may takes more work to change it. Worse. It is imported with .* and without specifying the method imported, so I can't even check that everything is easily available from kotlin.test.

It's only used in one place in a (with a cleanup). There's no noticeable improvement in removing `!!` if we fix this, but it is planned.

----

It's useful to go the PRs to get context. I apologize for not placing all justification in the commit messages.

- https://github.com/ankidroid/Anki-Android/pull/10429
- https://github.com/ankidroid/Anki-Android/pull/12042


* We want to remove `Assert.assertNotNull` and we have done so successfully with `JUnitNullAssertionDetector/LegacyNullAssertionDetector`
* I don't care about using `org.junit.Assert.` and I'd be happy to keep it for any code which we currently use **unless** it's using contracts (`assertNotNull`).
* We've fixed a lot of 'simple' cases with `kotlin.test.assertNotNull (single argument)` 👍. These are in the 'big' test classes
* We have code with `messages` to go, which are using 'JUnit5Asserter'. This is a very small number of assertions
* At the time, I didn't want to get into writing a replacement for `JUnit5Asserter` with contracts
   *  it involved the first usage of code contracts in the codebase, and contracts were an experimental feature 
   * I mistakenly expected that all `kotlin.test` would correctly use contracts.
   * (unsure) I believe it is no longer experimental, and I have less hesitancy about experimental features (coroutines are experimental, and I trust what you're doing on that side of the codebase. This is unit tests, so screwing up should be immediately visible)
* `kotlin.test.junit.JUnitAsserter.assertNotNull` exists because junit 5 has known issues with `androidTest`

I've placed the current state of the codebase in a table. I've struck through libraries which we should definitely aim to remove
|                                                           | **'message' at start** | **Code contracts for nullability** | **Notes**                             |
|-----------------------------------------------------------|------------------------|------------------------------------|---------------------------------------|
| kotlin.test.assertNotNull (single argument)               | ✅ (N/A)                | ✅                                  |                                       |
| kotlin.test.assertNotNull (with message)                  | ❌                      | ✅                                  | Hopefully no usages. We should lint out usages                   |
| org.junit.Assert.assertNotNull                            | ✅                      | ❌                                  | 1 usage. with KotlinCleanup to remove |
| kotlin.test.junit.JUnitAsserter.assertNotNull             | ✅                      | ❌                                  | Only in `androidTest`, 3 usages       |
| kotlin.test.junit5.JUnit5Asserter.assertNotNull           | ✅                      | ❌            | 14 usages                             |
| org.hamcrest.MatcherAssert.assertThat(it, notNullValue()) | ✅                      | ❌                                  |                                       |

I've included `Hamcrest` which was not included above. Here is where we'll see a large improvement.I did not want this in `JUnitNullAssertionDetector` before the Kotlin migration was completed as this would have caused line noise on the calling code.

I do not want to get rid of `Hamcrest`: matchers are extremely powerful, and we have a lot of untapped potential here which can make test code more succinct (and improve error messages, improving DX).

I do think we should change `notNullValue()` and `not(nullValue())` as there are obvious improvements (removing `!!`)

----

To me, the logical conclusion would be: add a method in `AnkiAssert` which:
* uses contracts
* has the message in the correct order

AND/OR:

Fix `JUnit[5]Asserter.assertNotNull` to use contracts

We could then change `JUnitNullAssertionDetector` to block all of the above, and remind the user to use the method from `AnkiAssert`.

Aside: I don't like using lint rules here, it would be useful to see if the IDE has a feature which allow blocking of certain imports from a package. I don't want to see the wrong `assertNotNull` from the IDE autocompletion.

Aside: I would question WHY `JUnit[5]Asserter` doesn't have the contracts. This could be a limitation of the Kotlin API, in which case we can document that and come back to the drawing board.

**Comment by BrayanDSO** [comment]
Keeping the "muscle memory" of the arguments order is reasonable to me. Getting rid of the junit Java dependencies too. And yes, getting IDE support instead of linting would be great

**Comment by BrayanDSO** [comment]
@david-allison, `kotlin.test.assertNotNull` doesn't take message first (https://github.com/JetBrains/kotlin/blob/v1.7.10/libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Assertions.kt#L143-L156)

---
And about hamcrest, I'm in favor of keeping it too. Pretty powerful and makes things more readable

**Comment by david-allison** [comment]
I've elaborated. A single argument is `asserNotNull(col)` without the message at all

**Comment by BrayanDSO** [comment]
> - has the message in the correct order

What do you mean by `correct` here? Message first or latter? (although saying `correct` for either of those isn't right, IMO) 

Personally, having optional parameters first confuses me. 

Also, I didn't know there was a convention to use message first on the repo. Is this noted somewhere on the wiki on any other docs?

**Comment by oakkitten** [comment]
> 'message' at start

I wonder if anyone is actually finding those assertion messages useful *in practice*?
