### ISSUE TITLE
Lack of gestures in preview window

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#12390]
I'm always frustrated when I preview a deck and i cant go to the next card with a single hand because the go to the next card is a small button on the bottom right corner

I would like to be able to tap or swipe right to go to the next card

I have tried to make the buttons bigger, but holding the phone with the right hand is not helping that. The show answer button is bigger and i can almost press it comfortably press it while holding my phone with my right hand, but it wont go to the next card

The reason im using this is because Im using the preview window to show all cards of a deck to review something learned with [LPCG (Lyrics/Poetry Cloze Generator)](https://ankiweb.net/shared/info/2084557901) after learning every individual card using regular anki

**Comment by mikehardy** [comment]
Hey @voidplayer :wave: - this may be possible, to have the gestures system do something like this. Can I ask what version of ankidroid you are using? If it is not already the latest alphas (at least as a side-by-side install) can you check there? Because the gestures system has already  had a huge amount of work, so we want to make sure you are using the latest stuff there to assign gestures etc.

There may already be a "next card in preview" command that may be connected to a gesture, I'm not sure

**Comment by voidplayer** [comment]
Im using the latest alpha. settings> gestures and searching `preview` on top doesnt return results

**Comment by mikehardy** [comment]
Great - thanks for confirming. Seems the task is to:
- determine if the Previewer has any ability to do gestures at all? Unknown.
- add Previewer commands if they don't exist, for flip card (may be same as reviewer...) and next card and prev card

**Comment by voidplayer** [comment]
> determine if the Previewer has any ability to do gestures at all? Unknown.

No gesture works on the preview window right now. I have many defined, like edit, go back,... and none works

> add Previewer commands if they don't exist, for flip card (may be same as reviewer...) and next card and prev card

i would settle with an easy way to go forward with a single hand but it would be great if other gestures like go back or edit or even show answer worked too :)

Thanks!

**Comment by alyoshenka** [comment]
If this is still an issue, I'd like to take a look at it.

**Comment by voidplayer** [comment]
Yes it is!

Please do!

**Comment by alyoshenka** [comment]
Sweet, just wanted to make sure it wasn't intentionally let to go stale/get closed by the bot.

**Comment by voidplayer** [comment]
The bot is kinda of aggressive. Some times you dont feel like fighting it! ;)

I cant reopen it tho

Thanks for showing interest!! This lack of gestures in preview window drive me crazy some times

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by BrayanDSO** [comment]
The previewer changed considerably and that includes the buttons.

As of now, IMO, all the previewer actions are reasonable to be done with the default buttons, and adding gestures is a big chunk of work/complexity/more settings that won't result in a good enough reward, IMHO.

Since we are moving feature requests to the [forums](https://forums.ankiweb.net/c/suggestions/17), I'm going to ask you to post the request there so more people can discuss it.

**Comment by voidplayer** [comment]
Not much to discuss. If its not worth it, is not worth it

Its just a convenience thing to be able to use the reviewer with one hand because theres only tiny awkward button on the right corner but if its too much work to implement🤷‍♂️

**Comment by BrayanDSO** [comment]
FWIW, I'm making possible to assign custom keybinds to the previewer and the new reviewer. 

Gestures will eventually be implemented as well

**Comment by voidplayer** [comment]
Thats very good news!

Thank you!
