### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Basemz** [ankidroid/Anki-Android#12428]
![Screenshot_20220917-201601_AnkiDroid](https://user-images.githubusercontent.com/113794099/190869267-5a1e4e22-d9b8-4227-97f3-e63bb893caec.jpg)
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! With apologies, you've ignored the template for our issues, so we do not have the information to go on in order to troubleshoot this, so I am going to close it as not actionable.

I will say in the past this happens when people have storage cards formatted as exfat and they have lots and lots of media, as that filesystem format cannot handle many files in the same directory. This is rare in modern phones, but happens to about one person a year on average I'd say.

**Comment by Basemz** [comment]
what should i do?, please

**Comment by mikehardy** [comment]
Open a new issue, read the template that is in the new issue box, and follow it's instructions

**Comment by Basemz** [comment]
It’s really complicated, I am trying to understand really hard but it
didn’t seem to work.
I am really sorry, but i really need to fix this issue.

Thank you so much for your time and kindness
