### ISSUE TITLE
Per-app language preferences in Android 13

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12458]
We know that android 13 is supporting per app language. And we can access that by :: Settings > System > Languages & Input > App Languages > selecting the app(our case AnkiDroid)

We can add this to our application. Would be more convenient? 

We can achieve so by placing `android:localeConfig ` attribute in your app's manifest. And complete the whole procedure?

**Comment by mikehardy** [comment]
It is...a lot more difficult then that I think. We have considered it, or at least I have considered it.
It's really important to know what problem you are trying to solve.
Check these out:
https://github.com/ankidroid/Anki-Android/pull/10027#issuecomment-1006670058
https://github.com/ankidroid/Anki-Android/pull/10027#issuecomment-1065135049

So the problem is multiple:
- including all translations (including the manual) will add 1MB per locale, so we want to only include the necessary ones
- ABB upload format (still in future for us...) will allow it to be per-locale, but then what about people with different in-app languages? What about APK users (non-play store users, we have a lot! We are popular on F-Droid for instance)
- Play Store APIs allow ABB users to then download locale packs for their in-app languages but...what about APK users again?

So I think first of all this is definitely *less* convenient. Using Play Store APIs means we have complicated our build system because we always need to handle non-play store delivery (via APK via source build from F-Droid for example)

It is potentially useful, but that would only be if we included translations of the manual for offline use, because then the size exapansion is so big that we want to ship only the locale people need. But then we have the ABB complication, new google APIs to implement, and still ship everything in the APK.

So in general I'm going to say no, this is not on our radar right now. It is not something we can feasibly implement.

For now the manual will still be offline in English only, online for the rest, and we'll ship all locales without messing with our build system or any Google APIs.
