### ISSUE TITLE
Blanc empty cards 

### ISSUE THREAD

**Issue by ahmedbenarab** [ankidroid/Anki-Android#12519]
I can't see some cards either the front nor the back 
It shows nothing , as shown in the photo below
![Screenshot_20220928-081337](https://user-images.githubusercontent.com/21174375/192713964-788293ce-3fe6-465d-bf07-cc058d0e2675.png)

This issue i figured it out in many previous stable versions, and it still present in the beta version too
I am using android 7.1

**Comment by mikehardy** [comment]
Can you please open a new issue, but this time do not delete the issue template that asks you for information we need to help? Much better to fill it in.
Also, we'll need to see the contents of the card template to know why display is not working.
You might try the most recent alphas to make sure it's not fixed in recent releases (they are far far more advanced than any currently released betas https://github.com/ankidroid/Anki-Android/releases

**Comment by ahmedbenarab** [comment]
ah yeah , i will open a new issue 
ps: i didn't delete the templet btw , just it doesn't apear when i entered from the anki help link 
ps: i am using the latest alpha version

**Comment by mikehardy** [comment]
@ahmedbenarab very strange regarding the template not showing up when you use the anki help link, we'll have to investigate that
