### ISSUE TITLE
Alpha 85 parallel release script ran out of heap space during build, and failed silently during publish

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#12594]
```
md5sum AnkiDroid-2.16alpha85.parallel.*
f456419d95a7bfc7b0c2b244a561f824  AnkiDroid-2.16alpha85.parallel.A.apk
f456419d95a7bfc7b0c2b244a561f824  AnkiDroid-2.16alpha85.parallel.B.apk
```

**Comment by mikehardy** [comment]
Huh - very unexpected, the process is fully automated and has been forever, surprising it didn't work. So, not to say I don't believe you and an md5 collision would be ridiculous but just to be sure, yep, they are equivalent:

```
mike@bistromath:~/Downloads % apkanalyzer manifest print AnkiDroid-2.16alpha85.parallel.A.apk |grep package
    package="com.ichi2.anki.a"
mike@bistromath:~/Downloads % apkanalyzer manifest print AnkiDroid-2.16alpha85.parallel.B.apk |grep package
    package="com.ichi2.anki.a"
```

:thinking: 

2.16alpha84 does not suffer the same problem:

```
mike@bistromath:~/Downloads % apkanalyzer manifest print AnkiDroid-2.16alpha84.parallel.A.apk |grep package
    package="com.ichi2.anki.a"
mike@bistromath:~/Downloads % apkanalyzer manifest print AnkiDroid-2.16alpha84.parallel.B.apk |grep package
    package="com.ichi2.anki.b"
```

Ahh - the build itself failed (silently! so that's a bug in the script) while making the parallel builds so they all failed. Most unfortunate

https://github.com/ankidroid/Anki-Android/actions/runs/3078621122/jobs/4974293175#step:10:515 (etc)

**Comment by mikehardy** [comment]
Task list:

- Add a bit more output prior to each step in the release script so the logs are easier to follow (pre/post build, pre/post upload)
- remove the git checkout after universal APK build (https://github.com/ankidroid/Anki-Android/blob/0467850e5034b27ff0cc3fa3e87ccf3cc60d80c2/tools/release.sh#L129-L131) as we don't abort releases anymore
- Make sure that a failure in the parallel release script propagates the failure up to the publish workflow and fails it
- Fix memory usage of build process - it takes more memory now that we are all Kotlin. Maybe just `./gradlew --stop` as first pass
- Optimization: Alter parallel release script to only build the ones it needs to (it builds all 5 for non-public releases but we only need 2)

**Comment by mikehardy** [comment]
Thanks for the heads up on that one, silent failures are the worst! All fixed.

```
mike@bistromath:~/Downloads % md5sum *apk
f6988990e96573f4a032363508cf2a20  AnkiDroid-2.16alpha86.parallel.A.apk
e5630d0ed52f4e315199967f8d135476  AnkiDroid-2.16alpha86.parallel.B.apk
```
