### ISSUE TITLE
Inconsistent colour of hyperlinks

### ISSUE THREAD

**Issue by pratyaksh1610** [ankidroid/Anki-Android#12595]
###### Reproduction Steps

Hyperlinks should follow a color scheme.

1. Settings -> About
2. Settings -> About -> Open changelog

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

![highlight_links](https://user-images.githubusercontent.com/76740999/194530549-94551215-fb47-4adb-80f9-876f41a03580.png)
![link_colour_must+be_same](https://user-images.githubusercontent.com/76740999/194530556-89923949-9296-4dd9-9574-ee47954d5880.png)

**Comment by TomerPacific** [comment]
Hi @mikehardy , can I help with this issue?

**Comment by BrayanDSO** [comment]
I'm not mikehardy, but yes you can. Enjoy working on it

**Comment by krmanik** [comment]
This may be fixed on ankidroiddocs issue because previous image has TexView and later image has html `<a>` tag in webview for docs.
The changes will be styling the link here for both night and dark mode.
https://github.com/ankidroid/Anki-Android/blob/bd818a03bb998538f35eb348327cd7a78632ea2c/AnkiDroid/src/main/assets/changelog.html#L8

But I have completed new docs which is consistent with Anki Desktop docs and AnkiMiobile docs.
https://github.com/ankidroid/ankidroiddocs/pull/103

**Comment by mikehardy** [comment]
@BrayanDSO 

> I'm not mikehardy, but yes you can. Enjoy working on it


![image](https://user-images.githubusercontent.com/782704/195660680-47caa109-3516-443d-9f1d-b743c88b590f.png)

**Comment by TomerPacific** [comment]
@mikehardy , @BrayanDSO - I have opened a PR and I welcome your feedback.
