### ISSUE TITLE
Request for a button to keep using the same Cloze number

### ISSUE THREAD

**Issue by pilgrimlyieu** [ankidroid/Anki-Android#13047]
**Is your feature request related to a problem? Please describe.**
It's annoying to change the cloze number over and over again if I want to create lots of cloze with the same number.

**Describe the solution you'd like**
I consider that it would be great if there is a button(like the button in browser in 2.16 alpha version) to achieve this function. 

Sol-1. If I click the button, its style would change(may be brighter) and the cloze added later would use the same number as before. If I click it again, it would return to normal(increasing number while adding new cloze).

Sol-2. If I long press it, it would switch the mode. If I click it, it would create a cloze(cos the current cloze button is small).

**Comment by BrayanDSO** [comment]
I feel the same pain, although I got used to it.

If by the browser button you mean the filters floating action button (FAB), I don't think that it would fit well the note editor screen. Adding it as an checkbox option on the three dot menu at the top right of the screen would be better, IMO

**Comment by pilgrimlyieu** [comment]
> Adding it as an checkbox option on the three dot menu at the top right of the screen would be better, IMO

I think it would be more convenient to switch the mode if there is a floating button nearby in my opinion.

**Comment by BrayanDSO** [comment]
A FAB is more convenient yes, but I don't think it is a good idea because:

- takes a reasonable amount of space on a screen that is already somewhat cluttered
- it should only show if the notetype is a cloze one, and inconsistent UI generally isn't a good idea
- FABs should only be used for a [very common or important action of the screen](https://m3.material.io/components/floating-action-button/overview#9f273ba1-50b2-497a-b7ae-89fd58353472), which isn't the case here 

---
Another suggestion is to add another button to the toolbar to add clozes with the same number. So there will be one button for each action, with different icons, that you can easily trigger and edit your note. What do you think?

**Comment by pilgrimlyieu** [comment]
> Another suggestion is to add another button to the toolbar to add clozes with the same number. So there will be one button for each action, with different icons, that you can easily trigger and edit your note. What do you think?

A nice alternative!

**Comment by pilgrimlyieu** [comment]
still searching for solutions

**Comment by pilgrimlyieu** [comment]
still searching for solutions

**Comment by dae** [comment]
AnkiMobile's approach is to allow a long-press on the button to keep the same number.

**Comment by pilgrimlyieu** [comment]
> AnkiMobile's approach is to allow a long-press on the button to keep the same number.

This way seems more convenient in my opinion. Is there any plan on this feature request?

**Comment by snowtimeglass** [comment]
> > AnkiMobile's approach is to allow a long-press on the button to keep the same number.
> 
> This way seems more convenient in my opinion. 

On AnkiDroid, long-pressing a toolbar item is assigned to show its tooltip, so that way might not suit for AnkiDroid. 

It might be better to add a new built-in button as you originally requested, and as on Anki Desktop. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/9c87a171-4a5c-4c7a-9171-4454be3b6d07)
(I agree that adding a customized toolbar item by yourself is nice, as a workaround for now.)

**Comment by pilgrimlyieu** [comment]
> > > AnkiMobile's approach is to allow a long-press on the button to keep the same number.
> > 
> > 
> > This way seems more convenient in my opinion.
> 
> On AnkiDroid, long-pressing a toolbar item is assigned to show its tooltip, so that way might not be suitable for AnkiDroid.

Yes, I've confirmed that(I don't know why I didn't realize that when I replied). You're right.

> It might be better to add a new built-in button as you originally requested, and as on Anki Desktop. ![image](https://user-images.githubusercontent.com/10436072/267196226-9c87a171-4a5c-4c7a-9171-4454be3b6d07.png) (I agree that adding a customized toolbar item by yourself is nice, as a workaround for now.)

Agree.
