### ISSUE TITLE
[Request] Add an option to choose the date format

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13048]
**Is your feature request related to a problem? Please describe.**
AnkiDroid shows dates in MM/DD/YY format in the Card Browser and in YYYY-MM-DD format in the Card info option. However, I am used to seeing dates in the DD/MM/YY format. So, this makes it difficult for me to read the date.

**Describe the solution you'd like**
There should be an option in the settings to set the date format.

**Describe alternatives you've considered**
If the app can determine the correct date format from the device locale, it would also be fine. For example, I don't think WhatsApp has a date format setting, but it shows dates in the correct format (DD/MM/YY).

**Comment by elliotcathcart** [comment]
Specifically which dates are in the wrong format?

Any dates I see in the app are in the DD/MM/YYYY format for me. Like if I go to card browser and sort by 'Card Modified' those dates are DD/MM/YYYY

**Comment by BrayanDSO** [comment]
> If the app can determine the correct date format from the device locale, it would also be fine.

It can (Android has a function to do it). And I definetely prefer to keep the app as simple as possible, so it's better to avoid adding settings if possible.

---
About the MM/DD/YYYY, if you are using the app in `English`, it is because AnkiDroid follows american english. To avoid ambiguity, I'd be in favor of specyfing that the language is `English (US)`.

---
And a question, YYYY-MM-DD is shown on card info with the legacy or the new backend? Or both?

**Comment by user1823** [comment]
> It's automatically done via the language settings. English is the US format. I have mine set to 'system default' which is UK format for me.

Thanks for this tip. Changing the language to "system language" corrected the date format in the card browser. I never realised that the app language was not set to system default.

However, the date format is still incorrect in the card info.

> And a question, YYYY-MM-DD is shown on card info with the legacy or the new backend? Or both?

With the new backend, the date format is YYYY-MM-DD.
With the legacy backend, the date format is MMM DD, YYYY (i.e., today's date would be Jan 2, 2023).

**Comment by BrayanDSO** [comment]
The new backend reuses screens from Anki desktop, so a proposal to change the date format of Card Info should be asked there. I guess that the reason to use `YYYY-MM-DD` is because it is the [ISO international date format](https://www.iso.org/iso-8601-date-and-time-format.html), and differently from Android, Javascript/Typescript (the programming language used to build pages like Card Info) don't have a function to get the best date format based on the locale (or maybe it has one, but I'm not proficient enough on javascript to tell, nor I found one on a quick google)

We probably should update the Card browser to display dates on the ISO format as well to be consistent with Anki/AnkiMobile's card browser.
