### ISSUE TITLE
Migration of AnkiDroid directory using `DocumentFile`

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13145]
Currently `com.ichi2.anki.servicelayer.scopedstorage` uses [`File`](https://developer.android.com/reference/java/io/File). It seems however that Android will limit the use of `File`s and require us to use [`DocumentFile`](https://developer.android.com/reference/androidx/documentfile/provider/DocumentFile) when we are not working inside the scoped storage directory.

So we need to change the whole process so that it accepts either a `File` or a `DocumentFile` as input (it can keep `File` as output). We don't want to remove `File` altogether, because we know it currently work. Instead, we should just ensure that all tests that currently exists and work with `File` also work with `DocumentFile`.

**Comment by BrayanDSO** [comment]
To be honest, I can't tell what is the goal of this issue, what problem this aims to solve

**Comment by Arthur-Milchior** [comment]
Let's assume you have a collection in `~/AnkiDroid` and you reinstall AnkiDroid. As you know, by default, we can't open the collection anymore. 
Instead, we'll need to use `ACTION_OPEN_DOCUMENT_TREE`. As David explained in #13134, which lead to getting `DocumentFile`. As discussed in #13134, we probably can't get `File` from `DocumentFile`. This also means that we probably can't open the sqlite database. So we need to ensure that the migration can also work using only `DocumentFile`. 

If I'm wrong, and we can start a migration from a new installation without having to use DocumentFile, I'd love to learn it.

**Comment by jeffchang5** [comment]
You can assign this to me @Arthur-Milchior

**Comment by david-allison** [comment]
As discussed in Discord:

* I do not trust `DocumentFile` enough to use it to perform a migration. We need a **lot** more testing as:
  1) If we need `ACTION_OPEN_DOCUMENT_TREE` it's an operation that we'll now be performing with no backup. This risks users' data being permanently deleted if `DocumentFile` fails
  2) If we're copying, not moving, we double the storage space required. Many users won't have this. Medical collections are HUGE.
  3) It's (sadly) a much better UX to push a user away from the Play Store to 2.16+ on GitHub/F-Droid, where they can access `/~AnkiDroid` at full speed without the risk of deletion, or 2.15 with the massive hit on access speeds.

This will be review/testing-heavy, rather than implementation heavy, and I struggle to see it getting to the level that we could release it.

**Comment by jeffchang5** [comment]
I can POC a migration or has this already been done?

**Comment by Arthur-Milchior** [comment]
@jeffchang5 It has not been done, and, as @david-allison , we may not want to do it. Hopefully, we'll never need it, so closing the issue.
