### ISSUE TITLE
Furigana stretch all the way to the previous Kanji [Bug]

### ISSUE THREAD

**Issue by Krassnig** [ankidroid/Anki-Android#13175]
###### Reproduction Steps

1. Copy the predefined Basic card type and add the {{furigana:Front}} to the front side (this probably works with any card type/any side etc..)
2. Add this CSS for easier debugging
```css
.card { font-size: 2rem; }
ruby { background-color: green; }
ruby rb { background-color: orange; }
ruby rt { background-color: red; }
```
3. Create a Card of the Basic Copy where the front has the value: "リンさんは ２５[にじゅうご] 歳[さい]です。コウさんも ２５[にじゅうご] 歳[さい]です。"
(Notice the spaces, here is the same sentence where spaces are replaced by underlines: "リンさんは_２５[にじゅうご]_歳[さい]です。コウさんも_２５[にじゅうご]_歳[さい]です。")
4. Open the card in ankidroid.

###### Expected Result

Preview of the Anki Desktop Card Editor:
![image](https://user-images.githubusercontent.com/24553082/215901330-a24a5695-8e83-4ab6-b2ac-a0b3be8e3cc1.png)

###### Actual Result

Card on AnkiDroid:
![image](https://user-images.githubusercontent.com/24553082/215900940-5215d22c-1504-4830-a642-da58e373f3da.png)

###### Debug info

AnkiDroid Version = 2.15.6
Android Version = 13
Manufacturer = OnePlus
Model = IN2013
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; IN2013 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.85 Mobile Safari/537.36
ACRA UUID = c130a893-4237-4509-84a7-93c217a64eae
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

It also happened on my friends phone which is a Google Pixel.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

##### Thanks for building such a cool App

I love learning with Anki and building Decks and thanks to you guys work I can do it whereever I go, tram, bus. It's impressive that you redeveloped almost all the feature for Android 👌♥.

**Comment by Aquafina-water-bottle** [comment]
Hey @Krassnig,

I ran into a similar issue, and found that when editing the raw HTML of the card (ctrl+shift+x), I saw a space was replaced with `&nbsp;`. It was specifically this that caused my furigana to not work and stretch past its supposed boundary. I wasn't actually able to reproduce your issue by copying/pasting your sentence, and I'm guessing it has to do with this point.

<details>
<summary>Images</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/17107540/30285f0e-1e16-4bff-9f16-6c964e972f43)
![image](https://github.com/ankidroid/Anki-Android/assets/17107540/5da1cf06-385a-4e0d-9791-602d3c88e510)
![image](https://github.com/ankidroid/Anki-Android/assets/17107540/447a1eee-381f-4786-92ae-f97175f47c73)

</details>

If you still have this card stored somewhere, do you think you can double check your field to see if it does indeed have `&nbsp;` or not?

Finally, can you try enabling the new rust backend? By doing so, the issue seems to have fixed itself (since the rust backend handles this case properly).

**Comment by Krassnig** [comment]
Yes! This was indeed the issue. Thank you soo much! I just removed all the &nbsp.
I suppose Github removed the &nbsp when I pasted it into the issue.

I don't know how to enable the Rust backend, though 😅 .

I am not sure if you still consider this a bug or if this resolves itself with the new Rust backend.
Feel free to close close this issue and thank you for your help.

**Comment by Aquafina-water-bottle** [comment]
Glad it was of help, and hopefully it'll help anyone searching the issues for something similar!

To enable the backend, navigate to:

> The 3 bars at the top left → Settings → Advanced → Use the new backend

Note that there's a bunch of warnings, and although I'm not an Ankidroid developer, it's probably not just for show. I do know of a good amount of people who have it enabled and I haven't heard any issues from them yet, but to err on the safe side, it might be best not to enable it until it becomes fully stabilized.

As for the issue report itself, if enabling the backend works for you, then it should be safe to close.
