### ISSUE TITLE
Is there a way to get read/write access on new media.collection directory, on rooted device, with Termux, since 16alpha93 and data migration?

### ISSUE THREAD

**Issue by Yoannjap** [ankidroid/Anki-Android#13222]
Hello everyone,

I have downloaded 16alpha93 last alpha version of AnkiDroid.
There is a new upward arrow on top of the app to 'migrate' your media collection to a private Ankidroid directory. A new directory only accessible by your currently installed or future-updated AnkiDroid app.
[See the described of this feature here on GitHub.](https://github.com/ankidroid/Anki-Android/wiki/Storage-Migration-FAQ)

Ok, **but** I do myself manage decks in which I add regularly new cards, that contains new video (MP4) files, for a French Sign Language deck.

I use a 'productive' method:
• I search in multiple sign language dictionary the sign video on Bromite,
• I download the .mp4 file onto my internal SD card download folder,
• I then open Termux and send all the little-size .mp4 files onto download folder to my media.collection AnkiDroid folde (that I set in settings on my external SD card), with my custom-command:
```
sudo find /storage/emulated/0/Download -mindepth 1 -maxdepth 1 -mtime -1 -daystart -size -10M -name "*.mp4" -exec mv -t /storage/emulated/0/Download/VideoDownloader {} \; && cd /storage/emulated/0/Download/VideoDownloader/ && ls -1 && cp /storage/emulated/0/Download/VideoDownloader/* /storage/684D-3V87/Documents/ANKI_à_mettre_dans_la_collection.media_PC && mv /storage/emulated/0/Download/VideoDownloader/* /storage/684D-3V87/Apps/Ankidroid/collection.media/ && cd -
```

Note that my phone is rooted with Magisk.

But I am so scared with clicking on the button 'migrate' my AnkiDroid media.collection to a private directory, and not being able then to send my new download media files from download directory to new private media.collection folder.

Do you know a way to do it on rooted device with Termux ?

Thanks a billion !

Yoannjap

**Comment by doozan** [comment]
If you have an important collection, don't push that button unless you have a good backup or have recently synced your collection to ankiweb as there is a chance you'll end up in a bad state (see #13212)

Since you have root access you should have no problem reading/writing files to the new directory which will be something like 
`/storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid`

Unfortunately the command you posted only uses `sudo` for the `find` command that moves the files into your intermediary directory, not for the later `mv` command that moves the file to you AnkiDroid storage so it won't work as-is. Since `find` can run multiple `-exec` commands you could skip the intermediary directory and simplify the whole thing into something like this (WARNING: UNTESTED) `sudo find /storage/emulated/0/Download -mindepth 1 -maxdepth 1 -mtime -1 -daystart -size -10M -name "*.mp4" -exec cp -t /storage/684D-3V87/Documents/ANKI_à_mettre_dans_la_collection.media_PC {} \; -exec mv -t /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid {} \;`

**Comment by Yoannjap** [comment]
Wow, thanks a lot for your help @doozan.

The intermediary folder into which I copy files let me then sync it with my cloud drive folder on my computer, in order to sync .mp4 files with ankiweb, using Anki desktop sync process (using Ankidroid sync process doesn't export .MP4 files to Ankiweb, dunno why...)

I'll test your command tonight and then give a feedback.

But another question: with new Ankidroid folder migration, it won't then be possible to store media.collevtion in a private external SD card folder (and not /emulated/0/ internal one ?)

**Comment by david-allison** [comment]
I will be pushing a patch so we can keep AnkiDroid in `/storage/emulated/0/AnkiDroid` for advanced users

This will be unavailable on builds from the Play Store due to Google Policies.

**Comment by Yoannjap** [comment]
Absolutely great if then!

And if you can, please a possibility to store your media collection also on external SD card storage, when rooted.
Because it is a huge advantage for ones with huge collection.

Thanks a lot, whatever 🙂

**Comment by david-allison** [comment]
AFAIK, SD cards are supported already. 

From memory, this needs to be in a specific folder (Device specific identifier for the SD Card + per-app folder structure) which will be wiped on uninstall, and has been that way since Lolipop.

There was a thread on our Google Group about it: https://groups.google.com/g/anki-android/c/Eu7AXSQa6Es/m/TBM0CwHHBQAJ
