### ISSUE TITLE
[Bug] 2.16Alpha93 - Ease for all cards reset to 250% after first synch

### ISSUE THREAD

**Issue by LBX1002** [ankidroid/Anki-Android#13236]
###### Reproduction Steps

1.  Download alpha93.B
2. Synch with web
3. 

###### Expected Result
Return notes with current ease 

###### Actual Result
Ease comes back as 250% for all cards

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I wonder if it is this: https://changes.ankiweb.net/changes/2.1.50-59.html#changes-in-2158
Which is on deck to be fixed by ingesting 2.1.58 (currently in release process, not quite out yet...) with https://github.com/ankidroid/Anki-Android-Backend/pull/272 + #13287 - it sure looks the same

**Comment by dae** [comment]
Yep, looks to be the same.

**Comment by mikehardy** [comment]
Okay - @LBX1002 if you follow the changelog link, there is a procedure you can do on Anki Desktop to repair things as much as possible, but otherwise I'm not sure there is much more we can do other than to release alpha94 (in process but will still be a couple days) and advise you to use alpha92.

So with no other actions to take I'm going to close this but I'm really sorry for the trouble. Ease resetting like that is of course unexpected and I'm sorry it happened
