### ISSUE TITLE
AnkiWeb Sync Says Complete But Never Is[Bug]

### ISSUE THREAD

**Issue by alex-pac** [ankidroid/Anki-Android#13243]
###### Reproduction Steps

1. Using version 2.16alpha84 on Android 11 on a Retroid Pocket 3
2. Syncing from AnkiWeb has taken several days.
3. On multiple occasions the sync will finish and say complete, but then tapping sync again and Anki has even more to download.

###### Debug info
AnkiDroid Version = 2.16alpha84

Android Version = 11

Manufacturer = Retroid

Model = Retroid Pocket 3

Hardware = ums312_2h10

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Retroid Pocket 3 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.132 Mobile Safari/537.36

ACRA UUID = 19fee80d-d17e-4d12-b0b3-64c7e47fff17

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
With apologies, alpha83 is old enough I'm not sure this is still valid. Thank you for testing though of course! Can you retry with current alpha to make sure we don't waste any time chasing already-fixed ghost issues?

**Comment by david-allison** [comment]
I strongly suspect this is greatly improved in 3cc351c545e0881f9c350c625d005d669e8c08ce (alpha 93):

The issue:

A sync consists of both a collection sync and a media sync.

When a full sync from the server is started due to a new login, the media sync may be extremely large. In addition to this (before alpha 93), the Android file system causes significant slowdowns.

The collection sync finishes quickly. The media sync is incremental, and may not finish when the sync is completed.

We could do with better messaging here about the status of the two syncs, but I'd much rather spend the effort moving the media sync to the background as is done with Anki Desktop.

I'm going to close this as WONTFIX in favour of https://github.com/ankidroid/Anki-Android/issues/11430 (or similar work), which should greatly resolve both the time to complete the media sync, and the valid UX issues which are reported here.
