### ISSUE TITLE
Hide only the status bar without hiding the app bar

### ISSUE THREAD

**Issue by C3tacea** [ankidroid/Anki-Android#13272]
Hello, 

First and foremost thanks alot for this great app. 
I have already used this app long ago and I remember that the android system bar where the notifications are shown was hidden whereas the ankidroid app bar to turn on whiteboard etc was still visible, which I found very convenient as it reduces distractions while keeping everything fully functional. 
Now I only see to options to modificate this, hide the Systembars which unfortunately hides also the appbar or hide the Systembars and answerbars which even takes away more functionality.

**Describe the solution you'd like**
A third option which only offers to hide the android notification bar and puts the app into fullscreen without modifying anything inside the app, as many internetbrowsers have.

**Describe alternatives you've considered**
I tried to turn on the android system option to show the app itself to fullscreen but there is no option to modify ankidroid (android 13)

Thanks alot!

**Comment by n1snt** [comment]
This sounds like a good idea to add an option to hide only the status bar & navigation bar.
If this gets approved as an issue I would love to work on this.

**Comment by doozan** [comment]
I agree that the fullscreen options aren't clearly named and don't offer enough options.

"Hide the system bars" hides:
 - Android status/notification bar
 - Android navigation bar
 - App bar

"Hide system bars and answer buttons" hides:
 - Android status/notification bar
 - Android navigation bar
 - App bar
 - Answer buttons
 - Review counts bar

Rather than adding a third option to "HIde only the status bar & navigation bar", would it more sense to break this into some checkboxes:
- Fullscreen (hides android status/notification bar and android navigation bar)
- Hide app bar
- Hide review counts
- Hide answer buttons

The "hide" checkboxes that could either operate independently of the "fullscreen" button or be dependent on "fullscreen" being enabled. I'd lean toward the latter if the implementation isn't over complicated, but either one would give users better options.

Full disclosure: I personally want the option to check "Fullscreen", "Hide app bar", and "Hide answer buttons", leaving just the "Card count bar", which is not currently possible and seems like an overly complicated option to add to the dropdown list.

**Comment by n1snt** [comment]
There should be a toggle for full screen.
And when you tap on that entry instead of the toggle it should open a popup with checkboxes as mentioned by @doozan & allow users to customize the full-screen option.

**Comment by niteshmandall** [comment]
I want to work on this issue as I have previously solved this issue in another app on which I am working now. 
![Screenshot 2023-03-06 124855](https://user-images.githubusercontent.com/108911562/223221629-7a0a27da-6af5-433e-8bcf-a00b357fceac.png)
