### ISSUE TITLE
Display complete deck hierarchy when studying

### ISSUE THREAD

**Issue by pochopsp** [ankidroid/Anki-Android#13590]
### **Problem**

When studying a deck with several subdecks, the top bar will always show the subdeck the current card is from. This could cause unwanted ambiguity.

### **Example**

I have a deck structure as follows:
```
Programming
        C
           Keywords
        Java
           Keywords
```
On one card in Programming::C::Keywords I have the question "What is the static keyword for?"

Since in the top bar I can only see the name of the deepest deck in hierarchy (in this case "Keywords") I cannot know if the question is for the C language or the Java language (both have the static keyword).

### **Solution**

I suggest the following solution: display the whole deck hierarchy instead of only the deepest deck name, and in case it is too long we could ellipsize it, and show it complete only on tap.

**Comment by user1823** [comment]
In [this issue](https://github.com/ankidroid/Anki-Android/issues/12385), the current consensus is to remove the deck name entirely, which is consistent with the behaviour on Anki Desktop.

So, I think that you should include sufficient information in your question itself, instead of relying on the deck name in the title.

**Comment by noppytinto** [comment]
the full deck path is very useful for me, in the end everyone has its habits, I think having the option to display/hide the full deck path is not that bad!!! at all!

**Comment by snowtimeglass** [comment]
In terms of consistency with Anki desktop and de-complexity, I agree with @user1823 and @BrayanDSO about the deck name on the top of the screen. 

@pochopsp How about suggesting the feature to Anki Desktop first if it seems fairly desirable for Anki learning system?

That being said, I guess an alternative solution to this issue is adding `{{Deck}}` field (one of the special fields) to the template of the card. It automatically shows you the whole deck hierarchy on behalf of the suggested top bar.

![image](https://user-images.githubusercontent.com/10436072/232203032-2e442c39-15dc-4127-b585-7bdbd917a79b.png)

![image](https://user-images.githubusercontent.com/10436072/232197442-3ca9ead8-b425-4f95-bf56-6f555a290c07.png)
![image](https://user-images.githubusercontent.com/10436072/232202635-007de93c-ded1-4cec-a55b-fed6ebb8c589.png)

**Comment by pochopsp** [comment]
@snowtimeglass thanks for yuor suggestion.

I think the feature is indeed fairly desirable for Anki learning system, so I'm going to open the same issue on Anki Desktop.

The way things are now, I'll bypass the problem by using a Card Type with {{Deck}} as you suggested

**Comment by BrayanDSO** [comment]
I'm going to close this while this doesn't become an Anki ecosystem feature
