### ISSUE TITLE
MigrationService: Add "Get Help" button

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13641]
https://github.com/ankidroid/Anki-Android/pull/13368/files#diff-497bed2a68320fc3c1156390b99cf19c33838cca8f5d97886d37499986a5c458R217-R218

```
        // TODO BEFORE-RELEASE Add a “Get help” button
        is MigrationService.Progress.Failure -> {
            val copyDebugInfoIntent = IntentHandler
                .copyStringToClipboardIntent(this, progress.e.stackTraceToString())
            val copyDebugInfoPendingIntent = CompatHelper.compat
                .getImmutableActivityIntent(this, 1, copyDebugInfoIntent, 0)
```

**Comment by oakkitten** [comment]
What kind of help do we want to show here? Do we actually have any helpful information here?

Since we are pressed for time, I suggest creating an empty Wiki page here on GitHub and having the help button open it. Yes it will be in English only, but then it would be easy to implement, and we would be able to easily edit it to put in any new relevant information.

**Comment by david-allison** [comment]
I feel it'd be better in https://github.com/ankidroid/ankidroiddocs so we have some control over the content. Our wiki is publicly editable, and therefore not indexed by Google.
