### ISSUE TITLE
[BUG]: Play version of beta "updated" to 2.15.6 by Play Store

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13801]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Install the play version of the latest beta release (2.16.0beta1)
- Update all apps using Google Play Store.

### Expected behaviour

The AnkiDroid app shouldn't be updated because the currently installed version is newer than the one currently on the Play Store.

### Actual behaviour

The Play Store "updated" my app to v2.15.6

### Debug info

```text
Couldn't share the debug info from v2.15.6 because it shows the error saying that the database version is newer than that supported by the app.

Couldn't re-install the play version because the installation fails with the error: App not installed as package appears to be invalid.

So, installed the full version and sharing debug info from that one. 

AnkiDroid Version = 2.16.0beta1

Android Version = 12

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-6; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
If you installed the latest beta version. It's possible that Playstore will not update this app again

**Comment by user1823** [comment]
> If you installed the latest beta version. It's possible that Playstore will not update this app again

I am not sure what you mean by this.
The Play Store updated the play version of the latest beta but it didn't update the full version of the latest beta.

**Comment by mikehardy** [comment]
I wonder if this is because we are doing an incremental rollout of the beta and currently have asked the play store to only deliver 2.16.0beta1 to 20% of the available beta subscriber pool 🤔 

They should not downgrade you, but at the same time I am not in control of that.

And because storage migration is a one-time process that will never be repeated even with future betas I must reserve some of the beta pool for delivery of beta2, beta3 etc. So I cannot really go back on this decision unfortunately.

It should resolve shortly though, in a matter of days.

As a workaround use parallel.A I think so you can keep an up to date version local while we work through our 2.16 release process

Sorry for the hassle

**Comment by mikehardy** [comment]
Another possible workaround - if you subscribe to the alpha testers list, 2.16.0beta1 (and all future betas...) are rolled out at 100% on the alpha channel.

https://ankidroid.org/#alphaTesting

**Comment by user1823** [comment]
I think that I am fine with the full version of the beta for now. I will switch to the public version of the app once the normal cycle of releases resumes.

(I switched to the alpha/beta releases because there was no clarity about when the public version was going to be released and I needed to use the v3 scheduler.)

**Comment by mikehardy** [comment]
2.16.0beta2 has been released to the play store with 40% rollout - so this version may be available or may not be available depending on whether google pseudo-randomly assigns you to the rollout population. We are still carefully rolling out 2.16 betas in this way so please continue to bear with us.

As mentioned above, for anyone interested:
- you can always grab the release directly from here: https://github.com/ankidroid/Anki-Android/releases
- if you join the alpha program you will *definitely* get the release: https://ankidroid.org/#alphaTesting

In the meantime we will continue with the staged rollouts until we're comfortable we won't crash everyone with the massive amount of changes + storage migration in 2.16

**Comment by BorisNA** [comment]
Something is still wrong with the beta builds. If I install play-universal or full-universal (beta5), play store insists on updating it to 2.15 (!). If I install arm64-v8a, play store doesn't mind, but I do get slooooow media update in Android/data location.

This is strange, since if you sideload an apk with higher version number (alpha, new stable, whatever), even if it is not available in play store at this moment (haven't rolled out for you yet), it won't get "outdated". 

Why is it not so for AnkiDroid? Should I be on beta in the play store?
