### ISSUE TITLE
[Bug] Accessibility issue - Deck overview Number contrast too minimal (2.16b)

### ISSUE THREAD

**Issue by MarkusJLechner** [ankidroid/Anki-Android#13889]
###### Reproduction Steps
This is new since 2.16 beta. Is it s desired feature or unnoticed change?

1.  Go-to deck overview
2. Inspect the 3 numbers to the right

###### Expected Result
The Zeros (0) have a higher contrast to the important numbers new - relearn - review. This is the behavior in version 2.15

(Source Google images, running two versions on phone is not possible)
![Screenshot_2023-05-18-06-24-16-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ankidroid/Anki-Android/assets/48199873/e6369592-cd7e-44c3-b0f4-19f899e76edf)
###### Actual Result
0s are too bright. 
As a user, i want to easily see which decks need how many reviews. 0 is no value information. The contrast between light gray and the actual light blue/green/red is too minimal to differentiate.
Numbers bigger than 0 are from value, 0 shouldn't be that present. Alternatively using a different character instead of 0 to mark a bigger difference, like a centered dot: • 3 •. However, this is a bigger change to be evaluated.

![Screenshot_2023-05-18-06-22-28-58_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/555bd2ed-781b-45ce-b373-205684cefb9f)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
> Is it s desired feature or an unnoticed change?

Yes, it's a desired feature, because the zeroes are not adequately visible in dark and black mode.
As @Subhadiptech creared an issue #12952 against

**Comment by MarkusJLechner** [comment]
The contract between gray and the other colors is definitely higher in the black theme than the dark theme. It seems that the gray does not adjust to the theme (background).

In issue #12952 I have the same opinion as the issuer, dark gray was nearly not visible at black theme. However I couldn't said that same issue on dark theme before. 

The remaining issue is that the "finished" indicator 0 with a brighter color makes the remaining "to be done" numbers harder to disguingish. Since the update, a amount of focus needs to be done on which deck has something else than zeros. Glimpsing through the colors on the right happened to be more difficult since the update. 
0 has in this case less value than a number.

**Comment by snowtimeglass** [comment]
>0s are too bright.
As a user, i want to easily see which decks need how many reviews. 0 is no value information. The contrast between light gray and the actual light blue/green/red is too minimal to differentiate.

I agree that more faint color for the zero counts would be desirable considering their role. How about re-adjusting the color to some extent, for example as follows. I would appreciate opinions on how others feel about them.

**Color comparison of zero counts**
Same as v2.15.6 (might be too dark) |v2.16.2 (might be too bright)|
---|---|
#202020![image](https://github.com/ankidroid/Anki-Android/assets/10436072/2aae39ff-0ac2-456e-a647-042a7bcc20f9)|#808080![image](https://github.com/ankidroid/Anki-Android/assets/10436072/f653a8c6-191e-4e31-879d-da4e0b02eebc)
#202020![image](https://github.com/ankidroid/Anki-Android/assets/10436072/f2d4e45a-8482-4ff9-9273-72f232efadcf)|#808080![image](https://github.com/ankidroid/Anki-Android/assets/10436072/8247a93e-64eb-4612-86cf-c7f3684547f5)

v2.16.2 (might be too bright)|Suggestions|
---|---|
#808080![image](https://github.com/ankidroid/Anki-Android/assets/10436072/f653a8c6-191e-4e31-879d-da4e0b02eebc)|#404040![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a391e6fb-5b81-4744-8994-af80ab2d0f91)
#808080![image](https://github.com/ankidroid/Anki-Android/assets/10436072/8247a93e-64eb-4612-86cf-c7f3684547f5)|#505050![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d0102565-9837-48a6-8af2-4fd3eee72bd9)

**Comment by snowtimeglass** [comment]
More faint versions
black|dark
---|---|
#303030![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d47bb54f-54ac-4e8a-9245-d1e084aa908a)|#404040![image](https://github.com/ankidroid/Anki-Android/assets/10436072/fb127e10-d333-45e8-84c2-79d04f1bdca6)

**Comment by BrayanDSO** [comment]
After giving this a thought, maybe reverting back to the previous color would be okay. The goal of the dimmed numbers is to not call attention, so it doesn't matter if they can't be easily seem

**Comment by MarkusJLechner** [comment]
> More faint versions
> `#303030` | `#404040`

definitely a big improvement! As i work daily with anki, this would make browsing my 15 "to be done" decks easy again. Since opening the issue i see myself of focusing a lot of time on which deck has something different than 0s, instead of seeing it at a glimpse.

**Comment by snowtimeglass** [comment]
Thank you for the feedbacks. 

>maybe reverting back to the previous color would be okay.

I also feel that the reverting might be okay, about the black theme. When viewed on a smartphone device (not on a PC screen), those `#202020` 0s looks bright enough for me.

However, as for the gray theme, reverting back to the previous color might not be good, because the 0s was darker than the background gray. That might make the 0s a bit stand out, against the intention of not to call attention.


---|---|
---|---|
Same as v2.15.6 `#202020` (might be rather conspicuous with the darkness)![image](https://github.com/ankidroid/Anki-Android/assets/10436072/894351de-5ca0-4fea-948d-febcaec985db)|`#303030` (invisible other than the case of the selected deck)![image](https://github.com/ankidroid/Anki-Android/assets/10436072/9b793604-5ce5-42e7-a931-70c603bae336)
`#353535`![image](https://github.com/ankidroid/Anki-Android/assets/10436072/40e0fd3a-674b-48c4-8d61-027502d0f985)|`#383838` (invisible in the selected deck)![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0979aa31-3b8a-4263-bb6f-e5d2e5751b57)
`#3C3C3C`![image](https://github.com/ankidroid/Anki-Android/assets/10436072/6557e4ba-2da7-4c6e-8c75-2dc3de0d74b4)|`#404040`![image](https://github.com/ankidroid/Anki-Android/assets/10436072/fb127e10-d333-45e8-84c2-79d04f1bdca6)
|Black theme `#202020` (Same as v2.15.6) ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ce648fa4-9798-41d2-b4c1-7097eb5e4a93)|Light blue theme![image](https://github.com/ankidroid/Anki-Android/assets/10436072/72fb953c-2d5c-4c11-868e-12a52802fdc8)

It would be desirable to emphasize the contrast with the other fuzzy colors (the background dark gray and other number's  pale colors) of that theme, while maintaining consistency with the 0's visibility on the rest of the theme. Considering this balance, `#404040` might be better than others for the dark gray theme.

**Comment by BrayanDSO** [comment]
`#404040` looks good to me as well

**Comment by Subhadiptech** [comment]
Thanks @snowtimeglass for pulling out this issue.
