### ISSUE TITLE
 Show the selection of the last study of the card in the study

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#13894]
**Is your feature request related to a problem? Please describe.**

When a card enters the learning phase and we encounter it again in the learning phase, I think the software should prompt the person what option he chose last time, whether it was AGAIN, HARD or GOOD

**Describe the solution you'd like**

When a card enters the learning phase, some cards usually require many clicks of the AGAIN, HARD or GOOD button, and I want to know which button I clicked last time
**Describe alternatives you've considered**

The last button clicked has something different to show, like the ability to add an aperture?

**Additional context**

This is an English learning software borrowed from anki, the Chinese in the middle actually means "hard", you can see a small Chinese in the upper right corner, his once is "last time", which tells me that I chose this last time.
![Screenshot_20230519_093711](https://github.com/ankidroid/Anki-Android/assets/112467275/713f7725-a1cf-4157-b08e-8dea379a5860)

**Comment by BrayanDSO** [comment]
From a learning standpoint, why do you want to know which was the last button you pressed while reviewing?

If it is just out of curiosity, you can use the card info menu option.

**Comment by BrayanDSO** [comment]
> Don't you have this experience?

If you mean forgetting things while learning a new card, yes. 

But how do showing the last button you pressed helps you? Does it serve as some kind of progress feedback? Like knowing that last time the card was "hard" so you should pay more attention to it? This seems like a valid concern to me. 

Personally I want to avoid as much cognitive as possible and just focus on learning, so to me it only matters if I remember the card right now, not if I remembered in the past, which is the point of using a memorizing tool.

I wouldn't support this as a feature bundled by default in the app because people already think that the app is too complex and this isn't included on Anki desktop. But I do support making this possible with the Javascript API in the future (maybe it is already) by fetching the last reviews data, so someone can implement this on a note type
