### ISSUE TITLE
Add "Last Reviewed" and "Days Since Last Reviewed" special fields for use in templates 

### ISSUE THREAD

**Issue by redfish64** [ankidroid/Anki-Android#13953]
**Is your feature request related to a problem? Please describe.**
I want to know how fast cards are increasing their delay before being shown again, so I can get better feedback when tweaking values.

**Describe the solution you'd like**
Add special hardcoded fields {{LastReviewed}} and {{DaysSinceLastReviewed}} across all Anki platforms including AnkiDroid

**Describe alternatives you've considered**
No, didn't do that.

**Additional context**
I was able to add this feature to my fork of AnkiDroid. I didn't add it to Anki proper though and of course can't add it to Anki for iphones. It shouldn't be hard, though. I guess there is the documentation too, though, so I dunno. I could do some of these updates if people like it. 

Here is my fork (contains only this one feature): https://github.com/redfish64/Anki-Android

Here is a screen shot with the change in action:

![Screenshot_20230605-144321_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/1922770/6286645f-e98d-4f17-bb40-8811469dc231)

**Comment by BrayanDSO** [comment]
For features like this, the ideal is to implement it on Anki Desktop first so the other platforms can have equivalent implementations (or even equal implementations since some things are shared in the same backend).

Since apparently you can code, have you tried using AnkiDroid's JavaScript API to do this? (https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt)

**Comment by BrayanDSO** [comment]
> Do you think the feature would work better as part of Anki proper and would
it be integrated if I coded it for Anki desktop?

I can't tell. Better asking it on the Anki forums

**Comment by dae** [comment]
Closing as this is not supported by the desktop. Support for this use case will probably take a while, as the current field-replacing approach is not efficient.
