### ISSUE TITLE
Crashes when using Instant-Add API when targetSdkVersion=33

### ISSUE THREAD

**Issue by hanpingchinese** [ankidroid/Anki-Android#14108]
My app (Hanping Chinese) has been using the Instant-Add API for many years now without a problem. Recently I increased the `targetSdkVersion` to 33, and have since noticed (in Crashlytics) several exceptions thrown from this API. It's not a huge number, but is a very significant increase so perhaps some devices are behaving differently to others. I cannot reproduce these problems on my own device however.

Some examples:

1. When getting note types (Android 13 (Zenfone 8), Android 11 (OnePlus 6/OnePlus 7 Pro), AnkiDroid 2.15.6, 3 users):
`java.lang.IllegalArgumentException: Must set a non-null context to create the configuration`
2. Also when getting note types (Android 13 (Pixel 7 Pro), Android 11 (Nokia X100), AnkiDroid 2.15.6, 2 users):
`java.lang.IllegalStateException: AnkiDroid database inaccessible. Open AnkiDroid to see what's wrong.`
3. When inserting note type (Android 13 (Galaxy Buddy, Galaxy A71), AnkiDroid version unknown, 2 users)
`java.lang.IllegalArgumentException: Unknown URL content://com.ichi2.anki.flashcards/models`

I wonder if the `ContentProvider` is running in the third-party app process and so doesn't have access rights to the database?

I'm curious if anyone else has noticed this?

###### Actual Result

These are observations from Crashlytics so I don't have reproducible steps unfortunately

###### Debug info
AnkiDroid 2.15.6

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hey - sorry for the crashing of course. I wonder if this will resolve with 2.16 rolled out? 2.16 is now in general release as of around August 5th or so, and we crossed over 50% adoption as of around August 11.

We won't be able to issue any kind of updates to 2.15 so I would (unfortunately...) just ignore those reports. 2.16 is the only version series we'll be able to respond to

Perhaps related, we are updating to API33 as well, you may track that here #14129 - hopefully we'll have that out quickly so know we have handled any issues there....

**Comment by hanpingchinese** [comment]
Thanks @mikehardy . The crashes do appear to have reduced, but that could be explained by users that got the crashes, no longer using the feature. Today I got this from a Galaxy Z Fold 4 (Android 13) device and using AnkiDroid 2.16.2:

`Unknown URL content://com.ichi2.anki.flashcards/models`

**Comment by hanpingchinese** [comment]
Still getting this exception (`Unknown URL content://com.ichi2.anki.flashcards/models`) from multiple devices (running AnkiDroid 2.16.5). Some interesting points:

- All are Android 13
- 81% are Samsung (6 different devices including S23)
- 19% are Xiaomi (Xiaomi Civi 3 and Redmi Note 13 Pro)
- no other brands

**Comment by hanpingchinese** [comment]
I wonder if it's related: https://github.com/ankidroid/Anki-Android/issues/14423

**Comment by mikehardy** [comment]
🤔  it could be, I wonder if these are users that have not done the storage migration - so we are still trying to access general storage ? I'm not sure if that is even possible, and if so how to handle it.

Really suspicious that it's all Samsung + Xioami

Do you have any sort of logcat or full trace from one of the crashes?

**Comment by hanpingchinese** [comment]
Looking more carefully, it's actually only 9 distinct users, so I guess the brand distribution isn't that significant. Also I noticed some of the instances are from AnkiDroid 2.15.6 FWIW.

The stacktrace is simply:

```
java.lang.IllegalArgumentException: Unknown URL content://com.ichi2.anki.flashcards/models
       at android.content.ContentResolver.insert(ContentResolver.java:2196)
       at android.content.ContentResolver.insert(ContentResolver.java:2162)

```
This is called when my app inserts a new note type, which will automatically happen when it notices the note type does not already exist.

I had a look at the Android 13 dev docs [behaviour changes](https://developer.android.com/about/versions/13/behavior-changes-13) and tried a few things like:

```adb shell am set-standby-bucket com.ichi2.anki restricted```

but I wasn't able to reproduce the problem. Also, I don't have an Android 13 Samsung device to test with.

**Comment by mikehardy** [comment]
Hey @hanpingchinese - I'm still getting a fair number of support requests that I *think* are from people with this setup:

1- were running AnkIDroid 2.15.x, granted storage permission, have *not* done the storage migration
2- Play Store updates them to AnkiDroid 2.16.x, storage permission still granted, have *not* done storage migration
3- They don't use the app for a little while and Android operating system *removes* the storage permission

Now they are in a situation where they cannot grant the storage permission, and AnkiDroid cannot access the collection.

The solution that works is having them install the full/universal build from https://github.com/ankidroid/Anki-Android/releases/tag/v2.16.5 with a warning that they really need to do the storage migration, then they can install from Play Store again

To see if this addresses your issue here you could install 2.15.x directly, grant permission and get a collection going (but without your note type...)

Then install 2.16.x play store version, do *not* do the storage migration and somehow (via adb?) revoke the storage permission (but do not add your note type...)

Now try to do the use case in your app that adds the note type?

We'll need a real crash trace in order to figure this out though. You should make sure to use the latest API artifact (#14790) and you should test on latest 2.17alphas to make sure you have latest fixes ( #14836  #14847 )

Until this has a crash trace or reproduction scenario we can really work with I'm going to close this, but we're paying attention - happy to reopen once we have actionable stuff that we know reproduces even after the recent API artifact / code fixes

**Comment by hanpingchinese** [comment]
Thanks very much for taking the time to lay out the detailed steps Mike.

I tried it on Android 14 (my Pixel 7a) and when I got to the second part (installing from Play Store), I was not asked about "storage migration". I was only asked about if I wanted to backup my database, which I think is different. When I went to the App permissions screen I didn't see anything about storage permission. Shouldn't it at least appear in the All Permissions screen?

Note - I did all of these steps without doing anything from Hanping (so no granting of the read/write to AnkiDroid database permission)

**Comment by david-allison** [comment]
I believe this is being tracked:

* https://github.com/ankidroid/Anki-Android/issues/14423#issuecomment-1777536234

**Comment by mikehardy** [comment]
Oh I hadn't considered the Android version skew. I suppose you have to test this on an Android 11 or 12 emulator? I apologize I haven't had time to read the rest 😬

**Comment by hanpingchinese** [comment]
Is there a user-friendly link I can direct customer to, to help them resolve this?
