### ISSUE TITLE
Update to targetSdkVersion 33 - ideally in 2.16, deadline Oct 31 2023

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14129]
_[Starting on August 31, 2023:
    App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; 
except for Wear OS apps, which must target Android 11.](https://developer.android.com/google/play/requirements/target-sdk)_

Issue to track things that need to be changed when targetSdkVersion is upgraded to 33

**Comment by lukstbit** [comment]
_[Starting on August 31, 2023:
    App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; 
except for Wear OS apps, which must target Android 11.](https://developer.android.com/google/play/requirements/target-sdk)_

**Comment by BrayanDSO** [comment]
> _[Starting on August 31, 2023: App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; except for Wear OS apps, which must target Android 11.](https://developer.android.com/google/play/requirements/target-sdk)_

lovely. But maybe we can finish the 2.16 rollout until the deadline

**Comment by lukstbit** [comment]
I did an update to Android 12(and looked through the changes) and everything seems to be ok.

**Comment by BrayanDSO** [comment]
Actually, in another link, [Starting August 31, 2023: Existing apps must target API level 31 or above to remain available to users on devices running Android OS higher than your app's target API level. You will be able to request an extension to November 1, 2023 if you need more time to update your app. You'll be able to access your app's extension forms in Play Console later this year.](https://support.google.com/googleplay/android-developer/answer/11926878?hl=en&sjid=2747974539653313127-SA)

**Comment by lukstbit** [comment]
I missed that, this is great news.

**Comment by mikehardy** [comment]
I requested more time and the extension was auto-granted.

The deadline for this is Oct 31, 2023 and the effect will be that new users with Android devices running Android13/API33 or higher will not see us in the play store until it is updated.

I would like to get this done before starting major work on 2.17 *because I think it will be quick*, but I applied for extra time so there is no pressure regardless.

*It may be quick enough to do before the release-2.16 support branch cut even, so updates to that branch are releasable*

The list of changes looks like it mostly does not affect us with the exception of these that need testing, possibly changing:

- how does dark mode affect the webview usage in our app? Check light/dark mode while reviewing and while loading changelog or external sites etc
- how do the new granular image/audio/video media permissions affect our ability to acquire external files when adding to cards - check adding image/audio/video both as creative activity (recording audio, capturing image or video) and as selection activity (choosing a file from gallery or similar)

I do not believe the list of changes affects in other ways but here is the link:
https://developer.android.com/about/versions/13/behavior-changes-13

**Comment by david-allison** [comment]
We're on targetSdkVersion 31.

This also requires `targetSdkVersion 32` (Android 12L):

> Android 12L (API level 32) is a minor release that makes Android 12 even better on large screens. There are no breaking changes, but you should review the 12L features and changes and test that your app works well on large screens. Then update your app's targetSdkVersion to 32.

* https://developer.android.com/about/versions/12/12L/summary
* https://developer.android.com/about/versions/12/behavior-changes-all#multi-window-mode

What this actually means:

> On large screens (sw >= 600dp), the platform supports all apps in multi-window mode regardless of app configuration. If [resizeableActivity="false"](https://developer.android.com/guide/topics/manifest/application-element#resizeableActivity), the app is put into compatibility mode when necessary to accommodate display dimensions.

**Comment by mikehardy** [comment]
Great pointer @david-allison - I added a specific action item on that one, 3 things to test+triage now
I'll post a PR that can serve as a basis for this in a moment - robolectric has an upstream issue preventing us from just changing build.gradle and I've already fuzz-busted through that so no one else should waste their time...

✅  I've verified locally that our usage of theming seems to work fine with our usage of WebViews (specifically I checked access of Changelog from prefs, I checked Anki manual and AnkiDroid FAQ which were all themed correctly light or dark depending on follows-system or app-specific theme)

❓  just need to test audio/image/video acquisition now
