### ISSUE TITLE
[BUG]: Screen is unexpectedly highlighted with gamepad's UI navigation when answering cards

### ISSUE THREAD

**Issue by AtilioA** [ankidroid/Anki-Android#14142]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Connect a gamepad (I have only tested Bluetooth controllers);
2. Make sure you have set controls to answer cards on AnkiDroid's settings;
3. Review a deck: answer with the buttons you have assigned;
4. After the first answer, the whole screen will have a highlight from Android's gamepad UI navigation.

NOTE: I cannot reproduce this issue with ALL keybindings I set for answering cards, but I tested setting only one button and also setting multiple buttons. Sometimes, reassigning them will cause another keybinding to cause the issue.
I tested face buttons, shoulder buttons, d-pad, and start, in different order of assignments. I couldn't find the steps to reproduce the issue with a particular button, but at least one of them will cause this issue; from my experience, this happens a lot with the d-pad and face buttons.

### Expected behaviour

A new card should appear without highlighting from gamepad's UI navigation.

### Actual behaviour

A new card appears, but the screen is highlighted as a UI element.

### Debug info

```text
AnkiDroid Version = 2.16.0beta5

Android Version = 13

ProductFlavor = play

Manufacturer = motorola

Model = motorola edge 30

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; motorola edge 30 Build/T1RDS33.116-33-3-2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = 69ebb9c6-295d-4aa8-9fda-2bca62a28367

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Video showcasing the issue:
https://github.com/ankidroid/Anki-Android/assets/27153776/afdf99d4-60e2-4c8f-8b91-171f1f571a8d
This was reproduced using the d-pad down button. This usually happens with face buttons as well (I recently managed to make the A button not trigger this issue).

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I've seen this before while using an external keyboard.

Not sure if this behavior existed before. If not, finding the first bad commit will be essential

**Comment by AtilioA** [comment]
> Not sure if this behavior existed before. If not, finding the first bad commit will be essential

I believe this has always been a problem. However, this may also be attributed to newer Android versions (I don't have any devices with Android versions older than 13 to test this).

I was able to reproduce it on `2.16alpha45` (one of the first versions with this feature), `2.15.6`, and `2.14.0` (these last 2 still didn't allow mapping controls).

**Comment by MarkusJLechner** [comment]
Unintentionally opened an issue, targeting the same topic. Here is my original message:

**Option 1: Using a Bluetooth Keyboard**
1. Connect a Bluetooth keyboard.
2. Go to the deck.
3. Press space, then 4.

**Option 2: Using an (Xbox) Bluetooth Controller**
1. Connect an (Xbox) Bluetooth controller.
2. Assign a key to a joystick or trigger (seem to always trigger the problem).
3. Go to the deck.
4. Press one of the assigned keys.

###### Expected Result
The screen's brightness/contrast should not change.

###### Actual Result
Instead, the screen appears as though it has been selected or highlighted. This state persists through the cards, and the only ways to fix it are to either exit to the deck overview or close the app altogether. This issue makes using Bluetooth devices unfeasible.

The problem has been around for a while and is a regression issue. Although I can't pinpoint the exact update that caused it, it appeared around the 2.15 life cycle. The temporary solution was to simply avoid using Bluetooth devices.

Normal:
![Screenshot_2023-08-14-05-52-30-16_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/25a41db7-1930-44b8-854a-dc71b2721a0a)

Highlighted
![Screenshot_2023-08-14-05-57-19-65_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/427720f1-d2d7-4526-ab40-5b21099c9286)
<img src="https://github.com/ankidroid/Anki-Android/assets/48199873/846f8a22-f810-4ab7-811d-4f9947de0c91" width="180">

---

The problem has indeed existed for a long time. Ever since the issue appeared, it has made using external devices more than just a hassle.
