### ISSUE TITLE
Re-add chess notation support

### ISSUE THREAD

**Issue by szukiadam** [ankidroid/Anki-Android#14205]
**Is your feature request related to a problem? Please describe.**
After #14092 chess notation support was removed, breaking some of my Anki decks. Could you re-add this feature, or is there a way to use an older version of Anki without experiencing problems in the future? 

**Describe the solution you'd like**
Chess notation support to be back. 

**Describe alternatives you've considered**
Using an older version of AnkiDroid, but it seems unstable and likely to break. Also not sure if there is a way to get such a version officially.

**Comment by BrayanDSO** [comment]
I'm sorry, but the feature won't be added again because of the reasons at https://github.com/ankidroid/Anki-Android/issues/14092#issue-1788287350. This kind of thing should be in your notetype.

To add into a notetype, this could be reverse-engineered from the previous [chess filter code](https://github.com/ankidroid/Anki-Android/pull/14097/files#diff-3a7df5c224938a2b31c64f29cc81cac3463cd5c0af7f539227b8d20e66ae0f26)

---
About the 2.15.6 question, you can download it [here](https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.6) and keep using it

**Comment by mikehardy** [comment]
As a side note, this really *should* be in a note template but it does not appear that anyone has implemented a *current* cross-platform note type that just does FEN.

It really is (was) just a javascript function though:

https://github.com/ankidroid/Anki-Android/pull/14097/files#diff-3a7df5c224938a2b31c64f29cc81cac3463cd5c0af7f539227b8d20e66ae0f26

In that file it basically does this:

1) Is this FEN? And does the user want FEN rendered or note? (looked up in preferences, but if it's a note type, you can just assume it should be rendered and simply grab the FEN string by the pattern match)
2) Okay, it's FEN. Do we show black or white first? (determined by pattern matching against the FEN string)
3) Okay, we defined a big render FEN function earlier, send the FEN through there with correct black/white orientation

That's all possible in javascript, in a note type and that is really how it *should* be done. Just needs someone interested enough to do it (and I have enough hobbies, not picking up chess at the moment...)

**Comment by szukiadam** [comment]
@mikehardy I agree 100%. Didn't see the resources you've linked, so thank you for that. Due to my laziness I decided to use an older version instead of implementing the note template myself, but for anyone interested your comment is of high value.
