### ISSUE TITLE
Controller mapping limitations

### ISSUE THREAD

**Issue by fredjoe7** [ankidroid/Anki-Android#14241]
While controller mapping in ankidroid has decent functionality, it's limited as there is no option for toggle next cloze or toggle next occlusions using image one by one

The recent note types have been implementing image occlusions one by one or multiple clozes with Cloze one by one . Like for example the ankingnotetype which uses cloze one by one feature which is very handy and can be controlled well in desktop anki with a controller. 

But the same card in ankidroid can only be navigated using touches as there is no way to map keys for that functionality. 

Can someone look into this and improve the controller mapping to include toggle next cloze and  one by one functionality  ..
Thank you.

**Comment by AnKingMed** [comment]
I'm also interested in this. Are there any plans to implement something to support the useractions that iOS are using?

**Comment by BrayanDSO** [comment]
Image occlusions will be implemented into the desktop version eventually, and we are porting the desktop reviewer (#14302), so the behavior should be the same eventually.

About clozes one by one, I believe that it can be solved with custom Javascript user actions, like Anki Mobile does and other people have proposed #14286.

Since all the requests solutions are being tracked in other issues, I'm closing this one. Feel free to ping me if you want it reopened
