### ISSUE TITLE
about Automatic display answer

### ISSUE THREAD

**Issue by GTXxeon** [ankidroid/Anki-Android#14254]
in Anki-Android，The automatic display only supports a time greater than 1 second. 
I hope it can be set to 0 and display the BACK directly. 
Because my front just the audio of the sentence, or it can exclude the time for automatically played audio fields

**Comment by SanjaySargam** [comment]
This is not as expected.
The AnkiDroid expects you to listen to the whole audio first and then the answer will be shown.
Just imagine, you don't know the question (audio) then what's the point of seeing the answer

**Comment by david-allison** [comment]
You should be able to use the [AnkiDroid API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#show-answer) to flip the card immediately. 

This isn't intended functionality for _Automatic display answer_

**Comment by extr15** [comment]
I want to directly display the BACK too. 
Sometimes I just want to let AnkiDroid automatically play some cards, thus I can put my cellphone aside and do something else. This is Not for a regular review process but I just want to enhance my memory of some specific cards in my fragmented time, so I don't need the front side here.

Btw, I found even if I set 1 second of `Time to show answer`, it still took **several** seconds before showing the answer? I have a audio in my card's front side, and when the audio finished, it still took several seconds instead of 1 second to show the answer.
Thanks for your work!
