### ISSUE TITLE
Ankidroid considers d pad and left joystick as same inputs

### ISSUE THREAD

**Issue by salmanuc** [ankidroid/Anki-Android#14282]
**Is your feature request related to a problem? Please describe.**
When mapping keys in controls for ps4 controller, the app is unable to differentiate between d pad and left joystick and therefore registering them as same input. 

**Describe the solution you'd like**
The app should be able to differentiate between these two different inputs.

**Comment by david-allison** [comment]
I believe that this is out of scope for AnkiDroid, we just relay the inputs which your system provides. If your system says the buttons are the same keycode, there's likely nothing that we can do

Unless there's some way on our end to differentiate the inputs, then there's nothing we can do to fix this.

You're likely best to try a keymapper app

**Comment by david-allison** [comment]
Got myself an 8Bitdo Ultimate and can reproduce this. Given the feedback above, this is fixable, so we should fix it

**Comment by salmanuc** [comment]
The app also does not recognize right joystick movement (up, down, left, right).

**Comment by david-allison** [comment]
* There are a massive number of axes which can be provided
* There is overlap between a button press and a `MotionEvent`
* If the `MotionEvent` is handled, then the key press is not sent
* You cannot seem to query an event for which axes it has efficiently
  * On the calibration screen, that doesn't really matter 
* Some axes are [-1, 1] others are [0, 1]

I presume the axes are non-standard: my controller uses `AXIS_BRAKE`/`AXIS_GAS` instead of `AXIS_RTRIGGER`

My controller doesn't appear as a joystick, it's a `TOOL_TYPE_UNKNOWN`

We need to be sure a user can 'block' an axis: OP may not want up/down/left/right to be mapped to two separate input schemes (or may not want all 4 axes of the joystick to be mapped)

We need to be sure that random movement will 'lock out' the control input screen

(future): thresholds/dead zones

<details>

<summary>Debug Code</summary>

```kotlin
val axes = listOf(
            // (left joystick) - also mapped to D-Pad
            MotionEvent.AXIS_X, // 1 = right, -1 = left
            MotionEvent.AXIS_Y, // 1 = down, -1 = up
            // right joystick
            MotionEvent.AXIS_Z, // 1 = right, -1 = left
            MotionEvent.AXIS_RZ, // 1 = down, -1 = up
            // left bumper - also mapped to L2
            MotionEvent.AXIS_BRAKE,
            // right bumper - also mapped to R2
            MotionEvent.AXIS_GAS,

            // unhandled on my 8BitDo Ultimate Controller (2.4ghz)

            MotionEvent.AXIS_RTRIGGER, 
            MotionEvent.AXIS_LTRIGGER,
            MotionEvent.AXIS_DISTANCE,
            MotionEvent.AXIS_GENERIC_1,
            MotionEvent.AXIS_GENERIC_2,
            MotionEvent.AXIS_GENERIC_3,
            MotionEvent.AXIS_GENERIC_4,
            MotionEvent.AXIS_GENERIC_5,
            MotionEvent.AXIS_GENERIC_6,
            MotionEvent.AXIS_GENERIC_7,
            MotionEvent.AXIS_GENERIC_8,
            MotionEvent.AXIS_GENERIC_9,
            MotionEvent.AXIS_GENERIC_10,
            MotionEvent.AXIS_GENERIC_11,
            MotionEvent.AXIS_GENERIC_12,
            MotionEvent.AXIS_GENERIC_13,
            MotionEvent.AXIS_GENERIC_14,
            MotionEvent.AXIS_GENERIC_15,
            MotionEvent.AXIS_GENERIC_16,
            MotionEvent.AXIS_HSCROLL,
            MotionEvent.AXIS_ORIENTATION,
            MotionEvent.AXIS_PRESSURE,
            MotionEvent.AXIS_RUDDER,

            MotionEvent.AXIS_RX,
            MotionEvent.AXIS_RY,
            MotionEvent.AXIS_HAT_X,
            MotionEvent.AXIS_HAT_Y

//            AXIS_RELATIVE_X,
//            AXIS_RELATIVE_Y,
//
//            AXIS_GESTURE_X_OFFSET,
//            AXIS_GESTURE_Y_OFFSET,
//
//            AXIS_GESTURE_PINCH_SCALE_FACTOR,
//            AXIS_GESTURE_SCROLL_X_DISTANCE,
//            AXIS_GESTURE_SCROLL_Y_DISTANCE,
        )

        for (axis in axes) {
            val value = event.getAxisValue(axis)
            if (value == 0.0f) continue
            Timber.w("%s %s", MotionEvent.axisToString(axis), value)
        }
```

</details>
