### ISSUE TITLE
Remove Custom Fonts setting

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14343]
I mean the `Fonts` setting at the `Appearance` section. It was added ˜11 years ago and have not got much care since then. 

Currently it needs some work because the AnkiDroid directory is not accessible by common means in Android 10+ devices with the play store version, because of scoped storage. This means that the user cannot add a custom font to use it.

Also, the default font options provided by the preferences (Open sans light, bold, etc) do not work at all in the Samsung phones I have tested, although I recall them working in the emulator.

Additionally, the default way to use custom fonts is by embedding them in the media files so the font can be reused along all of the Anki ecosystem.

Probably the goal of the setting was to fix possible issues with languages with many characters if the system font could not handle them all, like chinese. Or maybe because someone just wanted to use a different font and then implemented the feature. Since Android has evolved a lot since then, most likely the feature is not necessary nowadays and should be removed

**Comment by dae** [comment]
Another possible reason is because AnkiDroid is reloading the webview on each page transition, and that may have led to poor performance, and out-of-memory conditions if the webview wasn't properly freeing up memory. That should be largely avoided if AnkiDroid can switch from reloading the page each time to using a persistent page that only updates the text.

**Comment by pratyaksh1610** [comment]
I will look into it and resolve it.

**Comment by AasheeshLikePanner** [comment]
I think most of the people don't care about the font and being lazy to change the font. so, It was good to remove

**Comment by PinyoTenor** [comment]
Dear @dae !

Sorry for writing from out of nowhere!
I am really new in the Anki and in the github as well. 
I created a deck, which I use for learning chinese. There I created some cards, which automatically creates 3 types to test my character, pinyin and translations. That works fine. BUT:
I wanted to use a font called KaiTi. So I put the file on my pc to the collection.media folder. I set up the fronts and backs of the cards, so that I can use this for only the Chinese character fields (for the latin characters its super ugly...). Everything looks nice on PC, but when I open on my phone, it doesnt show me the custom font. It only shows the default. After opened my phone folder for anki, and tired to put there the file as well to make sure it will woek, the _Kaiti.ttf was already there (i guess the sync brouht there). Still still only showing the regular. So I opened the settings on my phone, and there I set up to use Kaiti as default font + I ticked the always use option as well. Now it shows the correct font, but now all the text is like that. Its really annoying.

Could you help me please to solve this?
Thank you!
