### ISSUE TITLE
Use the backend's congrats screen

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#14361]
Currently AnkiDroid has its own code for rendering the congrats screen. If it instead displayed congrats.html/js when the deck is finished, it would display the same text as the desktop version, and would allow the removal of some AnkiDroid-only code.

**Comment by criticalAY** [comment]
David mentioned to work on it

**Comment by BrayanDSO** [comment]
Huh, the congrats screen sends a `bridgeCommand` request instead of a POST when trying to open the custom study link. Is that intentional? 

I know what it does and have taken a look at it because of my job at the reviewer and can see why it is used there, but I think that it would be simpler for the congrats screen to have just one way of sending requests instead of two

**Comment by dae** [comment]
bridgeCommand (originally called 'pycmd') predates the time when Anki had a HTTP server, so the main answer is "legacy reasons". I'd like to [avoid it](https://github.com/ankitects/anki/pull/2568#discussion_r1266647471) in new code, but changing the existing instances of it will mean all the clients need updating. Also note the hasBridgeCommands argument, which can be used to disable the links if you don't want to implement that part yet.

**Comment by BrayanDSO** [comment]
That's what I thought. I'll probably send a patch to change that in the desktop version for the congrats screen. For the reviewer, my plan is to keep using bridgeCommand for the time being
