### ISSUE TITLE
BuildToolVension and compileSdkVersion seems to have disappeared. Remove reference

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14433]
On https://github.com/ankidroid/Anki-Android/wiki/Development-Guide you suggest to ensure th version match buildToolsVersion and compileSdkVersion in the [build.gradle file](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/build.gradle). Those files does not contains variable named this way. 

There is the line `compileSdk 33 // change api compileSdkVersion at the same time` that also refers to the variable, but that does not help.

So I assume there is an issue. Variables that used to exist and disappear, and both should be updated

**Comment by Arthur-Milchior** [comment]
@criticalAY If I trust Discord discussion you were the one who wrote it

**Comment by david-allison** [comment]
Related: #14258

**Comment by criticalAY** [comment]
I am confirming something will update it, it slipped out of my mind while updating the doc I was there in this PR covo

**Comment by criticalAY** [comment]
@Arthur-Milchior can we close this now ?

**Comment by BrayanDSO** [comment]
> @Arthur-Milchior can we close this now ?

the comment `// change api compileSdkVersion at the same time` is still at build.gradle. Since we have a bunch of outdated comments, and in order to improve the signal:noise ratio in the issues, I'm going to close this one. 

This is the kind of thing that is way more productive creating a PR directly than creating an issue
