### ISSUE TITLE
[BUG]: Empty undo snackbar shows up even if nothing was undone

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14471]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Assign `Undo` to a gesture
2. Open the reviewer
3. Don't have anything to undo
4. Use the assigned undo gesture repeatedly

### Expected behaviour

Snackbars aren't shown if there isn't anything to undo

### Actual behaviour

An empty snackbar is shown even without anything to undo

https://github.com/ankidroid/Anki-Android/assets/69634269/d90bb488-62e1-4a47-a941-717978421d06

(note: ignore the absent deck name. I've removed it in my personal build)

### Debug info

```text
2.17alpha1
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
@dae, what is the purpose of `OpChangesAfterUndo.getDefaultInstance()` below? 

https://github.com/ankidroid/Anki-Android/blob/9c3ad34803b2eb319907878f897cb0e5cb397f3b/AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt#L27-L39

And would there be a problem with dropping it and refactor the method to the code below?

```kotlin
 suspend fun FragmentActivity.undoAndShowSnackbar(duration: Int = Snackbar.LENGTH_SHORT) { 
     withProgress { 
         if (undoAvailable()) { 
             val changes = undoableOp { undo() }
             showSnackbar(TR.undoActionUndone(changes.operation), duration)
         }  
     } 
 } 
```

**Comment by dae** [comment]
undoableOp{} invokes withCol. The code above would need a separate withCol for undoAvailable(), and then you'd have a race condition: it might be available in the first call, but not when the undo action actually happens, as you release the collection lock, and another operation may be interleaved. getDefaultInstance() returns an all-blank change list, which would not trigger screens to refresh. An alternative approach would be to use a single outer withCol, and inline undoableOp's code instead of using undoableOp.

No strong feelings here, but isn't it better to show something to the user when they tap on the undo button? Otherwise nothing would happen, which might cause users to think it's broken.

**Comment by BrayanDSO** [comment]
> but isn't it better to show something to the user when they tap on the undo button?

Maybe replace the current `  undone` with something like `Nothing to undo`?

**Comment by dae** [comment]
Sure, that's available via tr.actionsNothingToUndo()

**Comment by dae** [comment]
You could check if changes.operation is empty, and display that instead.
