### ISSUE TITLE
[Bug] Regression: can't jump to latter sections in videos inside `<video>` tags 

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14490]
###### Reproduction Steps

1. Add a video inside embedded in a HTML `<video>` tag to a note
2. Open that note

###### Expected Result

The video loads quickly and you can immediately jump to later sections

###### Actual Result

The video is loaded sequentially and you can only jump to sections you've already watched

## Working right in 2.16

[Screen_recording_20230929_160101.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/d570c820-7643-4070-90db-e0bdff262947)

## Bug in 2.17

[Screen_recording_20230929_155443.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/687097f8-8bb8-41ea-ad78-124d55036ccc)

###### Debug info
2.17alpha1 at HEAD 100f219b09df13cbbfde7026a6454adeddbba53d. 
API 33  Emulator

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Probably because the file is served by `ReviewerServer` instead of the previous approach that I guess used something more natural in Android

**Comment by dae** [comment]
https://stackoverflow.com/questions/62551272/nanohttpd-serve-video-how-to-make-it-support-video-forward-and-backwardmake-se

**Comment by dae** [comment]
(instead of streaming the whole file, it would need to limit to the range specified in the range header)

**Comment by BrayanDSO** [comment]
Do you know of any advantage of serving media with the server instead of using the previous way?

**Comment by dae** [comment]
We need a way to be able to make POST requests so that custom scheduling works, and the old approach didn't support that. The .html file and post location need to be served from the same location, or you run into issues with CORS when making POSTs. You may possibly be able to add the old approach back in for just media files (by adjusting the `<base>` tag in `<head>`), but I'm not sure if that would be without problems, and it's probably simpler just to implement support for the range header.

Untested, but this is what ChatGPT had to say:

To serve a specific byte range from a file, you will need to first parse the Range header to get the starting and ending bytes, then use RandomAccessFile or a similar mechanism to obtain the necessary byte range from the file. Here’s how you might adjust your serve() method to handle a Range header:

```kotlin
override fun serve(session: IHTTPSession): Response {
    val rangeHeader = session.headers["range"]
    val file = ... // Obtain the file to serve
    val mimeType = AssetHelper.guessMimeType(session.uri)
    if (rangeHeader != null) {
        // Assume the range header is in the format "bytes=start-end"
        val parts = rangeHeader.split("=")[1].split("-")
        val start = parts[0].toLong()
        val end = if (parts[1].isNotEmpty()) parts[1].toLong() else file.length() - 1
        val contentLength = end - start + 1
        val raf = RandomAccessFile(file, "r")
        raf.seek(start)
        val response = newFixedLengthResponse(
            Response.Status.PARTIAL_CONTENT, mimeType, raf, contentLength)
        response.addHeader("Content-Range", "bytes $start-$end/${file.length()}")
        response.addHeader("Accept-Ranges", "bytes")
        return response
    } else {
        val inputStream = FileInputStream(file)
        return newChunkedResponse(Response.Status.OK, mimeType, inputStream)
    }
}
```

Here’s what this code does:

It first checks if a Range header is present in the request.
If a Range header is present, it parses the Range header to obtain the start and end bytes.
It then creates a RandomAccessFile to serve the specified byte range from the file, seeking to the starting byte and specifying the length of the content to serve.
It sets the Content-Range and Accept-Ranges headers in the response to indicate the byte range being served.
If no Range header is present, it falls back to serving the entire file as before.
In this code snippet, the RandomAccessFile is used to serve the specified byte range from the file, and the newFixedLengthResponse() method is used to create a fixed-length response with the specified content length.

This code makes a simplifying assumption that the Range header will be well-formed and in the expected format. In a production setting, you would want to add additional error checking and handling to ensure robustness.

**Comment by BrayanDSO** [comment]
I get the need for dealing with POST requests in the reviewer. 

My curiosity is about if there is a difference in terms of media loading speed and memory footprint between the server and Android's default loader (WebViewAssetLoader, I guess).

Also, the server could be removed from the previewer that way, which may matter much or be worth it by itself, but it is a thing to be aware of. 

In terms of simplicity, IMO, both approaches aren't complex enough to be preferred over the other

If someday I consider that the investigation is worth it and get the time for it, I'll finally try learning how to do profiling in Android to averiguate that

**Comment by dae** [comment]
Given that WebViewAssetLoader is also Java, I'd be surprised if there's a big difference in performance.

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:webkit/webkit/src/main/java/androidx/webkit/WebViewAssetLoader.java?q=file:androidx%2Fwebkit%2FWebViewAssetLoader.java%20class:androidx.webkit.WebViewAssetLoader
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/WebResourceResponse.java
