### ISSUE TITLE
Answer buttons on side in horizontal orientation.

### ISSUE THREAD

**Issue by dotancohen** [ankidroid/Anki-Android#14505]
**Is your feature request related to a problem? Please describe.**
When using Ankidroid in the horizontal orientation, accessing the Answer buttons requires scrolling and they are difficult to get to with one hand.

**Describe the solution you'd like**
There should be an option to display the answer buttons on the left side, or right side, or *both sides* when the device is in a horizontal orientation. This will make better use of the screen space.

Essentially, the answer buttons will remain where they currently are when the device is in vertical orientation. So only the Front and Back locations are rotated. And yes, there should be an option to have the buttons on both sides as it is common to switch hands when holding the device, like when reading a book.

**Describe alternatives you've considered**
Turning my head sideways when the device is in a horizontal orientation. Not a bad solution, but people look at me funny and my neck hurts ))

**Comment by BrayanDSO** [comment]
Hi there. We are migrating feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra work
