### ISSUE TITLE
[BUG]: All cards appear blank

### ISSUE THREAD

**Issue by star-dawn** [ankidroid/Anki-Android#14517]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When running Ankidroid, all of a sudden, all my cards stopped displaying any content. The front and back both show empty, regardless of text or image content.

I tried:
-checking database
-checking media
-restoring from backup
-reinstalling Ankidroid
-reimporting decks
-creating a new deck
No errors were reported, but all cards still show blank. 

### Expected behaviour

The card displays

### Actual behaviour

Blank display

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 10

ProductFlavor = play

Manufacturer = samsung

Model = SM-G960U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-G960U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 6073f235-3f01-4bbd-b4b5-e2fe4468075e

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Here is a sample card and how it looks
![Screenshot_20231005-212429_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/147124820/86f97c27-f095-4b2c-9d21-9cf01670d118)
![Screenshot_20231005-212440_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/147124820/6c1a34b9-877a-4d10-a52d-eba1cf84cf37)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment]
Nice tries.
You may also want to try restarting the device if you have not yet.

**Comment by AdrianSva** [comment]
> Nice tries. You may also want to try restarting the device if you have not yet.

I had the same issue, restarting the device appears to have fixed it.

**Comment by david-allison** [comment]
Hi @star-dawn,

* What does Anki Desktop/AnkiWeb show?
* Have you tried the 2.17 alpha
* Could you post a sample card export

Thanks

**Comment by mikehardy** [comment]
Going to close this as "not currently reproducible" but we can easily re-open it if it reproduces on the latest alphas https://github.com/ankidroid/Anki-Android/releases just let us know

**Comment by Vozf** [comment]
@mikehardy I've had the same problem with 2.17beta2.
First I had last version from gplay(I guess it's 2.16.5). It first appeared when I tried to install additional collection from web. It was too large to be installed fast so I switched to another application. Later ankidroid was killed by system and when I opened it again my original collectction started to be all blank. Exactly like in screenshot every card is just emtpy. However ankiweb worked without any issues, so that's definitely a problem with ankidroid. Then I removed and reinstalled from gplay and got my backup from cloud - no result, still blank. Then I updated to 2.17beta2 - no result. Then I rebooted the phone and it worked.
So for anyone with this problem - reboot phone
