### ISSUE TITLE
Spaced notifications

### ISSUE THREAD

**Issue by jaxxor44** [ankidroid/Anki-Android#14654]
**Is your feature request related to a problem? Please describe.**
like everyone, im busy, but my phone is always in my pocket. I dont have the forethought to pull out my phone and do an anki session.

**Describe the solution you'd like**
Ideally, the App would let you set a daily time period, (like between 0800 and 2000).
During that time period, divide the due cards evenly across that time.
Prompt a card, as a notification to the Android UI notification area.
The user can see the card, hit one of the 4 default values and go back to what they where doing.

**Describe alternatives you've considered**
setting a schedule for the app to auto open, just means ill close it when i need to do something else on my phone.

**Additional context**
Id love to help, but lack the 'high level' architecture understanding to fork and develop this solution.

**Comment by TCOTC** [comment]
> I dont have the forethought to pull out my phone and do an anki session.

Me too. 

> Prompt a card, as a notification to the Android UI notification area. The user can see the card, hit one of the 4 default values and go back to what they where doing.

It's a good way to remind us.

**Comment by mikehardy** [comment]
> Prompt a card, as a notification to the Android UI notification area.

This is a non-starter, it is not technically possible no matter how much you wish it was.

Why?

Every Anki card is potentially a full-fledged miniature website with HTML + CSS + Javascript (perhaps executing as an add on accessing the javascript API etc...)

Notifications **are not allowed to be full-fledged HTML things**

Period. It's not allowed

Not technically possible to display an Anki card as a notification.

Not intending to sound upset or anything I just really really want to emphasize (since this comes up frequently) that this is not technically possible, no matter how much people want it.

**Comment by TCOTC** [comment]
The alternative, just need to get the notifications to show up at the right time so I can click on the notification to open the corresponding card for review.

**Comment by TCOTC** [comment]
This may not apply to situations where you need to review a very large number of cards each day, but since the number of cards I need to review is small, I need such a feature.
