### ISSUE TITLE
AnkiDroid can't set "Desired memory retention rate" to 0.99

### ISSUE THREAD

**Issue by lalala-233** [ankidroid/Anki-Android#14731]
My AnkiDroid version is 2.17alpha5, and Anki Desktop version is 23.10.1 (fac9e0ee)⁩ Python 3.11.5 Qt 6.6.0 PyQt 6.6.0.

I'm using AnkiDroid and Anki Desktop, but AnkiDroid can't set "Desired memory retention rate" to 0.99, so I have to re-enable FSRS on my computer frequently.

I'm not a native English speaker, so I use a translator.

**Comment by Ceynou** [comment]
This is the same on Anki Desktop, just reopen the settings again and you'll see it's 0.97 because you can only set a retention between 0.70 and 0.97, anything else is very very stupid anyway

**Comment by david-allison** [comment]
Could you test again? 

This should have been fixed in alpha5: 
* https://github.com/ankidroid/Anki-Android/pull/14710

I've just tested and it worked (0.99). 

<img width="328" alt="Screenshot 2023-11-15 at 13 50 07" src="https://github.com/ankidroid/Anki-Android/assets/62114487/f75b82d3-1adb-446b-b40f-d5f0104bc51c">

> The permissible range for desired retention is 0.70 to 0.97 (0.7 to 0.99 in Anki 23.10.1 or newer)

https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md#desired-retention

**Comment by lalala-233** [comment]
Sorry, I mistakenly thought I used the latest version of alpha5, in fact, I used alpha4.
Now I've switched to the latest version, alpha5, and it works well.
Thanks
