### ISSUE TITLE
#14837 Add SplashScreen

### ISSUE THREAD

**Issue by S-H-Y-A** [ankidroid/Anki-Android#14838]
**Is your feature request related to a problem? Please describe.**
Add Splash Screen  to make user experiences richer.

**Describe the solution you'd like**
Implement AndroidX.SplashScreen and set animatedVectorDrawable.

**Describe alternatives you've considered**
None

**Additional context**
Actually, I've already created it(#14837).

**Comment by david-allison** [comment]
@Aracksontv ?

**Comment by mikehardy** [comment]
> add splash screen to make user experiences richer

The problem is that this is qualitative. And some users hate hate hate splash screens. The canonical reason to hate a splash screen is that you opened the app because you want to use it right now. What is this dancing baloney on the screen preventing you from using the app right now?

The historical need for a splash or loading screen was to give the appearance of activity while the app was preparing itself to be available for work. But if the app is ready for work then there is no technical need to delay doing useful work.

I would at minimum expect a lot of requests for a toggle to turn this off.
And I would also expect that if it were on, it was really really brief and went away as soon as the app was ready for work (i.e., the collection was loaded - that should trigger immediate dismissal)

I have to admit I'm not sold on the idea at all - I didn't realize that was an open issue to be honest, and there hasn't been much discussion

**Comment by BrayanDSO** [comment]
Splash screens are only useful if the app takes too much time to start up. Even on slow phones, AnkiDroid shouldn't take more than 2 seconds to appear. Animating something to fit that small time frame is jankier than a static screen. Delaying the app startup to show an animation is unnacceptable.

Particularly, I would like to focus on making the app startup faster instead of that.

**Comment by david-allison** [comment]
Current stats:

2.13% of users have a 'Slow cold start' (startup time over 5s)

90th percentile is ~3s

<img width="1154" height="610" alt="Image" src="https://github.com/user-attachments/assets/cb1e2fef-b76c-494f-9f08-56028d71b6c3" />

<img width="1153" height="301" alt="Image" src="https://github.com/user-attachments/assets/98747ded-8d5d-48dc-ab22-f42b9fff5257" />

----

Some operations can be slow and blocking (crash reporting, analytics, loading the backend library, then loading the collection and initalizing the WebView to determine if it's usable). 

Our splash screen should NOT add forced latency to the startup (other than the milliseconds to display the screen)

In order to make that work visually, I feel a subtle 'scale up' animation of the logo, from maybe 90% size to 100% size would be sufficient.
