### ISSUE TITLE
[CI] Flaky Instrumented test: testCustomSchedulerWithCustomData

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14940]
```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED 
	androidx.test.espresso.PerformException: Error performing 'performing ViewAction: single click on item matching: holder with view: (view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Default")' on view 'view.getId() is <2131296705/com.ichi2.anki.debug:id/files>'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
```

Can't see artifacts: https://github.com/ankidroid/Anki-Android/actions/runs/7162465093/attempts/1

Relevant code:

https://github.com/ankidroid/Anki-Android/blob/b155b2d359f0575b4e868a6b1e6098be375529f9/AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt#L104-L111

**Comment by david-allison** [comment]
Maybe a different flake, same method

[30-x86_64-google_apis-600-0-adb_video (1).zip](https://github.com/ankidroid/Anki-Android/files/13639846/30-x86_64-google_apis-600-0-adb_video.1.zip)
[30-x86_64-google_apis-600-0-adb_logs (1).zip](https://github.com/ankidroid/Anki-Android/files/13639869/30-x86_64-google_apis-600-0-adb_logs.1.zip)

**Comment by kuroahna** [comment]
> ```
> com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED 
> 	androidx.test.espresso.PerformException: Error performing 'performing ViewAction: single click on item matching: holder with view: (view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Default")' on view 'view.getId() is <2131296705/com.ichi2.anki.debug:id/files>'.
> 	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
> ```
> 
> Can't see artifacts: https://github.com/ankidroid/Anki-Android/actions/runs/7162465093/attempts/1
> 
> Relevant code:
> 
> https://github.com/ankidroid/Anki-Android/blob/b155b2d359f0575b4e868a6b1e6098be375529f9/AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt#L104-L111

For the error
```
12-11 16:06:07.123  3811  3949 E TestRunner: androidx.test.espresso.PerformException: Error performing 'performing ViewAction: single click on item matching: holder with view: (view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Default")' on view 'view.getId() is <2131296705/com.ichi2.anki.debug:id/files>'.
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.base.PerformExceptionHandler.handleSafely(PerformExceptionHandler.java:8)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.base.PerformExceptionHandler.handleSafely(PerformExceptionHandler.java:9)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at com.ichi2.anki.ReviewerTest.clickOnDeckWithName(ReviewerTest.kt:105)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at com.ichi2.anki.ReviewerTest.reviewDeckWithName(ReviewerTest.kt:120)
12-11 16:06:07.123  3811  3949 E TestRunner: 	at com.ichi2.anki.ReviewerTest.testCustomSchedulerWithCustomData(ReviewerTest.kt:79)
```

in the build https://github.com/ankidroid/Anki-Android/actions/runs/7162465093

I see in the video that first opens up the app at 4:13

![image](https://github.com/ankidroid/Anki-Android/assets/85209455/1817a73b-fc5e-4741-a4b7-bf3c4cc690c9)

it clicks the `Later` button for the `Backup your collection` dialog

Takes awhile to load. At 4:18, we see the page has fully loaded (shows `studied 0 cards in 0 seconds today (0s/card`), except for the actual deck

![image](https://github.com/ankidroid/Anki-Android/assets/85209455/a3d499bb-ced7-4fa5-8eba-f9dc9a831b84)

Then at 4:20, it finally loads the deck

![image](https://github.com/ankidroid/Anki-Android/assets/85209455/a3194f69-2f04-4f08-a11d-bf9cbd3bc6a8)

So I believe the problem here is that we just try to click on the Deck too fast without waiting/checking to make sure it exists.

This should be simple enough to fix and I can make a PR to fix that

**Comment by kuroahna** [comment]
> Maybe a different flake, same method
> 
> [30-x86_64-google_apis-600-0-adb_video (1).zip](https://github.com/ankidroid/Anki-Android/files/13639846/30-x86_64-google_apis-600-0-adb_video.1.zip) [30-x86_64-google_apis-600-0-adb_logs (1).zip](https://github.com/ankidroid/Anki-Android/files/13639869/30-x86_64-google_apis-600-0-adb_logs.1.zip)

So this is a weird one. At 2:40

![image](https://github.com/ankidroid/Anki-Android/assets/85209455/c548e058-3345-4bcd-a4ad-787a761c9b8b)

it attempts to click on the deck, then at 2:45 the app just crashes without going into the `Reviewer` screen

Grepping the logs for the what happened to the lifecycle:

```
12-11 18:50:49.417  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: PRE_ON_CREATE
12-11 18:50:49.572  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: CREATED
12-11 18:50:49.722  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: STARTED
12-11 18:50:49.748  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: RESUMED
12-11 18:50:54.951  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: PAUSED
12-11 18:50:55.056  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.DeckPicker@987cfd2 in: PRE_ON_CREATE
12-11 18:50:57.277  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.DeckPicker@987cfd2 in: CREATED
12-11 18:50:57.285  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.DeckPicker@987cfd2 in: STARTED
12-11 18:50:57.344  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.DeckPicker@987cfd2 in: RESUMED
12-11 18:51:02.304  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: STOPPED
12-11 18:51:02.312  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.IntroductionActivity@8314824 in: DESTROYED
12-11 18:51:03.743  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.DeckPicker@987cfd2 in: PAUSED
12-11 18:51:04.574  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.Reviewer@7895c7a in: PRE_ON_CREATE
```

The `Reviewer` is stuck at `PRE_ON_CREATE` and never transitions to `CREATED` -> `STARTED` -> `RESUMED` -> `PAUSED` -> `STOPPED` -> `DESTROYED` like the other activities

I couldn't find anything relevant in the logs except for

```
12-11 18:51:01.802  3832  3832 W chi2.anki.debu: JNI critical lock held for 33.004ms on Thread[1,tid=3832,Runnable,Thread*=0x741a9345dbe0,peer=0x71cf55b8,"main"]
...
12-11 18:51:04.574  3832  3832 D LifecycleMonitor: Lifecycle status change: com.ichi2.anki.Reviewer@7895c7a in: PRE_ON_CREATE
...
12-11 18:51:04.743  3832  3832 I AnkiDroidApp$onCreate: Reviewer::onCreate
...
12-11 18:51:05.132  3832  3832 W chi2.anki.debu: JNI critical lock held for 18.976ms on Thread[1,tid=3832,Runnable,Thread*=0x741a9345dbe0,peer=0x71cf55b8,"main"]
...
12-11 18:51:09.665   524   628 I ActivityManager: Force stopping com.ichi2.anki.debug appid=10168 user=0: finished inst
12-11 18:51:09.667   524   628 I ActivityManager: Killing 3832:com.ichi2.anki.debug/u0a168 (adj 0): stop com.ichi2.anki.debug due to finished inst
...
12-11 18:51:09.688   524   628 W ActivityTaskManager: Force removing ActivityRecord{6e123c1 u0 com.ichi2.anki.debug/com.ichi2.anki.Reviewer t11 f}}: app died, no saved state
...
12-11 18:51:11.087   271   271 I Zygote  : Process 3832 exited due to signal 9 (Killed)
```

I've found these stackoverflow posts:
1. https://stackoverflow.com/questions/35181785/android-sometimes-force-kills-application
2. https://stackoverflow.com/questions/55117940/crash-during-game-loading-understanding-of-jni-critical-lock-held-for

It seems like Android kills our application since it might be low on memory/cpu and it needs to free up resources. That JNI critical lock held log message seems concerning though. Not sure if we have a leak somewhere?

**Comment by kuroahna** [comment]
I'm wondering if we're getting that JNI critical lock because we're not properly closing the rust backend and db connection at the end of each test. Locking the thread for +30 seconds kinda sounds like there's a dead lock. 

In https://github.com/ankidroid/Anki-Android/blob/50fa39cd561d83662cd5ef1f708b14a9a15c74ac/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt we have some setup and cleanup code that opens/closes the backend and uses an in memory database instead. The in memory database would be nice to use to ensure that we have an empty collection at the start of each test as well because I've actually noticed when testing, it reuses the same database and doesn't start with an empty one if I run multiple tests at the same time which can also be another source of flakiness since we don't want data from other tests to leak.

What are your thoughts? I can open another PR to add this. Hopefully this will make our test suite more robust and less prone to these intermittent failures

**Comment by david-allison** [comment]
Cleanup code: definitely

In-memory DB: hold off for now, we want `androidTest` to be as close to real operation as possible, and some operations which open + close the DB will no longer be possible

**Comment by mikehardy** [comment]
> Is it possible to set these and increase them from whatever they currently are? Not sure how much RAM and CPU cores we actually get from the github runners? Or does it automatically use all available RAM if it's not set?

I believe the defaults for those are acceptable for now. The runners are reasonably tight on resources and taking more for the emulator would require real performance testing before I'd accept it was better than the auto-tuned settings the emulator puts into effect as it starts up the emulator VM. In the past this hasn't been the bottleneck in my testing at least
