### ISSUE TITLE
Add a way for the Javascript API to control where toasts (undo, leech, etc messages) appear

### ISSUE THREAD

**Issue by vgf89** [ankidroid/Anki-Android#15071]
**Is your feature request related to a problem? Please describe.**

When I was implementing my two-button-answer card template, which replaces the native four answer buttons, I discovered that the toasts for undo, leech, etc appear over my template-rendered buttons and prevent me from interacting with my buttons until I click the toast or wait for it to disappear on its own. Usually this isn't a bother with leeches because reading/comprehending the front of my card takes time, but if I click "undo" I want to be able to correct my answer as soon as possible, and the toasts appearing directly over my buttons makes me click an extra time. It's a subtle but mildly annoying interaction when trying to replace the native buttons with buttons in a card template.

**Describe the solution you'd like**

I'd like an API call I can call from my card template that tells ankidroid where toasts can be rendered to not obscure my buttons. Whether this is done with some sort of keepout zone, an offset from the bottom of the webview, or just setting an origin point for the toast, any of those ways would work for me.

**Describe alternatives you've considered**

I can't think of any alternatives, short of interrogating the webview renderer for positions of buttons to influence the toast position, which sounds worse than just letting a template set the position itself via an API. This is a very subtle interaction that, before now, I'm guessing no one thought of when implementing answer button calls in the Javascript API.

**Additional context**

I guess #15070, but only because I noticed both issues when trying to implement custom answer buttons in card templates to replace native answer buttons.

**Comment by BrayanDSO** [comment]
The only pratical way to do that that I can imagine is moving the feedbacks (i.e. the snackbars) to javascript. Hacks could be used, but I believe that moving to javascript is actually the easiest approach and is the most maintanable.

The users affected (a very very few) / work to do (moderate to big) ratio is low here I believe, so I'm marking this with https://github.com/ankidroid/Anki-Android/labels/Priority-Low, but is something that I accept.

**Comment by mikehardy** [comment]
@BrayanDSO interesting thought - it sounds like a possible implementation might be something like:

- if the javascript API is enabled (something that AnkiDroid will be "aware" of as a state at native and javascript layer)...
- then native snackbars should be disabled and
- there should be someway for snackbars to display in javascript ?

I'm not sure that's easier then wrapping snackbars in some AnkiDroid-specific class and instead doing:

- if javascript API is enabled,
- then for a snackbar instead of showing an actual snackbar make an element below the webview go from GONE to VISIBLE with the snackbar contents ?

I admit my suggestion there is probably a little brutal as a design but I'm not sure what the reviewer would do with regards to showing the snackbar info in combination with the user's ability to show any element at all anywhere in the WebView - without ability to predict with that user will draw how can we solve the problem really as we still might make a javascript-snackbar system that collides with user-drawn UI elements?

**Comment by BrayanDSO** [comment]
my idea was actually to stop using native snackbars in the reviewer and show all feedback messages with HTML/CSS/Js, so people can customize it. If the user don't use the Js API, the feedback would be still in Js
