### ISSUE TITLE
Add back the estimated review time left feature

### ISSUE THREAD

**Issue by dylanopen** [ankidroid/Anki-Android#15244]
In previous released of ankidroid, I've always been able to see an 'ETA' for when I finish the daily cards in that deck.
However it seems now that this feature has been removed.

Would it please be possible to add back the feature that lets us see an estimate of how long our remaining cards will take? OR at least a setting in the settings menu to toggle this on and off, like before.

This existed in <2.16.5 but seems to be missing in the most recent versions.

![Screenshot_20240117_074255_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/125146997/4767905d-81fe-44ca-936c-089d2d945f03)

(The time remaining is not there)

I will make a PR when I have time, but I added this as a feature request for now in case anyone would be kind enough to solve it :)

Thanks,
Dylan

**Comment by BrayanDSO** [comment]
Anki Desktop has removed the feature years ago because of how inaccurate it tended to be.
So, for the same reason and to keep things consist between clients, we removed the feature.

About restoring the setting, having too many settings is a common complaint of the users. Also, given our limited human resources in development and support, the best is to focus in more relevant matters.

Given Hyrum's law, there will always be someone that relied on an existing feature, like you, but we need to some kind of direction.

**Comment by dylanopen** [comment]
> Anki Desktop has removed the feature years ago because of how inaccurate it tended to be. So, for the same reason and to keep things consist between clients, we removed the feature.
> 
> About restoring the setting, having too many settings is a common complaint of the users. Also, given our limited human resources in development and support, the best is to focus in more relevant matters.
> 
> Given Hyrum's law, there will always be someone that relied on an existing feature, like you, but we need to some kind of direction.

Thanks for the info. I don't really need the feature, I just thought it was a useful way of having a *general idea* of the time left, but I understand it's inaccurate and so I respect the reasoning behind it!
