### ISSUE TITLE
Unreadable text in dark mode in transparent png

### ISSUE THREAD

**Issue by Frostedfox** [ankidroid/Anki-Android#15262]
**Is your feature request related to a problem? Please describe.**
Adding transparent png diagrams with parts labelled becomes unreadable in dark mode
eg:
![Screenshot_20240119_181554_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/84601232/981f0ba0-579a-4696-a7af-ea91cc12d2ba)
![Screenshot_20240119_181540_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/84601232/7dbace61-1f69-42b8-9f0a-074f36622426)
actual image:
![microsoft-r-logo-png-12](https://github.com/ankidroid/Anki-Android/assets/84601232/45ba768d-6179-4511-bfe1-56ace9d6d8c9)

**Describe the solution you'd like**
Is it possible to keep the white background in the png

**Describe alternatives you've considered**
Alternatives are to add a background via some other app and then import the image

**Comment by david-allison** [comment]
Closing this as answered. I don't think we'll make functional changes here.

Feel free to continue commenting & ask for this to be reopened if I'm mistaken

**Comment by BrayanDSO** [comment]
My two cents is that adding a white background would make white images not appear, so it would create another problem to solve this one.

The most common approach that image editors use the solve this is putting a chess-like grid with two different tones

e.g.

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/82598f93-badd-41f4-9dd9-ce636ca6949a)

Since we get the editor directly from Anki Desktop code, you should suggest the fix there
