### ISSUE TITLE
[Bug] Title for Vertical Menu(More options)

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15279]
###### Reproduction Steps

1. Go to statistics
2. Go to export
3. Long press on the vertical grill present in top right corner.

###### Expected Result
It should show title/Name as in other places.

###### Actual Result
It does not do anything for now.
![photo_6152100074231019519_y](https://github.com/ankidroid/Anki-Android/assets/85388413/16b52c70-5675-4aaa-84a5-91bfc1c490ec)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Sagar0-0** [comment]
Let me work on this, if this seems a valid issue.

**Comment by david-allison** [comment]
Context: "Save PDF" was fixed in bdff91ce43c3280a7a88412f76cf5edca4d6e358
* https://github.com/ankidroid/Anki-Android/pull/15193
* https://github.com/ankidroid/Anki-Android/issues/15192

This appears to be for the dialog which occurs after "Save PDF" is clicked

I feel this is a system dialog which we don't control

https://github.com/ankidroid/Anki-Android/blob/03e26164882b156995763519ee01f76735ef2696/AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt#L52-L65

Here is how it looks on my screen

![Uploading Screenshot 2024-01-20 at 18.42.11.png…]()

**Comment by Sagar0-0** [comment]
Got it, we can close this issue as Invalid, I will take care of it from now.
