### ISSUE TITLE
Option to migrate collection to any folder

### ISSUE THREAD

**Issue by virginviolet** [ankidroid/Anki-Android#15307]
**Problem**
I want to move my collection to `/storage/emulated/0/AnkiDroid` where I have read/write access. The settings in AnkiDroid allow me to change the directory, but it doesn't move my current collection. Since I do not have root access, I cannot move my collection manually.

**Solution**
I wish you could choose from the settings menu to migrate your collection to the new folder, or something like that.

**Alternative solution**
I could purge data, change directory, and download from AnkiWeb, but I don't wanna. I have a huge collection.

**Comment by david-allison** [comment]
Our `apk` on F-Droid doesn't require migration and allows you to retain the `/AnkiDroid` folder.

In my testing, Android's file browser often crashed when trying to move the `AnkiDroid` folder, ensure you have a backup if you're moving things manually and have a large collection

**Comment by virginviolet** [comment]
> Our `apk` on F-Droid doesn't require migration and allows you to retain the `/AnkiDroid` folder (and select an arbitrary folder to store data). The restriction on using the app-private folder is due to Google Play.

I am not using the Play Store version.

You can change the folder to `/storage/emulated/0/AnkiDroid`, but that does not move my existing collection, just updates the folder where it reads from and writes to (resulting in an empty collection, in my case).

**Comment by david-allison** [comment]
I think we all want to get rid of the migration functionality as soon as possible

Migration was required for almost all users, especially for users with neither free space nor a translator for in-depth instructions

In addition, Android's user-facing file copy operations are... insufficient, and we needed to copy across mount points

----

Since there's a workaround above, this will be some amount of work and we want to remove the functionality, I doubt we'll ever have the resources to get around to it

**Comment by virginviolet** [comment]
>  delete [collection] in Ankidroid

I don't see an option to do this. If I delete each deck, and check media, will everything be cleanly removed?
