### ISSUE TITLE
Preference to disable the new "Congratulations! You have finished the deck for now" screen

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#15349]
**Is your feature request related to a problem? Please describe.**
Usually, after a few weeks, interface changes that are annoying at first becomes invisible.
However, the new Congratulations screen keeps bugging me, because there is no gesture to wave it away. If you have gestures turned on and are swiping left or right, it breaks your rhythm to have to look for a tiny arrow at the edge of the screen each time you finish a deck.

**Describe the solution you'd like**
Allow ANY gesture to get rid of the Congratulations screen.

**Describe alternatives you've considered**
I tried getting used to it.

**Additional context**
I do ten decks daily and therefore run into this problem often.

**Comment by neeldoshii** [comment]
I agree with you. 

![image](https://github.com/ankidroid/Anki-Android/assets/60827173/1647cce1-8249-4e08-a480-732bd5a49c36)
Since most of the people on newer device don't use this its quite a hectic workaround to go back.

**Comment by boolbag** [comment]
Fantastic. Thank you. Glad to see I'm not the only one.

**Comment by BrayanDSO** [comment]
If you have a device with Android 10+, have you tried using swipe navigation gestures in your device? That should solve your problem

Otherwise, having any gesture closing this screen would be confusing and lead do unexpected closes. Also, tapping the back button of your device or in the top-left of the screen isn't that hard, and it's the intuitive behavior of anyone.

**Comment by boolbag** [comment]
> have you tried using swipe navigation gestures in your device?

Turning on a phone-wide feature to solve an application-specific issue creates more problems than it solves.
 
> the intuitive behavior of anyone.

Clearly not "anyone."
The new "Congratulations" screen is a downgrade for some of us who have been used to working a certain way with Ankidroid for years. Do what you like of course, but this is genuine user feedback.

**Comment by david-allison** [comment]
When a user sees a screen, the actions which we want them to take should be obvious.

This is not obvious currently and we should do something about this, whether it be gestures, or a button on the bottom of the screen moving the user back to the Deck Picker

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/ac1f0d76-2131-44c6-8d0c-37138bd264d4)

----

This screen is a confusing screen for a new user, and we have a lot of work here to make it 'good'. This is a small step in the right direction

**Comment by neeldoshii** [comment]
@SanjaySargam if you have any idea to how you can solve it. Feel free to work on the issue. I am in mid of refactoring all Material Dialog for 2.17

**Comment by david-allison** [comment]
This needs a discussion on how we implement it before it's open to work. Proposals welcome!

**Comment by boolbag** [comment]
> Proposals welcome!

Okay, I'll bite. :)

- definitely a screen that can be dismissed by swiping right
- not in love with the word "congratulations." Some decks might only have two or three cards in the review stack, and when I see "congratulations" after reviewing two cards, it almost feels like the program is patronizing me. ;)
- if you feel there really is a need for a screen between the last car and the Decks screen, I'd suggest something **informative**. For instance:

```
You've finished reviewing this deck for today!

1. you've reviewed x cards in y minutes
2. there are x new cards remaining in the deck.
3. due tomorrow: x cards
```

The "due tomorrow" is particularly helpful and informative as it helps manage one's time. The "tomorrow count" should include buried cards, as they will show up the next day. 
As an Anki filter, this would look like:
```"deck:some_deck" (prop:due=1 OR is:buried)```

**Comment by MarkusJLechner** [comment]
Just wanted to open an issue about this. Here the content I wrote together:

My proposal would be to add a option to disable the congratulations page for experienced users 

#### Summary
Introduce a user preference to bypass the congratulations page  for users familiar with Anki. This page, while beneficial for newcomers by providing a sense of completion and progress, becomes redundant for experienced users. The main points of contention are the interruption it causes in the review flow and its negligible informational value for those accustomed to the app's review dynamics.

#### Proposal
- Implement a "Skip this page for future reviews" button on the congratulations page.
- Add a setting under Review Settings titled "Show congratulations page," allowing users to re-enable this feature if desired.

#### Rationale
Experienced Anki users, particularly those managing reviews across multiple decks, often view the transition back to the deck overview and the visual cue of remaining reviews as sufficient indicators of session completion. The congratulations page, in these instances, serves more as an unnecessary interruption rather than a helpful summary. Providing an option to skip this page enhances the review process's efficiency and user satisfaction, catering to both new and seasoned users' preferences.

#### Implementation Considerations
- Ensure the "Skip this page for future reviews" option is easily accessible and understandable.
- The "Show congratulations page" setting in Review Settings should be clear in its purpose, allowing users to toggle the congratulations page's visibility based on their preference.

**Comment by mikehardy** [comment]
This is coming up in Play Store reviews.

> Introduce a user preference to bypass the congratulations page for users familiar with Anki

This would be great, and is what I think most people want.

**Comment by david-allison** [comment]
Let's use a preference - less user interaction is better for power users

**Comment by boolbag** [comment]
As a single data point, I confirm that a preference would be **a lovely solution**. Flower emoticons happy happy.

Regarding the other question, that of what the Congrats screen should contain (which won't be relevant to me as I'll activate the preference), I'd suggest at least having the "back / undo" button so that the user can return to the previous card in the same way as after every other card in the deck. Just a thought.

**Comment by BrayanDSO** [comment]
> Let's use a preference - less user interaction is better for power users

Just stating that I'm strongly against it

**Comment by mikehardy** [comment]
@BrayanDSO I'm strongly for it. Getting a *lot* of feedback on this one. And I'm normally not for another preference but I'm telling you in mailing list and play store review interaction this is a hot topic

**Comment by j-steinbach** [comment]
From a user experience perspective, the 'congratulation screen' just adds unnecessary friction to the review flow. It does not add anything of value. Anki is something designed to be used daily, so reducing daily friction should be the essential goal.

Personally, I would compare it to a in-game tutorial screen that you just can not skip. Every single time you finish a level, something pops out and explains to you that there is a 'custom study' feature. _Yes, I understood it the first time, now please go away and never come back!_

+1 for the preference solution.

**Comment by boolbag** [comment]
To try to be fair to the other side, I'm sure some users do enjoy being congratulated. But, generalizing grossly, my gut feeling is that that public tends to be more on duolingo. (Kaching! Kaching!) 

In my experience, Anki users tend to me a bit more self-motivated. Counter-argument: is that a weakness of Anki, meaning, could the Anki ecosystem be improved to be more accessible to users who prefer more hand-holding?

I won't attempt to answer this philosophical question, because either way, it seems to me that the proposed solution would make both publics happy.

Huge thanks, Ankidroid team. You have been doing an awesome job for years. Your app is an absolute gem.

**Comment by BrayanDSO** [comment]
I tend to prefer not adding options because we already have too many and that's a common complaint of the users, who feel that the app is too complex. So, IMHO, the most prudent thing to do is discussing alternative options first, like:

1. Can that screen become useful for everyone including power users? Like adding some kind of stats about the review session
2. Can it be dismissed more easily so doesn't become a hassle?
3. Is it a familiarity issue since the change is new?
4. If most people actually don't want the screen, should be better to just remove it?
5. Was the congratulations snackbar better for most users?
6. Should it be shown only to new users in part of the onboarding process?
7. Would it be better if it was displayed differently? Like a dialog (bottom sheet or not)

While there isn't at least a discussion about alternative options, it will be a premature decision and I'm not in favor of that. If all of that is discussed and the consensus is still for adding a setting, I'm fine with it

**Comment by MarkusJLechner** [comment]
The current congratulations screen disrupts the flow without adding meaningful value. Enriching this screen with useful or interesting information could help users see the benefit of this additional step. Also, key details are buried within a relatively lengthy sentence, making them easy to miss.

Moreover, there's no intuitive method to bypass this screen, aside from using the Android back gesture. Incorporating a dismiss or continue option would greatly enhance navigation and user experience. As @boolbag suggested, allowing users to undo their last action from the summary/congratulations screen would be a significant UX improvement.

Additionally, the dismiss or continue button should match the size of the review buttons to maintain consistency and ease of use. Introducing an extra tap for navigation will likely be less disruptive than relying on platform-specific gestures, thereby smoothing out the user flow.

I just hacked an idea together.
![image](https://github.com/ankidroid/Anki-Android/assets/48199873/e805da1c-bb5f-4f70-bfaf-e69557fb654a)

**Comment by j-steinbach** [comment]
If the screen is supposed to add value, and not disrupt flow, then maybe it could show or suggest next decks to study? Ie. I learn my decks in a specific sequence, and having a button to continue with the next deck is the same number of presses as selecting it from the overview.

(Note: I still think that the screen is a terrible idea and should just not exist)

**Comment by MarkusJLechner** [comment]
Great input! Enhancing the interface by modifying the "Continue" button to proceed directly to the next deck would be a valuable enhancement. Perhaps introducing two distinct options, "Dismiss" or "To Overview" and "Continue Review," could enhance user experience. However, I believe implementing this change based on a specific sequence might pose challenges. It might be easier to just pick the next deck with remaining cards.

I also want to acknowledge that my proposal was inspired by BrayanDSO's comment. Despite this, I firmly believe that any alternative would be preferable to the current congratulations screen.

**Comment by boolbag** [comment]
Two thoughts.

1. If the pref is in Advanced Prefs would it really bother newbies?
2. If the kudos screen is maintained, IMO one must-have piece of information is the number of cards due the next day in that deck. Why? This number helps you decide whether to add new cards today. I routinely run this search because there are some limits I like to have for certain deck. For instance, if for deck X I want to see 100 cards at most on a given day and the "due tomorrow" is 88, I can add 12 cards.

The correct way to calculate the number of cards due the next day is this:
"deck:some_deck" (prop:due=1 **OR is:buried**)
This is because BURIED cards are due the next day. Some people don't use that feature, some, such as myself, use it frequently.

**Comment by mikehardy** [comment]
I need to stop the notification traffic here.

Anyone that has time, please implement an advanced preference to toggle this off.

That should do it.

**Comment by Nigel-C** [comment]
Regardless of how useful the screen becomes, it's not something I want. Finishing each deck review now requires an additional button press, and for me it is strictly a downgrade when compared with no screen at all.
I know that some enjoy statistics and that may be useful for them, but the only metrics that matter to me are on the overview screen that is now just slightly further away.

It is a small inconvenience in what is otherwise a great app, and I greatly appreciate all of the work that has been put into making it what it is today.

**Comment by BrayanDSO** [comment]
> If the pref is in Advanced Prefs would it really bother newbies?

We've had a reasonable amount of even power users asking for a setting because they couldn't find an existing one. One of them even did a whole JavaScript setup to compensate that they didn't know the setting exist only to ask here later and discover that it existed. With more and more settings, it will naturally get harder to find a specific one, so that's another reason for avoiding to add settings. Additionally, newbies may also want to hide that screen and so an `Advanced` label wouldn't fit well the setting.

---

Also, the consensus is coming to `The screen is barely useful for anyone, the previous snackbar was better`, so what I  propose for now is hiding the screen and get the snackbar back. No setting. 

When in the future someone works more on that screen, then the discussion of implementing it back or using a setting should return

**Comment by snowtimeglass** [comment]
I add a further comment, _just_ to support for the simple solution as the current title of this issue, _not_ to discuss the ideas for the contents of Congratulation screen further here.


The current silent consensus in Anki ecosystem is to keep the congratulation screen, I think. (If not, it may be better to discuss it in the upstream forum.)

It is desirable that AnkiDroid follow it as possible, and now that it has already been achieved in the officially-released 2.17.x.

Also, the idea of implementing the new option (setting) to respect the consistency should not be treated by the same policy as ideas of implementing new options to move away from the consistency (or to meet users' too diverse needs) like "Sound with answer button would motivate me", "Just two answer buttons would be enough to me". 

Though flexible response for efficiency in this case is nice, the consistency of Anki ecosystem should also be respected. 

So, @MarkusJLechner's first proposal above (as the title of this page):
<details><summary>
</summary>
Just wanted to open an issue about this. Here the content I wrote together:

My proposal would be to add a option to disable the congratulations page for experienced users 

#### Summary
Introduce a user preference to bypass the congratulations page  for users familiar with Anki. This page, while beneficial for newcomers by providing a sense of completion and progress, becomes redundant for experienced users. The main points of contention are the interruption it causes in the review flow and its negligible informational value for those accustomed to the app's review dynamics.

#### Proposal
- Implement a "Skip this page for future reviews" button on the congratulations page.
- Add a setting under Review Settings titled "Show congratulations page," allowing users to re-enable this feature if desired.

#### Rationale
Experienced Anki users, particularly those managing reviews across multiple decks, often view the transition back to the deck overview and the visual cue of remaining reviews as sufficient indicators of session completion. The congratulations page, in these instances, serves more as an unnecessary interruption rather than a helpful summary. Providing an option to skip this page enhances the review process's efficiency and user satisfaction, catering to both new and seasoned users' preferences.

#### Implementation Considerations
- Ensure the "Skip this page for future reviews" option is easily accessible and understandable.
- The "Show congratulations page" setting in Review Settings should be clear in its purpose, allowing users to toggle the congratulations page's visibility based on their preference.

_Originally posted by @MarkusJLechner in https://github.com/ankidroid/Anki-Android/issues/15349#issuecomment-1926226964_
</details>

 is reasonable, in my opinion.

If the position of `Settings -> Advanced` appears too deep for this option, `Settings -> Reviewing -> Advanced` category (it already exists there) would be the appropriate position for the option, even for newbie users.

**Comment by user1823** [comment]
The only reason I like the congrats page is that it tells me whether I would have more cards due sometime later in the day or not.

![Screenshot_20240312-184801~2](https://github.com/ankidroid/Anki-Android/assets/92206575/96782a5a-32e5-46de-b7d0-ba2afe485b10)

Probably, the message which is going to replace this page should include this string too.

**Comment by user1823** [comment]
@david-allison, it looks like my previous comment was missed.

If you read it, a short comment with your thoughts on the suggestion would be appreciated.

**Comment by david-allison** [comment]
@user1823 I wanted a straight revert in 2.17.6 to avoid the possibility of bugs

I'll split this off into a new issue and we can get this in 2.18
