### ISSUE TITLE
2.17 alpha - Reintroduce the old "Statistics" page from older version of AnkiDroid >2.17, by enabling/disabling it

### ISSUE THREAD

**Issue by Fastball2880** [ankidroid/Anki-Android#15345]
**Is your feature request related to a problem? Please describe.**
Due to switching to my old device and using the 2.17 version, the new statistic page doesn't load in Nougat build in Samsung stock, whereas it works on an unofficial LineageOS 18.1 but very slow.

A reference to the old "Statistics" page - 
![](https://m.media-amazon.com/images/I/81evWn0GEML.png)

**Describe the solution you'd like**
Make the user able to switch to the old interface, in the appearance settings, of the statistics for performance-wise.

**Describe alternatives you've considered**
None, yet.

**Additional context**
See above

**Comment by BrayanDSO** [comment]
Updating Android's WebView should solve the problem of the screen not appearing and maybe some of the perfomance ones.

The old statistics can't be re-added in 2.17 because of the last upgrades to have the same code and behavior of the desktop version, so we now use the same screen of Anki desktop.

The team has discussed the issue before and won't work with the old screen again, so I'm closing this issue. I hope you get your problem fixed, and you can ask people here or in Discord if you still need any help.

**Comment by Fastball2880** [comment]
> Updating Android's WebView should solve the problem of the screen not appearing and maybe some of the perfomance ones.
> 
> The old statistics can't be re-added in 2.17 because of the last upgrades to have the same code and behavior of the desktop version, so we now use the same screen of Anki desktop.
> 
> The team has discussed the issue before and won't work with the old screen again, so I'm closing this issue. I hope you get your problem fixed, and you can ask people here or in Discord if you still need any help.

Thank you, updating WebView is worked, as I expected this issue was from using old WebView.

It would be nice if it was brought back but not possible due to major changes to the code. It would be nice however
