### ISSUE TITLE
Handle CI Runner performance improvements

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15368]
might just quickly change the number of threads in CI in the build gradle since they're all 4 vCPU now, and maybe stop doing the in-process kotlin compile? Those are both just toggles and might speed up windows as a quick extra-commit-win

future investigation may be to revive the old emulator test workflow we had that did nested virt on ubuntu to get the emulator to run there and convert tests emulator back to ubuntu ? but keeping it on macos-current is fine for now, incremental steps are positive steps

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/15367#issuecomment-1918305589_

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/0f95d228bd7acef9242ee5a17ac0f84a0350a344/build.gradle#L137-L149

The page now goes into less detail, it's harder to prove the CPUs are 1:1. Needs a minor amount of research

**Comment by david-allison** [comment]
We may also be able to remove the Windows Pagefile config:

https://github.com/ankidroid/Anki-Android/blob/671e84fede1ff1b7530de4f00d11b131ce9b77a9/.github/workflows/tests_unit.yml#L34-L41

**Comment by mikehardy** [comment]
I dug up our old ubuntu "allow access to /dev/kvm + install qemu stuff" so we can run android emulator in ubuntu vms via nested virt as that has some reported success on the new runners:

https://github.com/ankidroid/Anki-Android/commit/f9925c94438dbc1e98db0d134bc51d588dc65a5f

There are people in the community that should have some workflow definitions we can scour as well, since nested-virt has been available in large runners for a few months now. There may be a public repo that nevertheless paid for the large runners and published a workflow, or at least published their findings on how in an open way

**Comment by david-allison** [comment]
Emulator tests:

I suspect we can boot the emulator in parallel with Warm Gradle Cache

<img width="1156" alt="Screenshot 2024-02-02 at 01 44 02" src="https://github.com/ankidroid/Anki-Android/assets/62114487/3931a72b-3635-48ad-9c34-b8a938d32185">

**Comment by mikehardy** [comment]
with regard to booting in parallel - I believe I tried that at one point way back (before the slightly larger machines) and I noticed the same or slightly worse overall throughput. Both the gradle build and the emulator boot are max efforts of the VM essentially (or they were) so it didn't help and it was a simplification not to do so, so I left them in series

May be different with the slightly larger VMs but I suspect not as gradle is capable of maxing out even larger machines I develop on, as is an emulator boot, still

**Comment by david-allison** [comment]
Thanks! I'll hide the suggestion so we can focus on more fruitful efforts!

**Comment by mikehardy** [comment]
Cloud machine type is Standard_D4ads_v5 - which does have same hardware resources which were in the recent publicity around the upgrade ref https://github.com/github/docs/blob/a25a33bb6cbf86a629d0a0c7bef624743991f97e/content/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners.md?plain=1#L176

https://learn.microsoft.com/en-us/azure/virtual-machines/dasv5-dadsv5-series#dadsv5-series

It is listed as nested-virt supported, so that's nice, as a related testing item

It appears the vCPU:CPU is 2:1 however the benchmark page shows the previous VMs getting 37,635 while the current one for public repos gets 72,644 which is conspicuously close to 2x reflecting the vCPU doubling.

I'm going to change test forks from 2 to 4
