### ISSUE TITLE
Is FSRS-4.5 supported or only FSRS-4?

### ISSUE THREAD

**Issue by zxcvxzcv-johndoe** [ankidroid/Anki-Android#15401]
Hello,

Does AnkiDroid's latest AnkiDroid 2.17beta1 support FSRS-4.5, or for that matter does any AnkiDroid version support FSRS 4.5 yet?

I searched but there are no hits for FSRS-4.5 here. 

Basically the question is kind of related to this https://old.reddit.com/r/Anki/comments/18qh94q/anki_2312_changelog/keuwtwl/ (even though the link is about AnkiMobile and not AnkiDroid) and using Anki's desktop version 23.12.1 which uses FSRS-4.5, and what happens if AnkiDroid only supports FRSR 4.

**Comment by user1823** [comment]
AnkiDroid supports FSRS v4.5 since alpha 15.

To know the Anki version that a particular AnkiDroid release is based on, you can go to Settings → About and look just above the Contributors section.

<img width=300 src="https://global.discourse-cdn.com/business7/uploads/anki2/original/3X/3/2/325eac32f4fd9d7bc6da53b46013fdd886209f77.png">

**Comment by BrayanDSO** [comment]
Also, try asking for support in our [Discord](https://discord.gg/qjzcRTx) if it is just a question

**Comment by mikehardy** [comment]
We had a lot of question about cross-compatibility and in trying to solve it noticed that even the anki desktop version number (23.12.1 in this example screenshot) was not necessarily the fully unambiguous way to specify exactly what we are including internally, so that string of characters afterwards is the exact git commit shorthash that you can use to look up a commit in the upstream repo to find out what's built in to ankidroid

Here's an example with that commit hash --> https://github.com/ankitects/anki/commit/1a1d4d54

In that case you can see that this specific commit does bear the "23.12.1" tag in that repo, so we include the exact 23.12.1 code from upstream, no funny business :-)

Writing that up here and re-titling for future searchers
