### ISSUE TITLE
[Bug] 2.18alpha3 publish: The resource R.bool.is_big_screen appears to be unused [UnusedResources]

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15741]
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/bools.xml:3: Error: The resource R.bool.is_big_screen appears to be unused [UnusedResources]

 <bool name="is_big_screen">false</bool>
> Task :AnkiDroid:lintVitalFullRelease FAILED
       ~~~~~~~~~~~~~~~~~~~~
1 errors, 0 warnings
```

https://github.com/ankidroid/Anki-Android/actions/runs/8115373290

**Comment by mikehardy** [comment]
publish script has an order of operations, and a few things happen prior to trying to upload to google (which effectively "consumes" the version number / version code since you can't undo that) and prior to making a commit with the (burnt) version number to memorialize it

The gradle target `:AnkiDroid:lintVitalFullRelease` should run as the first thing I think, as the build failed *after* google got the build and burnt the version, but the full release process wasn't possible in a deterministic way, we just didn't know it yet. So move that up front as the first target run prior to publish play release target I think?

**Comment by david-allison** [comment]
In addition:

* This should fail the regular build

**Comment by david-allison** [comment]
I'm leaving the following to someone with more time, I don't want to rush it

> The gradle target :AnkiDroid:lintVitalFullRelease should run as the first thing I think, as the build failed after google got the build and burnt the version, but the full release process wasn't possible in a deterministic way, we just didn't know it yet. So move that up front as the first target run prior to publish play release target I think?

There's a number of caching steps which don't yet exist in `publish.yml` and I want to be sure we're not submitting release keys to the cache
