### ISSUE TITLE
Access _files through AnkiDroid

### ISSUE THREAD

**Issue by FubayashiKazue** [ankidroid/Anki-Android#15756]
**Is your feature request related to a problem? Please describe.**

Due to Android's restrictions for users to directly access the collection.media folder /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1 it may be useful to implement a way for users to access and manage those files (fonts, pictures etc for use on cards) through Ankidroid. 

please bear with me if my wording is not entirely correct because I'm just a user, not a programmer.

**Describe the solution you'd like**

This could work like this for example:
Settings -> Advanced (as this is something a normal user probably never uses) -> new "Access custom files" -> opens a filebrowser-like window that shows all _files in the collection.media folder.

In this "browser", we could use the following options:
- add file... (opens a dialogue that lets you select files on your phone/sd card and copies them over to collection.media folder, maybe adding the _underscore if the filename doesn't start with it?)
- remove file (for deleting _files you no longer need)
- maybe a rename option?

I know this needs some refinement, and I'm not sure how complicated that would be, but maybe this could be added somewhere in the future :)

**Comment by devharsh2k4** [comment]
@david-allison if this issue is valid can i give it a try?

**Comment by david-allison** [comment]
@devharsh2k4 It's still valid. 

This requires design beforehand. A quick proposal here, then a Discord discussion should suffice

**Comment by devharsh2k4** [comment]
Please assign me up i will prepare and share the proposal till tommorow

**Comment by devharsh2k4** [comment]
Hey for this issue rather than changing the implementation we can try another approach which is granting access to selected media files. we can create a gallery picker where we can use  Selected Photos Access feature permission to control media re-selection, and update our app's interface to let users grant  access to a different set of images and videos.we can check if your app has full, partial, or denied access to the device's photo library and update our interface accordingly and request these permissions when the app needs storage access, instead of at startup.

as we can see we can manage the selected media
<img width="1802" alt="partial-photo-video-access-reselect" src="https://github.com/ankidroid/Anki-Android/assets/103301856/482d86a9-f1bb-495e-b977-b6f986149d81">

choose media to be accessed
<img width="1802" alt="partial-photo-video-access-reselect (2)" src="https://github.com/ankidroid/Anki-Android/assets/103301856/646232e1-0db4-45b5-aea2-316290e9bada">

and it will be updated
<img width="1802" alt="partial-photo-video-access-reselect (2)" src="https://github.com/ankidroid/Anki-Android/assets/103301856/61b9b207-6982-48ee-869c-250b48534220">

**Comment by david-allison** [comment]
I don't quite understand this.

* Adding a new file is already simple
  * Adding a batch could do with work, but most people don't need/want this
* How would a user rename a file?
* How would a user delete a file?

Also bear in mind that device storage is 20-100x slower due to FUSE.

https://source.android.com/docs/core/storage/scoped#fuse-performance-tuning

**Comment by devharsh2k4** [comment]
actually that was another approach which i thought to try but the original approach could be to have an activity or a fragment where we will fetch those media files and up there we can remove and rename the file too
