### ISSUE TITLE
Can't record sound in background state as before

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15822]
Some users seem to feel it is an issue to be fixed.

> Hello
> 
> Sherry the upgrade i cannot record sound from Google Translate. This is because recording stops after losing focus (to switch to Google Translate). Can you fix this?

https://groups.google.com/g/anki-android/c/HFIaaCMKg-Q/m/qu_r6n7vAgAJ

> (...) I am trying to add the sound from the dictionary to the entry, but when I leave the Anki to play the recording in the dictionary (after I pressed record in Anki), Anki automatically stops the process of recording. (...) I will have to leave AnkiDroid if it is not fixed. (...)

(from Play store review)

`AnkiDroid Version = 2.17.5`

**Comment by criticalAY** [comment]
If it is about the audio recorder then it was a bug we say, the recorder was buggy, bug if other want to allow recording even if in background then I can make changes so that it can record until the user is on the Audio recording screen, I will wait for others to respond, 
Though I have proposed to refactor the multimedia editor code in GSoC so if I get selected it will be refactored anyway

**Comment by criticalAY** [comment]
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d319b411-2acf-4dfa-9a61-86e8e8b9d428)

![image](https://github.com/ankidroid/Anki-Android/assets/48384865/29a640cb-4d03-4c94-afe5-fcfa9ba08c8b)

**Comment by BrayanDSO** [comment]
The previous behavior wasn't designed with that intention, so I'm going to consider this as a feature request.

That way, we are migrating feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra work

**Comment by criticalAY** [comment]
I have opened it for @snowtimeglass 
https://forums.ankiweb.net/t/audio-recorder-to-work-if-app-is-backgrounded/44677
