### ISSUE TITLE
[BUG]: SVG CSS update via JS incorrect rendering.

### ISSUE THREAD

**Issue by YellowOnion** [ankidroid/Anki-Android#15863]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I have an svg file, and a simple template that updates the SVG style using Javascript.

```xml
<svg version="1.1" width="162px" height="120" xmlns="http://www.w3.org/2000/svg" id="keyboard" class="keyboard">

<style>
  path {
    stroke: #2c2c2c;
  }
  .white_key {
    fill:white;
  }

  .black_key {
    fill: #2c2c2c;
  }
</style>

<symbol id="white_key_path" width="23" height="120" >
  <path d="M0 0 h23 v115 q0 5 -5 5 h-13 q-5 0 -5 -5 v-115" fill="inherit" />
</symbol>
<symbol width="13" height="80">
  <path id="black_key_path" d="M0 0 h13 v77 q0 3 -3 3 h-7 q-3 0 -3 -3 v-77" fill="inherit" />
</symbol>
<!-- White keys  -->
<g class="white_key">
<use href="#white_key_path" class="note_C" x="0"  />
<use href="#white_key_path" class="note_D" x="23" />
<use href="#white_key_path" class="note_E" x="46" />
<use href="#white_key_path" class="note_F" x="69" />
<use href="#white_key_path" class="note_G" x="92" />
<use href="#white_key_path" class="note_A" x="115" />
<use href="#white_key_path" class="note_B" x="138" />
</g>
<!-- Black keys (overlap with the white keys) -->
<g class="black_key">
<use href="#black_key_path" class="note_Csharp" x="14.333333" />
<use href="#black_key_path" class="note_Dsharp" x="41.66666" />
<use href="#black_key_path" class="note_Fsharp" x="82.25" />
<use href="#black_key_path" class="note_Gsharp" x="108.25" />
<use href="#black_key_path" class="note_Asharp" x="134.75" />
</g>
</svg>
```

```html
<div class="vexbox">
  <h3> Key? </h3>
	<object id="keyboard_obj" type="image/svg+xml" data="_keyboard.svg" onload="changeRectColor()">
  </object>
</div>

<h2 class="answer" id="answer_key" >
{{English}}
</h2>

<script>
function changeRectColor() {
  var img_obj = document.getElementById("keyboard_obj");
  var notes = img_obj.contentDocument.querySelectorAll(".note_{{English}}");
  notes.forEach( (note) => { note.style.fill = "#98ff98"; } );
}
</script>
```

### Expected behaviour

Anki Desktop: 
![image](https://github.com/ankidroid/Anki-Android/assets/364160/7fc5ac58-33b3-4871-a52b-627b1e7bf4b7)

### Actual behaviour

But the CSS modifications from JS don't work on AnkiDroid:

![image](https://github.com/ankidroid/Anki-Android/assets/364160/e53a1b3a-426b-43b9-b0f1-cae7f5b30dd7)

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 4a

Hardware = sunfish

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 4a Build/TQ3A.230805.001.S1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = c023d340-ad1e-45d7-bbe3-fab43e49f220

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Not sure where to start with debugging this. Pretty new to JS coding, and I don't see anything obvious here that would break the script.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
```
"Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')"
```

Also didn't work in 2.16. Probably it's [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) denying `.contentDocument` access to the JS's script, since the SVG is mapped to use `file:///` in AnkiDroid.

Maybe [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) can be used or another approach (I'm not proefficient in that)

**Comment by BrayanDSO** [comment]
The options I see:

### 1. Disable CORS

That needs to manually serve files either in `Webview.shouldInterceptRequest` or `NanoHTTPD.serve`

Downside: loading media is way slower than using `file:/` protocol

### 2. Change the base URL of Anki POST requests and use the media directory as the Webview's base URL

Before, the media directory was set as the `baseUrl` of the reviewer and files were automatically served with `file:/` protocol with top-notch performance and no CORS issues.

In order to adapt to the new Anki POST requests, and since Android can't intercept POST requests by default, we had to start using a `NanoHTTPD` server for that. Also for that, the reviewer's webview uses now `http://127.0.0.1:listeningPort` which may have  CORS issues

By changing the base URL of Anki POST requests and use the media directory as the Webview's base URL, both problems would be solved.

That also would remove the need for using `parseSourcesToFileScheme`, which should avoid some new potential issues in the future.

I believe that that can be done by adding some kind of `postRequestsBaseUrl` property to the backend and use it at the post method:

https://github.com/ankitects/anki/blob/f73eb01047cfba28a4f29ccc3d898b2ca8c9d95b/ts/lib/post.ts#L9-L26

Is something like that possible, @dae?

**Comment by dae** [comment]
It could be done, but AnkiMobile just does a string replace of /_anki/ in the .js files.

**Comment by YellowOnion** [comment]
Nice thanks for the fast fix :-)
