### ISSUE TITLE
[Feature request] - Add an information panel with a list of all possible search commands to the "Browse cards" section.

### ISSUE THREAD

**Issue by Lucius-Will** [ankidroid/Anki-Android#15968]
Now we have to learn the search commands separately in the browser, switching between AnkiDroid and the browser several times. And beginners often don't even know that there are any special search commands.

This problem could be easily solved if the developers add the "All supported search commands" button in the "Browse cards" section, which opens an information panel where all supported search commands are listed with a short explanation of each command.

**Comment by brishtibheja** [comment]
If this is ever added to the card browser it would be helpful if we can just click on the search commands and paste them in the search bar.

**Comment by BrayanDSO** [comment]
Hi there. We are migrating feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra work
