### ISSUE TITLE
[BUG]: Preview is broken: fails to show the content of the card

### ISSUE THREAD

**Issue by XYIheng** [ankidroid/Anki-Android#15994]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. click FAB 
2. click Add
3. enter some text in the Front 
4. click preview button on top-right
5. see the error

https://github.com/ankidroid/Anki-Android/assets/31406320/edc388a0-7aad-4b7f-be19-8fb8a1dc96ce

### Expected behaviour

Show the content of the card

### Actual behaviour

Did not display the card content. Seems the preview is broken

### Debug info

```text
APP Version: 2.18alpha6
Android Version: Android10.0
```

### (Optional) Anything else you want to share?

Preview works well on 2.17.6

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
From your description, you didnt send the debug info correctly, so that makes harder tô help you.

From the vídeo, It looks like you are using an emulator, and emulators commonly come with their not updated Webviews (the debug info would include that info), and the WebView must be a recent enough version for the previewer to work.

I'll preemptly close this ticket. If it happens in a real Android device, and the posted debug info says that the WebView version is at least 77, comment again and this will be reopened.

**Comment by XYIheng** [comment]
@BrayanDSO Thanks for your explanation! I test it with real Android device and find it works well.
