### ISSUE TITLE
Changing the design of buttons of show answer and evaluation of answer.

### ISSUE THREAD

**Issue by jainishrpandya** [ankidroid/Anki-Android#16108]
**Is your feature request related to a problem? Please describe.**
the buttons for show answer and answer evaluation are basic. We can upgrade it to the design like the iOS version of Ankidroid as it looks more attractive designs as shown in the Screenshot.

**Additional context**
<img src="https://github.com/ankidroid/Anki-Android/assets/69842037/10684913-a57f-4115-81ff-54469a632d00" alt="image" width="400px" />

**Comment by BrayanDSO** [comment]
Hi there. We are migrating feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra work
