### ISSUE TITLE
UIUtils: move towards making these kind of functions as top level

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16146]
We should move towards making these kind of functions as top level, using an object as namespace is java like behavior.

_Originally posted by @lukstbit in https://github.com/ankidroid/Anki-Android/pull/15699#discussion_r1536748258_

**Comment by 410063005** [comment]
My Kotlin is a little rusty. I'm not sure I totally understand it.  Is that what we want?  https://github.com/410063005/Anki-Android/pull/2

If it is, can I finish this task in two seperate PRs considering `showThemedToast()` called in many files?

**Comment by lukstbit** [comment]
Yes, my intentions was to remove the useless object _UiUtils_ and make its functions as top level in the same file.
Besides making it more kotlin like, it's very annoying to want to show a toast(for example), write showThemedToast() and the IDE not helping because it's defined in an object(so now I have to do a project search to see exactly in which of our utility classes the functions are declared).

**Comment by 410063005** [comment]
@david-allison 

Please assign this to me if no one takes it

**Comment by lukstbit** [comment]
@410063005 With these simpler issues there's no need to ask to be assigned, just check to see if there isn't already someone working on it, leave a comment that you're working on it(to let other know) and create PRs.
