### ISSUE TITLE
New card design makes long texts look crammed

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16158]
On mobile devices, screen space utilization is of paramount importance.

The new card design introduced in https://github.com/ankidroid/Anki-Android/pull/15893 makes things prettier for cards with short texts. But, for cards with long texts, this new design makes them look crammed. 

Old design:
<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/84bd67c7-efb5-4462-a5a2-3ae1924ad40a">

New design:
<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/562548e0-7a69-43d4-ac4c-dd3447a7c74e">

**Comment by BrayanDSO** [comment]
I don't see much of a difference. And that's only the previewer

It is a valid request, but it's either one design or the other. No options

**Comment by BrayanDSO** [comment]
So, the screen went from 978 to 938 pixels, so the card layout has 95,91% of the previous layout, which isn't a big reduction.

The margins are probably different because it uses Anki Desktop's default margin, not the previous one in AnkiDroid's custom `flashcard.css`. The new margins seem better centered and easier to read, IMO. 

If screen space is your priority, you can set the margins in the notetype CSS

> Weren't you going to implement the same for the reviewer too in the future?

In Discord, I said that I wasn't sure about it. Haven't even decided how to display things yet. I also need to think about what the new `Immersive mode` settings are going to be. Checking if a `card layout` would fit well will be the last thing to do.

**Comment by user1823** [comment]
> The margins are probably different because it uses Anki Desktop's default margin, not the previous one in AnkiDroid's custom flashcard.css.
> 
> If screen space is your priority, you can set the margins in the notetype CSS

Thanks for the suggestion. I have added the following CSS and I am happy with it.

```css
body {
 margin-left: 6px;
 margin-right: 6px;
}
```
