### ISSUE TITLE
Allow enable/disable gesture control on a deck basis?

### ISSUE THREAD

**Issue by soliviantar** [ankidroid/Anki-Android#16170]
I use gestures to rate cards, suspend, etc. when I'm studying Chinese. I even hide the answer buttons by default. This works great on most of my decks.

However, I use a [deck](https://krmanik.github.io/Anki-xiehanzi/) which trains the handwriting of characters and the gestures interfere all the time with this whenever I do some medium-long stroke.

I set the swipe sensitivity to the minimum, but it's still unusable.

Solution: Allow the user to set exceptions for the gestures on a deck basis. I would just choose to not use gestures and show the answer buttons when using this deck.

Alternatives: Further decreasing swipe sensitivity or maybe adding a way to use action gestures only on certain areas of the screen? Or any other solution you can provide. Right now the only thing I can do is going to Settings disabling gestures and enable answer buttons every time I want to study this deck.

Thanks!

**Comment by BrayanDSO** [comment]
This kind of complex workflow is doable through using [user actions](https://docs.ankidroid.org/manual.html#userActions) and the [JS api](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API)

You can map the swipes into `user actions` and add the commands in only the templates that you want. Here's an example:

```html
<script>
var jsApiContract = { version: "0.0.3", developer: "your@email.here" };
var api = new AnkiDroidJS(jsApiContract);

var userJs1 = buttonAnswerEase1; // user action 1 triggers `Again`
var userJs2 = buttonAnswerEase3; // user action 2 triggers `Good`
var userJs3 = () => api.ankiSuspendCard(); // user action 3 suspends the active card
</script>
```

---
The second alternative is to use a different profile and put those decks there. Since AnkiDroid doesn't support profiles yet, there is the possibility of installing a [parallel build](https://github.com/ankidroid/Anki-Android/releases), which is just another AnkiDroid installation that you can be separated from your main one.

---
Since there's already a simple solution (parallel build) and a more complex and versatile one (user actions + js api), I'm going to consider this "solved". 

Gestures controls per deck seems very niche to be a "standard" feature, but it could be added as a JavaScript API option that can be added to the template.

In the future, JavaScript addons are going to be implemented, and that includes an user interface for setting things like this instead of having to code.
