### ISSUE TITLE
Prepare SvelteKit changes for Anki 24.06

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16232]
~~Blocker for AnkiDroid 2.18 release~~

Some SvelteKit changes are necessary

**Comment by BrayanDSO** [comment]
Anki's reference: https://github.com/ankitects/anki/pull/3077

**Comment by dae** [comment]
The svelte changes are not in .1

**Comment by BrayanDSO** [comment]
Oh yeah, it's in 24.04.2beta1 https://github.com/ankitects/anki/compare/24.04.1...24.04.2beta1

**Comment by BrayanDSO** [comment]
Got to the point of loading `index.html` all the immutable resources (css, js, etc), but keep running into this error `"Error: Not found: /sveltekit/graphs"` ([source](https://github.com/sveltejs/kit/blob/0fee61c571db253921d1a6503fc879235c6f3b60/packages/kit/src/runtime/client/client.js#L1297))

Currently with no time or interest to diagnose

**Comment by david-allison** [comment]
Got a patch/branch? I'm also time-limited

**Comment by dae** [comment]
For it to work, the webview should request '/graphs'. The web server should catch that request, and return the contents of index.html. You'll need to teach the web server the various endpoints it should map to index.html, like /graphs, /deck-options/{deck-id}, etc.

**Comment by dae** [comment]
Where is isSvelteKitPage() called?

**Comment by BrayanDSO** [comment]
It isn't called because I didn't see the need. 

Anki uses it [here](https://github.com/ankitects/anki/blob/e50a768e44c4ac30c8e180e410791841ce1f2f13/qt/aqt/mediasrv.py#L345) because `mediasrv.py` needs to differentiate between all the different requests in the app (media, reviewer JS, etc), but here we can have the webview isolated to only the Svelte pages

There's these other calls, but they only make sense in Anki's architecture

https://github.com/ankitects/anki/blob/e50a768e44c4ac30c8e180e410791841ce1f2f13/qt/aqt/mediasrv.py#L729

https://github.com/ankitects/anki/blob/e50a768e44c4ac30c8e180e410791841ce1f2f13/qt/aqt/webview.py#L138

**Comment by dae** [comment]
> For it to work, the webview should request '/graphs'.

> but [client.js](https://github.com/sveltejs/kit/blob/0fee61c571db253921d1a6503fc879235c6f3b60/packages/kit/src/runtime/client/client.js#L1297) says that it couldn't find sveltekit/graphs

**Comment by BrayanDSO** [comment]
Got it to work. Thanks!

I updated the patch. Idk when Anki will release it or when AnkiDroid will ship it, and I'm going to be out for some time, so I probably won't finish it out.

About the patch, the stuff I removed (like setting the background) was just to simplify the debugging process and because I expect most of the PageFragment classes to be refactored and perhaps removed.
