### ISSUE TITLE
Old 2.17.6 card preview toggle option

### ISSUE THREAD

**Issue by Wyzmic** [ankidroid/Anki-Android#16335]
I personally don't like the new layout and there's also less space for the contents. When making adjustments to note types and previewing with the new layout it's hard to tell how it would look when reviewing. Also the audio play button is larger than it is when reviewing as well. ![Screenshot_20240503_000027_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/72083780/3cf2c1fe-06b8-44c7-ba80-594c12c75ae2)

**Comment by david-allison** [comment]
The reviewer is going to be updated to a similar design in a later version, so the screens will be consistent.

I don't see us going back

**Comment by david-allison** [comment]
> Also the audio play button is larger than it is when reviewing as well.

@BrayanDSO FYI

**Comment by BrayanDSO** [comment]
> Also the audio play button is larger than it is when reviewing as well.

It uses the style of Anki Desktop. AnkiMobile uses 64x64px. The current reviewer apparently uses 1em.

I don't care which one is chosen.

---

For the next "this looks different from the reviewer" isssues, using the desktop css there as well would help, i.e.

`<link rel="stylesheet" type="text/css" href="file:///android_asset/backend/web/root-vars.css">` and `<link rel="stylesheet" type="text/css" href="file:///android_asset/backend/web/reviewer.css">` in the **Reviewer**

I won't do that myself because it's temporary work and I'm allergic to that.

**Comment by Wyzmic** [comment]
> The reviewer is going to be updated to a similar design in a later version, so the screens will be consistent.
> 
> I don't see us going back

I see, that's understandable. Thanks for the quick reply!

**Comment by david-allison** [comment]
Given that we'll be transitioning to the new reviewer, which should alleviate both complaints, closing this as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix.

One of our biggest complaints is our user interface, and we get pushback every time we make a change here. 

Old versions are always available on GitHub. At a point in the future, we'll likely be able to use addons to fully customize the reviewer with addons, but for now: I believe this is just unfamiliarity with a new interface, and the feeling of unease will go away with time.

Truly, thanks for the feedback
