### ISSUE TITLE
[BUG]: XMLHttpRequest bug is still happening

### ISSUE THREAD

**Issue by justarmadillo** [ankidroid/Anki-Android#16426]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

After I've reported the error in #16373, and the devs said that it will be fixed in 2.18, after updating to 2.18 the problem still occuring.

### Expected behaviour

loads and opens _collection.html normally without any errors

### Actual behaviour

here is a direct photo from the console when I did debugging

![image](https://github.com/ankidroid/Anki-Android/assets/10810222/3a89e698-e678-4ddf-a553-8ec444366326)

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2101K6G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2101K6G Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.172 Mobile Safari/537.36

ACRA UUID = b8213169-64ed-473b-b9ac-bf2dafbccea7

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by justarmadillo** [comment]
@BrayanDSO maybe you can take a look at this issue

**Comment by BrayanDSO** [comment]
I'm not going to be available to look into this for a time.

As I see, probably the only way to fix that is by reverting to use the http server as the base url of the media directory. Since we are current using the behavior that was used until 2.16, and overall we have only a small number of people affected, I'm going to give this medium priority.

This means reverting #16353, #16140 and https://github.com/ankidroid/Anki-Android-Backend/pull/367. Probably also going back to parse the HTML (either in `TemplateRenderContext` or in the javascript) to use `file:///` by default for images, audios and videos, in order to keep performance top-notch.

**Comment by BrayanDSO** [comment]
Oh, also need to fix `localStorage` again if those things are reverted. Probably by using a fixed port in the Reviewer server

**Comment by 2aecfff4** [comment]
In the meantime, if anyone else has the same issue, you can downgrade Anki without losing your data by using `adb install` with the `-d` flag.
`adb install -d com.ichi2.anki_21706300.apk`.

I downgraded from 2.18 to 1.17.6 and everything works fine.
Do it at your own risk.
