### ISSUE TITLE
Restrict webview in deck options

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16715]
Webview in deck options needs to be restricted. As of now, you can open the manual and find links to github.com and google.com which can be opened in-app.

This was done before in 2.18 version for SharedDecks webview.

**Comment by brishtibheja** [comment]
Well, Anki is a study app so I can't block it with other apps. If this can act like a browser with a few clicks, it defeats the purpose of itself. I think removing distractions should be a priority.

**Comment by voczi** [comment]
would be nice if the manual was just included with the app, and perhaps in anki desktop too?
but not too sure about how much it would affect the binary sizes.. might look at this later

**Comment by david-allison** [comment]
Manual:

* https://github.com/ankidroid/Anki-Android/issues/6829

But I don't particularly want this, due to size concerns

----

**This issue**

I'd propose closing

As [with the previous work,](https://github.com/ankidroid/Anki-Android/issues/16172) if someone wants to make a PR which scratches their own itch, I'd accept it, but we don't have much time from core contributors, and I don't think this would be a good use of time

**Comment by brishtibheja** [comment]
> Real studying requires focus and if the user ends up on the web distracted after several clicks through the deck options my thinking is that user wasn't really studying anyway so this isn't an issue.

I think it's often the case that we would search something study related on Google and end up jumping from one website to another. Normally I would just write down stuff I want to do when I can come online. I don't use the Internet for most of the day and I keep everything blocked. I know Anki isn't a parental app but the app blockers I use as 'parental apps' for myself are turned completely useless if Anki would come with a built in unrestricted browser. Internet addiction is a serious issue for many people, especially if they're young.

I might be biased because this affects me but I think this is serious for some of the users of Anki, probably those of us who are doing serious study and don't want to lose an hour after clicking on a link in the manual.

**Comment by BrayanDSO** [comment]
I tend to accept this mostly because there are educational devices that deliberately disable browsers, and the app isn't supposed to be able to access other sites anyway.

I see the point how disabling it help people addicted to the internet, but there are easier and powerful ways for them to get access to the internet than browsing in AnkiDroid, so I don't consider this a priority because of that.

**Comment by brishtibheja** [comment]
I agree but you can also restrict yourself from every other method of accessing the Internet. In AnkiDroid's case, the problem is it functions like a browser but it is not a browser. The asymmetry renders app/website blockers unusable. So a method that works usually wouldn't work for many people.

**Comment by BrayanDSO** [comment]
Anyway, up to whoever wants to implement this.

**Comment by david-allison** [comment]
Give it a week from now, then close it if there's no interest

**Comment by brishtibheja** [comment]
@RobozinhoD
 Thank you for working on this ♥
