### ISSUE TITLE
Update docs - AbstractFlashcardViewer not accessible from maven API package

### ISSUE THREAD

**Issue by bqv** [ankidroid/Anki-Android#17021]
https://github.com/ankidroid/Anki-Android/blob/eaa0463fd62c894de15955715b8e48e7eccac050/api/src/main/java/com/ichi2/anki/FlashCardsContract.kt#L689-L695

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/aabd99dc4ea1044ef77ff1f57fa79e59ad8b6881/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L2658-L2661

**Comment by benwicks** [comment]
Hi, I'm new to the project so I'm just trying to get acquainted!

- Does the `AbstractFlashcardViewer` class really need to be accessible from the `API` package since this is just a String value?

- I assume the FQPN and constant name are what is stored in the content provider? So if the constants are moved to the `api` module, they would need to retain the exact same FQPN?

**Comment by david-allison** [comment]
* `AbstractFlashcardViewer` should not be visible from the API package
* The constants should be copied into a class the `api` module. Ideally with appropriate attributes to expose them to Java consumers
* A FQPN is not necessary, the `Int` value is used

https://github.com/ankidroid/Anki-Android/blob/4d19c4020a0f522c00315c6476e83c4223203c7d/AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt#L582

Ideally a test should be added comparing the constants, but I suspect you'll have problems with the API -> AnkiDroid dependency

I would add a comment to `Ease.kt` stating that the API should be updated if constants are changed:

https://github.com/ankidroid/Anki-Android/blob/a5191f7b9b8b23f418c981b987bf02414c70c86f/AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt#L18-L23

This is because `AbstractFlashcardViewer` is going to be replaced with `ReviewerFragment`

**Comment by benwicks** [comment]
@david-allison would it be okay to remove the 4 ease `Int` constants and move the existing `Ease` enum to the api module?

**Comment by david-allison** [comment]
Keep them separate & duplicated so we don't have a hard dependency on the api module
