### ISSUE TITLE
[BUG]: LaTeX \texteuro not showing

### ISSUE THREAD

**Issue by TIBOunderscore** [ankidroid/Anki-Android#17226]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

I created an Anki deck on a computer and synced it with AnkiWeb to have it on my phone (Android). I used the \texteuro (€) symbol in some of my cards and, while reviewing them on AnkiDroid, I realized that this piece of LaTeX did not work (unlike the desktop version). This is not a "big" bug but I wanted to let you know about it.
Attached is a screenshot:

Thank you so much for everything you do to keep this app alive!![Image](https://github.com/user-attachments/assets/fc8c6148-3b1a-46a1-959c-73f6a1641c59)

### Expected behaviour

Well, the € symbol is normally displayed directly in LaTeX :)

### Debug info

AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 22101316G

Hardware = mt6877

Webview User Agent = Mozilla/5.0 (Linux; Android 14; 22101316G Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.70 Mobile Safari/537.36

ACRA UUID = fe167ef7-f498-44ef-836d-e121c6584d83

FSRS Enabled = false

Crash Reports Enabled = true

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, is this MathJax or LaTeX? (Could you export and upload a sample card/deck)?

I suspect this is MathJax as AnkiDroid didn't have a LaTeX compiler the last time I checked

**Comment by mikehardy** [comment]
You may also want to check with the latest 2.19beta to see if it is already fixed --> https://github.com/ankidroid/Anki-Android/releases

**Comment by mikehardy** [comment]
I wonder if this would work as a stopgap?

https://math.meta.stackexchange.com/a/8657

`\unicode{0x20AC}`

The root cause of any differences between desktop and ankidroid in the Mathjax area are that we are building+copying their built lib into our repo here, instead of exposing it directly from their repo. Unless we resync by rebuilding+recopying our version goes stale, and in fact we haven't updated things in a couple years:

https://github.com/ankidroid/Anki-Android/tree/433a4c887b96c04308ada10348546cd685bcbe25/AnkiDroid/src/main/assets/mathjax

There is an issue logged to switch our mathjax style so we no longer have a local copy and just expose the upstream version directly, that will *likely* fix this: 

- #15138

**Comment by MorenoTropical** [comment]
Leave it to me
