### ISSUE TITLE
Ensure FSRS parameter mismatch issue has a cross-compatibility plan

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#17236]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

This is mostly a tracking issue to make sure Anki Desktop has a resolution for cross-compatiblity between old and new anki versions when FSRS parameter count changes with 24.10

### Expected behaviour

different versions should be cross-compatible

### Debug info

currently they are not

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Pinging @dae 

My previous idea was to sync two parameters list in 24.10, one with 17 parameters, compatible with old clients, under the current key, and one with 19 parameters under a new key.

If the user optimizes in a newer version, the last two parameters can be stripped and synced under the old key so things keep working

If the user optimizes in an older version, Anki can detect it and re-optimize if necessary.

**Comment by user1823** [comment]
Automatically converting FSRS 4.5 parameters into FSRS 5 parameters is easy and the latest beta of Anki already does that.

However, converting FSRS 5 parameters into FSRS 4.5 parameters is difficult because quantifying the effect of the short-term reviews for making necessary adjustments to the other parameters is difficult.

Anki/AnkiWeb can just strip off the last 2 parameters and make some adjustments to w4 and w5 (inverse operations to those mentioned in https://github.com/ankitects/anki/issues/3463#issuecomment-2388421460). But, I doubt that the converted parameters would perform better than the parameters optimised on an old client.

So, I think that if someone uses both old and new clients, they should optimize the parameters only on the old client until they can update all of their clients to the new backend.

**Comment by david-allison** [comment]
We're going to get review bombed if we don't handle the following cases in a reasonable manner:

* [  ] AnkiDroid > Anki Desktop
  * AnkiDroid auto-updates and the user does not want to update Anki due to addon compat. Anki Desktop is broken
* [  ] AnkiDroid < Anki Desktop
  * A user does not want to/cannot update AnkiDroid (e.g. due to regressions, or their device no longer being supported). AnkiDroid is broken

----

**UX**

The current error provides the user neither explanation nor context (what is a parameter), nor action to take to fix the issue

![Screenshot_20241012_053756_AnkiDroid.jpg](https://github.com/user-attachments/assets/ee346fd3-6c38-4ab7-b039-33cc9b836a93)

Even if we have a suboptimal solution, we & Anki Desktop need to provide the user with a reasonable UX to enable them to continue to review

**Our Release Schedule**

In terms of pending releases:

* AnkiDroid 2.19: 24.06 - 17 params
* AnkiDroid 2.20: 24.10 - 19 params

2.20 will be out quickly after 2.19, we know we need it to be stable for when Anki releases, and will accept fewer risky changes now GSoC is over and development has slowed

**Comment by dae** [comment]
Things don't break until the user explicitly reoptimizes after an update, so I think the "user has no idea what happened" cases are going to be somewhat limited in scope. It's also not going to save us from the inevitable questions about heterogeneous FSRS versions giving different scheduling results for the same card. But I seem to be in a minority here, so will be happy to accept a PR that changes things. Similar to Brayan's suggestion, how does the following sound?

- fsrs5-specific field added to deck config; optimizations stored there
- fsrs5, when fetching params (during review, and in the deck options screen), falls back via 5Params ?? 4Params ?? defaults
- fsrs5 would only write to the new field, so older clients can retain their old params

**Comment by user1823** [comment]
> Similar to Brayan's suggestion, how does the following sound?

Sounds GREAT to me.

**Comment by mikehardy** [comment]
Agreed, that sounds like a solid forwards / backwards-compatible plan. Paves the way as a style for fsrs vN+1 etc etc where there are perhaps truly breaking things

**Comment by mikehardy** [comment]
For the now even smaller group of future people that will be on heterogenous versions of FSRS *and* will notice the different scheduling behavior with the same card *and* will care enough, we can put a FAQ in perhaps that explains what happens if you are on different FSRS versions, and whatever the current client vs FSRS versions are. A trivial / easy thing to do.

Then for AnkIDroid at least we could add the FSRS version to our About page info "anki" line (currently says like `anki 24.06.03 / d678e393` could say `anki 24.06.03 / fsrs4 / d678e393` - but these are pulled dynamically or at build time so will move along nicely in future without ongoing maintenance) to help that be a self-service answer for people and then be done with it?

**Comment by BrayanDSO** [comment]
so, the cross-compatibility stuff needs to be done at Anki's repo, and the FSRS version notice here?

Although what version name of FSRS should be used? FSRS-X or the version at [fsrs-rs](https://github.com/open-spaced-repetition/fsrs-rs/releases)? Or both? (I don't get the naming logic here)

**Comment by mikehardy** [comment]
(note: the version display is a nice-to-have in my opinion, to help any concerned + confused users self-help themselves if they become really preoccupied about scheduling behavior of cards on heterogenous FSRS clients. I *personally* think it's good because I also think it should be easy to do, but just handling the cross-compat case with non-error degradation vs errors up in anki is the thing I'm *really* excited about)

**Comment by Expertium** [comment]
> Then for AnkIDroid at least we could add the FSRS version to our About page info "anki" line (currently says like `anki 24.06.03 / d678e393` could say `anki 24.06.03 / fsrs4 / d678e393`

https://forums.ankiweb.net/t/display-fsrs-version-in-the-debug-info/50236?u=expertium

I have previously proposed that + adding the FSRS version in the debug info, Dae wasn't excited about it.



> Similar to Brayan's suggestion, how does the following sound?
> 
> * fsrs5-specific field added to deck config; optimizations stored there
> * fsrs5, when fetching params (during review, and in the deck options screen), falls back via 5Params ?? 4Params ?? defaults
> * fsrs5 would only write to the new field, so older clients can retain their old params

If it doesn't require any extra actions from the user and is - for all intents and purposes - invisible, that would be really good.

**Comment by david-allison** [comment]
> I think the "user has no idea what happened" cases are going to be somewhat limited in scope.

Just to note: we're already getting user support queries about this

https://www.reddit.com/r/Anki/comments/1g2tmvk/ankidroid_does_not_work_pc_seems_fine/

----

I'm happy with the above solution to use two keys for parameters

I'd want to update AnkiDroid to handle the "parameter mismatch" case and provide a "reoptimize" button at the very least

If we can do it efficiently, we would want to detect that a newer/larger set of parameters exists,

**Comment by user1823** [comment]
> If we can do it efficiently, we would want to detect that a newer/larger set of parameters exists, so we can be both forwards and backwards compatible

I think it would be better to show a Re-optimize button whenever the user has invalid parameters. So, we don't need to know what the future/new parameters look like. IMO, this change should be made in Anki Desktop too.

**Comment by mikehardy** [comment]
Anki-Android-Backend has been published with the FSRS crate version available as `FSRS_VERSION` in the backend `BuildConfig`, so anyone that wants to make a PR in this repo to add it to debug info ([example](https://github.com/ankidroid/Anki-Android/pull/14943/commits/02220de36538e6da0f10c29b556749c38b4ca65d)) / about screen ([example](https://github.com/ankidroid/Anki-Android/pull/14943/commits/d1fb394a8d1990bb584ce7e701ee8946a33d3360#diff-b32b90af874bacc887a4a769abd51c7ec8fc48c71dcb8cb8929bd0a4e526c6e4R64)) can give it a go

**Comment by user1823** [comment]
FYI: Damien has already made the promised change (separate fields for FSRS 5 parameters) in Anki in https://github.com/ankitects/anki/commit/c45fa518d2c0f1d07aff47eadc559c72be7b43c8

**Comment by david-allison** [comment]
Thanks. Voting to close as resolved.

The following still needs to be integrated, should be a separate issue if we agree to close this

* https://github.com/ankidroid/Anki-Android-Backend/pull/427

**Comment by mikehardy** [comment]
Agreed - thanks all, it may be a mountain out of a molehill but I do believe users will appreciate this even if they didn't know it was done, there will be people using incompatible versions for years for whatever reason and they'll be handled gracefully
