### ISSUE TITLE
[BUG]: First Click on Graph Scrolls Page to Top

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#17276]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to Statistics.
2. Go to the bottom at Added graph.
3. Click on a bar on the right side of the graph.

### Expected behaviour

The page scrolls to just above the graph. The next click works completely fine.

### Debug info

2.19beta6

### (Optional) Anything else you want to share?

This issue existed back when the new statistics was added. It was reported here: https://github.com/ankidroid/Anki-Android/issues/15805

The fix was working fine until recently. On another device, I can't reproduce this using beta5 so it's probably beta6 that introduced this.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by deysak** [comment]
The bug resurfaced after https://github.com/ankidroid/Anki-Android/pull/17250 (which used a custom `WebView` implementation to handle nested scroll for Statistics),
and was gone after https://github.com/ankidroid/Anki-Android/pull/16027 (which used `NestedScrollView` to handle nested scroll for Statistics),
before which the same bug existed.

The custom `WebView` implementation does not appears to be the root cause of the bug, as using the vanilla `WebView` also results in the same bug.

Somehow `NestedScrollView` unintentionally suppressed the cause.

**Comment by brishtibheja** [comment]
@david-allison should this get closed as this one used to be an issue when the graph was at the bottom of the screen, not anymore as true retention table is at the bottom and it shows no pop-ups on tap.
