### ISSUE TITLE
AndroidManifest.xml: handle `minSdk 24` changes for  `dropanddrop`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17425]
I've reverted the `AndroidManifest.xml` `dropanddrop` changes.

The upgrade should be extracted to another issue

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/17364#issuecomment-2468146738_

**Comment by david-allison** [comment]
See: 292d662d0b676edf21939b15c88dcf38fb3d83ba for addition

I believe `<uses-feature` should be used, but this caused lint failures.

**Comment by jradchaima** [comment]
Hi @david-allison  I was able to successfully  to fix this bug by adding <item quantity="many">Quedan %d minutos</item> to
<plurals name="reviewer_window_title">
        <item quantity="one">Queda %d minuto</item>
        <item quantity="other">Quedan %d minutos</item>
    </plurals>
 Can I work on this issue

**Comment by mikehardy** [comment]
@jradchaima this needs to be fixed on crowdin in the upstream translations and synced here if we need new quantity translations

There is maybe a deeper problem though - it may also mean that we need to change the quantity definition here first so that `many` is available (I'm unsure on that) or there is something going on in crowdin such that it is not making `many` available, either way, I don't see it upstream on the translation site:

https://crowdin.com/editor/ankidroid/7290/en-ca?view=comfortable&filter=basic&value=0#q=reviewer_window_title

So there is something more to be done here than just adding the translation directly in file

**Comment by david-allison** [comment]
@mikehardy 

The lint rules were moved from `` to `fatal` in:

* https://github.com/ankidroid/Anki-Android/pull/17292

I believe that we should revert this and fix `AndroidManifest`

As below, `ca` is incorrect, and would need fixing on Crowdin

https://www.unicode.org/cldr/charts/46/supplemental/language_plural_rules.html#ca

**Comment by mikehardy** [comment]
Agreed on revert+fix AndroidManifest for now, a shame that's not working well

The last time I took a deep dive on the plurals - while doing that lint odyssey PR - it seemed like maybe crowdin itself had a bug. That is, why isn't "many" an option for Catalan? Shouldn't crowdin know the unicode rules and offer all required plurals for languages ? 🤔 I'm unsure if that's their responsibility or whether we need to have them all present in the source string first.

If it is our responsibility, then I'm unsure how adding a plurals item will affect existing translations - can we just add it, or do we have to make a new string ?

**Comment by david-allison** [comment]
@jradchaima open for work if you want to take on this issue:

* Implement the manifest changes in https://github.com/ankidroid/Anki-Android/commit/292d662d0b676edf21939b15c88dcf38fb3d83ba
* Revert lint rule changes in https://github.com/ankidroid/Anki-Android/pull/17292 : `[UnusedQuantity, MissingQuantity]` until lint passes

**Comment by jradchaima** [comment]
@david-allison Yes, I would like to work on this issue
