### ISSUE TITLE
Review widget

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1842]
Originally reported on Google Code with ID 940

```
Comment from Market:
widget that allows you to flip through flashcards without opening the program
```

Reported by `nicolas.raoul` on 2012-01-12 03:00:34

**Comment by jabobian** [comment]
I would not agree with the labels added by hssm.
The reason is that many smartphones have fingerprint unlock capability now. 
Also when touch the main button, the desktop show
And we unlock the mobile many times a day.
If the memo interface show instantly, one can use many scattered spare time to learn.

It will be great if there is a widget which shows flashcard and allows one to choose level of familiarity (e.g. 3 colored buttons) and to flip the card . 
The font size should adapt to the height of the gadget.
A widget called "bnanu quote widget" can be referred to.
The "Flashcards widget" is also ok, except the font size is too small.
Many thanks!

**Comment by eginhard** [comment]
@jabobian This kind of widget is requested frequently, so in that sense it certainly is important - unfortunately there hasn't been anybody so far who had time to work on this (and any contributions from volunteers will definitely be appreciated).
