### ISSUE TITLE
media folders with 12k+ files not supported

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2060]
Originally reported on Google Code with ID 1158

```
As reported on the Anki forums, if the internal memory or SD card are on a VFAT partition,
there's a limit of about 12k files in a folder, and attempts to write more than that
many files fail. Most desktop users are on NTFS/HFS+/EXT3+ which all scale to that
many files fine, and as iOS also uses HFS+, this issue seems to be limited to old desktops
on VFAT and AnkiDroid.

Perhaps the easiest solution is to provide an option to save the files in a zip and
extract them when they're first referenced on a card, leaving them there. That would
minimize extra writes compared to removing them after a card is displayed. Storing
them in lots of subfolders seems a much more complicated solution: you wouldn't be
able to rely on the html <base> tag for media any longer, and it would make it considerably
harder for users to know which folder media is located in.

Forum thread for reference: https://groups.google.com/forum/?fromgroups#!topic/ankisrs/vrvELhL5V4M

```

Reported by `dae@ichi2.net` on 2012-06-04 06:18:35

**Comment by jytou** [comment]
My main problem is still with Android's media android.process.media process taking loads of time in the media directory and eating up the CPU/battery all the time. So even if I understand that dumping all the media in a single directory may be convenient for the anki developers, I find it poor practice. And I'm a computer engineer, not a "non-computer-friendly" person. It definitely would be best to find another option for this. Either SQL database, either subfolders (which would still not 100% fix the process.media problem, but would somehow be better than only one directory). I consider moving all my media to a web server rather than having to have to duplicate them on all my devices. I understand that this would break the "check media" paradigm, but that can be done differently with a plugin.

**Comment by timrae** [comment]
Are you using an external sd card?

**Comment by jytou** [comment]
Yes (but at the beginning, I wasn't - in the end it doesn't change a thing). I also tried adding a dot at the beginning of the folder name (some claim that this would "lure" the media scanner into thinking it's a system folder and thus not scan it, but it still gets in it), as well as the regular ".nomedia" file, to no avail.
Note that my tablet is not that new, it's a Galaxy Tab 2 10.1, Android 4.1.2. And no I don't plan upgrading it.

**Comment by jytou** [comment]
... and just letting you know that beside this media library problem, Anki is a wonderful piece of software. :)

**Comment by timrae** [comment]
I had the same problem with my galaxy S2. I don't have either of the 12k
limit or the scanning issues after upgrading to an Xperia, which has a
decent internal filesystem.

As far as I'm concerned, they're both legacy issues that can be fixed by
upgrading to a newer device, so I don't feel it's worthwhile for us to make
any big architectural changes.

**Comment by aleksejrs** [comment]
My Alcatel smartphone with Android 5.0 supporting only FAT32 on the SD card starts having serious issues (frequently unmounting the SD card or refusing to mount it altogether) with less than 300 files with some very long names in a single directory (the names in Anki are shorter, so it worked with over 800 files, but that was just 1 to 3 days of due cards).

**Comment by mikehardy** [comment]
Looks like it is unassigned now, but it's also more than 2 years since an update on an issue that's not going to be fixed I don't think...shouldn't matter?

**Comment by jytou** [comment]
I have found an alternative (I'm actually storing my media on an external server and only have links to it). It's working for me. I still think that forcing everything to be in one single directory is a recipe for trouble.

**Comment by mikehardy** [comment]
...and a PR that maintains the "flat" appearance of the media for import/export/synchronization but transparently sends and/or moves things like "AA.mp3" to "A/AA.mp3" with no locking, synchronization, or data-loss issues across the entire Android API version and device skew of the installed base should be easy to code up. I'll be happy to review and help QA it... To avoid doubt, I am being a little sarcastic - I mean, that's probably how I'd go about solving this and maybe it would even be fun to code up, but it's not a small thing. And it doesn't get reported much whereas we have some other pretty serious issues to work on.

**Comment by connwork** [comment]
Does anyone know if this is still an issue? It is closed as completed but I cannot find the fix details.

**Comment by timrae** [comment]
See https://github.com/ankidroid/Anki-Android/issues/2060#issuecomment-177340106. We considered it to be a legacy issue as it's only a problem with FAT32 file system, which we don't really see being deployed in modern devices anymore. Therefore we decided no fix is required.
