### ISSUE TITLE
Native LaTeX rendering

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2200]
Originally reported on Google Code with ID 1298

```
Some people might be typing math flashcards on their Android tablets, without Anki Desktop
present to do the rendering.

http://stackoverflow.com/questions/5820740/typesetting-math-functions-in-latex-to-render-in-android-application
http://stackoverflow.com/questions/5767409/math-or-latex-engine-for-droid-phones
```

Reported by `nicolas.raoul` on 2012-08-04 17:53:35

**Comment by maurimo** [comment]
It would definitively be great, anki with MathJax could be a wonderful tool for complementing teaching.
I tried to put a MathJax distribution in the media directory but it is tricky to make it work, the directory structure needs to be flattened with files starting with _, and the loading script edited accordingly, this integration still has many limitations and bugs, and what it worse, it does not work on Android and I have no idea about how to debug it!

**Comment by SzymonPajzert** [comment]
Is there any solution to this issue? I've just noticed that neither [$] nor [latex] markups are working on my phone.

**Comment by Data-Science-Solutions** [comment]
What are the chances of AnkiDroid following the example of Anki 2.1 beta, AnkiWeb, and AnkiMobile beta to offer MathJax support out of the box?

Anki 2.1 has supported MathJax since beta 5 (the latest version is beta 27 now, so this feature appears to be consolidated now), and I would love to avoid the constant transfer of precompiled LaTeX images between my desktop computer and smartphone. As mentioned in the first post, this would also allow users to create cards featuring math on mobile devices. It would also facilitate the dynamic creation of math problems using javascript.

Could you please consider increasing the priority of MathJax integration? If so, do you have any idea when we'll see the implementation in a beta release? Thank you for all your work so far!

**Comment by timrae** [comment]
> What are the chances of AnkiDroid following the example of Anki 2.1 beta,
AnkiWeb, and AnkiMobile beta to offer MathJax support out of the box?

This question is equivalent to "what are the chances that someone submits a
PR implementing MathJax support?", hence I cannot answer it. For sure I
don't have time to implement it myself, but I think it's a great idea.

**Comment by Zerophase** [comment]
I'm a bit bored and should have some free time, within the next month for implementing this. Where should I start looking for implementing this?

**Comment by timrae** [comment]
I guess I'd start by looking at the anki desktop implementation and then figure out how to port it over to Android

**Comment by wuffi** [comment]
The problem with creating a card type rendering MathJax by including

    <script src=".../MathJax.js?config=...">
    </script>

as mentioned above is that it doesn't work on Anki Desktop.
Anki Desktop's MathJax snippets in turn don't work on AnkiDroid (as well as on AnkiWeb), as far as I could see.

It would be great to have Anki Desktop MathJax support also in AnkiDroid, so that synchronization would work smoothly.

**Comment by telotortium** [comment]
There is a good workaround here: https://github.com/ankidroid/Anki-Android/issues/4915#issuecomment-433134498. This loads MathJax from an external CDN, but otherwise works nearly perfectly, and lets you use MathJax on all of Anki 2.0, Anki 2.1, and Ankidroid 2.8.

**Comment by timokau** [comment]
Looks like @adamwolf implemented this in https://github.com/ankidroid/Anki-Android/pull/5285, so it should be in the next release (thank you!).

So this can probably be closed.

**Comment by mikehardy** [comment]
yeah already out in betas even it'll be public release shortly
