### ISSUE TITLE
Feature request: Record speech for comparison with audio on card

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2221]
Originally reported on Google Code with ID 1319

```
Please explain your idea here.
When reviewing a foren language, some facts may include audio. I'd like to make a card
like this:

Q
1. The card's audio is played
2. Audio recording is activated (automatically or by pressing some button) so that
I can record my pronunciation of the phrase.

A
1. When pressing "Show answer", my recording is played back
2. The original audio is played back for comparison (maybe after a short delay)
3. I rate my answer according to the accuracy of the pronunciation.
4. Delete recorded audio.

The quality of the audio may not need to be very high for speech, I think.


Is this feature available on similar apps (Anki Desktop, AnkiMobile,
AnyMemo, etc) ? If yes, it could help to include a screenshot or link to a page explaining
the feature.

I think there is a plugin for pre-2 Anki, but I have never used it, so I don't know
whether it works as I have described, or will/can be ported to 2.x. 

This would be a nice feature for all platforms, though, so some discussion between
the projects would probably be necessary. I have not suggested this to the Anki project,
since ankidroid is what I use daily; let me know if I should.


```

Reported by `fropeter@online.no` on 2012-08-13 20:21:48

**Comment by koendv** [comment]
I patched Ankidroid to do just that. You can download an Ankidroid binary and a sample deck from the [github](https://github.com/koendv/Anki-Android)

**Comment by dvopalecky** [comment]
I would use such feature for the following use case:
Having cards with Bible verses which have sometimes 50+ words.
Question: Verse reference. I press audio button and record the answer.
Answer: The answer is displayed and my recording is played back, so that I can check that I said the whole verse correctly word for word.

This feature is available in the http://www.remem.me/ app, but I would prefer to have it in AnkiDroid also.

I will probably check @koendv solution, but it would be nice to have it in the official version as well.

**Comment by mikehardy** [comment]
@koendv that's fascinating - you've got a good fork there. It's not too far off from master even now (I looked at the diff - looks like lots of localization stuff but the feature itself isn't too heavy - it's pretty self-contained). 

Do you have any interest in trying to integrate with mainline? I could try to help shepherd it to a merge as long as we could figure out a way to do it well and Tim likes the idea. 

The only thing that gives me pause is that the DSP jar is 11MB and right now AnkiDroid in total is around 8MB, so this would grow the app a lot (your release is 20.8MB total for the APK). It looks like the added libraries are about 5MB per CPU architecture, so if we used the new split-APK style the majority of the users would probably see about the same 8MB APK. I think it has potential, what do you think @timrae  ?

**Comment by dvopalecky** [comment]
@koendv, I checked you solution for my use case on Bible verses.
Currently it's not usable for my use case because of two reasons:
1) There is a limit on the audio length that you can record while reviewing - probably about 10 seconds. Sometimes my cards have longer texts, so I would need the limit to be increased to 1 or maybe even 2 minutes.
2) The record button shows only if there's an audio in the card or maybe only in the question. I would need the ability to record my voice also on pure text cards. I don't need the intonation graph.

Would you be willing to do these updates?
Thanks a lot for your work.

**Comment by dgeranton** [comment]
I have proposed a patch to allow that activation of the audio record tools during card review.
Here is the branch : https://github.com/dgeranton/Anki-Android/tree/feature/reviewer_add_mic_tool_bar

**Comment by koendv** [comment]
Nice. But maintaining a patch on your own through various Anki versions is a lot of work.  Try to get it into the official AnkiDroid source so it becomes part of the community effort.

**Comment by mikehardy** [comment]
@koendv @dgeranton did propose a PR, it's linked above the comment in the github web ui and I will consider it once back from travel 👍

**Comment by fabricem1** [comment]
@koendv I couldn't use install your binary. I get a message saying "App not installed".

**Comment by koendv** [comment]
OK. Maybe because you have a newer version of Anki already installed, and Android does not want to overwrite a newer version with an older one?

**Comment by mikehardy** [comment]
@dgeranton has implemented this in #5774 - will be out in the next 2.12alpha

**Comment by fabricem1** [comment]
I just wanted to say thanks guys for implementing this.  It's made my mobile use of Anki so much better. How do I make a small gesture to express my gratitude?

**Comment by mikehardy** [comment]
Hi there @fabricem1 ! I think the most direct way, if you like - and perfectly fine if you don't like :-) - is via our opencollective - https://opencollective.com/ankidroid - we are paying that out in a stable / monthly installment way to anyone that posts PRs here, so it goes directly to contributors and is (in my way of phrasing it) like the internet buying you a coffee, as a way of saying thanks for the effort. Glad you like the feature

**Comment by fabricem1** [comment]
Hi Mike,

Thanks.  That's exactly what I was looking for.

Kind regards,

Fabrice
