### ISSUE TITLE
Randomize new cards

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2310]
Originally reported on Google Code with ID 1408

```
What steps will reproduce the problem?
1. Added 5 cards( 1 2 3 4 5)
2. Selected "Deck preferences" > "New cards" > "Order"
3. Choosed "New cards in ramdom order"
4. Start reviewing

What is the expected output? What do you see instead?
It should randomize the cards added, but displayed them in the order they were added.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
Tried to select the option "New cards in ramdom order" again, but it happens again.
I thought the text in options was wrong and also tried to Select "New cards in order
added", but it also showed in the order added.


What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
On what version of Android? (Home screen > menu > About phone > Android
version)
Ankidroid 2.0 beta18, android 2.1.


```

Reported by `renato.g.amici` on 2012-10-05 23:38:32

**Comment by HairyPhil** [comment]
This issue has been closed but has not been resolved. It is marked as a duplicate of issue #1354, but that issue seems unrelated. I think this issue should be reopened.

Summary:
In Deck Options > New Cards > Order, if Random Order is selected, new cards are not actually in random order, they are in order of most-recently added. (Example: If I add cards 12345 and select Random Order then I expect new cards in the order of 13524 but I get 54321.)

AnkiDroid v2.8.4 on Android 9.0 on Pixel 3.

**Comment by timrae** [comment]
Please check on Anki desktop whether or not the same issue occurs. If the problem is really only in AnkiDroid then open a new issue here with more details on how to reproduce. If the same issue exists in Anki desktop, you can ask on the main Anki support site.

**Comment by HairyPhil** [comment]
Okay, you're right, it happens on Desktop too. I'll head over to main support.
