### ISSUE TITLE
Negative Review time

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2351]
Originally reported on Google Code with ID 1449

```
I copied my ankidroid data to my desktop and its showing studied 417 cards in -596 hours

Using ankidroid 2 beta 19 on samsung galaxy s 2.3.5
```

Reported by `otaku.hari` on 2012-10-27 14:04:32

**Comment by dotancohen** [comment]
I can confirm that the issue still exists in Anki 2.1.15. I do most of my reviews on an E-ink device with Ankidroid and sync via the built-in sync mechanism. The deck is in use since 2009, with 30,000 cards and over half a million reviews.

![Screenshot_20191129_174444](https://user-images.githubusercontent.com/246144/69879527-53ffec00-12d0-11ea-96c2-65f6f101b705.png)

**Comment by hssm** [comment]
It is technically [still possible](https://github.com/ankidroid/Anki-Android/pull/3652#issuecomment-142786993) to get a negative review time on any client. Is this a once-off issue or is it common?

**Comment by dotancohen** [comment]
@hssm I am not sure. I've noticed the issue in the past but never fixed it. The addon for [fixing the issue](https://ankiweb.net/shared/info/3009264632) won't run in 2.1 so I just ran `[update revlog set time = 60000 where time < 0](https://github.com/ospalh/anki-addons/blob/44167e25c57dbc3939e37c075d3d580f5be362cf/fix_negative_review_times.py)` and the issue seems resolved.

If it comes back should I report here, or open a new issue?

**Comment by hssm** [comment]
Best to open a new issue.

**Comment by dotancohen** [comment]
Will do, thanks!
