### ISSUE TITLE
synchronization doesn't work - timezone issue

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2402]
Originally reported on Google Code with ID 1500

```
It worked. I installed the last version. When I try to download my decks I see only.

The time of your device is different than that of the server by 68340 sec, the device's
time zone is possibly wrong; unable to sync.

I tried to change it.
```

Reported by `gaal.dev` on 2012-12-08 06:20:36

**Comment by gerich-home** [comment]
![screenshot_2016-03-20-16-23-03](https://cloud.githubusercontent.com/assets/296593/13904638/d7580cfa-eec0-11e5-8a3b-a09350bf041a.png)
![screenshot_2016-03-20-16-25-25](https://cloud.githubusercontent.com/assets/296593/13904664/42014616-eec1-11e5-9820-a10293934ef7.png)

Hi, the issue is still reproducible. Please reopen.
Some more details: when I change the time to 17:25 (in the same example) sync completes successfully.
However the issue does not reproduce on Windows client and it works fine there (in the same timezone).

**Comment by timrae** [comment]
What happens if you change the "Automatic date & time" setting to On?
3739 seconds is about an hour so it's almost certainly a time zone issue with daylight savings. Please see [here](https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-i-get-an-error-about-the-timezone-when-i-try-to-sync) for details about fixing the issue if the above doesn't work.

**Comment by gerich-home** [comment]
The time gets adjusted to wrong time in System (for some reason both GPS and cell time are wrong)  and sync starts working, but it is not convinient to adjust system date all the time I want to sync.

**Comment by timrae** [comment]
Please refer to the link I previously posted

**Comment by gerich-home** [comment]
Sad to know that I have to manually change time each time I want to sync..
But thank you anyway!

BTW, it would be really good to have an ability to override time offset somewhere in AnkiDroid's settings menu. Such unhappy users as me will become much happier :)

**Comment by timrae** [comment]
> Sad to know that I have to manually change time each time I want to sync

I'm not sure where you got that from... there are two recommended solutions in the link that I previous supplied to you.

**Comment by gerich-home** [comment]
Oh, I have read them - the only suitable for me is to change the time manually each time, as I want neither root my device nor change timezone (to do not confuse other programs cause it shows me the correct one - Moscow and I am located in this timezone)
