### ISSUE TITLE
Introduce minimum delay between tapping show answer & ease buttons to prevent double-tap

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2458]
Originally reported on Google Code with ID 1556
```
What steps will reproduce the problem?
1. Have a neurological disability that causes tremors of the hands.
2. Press a button.
3. Get unintended double tap.

What is the expected output? What do you see instead?

I see the next question when I wanted the answer.  This is associated with unintended
tapping of the bad\good\easy buttons.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?

Pretty much any time I have problems.

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
v2.0

On what version of Android? (Home screen > menu > About phone > Android
version)
n/a

Please provide any additional information below.

Due to disgraphia and other related disabilities, my hands tremble.  They have since
I was a child.  With sensitive apps on Android, this causes double taps of buttons.
 Where it causes a problem in Anki is when I tap the "show answer" it sometimes causes
me to select the bad\good\easy button below wherever I tapped.

On the small screen, I see there is no place to move the buttons to so that they do
not overlap.  The only solution I can see is an adjustable setting to add a delay before
the bad\good\easy buttons are enabled or before they appear.  I saw adjustable because
different people (such as the elderly or people with disorders like ALS and Parkinson's
disease) have different levels of trembling than I have.  Even a few options like 0.1,
0.5, and 1 second might be enough.

```

Reported by `1eric.mccormick` on 2013-01-04 19:20:09

**Comment by gilamori** [comment]
Issue: Remove delay to enable intentional double-tap :)

I recently got a new phone, which automatically installed the latest version of AnkiDroid (my old version was from 2014). To my frustration and annoyance, with the latest version I am no longer able to quickly double-tap in the lower right corner to get to the next card. Today, I managed to find this page, which seems to be the cause of my problems. So apparently I am the exception to "Nobody would even notice the difference, except in a good way."

It doesn't look like many other people are having problems with the delay (and it's obviously really useful for some people), and I guess I could keep using an AnkiDroid version from 2014 forever, but personally, I'd love it if someone could make the delay adjustable. My old version of AnkiDroid kept crashing, so now it seems I have to choose between a crashing version and a frustrating version that forces me to change the way I've used Anki for six years.
