### ISSUE TITLE
Deleting decks and importing cards from apkg is too slow

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2547]
Originally reported on Google Code with ID 1645

```
Deleting and importing cards is too slow. What takes less than a second on the desktop
can take more than 30 min for large decks on AnkiDroid. Clearly my PC CPU is not 1000x
faster than my Galaxy S2, so the code itself is doing something really inefficiently.
```

Reported by `perceptualchaos2` on 2013-01-27 06:29:14

**Comment by mikehardy** [comment]
Interesting, I didn't realize deleting was a problem as well. Cross-linking this with #4864  and #4481  as they are related

**Comment by timrae** [comment]
Wow this issue is 5 years old, and opened by me before I started contributing to the project. I'm pretty sure I fixed the problem at some point, so will close this.

**Comment by atomical** [comment]
@timrae Not from what I can see. I have a Pixel 2 and have been loading a deck for 30 minutes.

**Comment by mikehardy** [comment]
@atomical any details on the size of deck you are importing? I'm aware it is still possible to have slow imports on extraordinarily large decks (for instance, it wasn't even possible to import decks greater than 2GB until recently, but we made some changes to break through that barrier) but performance should now be more on order of O(n) or O(n^logn) so that the import does still work, and does keep reporting progress, but might take a while for gigantic decks.

Something else to think about is that during that time you do need to occasionally interact, which is not great but has a feature semi-in-progress: #7078

**Comment by atomical** [comment]
80 megabytes.

....

**Comment by mikehardy** [comment]
Interesting - perhaps a better measure than raw size (as that scales with media but media does not actually slow things down other than a minor impact on unzip / copy speed which is dependent on storage throughput and does not really impact total time much) is the count of cards in the import. The 'n' in my big-O notation above was count of cards, and I was not specific, sorry
