### ISSUE TITLE
font color for selected words differs between Android one one hand and Linux and WebAnki on the other hand

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2603]
Originally reported on Google Code with ID 1701

```
What steps will reproduce the problem?
1. Use Anki client under Linux (Ubuntu 11.04): create a card with some words colored
differently than the default color using GUI "Set Foreground" dialog.
2. Sync to the web server. The colors of the words remain the same on web client as
under Linux.
3. Sync onto an Android device
4. The colors of the words change on Android (HTC Droid Incredible, CynogenMod 7.2.0).

What is the expected output? 

The colors of the words on flashcards on all devices should be the same

What do you see instead?

Linux,web  |  Android

blue       |  yellow
red        |  turquoise
yellow     |  blue
green      |  purple
purple     |  green
brown      |  brown
orange     |  blue
gris       |  gris
turquoise  |  red

Notice that if one looks in HTML source under Linux and Android the blue color is represented
as <font color="#0000FF"> as it should if RGB color model is used. But apparently something
else is used on Android and that hex is interpreted differently.


Does it happen again every time you repeat the steps above? Or did it
happen only one time?

Always


What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)

2.0.1

On what version of Android? (Home screen > menu > About phone > Android
version)

2.3.7

If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.

```

Reported by `igor.2004` on 2013-02-28 02:46:57

**Comment by cipri-tom** [comment]
Is there an easy way to change or edit multiple cards in a deck?

**Comment by eginhard** [comment]
I'm not sure what you want to do. Change the font colour of multiple cards because you posted it here? You can do this via [card templates](http://ankisrs.net/docs/manual.html#cards-and-templates).

For general questions like this I'd recommend to use the [mailing group](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/anki-android).

**Comment by cipri-tom** [comment]
I'm sorry I abused the bug tracker to ask newbie questions.

A shared deck I got has `<font color="#0000FF">` in the actual field of the card, instead of using another field with a CSS tag. Because of this bug, cards get displayed differently in Anki-droid with night-mode `ON` than on the desktop and I cannot use the above fix, since the color is hard coded in the card.

I was wondering if you could suggest a way of accessing the cards so that I can edit out that text. If there's a way to export them to text and import back, then I can use text manipulation to fix the deck (500 cards).

---

Sorry, again, for using the bug tracker. I don't know why I unassigned `ankidroid`.
I'm getting some error when trying to access the mailing group.

**Comment by eginhard** [comment]
AnkiDroid doesn't have such a functionality, but you can synchronise your cards to Anki Desktop and use it's *find and replace* feature: http://ankisrs.net/docs/manual.html#find-and-replace

**Comment by cipri-tom** [comment]
Perfect! Thank you! 👍 
And sorry for the noise. I should've RTFM 😊
