### ISSUE TITLE
Custom color stroke for whiteboard

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2731]
Originally reported on Google Code with ID 1829

```
Hi, I added a color picker and using the picked color for the whiteboard.
The library I added to supply the color picker was:
https://github.com/attenzione/android-ColorPickerPreference

As you can see from my screenshots, it works well!

One tiny problem, monochrome and custom color can be enabled at the same time. If this
happens, the color will appear on the screen as you write, and when you let go, it
will turn monochrome.
This can be fixed, I think to stop both checkboxes from selected at the same tie, this
needs to be done in java code, not by xml.
Although, I think when you have a case like this, you should use radioboxes.

Would this addition be nice for AnkiDroid? I can set up my computer so I can do a pull
request etc, but I just want to see if you guys like it first.

Thanks a lot :)
```

Reported by `woof.addict` on 2013-08-26 16:08:50

<hr>
- _Attachment: Screenshot_2013-08-26-14-51-31.png<br>![Screenshot_2013-08-26-14-51-31.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-1829/comment-0/Screenshot_2013-08-26-14-51-31.png)_
- _Attachment: Screenshot_2013-08-26-14-51-52.png<br>![Screenshot_2013-08-26-14-51-52.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-1829/comment-0/Screenshot_2013-08-26-14-51-52.png)_
- _Attachment: Screenshot_2013-08-26-14-53-03.png<br>![Screenshot_2013-08-26-14-53-03.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-1829/comment-0/Screenshot_2013-08-26-14-53-03.png)_

**Comment by david-allison-1** [comment]
This one comes up quite a lot

**Comment by maxily** [comment]
Not sure about the library to use for this. All I found hasn't been updated recently.
Also thought that the behavior shouldn't be over complicated by popup or any complex color picker UI itself.
In the example below I used [Spectrum](https://github.com/the-blue-alliance/spectrum).
Would appreciate any ideas?

![whiteboard_palette](https://user-images.githubusercontent.com/6668375/85201022-2b187480-b350-11ea-9a9c-5d65c7ef0112.gif)

**Comment by timrae** [comment]
Can't this just be a global preference for the whiteboard color? When I said 5 years ago that we'd welcome a PR for this, that was what I meant. I'm not really in favor of further cluttering up the reviewer with new menu/toolbar items for dynamically changing the color tbh. I spent a lot of effort cleaning up the AnkiDroid code base over the years, and consequently have been pushing back pretty hard on most features that aren't already in the Anki ecosystem or have an extremely strong use case for a lot of users, as I've seen what happens when you just accept every PR willy-nilly.

**Comment by mikehardy** [comment]
@timrae as a sincere question - what happens? My concerns are generally 1 "(over-)proliferation of options in high traffic areas" and 2 codebase is hard to maintain as inertia increases

Is there something else to be concerned about that is a good lesson learned? I would love to know if so

2 I am actually a bit less concerned about at the moment as the efforts to increase automated testing are beginning to catch things so maintenance of older features is becoming less cumbersome

1 is something I am concerned about though, it's a general issue and right now the reviewer menu in particular is bloating out, I'm not pleased with current state

**Comment by timrae** [comment]
Mainly one and two. I think maintenance is more of a problem than you might think. Tests don't catch everything and just because you have lots of tests telling you that you've broken lots of things doesn't make it any less frustrating when your "simple" change ends up taking two weeks because the code paths have become too convoluted.

In retrospect, I think accepting the advanced editor was a big blunder on our part, we were too eager to have the feature that we overlooked how unmaintainable that code was, and didn't check whether the author was willing to commit to long term maintenance.

We went through a massive effort of simplifying the settings and menus some years ago due to multiple and frequent complaints from new users that there were too many and too hard to understand.

**Comment by mikehardy** [comment]
Agreed on the advanced editor, I'm suffering in that 🍝 right now with #6543 trying to bring crop home.

Agreed tests don't help everything, but we are also reviewing pretty strongly now. This will be another tough balance point I think. I definitely hear you.

The options thing is definitely an ongoing problem as well. I'm thinking about it and need to study some more on how to shape a power user tool that doesn't suck for new users, in general. There must be existing patterns (e.g., "opinionated set of defaults w/everything hidden until you toggle an "advanced mode", "a help icon next to options that links to relevant manual chunk", there was the new user intro idea that did a quick in-app tour) plus organization of options.

**Comment by timrae** [comment]
I'm not following any of the discussions in detail, but tbh I feel like I'm seeing a pattern of pull requests being reviewed before any high level discussion or decision about whether a feature is justified or how it should look.

In this specific case there is an exisiting issue, we've said that we'd take a PR for a global preference for whiteboard colour, and then PRs have popped up that are far more intrusive without any discussion.

IMO before even starting a code review (or ideally before anyone starts coding) there should be a discussion on a GitHub issue about whether the feature is necessary and how it should be implemented. We should be discouraging people from submitting PRs without any prior consultation of the maintainers.

**Comment by timrae** [comment]
I should probably also say that I tend to only make knee-jerk reaction posts when I disapprove of something recently, but you guys are all doing an amazing job, and I hope my little comments are taken constructively.

**Comment by mikehardy** [comment]
I take them constructively and appreciate them. Coding is something I know I can do. Shepherding code is something I did once about 20 years ago and wasn't ready for at the time, I know it's hard and am always looking for feedback ...
