### ISSUE TITLE
Reschedule whole deck as new

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2746]
Originally reported on Google Code with ID 1844

```
Please explain your idea here.

I would like to ask can I set back my decks to the original (unused) status?
I would like to restart learning with some of my decks, and I can't find this option
anywhere.
Is there any option in Ankidroid? If not, it will be important in my opinion.
Thanks.

Is this feature available on similar apps (Anki Desktop, AnkiMobile,
AnyMemo, etc) ? If yes, it could help to include a screenshot or link to a
page explaining the feature.
```

Reported by `botondbori` on 2013-09-18 10:03:48

**Comment by erikamit** [comment]
Why? I use Anki to learn bird songs. Every spring. By fall, I don't have time to review the songs anymore. And by the next spring, I've forgotten everything and need to start over. Gosh, I wish there was a built-in button in Anki so I could just start over without having to export everything and re-import.

**Comment by AMDsn** [comment]
I've imported someone else's deck that contained scheduling information associated with cards annnd it's really annoying, that's why

**Comment by flerda** [comment]
You can use the add-on mentioned in the previous comment if you would like.
Alternatively, you can re-export without schedule, delete the deck, and re-import.

I hope this helps.

**Comment by raulfdm** [comment]
> I have created an add-on to perform this function; see:
> https://ankiweb.net/shared/info/1432861881

The workaround above doesn't work on v2.1+.

In my case, I've stoped to do flash cards for 7 meses and wish start my old decks again.

**Comment by mikehardy** [comment]
Just cross-linking issues - I think this may be achievable with the #2339 PR

**Comment by mikehardy** [comment]
@raulfdm In Anki Desktop: Go to Browse. Then click the deck you want to reset on the left side column. Then click Edit --> Select All and then "reschedule"

**Comment by mikehardy** [comment]
Worth noting that this is the most popular content the project. No matter what SRS has to say about resetting a deck, it is clearly important to many people - https://github.com/ankidroid/Anki-Android/graphs/traffic

**Comment by mikehardy** [comment]
Okay, I've looked at this again since it's so popular, and it's really two requests in one.

The first request is to completely obliterate review information. This case happens when you import a deck that contains someone else's scheduling information and the review history is completely unwanted. Neither Anki Desktop nor AnkiDroid supports this currently, and I argue they shouldn't - it's really an export error (they shouldn't have exported it with scheduling information if they were going to share it). The solution since you are already exporting and importing decks is to re-export it but this time without scheduling information, delete it from your collection, then import the clean export.

The second request, and the one we should implement in order to mirror Anki Desktop, is to reposition all cards into the new queue. You can do this with the instructions above on Anki Desktop (card browser, select the cards you want, edit -> reposition -> as new). You can do it on one card at a time in AnkiDroid in the options menu for each card. But you can't do it on all the cards selected at once in multi-select mode. Multi-select mode is only present in AnkiDroid 2.9 alphas right now and is a new feature so that is expected, but we can implement this now, we just need a PR that hooks the "reschedule" feature AnkiDroid already has into the options menu for Card Browser multi-select.

This would match Anki Desktop behavior so it should be acceptable to merge if anyone wants to implement it. 

It would be something very similar to this, but "rescheduleCards" instead of "checkDeck" - https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L311

And here is the reschedule cards implementation all ready to take an array of IDs from the multi-selection, but only takes one at the moment: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1023

Hooking these two things together would be a great addition and not too hard to do if anyone has time

**Comment by mikehardy** [comment]
This is not an actual implementation (yet) but it shows in the actual code where the various bits should go and how to hook them together: https://github.com/mikehardy/Anki-Android/commit/e6d5c14907ce39bff29b13e6df6a618f78d60ff0

**Comment by mikehardy** [comment]
I have it all working now in that branch above but need to polish up some localization issues. This should make it into 2.9 though

**Comment by mikehardy** [comment]
Implementation complete and pretty polished, it's already in the review/revise cycle. It'll be in 2.9

**Comment by mikehardy** [comment]
Follow instructions at the link below to tell google play you want betas and join the alpha google group and this will be present in 2.9alpha53 (the next alpha) and higher
https://docs.ankidroid.org/manual.html#betaTesting
