### ISSUE TITLE
Plugin architecture

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2982]
Originally reported on Google Code with ID 2085

```
By HTML transformation I mean processing a card just before displaying it.
For instance adding kanji information, or transforming a FEN code into a table representing
a chess board.

The goal is to:
- Reduce the size of the AnkiDroid APK.
- Allow third-party developers to implement more transformations.
- Separate the release cycles of AnkiDroid and transformations.
- Simplify preferences.

I am not sure what is the best way to implement this, but it sounds possible:
http://stackoverflow.com/questions/23002072/delegate-text-transformation-to-plugin-android-apps-not-known-in-advance

Do we need to send anything to the plugins besides the source HTML?
```

Reported by `nicolas.raoul` on 2014-04-17 09:26:22

**Comment by mikehardy** [comment]
@timrae  Check this out https://github.com/qwiglydee/anki-interactive

Shows the power of current web standards.

Here's what I'm thinking about plug-ins since I know we have a webview hook where the Java code and the WebView each hook each other. The linked project made me think the common denominator cross-platform is web standards (and here I'll focus on javascript) with Anki 2.1 exposing more java script hooks #4991 and plug-in authors maybe willing to maintain javascript + python as long cross-platform was possible, maybe the plugin architecture could be javascript and we expose hooks? At the minimum, any plugin that wanted to do something that was review specific should join forces with the project above

As it is, this could maybe nuke all of type answer, cloze, occlusion (in the future?), and multiple choice (since the preceding are already implemented), but also chess, latex, mathjax, whiteboard etc. And the core reviewing platform could rev independently of AnkDroid.

:thinking:

**Comment by sudomain** [comment]
Could javascript affect something like the tag list screen if, for instance someone wanted to implement something like hierarchal tagsaddon?

**Comment by mikehardy** [comment]
Currently no - javascript only executes in various "reviewer" modes (previewer, reviewer) and only interfaces with the Java object that handles reviewing. There's no execution of javascript between other objects or at other times

**Comment by sudomain** [comment]
I came across [this comment](https://github.com/ankidroid/Anki-Android/issues/4902#issuecomment-407783401) from Mike from a few years ago. Quoting the relevant section:
> I just had an idea though - if you could combine a Python execution environment with a separate app that used the AnkiDroid API, you could perhaps have cross-compatible Python scripts that loaded in your app, executed against the AnkiDroid database (to set scheduling information or similar) and handled your use case

That comment made me think of [Termux](https://github.com/termux) which has a [Python package](https://github.com/termux/termux-packages/blob/master/packages/python/build.sh) (3.8 at the time of this writing). I don't think it would be able to use the Instant-Add API as that would require modifying that project's build.gradle. Maybe there could be an app that interprets intents sent by Termux's `am` tool and performs an appropriate action via AnkiDroid's Instant-Add API?

**Comment by mikehardy** [comment]
For people willing to tinker I think it's possible to actually run anki desktop on android now? I know I saw someone post about it - @Anthropos888 sorry to just tag you in but did you set up a python environment in your android? I'm struggling to remember

**Comment by Anthropos888** [comment]
@mikehardy nope, that wasn't me, sorry :-)

**Comment by sudomain** [comment]
Hey [that was me!](https://github.com/ankidroid/Anki-Android/issues/2545#issuecomment-555752004)

**Comment by mikehardy** [comment]
Ah ha! Excellent :-). Except then my attempt to maybe cross-pollinate was ineffective as you won't learn anything new from being shown your own investigations ;-). What you indicate might work (Termux+Python -> intermediary that bridges Termux Intents to AnkiDroid API -> AnkiDroid) but I'm not sure how useful it would be. I may be wrong but I thought most of the really useful plugins everyone wants (scheduler tweaks, image occlusion) require hooks that alter data as it comes from libanki and before presentation, and the AnkiDroid API is more about CRUD (create read update delete) in conventional ways, no inner-working exposure happens.

**Comment by dae** [comment]
Closing this in favor of #7959
