### ISSUE TITLE
Integrate Github with Coverity

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3056]
Originally reported on Google Code with ID 2159

```
https://scan.coverity.com/github
```

Reported by `nicolas.raoul` on 2014-06-20 03:37:36

**Comment by mikehardy** [comment]
@timrae - I have a playground branch that integrates with http://codecov.io - but as with the other build / static-analysis / CI issues, I like the idea while at the same time I'm not sure how to make it an actionable part of the process, so I'm not sure if there is value.

**Comment by timrae** [comment]
It might be cool if we could see in a PR if the number of warnings increased or something like that... I'm not sure if there are any tools like that though

**Comment by mikehardy** [comment]
I think that's exactly what sonarcloud.io is for actually. Once integrated with CI I believe you can have github link the report and probably even show an indication based on rules (increased count etc). Sonarcloud integration at least is close then integrating it to PRs and commits would be after.

**Comment by mikehardy** [comment]
I think we've got codacy going enough with Codacy in #4914 to close this one
Once the PR is merged - since it includes a move of the checkstyle to the root - codacy should find it and apply our local checkstyle as well. I'm just working on stabilizing the coverage vs the flakiness of the emulators on Travis for CI now but I have a solution in hand
