### ISSUE TITLE
Option to remove border on sides of the screen

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3073]
Originally reported on Google Code with ID 2176
```
What steps will reproduce the problem?
1. Open any deck for review.
2. Look left and right.
3. You see wasted screen estate.

What is the expected output? What do you see instead?
I would like to use all of the available space for content, not for "decoration". This
is critical on devices with smaller screens. Not everybody carries 5" phones. Even
if you do, it would be nice to use all of it. This is especially critical in the use
case I describe below.

I use 
AnkiDroid v2.1.3 
on
Android 4.3 / 4.1.2 / 4.1.1 /2.3.6
(depending on the device I have closest to me).

I really like your app and use it frequently, but studying countries of the world always
angers me not to be able to use all of my screen, especially when I cannot find smaller
countries. I would be very happy to have such an option.
```

Reported by `MorgenTee` on 2014-07-05 14:58:11

**Comment by Glutanimate** [comment]
>And on how to actually use the full width:
use the card styling and CSS to set the margin (or left and right margins) to 0 and
image width to 100%

For some reason this doesn't seem to work for me. I've tried setting all types of margins, paddings, etc. to 0 and the dimensions to 100%, but my cards still have a small margin on all sides. Here's an excerpt of the styling I use:

```css
.body {
  position: absolute;
  margin: 0;
  padding: 0;
  top:0;
  bottom: 0;
  left: 0;
  right: 0;
  width: 100%;
  height: 100%;
}

.card {
  position: absolute;
  margin: 0;
  padding: 0;
  top:0;
  bottom: 0;
  left: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

I am using AnkiDroid 2.5alpha64 right now (latest release as of this post).

Here's what my cards look like on Ankidroid (notice the margin on the left and top):

![](https://i.imgur.com/jYn16GY.png)

The main reason I'd like to get rid of these margins is because I am planning on creating a Material Design inspired template with several layers. However, this will only look good if I can use the full display width.

**Comment by ospalh** [comment]
Could you please try [this](https://groups.google.com/forum/#!topic/anki-android/TjakbVGJLmk) method? (See also #3685).
That space between the screen border and the text is the margin in the HTML document of the card, and is different from the border between the card and the screen border of AnkiDroid ≤2.4. This margin was there on older AnkiDroids in addition to the old border.

Oh, and i still got the images that seem to have got lost on the Google Code → GitHub transfer of this issue:
![screenshot_2015-06-23-13-49-04](https://cloud.githubusercontent.com/assets/1690429/10203121/80080344-67b4-11e5-849f-8f9fb9930349.png)
![screenshot_2015-06-23-13-58-05](https://cloud.githubusercontent.com/assets/1690429/10203122/800b8406-67b4-11e5-8703-0d2ca753c3f0.png)

Please note that the beige area is wider in the bottom (2.5) image.

**Comment by Glutanimate** [comment]
Awesome, that solved it! Looks like I was missing this style, specifically:

```css
#content {margin: 0;}
```

Thanks a lot!
