### ISSUE TITLE
SD card changes in Android 4.4.2 make AnkiDroid inoperable

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3106]
Originally reported on Google Code with ID 2209

```
Here is a link with more details about the changes: http://www.androidcentral.com/kitkat-sdcard-changes

I've had a user report two Samsung devices that are now unable to use AnkiDroid after
they both got updated to Android 4.4.2:
Note 2 on 4.4.2, exFAT 64GB SD
Note 10 on 4.4.2, FAT 16GB SD

Also a couple screenshots that show what happens when downloading a collection or opening
an existing one.

I believe so far we have only tested 4.4.2 on Nexus devices which only have internal
storage so we never caught this.
```

Reported by `Houssam.Salem.Au` on 2014-07-24 11:59:33

<hr>
- _Attachment: [2.jpg](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2209/comment-0/2.jpg)_

**Comment by gbriel-almeida-santos** [comment]
hssm, I did what you said "/storage/NAME_SD/Android/data/com.ichi2.anki/AnkiDroid/". first it worked, but when I was syncing my collection another error appeared. Then I deleted my anki e reinstalled it, and now the path is not valid.

I tried the second method too, but didn't work.

My Android is 5.0.2. 
In my old smartphone with Android JellyBean, the change of path woks normally.

**Comment by mijascuric** [comment]
Hi, 

Currently my AnkiDroid collection and backup is stored on my device storage. I would like to move it to external SD card. 

I was looking at the directions above but I am not able to find apk "com.ichi2.anki-2.apk" or the package name is "com.ichi2.anki". 

The collection path on my phone is /sdcard/AnkiDroid. 

Can I just move all the subfolders from my device storage AnkiDroid folder  to newly created AnkiDroid folder in sdcard? 

My Adroid version is 5.0 on  Samsung Galaxy Active. 

Thanks,

**Comment by timrae** [comment]
Sorry we can't provide support on this issue, and we strongly recommend *not* to use external SD card. If you choose to ignore our advice then you're basically on your own, though you can probably find help on sites like forum.xda-developers.com and android.stackexchange.com

**Comment by LucasCoder** [comment]
What a bunch of lazy devs to not support such a basic feature.

**Comment by wareya** [comment]
Just for reference, when I add an SD card, my device treats the SD card as internal storage and the internal storage as an SD card. I don't think SD cards can officially be formatted with anything that supports more characters than UCS-2, so this actually made it so that I couldn't use (without modification) a deck that had media filenames with characters in supplemental planes (i.e. extended kangxi radicals).

**Comment by weakedsick03** [comment]
the one for sony xperia worked for me. Thank you very much

> On a Sony Xperia Z1 manually creating the folder on the external sd-card didn't work.
You have to rename the folder on the internal storage (presumably AnkiDroid) to match
Ankidroid's package name: com.ichi2.anki and move the folder to the external sd-card
using File Commander (Default system app on Sony devices with root permissions). Afterwards
change the storage path in the settings to /storage/sdcard1/Android/data/com.ichi2.anki

>Reported by chris.yereaztian on 2014-12-28 13:53:41

**Comment by gadamiak** [comment]
A workaround with creating a `com.ichi2.anki` folder worked for me on Android 6. My path is `/storage/<XXXX-XXXX>/Android/data/com.ichi2.anki/AnkiDroid/`.

Anyway, ability to store app data on external SD card is quite a standard feature and lack of it may be a showstopper for using the app. One big deck will fill up whole left space on most 8GB devices forcing users to uninstall other applications. It should definitely be possible to select external storage for data.

**Comment by tf0054** [comment]
Using android 7.0 on Galaxsy S7, we could change the storage to "External storage" via Settings/Applications. After this change, I guess we could set the AnkiDroid directory to /storage/<XXXX-XXXX>/Android/data/com.ichi2.anki/AnkiDroid/

**Comment by sudomain** [comment]
I realize this is an old and closed issue, but I'm hoping to gain understanding why SD cards are not supported. Please don't interpret this comment the wrong way: I'm positive the devs have good reason to not support the feature, I just wish to know why.

A few possible reasons that I'm not sure of because I don't have a lot of Android dev experience:
1. Maybe there isn't a reliable way to use SD card storage across the different device manufacturers and Android versions? It seems storage is changing again with #5304 
2. The  `collection.anki2` file is a Sqlite database that seems to get written to every time the app is opened. SD cards [typically have fewer write cycles than the technology typically used  for internal flash](https://stackoverflow.com/questions/13159494/should-i-be-concerned-with-flash-memory-write-cycles-resource-limits)

Can one of the devs please confirm or provide insight why I'm wrong?

**Comment by mikehardy** [comment]
Your point 1 is correct in that external storage in general is really hard to work with across the android API skew (more than vendor skew), and with the move to scoped storage, there is just not really time for us to handle the support load that comes in with custom paths and custom external storage setups. Go ahead and do it, you're just on you're own...

Point 2 is not something I think we cared about much. It was purely that the support load was really high and soaked up scarce developer time for a real niche audience that has only grown smaller as more phones don't even support external cards at all now and more phones have enough space now it is not as pressing.

I'm always keen to mention that I live in a country where most people actually *do* have space constraints so it would be great to have easier support for it, but then as a contributor I can only say that the experience in the project was such that it ate up too much time with regard to support to continue it

**Comment by david-allison-1** [comment]
They were unsupported before I joined. I'm willing to question the status-quo and state that I don't know, but I don't have the time to take this on. Unsupported also means "they work if you change the path, but we don't provide support for issues".

You can probably find some history from older threads about this.


Point 3: Having an SD card allows the user to eject the card whilst the application is running, this can lead to (unavoidable) issues.

Point 4: SD cards can be badly formatted (FAT32 for example) and AnkiDroid users can have more than 65,534 files in their `collection.media`. This could easily be the cause of why a few of the AnKing decks don't work on AnkiDroid (they give a badly formatted unicode error which I haven't been able to reproduce)

AnkiDroid handles the Android lifecycle fairly badly here (we have the Android lifecycle PLUS `onCollectionLoaded` handling PLUS SD Card ejection detection), which is done in a nonstandard per-activity basis. 

If I were to fix/improve things, I'd want to use it as an excuse to tackle the lifecycle issues, which is a very big job in itself

**Comment by sudomain** [comment]
Thank for the detailed replies. Some of this comment could be in my feature request(#9532 ) but is here because it ties with this discussion too.

> I'm always keen to mention that I live in a country where most people actually do have space constraints...

I'm in an US metropolitan area and I'm (very) fortunate enough to be able to afford a device with storage that is "the next size up" from my current device. At the same time, I'm willing to pay a bounty for the SD feature equivalent to the price of this new device ($30 USD). This would be my first feature bounty offered, so I apologize if that amount is paltry.

> Go ahead and do it, you're just on you're own...

To be clear- if I manage to implement it myself or pay someone else to, do you wish for a PR? Or shall I keep it in a fork? Like you said it would be another thing to maintain, even after initial implementation. At the same time, the number of people that would benefit decreases as phones with larger capacities become cheaper. Also, (IIRC) There used to be hesitation to adding more settings to the app.

> Point 3: Having an SD card allows the user to eject the card whilst the application is running, this can lead to (unavoidable) issues.

Good point. However, if users are technically savvy enough to go into Advanced settings and change a path to somewhere on their SD card, I'd hope they be able to realise removing it causes their media to disappear :).

> Point 4: SD cards can be badly formatted (FAT32 + AnkiDroid users can have more than 65,534 files in their collection.media). This could easily be the cause of why a few of the AnKing decks don't work on AnkiDroid (they give a badly formatted unicode error which I haven't been able to reproduce)

Referring to #8148 ? I think 99℅ of my collection.media comes from two AnKing mega decks- `AnKing` and `AnKing MCAT` and I've got ~36,000 files: (please ignore my use of `ls` in a pipe :)

   $ ls /storage/A313-660E/Android/data/com.ichi2.anki/collection/collection.media | wc
    36263   81252 1113904

**Comment by david-allison-1** [comment]
Yep - there's a hard limit of 65k files per directory in FAT32, which is a more pressing issue than the #8148 issue (which I can't reproduce on my Android).

**Comment by mikehardy** [comment]
Still, with regard to filesystem formats, that's probably something we can detect, looked at as an engineering problem. Similar to our "we can't expand this zip file because there's no space" check. We can check for files vs formats and do something. Anyway, I'm totally fine maintaining it as an option (that is: supported in code) I would just continue it's "go ahead and use the feature but please don't ask for support" status. People losing collections is a tragedy, and being very very explicit that it can happen and we will probably not be able to help is the right expectation to set.

**Comment by Fabiensk** [comment]
> A workaround with creating a `com.ichi2.anki` folder worked for me on Android 6. My path is `/storage/<XXXX-XXXX>/Android/data/com.ichi2.anki/AnkiDroid/`.

I have a old Galaxy S5 mini (Android 6.0.1) which becomes very slow if I don't add a SD-card (because of lack of internal storage). Using the tip above was the only way I could store my Anki files on the SD-card. I use this old phone as a Anki-phone (it's small enough so I can hold it and anki while running).
