### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException: magnitude == null

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3126]
Originally reported on Google Code with ID 2229

```
Media syncing bug in 2.2.3

Triage link:
http://ankidroid-triage.appspot.com/view_crash?crash_id=5268036193878016
```

Reported by `Houssam.Salem.Au` on 2014-08-07 15:02:52

**Comment by ryantimjohn** [comment]
AnkiDroid Version = 2.6.1

Android Version = 6.0.1

ACRA UUID = ea490a9a-198c-47d1-b116-8b8e0c7bed5f

**Comment by timrae** [comment]
I don't think we have any stack traces from that long ago, we periodically remove them to conserve server resources. You should have access to check yourself though!

**Comment by mikehardy** [comment]
Then I think this should be closed for lack of info, I'm unable to find the string 'magnitude' anywhere in the codebase

```

mike@Ibiza:~/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/java (master) % grep -ri magnitude *
mike@Ibiza:~/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/java (master) % 
```

**Comment by JakobEichler** [comment]
I still have this error, and sometimes IOExceptions also. 
The magnitude==null error occurs always when leaving anki open. 

The IOException, when minimizing AnkiDroid.

With the computer everythinng works fine. 

I have a very huge database 3-5GB.

Because the sync was completed and some media files where missing, I fully removed AnkiDroid and reinstalled:
AnkiDroid 2.9alpha22

The store from Google Play had the same errors. And I think on the Google Play might even have been worse (with regards to the synchronization appart from it, it is amazing : ) 

![screenshot_20180626-092020](https://user-images.githubusercontent.com/33957025/41895807-4978b4bc-7923-11e8-973c-72a99598ec00.png)

**Comment by JakobEichler** [comment]
![screenshot_20180626-092945](https://user-images.githubusercontent.com/33957025/41895996-c6549a96-7923-11e8-9022-d38ccc1ab73d.png)

**Comment by mikehardy** [comment]
I found the stack trace, for what it's worth. It's the same as #3726 

Something happens while downloading media where file permissions have problems:

06-14 12:10:37.166 E/AnkiDroid(24255): java.io.FileNotFoundException: /sdcard/AnkiDroid/collection.media/1cf039a5aba03a91ebc6a4b21d867e3c.mp3 (Permission denied)
--


...and/or file sizes can't be read (leading to magnitude == null)

separate stack traces, but both in this area 

at com.ichi2.libanki.Media.addFilesFromZip(Media.java:896)
at com.ichi2.libanki.sync.MediaSyncer._downloadFiles(MediaSyncer.java:241)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:167)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:188)
at com.ichi2.async.Connection.doInBackground(Connection.java:178)
at com.ichi2.async.Connection.doInBackground(Connection.java:50)
