### ISSUE TITLE
Customize which icons are visible in the reviewer action bar

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3154]
Originally reported on Google Code with ID 2257
```
> Please explain your idea here.
Have buttons whose actions is configured by the user.
Currently this is available for gestures, 
but gestures are not available when using the whiteboard.

One Use case that needs this:
Draw CJK characters with cards that do not fit the screen, as it is the case with cards
that include enough info.
Whiteboard needs to be switched on and off frequently to scroll the cards; for instance
to look at a stroke order diagram or or to look at kanji composites. The button present
in 2.2 has been removed in 2.3 and this has made reviews extremely painful.

see discussion in 
https://groups.google.com/forum/#!topic/anki-android/kCVim4Oq1bk


> Is this feature available on similar apps 
Available for Ankidroid's gestures though the actions currently do not include switching
the whiteboard on and off.

One way to implement this would be dedicated bar, with 4-5 buttons.
It's important that the buttons be always visible and actionable as any additional
click when multiplied by hundreds of reviews becomes a problem


```

Reported by `enrico200165` on 2014-08-28 05:21:38

**Comment by timrae** [comment]
For the benefit of anyone planning to work on this:

The way I envisage the feature working is we have a list of all the available actions, and users can choose between (separately for each action):

Always show / Show when room / Never show / Disabled

Where Disabled means that it's hidden even from the overflow menu. This last option would allow us to add "Add note" to this menu without cluttering it up for the majority of users that don't need it.

**Comment by arooooon** [comment]
This is a great feature. Personally I don't like gestures so much but I bury and suspend a lot of notes. Is anyone working on this because I could definitely work on this.

You should be able to remove any button as well as deck name and time left. This would not be according to the design guidelines I think, but if the default settings follow those guidelines I don't see any problem. These are settings for advanced users.

Actions to choose from? I think all of them:
Bury and suspend note/card
Add card
Edit
Replay
Etc...

But also to toggle specific tags. This could allow a user to easily one-click tag his collection while reviewing.

Optimally you would have an action bar just like in the reviewer to preview instantly when you are customizing these buttons.

Which icons could we use for all these actions?

**Comment by timrae** [comment]
I don't think anyone is working on it, and I would be very happy to get a pull request!

How about maybe start off by including all of the actions in the reviewer menu xml file, allowing each of them to be set in the three states I mentioned earlier in this thread. We can then discuss adding extra actions and hiding other stuff in a separate PR.

**Comment by arooooon** [comment]
Ok so I have begun to look into this and there is this problem where items in a submenu (Hide / Delete) won't support showAsAction="ifRoom". They are stuck in the menu. Neither can I find I way to see what items are placed in the actionbar and what are placed in the menu, because that could have been usefull for a work around.

Anyway, for me it is acceptable if the items in Hide / Delete only support the other three options. Though we could of course write our own way of dealing with which icons should be in the actionbar versus in the menu, but I don't think it is worth it.

Also, I noticed that the actionbar/overflow is not updated when rotating the device.

**Comment by timrae** [comment]
Maybe implementing the submenu as an action provider would work...? I'm
sure we can figure something out, just send a PR (even if incomplete) and
we can discuss specifics.
