### ISSUE TITLE
Crash when logging out from Anki Web

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3315]
Originally reported on Google Code with ID 2419

```
From looking at the crash report you can probably reproduce by manually deleting the
media database and logging out, though I'm not sure if this is the root cause of the
problem:

http://ankidroid-triage.appspot.com/view_crash?crash_id=4716422403981312
```

Reported by `perceptualchaos2` on 2014-11-26 03:37:43

**Comment by mikehardy** [comment]
Yep - not sure who would just delete the a database and expect the app to work, but I can still reproduce this 3 years later!

09-16 22:29:03.475 1699-1810/system_process I/WindowManager: Destroying surface Surface(name=com.ichi2.anki/com.ichi2.anki.Preferences) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3017 com.android.server.wm.WindowManagerService.relayoutWindow:2897 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 
09-16 22:29:04.249 5767-5767/com.ichi2.anki E/SQLiteLog: (1802) statement aborts at 5: [delete from media] disk I/O error
09-16 22:29:04.250 5767-5767/com.ichi2.anki D/AndroidRuntime: Shutting down VM
09-16 22:29:04.256 1699-2172/system_process W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) } U=0: not found
09-16 22:29:04.261 5767-5767/com.ichi2.anki I/ACRA: ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception on to default ExceptionHandler
09-16 22:29:04.261 5767-5767/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 5767
    android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
        at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:779)
        at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
        at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
        at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1910)
        at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1851)
        at com.ichi2.libanki.DB.execute(DB.java:282)
        at com.ichi2.libanki.DB.execute(DB.java:268)
        at com.ichi2.libanki.Media.forceResync(Media.java:771)
        at com.ichi2.anki.MyAccount.logout(MyAccount.java:154)
        at com.ichi2.anki.MyAccount.access$200(MyAccount.java:41)
        at com.ichi2.anki.MyAccount$4.onClick(MyAccount.java:206)

**Comment by mikehardy** [comment]
I checked, and after delete media database, logout, crash, restart, logging in again, all media was downloaded and the db was recreated, and review showed the images correctly, whereas if you don't set the media database up for resync it will never sync correctly.

A normal deauth/re-auth does not re-download anything, so takes a lot of bandwidth for big collections but it self-healed. Perhaps the fix here since the crash is rare, is to catch any database exceptions on logout, delete the database (if it exists) to make sure it will self-heal, and pop a dialog explaining the problem and that all media will re-download if they log in again.

https://github.com/mikehardy/Anki-Android/blob/hotfix-2.8.5/AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java#L154

I think we have all the utilities (dialog stuff, that is) to do that relatively painlessly?

**Comment by dae** [comment]
Obsoleted by the backend switchover.
