### ISSUE TITLE
move the media library into an sqlite database

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3336]
Originally reported on Google Code with ID 2440

```
This is more of a question than a concrete suggestion.

In my Ankidroid installation i have 27000+ tiny files of sounds and images. Simply
copying onto the device already takes forever, but a bigger issue is that this also
impacts the device performance overall, since every android devices do not work very
well with directories that contain a lot of files. Any app that tries to touch the
ankidroid directory takes forever since it seems none of them are written in a manner
that they can deal well with giant directories, on top of the general slowness of the
android file system.

The one way i can think of resolving this would be to have ankidroid keep an sqlite
database of all the media files, instead of storing them straight on the hdd.

Would this be feasible at all?
```

Reported by `walde.christian` on 2014-12-15 03:52:38

**Comment by jytou** [comment]
I must admit I'm really a big fan of this idea. There are several problems when you have large decks in your collection, especially on Android:
-folders with 10k+ media files are a real nightmare with the media scanner screwing up the device,
-restrictions on folder sizes for FAT make it impossible to store all media on some devices,
-folders with 10k+ files in general are a pain on any system, even the best ones.
I have almost 50k files in my media collection, and that's a huge problem. I'm thinking of externalizing these to a web site and referencing them as external resources rather than having them stored on each device where I want to study. That implies having a good connection around, but I don't mind that (that's a personal preference/choice). Having these media stored in a database would make much more sense than in the filesystem, especially in a unique folder.
Any hint on the class to extend if I was going to write a python plugin to "redirect" every media request to a website rather than the local folder?

**Comment by timrae** [comment]
Couldn't you just write a script to convert all your media references to urls?

**Comment by timrae** [comment]
The standard regex search and replace feature may even be enough for you... If not, you may find some inspiration from [this plugin](https://github.com/timrae/anki-replaceall) I wrote ages ago that does a kind of custom search & replace across different fields.

**Comment by jytou** [comment]
> Couldn't you just write a script to convert all your media references to urls?

That's exactly what I plan to do. But in the meantime I'll also split every collection into separate folders on the web server. I'm definitely not a big fan of large directories as it bit me quite a number of times (regardless of the filesystem/OS). Thanks for the regexp plugin, can give me some inspiration (I'm in the process of writing a plugin - haven't done some Qt in ages, and python is not my main programming language, but it's going forward). Is there any pydoc of the Anki classes (Note, DeckManager, etc.)?

**Comment by timrae** [comment]
Not really but there's some database doc on our wiki

**Comment by jytou** [comment]
For the DB, I use sqlite, that covers it pretty much. :) I guess I'll manage, along with some dir commands to expose methods/attributes. Thanks for the tip, though.

**Comment by timrae** [comment]
I meant doc for the collection.anki2 database. In the plugin I linked to I
just operated directly on that without using the libanki classes

**Comment by jytou** [comment]
Right. I guess I should go that path too, otherwise, performance is going to be a mess... :D

**Comment by mikehardy** [comment]
@timrae this is maybe similar to #3282 in that I don't think ext4 suffers from any performance problems with large directories? but maybe that's a naive stance

**Comment by mikehardy** [comment]
I don't think this is nearly as much of an issue on newer systems (with modern filesystems - though I understand that's not everyone) but I wanted to note that I've seen terrible performance on media deletion. May be a separate issue but imagine 10,000 orphaned media files during media check for instance, that seemed to be slower than it should have been by a wide margin
