### ISSUE TITLE
Issue on AnkiDroid without SD Card

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3424]
Originally reported on Google Code with ID 2528
```
What steps will reproduce the problem?
1. Install latest AnkiDroid build on a emulator or device without SD card (ex. Nexus
5/7 Emulator)
2. Unable to access Anki data directory

What is the expected output? What do you see instead?
Anki should find the proper directory. It says (on my actual device) /sdcard/AnkiDroid
when it should be /storage/emulated/0/AnkiDroid. I believe it is possible that some
changes have made Android return the wrong directory, possibly you need to test if
there is an actual storage directory.


Does it happen again every time you repeat the steps above? Or did it
happen only one time?

It was fixed by manually entering the path.
```

Reported by `tomac120` on 2015-02-16 15:08:58

**Comment by barrynauta** [comment]
Well... there is a small issue here.
I have a "One plus One (OPO)" device myself, a device without an SD card. I created a small test deck and exported it, but when I search for the collections.apkg file on my device afterwards, I cannot find it. It exists, since I can mail it. 

Anki asks for the following location when importing: "/sdcard/AnkiDroid", this directory does not exist on my device. When I create it, it is not recognise as such (probably related to some sort of hidden root folder structure?)

When I create a deck using the windows app and mail the file to my phone and open it via Anki, I am  able to open it (so there is a workaround!) 
For information: Anki asks me in this case if I want to replace the file '/data/data/com.ichi2.anki/cache/collections.apkg' a directory that I cannot find on my phone either...

Anyway, I am able to use the work-around and use Anki on my phone, thanks for this fantastic product!!!

**Comment by timrae** [comment]
There should be a folder in the root directory of your device called AnkiDroid. Try using ES file explorer if you can't see it. Essentially all Android devices have an internal sdcard, which is what's being referred to here.
