### ISSUE TITLE
Menu item to edit tags directly from the reviewer

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3566]
Originally reported on Google Code with ID 2694

```
Please explain your idea here.

in the Hanping Dictionary, the mark star has a dual function: press for mark, long
press for tagging. that would be nice for AnkiDroid too. I have some long notes, and
have to do two button presses plus a scroll down now to access the tags.


Is this feature available on similar apps (Anki Desktop, AnkiMobile,
AnyMemo, etc) ? If yes, it could help to include a screenshot or link to a
page explaining the feature.

```

Reported by `sarefo` on 2015-07-17 00:40:21

**Comment by marcardar** [comment]
Hanping developer here. I've never found a particularly good solution to this. In Hanping, the Star icon is in a toolbar (not action bar) at the bottom of the screen. Regardless, long-press should really show a label rather than provide other functionality. However, I've found it pretty invaluable to go against the rules here for not only the Star icon but also the other toolbar icons.

The other approach I thought of was for some kind of attached popup to show as soon as your finger touches the button - so that you can then drag up to whatever tag and then release.

**Comment by Glutanimate** [comment]
Would love to see this implemented! I often find myself trying to update tags via the reviewer and it's always a frustrating experience since you have to go through about eight steps and three different menus to complete the procedure. Quick access to the tag entry, be it via a long press gesture or a simple entry in the reviewer's menu, would be a marvelous thing to have.

**Comment by timrae** [comment]
I'd be in favor of adding an option to include a menu entry for editing tags which is disabled by default, and can be enabled or disabled in preferences with the other reviewer menu items. Please feel free to submit a pull request.

**Comment by david-allison-1** [comment]
Let's give this another round - I think it'll be useful

**Comment by tobrie** [comment]
Attempted to solve this. Feel free to criticize. I've decided against using "tip and hold", because that's not obvious enough in my opinion. If you want an ActionButton for tags you can now adjust the settings under "Review".
