### ISSUE TITLE
Android System WebView update stops our custom fonts from being loaded from the SD card

### ISSUE THREAD

**Issue by curiousdannii** [ankidroid/Anki-Android#3581]
Android version: 5.0.2
Anki-Droid version: 2.4.3
Android System WebView version: 44.0.2403.90

Updating to the new WebView stops our custom fonts from being loaded from the SD card, and Anki goes back to using Android's default (or the WebView's default I guess.) Uninstalling the WebView update will allow custom fonts to work again.

**Comment by timrae** [comment]
Which font is that? Try using one of the Google Noto fonts.

**Comment by curiousdannii** [comment]
I'm using Cardo. But changing fonts is not a fix for this bug. I also doubt it would work. If it won't load one custom font, why would it load another?

**Comment by timrae** [comment]
Just because it stopped working for your font why would it stop working for
all fonts? :-p

**Comment by curiousdannii** [comment]
I have tried several fonts. None are loaded. Please treat your bug reporters with respect.

**Comment by ospalh** [comment]
That is odd.
This is a card that i use and it shows (at least) 6 non-standard fonts.
![six fonts](https://cloud.githubusercontent.com/assets/1690429/9002994/461d6d42-376a-11e5-8e55-42a6f5fb2df0.png)

Maybe all of your fonts are old?
Please check [this thread](https://groups.google.com/forum/#!searchin/anki-android/epson/anki-android/svgWDMukz1s/qwx6VI30eioJ), maybe try [my steps](https://groups.google.com/d/msg/anki-android/svgWDMukz1s/XQFk0057AFcJ)

**Comment by curiousdannii** [comment]
@ospalh I have "default font applicability" set to "always", which I guess you must not for that to be possible. So maybe it's only a problem with that setting.

**Comment by ospalh** [comment]
You have set it up to always use one font, and then wonder that now other font gets used‽

**Comment by curiousdannii** [comment]
@ospalh No of course not. It was working perfectly, until I installed the WebView update. If I uninstall the update the custom font starts working again. I don't know how the override setting works, but I guess however it works is broken by the WebView update!

**Comment by flerda** [comment]
I think Dannill's use case make perfect sense: if you set the font as the default for the entire card (by placing it in the fonts directory and configuring it in the settings), it should be used to render the card's content.

I will have a look to see if there is a workaround. In the past we have seen that some fonts stopped working on upgrades because the font format was no longer supported, or it was actually an invalid font that the system was working around but stopped doing so.

**Comment by flerda** [comment]
I checked with OpenSans-Italic (which is shipped with AnkiDroid) and that one seems to work correctly (I get an italic font used).

I downloaded the font from http://www.fontsquirrel.com/fonts/Cardo (not sure if that's the one you are using) and that one also seems to work for me (I compared the fonts and can see the difference in letters like s).

I have the same version of WebView and AnkiDroid but a different OS version (5.1.1).

**Comment by ospalh** [comment]
> I downloaded the font from http://www.fontsquirrel.com/fonts/Cardo (…) and that one also seems to work for me

dto.

![cardo](https://cloud.githubusercontent.com/assets/1690429/9007999/18182450-3797-11e5-9acb-8874310e6ee3.png)

This is using the default font mechanism:
![liar](https://cloud.githubusercontent.com/assets/1690429/9008044/91f671a0-3797-11e5-8137-5900a0380f49.png)

Maybe you should complain about the extra web view package you are talking about. Why and where did you get that?

**Comment by ospalh** [comment]
I even installed tha extra Webview. I still see the font.
Btw, looking at the font: De gustibus non est disputandum.

**Comment by curiousdannii** [comment]
Wow, there's a fair amount of hostility here. I know that confirming bugs can be difficult, and I'm willing to do what I can to help. But don't tell me to leave because you don't even know what the WebView is for @ospalh.

**Comment by curiousdannii** [comment]
@Flerda I've just tried some of the OpenSans fonts, and the italics is recognised, but not the font weight. ('light' actually displays heavier than 'bold'!)

I've been using the version of Cardo from the official site: http://scholarsfonts.net/cardofnt.html
Cardo104s.ttf

I get the impression that the sd card method is no longer recommended. I can try adding the font as a deck media item later, but I can't right at the moment. Even so, the docs say it's still supported.

**Comment by ospalh** [comment]
Hostility? Not up to now.

I

* Demonstrated that custom fonts in general work and pointed you to a solution to problems with *some* fonts.
* Hunted for a font.
* Installed that, modified my decks, played around with the settings on AnkiDroid and posted a few screen shots.
* Hunted for a package and installed that. (Maybe i would have done that some time soon. Anyway.)

Yeah, maybe some comments were a bit snarky. Sorry.

And i tried the “sd card” method, my second “Xylophonmusik” screen shot, and the media folder method (where the files are stored on the same sd card as with the sd card method), the first “Xylophonmusik” screen shot. They all work for me.

(And i still see that the spacing in that font is terribly off. On Linux and Android more so than on Windows.)

**Comment by curiousdannii** [comment]
@ospalh I was annoyed because I didn't think timrae was treating my bug report seriously either (suggesting I just use another font.) Thanks for apologising.

When I get back from a trip I'm on I will try the media folder way and report back if it works any better.

This seems very strange to me because it is clearly the combination of Anki and the update to WebView that is doing it, and yet when you guys have installed the update it still works.

**Comment by timrae** [comment]
> I was annoyed because I didn't think timrae was treating my bug report seriously either (suggesting I just use another font.)

I meant that I wanted you to try Google Noto and see if it works so that we can eliminate your font being the problem. Reading my post again that's not really clear, sorry about that. 

I'm really busy at the moment, and we get hundreds of posts a year about custom fonts which inevitably turn out to be an error with the font or an error on the user's part... You'll likely find a warmer response from developers of open source projects (i.e. volunteers) if you don't immediately assume that the program is at fault and try to show more effort in debugging the problem yourself if you do file a bug report.

**Comment by chiizujin** [comment]
I am also experiencing this problem and can confirm that it is a WebView issue when using unicode fonts.

Here's some background.

It's a known problem that the default Android fonts on non-Japanese devices display Chinese versions of characters instead of Japanese versions. In most cases this doesn't matter, but there are a few cases where the Chinese and Japanese characters differ. See http://forum.xda-developers.com/google-nexus-5/themes-apps/font-japanese-unicode-fallback-han-t2777478 for some examples. The "before" images are Chinese characters and the "after" images are Japanese characters. The differences may not seem great, but when you're learning these characters it's incredibly important.

I use a custom Japanese font in AnkiDroid, NotoSansCJKjp-Regular (https://www.google.com/get/noto/help/cjk/) which displays the correct Japanese versions. This has been working correctly until recently. I say "recently" because unless one of the incorrect characters comes up (and you know that it's incorrect) it's not noticable.

Up to the point of noticing the problem, everything had been working fine. No configuration changes had been made in AnkiDroid until I noticed that the correct font was no longer being used. After finding this thread and uninstalling the Android System WebView updates, the correct Japanese characters are being displayed again.

However, other non-Japanese custom fonts do seem to work (I tried DroidSerif-BoldItalic and got a bold italic font though of course the characters are wrong for Japanese). I looked up the "Cardo" font mentioned by curiousdannii and it's described as a "large Unicode font" which bears similarities to my situation.

This indicates to me that the problem is with WebView and fonts that go beyond the ANSI character set, so you will only be able to reproduce the problem by using such a font. To aid in your testing, this character (画) should look as it does in the "after" image on the link above, not the "before" image when using NotoSansCJKjp-Regular.

Since this looks to be a WebView problem, I'm not sure if you will be able to resolve this in AnkiDroid unless, as you say, you can find some workaround.

Anyway, here's a summary of my situation:

- The font NotoSansCJKjp-Regular (as well as several other Japanese fonts, both TTF and OTF) is not being used in AnkiDroid with WebView 44.0.2403.117.
- Uninstalling the WebView updates, reverting to version 37 (1726107-arm64), causes the font to be used fine again.
- This only occurs in WebView (i.e. during testing). The card browser always uses the specified font.

**Comment by timrae** [comment]
How about [`NotoSansJP-Regular.otf`](https://github.com/googlei18n/noto-cjk/raw/master/NotoSansJP-Regular.otf)?

**Comment by chiizujin** [comment]
That has the same problem - only correct with the version 37 WebView.

**Comment by timrae** [comment]
If you know some html, could you test whether the same fonts are working in Chrome for Android browser?

**Comment by chiizujin** [comment]
Yes, that does appear to work correctly with the latest WebView:

![1](https://cloud.githubusercontent.com/assets/1300745/9299875/b67992a4-4503-11e5-82a9-84e952b82a3d.jpg)

![2](https://cloud.githubusercontent.com/assets/1300745/9299882/c33e0ed4-4503-11e5-8c54-a088b15e4321.jpg)

```html
<style type="text/css">
  @font-face { 
    font-family: 'DejaVuSansMono';
    src: url('/sdcard/Documents/DejaVuSansMono-Bold.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }
  @font-face { 
    font-family: 'NotoSansJP';
    src: url('/sdcard/Documents/NotoSansJP-Regular.otf') format('opentype');
    font-weight: normal;
    font-style: normal;
  }
</style>

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
    <p style="font-family: DejaVuSansMono">Font load test</p>
    <p style="font-family: DejaVuSansMono">Incorrect test: 画</p>
    <p style="font-family: NotoSansJP">Correct test: 画</p>
  </body>
</html>
```

**Comment by Steven-Hou** [comment]
Is there anyone who can help me with the web view problem? 

I can not open a html hyperlink from the SD card in the AnkiDroid (Android version) 

The codes are as follows:

![image](https://cloud.githubusercontent.com/assets/13896742/9400628/49c8b1d0-47f6-11e5-8b2b-39012062ef17.png)


However, I can open a hyperlink like this using the web browser!
![image](https://cloud.githubusercontent.com/assets/13896742/9400650/6ca997fa-47f6-11e5-85d7-3f1f2d61ef76.png)

I just wonder whether there is something wrong in my code or is this a bug?
Could you tell me how to open a web (html) from the SD card?

Thank you very much!!

**Comment by chiizujin** [comment]
This issue isn't related to your problem (this is about custom fonts), however I can see a couple of things that may be the problem in your link:

- There's a trailing / in your link. It should be new3.html not new3.html/
- You may need to have the root location as /sdcard so it starts with file:///sdcard/

**Comment by Steven-Hou** [comment]
chiizujin, thank you so much! You answer has been very helpful!!![image](https://cloud.githubusercontent.com/assets/13896742/9401807/9e85b0c2-4807-11e5-97a3-6baee28f85f2.png)

**Comment by timrae** [comment]
I finally got around to looking into this, and it was indeed an AnkiDroid problem. Thanks @chiizujin for reproducing it.

The crucial piece of information from @curiousdannii that I guess @ospalh @flerda might have missed in their testing(??) was:

> I have "default font applicability" set to "always", [...]  maybe it's only a problem with that setting.

Indeed, it was just a problem with that setting. The [official method](https://ankidroid.org/docs/manual.html#customFonts) never stopped working.

**Comment by curiousdannii** [comment]
@timrae Thanks!

I guess I'll look into the other method...

**Comment by chiizujin** [comment]
Thanks for your work on this.

I wasn't actually aware there was another method. I guess the unofficial method seemed simpler at the time when I first looked into it then I forgot about the official one.

I think I'll stick with the unofficial method and use the older Webview (which is now newer after a recent system update but still works with the fonts) until this fix is pushed out.

At least I now know there another method if I run into problems.

**Comment by timrae** [comment]
OK I'll release a new alpha in the next few days with the fix, but the
unofficial method is less reliable and less portable, so I'd recommend
setting your cards up properly with Anki Desktop in any case.

**Comment by chiizujin** [comment]
I've taken your advice and added fonts to the cards which I can confirm does work correctly with the latest Webview.
