### ISSUE TITLE
Icon is too old-fashioned

### ISSUE THREAD

**Issue by Huguet57** [ankidroid/Anki-Android#3660]
I think a new fresh look would give Anki a wider range of users and take the user experience a bit further to the next level. I have here a few alternatives that I hope you all like.

![anki_icon_1](https://cloud.githubusercontent.com/assets/6130834/9947599/8f982000-5d9b-11e5-9975-e000059cb866.png)
![anki_icon_2](https://cloud.githubusercontent.com/assets/6130834/9947600/8fbc6d5c-5d9b-11e5-8f50-20151c027413.png)
![ankidoid_icon_1](https://cloud.githubusercontent.com/assets/6130834/9947601/8fe3a0ac-5d9b-11e5-9bbc-f0f1e95520f5.png)
![ankidoid_icon_2](https://cloud.githubusercontent.com/assets/6130834/9947602/8fe3dda6-5d9b-11e5-8cfa-7f675970a355.png)

I used a font called RussianQuality, the creator Samuel Park says in his README: "Feel free to use them in personal, non-money-making and fun stuff", I guess we fit in that description, if we don't please let me know.

**Comment by ospalh** [comment]
* As this says "Anki" rather than "AnkiDroid, you could try the [Anki](https://anki.tenderapp.com/discussions) support site
* Both projects, Anki and AnkiDroid are neither "personal" nor "fun stuff". While Anki desktop and AnkiDroid are free/libre, i am not sure that that can be called "non-commercial".
* I do not agree that the current icon is "too old-fashioned"
* Your icon doesn't look so much like Anki/AnkiDroid but more like "[Captain America](https://www.google.de/search?hl=de&q=captain+america%27s+shield&ie=utf-8&tbm=isch&gws_rd=cr) fights for [Ukraine](https://www.google.de/search?hl=de&q=flag+of+ukraine&ie=utf-8&tbm=isch&gws_rd=cr)".
* AND IT IS SHOUTING AT THE USER
* The app name "AnkiDroid" uses upper and lower case letters. The lower case letters of RussianQuality are ugly.

(This reply is my personal opinion, not the official position of the project.)

**Comment by snowtimeglass** [comment]
>I do not agree that the current icon is "too old-fashioned"
Neither do I.

>Your icon doesn't look so much like Anki/AnkiDroid
I agree with you.

**Comment by hssm** [comment]
I'm also against it. The icon is too different and loses all brand recognition. There has been [at least one other attempt](https://anki.tenderapp.com/discussions/ankidesktop/6139-possible-new-anki-logo) at a new Anki logo that also was not received well. I don't think the community feels the need to change the icon.

An update to the existing logo/icon might be received favourably if done well, but an outright change is probably not.

(It also looks like a [Star Coin](http://vignette4.wikia.nocookie.net/mario/images/3/32/Star_Coin.png/revision/latest?cb=20120731132023))

Voting to close this issue and move on.
