### ISSUE TITLE
Insert images/audio at cursor location in Note Editor

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#3669]
When I "Add image" to add another picture to note,the next picture will replace the last picture.So how to inset two or more picture in my android-anki?
![screenshot_2015-09-25-20-57-58](https://cloud.githubusercontent.com/assets/10048069/10101055/bfb2c348-63c8-11e5-9dba-295757f5d258.jpeg)

**Comment by flerda** [comment]
At the moment, add image always replaces any existing content in the field, so there is no way to do this.

In many cases, one would probably want to put different pictures in different fields, if they represent different aspects of the note, but it seems reasonable to allow inserting more than one picture in a single field.

The only workaround I can think of at the moment would be to copy the HTML from inserting the first image, insert the second image, and then paste the first HTML so that both would be there.

**Comment by Juddd** [comment]
thank you for your response,my courrent method is copy the HTML to do it,any way,I'm very appreciate to you.

**Comment by johanrhodin** [comment]
Is there a separate issue for the behavior that it always overwrites the previous content in the field (text, image or otherwise)?

**Comment by eginhard** [comment]
This is actually available now.
