### ISSUE TITLE
Deck picker screen looks odd on tablet

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3703]
There are two or three things i think are odd on the new xlarge deck picker layout:

* There is a gap in the blue action bar
* There are two back buttons. Both take you to the launcher (Android home screen). I liked the old style better, with one button to open the drawer.
* There are two ⋮ menu buttons. That may be OK, they show different menu items.

![screenshot_2015-10-05-10-30-07](https://cloud.githubusercontent.com/assets/1690429/10276125/ab680fc4-6b4d-11e5-953f-717e95db654b.png)

AnkiDroid Version = 2.5alpha67

Android Version = 5.1.1

ACRA UUID = 1de7e18b-4656-47bb-aaa6-8e42f2d59b74

**Comment by timrae** [comment]
> There are two back buttons. Both take you to the launcher

That's a mistake. I meant to disable the back button in tablet views, I'll fix it soon thanks.

> There are two ⋮ menu buttons. That may be OK, they show different menu items

That's completely intentional. The one on the left operates on the entire collection, and the one on the right operates on the currently selected deck

> There is a gap in the blue action bar

That's semi-intentional. At first it was just a mistake, but then later I thought that it might make more sense to separate them as they are two separate toolbars with separate actions. Getting rid of the gap is a slight pain in the ass, it would probably be easier to do programmatically. Do you have any other apps that have two toolbars in the same Activity? What do they look like? I don't have a tablet so have just been going off the emulator with it's standard system apps

**Comment by ospalh** [comment]
>> There are two ⋮ menu buttons. 

> That's completely intentional.

OK then.

>> There is a gap in the blue action bar

> That's semi-intentional. (…) Getting rid of the gap is a slight pain in the ass.

And i guess i can get used to it.


My main reference for this kind of split is GMail, and i think they have one toolbar and make it look like two. They have a search button where the left ⋮ is in AnkiDroid, only one ⋮, and no gap. That app also hides the mini drawer in the one-pane just-one-email view in portrait mode, cf #3702.

**Comment by timrae** [comment]
Could you post a screenshot please?

**Comment by ospalh** [comment]
I guess it is easier when you look at the play store, second image (third gallery item)

https://play.google.com/store/apps/details?id=com.google.android.gm

**Comment by timrae** [comment]
I see. The second screen is in portrait it seems. Do you review in portrait or landscape?

I made a [thread on the forum for feedback](https://groups.google.com/forum/#!topic/anki-android/UIaR1DzN9ks). @hssm and @snowtimeglass, please post some feedback there.

**Comment by timrae** [comment]
I think the two overflow menus is OK, and I've fixed the other stuff in alpha69
