### ISSUE TITLE
v2.5 Hungarian translation

### ISSUE THREAD

**Issue by mila6452** [ankidroid/Anki-Android#3759]
Android beta version
- lot of text without translation! (especially embarrassing on pop menus where some text is in English between the Hungarian) 
- The "setup" itself is full with english phrases
- "Add" (plus sign) popup: the last menu point (small plus icon) is wrong. The correct one is "Új kártya hozzáadása"

Is it possible to correct immediately somewhere in a translation file? (and later I send you just this translation file)

**Comment by pducrocq** [comment]
You can modify translation files here :
https://crowdin.com/project/ankidroid

**Comment by ospalh** [comment]
> Is it possible to correct immediately somewhere in a translation file?

Not easily.
The not-easy way is to get the source code, change the files in the [`values-hu`](https://github.com/ankidroid/Anki-Android/tree/develop/AnkiDroid/src/main/res/values-hu) or `values-NN` directory, build, delete the downloaded version and install your own.
See the [development guide](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide) section of the manual about how to get started with this.
Or rather than changing the translation files in the `values-NN` directory, you should probably translate them at Crowdin, and download xml files from there. That’s the best way to share you translation.

**Comment by mila6452** [comment]
Ok, got it. One quick question:
What language key have used for the "Add" (plus sign) popup: the last menu point (small plus icon)?
If this is "menu_add_note" lang key than it is a wrong usage. (The translation is good)
This should be: "menu_add_card"

**Comment by ospalh** [comment]
Actually, “Add note” and so `menu_add_note` is correct. You add notes, and for each note one *or more* cards are generated. See also the main [Anki manual](http://ankisrs.net/docs/manual.html#adding-cards-and-notes).
(The number of cards generated can even [depend on the data added](http://ankisrs.net/docs/manual.html#selective-card-generation). The complex note type i use most of the time generates anything from two to seven cards, depending on what i put in.)
