### ISSUE TITLE
Add Automaticsync option only on Exit

### ISSUE THREAD

**Issue by MarcoSchicke** [ankidroid/Anki-Android#3798]
The Automatic Syncoption is great.
But even if Ankidroid is opened and there is nothing to sync it takes over 5 seconds till sync is completed. 
If the syncoption now is:
- Automatic sync on / off

Maybe a Change to this will be nice:
- Sync on open and exit
- Sync only on exit
- Manual sync 

I know that there are now also interfaces for Tasker, but this may be a small change which may make the sync option more comfortable.

**Comment by eginhard** [comment]
I'd personally find this very useful as well. I review almost exclusively on the phone, so syncing on startup is usually not necessary, but an automatic backup sync on closing would be handy.

**Comment by timrae** [comment]
I'd support merging if someone submitted a PR

**Comment by mikehardy** [comment]
For what it's worth, I looked at having Android applications do anything on exit, and it looks like the platform simply doesn't support reliable execution of any codes as an app is exiting. Could maybe done on the onStop() lifecycle hook but after reading up on this now I realize why mobile apps all do time-based synchronization (e.g. every X hours).

**Comment by nicolas-raoul** [comment]
If anyone knows an app (preferably open source) that reliably syncs (potentially large amounts of data) on exit, please let us know :-)

**Comment by mikehardy** [comment]
If we've all looked at this and no one can find a reliable way to do it, seems like it could be closed as some version of "not possible"

**Comment by mikehardy** [comment]
@nicolas-raoul I just found something interesting related to your question about any apps reliably syncing on exit.

The onSaveInstanceState() API will be called and allow execution synchronously, on system process kill: https://developer.android.com/topic/libraries/architecture/saving-states#use_onsaveinstancestate_as_backup_to_handle_system_initiated_process_death

It should not be used to do the synch, however, it could be used to implement the "reliable" portion, as it refines my understanding and makes my previous statement ("the platform simply doesn't support reliable execution of any codes as an app is exiting") incorrect.

I don't think that really changes things here since syncs still may or may not complete onFinish() but you could at least indicate in saveInstanceState whether it completed and maybe handle re-start more effectively.

There's another patch floating around about syncing on an interval, and one about syncing after studying last card in a deck. Review on that last one was that syncing options in general should be consolidated, so at that point there'd be

sync on open
sync on interval
sync after studying last card (in deck? in whole collection?)
sync on close (should be marked as possibly unreliable, maybe use saveInstanceState also and if it didn't complete include a popup on next app start to sync?)

**Comment by mikehardy** [comment]
I have some ideas here but think this is best deferred so we can get 2.9 out

**Comment by david-allison-1** [comment]
Duplicate of #4487

**Comment by david-allison-1** [comment]
Whoops - misread - this is on app exit

**Comment by mikehardy** [comment]
I just don't think this is viable. system exit is just not for long-running tasks and sync is long-running.
