### ISSUE TITLE
Software keyboard covers input box (2.5beta)

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3806]
In this [Google Groups thread](https://groups.google.com/forum/#!topic/anki-android/2_HVyTA6TeA) there are two or three issues discussed. One of them:

When you have a longish card, and a type input box at the bottom, when you touch the box, the software keyboard covers the input box.

I tried to fix it with the help of a tip from @flerda, but can’t get it to work.

My try is [this branch](https://github.com/ospalh/Anki-Android/tree/notafix-invisible-inupt). Not sure why that does not work.

**Comment by 110229048** [comment]
good good study

**Comment by hssm** [comment]
It's very likely that the navigation drawer is responsible since it's the container of everything else in the activity.

I've been trying all sorts of stuff for this and in the end I removed the Navigation Drawer where it finally worked. But at the moment it could be a combination of things since I've hacked away bits and pieces all over the place. I'll figure something out soon enough.

**Comment by hssm** [comment]
Aaah so it turns out there's a whole [saga](https://github.com/mikepenz/MaterialDrawer/issues/95) over this very issue on the MaterialDrawer issues page. I'm glad I found this before spending any more time on it. Looks rough.

There is a method available that enables the workaround. It's not turned on by default. Now I just need to figure out how little we need to change to make it work for us.

**Comment by ospalh** [comment]
Thanks for finding & fixing this.
