### ISSUE TITLE
AnkiDroid port to ChromeOS doesn't run

### ISSUE THREAD

**Issue by shippy** [ankidroid/Anki-Android#3814]
At some point this week, the AnkiDroid (2.4.3) from the Chrome Web Store ceased to run. As in, clicking on the icon, selecting it from the app drawer, or otherwise invoking it results in no action whatsoever. Looking through one-star reviews on the Chrome Web Store, this does not appear to be an isolated case.

I'm using a Toshiba Chromebook 2 (CB35-B3340). ChromeOS version is 47.0.2526.49 beta (64-bit) -platform 7520.34.0 (Official Build) beta-channel swanky, with firmware Google_Swanky.5216.238.5. The AnkiDroid stoppage preceded the latest update; removing and re-installing the app from the store did not help.

My current hypothesis for the cause: in the extension list, App Runtime for Chrome (beta, 47.5021.508.9) is listed as disabled and clicking on "Enable" does not activate it. The other ported Android app that depends on ARC, Evernote, doesn't launch either.

I'm not sure how to debug this further.

**Comment by agrueneberg** [comment]
Hi Simon,

thanks for letting us know. Ever since they closed the mailing list in favor of tagged questions on Stack Overflow I haven't heard much news about ARC (App Runtime for Chrome). Unfortunately, with the transition to the ARC Welder app to prepare releases, the documentation for the Python scripts that we use have also disappeared, and with that the only way I'm aware of to properly debug the app. Not that I could do much about the runtime issues anyway...
I can try to run the app through an updated version of the ARC script and see if that fixes any problems. Actually, I have been waiting for the final release of 2.5 because I want to keep releasing new versions to the Web Store to a minimum. With each release there is a risk of users losing their decks because the app is not allowed to write into the Downloads folder...

The app still works on my original Samsung Chromebook (ARM). Have you tried switching to the stable channel? Maybe it's the runtime that is not supported on the beta channel, otherwise I can't really see a reason why it would be disabled.

In the meantime, can you install the [ARC Welder app](https://chrome.google.com/webstore/detail/arc-welder/emfinbmielocnlhgmfkkmkngdoccbadn) on your Chromebook and see if it works with a [recent AnkiDroid 2.5 APK](https://github.com/ankidroid/Anki-Android/releases)?

Cheers,
Alex

**Comment by shippy** [comment]
Solved the problem! I uninstalled both apps that were dependent on ARC (ARC Welder, AnkiDroid & Evernote), which uninstalled ARC as well. Then, re-downloading AnkiDroid re-installed ARC -- and now both work.

(For the record, ARC Welder got stuck unpacking the APK during my initial attempt. After the ARC reinstallation, ARC Welder had no problem.)

**Comment by agrueneberg** [comment]
Thanks for following up! Uninstalling all dependent apps to be able to reinstall the runtime should definitely go on our list of recommendations in case of trouble.
