### ISSUE TITLE
App bar isn't elevated properly

### ISSUE THREAD

**Issue by tsudoko** [ankidroid/Anki-Android#3890]
According to the [Material Design guidelines][0] the app bar's elevation should be 4dp, on my device it's 0.

    AnkiDroid Version = 2.5beta27
    Android Version = 5.0.1
    ACRA UUID = b3887115-17b7-4ba4-ba9c-84544d3f152b

[0]: https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-shadows

**Comment by timrae** [comment]
Thanks for the reminder, I had been meaning to fix it for a while

**Comment by timrae** [comment]
IMO it looks a bit weird with the elevation in the reviewer together with the light blue color of the top cards count bar. How about making that bar white so that it looks like a single surface? This seems more "material" to me

![transparent](https://cloud.githubusercontent.com/assets/2818274/11456621/0be8c208-96d2-11e5-8bc8-0a6588038d49.jpg)
