### ISSUE TITLE
Remove mostly unused / brittle "Lookup dictionary" feature

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3896]
It is appropriate that the following texts ("None" and "Eijiro") should be translated.
![image](https://cloud.githubusercontent.com/assets/10436072/11451998/da9f520e-961b-11e5-8408-b63539d211b4.png)

**Comment by mikehardy** [comment]
great first issue

**Comment by Arnold2381** [comment]
@mikehardy can u elaborate more on what needs to be done?
I want to work on this.

**Comment by david-allison-1** [comment]
It'd likely be best to find another issue to work on until 2.15 is out. I think we'll be able to remove this feature: #8263

This would involve extracting strings to resource files, see: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

**Comment by Kritartha1** [comment]
@mikehardy 
![image](https://user-images.githubusercontent.com/68478501/149199767-18938187-8c51-4395-96c9-cc7a0c824f9b.png)
![image](https://user-images.githubusercontent.com/68478501/149199801-6c476f43-e7c8-4a5a-9f73-877475060bf0.png)
So, the issue is  just to remove the lookup dictionary feature/ tab from the app?

**Comment by mikehardy** [comment]
Yes!

**Comment by shocoman** [comment]
Hey, I actually liked this feature :(
How about instead of removing it completely just make it easier to use? For example, show dictionary by double tapping on a word (no need for copying or any other slow stuff). 
By the way, Lookup dictionary is currently bound to long tap gesture programmatically (even though this gesture is not accessible from the menu), so that should also be accounted for when this feature will be removed.

**Comment by mikehardy** [comment]
We will never be able to make everyone happy unfortunately. I understand the feature is in use, it's just that use is vanishingly small, and the feature itself is complicated, and limited (only a few languages. No one works on it, it's brittle as the online dictionaries change semi-frequently, so to my view as a maintainer it is not justifying it's existence vs it's carry cost. It's a difficult reality.

**Comment by BrayanDSO** [comment]
Can I work on this?

**Comment by david-allison** [comment]
Sure!

**Comment by BrayanDSO** [comment]
> Just a question, is there a standard procedure to remove an unused string from resources or should I just do a mass find and replace?

As stated at the [development guide](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations), I believe I should just edit things. So I guess this answers my question.
