### ISSUE TITLE
Can't open some collections with high degree of nesting in the decks

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3905]
A user on the forum sent me his collection that wouldn't open and I've reproduced the issue.

I've pasted the stack trace below; the crash seems to be happening due to calling `mCol.getDecks().confForDid(did)` where `did` is null. After looking at the code, it's not obvious to me why it doesn't fail MORE (i.e. whenever there are a few levels of nesting), but on the surface the code appears to be the same as Anki desktop.

(Note however that Anki desktop **doesn't** crash with the same collection, so there's obviously a subtle difference somewhere)

I can get the collection to open by changing it to `confForDid(node.did)`, but that's not what Anki desktop does, so I'm not sure if that's correct or the best solution. 

@hssm could you please take a look?

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
	at com.ichi2.libanki.Decks.confForDid(Decks.java:645)
	at com.ichi2.libanki.Sched._groupChildrenMain(Sched.java:505)
	at com.ichi2.libanki.Sched._groupChildrenMain(Sched.java:497)
	at com.ichi2.libanki.Sched._groupChildren(Sched.java:449)
	at com.ichi2.libanki.Sched.deckDueTree(Sched.java:437)
	at com.ichi2.async.DeckTask.doInBackgroundLoadDeckCounts(DeckTask.java:490)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:235)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66)

**Comment by hssm** [comment]
I've pin-pointed the source of the problem but it'll have to wait until tomorrow to get a proper fix in. Took me forever to figure it out.

**Comment by timrae** [comment]
Great, nice work! I'm interested to see what the fix is and why the desktop can assume the did is non null.

**Comment by timrae** [comment]
Fixed in 2.5.1

**Comment by hssm** [comment]
I said I would explain this so here it is before I forget.

It ultimately comes down to my mininterpreting [this](https://github.com/dae/anki/blob/master/anki/sched.py#L268) line in python. In my defence, the python version was really confusing as it interchanges between a string and a list of strings for the same variable as it processes the tree. In hindsight it's kind of obviious what it's doing.

The old code was only sorting on the first element of the names array which is the top-most parent deck name. The new code sorts correctly by considering every element in the names array, made slightly more complex because python sorts a list of string lists for free while we have to manually check each element.

The failure condition was a list of decks where a sibling deck gets sorted before a child deck. So instead of:

a::X
a::Y
a::Z
a1::X
a1::Y

You got:
a::X
a1::X
a::Y
a1::Y
a::Z

(or something along those lines). We iterated (recursively) over that list by taking a [chunk of repeating](https://docs.python.org/2/library/itertools.html#itertools.groupby) parent deck names. But the "repeating" part falls over when the list isn't sorted correctly.

The reason `did` was null was because we were expecting a child deck at the end of the iteration but it terminated early because we didn't have the complete list.

So you were right about the nesting which greatly increased the chances of this happening.

**Comment by timrae** [comment]
Thanks for the explanation!
