### ISSUE TITLE
Make StudyOptions information easier available

### ISSUE THREAD

**Issue by Steph1444** [ankidroid/Anki-Android#3920]
In the previous version, on opening a deck one got the deck overview screen. It took no effort to have the information available and one tap to begin the learning session. All that is easy and comfortable.
Now one needs 9 steps to get this information in the Statistics tab.
I find this is a step back and I'm curious how other users experience this change.
Please offer an option to restore this functionality.
I'm using Ankidroid on a daily basis for almost 2 years now and it's a life changer! I most like it's flexibility and efficient learning capabilities.

**Comment by Musashi1986** [comment]
I also liked it more when we had the deck overview screen. Since I use it in a tablet, it just appears in the right side of the screen when I select a deck, and the button to start studying is still there, so for me not having it does not mean I access the session faster/easier. While the number of cards still appears on the screen, I miss the graph indicating how many cards I have for reviewing the following days.

**Comment by eginhard** [comment]
Some ideas:
* The long-press menu in the deck overview could show this information (at least on phones).
* There could be an icon in each deck list item that directly opens the reviewer, clicking elsewhere opens the study options (this is probably hard since there's already the expander icon and the numbers on the right).
* Somehow make the numbers on the right more button-like, clicking on them would open the study options, clicking elsewhere the reviewer.

**Comment by timrae** [comment]
> Somehow make the numbers on the right more button-like, clicking on them would open the study options, clicking elsewhere the reviewer.

That's a pretty cool idea, it should be pretty straight-forward to make their layout clickable!

**Comment by hssm** [comment]
I had another idea which may not be as simple to implement. We aren't making use of [horizontal swiping](http://developer.android.com/training/design-navigation/descendant-lateral.html#paging) for anything in the deck list, so maybe this could be a use for it. Swipe to go to the deck overview or tap to go straight to review.

**Comment by timrae** [comment]
That could work, but yeah adding a ViewPager might be a bit of a pain

**Comment by timrae** [comment]
@eginhard's fix is available in the 2.5.2 beta: https://github.com/ankidroid/Anki-Android/releases

**Comment by Steph1444** [comment]
Thanks for answering and solving my issue. Amazing how fast this was handled. It's better then ever
