### ISSUE TITLE
Long press -> "Web search" serches for previous search term

### ISSUE THREAD

**Issue by johanrhodin** [ankidroid/Anki-Android#3971]
1. Perform a couple of long press actions on the front or the back part of a word in a card; each time select "Web Search" from the context menu.
2. The third or so search will start to search for a previous searched term and not the one highlighted.

**Comment by eginhard** [comment]
That contextual action bar is controlled by the Android system, not by AnkiDroid, so it would be an Android bug. I can't reproduce it either.

**Comment by hssm** [comment]
This appears to be a problem with the Google Search application itself.

1. Use web search
2. Switch applications with recent tasks button (*don't* use back button)
3. Use web search again

At step 3 it simply raises the previous instance instead of initiating a new search. This is completely out of our control. The same thing happens when doing this from the Gmail app, for example.
