### ISSUE TITLE
A bug and an amateur solution ordering decks' names

### ISSUE THREAD

**Issue by M-M-Rezaee** [ankidroid/Anki-Android#3987]
Dear Ankidroid developers,

If I name my decks by number, its order get in to trouble. To be more precise when my decks' name are 1, 2, …, 9, 10, the order would be 1, 10, 2, ..., 9. However, I have realized they arrange in nominal order when I name them 01, 02, …, 10. I was wounding if you could solve this problem professionally.

I look forward to hearing from you.

Bests, 
M.M-Rezaee

P.S. Amateur solution: I have realized decks' names arrange in nominal order when I name them 01, 02, …, 10.

**Comment by hssm** [comment]
We use the same ordering as the desktop client. We know it's not the preferred way but we can't change it since the [order of the decks impacts review behaviour](http://ankisrs.net/docs/manual.html#display-order), and some people order their decks to exploit the behaviour described in that link.

The manual tells you to order them in a similar way to your own one, so that's the "official" solution for now.
