### ISSUE TITLE
Number of buried cards not shown correctly

### ISSUE THREAD

**Issue by cyclohexanamine** [ankidroid/Anki-Android#4002]
When I review a card with siblings that are due, and the siblings are buried, the number of cards that are due does not change. It can be updated by exiting to the deck screen. This seems to create issues with new card scheduling when Anki is set to mix new cards in with reviews, as it will unexpectedly run out of review cards early and have to schedule the new cards all together.

AnkiDroid Version = 2.5.4

Android Version = 5.1

ACRA UUID = 081d0fd0-65d3-41ce-9223-f336296238b0

**Comment by hssm** [comment]
Does the desktop client behave differently? Can you export a deck that exhibits this problem and email it to me so I can take a look?

**Comment by cyclohexanamine** [comment]
The desktop client does the same thing. I've sent you a deck.

**Comment by hssm** [comment]
Since the desktop client behaves the same way you will have to report this as an issue on [the main project support site](https://anki.tenderapp.com/). It's not a problem specific to AnkiDroid so there isn't anything we can do about it since we can't change the reviewing and scheduling behaviour on our end.
