### ISSUE TITLE
The underline of the textbox of 'Reschedule card' is red when any strings aren't entered

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4008]
and there is a counter on the right end.

Are they intentional?

![image](https://cloud.githubusercontent.com/assets/10436072/11911167/f6d26e2c-a64f-11e5-9286-63fbeb47f74b.png)

![image](https://cloud.githubusercontent.com/assets/10436072/11911172/0c4ac966-a650-11e5-9e98-24b372740140.png)![image](https://cloud.githubusercontent.com/assets/10436072/11911178/252e12c6-a650-11e5-9c5b-45d990f667e0.png)

**Comment by snowtimeglass** [comment]
The counter counts not the number of the days but the digits of the days.
![image](https://cloud.githubusercontent.com/assets/10436072/11911287/8a17f590-a654-11e5-8a6c-6e9bb0cca3bf.png)

**Comment by hssm** [comment]
No it's not intentional.

**Comment by hssm** [comment]
Or actually, it should show those numbers but with a count of 4 instead of 9999.

**Comment by snowtimeglass** [comment]
I think the counter need not be displayed. If anything, it's better not to display it.
10000 days (= about 27 years) is very unnatural number for the textbox, so such a inputting seldom occurs.
It seems to be enough to display a error message when such a number is inputted.

**Comment by hssm** [comment]
Normally when dealing with numbers you would use a [number picker](http://stackoverflow.com/questions/11800589/number-picker-dialog), but we can't use the built-in one because we target older APIs, and pulling in a new dependency just for this seems excessive.

I'll put in a quick fix for the maximum number, but I don't think the underline and counter are such a big deal. Technically, since there is limited input, showing the counter is the "correct" thing to do in Material Design.
