### ISSUE TITLE
All media files disappeared

### ISSUE THREAD

**Issue by jkadlubo** [ankidroid/Anki-Android#4060]
Since the last update all of my media files are gone from both my android devices. I tried syncing multiple times, creating New cards on the laptop and to no avail.

When viewing a card with a picture, the name of the picture file is displayed, followed by the rest of the explanation.
Moreover, syncing to computer removed all of those files from the main copy of the deck. Part of the deck is saved with files in there on Anki web, but right now I'm afraid to touch that deck to not destroy the last mostly workable copy of the deck.

The debug info:
AnkiDroid Version = 2.5.4

Android Version = 5.0.1

ACRA UUID = 3ced603b-5210-467e-9ca5-c236f82e7467

**Comment by eginhard** [comment]
First of all, if you know that the media is still on Anki Web, you can force a sync in one direction with both AnkiDroid and Anki Desktop (there's a check box in the settings), so you can back up your Anki Desktop data (just in case) and force a download of the collection from Anki Web to recover it.

When updating AnkiDroid, the application data isn't touched at all in general and wouldn't just be deleted. Maybe your collection path has been reset, so that AnkiDroid is looking at the wrong directory. You can use a file management app or your computer to see if there is another AnkiDroid directory and, if necessary, reset it in Settings -> Advanced -> Collection Path/AnkiDroid Directory.

**Comment by darvag** [comment]
I have just the same problem! 
all of my data are gone and there is nothing as backup in ankiweb, although I had backup.

**Comment by eginhard** [comment]
[AnkiWeb terms of use](https://ankiweb.net/account/terms): "Decks stored in your account may be archived and eventually deleted if they are not accessed in 3 months or longer." But for support with your AnkiWeb account, please report it here: https://anki.tenderapp.com/ (the AnkiDroid team doesn't manage AnkiWeb)

For locating AnkiDroid data on your phone, see my advice above, but if you wiped your phone your data will have been deleted.
