### ISSUE TITLE
Zoom image in card distorted

### ISSUE THREAD

**Issue by jsalatiel** [ankidroid/Anki-Android#4085]
I have attached a jpeg image on a card, the image has a big resolution (3769x6099) and if i open it directly by browsing the collection.media folder, it opens just fine and i can zoom it just fine. The problem is when the image is loaded inside the card. When i try to zoom, i get a completely distorted image that i just cant read.  Please see the attachment.

![screenshot_2016-02-09-14-32-22](https://cloud.githubusercontent.com/assets/5522389/12925193/e0cdd50c-cf3b-11e5-8ff8-0a0a500d62fc.png)

**Comment by hssm** [comment]
I don't know if there is anything that we can do about that. It's up to the system components (I.e., the Android System WebView) to decide how to scale the images. We have no involvement in the process. It's likely that the WebView is optimized for the web while your image viewing application isn't, which is why you see the discrepancy. On the web, text-based images will usually be in PNG instead of JPEG.

That said, 3769x6099 is *huge*. Do they really need to be that big? If you are generating these images yourself, you need to make them PNGs, because those handle text and scaling way better. It'll likely solve your problem completely. Other than that, you can try resizing the images on a computer.
