### ISSUE TITLE
Color problems with themes

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#4090]
I noticed two or three problems with the themes:

I am using 2.6alpha13, Android 5.1 and 6.0.

* In the black night mode, on a tablet, the selected settings group on the left is “shown” with black text on a black background.
* Now in the settings, with the default theme, i get black on light blue text in the title bar, instead of the white on light blue everywhere else in the app. This was still OK in 2.6alpha10.
* This may be intentional, but i don’t like it that, with the black night mode, you can’t see where one ease button ends and the next one starts. (In the plain day theme, you get thin lines between these buttons.)

**Comment by hssm** [comment]
I'm aware of the first two and hope to fix them by finishing off https://github.com/ankidroid/Anki-Android/issues/3625 one day.

As for the third point, there *are* thin lines around the buttons in the black theme as well. They're actually bigger than the plain theme's borders. I could make those a little brighter. They might be harder to see on a tablet since the buttons are pretty large and drown them out.

**Comment by ospalh** [comment]
> As for the third point, there are thin lines around the buttons.

Yes, i see them. But only in the directly recorded digital screen shot.

This is the best i could manage with a camera at short notice:
<blockquote class="imgur-embed-pub" lang="en" data-id="8N11CkN"><a href="//imgur.com/8N11CkN">What lines‽</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
