### ISSUE TITLE
Prioritize learning over reviews

### ISSUE THREAD

**Issue by jsalatiel** [ankidroid/Anki-Android#4118]
Would it be possible to add an option to prioritize learning cards over reviews or at least mix them ?
Currently if i have 100 cards to review and 50 in learning mode , the learning cards will only show after all 100 review cards are finished.

**Comment by eginhard** [comment]
Any suggestions to change the scheduling algorithm would have to be made on the [Anki Desktop forum](https://anki.tenderapp.com/discussions). However, you can already use [filtered decks](http://ankisrs.net/docs/manual.html#filtered-decks-&-cramming) to specifically study learning cards and if they always appear at the very end of the queue this is probably due to having set too high values for the [learning steps](http://ankisrs.net/docs/manual.html#learning) for new cards. Adjusting those won't change the scheduling of your existing learning cards, but it should help to prevent this problem in the future.
