### ISSUE TITLE
how to update my project forked form other on online Github?

### ISSUE THREAD

**Issue by John0079** [ankidroid/Anki-Android#4154]
hollow everyone,
  help me, I am new user for Github,
on github website, i forked a open source project, After modify it , I commit it by PULL Request.
After some days, when I open the project on Github website, i want to see the latest version, but the project version under my account is still the version which i commit last time, how can I update it to the lastest version of the open source project.

**Comment by flerda** [comment]
I think this link might contain the information you seek:
https://help.github.com/articles/syncing-a-fork/

**Comment by John0079** [comment]
@flerda Thanks you!
but it isn't what i want, it give a way under windows version Github, but i want to know how do it on the github webpage.

**Comment by flerda** [comment]
You cannot do it from the Github website as far as I know.

This is because there might be conflicts when you perform such an operation, that would require making changes to the code, which cannot be done on the website itself.

Also note that because of the way AnkiDroid accepts pull requests, you should rebase rather than merge.

If you seek further advice on getting this done via the website, I would suggest looking at https://help.github.com/ and posting question there, since that's not specific to this project (and people from Github who can implement this feature are more likely to see this request).

**Comment by flerda** [comment]
This is an issue on Github that you might want to follow:
https://github.com/isaacs/github/issues/88
but it has been open for 3 years without much progress...

**Comment by John0079** [comment]
@flerda Thank you very much, i will follow your suggest to do it.

**Comment by timrae** [comment]
The easiest way is to delete your fork and then refork. Note that you'll
lose any changes you made to your fork.

**Comment by John0079** [comment]
Yes, ah, it seems this is currently the most effective way! Thank you!
