### ISSUE TITLE
deck sorting options: last opened, last edited, most cards to study, etc.

### ISSUE THREAD

**Issue by katrinleinweber** [ankidroid/Anki-Android#4211]
[Apparently](https://groups.google.com/forum/#!searchin/anki-android/sort/anki-android/juf8Oe5ARro/0Toy-kJ66OgJ), AnkiDroid at some point had a "sort alphabetically" option, which is now the default. Please consider adding other sorting options, to accommodate use-cases where the user:

- has lots of decks, but wants to focus on few => last studied on top
- edits decks in [Anki Desktop](http://ankisrs.net/) & syncs edits to AnkiDroid => last edited deck on top
- has to crunch through everything before exams => largest decks on top

All these options could have both as- & descending direction. Currently, one can only simulate different sorting orders be prepending a number or special character to the deck name.

**Comment by hssm** [comment]
This is something we can't change independently of the desktop client. Aside from consistency, the order of the decks influences the order that cards appear in sub-decks, so some users build a custom ordering using the method you mentioned. It's actually what the Anki manual suggests so we have to support it since it's "official" behaviour.

Perhaps in the next version of Anki this will be one of the things that will be reconsidered. For now it's not something we can change.

**Comment by katrinleinweber** [comment]
Too bad, but thanks for explaining :-)
