### ISSUE TITLE
Review session stops when all new & incorrect cards are used up

### ISSUE THREAD

**Issue by AngledLuffa** [ankidroid/Anki-Android#4221]
I have noticed that when I have a list of cards to review and a list of new cards in the same session, AnkiDroid will often stop reviewing as soon as all the cards in the new or incorrect category are used up.  This is true even when there are still cards to be reviewed from previous days.

I am currently using version 2.5.4 on a recently updated Blackberry Priv.

**Comment by hssm** [comment]
- Does it show a message when it exits?
- What happens if you go back in to the reviewer and continue reviewing?
- Can you check what happens if you *undo* the last review (using the undo menu option) and then go back to your deck and review the last card.

The easiest test for us would be for you to sync your collection and see how the desktop client behaves before or when it ends up in that state and tell us if AnkiDroid does things differently.

It's hard to test for things like this without having a copy of your collection in this exact state and the exact time that the problem occurred.

**Comment by AngledLuffa** [comment]
It doesn't show a message when it exits.  It goes straight to the deck list (where I only have the one deck).

If I go back to the reviewer, it just says I am finished with the studying for the day.  No option to continue reviewing in any way.

Given that I can't re-enter the study session once it calculates I am finished for the day, it is not possible to undo the previous action and see how it responds.

When I study tomorrow, I will be happy to save it when there is just one card left in the session.  How do I do that?  Is there a mechanism to export the current state?

I have not used the desktop client at all.

**Comment by hssm** [comment]
>it is not possible to undo the previous action

I can't remember when we added it but there *might* be an undo option in the action bar menu (the three dots) from within the deck list screen in the currently released version.

You can export from within the application: https://ankidroid.org/docs/manual.html#_exporting_collection_package

When you do that, make a note of your time and time zone.

**Comment by AngledLuffa** [comment]
I've been meaning to do this, but the last couple days have had varying results.

I saved the database and finished my session two days ago, but instead of stopping when the new and incorrect cards were used up, it continued until my review cards were complete as well.

Last night, I didn't save the database, and it did exhibit the abnormal behavior.  However, it may have been because I was finishing the review after midnight.  Could that have an effect on whether or not it finishes the review?

**Comment by hssm** [comment]
Since we don't know the cause it's entirely possible that it has an effect. If your `new day starts at` setting is set to 0 or 1 then it becomes even more likely.

**Comment by AngledLuffa** [comment]
It's not because of midnight.  I saw it happen both yesterday and today when I was nearing the end of a review session.

Here is my state immediately after it happened.  I'll save it before I reach the end tomorrow and see if it happens.

[collection.apkg.zip](https://github.com/ankidroid/Anki-Android/files/233202/collection.apkg.zip)

**Comment by hssm** [comment]
Can you also make note of the time and the time zone so I can try to reproduce it.

**Comment by AngledLuffa** [comment]
This one happened roughly noon PST.

**Comment by madhead** [comment]
I'm facing similar behavior. E.g. I'm starting a review session with 20 new cards (blue), 0 learning cards (red) and 43 cards to review (`20 0 43` under the deck name): 
![screenshot_20160627-192036](https://cloud.githubusercontent.com/assets/577360/16387192/7752627c-3c9c-11e6-9798-c748ea4ab963.png)
Then, when I'm done with new+learning cards, even if I have some cards in third category (graduated cards), that number is zeroed and I'm shown a decks screen.

What I've noticed is that graduated cards _got buried_. I am not sure if this is expected / correct behavior or not. What the docs says here is:

>When you’ve finished the cards that are due to be studied today, you’ll be taken back to the decks list and shown a congratulations message. From here you can select a different deck, or if you’ve finished studying for the day, you can simply tap the home button in order to close AnkiDroid (and you can also do this in the middle of reviews if you wish).

As a workaround I just unbury that deck (using the context menu), so the numbers are set to something like `0 0 42` (42 is just an example here) and continue the review session until all three are zeroed.

**Comment by eginhard** [comment]
Are these just sibling cards? (see sibling burying in the manual:
http://ankisrs.net/docs/manual.html#siblings) Then it is intentional.

On Jun 27, 2016 9:33 AM, "madhead" <notifications@github.com> wrote:

I'm facing similar behavior. E.g. I'm starting a review session with 20 new
cards (blue), 0 learning cards (red) and 43 cards to review (20 0 43 under
the deck name):
[image: screenshot_20160627-192036]
<https://cloud.githubusercontent.com/assets/577360/16387192/7752627c-3c9c-11e6-9798-c748ea4ab963.png>
Then, when I'm done with new+learning cards, even if I have some cards in
third category (graduated cards), that number is zeroed and I'm shown a
decks screen.

What I've noticed is that graduated cards *got buried*. I am not sure if
this is expected / correct behavior or not. What the docs says here is:

When you’ve finished the cards that are due to be studied today, you’ll be
taken back to the decks list and shown a congratulations message. From here
you can select a different deck, or if you’ve finished studying for the
day, you can simply tap the home button in order to close AnkiDroid (and
you can also do this in the middle of reviews if you wish).

As a workaround I just unbury that deck (using the context menu), so the
numbers are set to something like 0 0 42 (42 is just an example here) and
continue the review session until all three are zeroed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4221#issuecomment-228800040>,
or mute the thread
<https://github.com/notifications/unsubscribe/AE-ZZR3tROUc-E64OIwpQTSAw3TfEFJeks5qP_tUgaJpZM4IK_sm>
.

**Comment by madhead** [comment]
@eginhard, Maybe. The deck [I'm talkig about](https://ankiweb.net/shared/info/1409355905) creates 3 cards from each note. So, I suppose, there are multiple sibling groups in the remaining cards (7-10, for example) and maybe I've already seen one card from each of that groups?

Any instructions of how I can track this down? I haven't done any reviews today yet, so it's a good chance on a deck with `20 0 75`.

**Comment by eginhard** [comment]
@madhead If you have sibling burying disabled for new cards and reviews in the deck options of that deck (make sure it's the correct one), it shouldn't happen. If nonetheless some cards are buried, you should check if the same behaviour can be observed in Anki Desktop.

**Comment by madhead** [comment]
As expected, when I turned off "New cards / Bury related new cards" and "Reviews / Bury related reviews" the cards are not buried.

**Comment by AngledLuffa** [comment]
Neat, thanks for letting me know!  I will give that a try and report back.
