### ISSUE TITLE
AnkiDroid doesn't generate two different cards you just get two same cards

### ISSUE THREAD

**Issue by ozarux** [ankidroid/Anki-Android#4275]
Then I want use type: basic (and reversed card), it generate two cards like example front: 1 back: 2 and front: 2 back: 1, but then you want to study created cards you get 1 2 and 1 2 but have to be 1 2 and 2 1

**Comment by timrae** [comment]
There's most likely an error in your card template. Please check the card layout and edit as necessary.

https://www.youtube.com/watch?v=F1j1Zx0mXME

**Comment by ozarux** [comment]
Look it yourself and say what is wrong https://youtu.be/iPvzJz6h1BU

**Comment by hssm** [comment]
It's working as intended. Both the card layout screen and the card browser show two different cards with the expected layout.

In the reviewer, the second card is being [buried](http://ankisrs.net/docs/manual.html#siblings-and-burying) after you answer the first one. The first one appears again because you failed it, so it's in the learning queue (the red numbers).

**Comment by timrae** [comment]
Actually he didn't fail it (see the two dots at the top), it's in the learning queue because it takes two steps to graduate ;)

http://ankisrs.net/docs/manual.html#learning
