### ISSUE TITLE
Move "Cram" bar to top in Review Count/Review Time

### ISSUE THREAD

**Issue by sigkell** [ankidroid/Anki-Android#4277]
In AnkiDroid, the Review Count and Review Time graphs look like this: <http://i.imgur.com/CaQrv9J.jpg>

However on the desktop version of Anki, the "cram" part is at the top: <http://i.imgur.com/z6vMwqc.png>

For consistency, I think it'd be a good idea for the graph to look the same as the desktop version. It's also a lot harder to visually compare regular reviews from day-to-day when it's like this.

**Comment by timrae** [comment]
Can you please just post the images inline into your post  without using Imgur, so we can compare side by side?

**Comment by sigkell** [comment]
Will do in future, but I fail to see how clicking the links prevents you from comparing them.

**Comment by jvanprehn** [comment]
I solved this one here (https://github.com/jvanprehn/Anki-Android/commits/statistics-legend-order), but I haven't made a pull-request yet because I'm not sure if I can do it because there are classes changed both for the not-yet-accepted pull request https://github.com/ankidroid/Anki-Android/pull/4282 and this one.
