### ISSUE TITLE
Suggestion to improve the syncing conflict case

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#4366]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

I really don't know how to reproduce the conflict

###### Expected Result
I have to say this is a most impotant suggestion than I have given ever.Attach importance to this,please.:)  Maybe the system cann't understand fully human.Actually I have try to find the conflict reason many times,but I'm failure.Today I receive this prompt again.I make more than 5000 cards one by one up to now,such error information is a nightmare to me.
![22](https://cloud.githubusercontent.com/assets/10048069/16704288/eff35592-45a7-11e6-8937-e2f871204b22.png)

**My sugestion:**
Please list out all the conflict cards,then the user can give some savior action for the specific cards,not just give a such error information.This make me very panic for these data,because I don't know the error action is result which card.Please,help.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment]
Individual cards don't cause conflicts. If both ends are changed it always chooses the newest version by change time. Conflicts normally arise by changing the *layout of the data*, like adding or removing fields from a note type, or adding or removing card types.

We can't provide more information to the user because the server doesn't tell us which exact thing is not compatible. Even if you did know the cause, there is nothing you can do to "undo" the change that causes it anyway.

We are supposed to show a warning asking you to confirm if you want to make changes that will trigger this state. Maybe we haven't covered all cases (I think the new note type editor might be the culprit).

**Comment by timrae** [comment]
I'm pretty sure we're catching all the cases as I added an exception in
libanki to enforce this. Maybe there will be some clues in the users
collection.log files how they triggered the full sync
On 9 Jul 2016 10:03, "Houssam Salem" <notifications@github.com> wrote:

Closed #4366 <https://github.com/ankidroid/Anki-Android/issues/4366>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4366#event-717671011>,
or mute
the thread
<https://github.com/notifications/unsubscribe/ACsA4m7ekQP7pY2LyqUhRVxZcJEUh05cks5qTvNPgaJpZM4JIfAA>
.

**Comment by hssm** [comment]
Yeah I just checked. It shouldn't be possible.

**Comment by Juddd** [comment]
When I recite my cards,I usually change or add some new thinking in it.But these action rarely cause that conflict error and this my [collection.log](http://note.youdao.com/yws/public/redirect/share?id=98a03af8ff82ed8d648179f71f1fe46a&type=false),maybe can help

**Comment by hssm** [comment]
Your issue is not from a schema change but your card counts are off:
`[1468020256] Syncer.java:sync(): sanity check failed,  {"client":[[30,0,31],5257,5257,32343,1210,7,35,2]},  {"status":"bad","s":[[24,0,31],5257,7,35,2],"c":[[30,0,31],5257,5257,32343,1210,7,35,2]}
`
That definitely shouldn't happen. Do you have a deck with these counts: `30 0 31`? Have you done anything that isn't basic with this deck (like making filtered decks)?

**Comment by Juddd** [comment]
@hssm 

> Do you have a deck with these counts: `30 0 31`?
Sorry my English,I don't understand this sentence.And I have not do these strange thing like filtered deck you mean. :)

**Comment by hssm** [comment]
@dae
Sorry I know you're busy right now but I need some help with this issue.

AnkiWeb is returning with a sanity check error and I'm not sure what to look for to narrow it down.

The [last time](https://github.com/ankidroid/Anki-Android/issues/3574#issuecomment-133625795) we had an issue like this it was a 5 minute gap between requests. This isn't the case this time. Any ideas?

**Comment by dae** [comment]
@Juddd please export your collection with scheduling & without media, and share it here or on help.ankisrs.net - you can make the ticket on there if you don't want the public to see it

**Comment by Juddd** [comment]
@dae  You can get it in [this link](http://note.youdao.com/yws/public/redirect/share?id=657e84f663d4eeebcbfb0cb4fb72c0f9&type=false),And I'll delete this comment after you download it.Hope you solve this issue sincercely.

**Comment by dae** [comment]
Thanks, I was able to download it. It looks like you downloaded from AnkiWeb before you shared the file? If so, unfortunately it is not possible to see why the two sides didn't match. Next time this happens, please don't choose upload or download; choose cancel instead, and then post your collection again here so we can compare it to the ankiweb version. Then please wait until we've had a chance to grab your AnkiWeb collection before syncing again.

(note to self: 807311)

**Comment by Juddd** [comment]
@dae  No. :) actually I used the desktop Anki export that data

**Comment by dae** [comment]
We need a copy of your AnkiDroid data (not the desktop), before you download or upload from/to AnkiWeb. Since it looks like you downloaded the server version into AnkiDroid, we'll need to wait until this happens again.

**Comment by Juddd** [comment]
@dae Sorry cann't get the keypoint before this.I'll do it as you teach next time.

**Comment by dae** [comment]
No problem, we'll wait to hear from you.

**Comment by Juddd** [comment]
@dae Help.The problem appear again...

**Comment by dae** [comment]
Did you cancel the full sync this time? If so, please export your collection from AnkiDroid without media, and attach it to a private ticket on help.ankisrs.net, and I'll compare it to AnkiWeb.

**Comment by Juddd** [comment]
@dae Yes,I get this pop information [like this](http://o8aucf9ny.bkt.clouddn.com/2016-11-02-11-58-18.png).Then I click the <kbd>CANCAL</kbd>.

**Comment by Juddd** [comment]
Do you mean I should export collection from my **Android AnkiDroid** without media?

**Comment by dae** [comment]
yes

**Comment by Juddd** [comment]
@dae I have opened a disscuss,and the topic is " About the syncing conflict case #4366"

**Comment by Juddd** [comment]
@dae  I hope when we meet the syncing conflict the pop-up prompts tell me **which on earth card lead to this**.

**Comment by dae** [comment]
Judd: this looks like an AnkiDroid bug. 

Devs:

- AnkiDroid started a sync but the connection timed out after the sync/start call
- The subsequent sync failed the sanity check
- When I compare the collection from Judd's device and AnkiWeb, they both have the same USN. A number of cards have that USN, but they were not sent during the subsequent sync because AD having that USN implies it has already saved them in a previous successful sync.

I suspect something has caused AD to accidentally update the USN despite the previous sync timing out, instead of rolling the DB back to the pre-sync state.

**Comment by Juddd** [comment]
@dae What I should I do now?And How to know I will lost which card when I sync in my Android?

**Comment by dae** [comment]
since your AD collection seems to be in an inconsistent state I'd recommend choosing download in AD, though please note you will lose any changes you did in AD since the last sync

**Comment by Juddd** [comment]
@dae I hope the anki will tell me which card will be lose or change when the conflict appear.This wish can be achieved?

**Comment by dae** [comment]
The conflict should not happen at all - it is a bug that should be fixed.

**Comment by hssm** [comment]
Thanks for looking into it Damien.

It might be a while before I can figure this one out. We are definitely rolling back the DB on sync failures. If I had to guess, we're probably swallowing an exception on timeouts. It's hard to tell until I can reproduce it which doesn't seem simple.
