### ISSUE TITLE
Study Options: Handle RTL Number Display

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4371]
Hi
In Persian language and Arabic we write from the right side of any pages contrary to English So when I open my deck and wanna see >>> due today or total new cards or estimated time there is a malfunction 
Numbers should be at the left side while they are in right one
Thanks

**Comment by hssm** [comment]
Can you post an image or screenshot to explain what it should look like?

**Comment by lahootian313** [comment]
Hi 
Sir I don't know how to send screenshot to this site
Please change your ankidroid app's language into Persian and open a deck ;I mean open it so that u can see due card today or estimated time and so on 
In this page numbers should be at the left side exactly in front of this sign :
While they are not 
Thank u again

**Comment by eginhard** [comment]
I think that's the overview statistics in the deck options screen. It
should be relatively straightforward to make it support RTL layouts, but
unfortunately I don't have the time to look into in right now.

**Comment by lahootian313** [comment]
Hi
I mean in that page that u can see spanner not deck options

**Comment by lahootian313** [comment]
![screenshot_20160826-205627](https://cloud.githubusercontent.com/assets/14838633/18012655/c54a2c32-6bcf-11e6-95bc-44b016fde6d2.png)

**Comment by stu40** [comment]
Hi,
I'm learning Farsi, and just wanted to clarify something that isn't well explained in this issue. Though Arabic and Farsi are right-to-left languages (RTL), their **numbers** are written in the same direction as English, as demonstrated below -

۱۲ + ۱ = ۱۳
which says 12 + 1 = 13.

So the poster of this issue is just saying the deck overview screen would flow naturally if the statistics on how many cards are due etc. were at the end of the RTL line ie. the far left. Of course this would mean an app designed for a left-to-right language would have to be completely redesigned to reverse the order of labels and their output to be RTL. This isn't practical.

I think you can close this issue unless you are planning on improving the reading layout of Ankidroid for RTL languages. Having said that, if you remove the colon from the end of the statistic label, it would no longer imply the statistic is following at the end of the line - this is the only practical resolution I can think of for this issue. 

![deck overview](https://cloud.githubusercontent.com/assets/25576046/22634721/15b33376-ec81-11e6-8e63-9ca84d1d02c6.png)

**Comment by rillig** [comment]
[This blog post](https://android-developers.googleblog.com/2013/03/native-rtl-support-in-android-42.html) sounds as if it weren't too difficult.

**Comment by david-allison-1** [comment]
I'll take this on if it's not seen within the next 2 months.

**Comment by david-allison-1** [comment]
Could be done with a custom RTL Layout, modifying the existing layout doesn't seem feasible

**Comment by prosperian** [comment]
Hi, i can read and write in Persian and i can work on this if it's still an issue?

**Comment by david-allison-1** [comment]
@prosperian Thanks!!

We've just merged a large RTL change in the latest alpha, any feedback (and getting this issue sorted, if it's still an issue) would be fantastic.

**Comment by prosperian** [comment]
Okay, i will check this out

**Comment by prosperian** [comment]
<details>
<summary>These changes should be made</summary>
<img src="https://user-images.githubusercontent.com/25820674/112961468-a5d1b400-915a-11eb-9e45-39d5c50795f3.jpg">
<img src="https://user-images.githubusercontent.com/25820674/112961713-dfa2ba80-915a-11eb-9e0e-367989dd3914.jpg">
</details>

<details>
<summary>No translation for this dialog</summary>
<img src="https://user-images.githubusercontent.com/25820674/112962089-3f00ca80-915b-11eb-892f-9e28524db5a0.png">
</details>

**Comment by david-allison-1** [comment]
Perfect, thanks!

Let's handle the night mode toggle in a separate PR than the study screen

**Comment by eginhard** [comment]
It doesn't look like you're using the latest alpha version (2.15alpha36), see the manual for how to get it: https://docs.ankidroid.org/#betaTesting

Both the study options screen and that toggle were fixed by #8261 (see screenshot below). Have a look at #8259 for other RTL-related issues.
![nav-drawer](https://user-images.githubusercontent.com/5216613/112990743-ac662880-9166-11eb-89af-2a357049c6e8.png)

**Comment by prosperian** [comment]
Thanks @eginhard, but i run the app from github repository on android studio, is there anyway that would be able to have the latest test version that way?
