### ISSUE TITLE
How can I get the same image replay button icon between Anki computer and Ankidroid

### ISSUE THREAD

**Issue by limitted** [ankidroid/Anki-Android#4394]
I try to change replay button image.png in add on folder of my computer but when play in the Ankidroid it not the same as my computer 
Also i try to change  _inline_replay_button.png but it still problem
in collection.media folder.
Could everybody suggest me how to correct it , Thank you
picture show problem below
https://www.dropbox.com/s/5jtdgqz5yt5ckaa/pictue.jpg?dl=0

**Comment by hssm** [comment]
Desktop add-ons have no effect on mobile platforms.

There is no external resource available for you to change on AnkiDroid. You will have to swap it out using javascript or css, targeting the `replaybutton` class.

**Comment by limitted** [comment]
Could you suggest me how to edit the replay button by using the css , some of my deck that use the default black color Thank you

**Comment by timrae** [comment]
Another option is to replace the icon used in the desktop plugin with the
AnkiDroid one, then they'll at least be consistent.

On 31 Jul 2016 13:09, "limitted" <notifications@github.com> wrote:

Could you suggest me how to edit the replay button by using the css , some
of my deck that use the default black color Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4394#issuecomment-236408479>,
or mute the thread

**Comment by hssm** [comment]
I'm actually trying to find a fix for this problem. As a workaround for now, you can add this to the `styling` section of your template:

```
.replaybutton span svg {
  fill: #55f !important;
}
```

Or, if you set AnkiDroid to use night mode, the button will appear white.

**Comment by limitted** [comment]
.replaybutton span svg {
  fill: #55f !important;
}

What does this code effect for?

**Comment by hssm** [comment]
Given that we just had a discussion about the color of the playback button, I would have thought that is was obvious it was about the color of the playback button...

**Comment by limitted** [comment]
Thank you for your help , I got it  for one question could i change the
shape of background playback button.

**Comment by hssm** [comment]
You can probably do it with javascript, targeting the same `.replaybutton span svg` element. You're on your own with figuring that out.

**Comment by limitted** [comment]
Thankyou verymuch
