### ISSUE TITLE
[feature request] add on to onenote

### ISSUE THREAD

**Issue by DonCN** [ankidroid/Anki-Android#4408]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I have many note save in Microsoft's onenote, I want to repeating some of pages of the notes. I think if it is possible to make an add on to onenote, and users can chose some of the notes to anki to for repeating.
2. Each day anki give the links of the note that need to repeat.
3. thank you for you excelent software!

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
AnkiDroid provides an [API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API) which will probably suit your use case, so you're welcome to develop such an addon or ask other OneNote users or plugin developers to do so. Feel free to ask in the AnkiDroid group if you have specific questions about using the API, but you probably won't find AnkiDroid developers to implement such an addon because this is not related to the app itself.
