### ISSUE TITLE
Google Spreadsheets Continous Sync Feature Request

### ISSUE THREAD

**Issue by gwpl** [ankidroid/Anki-Android#4418]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Feature request
 I have some sheets, containing columns that could be used as Fronts and Backs of cards, sometimes two others that could serve as Deck name and tags.
(E.g. one produced by Google Forms, 
 spreadsheet (which is btw. output of Google Forms) which has multiple columns including two "Front" and "Back" and other two with tags and Deck name.

I have also Googlen Translate exporting  starred translations i.e. phrasebook to another Google Spreadsheet)

I'd love to not only import once those (e.g. on pc via csv export), but to allow AnkiDroid to access Drive for continous syncing! So when new rows appear, to add cards. When I edit rows, to also update related cards (or at least add new ones woth new concent and somehow tag/mark old onces as "deprecated").

Thos of cpurse could be also implemented ln ankiweb side, but also AnkiDroid.
This would hihly help me manage my decs I have originally in spreadsheets of different forms.

**Comment by timrae** [comment]
This probably isn't something we'd merge into the main app, but it should be possible to write an app to do it by making use of the [API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API)

**Comment by iltempovola** [comment]
I was looking for th same feature and I couldn't find any tool. But I found this add-on that does it from a Google Doc instead of Google Sheets: https://ankiweb.net/shared/info/911568091

Now I'll try to automatically replicate my google sheet into a google doc, so that in two clicks I can  have the same effect. Let's see if it works well. 

FYI, many other people were lookig to use google sheet  as well (https://www.reddit.com/r/Anki/comments/c9xehw/auto_sync_google_sheet_with_anki_flashcard_deck/) but it seems that 
nobody developed anything dedicated yet. Let us know if you find anything else.
