### ISSUE TITLE
Review Ceiling

### ISSUE THREAD

**Issue by tttdribble** [ankidroid/Anki-Android#4442]
Ankidroid is not handeling the Review Ceiling correctly.

Example: There are 500 Cards to be reviewed. The user caps this to 50 Cards per day. The user reviews these 50 cards, he knows them, and all of them should reappear the next day because he clicked on "Good" and it was set to 1 day. BUT the 50 cards do not reappear, instead all other 450 cards appear before the 50 cards during the next few days 

This is a huge issue for the learning process. I say that the last reviewed card must have priority over the cards that are untouched for weeks or months. (They only appear first because Ankidroid is only checking the Due date of the cards)

So if you would wan't to see the 50 cards again, you would need to turn off the Ceiling and click through every card that needs to be reviewed. I believe this is not the purpose of such a ceiling...

Please review this as soon as possible because it's an actual flaw

**Comment by tttdribble** [comment]
The learning-progress is being diminished by this tremendously - I really hope you can solve this in the next release

**Comment by eginhard** [comment]
That is the expected behaviour and Anki Desktop does the same. By default, cards are displayed in the order they are due and the remaining 450 cards are therefore scheduled to be reviewed first. In order to see the 50 cards first, you'll need to use a filtered deck that includes only cards that became due recently. See this part in the manual for specific instructions: http://ankisrs.net/docs/manual.html#catching-up

In general, if you have any comments or suggestions related to scheduling, you should use the main Anki forum because AnkiDroid just implements the same scheduling algorithm: https://anki.tenderapp.com/discussions
