### ISSUE TITLE
How to make donation ?

### ISSUE THREAD

**Issue by OoDeLally** [ankidroid/Anki-Android#4460]
###### Research
[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[X] I have searched for similar existing issues here and on the user forum

I'm using the app a lot to learn Czech vocabulary.
Is there a way to donate to Anki organization?

Thank you

**Comment by eginhard** [comment]
First of all, as you may know AnkiDroid is a project independent from Anki. We don't really have any ongoing costs that require donations. [Bounties](https://www.google.com/url?q=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FOpen-source_bounty&sa=D&sntz=1&usg=AFQjCNFdUmtmA3g8rD6y4cEACTQEi3kQ-w) would be appreciated though if there are specific features that you want.

Currently the only way to directly support the Anki project financially is to purchase Anki Mobile for iOS (even if you don't intend to use it): http://ankisrs.net/support/

Otherwise, some ways to contribute to AnkiDroid are listed in the manual: https://ankidroid.org/docs/manual.html#contributing

**Comment by thoral** [comment]
Now it's possible to make a donation! Good idea!

 https://opencollective.com/ankidroid

**Comment by mikehardy** [comment]
Indeed! It took us a while to set up because nothing like OpenCollective existed before.
It is important to note that I asked the previous maintainers that I have contact with for their opinions, as well as current contributors and worked really hard to come up with something that we hope will be peaceful fair and sustainable for contributors here.

And whether it is any of those things or not, it is 100% transparent (thanks to OpenCollective) so you can judge for yourself how we do :smile: 

We have been extremely touched by the support of the community since we put up the donation site, and with our planned style it looks like we are sustainable for at least a year, which is fantastic

Cheers

**Comment by OoDeLally** [comment]
Yep, I've made a donation 🤗 Thanks for setting this up!
