### ISSUE TITLE
Option to bias "Center align"

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#4470]
Currently, if I

* set "Center align" the bottom content of my cards is commonly covered by the keyboard once activated (Google Handwriting is esp. huge)

* don't set "Center align" the content has both its top parts hidden behind Anki's top bar once a keyboard activates and is (ofc) too far up.

Thus as a compromise I'd like to ask for an option to bias "Center align". Eg, select a value between -50% and 50% (of app height), with negative values pushing the center up and positive ones pushing it down.

**Comment by eginhard** [comment]
That option is mainly there as a simple workaround to using custom CSS on your card templates because center alignment used to be done by default. If you need something different from the provided behaviours, you can add your own CSS. See the Anki Desktop manual: http://ankisrs.net/docs/manual.html#card-styling
