### ISSUE TITLE
Text to speech is not available when I enable night mode

### ISSUE THREAD

**Issue by alireza001** [ankidroid/Anki-Android#4508]
###### Reproduction Steps

1. X
2. X
3. X

**Comment by eginhard** [comment]
Could you please provide details on your device and Android version and explain the steps that will reproduce the problem?

For me, TTS works fine in both day and night mode. Make sure that you have "Automatically play audio" enabled in the deck you're using or otherwise play it via "Replay Audio". You might also have disabled TTS for certain decks, so also try resetting the TTS languages.
