### ISSUE TITLE
Can't change deck for all cards of a note when editing it from the browser

### ISSUE THREAD

**Issue by Alphalpha007** [ankidroid/Anki-Android#4532]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Create a reversed note card in Deck A
2. Edit the note from the card browser and change its deck to Deck B

###### Expected Result

Both the cards of the note should change to Deck A

###### Actual Result

Only one card changes decks

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
It's the same in Anki Desktop and intentional, see: https://anki.tenderapp.com/discussions/ankidesktop/12784-bug-changing-deck-for-one-card-does-not-change-deck-for-whole-note

Note also that it says "Card deck" when editing a card from the browser, instead of "Deck" otherwise. But this indeed leaves the problem that unlike in Anki Desktop there is (I think) no convenient way to change the deck for the whole note from the browser. We could wait for #2339 and then do it like Anki Desktop.

**Comment by mikehardy** [comment]
#2339 is done - I think the way to do this is just to use the browser now and multiselect, it's out in 2.9alpha24 I think (and we are at 2.9alph42 now - stabilizing nicely)
