### ISSUE TITLE
Blackberry devices are unable to sync

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#4536]
AnkiWeb's SSL certificate was updated on the 7th, and it appears to have broken syncing on Blackberry devices. Users are able to access ankiweb.net in their device's browser, but connections within AnkiDroid time out. There don't appear to be any errors in the server logs, so I'm not sure whether any connections are being attempted. Might be worth turning off certificate validation on these devices to see if it helps?

Related reports:
https://github.com/ankidroid/Anki-Android/issues/4533
https://anki.tenderapp.com/discussions/ankiweb/1919-a-network-error-has-occurred

**Comment by finalion** [comment]
the same. blackberry passport

**Comment by timrae** [comment]
> AnkiWeb's SSL certificate was updated on the 7th, and it appears to have broken syncing on Blackberry devices.

Do you have any idea why?

> Might be worth turning off certificate validation on these devices to see if it helps?

It would be good to know the reason why first. I'm a bit uncomfortable about putting such a hack into a major release, unless that's really the only option. Also, it's unlikely that I'll personally have time to work on that.

**Comment by dae** [comment]
Hi Tim,

I'm not sure what you're asking. Why did we update the SSL certificate? Because the certificates need to be updated periodically and need to match the front end servers. Why did it break on Blackberry devices? The certificates are valid and work on other devices and platforms, so it is presumably a Blackberry OS bug. You and the other AnkiDroid developers are free to do with this report as you please, I am simply giving you a heads up.

**Comment by timrae** [comment]
Yes I meant do you have any idea why blackberry devices were happy with the old certificate but not with the new one? What changed?

**Comment by dae** [comment]
I can only hypothesise as to why it is not working. Perhaps it's getting confused that the subject name does not match 'ankiweb.net', which should not be a problem as ankiweb.net is listed as a subject alternative name - the link I posted in the tenderapp discussion above seems to indicate Blackberry has had some issues with SANs.

**Comment by dae** [comment]
finalion: I've added an extra certificate to AnkiWeb,  which may or may not work around this issue with bbOS - could you please try sync again and report back on whether it works or not?

**Comment by finalion** [comment]
It still doesn't work.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Damien ElmesSent: Saturday, January 14, 2017 09:29To: ankidroid/Anki-AndroidReply To: ankidroid/Anki-AndroidCc: finalion; CommentSubject: Re: [ankidroid/Anki-Android] Blackberry devices are unable to sync (#4536)finalion: I've added an extra certificate to AnkiWeb,  which may or may not work around this issue with bbOS - could you please try sync again and report back on whether it works or not?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ankidroid/Anki-Android","title":"ankidroid/Anki-Android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ankidroid/Anki-Android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dae in #4536: finalion: I've added an extra certificate to AnkiWeb,  which may or may not work around this issue with bbOS - could you please try sync again and report back on whether it works or not?"}],"action":{"name":"View Issue","url":"https://github.com/ankidroid/Anki-Android/issues/4536#issuecomment-272607988"}}}

**Comment by dae** [comment]
That's unfortunate :-( I'm afraid I'm not sure what else I can do from my end to work around this issue.

**Comment by timrae** [comment]
Did someone contact BlackBerry tech support?

**Comment by timrae** [comment]
The best we could do from our end is try to temporarily make a build that
users can optionally download with certificate verification disabled. It's
not a permanent solution though, BlackBerry need to push a fix or instruct
users how to solve the issue.

**Comment by benbassist** [comment]
Sadly not working here still. But thank you for your efforts so far.

**Comment by vintotal** [comment]
It is not working on Blackberry Z30 with the latest OS. I tried with an older version (2.4.2), still unable to synchronise.

**Comment by pheochromocytoma** [comment]
Please fix this, using BlackBerry Passport and AnkiDroid version 2.8.

**Comment by timrae** [comment]
Currently we require a user to contact Blackberry technical support and have them make a statement on whether it's a bug on their end, and instruct us on any necessary workarounds. I suspect it is indeed a bug on their end as it only occurs on Blackberries.

Posting here saying "same problem" isn't going to help; you all need to contact Blackberry.

**Comment by vintotal** [comment]
https://supportforums.blackberry.com/t5/BlackBerry-10-Functions-and/Ankidroid-not-working-ne-fonctionne-pas/td-p/3208106

**Comment by benbassist** [comment]
Thanks for posting on the BlackBerry support forum vintotal. It appears maybe not to be just a BlackBerry problem, as a Samsung user has responded to my original issue report.

**Comment by dae** [comment]
No, it's more likely the user has just had trouble logging in and assumed it's the same issue - if it were the same issue it would not behave differently when their password was wrong.

**Comment by benbassist** [comment]
> No, it's more likely the user has just had trouble logging in and assumed it's the same issue - if it were the same issue it would not behave differently when their password was wrong.

I see, I get the network error message even if i put in the wrong password. I thought at some point when I tried with the wrong password it had been recognised it was wrong.

**Comment by dae** [comment]
Ok, you guys may be in luck. Due to other issues with the CDN we were using, I've had to move parts of AnkiWeb back to the old infrastructure, and I suspect this will also have the side effect of allowing you to sync again. Please give syncing a try again and let us know how you go.

**Comment by vintotal** [comment]
Your anticipation was correct.  I am now able to synchronise using the latest AnkiDroid version. Merci. :-) ありがとうございます。謝謝。

**Comment by benbassist** [comment]
I can confirm Anki now syncs again. Thanks for letting us know.

**Comment by dae** [comment]
ok, glad to hear :-)

**Comment by pheochromocytoma** [comment]
Happy to report that AnkiDroid sync issue has been resolved for BlackBerry!
