### ISSUE TITLE
SecurityException: Permission not granted for: CardContentProvider.query /decks 

### ISSUE THREAD

**Issue by mvysny** [ankidroid/Anki-Android#4544]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. This is actually hard to reproduce as this occurs on one user phone only. For example I couldn't reproduce the issue.

###### Expected Result

Export to AnkiDroid from Aedict3 works

###### Actual Result

For unknown reason the export crashes with the following exception: https://github.com/mvysny/aedict/issues/689
I have double-checked and Aedict3 asks for the necessary permission upon install time:
The AndroidManifest.xml lists the permission:
    <uses-permission android:name="com.ichi2.anki.permission.READ_WRITE_DATABASE"/>

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

This needs to be provided by the user as I unfortunately cannot reproduce the issue.

**Comment by Jpcomben** [comment]
I am the user with the issue. Thanks for looking into this. Details as follows... 

I am using the latest version of aedict. My phone make is Nexus 5, running stock android 6.0.1. No custom roms. 

My debug info is... 

AnkiDroid Version = 2.7

Android Version = 6.0.1

ACRA UUID = 2d50cc2b-17e5-46e3-b1ad-f8aca3bc6d8a

Thanks, 

James

**Comment by timrae** [comment]
Please go to settings, apps, aedict, permissions, and check that the "read and write to the AnkiDroid database" permission is enabled.

**Comment by Jpcomben** [comment]
Hi Tim

Neither the permissions are enabled in either Ankidroid or Aedict. I guess
this is the problem.

However, I tried to enable both but it doesn't seem to take effect. Every
time I go back into the settings menu the permission has reset to the left
'off' position.

Thanks,

James

**Comment by timrae** [comment]
Hmm OK it sounds like a problem with your device, I'm not sure there's anything we can do sorry. You can try searching for similar bugs on the Android bug tracker, rebooting, reinstalling, factory resetting, etc...

**Comment by mvysny** [comment]
Thank you Tim for handling this. I completely forgot that Android app permissions may be revoked by the user.

**Comment by nake90** [comment]
@Jpcomben Did you find a solution? I have exactly the same problem and I can't find anything related. AFAIK this problem only happens with the custom permission for ankidroid database, that for some reason can't get enabled.

I am using android 7.1 (x86) with Lineage OS.

**Comment by Jpcomben** [comment]
Hi Alfonso,

Yes it now works for me alright. Somehow the permission got reset and it
was turned off. There is a setting in android settings/apps/Aedict for
storage permission and then a further permission for writing to anki and
that was the one that was causing my issue.

I hope you can get it resolved.

On 1 Sep 2017 1:38 pm, "Alfonso Arbona Gimeno" <notifications@github.com>
wrote:

@Jpcomben <https://github.com/jpcomben> Did you find a solution? I have
exactly the same problem and I can't find anything related. AFAIK this
problem only happens with the custom permission for ankidroid database,
that for some reason can't get enabled.

I am using android 7.1 (x86) with Lineage OS.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4544#issuecomment-326485294>,
or mute the thread

**Comment by nake90** [comment]
Thanks for the fast reply @Jpcomben and sorry for bothering you with this again.

Do you recall updating or reinstalling or doing something like that? My problem is that the permission gets reset the same way as it did to you so anything you remember that you did would really help me a lot.

Thanks a lot for the help.

**Comment by kuukunen** [comment]
I wrote about my findings about the permission issues on the Aedict bug tracker and figured this issue might benefit from it too.

Short version: If Aedict export doesn't work because of permissions (either crash or does nothing), it might work if you uninstall Aedict and reinstall it. (Make sure Aedict is always installed after AnkiDroid.)

https://github.com/mvysny/aedict/issues/794

**Comment by nake90** [comment]
Thank you very much! It fixed it!
