### ISSUE TITLE
Investigate switching from acra to countly

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4551]
https://github.com/Countly/countly-sdk-android

> **What's Countly?**
> Countly is an innovative, real-time, open source mobile analytics application. It collects data from mobile devices, and visualizes this information to analyze mobile application usage and end-user behavior. There are two parts of Countly: the server that collects and analyzes data, and mobile SDK that sends this data. Both parts are open source with different licensing terms.

**Comment by mikehardy** [comment]
I just saw this and it's only free if self-hosted (requires a machine somewhere - Ubuntu). I'm unsure how acralyzer is paid for but it's at least working now (free?) and google analytics will be free as well. Not sure if this is worth the switch?

**Comment by timrae** [comment]
Acralyzer is self hosted on an Ubuntu machine :p does Google analytics handle crash reports??

**Comment by mikehardy** [comment]
I doubt it, but it is pretty powerful and (theoretically) a trivial integration conceptually. If we already have self-hosting there is also acrarium (think of it as acralyzer v2, by current acra maintainer). I'm not keen on moving this just now though, even if that's sunk-cost reasoning on my current acra knowledge...

**Comment by mikehardy** [comment]
possibly worth noting that F43nd1r has so far been ridiculously professional so "early development stage" for acrarium likely means "does everything acralyzer did, but well"

**Comment by mikehardy** [comment]
I don't see a reason to switch personally after experiencing the very solid maintenance on ACRA in general and the fact acralyzer on our self-hosted droplet (docs.ankidroid.org server) working "okay" and the only options I'm aware of require self-hosting since cloud hosting providers all charge. In my experience switching from one self-hosted system to another typically provides no clear benefit, just a new set of quirks to learn and manage. The only time I'd change this is just to a fresh install of something maintained (acrarium) whenever we need to finally upgrade the docs.ankidroid.org server
