### ISSUE TITLE
[Bug]Copy&Past Problem by editig card layout

### ISSUE THREAD

**Issue by TxBase** [ankidroid/Anki-Android#4554]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. go to manage note type 
2. edit card of a note
3. select something to copy

###### Expected Result
select all/cut/copy/paste bar shouldn't be hidden

###### Actual Result
select all/cut/copy/paste bar moved out of the screen, when the keyboard poped up.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.7

Android Version = 5.0.1

ACRA UUID = 3f7b285e-03a3-44e0-9117-7758531e63da

**Comment by timrae** [comment]
Can you post a screenshot?

**Comment by Two-Finger** [comment]
Here are some screenshots, I believe it's the same issue @TxBase is talking about.
It only happens when the edited text field is lower than the top border of the keyboard.
If it's higher, it works fine (first screenshot)

![screenshot_2017-02-03-09-08-35](https://cloud.githubusercontent.com/assets/3533666/22582655/b8e93cfe-e9f0-11e6-8e4a-cf455432a3e4.png)
![screenshot_2017-02-03-09-09-22](https://cloud.githubusercontent.com/assets/3533666/22582658/c1fcc1c6-e9f0-11e6-84b3-7388056fbeeb.png)
![screenshot_2017-02-03-09-09-45](https://cloud.githubusercontent.com/assets/3533666/22582667/cc455166-e9f0-11e6-81a1-f56179d4e599.png)

**Comment by snowtimeglass** [comment]
This bug is reproduced on my device, too.

Android 4.3
AnkiDroid 2.8.2beta3
