### ISSUE TITLE
Feature Request - Show least overdue learning card first

### ISSUE THREAD

**Issue by Enkidu6** [ankidroid/Anki-Android#4614]
I'm so happy with the results of an addon I made for Anki Desktop for my study - https://ankiweb.net/shared/info/11767883
It shows the least overdue learning cards first, which is the opposite to the normal behaviour. This is done because when I mark a card "again", I don't want to see it in 2 minutes or 30 seconds, I want to see it in 3 seconds, or I'll forget it, so I need to ensure old "learning" cards don't pop up before it.
I love this change to my study so much, I've been prefering the desktop app over the android, it would be great if I could have the desktop app on my phone.  Or even better, can I somehow change the code and have in Ankidroid?

**Comment by timrae** [comment]
> it would be great if I could have the desktop app on my phone

As far as I know, that would be impossible as the desktop app is written with python and QT which are not supported on Android.

> can I somehow change the code and have in Ankidroid?

If you're asking whether or not you can change the AnkiDroid source code, then yes obviously AnkiDroid is open source, see the instructions [here](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide) for help with that. You can build your own custom version of AnkiDroid which you install and run on your phone.

If you're asking whether we would consider merging this feature into the main repository so that it's released into the main app on google play store, then no, probably not... We basically only add features like this if they are added into the main desktop app (i.e. not as an add-on).

Running your own custom version of AnkiDroid is probably the easiest way to proceed, and there are several users that do this, but it requires a bit of continual maintenance on your part if you want to bring in the latest changes when we release a new version.
