### ISSUE TITLE
Night Mode image invert colors Android 4.1.2

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#4626]
Hi everyone,

I have the following question, is it possible to invert the colors of an image (specifically a gif) when Night Mode is activated in an Android 4.1.2?

I've seen the Advanced Formatting but it clearly states that works for versions 4.4+...is there a workaround for my version?

Thank you all in advance and best regards.

Saul Cuen

**Comment by timrae** [comment]
This is answered in the wiki on the advanced formatting page

**Comment by timrae** [comment]
I should really try not to answer questions here when I first wake up...

You might be able to pre process the images on your PC with gimp or something. Feel free to ask on the forum for help, but this isn't a feature we would consider adding to AnkiDroid since Android 4.4 has been out for years now.
