### ISSUE TITLE
Audio won't play automatically on droid app

### ISSUE THREAD

**Issue by anki2017** [ankidroid/Anki-Android#4647]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. ?
2. 
3. 

###### Expected Result
For audio to play 

###### Actual Result
No audio plays...

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by anki2017** [comment]
New to all of this. I am sorry if I didn't provide enough details.

**Comment by eginhard** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

**Comment by anki2017** [comment]
I tried all of that and nothing worked...

**Comment by timrae** [comment]
Hi, please show the details of each step that you have taken from the guide in the FAQ (ideally with screenshots to backup your words). When media doesn't play, 99.9% of the time it's due to user error, so we can only accept a bug report related to media not playing if you give us a report with very detailed instructions for reproduction.
