### ISSUE TITLE
Feature Request: Additional card Fields

### ISSUE THREAD

**Issue by popo63301** [ankidroid/Anki-Android#4676]
Would it be possible to add this plugin to the app?: https://ankiweb.net/shared/info/441235634

Especially "{{info::Reviews}} - the amount of reviews that you had on a card". 

Thanks in advance ! :D

**Comment by adlew44** [comment]
I would also find this very useful, and have given it a thumbs up. I feel sure that sometimes cards appear weeks or months before they are due; I have no objection to that, but I'd like to know when it happens, so the ability to add relevant special fields to cards would be welcome.

**Comment by mikehardy** [comment]
This is the sort of thing that could likely fit into the "hooks" architecture:

https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/java/com/ichi2/libanki/hooks

You'd want to enter a CardInfo hook for the "mungeQA" hook (I belive), that scanned for `{{info::` and replaced it with info it looked up. The hook would be passed all it needs in order to lookup info the "args" Object array, this function is where it is called so you can see the args content:
https://github.com/mikehardy/Anki-Android/blob/1187dddac916f75d952bdb683931df489fcef985/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1055

An example is here:
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/hooks/HebrewFixFilter.java

This is a plugin on desktop, so would not normally make it in to the codebase for AnkiDroid, but we do have a hook infrastructure already and there's no other way to do plugins during review. So if someone proposed a clean PR for this, it could work.

**Comment by david-allison-1** [comment]
Let's keep this open for a little bit. 

@infinyte7 - pinging for informational purposes, as this is very close to the area you're working in

**Comment by infinyte7** [comment]
Next weekend I will into this.

**Comment by david-allison-1** [comment]
No rush or action intended if you don't want to, but thanks!!

**Comment by infinyte7** [comment]
I looked into it. But is there any information stored for particular cards info (eg. reviews). The information stored that when it will appear next for reviewing. But for count number of reviews for particular cards, where to look/add code?

**Comment by david-allison-1** [comment]
Yeah, card.reps is already available on the `card` object.
