### ISSUE TITLE
AnkiDroid ignores language setting in multi-window mode

### ISSUE THREAD

**Issue by 5hir0kur0** [ankidroid/Anki-Android#4700]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Set AnkiDroid's UI language to something other than the system language.
2. Put Android into multi-window mode (long-press on the multitasking button on my system). 
3. Observe how some texts change language (e.g. the text in the top bar).

###### Expected Result
The UI language should not change when AnkiDroid is in multi-window mode.

###### Actual Result
The UI language changes when AnkiDroid is in multi-window mode.
(Only some texts (e.g. the text in the top bar) change,
but not others like the text at the bottom ("Studied X cards in Y minutes today"))
When AnkiDroid is put back into single-window mode,
only some texts change back to the correct language.
In my case, this lead to the buttons that are shown on the bottom of the screen during review being displayed in different languages.

Screenshot taken after switching to multi-window mode and back to single-window mode again:
![screenshot_20170909-102805](https://user-images.githubusercontent.com/12101162/30238683-ea0ae5e2-954b-11e7-9b47-651d7064d44b.jpg)

(As you can see, some parts of the UI are Japanese (system language) and some are English (language set in AnkiDroid settings).)

###### Debug info
AnkiDroid Version = 2.8.2

Android Version = 7.1.1

ACRA UUID = 0f58280d-a332-42b1-9a3b-57bf6088835e

**Comment by mikehardy** [comment]
I only just saw this specific issue as I wasn't looking at AnkiDroid code in September, but a more recent issue came in  - #4729 - and I did some research there since there appears to be a general problem related to non-system languages in Anki in Android versions with API 23+ (Android 7.1+)

I think 4729 covers everything mentioned here except the multi-window-specific part. If we resolve this as a duplicate and put a note to test multi-window non-system GUI languages in 4729 then that issue would cover the entire problem and we could track everything there?

**Comment by 5hir0kur0** [comment]
Yes, that would be fine.

I'm not really affected by this issue anyway;
I only reported it, because I thought it might be caused by a more general underlying problem.

**Comment by 5hir0kur0** [comment]
Duplicate of #4729.
