### ISSUE TITLE
New feature "Display a card on Screen unlock"

### ISSUE THREAD

**Issue by rafenciugo** [ankidroid/Anki-Android#4709]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

I would like to propose a new functionality that could significantly help AnkiDroid users to boost their learning process. 

Problem: 
Right now, to study cards, it is necessary to start a learning session manually. That means that a user has to find time to do it and be motivated. It is much more difficult to motivate children to work with AnkiDroid although they use mobile phones all the time.

Solution:
Imagine that it is possible in AnkiDroid to enable a feature "Display a card on Screen unlock". If enabled, every time when a user unlocks a screen of his mobile phone a single card is displayed. The user can answer the question in the same way that he does it in AnkiDroid, and continue doing what he was supposed to do with his phone.  Or, if he needs to use his phone urgently, uses an additional button "Abandon" or a main button of the phone that minimalizes all the applications. In that case, a card disappears but remains unanswered, and the user can use his phone. The card is displayed on the next screen unlock or in the standard AnkiDroid session if the user decides to do it.

Now imagine how many times, during a single day, you unlock your phone. At least 50 or more, could be 100. Using a "Display a card on Screen unlock" feature:
-  you could have completed your AnkiDroid reviews without doing a dedicated session
- you could have a continuous contact with your cards. Especially valuable while learning languages.
- you could involve your children, make them answer the questions (cards) without too much effort

I have done an experiment myself, turning on AnkiDroid manually on every screen unlock during two weeks. The results are incredible. I have caught up with all my outstanding cards and have done an impressive progress, without spending a minute in dedicated sessions. Turning AnkiDroid every time manually was a pain in the a..., but the "Display a card on Screen unlock" feature would be a gift.

The next step could be implementing a feature "Display a card on Starting an application". This could work in the same way as described above but the cards would be displayed when the user starts some (configured) applications. For instance, a child starts his favorite game or youtube, before he can use it, a single card is displayed.

I would appreciate it if a person responsible for AnkiDroid backlog management could consider adding this feature to that backlog. 

I am ready to provide a very detailed description of this new and powerful feature "Display a card on Screen unlock". I could also engage as a tester.

**Comment by jozefwczasy** [comment]
Hi rafenciugo,

I work in management, most of the time on the phone and half of the day on the underground. Unlocking the phone and at the same time clearing back log of Anki cards? Genius! Beautiful! What else does one need...? How much time a day do you guys spend on the phone (tablet) a day? I think it is an excellent idea!

**Comment by rafenciugo** [comment]
Hi Josef, thank you very much for your comment and confirmation that the idea described above (displaying a single card on screen unlock) would also work in your case and would accelerate your learning process.  I have talked to some Anki users after publishing the description above, they are really looking forward to contributing, mainly in the terms of testing, because they are not programmers. 

BTW, guys, how many times a day do you unlock your phone? I do it about 100 times. At the beginning, I thought I was an addict but now I know that it is not that many. Normally people do more.  How about you?

Kind regards, R.

**Comment by lucwastiaux** [comment]
This is an awesome idea. Want to waste some time at your phone ? have to pay for it with some reviews first ! With a circumvention mechanism in case of extreme urgency only.

**Comment by coltongrainger** [comment]
A circumvention mechanism? Maybe only for emergency calls. 

Related: https://imgs.xkcd.com/comics/tar.png

**Comment by rafenciugo** [comment]
I imagine that the AnkiDroid should display a single card (or configured number cards) automatically on ScreenUnlock, but.... the user should always be able to simply reject the card. Reviewing the card is totally voluntary. Of course, it would be nice to have some statistics, how many times a card was answered and how many times was rejected.

**Comment by Worthy7** [comment]
Btw, this should be generalized into "make a better widget".

**Comment by rafenciugo** [comment]
As far as I know, there are two widgets available right now. One simply opens the AddNewCard form, another one, displays a number of reviews pending and simply opens the AnkiDroid.  Worthy7, do you think of implementing another widget "Display a card on Screen unlock"? I thought it should be implemented an integrated feature of AnkiDroid.

**Comment by Worthy7** [comment]
Yea I agree, TinyCards is going to take over Anki at this rate.
Basically a mini ankidroid as a widget is all we need.

**Comment by mo271** [comment]
I think this would be a great feature! 
I want to do something similar with for an app that I wrote that quizzes you on random dates (you are supposed to guess the day of week). 
Is there any open source android app which does something similar?

**Comment by mo271** [comment]
One could think about, whether the behavior should come from the app, or if it should rather be managed by another app. Imagine having two or more programs that compete for being the app opened after unlock.. 
The app Hangar provides a widget on the lockscreen, that can display the anki symbol and if you click on it it opens the app automatically. 
https://f-droid.org/packages/ca.mimic.apphangar/ 
While it is not exactly what @rafenciugo was asking for, it is already more convenient then opening anki every time by hand. Also there is this old app, which seems to be not maintained and not open source:
https://play.google.com/store/apps/details?id=se.webworks.android.apponunlock&hl=en

**Comment by Worthy7** [comment]
It basically need's to be a widget built into Ankidroid. It needs to have access to Ankidroid code to do the reviews.

**Comment by mikehardy** [comment]
I don't believe Android allows lock screen widgets anymore. However there are notifications you can interact with. Perhaps most of the review logic could be stuffed into a notification so you could display card and have a flip action then display the back side with answers. No idea if that could work but a proof of concept tiny app with static content would show

**Comment by SergioGeeK7** [comment]
Hi @mikehardy, it does support, I just used https://play.google.com/store/apps/details?id=net.wordbit.enes it works like a charm yet does not let you add cards or create decks

**Comment by SergioGeeK7** [comment]
Also https://play.google.com/store/apps/details?id=co.unlockyourbrain

**Comment by Worthy7** [comment]
https://stackoverflow.com/questions/2803069/android-unlock-screen-intent

I'm not an android dev, but could we not use this to launch the app with some "parameter" which will make the app open `Study` of whatever deck the user specifies in the settings? Something like that?

**Comment by mikehardy** [comment]
No, they limit which intents are receivable starting with 8 / oreo, which is already around 40% of our new installations (combined with 9 / Pie)

https://developer.android.com/guide/components/broadcast-exceptions

It would be neat, I too would like it - but it is fighting where the platform is going and that is a tough path to go down

After the study I did on it this morning and reported on above, a very dynamic notification is the only path I personally see as workable, and at least that path is something the platform is encouraging at the moment

**Comment by Worthy7** [comment]
Fair enough Mike, thanks for investigating

**Comment by mikehardy** [comment]
On the plus side, I have only been an "android developer" since December, and a "very dynamic notification" (or at least a proof of concept for one) is totally doable....

**Comment by sks4903440** [comment]
Just wanted to state that U-Dictionary provides a similar feature where it displays you a card with a word on it and you can check the meaning of the word on tap as well as mark it favorite on clicking another button. You can slide for other words. Can we do something like that or it will mess with unlocking?

**Comment by mikehardy** [comment]
Interesting, @sks4903440 - I looked and by the look of the image on their app store listing, and that they require the "disable screen lock" permission, I'm guessing they are going down the route of replacing the lock screen. I haven't tried it personally, but if you have it installed you could tell us instead of me guessing. Does it replace your entire lock screen, or does it just add something to the standard lock screen?

**Comment by SergioGeeK7** [comment]
Hey guys, I discovered there's an app that does just what we wanted, is amazing, I tried for 15 days before publishing here just to make sure it worked, here's the link. it works along with anki, I love it

https://play.google.com/store/apps/details?id=morisson.ankihelper

**Comment by mikehardy** [comment]
Also very interesting - I remain convinced that lock screen replacement is a dead end *for the future* in Android, but for other older APIs, great - and it's obviously great that someone has something working that fits people's needs now. It looks like it's using the AnkiDroid API which is the whole point of AnkiDroid having an API, people can do whatever they want with it :-). I'd still love to see a "modern" (read as: non-lockscreen-replacement) take on card display / answer like a rich notification but hopefully everyone here can take advantage of AnkiHelper. In the app store description it said "open software" but I was unable to find any source for it. That's not a problem (you can use the API however you want), just curious if anyone's able to discover code for it.

**Comment by sks4903440** [comment]
@mikehardy Sorry for the late reply. The app places an additional screen on top of the lock screen. When you use your fingerprint, the phone unlocks and when you use the power button, the app shows the word screen. You can swipe up for the lock screen.

**Comment by mikehardy** [comment]
Looking for something unrelated, found the link to the notification style that would fit best for the "fancy notifications" branch of thinking https://developer.android.com/reference/android/support/v4/app/NotificationCompat.DecoratedCustomViewStyle

If the implementation @sks4903440 saw isn't too hard maybe the lockscreen path is still viable though - I haven't seen the code for it so don't know

**Comment by JulyMorning** [comment]
still would be great to have it. I just tried to use the app above (isn't available on gp, but easily findable). it doesn't read decks right. I just cannot choose the one deck I want: it checks s lot of other decks alongside + keeps showing the same deck I didn't choose. Good news: with tasker app or something even more powerful as xposed edge pro you can make any trigger you want and it will work like a charm, because this app has an explicit activity to show a card. For example, I've set to open the activity when screen lights up if gps is off, no one is ringing and no music on the background (if the reason to take a phone was a willing to switch a track), it shows a card right after lighting up (rven without unlockingl. Meanwhile the native feature of the app is turned off. It's easily possible to show the card randomly with tasker too. Or when you open social nets, you name it. The problem is that it's showing dome random decks, I can't tame it. Is it only my problem? Maybe there were some huge api changes that broke things?
 
Still it's possible to create separate account or make an anki clone with a limited number of decks so it will work anyway.

Ankidroid devs, please, make a simple activity to show just one card + an option to choose decks, thats's it. It sounds pretty doable to me, and it could make things easier.

**Comment by mikehardy** [comment]
This is the perfect use for the API. I am still against this in core, it would be a device- and android-level-specific fracture of an implementation I think. Regardless, no one has proposed code and in this area code will talk

**Comment by JulyMorning** [comment]
I kinda managed to make use of the native AnkiDroid .Reviewer activity which shows a card too, but:

1. It shows a next card right after your answer – it may affect stats
2. I needed to force cloze anki with the help of tasker and its plugin called AutoInput (the trigger is a click when the buttons "again", "good", "easy" etc are shown). It may affect the loading speeds, because of the unloading the app from memory.
3. Can't choose multiple decks: it shows cards from the last used deck/study session.
4. Overall, it's not as neat as it could be. But still it can work with any imagiable trigger.

Yeah, I know, that making this under-the-hood activity seems too specific, but yet it's pretty simple thing to do. As an alternative, it would be just freaking huge if you'd make use of the tasker api. Tasker has a great community, lots of apps can communicate with it, even if it's not advertised much.  This way it may become a lot more than simple showing a card. Tasker can parse data, so it could become an instrument to make new cards too.

**Comment by david-allison-1** [comment]
> I kinda managed to make use of the native AnkiDroid .Reviewer activity which shows a card too, but:
> 
> 1. It shows a next card right after your answer – it may affect stats
> 2. I needed to force cloze anki with the help of tasker and its plugin called AutoInput (the trigger is a click when the buttons "again", "good", "easy" etc are shown). It may affect the loading speeds, because of the unloading the app from memory.
> 3. Can't choose multiple decks: it shows cards from the last used deck/study session.
> 4. Overall, it's not as neat as it could be. But still it can work with any imagiable trigger.
> 
> Yeah, I know, that making this under-the-hood activity seems too specific, but yet it's pretty simple thing to do. As an alternative, it would be just freaking huge if you'd make use of the tasker api. Tasker has a great community, lots of apps can communicate with it, even if it's not advertised much. This way it may become a lot more than simple showing a card. Tasker can parse data, so it could become an instrument to make new cards too.

Is the AnkiDroid API not sufficient for what you're looking to accomplish?

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API

**Comment by JulyMorning** [comment]
> Is the AnkiDroid API not sufficient for what you're looking to accomplish?
> 
> https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API

Seems great that it already has a way to communicate with tasker, but it requires to have some knowledge which most users including me don't have, unfortunately. Operating with tasker plugins is much easier. Maybe you could help figure out how to make what we want with the AnkiDroid api?

**Comment by david-allison-1** [comment]
This isn't a feature that I'd be interested in taking on, as I have other priorities within the project (sorry!), but it should be possible to extend AnkiDroid to do what you need via the API. 

Take a look here for `SCHEDULE` or `ReviewInfo`: https://github.com/ankidroid/Anki-Android/blob/master/api/src/main/java/com/ichi2/anki/FlashCardsContract.java

**Comment by JulyMorning** [comment]
#helpWanted :)

**Comment by mikehardy** [comment]
@JulyMorning @david-allison-1 we maintain a fully functional (or it should be anyway) Sample app that is an API client, so most of what you need in order to get started making an AnkiAndroid API client is all done for you. Try forking that, re-purposing it to integrate the Tasker API, and should be all set? https://github.com/ankidroid/apisample

That said, the Tasker API is already partially done, you can use it to do syncs for instance: 

https://github.com/ankidroid/Anki-Android/blob/5b5afadaf3be5fc7456ae50c89ff2e0921e0db3d/AnkiDroid/src/main/AndroidManifest.xml#L174-L178

It's on the 'IntentAction' so I suppose you could add a different intent filter with different direction to the intent filter and have it be "show one card", but that's not something I'd merge. This is why we have the API

**Comment by vocabwidget** [comment]
hi everyone,

forgive me for intruding -- and forgive me for probably not yet understanding social good practice on github. i hope it's ok if i post my question here, because i'm at a point where i have to reach out. i signed up for github solely to meet anyone who can help me either (a) find or (b) talk somebody, somewhere, into creating the specific function that user rafenciugo has brought up. i have been looking for a tool that will do this for literally 21 years. every few years i scour the internet. in the late 90s, i thought a desktop screensaver would do the job. when smartphones arrived, i thought it would only be a matter of time. 

i'd like to message with anyone who is interested in exploring this further with me. i think i understand that ankidroid involves tests, or some gamification, and that this could be a problem when it comes to integrating the function. but to be clear, the function that would 'complete me' has two or three components:

1. ability to select and define a word while reading normally in any app by highlighting it, with the option to add it to a custom wordlist/flashcard list
2. a lock screen OR home screen widget that perpetually cycles through items on the vocabulary list that you have designed for yourself. when you're looking, it's there. passive exposure to salient material. 

i'm just mystified. i've seen one app in the playstore that will do this, but it doesn't work, and the developer does not answer emails. 

as we drive around our towns, we perpetually encounter advertising billboards. in our peripheral vision, every day, we become aware of cheeseburgers. admit it: each of suffers from incidental, involuntary cheeseburger awareness. but imagine a world in which these billboards displayed information we're trying to learn. consider that learning can be "something that happens to you" instead of something you sit down to grudgingly do. 

now imagine that your phone can do this for you.

**Comment by JulyMorning** [comment]
@vocabwidget I'm not a big programmer to help, but I love your spirit. You may want also to check out the app with some name I can't recall, but I guess you can easily find it with words: "prime picture screen unlock". It doesn't solve anything even nearly, but it works on the same passive principle and utilizes so called prime effect to make you remember stuff. The AnkiDroid feature we discussed here is still wanted, because I don't really have needed skill to do it myself, my bad.

**Comment by lucwastiaux** [comment]
@vocabwidget have you thought about commissioning a developer to make your idea happen? Do you already have a deck in Anki that contains the facts you want to memorize?

**Comment by mikehardy** [comment]
Create the smallest app you can think of first. 

Just install AndroidStudio and have it generate the default app (this is easy I promise)
Have the code do nothing but generate a local notification that says "this could be a vocabulary word"
Confirm you see that notification on your lock screen

Now go to the ankidroid API sample app: https://github.com/ankidroid/apisample

It will show you how to ask for "the next card due"
Show the front and back in the notification from before
Confirm you see it on your lock screen

You are started!

Further improvement: any time the notification is dismissed, the application responds by making a new notification with the next card.

Etc

I'm not being snarky, this is how to start it

**Comment by lucwastiaux** [comment]
> Yea I agree, TinyCards is going to take over Anki at this rate.
> Basically a mini ankidroid as a widget is all we need.

Tiny cards is shutting down. https://support.duolingo.com/hc/en-us/articles/360043909772-Tinycards-Announcement#:~:text=Since%20Tinycards%20will%20be%20shut,this%20post%20for%20more%20information.

**Comment by lucwastiaux** [comment]
@mikehardy is right, lockscreens can't be done in Android right now. I think something creative can be done with Bubbles API which will be generally available in Android 11.

**Comment by mikehardy** [comment]
Lock screens *can* be done. But the way in will be with persistent, interactive notifications. Like the notification presented by your favorite music player, where you can rewind, pause, forward etc. Android can do that.
But AnkiDroid does not need that in the core. It would be done as a consumer of the Ankidroid API, with a simple app using it for card fetching / scheduling, but handling all the notification posting etc itself.

Starting with a simple notification as I detail above is the way to begin

**Comment by mikehardy** [comment]
Would be great if someone exported all the TinyCards decks to shared decks on AnkiWeb via their automated tools if it hasn't been done already. They apparently invested some in creating curated content and it would be a shame for that to not be available to everyone https://forum.duolingo.com/comment/39200018

**Comment by vocabwidget** [comment]
thanks everyone. i might look into what mikehardy is suggesting. and another possibility is to commission the development, yes. i've been thinking that could be the next step, though i'm not sure how to find a person who would do it. i could probably mount a search. i'm thinking it may be the way to go because i feel like a key part of it is the dictionary lookup feature. the way this would ideally work is that i'd be able to define any word that i encounter online by highlighting and getting some sort of popup definition, and there i'd be able to choose whether to add it to my list or not. combine that with the home screen widget which cycles through my words and the whole system would work essentially automatically, which is my entire goal. i actually think a home screen widget is preferable to a lock screen widget, too.

there are plenty of fine apps we can use to really drill ourselves on vocab, but studying in that way requires goal-setting and a certain kind of engagement and follow-through. i don't want the drudgery of work to spoil the joy of words. so i'm imagining this as a very simple app that's targeted at readers and word-collectors, something for people who want to improve their vocabulary without trying too hard. if you read a lot, often you run into a word that you sort of know, but it's not part of your working vocabulary. a lot of these are workhorse words that you'll see here and there, so you already know something about their general frequency. they stand out as worth knowing, but you don't want to devote a season of your life to studying a huge list of, say, GRE words, simply because the utility of a given word isn't always guaranteed and because there's just something about memorizing things that you dont care about in order to burn in the things that you do which is inefficient and somehow a turnoff. hell, sometimes you just dont like the feel or sound of a word. it might do solid work, but you'd feel ridiculous using it. 

an app like this would enable readers to improve working vocab in an idiosyncratic way just in the course of reading normally. i think that there *should be* a high demand for such a thing, and i've just never understood why it hasn't emerged.

**Comment by lucwastiaux** [comment]
@vocabwidget please give me your email and we can discuss this further

**Comment by vocabwidget** [comment]
lucwastiaux, i emailed you a few weeks ago, but i may have done it wrong. i'm sorry if i'm using the forum incorrectly everyone -- this thread probably gets resurrected now for a spell -- but i'm new here. if lucwastiaux or anyone wants to talk about this, i would be interested. i can be reached, conveniently enough, at vocabwidget at gmail

**Comment by lucwastiaux** [comment]
ah I saw your email but couldn't connect the dots earlier. I responded just now.

**Comment by thiswillbeyourgithub** [comment]
> Would be great if someone exported all the TinyCards decks to shared decks on AnkiWeb via their automated tools if it hasn't been done already. They apparently invested some in creating curated content and it would be a shame for that to not be available to everyone https://forum.duolingo.com/comment/39200018

I can't find an archive anywhere. Did they open the access to their files or do users have ot manually export it? It would be great if they just made a torrent or something. Woudldn't cost them much.

**Comment by lucwastiaux** [comment]
@thiswillbeyourgithub users had to manually download their content from tinycards. So I doubt you'll find a big archive with everyone's decks.

**Comment by thiswillbeyourgithub** [comment]
Hey guys, I have been giving some thoughts about all this and was interested to get your opinions.

Basically, why not make a simpler version of this that would be more robust to the new android changes?

Here's what I'm imagining :

Each time you unlock your phone for more than 30 seconds (in case you really was just looking at one quick thing) a notification appear, prompting you to do 10 reviews. You click on the notification and it shows you a preordered list of you decks to decide where those reviews will be picked from. You then do 10 cards (be it reviews, learning, new etc) and after that it simply asks you if you want to continue (not to overdo it I guess).

To me, if everytime I unlock my phone I get a notification offering 10 quick reviews without having to open the app / choose a deck / worry at my growing due review list etc that would be incredible already. Of course, if you unlock your phone several times you will have several notifications like this one.

I think it would be a good idea to avoid doing filtered deck automatically, but to really act like you just clicked on the deck.

The only new settings would be : 
* number of cards to see
* if new notifications pile up or if only one should stay on
* deck order : an ordered list of decks where the reviews would be extracted from


Thoughts?

**Comment by mikehardy** [comment]
Make a separate app using the AnkiDroid API

**Comment by thiswillbeyourgithub** [comment]
Thank you for answering. Do you know of anyone who could be hired to do so? I understand you don't think it should be part of ankidroid but I'm sure other users would be interested in this.

**Comment by lucwastiaux** [comment]
Just curious, what kind of crowdfunding site is appropriate for mobile apps ?

**Comment by mikehardy** [comment]
There is not a great deal of money to be had anywhere for donation where, in my experience with one of the bigger open source ecosystems anyway (react-native). I have seen OpenCollective used to some effect, but no one will quit their day job on it, if you know what I mean. BountySource maybe. I have direct experience with both and have seen money change hands at least so could work

**Comment by unalkalkan** [comment]
Heya everyone, sorry for necro-ing the old issue. I made a very simple app as a weekend project based on @mikehardy 's ideas here. Mind you, I am in game-dev industry and have little to no experience in Android Ecosystem, so the whole thing is ideas mashed together in a weekend. So don't expect much haha

Originally I was aiming for a lock-screen widget but seeing this issue made me go down the notification path. Here's how the app works:
- Makes you select a deck
- Shows next card of your deck as the title of the notification
- You can expand it to see the answer, and then vote for it.

Here's the repo for the app;
[AnkiDroid Companion](https://github.com/unalkalkan/AnkiDroid-Companion)

**Comment by unalkalkan** [comment]
Also, after I made the app in this "notification" way, I saw that Samsung had a new update which allows you to use Widgets in the lock screen. I use a Samsung device and tried and saw that I can add widgets to lock screen. 

So next update might be a widget for the lock screen for people that can use this feature.

Here's the Reddit post about the said Samsung update: [link](https://www.reddit.com/r/oneui/comments/15f5hen/widget_on_lockscreen_and_aod_with_lockstar/)

**Comment by mikehardy** [comment]
@unalkalkan I think that's great! 

I notice this important bit in the limitations "Currently this app only supports simple cards with small texts that doesn't include any HTML" and that's what stopped us here basically. We aren't able to support the full Anki experience so it is hard to do, for us.

But as a companion app with known limitations that works for a *lot* (but not all) use cases, hey, that's fantastic.

Really well done.

You might want to add yourself in here? https://github.com/ankidroid/Anki-Android/wiki/Third-Party-Apps  (I assume it's using our AnkiDroid API - the low-level integration method for apps)

**Comment by thiswillbeyourgithub** [comment]
Thank you very much. Ill keep an eye on your project that looks awesome!

**Comment by unalkalkan** [comment]
> @unalkalkan I think that's great!
> 
> I notice this important bit in the limitations "Currently this app only supports simple cards with small texts that doesn't include any HTML" and that's what stopped us here basically. We aren't able to support the full Anki experience so it is hard to do, for us.
> 
> But as a companion app with known limitations that works for a _lot_ (but not all) use cases, hey, that's fantastic.
> 
> Really well done.

Thanks @mikehardy! Also thank you guys for the great app and taking extra mile for the API, yes it does use AnkiDroid API, I'll include the project in the Third Party Apps as well.
