### ISSUE TITLE
Something changed unexpectedly during sync process

### ISSUE THREAD

**Issue by sr030** [ankidroid/Anki-Android#4741]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. [sound:http://dict.youdao.com/dictvoice?audio=smoothly&type=1] was added in any card on Anki PC client. 
2. Sync. PC->web then Web->Ankidroid
3. 

###### Expected Result
[sound:http://dict.youdao.com/dictvoice?audio=smoothly&type=1] 

###### Actual Result
[sound:http://dict.youdao.com/dictvoice?audio=smoothly\&amp;type=1]

It leads to a totally different style of pronunciation.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment]
Interesting, looks like a HTML vs URL encoding/decoding error.
Specifically somewhere along the line the URL must have been HTML encoded (& -> &amp;) instead of URL-encoding (& -> %26) and then when AnkiDroid goes to render it just puts &amp; in there because it isn't a URL encoding.

Is the URL you posted from the contents of the edit card view on both desktop and ankidroid? I think so, just curious.

If that's correct then it could be part of the process that creates new cards during sync in AnkiDroid

**Comment by mikehardy** [comment]
I thought this might be an interesting problem (html/url encoding issues sometimes hide forever and are fun to fix) but I don't think the problem is in AnkiDroid. Here is what I did:

- opened AnkiDesktop and created a new deck with a new card in it, that has just your URL as an answer
- sync this to the web, then to AnkiDroid, and I hear the US version, not the British version - which is an error as you indicate
- I edit the card in AnkiDroid and see that it is indeed '&amp;' which is incorrect, I correct that to '&', save it, and sync it to the web, and back to AnkiDesktop
- now it plays correctly in AnkiDroid and AnkiDesktop
- I sync again from AnkiDesktop to the cloud to AnkiDroid, use the card browser, and it is correct and plays correctly
- BUT, if I edit the card in AnkiDesktop, the URL is corrupted again. 

So I think this is a problem with AnkiDesktop taking URLs and HTML-encoding them instead of URL-encoding them, but AnkiDroid can't fix that.

If my tests were wrong in some way, please show me and apologies in advance

**Comment by timrae** [comment]
If I remember correctly, Anki Desktop defaults to a WYSIWYG editor, and there's an option in the note editor to enter plain text

**Comment by mikehardy** [comment]
Hmmm, you are on to something. I was unable to find a plain text option in the note editor, but when you are currently in the editing box with the URL in it, and you select the little down-arrow top-right above the box to open the menu for more options you see 'Edit HTML', when you look in there, it is incorrectly HTML-encoded. This really looks like an AnkiDesktop bug to me. I can verify AnkiDroid does not do this when you enter or edit URLs with parameters in them.

**Comment by timrae** [comment]
Yes `Edit HTML` is the plain text editor! I don't think it's a bug, just a usability issue in AnkiDesktop.

**Comment by mikehardy** [comment]
Even when you use edit html and fix it manually , it html encodes the ampersand on close somethings not right in ankidesktop 

-Mike
--
+14157209408 (WhatsApp and US phone) 

-----Original Message-----

**Comment by timrae** [comment]
Ah ok, please report it to Damien over [here](https://anki.tenderapp.com/)

**Comment by mikehardy** [comment]
Logged https://anki.tenderapp.com/discussions/ankidesktop/26145

**Comment by mikehardy** [comment]
I followed up on AnkiDesktop and the problem is that the "field" in the note is part of the larger HTML document that is the note. So they must HTML-encode it, which of course damages the link (from the perspective of your use case) when you ask AnkiDroid to edit it.

Here's what you should do after importing or syncing a deck to Anki Desktop with these sound URLs - install the "Media Internalizer" add on (https://ankiweb.net/shared/info/221033553), then change the regexp in there (via 'Edit...' in add-ons for that add-on) to \[sound:(http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)[^>]*\]

It will match your sound URL and download the file locally, replace the url with a file lookup, and should work. 

After learning all this I asked them to close the Anki Desktop issue because this isn't a bug, just something that almost worked for you, but isn't supported.
