### ISSUE TITLE
Need detailed anki statistics

### ISSUE THREAD

**Issue by sharmas5** [ankidroid/Anki-Android#4773]
How can I extract detailed anki statistic? I want to know details about: 

how many cards on a given day
how long spent on anki per day (including mobile)
how many days over the span of a year
which days and how many cards reviewed as well as what time of day 
how many cards added/created/edited by a user
number of images added.

I need to compile these stats for ~150 users and ideally get as an output in excel. I understand I will likely have to extract user by user and then probably combine the excel fields.

Thank you!

**Comment by mikehardy** [comment]
As far as I know there are no tools to do this on a multi-user basis, but if you have access to their databases / collections I think there is some reasonable documentation about it. I have looked into this a little because I'd like to implement Anki in an educational environment and the statistics you mention would be exactly what's required to know what the impact was. This overview (and the link to the database structure document inside it) seem like a good handle on the problem: https://www.juliensobczak.com/tell/2016/12/26/anki-scripting.html

**Comment by sharmas5** [comment]
What if it's just for a single user? I'd be happy to go through it 150 times if I even knew how to extract that data for a single person.

**Comment by mikehardy** [comment]
For a single user / profile, I've been using plugins on the Anki Desktop client. They are open source and written in python so they might be a good starting point. "More Overview Stats" (and I guess "More Overview Stats 2" though I haven't used this one?) do things in the area of what you're looking for and might be a basis for the work

**Comment by sharmas5** [comment]
I guess that's my question. I know the data is there and can viewed by various add ons but how do I export that to an excel file or something that I can analyse with statistics software?

**Comment by mikehardy** [comment]
That's a large scope question :-), I'd take an add-on that has some of the statistics you want, clone it out to your own so you can work on it, then start by adding some code that does file operations to create a statistics file, then after processing start printing the stats out in CSV form using Python code. Then you can open the CSV in excel and do whatever aggregation / post-processing you like. This is only the barest skeleton of a sketch though

**Comment by mikehardy** [comment]
There is a pull request that will likely be merged soon that implements a StatsProvider #4881 - that may open this up, also there was discussion on the google support forum that gave the exact SQL queries for accessing the sqlite database, plus pointers to sqlite apps that can do it. I'm going to close this because it's not really a bug and there's slow progress in this direction regardless
