### ISSUE TITLE
No Sync of Pictures to AnkiDroid, Error occuring

### ISSUE THREAD

**Issue by CasyFel** [ankidroid/Anki-Android#4781]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. All of the above
2. 
3. 

###### Expected Result

Pictures syncing to the "answer" section in my Cards on AnkiDroid. Pictures can be Seen properly on the Desktop Version. 

###### Actual Result

See heading. Error occuring. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.3

Android Version = 7.1.2

ACRA UUID = b17d30bd-0336-4e7b-b5ca-e04a1ec5d9e1

I can't see pictures on my Cards in AnkiDroid. After syncing with my desktop Version, an Error occurs.

Thanks massively for any Help!

**Comment by mikehardy** [comment]
Interesting - you say "Error occuring", but what error exactly? Does the exact same error happen every time or is it on a different picture each time? Do you have the actual error text or a screenshot of some error message? This may be related to issue #4782  where syncing mp3 media files was failing (for an unknown reason) but if the sync was retried the media files would all come in with enough retries.

**Comment by CasyFel** [comment]
Hey! thanks a lot for your answer, and sorry that my information was incomplete (I thought, the error message would be included in the error text I posted). 
The error occurs every time i tab "sync" on my phone. All cards are correctly synced, except for the ones with pictures- there's a little "picture symbol" instead of the picture itself on the cards. No matter how often I sync, the pictures never come to my phone. I use a Xiaomi Redmi 4X, but I never had problems with apps earlier. 
I try to attach a screenshot of the error below. 
Thanks a lot for your help! 

![screenshot_2018-02-05-14-51-51-434_com ichi2 anki](https://user-images.githubusercontent.com/36159640/35846011-1aafade2-0b15-11e8-8fd7-377b68299da3.png)

**Comment by mikehardy** [comment]
Apologies for the long delay - have you looked at the solution in #4782 ? If you try one of the alpha build candidates (which are actually stable as near as we can tell, just not formal releases), you may see success with synchronizing your images - especially with multiple synch attempts -  due to the current alphas re-trying to fetch images when there are errors

If the alpha builds do not fix your issue then we have a separate unknown problem

**Comment by timrae** [comment]
Json exception syncing images sounds weird, no idea from where this might be getting thrown without digging into the source. I wonder if there's a stack trace on acralyzer?

**Comment by timrae** [comment]
```
java.lang.RuntimeException: org.json.JSONException: Value invalid of type java.lang.String cannot be converted to JSONObject
at com.ichi2.libanki.sync.RemoteMediaServer.begin(RemoteMediaServer.java:85)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:95)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
```

**Comment by timrae** [comment]
```
org.json.JSONException: Value invalid of type java.lang.String cannot be converted to JSONObject
at org.json.JSON.typeMismatch(JSON.java:111)
at org.json.JSONObject.<init>(JSONObject.java:160)
at org.json.JSONObject.<init>(JSONObject.java:173)
at com.ichi2.libanki.sync.RemoteMediaServer.begin(RemoteMediaServer.java:80)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:95)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:388)
```

**Comment by timrae** [comment]
That stacktrace is pointing here:

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java#L80

So it seems you're getting malformed messages from the server, most likely due to poor network conditions. I don't think #4782 will help with this, as that specifically addresses filesystem problems.

Basically all you can do is one of the following:
* Retry the sync until it works (I presume it works for a while and then eventually throws an error?)
* Move to a more stable network
* Manually sync your media by importing an apkg from Anki Desktop over USB as described in the manual
