### ISSUE TITLE
Answer card text offset, <span> after audio file(s)?

### ISSUE THREAD

**Issue by aphirst** [ankidroid/Anki-Android#4806]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Download and import [this deck](https://u.teknik.io/qoWn5.apkg)
2. Practice the deck until an affected card is displayed
3. (Affected cards include "moon", "four"; there are lots)
4. (One way to force the card to display is to find it, give it a custom tag, then study that tag)

###### Expected Result
English translation text is centered, as it is for most cards (and all other fields), and in Anki Desktop.

###### Actual Result
English translation text is offset to the right.

A workaround (suggested by "sneep" in #anki on Freenode) was to edit the Card definition. The references to the audio fields were at the "top" of the Answer card, and moving them to the bottom seems to prevent the offset.

###### Debug info
AnkiDroid Version = 2.8.3

Android Version = 7.1.2

ACRA UUID = e1d89010-713e-4945-8de9-035503d22422

**Comment by mikehardy** [comment]
If someone is coming in looking for a good first issue, the CSS and Javascript and HTML is all in AnkiDroid/src/assets and AbstractFlashcardViewer (interacting with Card and Note) is where the data and logic flow through)

**Comment by milyukhin** [comment]
I took a look, and I don't see an issue here to be honest. The cause of why the english translation aligned to the right is that there are two "Replay" buttons (I manually changed the color of the replay buttons in the source code, so the can be visible):
<img width="369" alt="Screen Shot 2019-06-30 at 21 59 42" src="https://user-images.githubusercontent.com/6668375/60395180-d189c980-9b83-11e9-8e5d-615bf7c4aad9.png">

Noted that the card's style template is custom:
styles:
`.card {
 font-family: arial;
 font-size: 25px;
 text-align: center;
 color: White;
 background-color: Black;
}
`
back:
`{{FrontSide}}
 
<hr id=answer>
 
{{Vocabulary-Audio}}
{{Sentence-Audio}}
<span style="font-size: 30px; ">{{Vocabulary-English}}</span>
<br>
<span style="font-size: 35px; ">{{Vocabulary-Kana}}</span>
<br>
<span style="font-size: 14px; ">{{Vocabulary-Pos}}</span>
<br>
<span style="font-size: 40px; ">{{furigana:Reading}}</span>
<br>
<span style="font-size: 25px; ">{{Sentence-English}}</span>
<br>
`

And so it can be customized further to make the replay buttons on new line each (eg using `<br>` tag). I am just not sure what is the expected behavior here. Help me out please.

The confusing part for me is the default color (black) of the Replay buttons and the background (which is chosen by the card's template). I wonder if they (the buttons) would still be hidden with default cards styles (`color: black; background-color: white;`) and black mode on...

**Comment by mikehardy** [comment]
Good sleuthing! I believe with default colors there is a color inverter that kicks in with night mode, so this would not have happened.

I don't see an issue here either now that I see it's just normal layout but hidden buttons. If people shoot themselves in the foot with CSS, it's not our fault...
