### ISSUE TITLE
Keep card timer running in background when reviewer loses focus

### ISSUE THREAD

**Issue by aportley** [ankidroid/Anki-Android#4808]
In Anki desktop, the card timer continues to run in the background while other apps (browser etc) are being used. In AnkiDroid the timer is paused. This pause is problematic for me because when studying I frequently switch between Anki and a dictionary or writing pad app, and as a result the study time statistic is off by a factor of 2 or 3. Ideally the timer would pause when the screen is locked but continue to run if another app is brought into the foreground.

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Enable card timer display and begin review.
2. Switch to a different app.
3. Check if timer continues to run.

###### Expected Result

Timer should continue to run.

###### Actual Result

Timer is paused.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment]
Interesting - this does seem like a difference between AnkiDroid and the other Anki clients. @timrae  - what do you think? Would you accept a pull request that changed timer behavior as described?

@aportley - can you submit a pull request that implements the functionality as you described?

**Comment by aportley** [comment]
@mikehardy - I don't have any experience with Android dev but I have given it a shot.

**Comment by mikehardy** [comment]
Wow, you may not have much experience but that looks pretty good. As a guess I'm probably similar - Java experience but not really mobile experience either - which makes me curious to see what Tim thinks about suitability. But I'll happily build this and test it as a second pair of eyes just in case since it looks like it should do the trick.

**Comment by timrae** [comment]
> This pause is problematic for me because when studying I frequently switch between Anki and a dictionary or writing pad app, and as a result the study time statistic is off by a factor of 2 or 3.

I'm not really keen on changing this behavior to be honest... I don't think we have a way to distinguish between your use case of switching to a dictionary app vs. receiving a phone call or opening an email. Yes, the behavior is different from Anki Desktop, but then again it's a mobile device rather than a PC so there are different constraints like the one I mentioned above, and the fact that Android can kill an app at any time while it's in the background, which makes timekeeping a bit complicated. We had several issues with this in the past, and with the time overflowing and becoming negative, etc. The current code has been carefully written to work properly.

Personally, I think our behavior makes more sense than desktop... Does anyone know how it's implemented in Anki Mobile (iOS)?

**Comment by aportley** [comment]
> I don't think we have a way to distinguish between your use case of switching to a dictionary app vs. receiving a phone call or opening an email. 

The IntentFilter registered with mPauseTimerReceiver is supposed to take care of pausing the timer in the event of an incoming or outgoing call, screen off, and some other cases. For other cases like opening an email the user can exit the session by going back to the decks page before switching tasks - this is an additional couple of clicks.

Even if the user switches tasks occasionally without exiting back to decks, the effect on timekeeping is likely to be small, especially if the "Maximal Answer Time" is set appropriately. On the other hand, with the current behavior, switching to a dictionary app frequently during study is likely to have a pronounced and pervasive effect. For me the recorded time was less than half of the actual study time.

I have been using this code for the past 4 months on a tablet where Anki is frequently killed in the background and have not seen problems with the recorded time across the session.

**Comment by timrae** [comment]
@hssm 

(Not sure if you're still around but...) Do you have an opinion?

**Comment by timrae** [comment]
I tried to do a bit of research on the history of this feature... It seems it was first requested and rejected in  #1101 by @nicolas-raoul, then finally it was requested again in #1340 and implemented by @nobnago (d332bb60be9143ab0d437de04653aaef30b4aee6, a8799e81f4cd1456ca7173851234074e1a09ebf1, 766218d96ebac5675f703dc0d7d1150739532e5e), but the reasons back at that time (before I joined the project) seem to be related to exceeding the session time limit, which is a feature we don't have in the Anki 2.x era. The most relevant recent change is probably #3652 by @hssm, though there was also a fix from @eginhard in #4062 and a patch for the content provider in #850.

I think that @aportley's reasoning above does make sense, so I'm not against going back to the desktop behavior, but I don't really have a strong opinion since I don't pay much attention to the time statistic, and therefore I'm not really comfortable to make a decision on my own without getting more feedback from the community, and would like to hear what other project members have to say.

If we do go ahead with this change, we should check through that history I posted above properly and make sure we didn't miss anything.

**Comment by mikehardy** [comment]
I'm listening more because interested in how you'd gather feedback in a situation like this. I don't pay attention the time either personally. I'm almost laughing as a suggest it (because I'm from a linux background, where this is always the "answer") but you could always make it an advanced preference. Not really serious unless it's a religious issue in the community then, why not...

**Comment by kieranclancy** [comment]
Recently I've changed my review workflow in one of my decks - I now have links in my cards that open other apps for me to do the review action before returning to the review screen and hitting "show answer". The stats for that deck are now off by a factor of 5 to 10 which has been bothering me (e.g. AnkiDroid suggests it will take 5 minutes for something that will take at least 30 minutes in reality).

In my mind the problem of measuring actual review time is nearly the same on both desktop and mobile. On both platforms you can change between applications, be distracted by an instant message/email/call, be interrupted in real life, etc. On both platforms you can also choose to use other applications as part of your review workflow.

Time spent in other activities can either be excluded from review time (current AnkiDroid behaviour), included in review time (current desktop behaviour), or we can be selective and only exclude activity changes that are unlikely to be review-related (e.g. incoming phone calls or turning off the screen, as the proposed patch detects).

Personally I think the behaviour in the patch makes most sense. I agree with @aportley's reasoning that this change would not really have a noticeable impact on users who occasionally switch activities for non-review purposes (with maximum review times capped at 60 seconds by default), but that it would have a worthwhile and significant impact on users who have other apps as part of their workflow.

In summary, I think here are the arguments for making the change:
- Better prediction of time remaining for reviews - when we say "100 cards due (12 min)", we want this to be accurate because it lets users make sensible decisions about when to study (e.g. can I finish all these reviews during my lunch break?)
- Closer alignment to desktop Anki behaviour
- More accurate review statistics. Some small amount of time spent in other apps may be included when it shouldn't be (up to the maximal answer time), but unless users are doing this extremely often then it's not going to have much of an impact on the overall picture (and if they are for example constantly distracted and flicking back and forwards between social media apps then maybe it's not a bad thing for this to be reflected in the estimate, as it would be on desktop)

**Comment by mikehardy** [comment]
The related #4811 pull request was closed with some discussion. We agree it is a fine line here and the discussion was good, but we will continue with timers that only run while app is in focus
