### ISSUE TITLE
[Bug] Wrong cryptic path in import message

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#4834]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Touch Import in Option

###### Expected Result
Maybe, technically it's correct, but message is not user friendly. It reads `sdcard` but in my case it is _not_ the external microSD card but the internal storage (`emulated`).
Creating `AnkiDroid` folder on microSD doesn't make import available but putting apkg in the main storage does.

Same bug in the Settings

###### Actual Result
Appears this message https://github.com/ankidroid/Anki-Android/blob/161ef99ab324eb427bc92586e524e42f68886284/AnkiDroid/src/main/res/values/02-strings.xml#L145
> Place apkg file in directory "/sdcard/AnkiDroid/" ...

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
I don't think the canonical path gives any improvement in UX for your average user... I think there's only one real solution to this problem which is using a file picker. Unix paths are most likely only helpful to power users familiar with ADB, in which case the symlink should be just fine.

**Comment by mikehardy** [comment]
Good point - that SAF (Storage Access Framework aka filepicker) change is queued up and ready to go pending one fix where after selecting from the filepicker, if I try to show the confirm dialog it fails, but if I just import it immediately it works. I don't consider that acceptable which is why I haven't PRd it  yet (I want that confirm dialog for the SAF path) but it's right at this line on my branch https://github.com/mikehardy/Anki-Android/commit/3b4f5c4f5c8bd9ffc20bf1939ae5778b235e62de#diff-f68abd17e6cd7e74032d32bd9e54a90aR69 - if anyone wants to fix it before I come back around, more power to  you :-). You'll be internet famous with the 16,000 users on Chromebooks also, as they can't import without this change. Otherwise I'll get it at some point.

**Comment by timrae** [comment]
Yeah sorry I was meant to look at your code, but I haven't had time, if you
really have a hard time figuring it out then ping me again

**Comment by mikehardy** [comment]
Really it should be trivial and my UI skills are still improving so next time I look it will probably be obvious. No worries

**Comment by mikehardy** [comment]
Except we actually (in AnkiDroid code) use '/sdcard/AnkiDroid' to access the files. It is a valid path, even if it is a symbolic link. It is not incorrect, it is just not the canonical path. This would be a change to the stable build though as the deck picker will be finished before 2.9, and I don't think it warrants a bugfix release on the 2.8 branch for something that is not actually wrong

**Comment by homocomputeris** [comment]
Should a user care what is written in the code or know Android's symlink conventions? If a user reads 'sd card', puts files to the SD card, and AnkiDroid cannot use these files, then its a bad UX.

**Comment by mikehardy** [comment]
This discussion is obsolete as soon as the PR is merged. Helping move that forward is a productive use of time
