### ISSUE TITLE
The issue related to TTS

### ISSUE THREAD

**Issue by hotfair** [ankidroid/Anki-Android#4849]
Hello everybody, I'm a Chinese user of Anki android version, I have an issue with TTS, I use Anki to memorize English vocabulary, I have installed google TTS for making the Anki can pronounce the word when I memorize the words. After I set the Google TTS as the main TTS engine It works, but it doesn't work very well. When I restart to use Anki, There is a message show in the Anki, "No text-to-speech language available", all I have to do is that to set Google TTS as the main TTS engine again, and after that the problem will come back again after several minutes, so I have to do the setting again and again. Is there anyone has the same problem as mine? what should I do to solve the problem? many thanks

**Comment by mikehardy** [comment]
You did not follow the template. It has information vital to help you. Please follow the template in the new issue form, as well as in the help document or we cannot help.

**Comment by timrae** [comment]
I'm quite certain this is a problem with your device rather than a problem with AnkiDroid.

I suggest you try to uninstall --> reboot device --> reinstall Google TTS engine. If that doesn't work you can try to install a different TTS engine, or try to factory reset your device, or try another Android device.

I'm sorry we can't be of more assistance.
