### ISSUE TITLE
Add "Study Recent Errors First" setting

### ISSUE THREAD

**Issue by xobs** [ankidroid/Anki-Android#4855]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Try to learn a new language
2. Have lots of cards that you don't know
3. Get stuck reviewing the same 50 cards forever

###### Expected Result

If the user clicks "Again < 1s", then the card should be shown in the next 5-7 cards, not after 30-50 cards.

###### Actual Result

When getting a card wrong, the card is not shown again for a very long time, at which point I've forgotten it.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.3

Android Version = 8.0.0

ACRA UUID = 9c0fcb8b-2a92-4fb6-b4f5-f9334dcaf8f6

###### More information

I'm new to Anki. I've used Memrise in the past, but now I'd like to switch to AnkiDroid.  I'd like to shorten the spacing for repetition.

I'm trying to learn Japanese, and I've been stuck on the same first few cards for months now. My problem is that when I get a card that I don't know, which is most of them right now, I mark it as "Again < 1 s". AnkiDroid then shows me 20-30 cards in between, each of which I also mark as "Again < 1 s". By the time the first card comes around again, I've forgotten it.

How can I reduce the spacing to something like 5 cards maximum? By that I mean that when I mark a card as "Again", it will only show me at most 5 cards before coming back to the one I got wrong?

I believe what's going on is that cards are getting put into a FIFO queue, but what they really should be put into is a FILO queue.

There is a desktop plugin here: https://ankiweb.net/shared/info/11767883 which I believe does what I'm looking for.

**Comment by mikehardy** [comment]
I expect to be corrected if I'm wrong, but I believe the default stance of the AnkiDroid project is to limit feature requests to those that either implement something supported by the official Anki Desktop platform, or that take advantage of mobile-device-specific features but don't otherwise affect the functionality implemented by the Anki Desktop platform.

Ergo if the plugin you link is ingested into the base Desktop platform, then this is something that has potential, but in the meantime using the scriptable (and therefore changeable) Desktop platform would work best.

I will say that the behavior you mention means you would essentially see the same card again immediately, right? You can easily achieve this behavior in the existing app by hitting the back arrow you see at the top of the app which is an "again" button, if you wish. So in that way you may not even need a change to get the desired behavior.

I will also add that at least for my personal learning style, if I'm hitting "again" on the same card more than a few times, it's time to move out of an SRS app and do a focused study offline of the same ideas as empirically SRS isn't working at that point, for me. Then the SRS will re-enforce it later but only once learned. Not intending to be irritating - I sincerely hope this helps. Cheers
