### ISSUE TITLE
Changing Japanese font slows down ankidroid considerably

### ISSUE THREAD

**Issue by TorridCheese** [ankidroid/Anki-Android#4856]
Changed to a different font using the "add font to media folder and use @font family to the template" method. Loading every card and it's answer takes around half a second. Attempted it with two different fonts, and only the default font makes ankidroid run normally.
Tested fonts were Hanamin and Ryumin

###### Reproduction Steps

1. Download font
2. Add it to Anki media collection on the desktop
3. Set it up as a template for all cards in a single deck

###### Expected Result

The font changed on every card.

###### Actual Result

The font changed, but now ankidroid takes around half a second to load every card while going through reps.

**Comment by mikehardy** [comment]
Hi there - I can maybe analyze the performance on this, though I suspect it is in the rendering, which is done by a system component and not something we control.

Can you upload a collection with the font installed and cards that use it so I can reproduce this more easily?

Also, you did not indicate what version of Android or AnkiDroid you are using, that information along with your WebView implementation version is necessary to pin this down

Thanks!

**Comment by TorridCheese** [comment]
Sure thing. I'm using ankidroid 2.8.3 and Android 6.0.1. The WebView implementation version is 66.0.3359.158. Thanks!
[Anki collection.zip](https://github.com/ankidroid/Anki-Android/files/2030979/Anki.collection.zip)

**Comment by Xyde** [comment]
Using custom Chinese font and this issue persists in latest alpha of 2.9 on Android 7.0.12.

Card also flashes whenever this happen. CSS styling also doesn't load properly due to this.

**Comment by alex7kom** [comment]
I can confirm this is the issue with the latest WebView. It works perfectly fine with WebView 55 (I've used 'Uninstall updates' to downgrade to the stock version for my device) but not with the latest WebView 66 (I've also tried 68.0.3440.40 beta with the same result).

**Comment by alex7kom** [comment]
I've created an issue on Chromium Issue Tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=866244

**Comment by timrae** [comment]
I don't think that chromium issue is going to receive any attention unless you provide the full html and font file for a card that is slow to load. If you compile ankidroid from source there's a flag you can enable somewhere which enables saving the rendered html of each card to a file inside the ankidroid folder

**Comment by mikehardy** [comment]
Hi @nfischer with the collection above and recent alpha builds (forwards- and backwards-compatible with 2.8, no worries for your database) I've enabled chromium webview debugging and also output the HTML of the card on the device with every card. So the workbench is laid out if you have the time to look at this.

https://github.com/ankidroid/Anki-Android/pull/4979

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by nfischer** [comment]
Hi @mikehardy. Thanks for following up. I left a comment on the crbug.

**Comment by mikehardy** [comment]
OK I read it I'll try to get one of those html files wrapped up with a repro bow if I can reproduce in the app

**Comment by mikehardy** [comment]
@TorridCheese @Xyde or @alex7kom - It sounds like at least one of you is using the latest alpha. I don't know if any of you have ever built from source or run a debug build but in the newest alphas, if you do so the HTML drops right on the device filesystem in /sdcard/AnkiDroid so we can pinpoint this.

Are any of you still experiencing this and able to build the current alpha code so you have this HTML debug feature? 

Having someone else handle the build / generate-html / submit to chromium tracker / handle feedback loop would be a big help to me. I can assert that the Alpha at this point is backwards compatible and has no known crash bugs so I'm not asking you to put your collection or study time at risk ;-). Please let me know, thanks.

**Comment by Goresome** [comment]
I've obtained html of the same card with default system font, and the slow version with Noto-CJK.
[card.zip](https://github.com/ankidroid/Anki-Android/files/2474152/card.zip)

**Comment by mikehardy** [comment]
That is fantastic! Thank you - @nfischer - see above, we seem to have HTML?

**Comment by mikehardy** [comment]
Okay - word from the chromium bugtracker is that they have looked at the cards in isolation and they can't reproduce it. I just loaded the collection attached to this bug into the API29 / Android 9 Pie emulator, and I see it. Somewhere between the HTML in isolation and the HTML in the webview, there is an answer. As @nfischer mentioned it is probably in our callbacks - we have a couple javascript files that fire and an interaction between the app and the webview on each card load, it must be one of those

**Comment by mikehardy** [comment]
I reproduced this in stock html on desktop chrome and attached the same to the chromium bug. We'll see...

**Comment by mikehardy** [comment]
It looks like they have reproduced this, thanks everyone for the help - https://bugs.chromium.org/p/chromium/issues/detail?id=866244#c13

**Comment by mikehardy** [comment]
I'm going to close this because there is nothing we can do, and even when fixed there will be no action to take that I'm aware of. But I have starred the bug upstream and I recommend anyone interested in the resolution to do the same

**Comment by oakkitten** [comment]
if it is even possible, can “installing fonts” (like you'd do on a desktop os) help?

otherwise, seeing that rendering the answer takes time as well as the question, it seems to me that the app is changing the whole document each time. is that the case? if it is, wouldn't things be considerably faster if only the relevant parts would be changing, through javascript or otherwise?

**Comment by mesufesu** [comment]
The card with the answer is technically a whole different page so the result is indeed being re-rendered. I've tried various fonts and the bigger the local font file the longer it takes (Noto-CJK is in particular huge) so it seems that the web backend has to reload the same font file every time which I think is a design flaw, but Chromium guys see no problem with it.

I don't see a way to install a custom font into a system on my devices, so the solution I've come to is to use a smaller font like Sawarabi Mincho, the lag is still there on slower devices but at least it is bearable.

**Comment by mikehardy** [comment]
Has anyone here tried the font-display: block CSS attribute? It was mentioned on the chromium tracker as being a possibility to optimize things slightly

It might also be interesting to see if someone can get any performance out of the official Google Fonts API: https://developers.google.com/fonts/docs/getting_started

**Comment by timrae** [comment]
I have been using the Noto (non-combined) Japanese font for years on various devices and never had a problem. Here is an apkg with a few cards from my Japanese deck using this font. Most likely you will not notice any significant delay after the first card when using my deck.

https://github.com/ankidroid/Anki-Android/issues/5213#issuecomment-466602921

**Comment by oakkitten** [comment]
> The card with the answer is technically a whole different page so the result is indeed being re-rendered.

css is often shared between cards of the same (and sometimes different) type, so you probably can get away with doing something along `body.innerHTML = 'new contents'` or even `answer.innerHTML = 'answer'` since the flip side often starts with `{{FrontSide}}` anyway. probably the widget has means of altering particular elements through the framework (java) as well. shouldn't this be much faster?

given how anki itself is doing this fade thing in the new version, i take it they are doing similar things—perhaps for the same reasons?

**Comment by mikehardy** [comment]
@oakkitten - In theory, since AnkiDroid will only ever display one card at a time, we could maintain a single WebView for the lifetime of the application (currently it is maintained only for the "started" states of the Activities that use AbstractFlashcardViewer if I recall correctly). Further, we could maintain an HTML document "shell" inside that webview and programmatically inject whatever we wanted in order to alter contents in response to showing new questions or answers. Possibly even looking at the different "slots" that we allow (front, style, back, again if I recall correctly) and only injecting a new version if it differs from the old one. In that way we would certainly be asking Chrome to do the least amount of work. 

But. 

This would be a non-trivial change, it may not even work (it's a performance change so there would need to be very very easily reproducible tests that showed before and after timings), and in the end Chrome could change again in the future to make something in that strategy slow. 

Before anything, It's important to isolate *exactly* what things are slow. For instance, it seems clear from Tim's comment that some fonts are indeed slow (we know that) but also that at least one Japanese font (Noto non-combined) is sufficiently fast. Only once we understand exactly what's slow and why can we even make a reasonable decision. 

Note that AnkiDroid has some abilities that would help a curious person do exactly that - https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by mikehardy** [comment]
For anyone having fun and following along at home, there appears to be renewed interest in the issue, but migrated to a different chromium bug id https://bugs.chromium.org/p/chromium/issues/detail?id=945117

**Comment by mikehardy** [comment]
Not sure if anyone has tried this, but apparently the fallback logic in chromium for ideographic languages has a tough time. You might try setting lang="ja" in the html element of the note (is that possible? may not be - you might have to hack card.html in our source code to test it...). Or lang="zh" as the case may be (for your card)

https://bugs.chromium.org/p/chromium/issues/detail?id=945117#c33

**Comment by d-schmidt** [comment]
They did split the issue again. This one discusses cache and font sizes:  
https://bugs.chromium.org/p/chromium/issues/detail?id=893318#c4

**Comment by eiennosihaisya** [comment]
I can confirm that the font re-renders, front and back, after updating my OS to Pie. It only needed to do it on the first card before. The larger the font, the longer the delay. With a rooted phone, I installed older versions of WebView, but it seems they are not compatible with Pie, as any app that uses Webview crashed.

Here's a hacky workaround for rendering Noto Sans JP quickly. It uses Google API, which serves WOFF2 format with small file size, so rendering is very fast. (You have to be online the first time to load, then the font will display even when offline. I assume because it gets cached in Webview).

[Test GoogleAPI.apkg.zip](https://github.com/ankidroid/Anki-Android/files/4113748/Test.GoogleAPI.apkg.zip)
(remove ".zip" from name)

**Comment by oakkitten** [comment]
(in case this is still an issue)

> This would be a non-trivial change

i wonder if keeping a separate web view for the answer would be (more) feasible? so that you load the answer at the same time as the question, and do a switcheroo when it's time to display it? perhaps it'd be possible to preload the question as well?

even with the default fonts the web view doesn't load instantaneously; loading external resources such as images from the web can be slow as well, so this could be helpful even if the font issue is resolved

**Comment by mikehardy** [comment]
I'm not sure you can have multiple WebViews at the same time, this would need a speculative branch and technology demo before I'd believe it, and to feel out any problems. After fixing most of our trivial (as in: easy to find) crashes WebView became our top crasher, it can be quite fickle to use correctly and loading large fonts is one thing that crashes it. So having a couple WebViews with large fonts would be something I'd want to see first

I would much rather see the WebView re-used. While it would be a non-trivial change, it would also be a big performance increase I think, and (who knows!) it might just work on the first attempt

**Comment by Pedrubik** [comment]
I was having this problem too. I downgrade to webview 59.0.3071.125 and now it works.

**Comment by basvdelsen** [comment]
This is still an issue in 2023

**Comment by mikehardy** [comment]
This will likely continue to be an issue forever. Computers aren't magic, and when very large font files are used on small devices (read as: mobile android devices), the devices will struggle to do the computational work necessary to handle the large / complex fonts.

The solution is to use simpler / smaller fonts. I believe they are available

**Comment by oakkitten** [comment]
My current cheapo phone is a few times more powerful than the computer that I first tried to use a custom font in Anki on, and it handled it without issues. And I'm still using the very same font

**Comment by mikehardy** [comment]
One of the fun things about all the font stuff is that it varies by Android System WebView version as well.

**Comment by 0x009922** [comment]
> This will likely continue to be an issue forever. Computers aren't magic, and when very large font files are used on small devices (read as: mobile android devices), the devices will struggle to do the computational work necessary to handle the large / complex fonts.

Fonts caching in WebView is not a big deal, really. And, I think, this issue actually might be solved by AnkiDroid if it doesn't initialise a new WebView for each card for each side (as I see it works now, not sure though). But this solution comes with lower isolation and might lead to issues, I guess.

**Comment by AustinHasten** [comment]
Still experiencing this in 2024. Unfortunate if nothing can be done about it. I tried converting my TTFs to WOFF2s which did reduce the file size of the fonts, but evidently had no effect on the issue. I'm not sure how fonts are installed in Android, but if I can get them installed I'll confirm whether that changes things at all.

**Comment by MarvNC** [comment]
> Has anyone here tried the font-display: block CSS attribute? It was mentioned on the chromium tracker as being a possibility to optimize things slightly
> 
> It might also be interesting to see if someone can get any performance out of the official Google Fonts API: https://developers.google.com/fonts/docs/getting_started

Setting font-display to swap worked for me, loading 45MB of fonts it doesn't block the card from loading and instead causes a bit of visual stutter once the correct font is loaded (which is like half a second). On a Pixel 6, at least.

**Comment by AustinHasten** [comment]
I'm seeing much better performance using Google's font API than local files. This does limit you to Google fonts but there are plenty of good ones. Being faster to grab something off the net than load it locally is wild 😄

**Comment by ElnuDev** [comment]
> I'm seeing much better performance using Google's font API than local files. This does limit you to Google fonts but there are plenty of good ones. Being faster to grab something off the net than load it locally is wild 😄

Can confirm that using the Google Fonts API imports is substantially faster. Anecdotally `<link>` seems to be *slightly* faster than `@import` but it's hard to say, both are substantially faster than loading locally which is crazy. It's unfortunate that this doesn't seem to be solvable.
