### ISSUE TITLE
Open external files through Intent

### ISSUE THREAD

**Issue by xerpi** [ankidroid/Anki-Android#4917]
###### Research
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Add an `href` Intent to open an external file:
```
<a class="link" href="intent:file:///storage/emulated/0/Documents/foo.pdf#Intent;type=application/pdf;end;"> Foo </a>
```
2. Click it

###### Expected Result

On the regular browser it works, on AnkiDroid it crashes.

###### Actual Result

AnkiDroid crashes.

###### Debug info

```
android.os.FileUriExposedException: file:///storage/emulated/0/Documents/foo.pdf exposed beyond app through Intent.getData()
```

**Comment by xerpi** [comment]
See https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed/38858040#38858040 for more info.

**Comment by mikehardy** [comment]
I understand what you're saying, what I don't understand is how that link to 'foo.pdf' exists in the first place? The only links AnkiDroid supports are to objects in collection.media via syntax defined in the manual (`[something.mp3]`) or to valid HTTP objects (i.e., not intents or files or content URIs).

The desktop clients can't support it as it is Android-specific, so this isn't something I think we can support in AnkiDroid, unless I am misunderstanding something?

**Comment by mikehardy** [comment]
I haven't heard back on my questions, I'm going to mark this as waiting for information and if it goes stale I'll have to close it

**Comment by xerpi** [comment]
The idea is to be able a PDF with the explanation for a given card directly from Anki. As you can see when trying to open the PDF through an Intent created from a href, `android.os.FileUriExposedException` is raised. Maybe doing what's on the stackoverflow is a bit too much for AnkiDroid (in terms of permissions).

**Comment by mikehardy** [comment]
Hmm - I think I see. AnkiDroid actually implements a ContentProvider to serve files (this is how the export package works to attach to mail clients), perhaps if you put the files in /sdcard/AnkiDroid/export and referenced them from there or the cache dir - I think those are both allowed:

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/xml/filepaths.xml

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/AndroidManifest.xml#L378

I have no idea what URL to use for those though. If you use the cache dir the system is allowed to delete things any time it wants for space reasons. If you use export they should be safe though they will not be synchronized anywhere, so maintain good backups if you try it. Let us know if it works

**Comment by mikehardy** [comment]
providers are actually finer-grained than permissions, and for export we'll always need one. Not saying is the best use of that provider, but this is orthoganal to read_write_external I think. Good to know of that intention though - I wasn't aware before and won't push in that direction inadvertently now that I know.

As for content accessing collection.media I dunno, but to remove storage permission I think we'd have to have Anki live completely inside /data/data/com.ichi2.anki - fully internal storage, OR to do that programmatically but allow the user to move it to the sdcard (we're "auto" in the manifest now so that's possible at least). That's my technical understanding at the moment. This isn't the place to think deeply on it but I wonder how this intersects with the "let's work on all the tiny cheap phones" Android Go initiative where internal storage will always be tiny. I worry about space, especially if we don't allow users to rescale/crop camera captures etc...I have no concrete ideas or motivation in this area though so I'll leave it but keep it in mind

**Comment by timrae** [comment]
> to remove storage permission I think we'd have to have Anki live completely inside /data/data/com.ichi2.anki - fully internal storage

No, the idea is to use [this](https://developer.android.com/reference/android/support/v4/provider/DocumentFile)

**Comment by timrae** [comment]
Or [this](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE) if we can I guess, I haven't looked into it for a while, but I remember there are APIs for accessing a subtree now, without requiring access to the entire filesystem.

**Comment by mikehardy** [comment]
Very interesting. Still learning about 10 things a day with Android. This would also allow us to remove that perm I think - just putting it here as a form of note-taking: https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)

**Comment by mikehardy** [comment]
@xerpi I'm going to close this one as adding more providers clearly isn't the way we want to go, however I do think the current provider is something you can piggy-back on. I'm interested in hearing if it worked or not even if this is closed - cheers
