### ISSUE TITLE
Gesture configs not preserved when moving to new device

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#4990]
Hi,

This is not a bug report, but it seems I can't find where to do request.
Gestures are really a plus in ankidroid. My only single problem is that I need to configure it again each time I change my phone. 
Anki database has a table "col", with a json field "conf", in which you can save arbitrary data. It seems its mainly done to save configuration of add-ons (see https://apps.ankiweb.net/docs/addons.html#the-database ) and I believe it would be perfect for this. My request is the following one: when gestures is set by the user, add in it the entry "Swipe up" to "answer button 1" for example. I kind of hope it wouldn't be too difficult to do (I don't know android development, so I can't help directly here). And when syncing, check if there are value here, in which case use them to change ankidroid's configuration.

I hope this request is ok for this issue tracker.

Regards,
Arthur

**Comment by mikehardy** [comment]
Hi there! May I ask what version of Android you were using prior, and what version you are using now? I am curious because more recent versions of Android should automatically save and restore user preferences if you let google back up application data

You are correct that there is some space in the database for things like that, but it is not unlimited: "If you need the data to sync across devices, small options can be stored within mw.col.conf. Please don’t store large amounts of data there, as it’s sent on every sync". That said, gestures conf would not be a lot of data. 

I have some other items that I've been thinking of storing in there - that are deck-related but stored in the AnkiDroid-specific database ("MetaDB") but I'm curious first about the answer to the versioning question. May be that this problem simply resolves for you in the future based on the current version of Android you just migrated to

**Comment by mikehardy** [comment]
I see what you're saying. It's a tough balance of "data/storage cost on sync" vs "keep everything synced" and the line has previously been that if it's something that is only useful for AnkiDroid, it has not gone in the database that gets synced into the cross-platform service. I'm working on a separate feature right now that will generate config state that is AnkiDroid specific and I've been struggling with the balance myself. I need to talk with some of the other project members to see how they feel about these sorts of configurations and I can't say what will come of it, but I can say I/we have hard the interest and I think I understand the use case and desire at least. We'll see

**Comment by mikehardy** [comment]
Just as a clear breadcrumb for myself: the use case is that some people may be on older devices (lacking Google backup), in general we support non-Google devices (we don't use any other play services), and users may be in a shared device situation where using google-account-related storage like the auto-google-backup isn't a preferred method. All that said, the majority of our installed base is on a version that supports google app data backup, and some of the configs we have aren't valid for the other platforms in the anki ecosystem. That captures my take on where things are currently
