### ISSUE TITLE
One deck always set as current when switching to browser

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#4999]
###### Reproduction Steps

0. I have a couple of decks: Geography, English, German, Spanish and French. French is the one I created only recently, about 2 weeks ago.
1. Pick any deck other than French by clicking it - it becomes the 'current/selected' deck and it is marked with a 'grayed' background.
2. Go to 'Browse cards'.

###### Expected Result

I expect the browser to have the 'current' deck selected and show its cards as specified in the manual and allow me to perform searches in that very deck.

###### Actual Result

No matter which deck was selected, the browser shows French whenever it is started, and I need to change the deck to perform searches I want to. When I go back, the French deck is 'grayed' i.e. current/selected by AnkiDroid, overriding my preference from before starting the browser.

###### Debug info

AnkiDroid Version = 2.8.4

Android Version = 8.1.0

ACRA UUID = 57ffb637-79cd-4fc7-a8ed-83cd0c0fa31a

###### Research

*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hmm - I can't reproduce this, for me the Card Browser always opens into "All Decks", not any particular deck I have. As far as I know the code makes no attempt to take state from the deck picker (where a deck may be selected) and use that as an initial selection in the browser. So 2 things really - should the browser start on whatever deck you were just using? I'm unsure on this one. It's a matter of opinion I think but I can understand the argument it should. Second thing, why is it going to a specific deck for you every time? Unsure on that one since I can't reproduce it either in 2.8.4 or current alphas

**Comment by wujek-srujek** [comment]
The documentation states:

    The browser screen starts by displaying all the cards in the currently selected deck.

I understand the 'selected deck' to be whatever deck I am using right now. So either the documentation is wrong, or the code as you say it doesn't happen, or I just overinterpret the sentence.

Would it help if I shared my collection? I might be a bit big, though, there are quite a few images and a few audio files in it.

**Comment by eginhard** [comment]
Yes, there are some irregularities in how the current deck state is handled. I never got around to look further into that.

To reproduce on 2.8.4:
1. Open card browser and select deck A, return to deck picker.
2. Select any other deck B to start studying.
3. (optional) Going to the browser now opens it for deck B.
4. Return to deck picker from reviewer or browser, the current deck B is marked gray.
5. Opening the card browser now wrongly shows the cards of deck A, not of the current deck B.
6. Going back to the deck picker, the gray highlight jumps from B to  A.

On a related note, opening the browser from the statistics always shows all cards even when statistics of a specific deck are selected.

**Comment by mikehardy** [comment]
Thanks both of you - between the reproduction and the documentation snippet there's definitely something going on. I'll look again when I have a minute - may be a few days though. At least this isn't a review blocker or anything - just an annoyance

**Comment by timrae** [comment]
Yeah I've been noticing this as well, I believe it used to work as written in the manual

**Comment by wujek-srujek** [comment]
I've just submitted a PR (https://github.com/ankidroid/Anki-Android/pull/5007) that may fix the issue. The change is minor and it seems to work. Now, in any of the three main activities (browser, statistics and picker) whenever a deck is changed, it is reflected in all the others. This was the previous behavior on 2.8.4, except for the browser, which was the reason for the original issue.

While my change is limited to a single line only, and so is my knowledge about the codebase, I actually noticed there is quite some handling of the 'selectedDeck' with the did put into Intents etc. (e.g. NavigationDroverActivity#openCardBrowser, DeckPicker#openDeckBrowser, CardBrowser#closeCardBrowser). I might be wrong, but it seems unnecessary - why not just depend on the activities setting the did of the selected deck on the collection (e.g. CardBrowser#selectDropDownItem) and just have the others use it by working with the collection? This would make the code much simpler, I hope. There may still be some special handling for the 'All decks' option in the browser etc. but maybe not?

**Comment by timrae** [comment]
@wujek-srujek @mikehardy 

How does this work for you?

https://github.com/timrae/Anki-Android/commit/ec95ff63e4330d6e5877130eb5366184647948e5

**Comment by wujek-srujek** [comment]
When I change the deck in deck picker, it is reflected in the statistics and browser activities, as expected. However, if I change the deck in statistics or in the browser, it doesn't influence other activities - is this expected?

**Comment by mikehardy** [comment]
Sorry for the delay - codewise, looks fine - going from an intent to a shared preference certainly simplifies things. Thinking theoretically about performance since the first use is a write to the value on startup that means memory state is coherent with disk from the beginning so this will never wait for a disk read and since you used apply vs commit, won't wait for a write either. Neat state-passing trick, seemingly without negative consequence.

I personally prefer clarifying parentheses but significantly less than I hate talking about formatting preferences... motivation is just that it doesn't worsen the signal to noise on our current static analysis stuff which is trending dow. And codacy will chirp if it does

Looks good

**Comment by timrae** [comment]
Thanks, the main point for posting the link was the new business logic, I'll make a PR for this once the other one goes through
