### ISSUE TITLE
Changing deck in Browser and Statistics changes the currently selected deck

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5010]
###### Reproduction Steps

1. Start from Deck Picker with Deck A selected
2. Open Browser or Stats
3. Select Deck B
4. Go back to the Deck Picker

###### Expected Result
Deck A is still the selected deck

###### Actual Result
Deck B is the selected deck

This is strongly related to #4999

**Comment by timrae** [comment]
> and #5007 (fix for #4999 which is related) explicitly changes the behavior so that your Actual result is the expected result.

I haven't tested it, but from looking at the code I don't see how that is possible

**Comment by wujek-srujek** [comment]
tl; td: I think that my #5007 change might not be desired at all as it changes the behaviour as it is defined now. Also, it has a lot to do with the way I use Anki and might not al all be what other users expect.

Long story:
I always (and today is my 1199th consecutive day ;)) thought it was supposed to work the way I changed it to, i.e. wherever you change the deck in any of the views, it becomes the 'current deck' in all the other views. I think it used to work like this for a long time, and the behaviour might have changed recently. I wasn't aware of the 'save current deck per activity' behavior.

I also don't really know what desktop Anki does during reviews, I only ever use it for card creation and search for card refinement and have done very very few reviews with it. But I've just started it (version 2.1.4) and it seems that:

1. The browser is completely 'detached' from current deck settings - at my computer, it always starts empty, with all filters cleared, the search field has focus, and a search is performed collection-wide, i.e. without being limited to any particular deck. There is no way to set the 'current deck' and influence the picker or statistics. I never noticed that before as when I open the browser simply adding input and pressing enter searches for the words I want and is not as disruptive as having to pick the deck on the phone. The way I use the browser, I guess 'all decks' in AnkiDroid would work just as well, though. The one difference I would see as an issue with AndiDroid's browser is that the desktop app starts with empty search results by default and the search field is focused, whereas AnkiDroid pre-fills the results, which in my case takes some time to initialize (as I have quite a few notes), and is pretty much 100% of the time not what I want, and so I need to pick the deck or refine the search _every time_. Also, the user needs to touch the 'search' button to land in the input field, which also kind of disrupts my workflow.
2. The stats window doesn't allow changing decks either, I just have the options for current deck and collections, and time settings.

I guess my expectations were what they were because of the 'enhanced' actions possible in AnkiDroid: I always expected the deck choice in statistics to influence the deck elsewhere. I might expect that in the desktop app as well but it doesn't allow it as of now, so I don't have to think about it. But, when I go to statistics in the desktop, sometimes I do search for the option to change the deck to see its stats, but this might be caused by the fact I use AnkiDroid so much.

**Comment by wujek-srujek** [comment]
Yeah, my change doesn't fix this issue; if anything, it makes things worse, although consistent.

**Comment by timrae** [comment]
@eginhard 

According to the git history, it seems this is introduced in #782 actually. I'm not really sure why we call `getCol().getDecks().select()` when the user changes the selected deck in the browser... Does something in libanki require it? Or is desirable for some other reason?

**Comment by timrae** [comment]
> at my computer, (anki desktop) always starts empty, with all filters cleared, the search field has focus, and a search is performed collection-wide, i.e. without being limited to any particular deck.

It seems from a UI perspective, the Anki Desktop browser is optimized for two actions:
1. Listing all cards in the current deck (`deck:current` filter is applied if you press search key on opening the browser)
1. Searching for something in all decks (`deck:current` filter is removed by typing a search term on the keyboard)

**Comment by wujek-srujek** [comment]
I wasn't aware of the 'go to browser and click' shortcut but I never bothered to actually read the default text in the filter...
But, this means using the current deck in the browser in AnkiDroid is more consistent with the desktop app, right?

**Comment by eginhard** [comment]
@timrae 
No, nothing relies on that. The main issue appears to be that we have different intuitions on what the ideal behaviour should be. I think it's sensible for AnkiDroid to update the current deck also in the browser and statistics to be always consistent because otherwise the selected deck could appear to jump randomly when changing between them (on the other hand it seems natural to me that the selected deck in the deck picker might change when returning from the browser). In Anki Desktop this doesn't arise in the same way because the browser is always launched in a separate window and statistics doesn't allow changing decks at all. So in this case consistency with Anki Desktop is not necessarily relevant because the UIs are very different.

**Comment by timrae** [comment]
> I think it's sensible for AnkiDroid to update the current deck also in the browser and statistics to be always consistent because otherwise the selected deck could appear to jump randomly when changing between them

Sorry I don't really understand, you're saying that you think that when changing the drop down deck selector in browser/stats, the "current" deck should also be updated, right? What would be jumping randomly if we didn't do this? 

Personally I see the "current" deck semantically as the one which is currently being reviewed, and the drop down selector in the browser simply as a user convenience to avoid typing `deck: xyz`.

**Comment by mikehardy** [comment]
That's the nut right there - it's personal preference. I like the selected deck being a unified virtual thing that's shared amongst the screens FWIW

**Comment by eginhard** [comment]
It looks actually like I just modeled it on this change, where the same issue was raised: https://github.com/ankidroid/Anki-Android/pull/766
So I think for the browser the implementation doesn't really matter, but for the statistics libanki cares.

**Comment by timrae** [comment]
Ah right, so it's just the stats and scheduler packages that use that `decks.current()` state variable I guess.

@dae 

Don't you have any plans to allow changing the deck for the statistics from within the statistics window itself? In libanki the stats constructor already takes a boolean parameter for "all decks", it probably wouldn't be that much work to take a deck id instead and take `None` to mean "all decks", then it wouldn't need to use the current deck state variable, and you wouldn't have to go back to the deck list and click on a deck to view its stats.

**Comment by timrae** [comment]
Oh actually it seems the python and java are quite different now

**Comment by dae** [comment]
Might be nice to have, but not a high priority.

**Comment by timrae** [comment]
I started working on getting deck specific statistics without changing the selected deck, but it didn't immediately work as intended, and then I got distracted with other things.

**Comment by timrae** [comment]
Ok I've got the stats working now without changing the libanki selected deck. So I think now we just have to specify exactly what the intended behavior is in browser and stats, and implement it on top of what I've done.

**Comment by mikehardy** [comment]
@eginhard please correct me if you disagree, but I think we're both on record as thinking that the picker + browser + stats "current deck" is mentally a single thing and it would be nice to have that current deck be what shows up consistently as you switch between the activities if that were possible. As with most individual preference related things, everyone can disagree, and my taste might be questionable, but there it is...

**Comment by eginhard** [comment]
Yes, that would seem logical to me. At least when the browser and stats are entered, I'd expect it to show the deck that was "active" in the previous activity (picker, reviewer, browser, stats). When going to the deck picker, it's probably best to retain the highlight on the current deck, i.e. the one that was studied last. This is consistent with Anki Desktop then.

**Comment by timrae** [comment]
That's more or less what I've done if I understand correctly, just need to finish it off, do some testing, and make a PR
