### ISSUE TITLE
Please get rid of red/green dots after each card.

### ISSUE THREAD

**Issue by reggusdorf** [ankidroid/Anki-Android#5084]
I apologise if I am not putting this in the right place. I would be most grateful if you could get rid of (or add a way to turn off) the red/green dots that appear and disappear for a few seconds after each card as they can be distracting.

Thank you so much!!

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Hi thanks for the suggestion. The dots give you feedback on which answer button was selected, which is important on a mobile device because sometimes we accidentally push the wrong button. We will definitely not be removing the dots, and I don't really want to add even more clutter to the preferences, so it's unlikely that we'd provide a way to turn it off either, sorry.

I believe someone in the community is working on a reviewer plugin that gives a more custom reviewing experience, so you might like to keep an eye out for that in a future AnkiDroid version, as it will likely not have dots and give many more options.

**Comment by mikehardy** [comment]
This template project might be of interest https://github.com/qwiglydee/anki-interactive/wiki - works with current AnkiDroid, replaces all the visible stuff during review if I understand correctly
