### ISSUE TITLE
allow cloze deletions without numbers

### ISSUE THREAD

**Issue by jakov** [ankidroid/Anki-Android#5090]
###### Reproduction Steps

1. Make card of close type.
2. Write content like "The chemical structure of water is H2O."
3. Replace the facts in question with the cloze syntax, e.g. "The chemical structure of {{c::water}} is {{c::H2O}}."
4. number all the cloze deletions: "The chemical structure of {{c1::water}} is {{c2::H2O}}."

My feature request would eliminate step 4 in those cases where there's no need to connect them (i.e. where every deletion is on a separate card).

###### Expected Result

"{{c::water} is {{c::H2O}}" should automatically be saved as "{{c1::water} is {{c2::H2O}}".

**Comment by mikehardy** [comment]
Have you tried it using nothing but 'c1' ? The last time I looked I think repeating the same number may work - either way for cloze deletion syntax we must behave the way upstream Anki Desktop works, so the fundamental question for AnkiDroid is - how does Anki Desktop handle this? If we do something different - then the difference should be specified here as an issue, if not, then this will be closed as won't-fix because it would harm interoperability

**Comment by jakov** [comment]
using c1 every time makes the deletions go in sync, i.e. there are multiple deletions on one card then.

without changing the syntax at all, ankidroid could replace the "c::", "c::", "c::" with "c1::", "c::2", "c3::" whenever you save a card without numbering the clozes.

**Comment by mikehardy** [comment]
feedback not received, can re-open if it comes in later

**Comment by jakov** [comment]
Anki desktop has a button for adding clozes next to the buttons for formatting and images.

**Comment by rgamici** [comment]
> without changing the syntax at all, ankidroid could replace the "c::", "c::", "c::" with "c1::", "c::2", "c3::" whenever you save a card without numbering the clozes.

You need the number to specify with deletions should be shown, because you may hide two parts for the same card.
For example, "{{c3::Google}} was founded in {{c2:September 1998::when}} by {{c1::Larry Page}} and {{c1::Sergey Brin}}
