### ISSUE TITLE
Consistency with Anki: show "1000+" new cards instead of exact number

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#5092]
If you have 1088 new cards in a group, Ankidroid shows "1088" in the *New* column.
Instead, Anki Windows shows "1000+". 

For consistency, how about adopting the "1000+" format?

**Comment by mikehardy** [comment]
@timrae this is a taste question but does fall into that "do we conform exactly with upstream or not" category where we usually lean upstream...

**Comment by werkn** [comment]
@timrae @mikehardy 
I didn't open the issue but I just populated a dummy deck on the **desktop app** and the following is the appearance for a deck having 1500 cards in it.

### New Cards
<img width="371" alt="capture" src="https://user-images.githubusercontent.com/10902433/49561590-50ac6d00-f8d5-11e8-9ed9-8f03e4a8b387.png">
 
### Due Cards
<img width="374" alt="capture2" src="https://user-images.githubusercontent.com/10902433/49561653-89e4dd00-f8d5-11e8-99c9-2eb419741011.png">

Seems fairly trivial and if you decide on moving forward I would be happy to provide a fix.

**Comment by mikehardy** [comment]
I like the general rule of "we do what Anki Desktop does" with reasonable exceptions for things that are platform-specific, because it makes it easy to rule yea or nay on issues and keep our issues list clean. It seems like it makes it more difficult to justify applying the rule when closing an enhancement request when there are obvious opportunities like this to conform, so I would go for the fix as a vote. But I'm only really explaining my reasoning because @timrae is the ax here - years more history and wisdom keeping things tasteful, so I'm more curious on his take on my reasoning, and what he thinks on this issue. I'd wait for his take.

**Comment by timrae** [comment]
Is this new behaviour on desktop? I didn't notice it before, that might just be because I've never set my study limits that high though. There is another place in the app where we decided not to follow desktop behaviour on this specific issue. If I understand correctly, the large values will only be shown when the user explicitly uses extremely large values for the limits. In such a case I would imagine they want to see the actual number...? What's the rationale for hiding them other than just following Anki desktop?
