### ISSUE TITLE
Fresh install getting treated as upgrade

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5106]
###### Reproduction Steps

1. Uninstall latest alpha
2. Reinstall it
3. Open it

###### Expected Result
Database check not invoked

###### Actual Result
Database check invoked

**Comment by timrae** [comment]
It seems we have allowBackup=true in the manifest so it must have been enabled for years. Maybe there was something wrong in my google drive up until now because I'm sure I've had to re-enable all my settings everytime I do a uninstall / reinstall

**Comment by timrae** [comment]
It's not really clear to me whether or not we should or should not be backing up the version upgrade related values. Considering db checkpoints are pretty rare and preference checkpoints more common, I'm leaning towards continuing to back them up as we currently do, making this a won't fix issue.

**Comment by mikehardy** [comment]
Version should be in a not backed up place because it is per device I think. I believe we can specify stuff to ignore and out the version by itself? Or version in the database? That's where it usually is anyway

**Comment by timrae** [comment]
I dont know if/how Google handles users that concurrently have multiple devices with different settings for example... I would assume they store the different files for the different devices in separate locations and then just choose the most recent one when a user is re-installing on a new device. I don't think they provide any way to choose which device to restore the user data from.

In the case of preference upgrade checkpoints, we should be comparing the current version of the app with the version of the app that was used to generate that set of preferences, so I think it does make sense to backup those version numbers. For DB related checkpoints though, I think we should be storing additional version numbers in the db itself, and using those.

**Comment by timrae** [comment]
Maybe we could add some functions to `Collection` to facilitate this:

`@Nullable Long getAnkiDroidVersion()`
`void setAnkiDroidVersion(@Nonnull Long)`

**Comment by mikehardy** [comment]
When contemplating schema+data version it's possible there are multiple changes in each version, and if done right each change would be in a transaction, would be separate and would be tolerant of failure. They may not be idempotent though, so if you do 2.9.0-migration1 but OOM on 2.9.0-migration2 (or something), you haven't setAnkiDroidVersion(2.9.0) yet (as proposed above) and you'd re-try 2.9.0-migration1. For that reason all the migration tools I've used or written treat migrations as a list of changes to apply, independent of app version, and the app just bundles all the changes it expects, and on startup whatever changes are discovered are applied. So you have more of a getCurrentMigrationLevel() / setCurrentMigrationLevel().

The devil is in whether and how you do classpath auto-discovery (so implementation is easy), what types of migrations you support (.sql only, or also defined in the implementation language like .java), how you handle branches (stable+hotfixes while dev is happening with alpha releases), whether you do downgrades. That's why I'd just integrate a well-tested one (like flyway) for db mods (and prefs really) and be done with it instead of sussing out all the use cases bespoke here

**Comment by mikehardy** [comment]
Would really want the #5103 change allowing solid testing against databases prior to contemplating it though - after my startup logic fracaso prior :-)

**Comment by timrae** [comment]
Thankfully we haven't had to deal with any db schema changes other than the v1 --> v2 db migration which was a huge mess. I don't think I'd want to introduce a new tool that I don't understand into the app upgrade flow just as we are approaching a 2.9 beta, but maybe for 2.10 if it's useful. In the meantime I think we need to solve this issue of only doing the db integrity check once for a given database for v2.9 by storing something in the db itself.

**Comment by mikehardy** [comment]
Agreed there. Luckily the best tools are easier to understand than our current flow (from my perspective) but even then it's fresh tooling which should rightly be a no. Integration of something like flyway in the future would make cleaning up any decisions here trivial as well so literally whatever would work here would be fine for me now + future

**Comment by mikehardy** [comment]
The related PR was reverted so 2.9 could ship, just reopening to track for an eventual 2.10

**Comment by david-allison-1** [comment]
@mikehardy Is this still active?

**Comment by mikehardy** [comment]
Perhaps? But it was never fully isolated and the fix would be storing database versions in the database and doing real migrations and such, a PR that was already proposed and had promise but was shot down. I may resurrect it at some point but not a priority at all. The consequence is possibly too many database checks, which is performance more than correctness
