### ISSUE TITLE
JS codes don't work on AnkiDroid

### ISSUE THREAD

**Issue by DishKun** [ankidroid/Anki-Android#5123]
###### Reproduction Steps

I added some JS to the template to replace some characters in a word into "_". It works well on desktop/web/iOs, except android.
the codes is below:
![image](https://user-images.githubusercontent.com/6910173/48824519-7eef6000-ed9f-11e8-9f8c-14867e938cac.png)

###### Expected Result
the word should be like "n__t_al",not "nuptial"
![qq 20181121144322](https://user-images.githubusercontent.com/6910173/48824339-f53f9280-ed9e-11e8-8dfc-77eb84965d99.png)

###### Actual Result
JS codes don't work here on my android phone.
![qq 20181121144533](https://user-images.githubusercontent.com/6910173/48824359-fffa2780-ed9e-11e8-85e1-ca60658b5055.jpg)

###### Debug info
My version is 2.8.4

**Comment by mikehardy** [comment]
@timrae - what do you think about making the changes that enabled web debugging (open the webview for debug, write out the HTML to /sdcard/AnkiDroid) a visible-but-disabled preference in advanced preferences on non-debug builds? I can't think of a negative side effect, and since the ability to develop JS like this is part of the platform, seems like providing the ability to debug it would match it well. I can't imagine how to quickly debug issues like this otherwise - it's be much easier to to tell people doing JS development to toggle that and iterate individually.

**Comment by mikehardy** [comment]
Hi @DishKun - you can see the source components for how the reviewer page is built, here: https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/assets

You can see an example of the HTML code we emit here: 
[card.html.gz](https://github.com/ankidroid/Anki-Android/files/2605727/card.html.gz)

If you check out the code and build a debug version for yourself, you'll see we have HTML/JS debugging abilities available according to these instructions: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

I'm afraid beyond that I'm not able to help with custom javascript - I think it's possible and you probably are just missing a hook like implementing onLoad() so the code runs but I can't be sure. It is worth noting that desktop/web/iOS is developed by one group and we (AnkiDroid) are separate so sometimes the functionality differs - I think they have a formal javascript hook chunk for instance, maybe enabling this - whereas we don't. So it's not a bug in AnkiDroid per se, though maybe an enhancement in order to match Anki Desktop functionality

**Comment by timrae** [comment]
> what do you think about making the changes that enabled web debugging (open the webview for debug, write out the HTML to /sdcard/AnkiDroid) a visible-but-disabled preference in advanced preferences 

Sure sounds good to me!

**Comment by mikehardy** [comment]
@DishKun - you should join the alpha channel now (no worries, it's going to be beta soon and is forward- and reverse-compatible in case you need to leave it) following these instructions: https://docs.ankidroid.org/manual.html#betaTesting

Then whenever @timrae does the next alpha release follow these updated instructions (to match the pull request I just merged) in order to have pretty easy debugging capabilities for your javascript: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by mikehardy** [comment]
@DishKun I believe you got some feedback on the forum, but if not and you still need to debug this, my change that exposes debugging utilities was just pushed out as a publicly available alpha build. Cheers

**Comment by kanjieater** [comment]
I haven't set up the JS debugger yet, but am running into the same problem as OP. Why is it that replacing nodes doesn't work on AnkiDroid but does on desktop?

**Comment by mikehardy** [comment]
no idea, but the card is running inside of a WebView which these days (read as: in most modern devices, careful if you have a very old device) means a pretty up to date Chromium web container with all the modern everything. I'm not sure what exactly AnkiDesktop uses to render, so there may be some web technology skew between the two platforms, but we're not doing anything special - basically if Chrome runs it, we should run it (whatever it is)
