### ISSUE TITLE
AnkiDroid launching with slide up animation

### ISSUE THREAD

**Issue by TesseractCat** [ankidroid/Anki-Android#5143]
###### Reproduction Steps

1. Use a launcher that lets you adjust the default app launch animation.
2. Set that animation to something other than "slide up"
3. Launch AnkiDroid for the first time (make sure it isn't still stored in RAM)

###### Expected Result

AnkiDroid should launch with the default chosen animation.

###### Actual Result

AnkiDroid uses a slide-up animation.

###### Debug info
```
AnkiDroid Version = 2.8.4

Android Version = 8.0.0

ACRA UUID = 56bbd24a-3865-46b3-855a-440a0bdcd40a
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Interesting - I had no idea this was even a thing. Can  you give a specific example of a launcher that does this that we can use for free to reproduce it, and the exact way you configured it?

**Comment by TesseractCat** [comment]
[Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en_US) is free, and allows you to configure default app launching animation through `Nova Settings -> Look & Feel -> App Animation`. Keep in mind this issue only occurs when launching the app if the app is not already running.

**Comment by mikehardy** [comment]
Got it - thanks. I actually use Nova but didn't know about this feature. I can confirm it happens as you describe if I do this:

Nova Settings -> Look and feel -> App animation -> Zoom (as opposed to the system default)

Other apps zoom from the icon to the full screen, AnkiDroid always slides up.

I can't say this is a high priority :-), but it does exist :thinking:

**Comment by TesseractCat** [comment]
Issue is still present as of version 2.11.3

**Comment by mikehardy** [comment]
That was a useful pointer into the code but not the root cause.

There is some semi-fancy animation stuff going on in AnkiDroid but it boiled down to one well-intentioned line in IntentHandler that set an animation on launch intent handling, thus overriding the system or launcher provided animation.

PR coming in a moment

**Comment by mikehardy** [comment]
Ok @TesseractCat PR is made - because I think you also realize this was probably not the most useful thing either of us will do all day, may I ask for a small exchange of value in return, please please? 

We have had users asking us what the whole "flags" thing is since we added them but they aren't in the manual at all. Can you look for any where "mark" is used in the manual and add similar docs but for the new flags? Like https://github.com/ankidroid/ankidroiddocs/blob/master/manual.asc#action-bar-2

Github makes docs PRs really easy, and flags are just integers, zero through five, with zero meaning "no flag" and the others like so https://github.com/ankidroid/Anki-Android/blob/dfd621310f8051bd9b6a06fba7a20834454a792e/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1993-L2001

And they can be searched in the card browser (similar to searching for marks via 'flag:1' etc
