### ISSUE TITLE
Show accuracy during reviews

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5185]
Other srs/review apps show the accuracy percentage during reviews, which I find very useful.

So for AnkiDroid: 
in the top right of the information bar (where the number of new/wrong/old cards in the review queue is shown) would be a good spot to show the accuracy of the current session in percent.

That would be very useful since the normal way to get the accuracy is quite complicated: go to statistics, choose the deck and search for the accuracy number within all the other information.

Also the accuracy can be a motivation to keep on with reviews ("I'm not going to stop until I reach XX percent")

Pics here: https://groups.google.com/forum/m/#!topic/anki-android/JtodgZb8ueM

**Comment by mikehardy** [comment]
I could see implementing this, but I would want to make sure the definition of "accuracy" is very well-defined. In AnkiDroid statistics all I can see that is accuracy-related is the "Again count". By accuracy then do you mean ("review count" minus "again count") divided by "review count"? And how would you define the period of time over which to do the calculation? Just the time in the reviewer without leaving (that seems wrong...)? Or the time since the start of the current "AnkiDroid day" as configured in preferences (this seems like the easiest / most-likely-to-be-implemented)? Or some other period of time? Should it cross decks or just be in the current deck (I'm guessing current deck - then it could reuse current stats code pretty well)

**Comment by Anthropos888** [comment]
Other apps (and I think this makes sense) implement the accuracy display like this:

- accuracy is based on the current review session. For AnkiDroid: the time in the reviewer without leaving it 

- based on one deck (including subdecks): only the one that the user clicked to review

- if leaving the reviewer and continuing the same (or any other) deck later, the accuracy starts new (0/0 cards, 100%) again for the remaining cards

- accuracy is based on all reviewed cards in the current session: number of correct (ease > 1) cards multiplied with 100 and divided by the number of total cards reviewed in the current session. In sql: ( ( SELECT count (*) 
  FROM revlog (the current session)
  WHERE ease > 1 ) * 100.00
 ) / count (*)

So when I did 10 reviews and I got 9 correct, it would show me "90%". 

- there is no time based calculation, you just need the numbers for "total reviewed cards" and "correct answered cards" of the current session in the reviewer without leaving it.

To be clear: when doing reviews the only useful accuracy information is the accuracy for the current session. This accuracy should not be mixed with other deck's accuracy or total accuracy on that day etc. These numbers can be searched via the statistics.
