### ISSUE TITLE
Request: Additional full screen mode

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#5195]
I'd like to ask for the "full screen mode" to be extended by one/two options with an effect between the two present active settings of "hide system bars" and "hide system bars and answer buttons":

1. Omit the verbal descriptions on the answer buttons – anyone who's used Anki for a week knows what they mean – but nonetheless leave them in (with only the time on them), thus halving their height.

2. Combine 1. with hiding the remaining cards bar as in the current "hide system bars and answer buttons".

Essentially, both would mean saving maximum of screen space (and minimum distraction) while still not being required to use gestures during learning.

(Dunno what the English terms are as my "language" setting gets entirely ignored. 2.9a56)

**Comment by mikehardy** [comment]
I can understand this request as I always forget gestures personally (maybe I should make some flashcards for them !?! ) so I prefer the buttons, but the full screen is otherwise pretty cool. Not saying I will do this or anything, just saying I understand and I will certainly leave this open for now to see what others think.

As for the mention on language settings - indeed: #4729 tracks that

**Comment by tjbrn** [comment]
Related #5389
