### ISSUE TITLE
Changing time zone breaks statistics

### ISSUE THREAD

**Issue by n1kl** [ankidroid/Anki-Android#5207]
###### Reproduction Steps

1. use anki with UTC+0 at 10 in the morning
    - answer a few cards
    - open statistics with hourly usage, everything is still correct
2. change to UTC+X example + 6:
    - open android system for date and time and choose different time zone
    - jump back into the open anki app
    - go out of the statistics view and back to reload ui
3. hourly usage statistics of anki tells me i was learing at 10+6 = 16h in the afternoon

###### Expected Result
Local time of usage

###### Actual Result
UTC time of usage

###### Research
[ x ] I have searched for similar existing issues here and on the user forum

**Comment by n1kl** [comment]
Similiar issue with next day starts N hours after midnight changes automatically to N+X hours after midnight by changing the time zone.

**Comment by mikehardy** [comment]
Hi there! Thanks for taking the time to report this.

To make sure I understand this correctly, can you elaborate on step 2 and include every step? I think when you say "change to UTC+X" you mean open system preferences, change system timezone etc. If you close Anki and restart it, or if it is running the entire time is also useful information

Finally, if you sync with AnkiWeb and check on Anki Desktop, it would be useful to compare if those are already installed and easy to check for you. I mention that last bit because we have a related issue about how we are synchronizing those specific bits of data with AnkiWeb (#3488 at least, maybe one other)
