### ISSUE TITLE
Showing answer card suddenly lags some seconds

### ISSUE THREAD

**Issue by PieterVanB** [ankidroid/Anki-Android#5213]
###### Reproduction Steps

1. download deck: https://ankiweb.net/shared/info/211246396, the "Japanese Core Vocab" deck
2. Click 'show answer'
3. Observe

Note: it never lagged up until yesterday. No font changes, or deck size changes.

###### Expected Result
instant answer

###### Actual Result
~300ms estimated lag
- answer page loads
~ 300ms estimated lag
- answer loads
~300ms estimaed lag
- question (above answer) and example sentences (below answer) load

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 6.0.1

ACRA UUID = 62f5b6ab-39e7-42d7-8092-8a460f5d0995

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Chrome just updated though, and we have seen a similar lag with font loads. Can you try using the system font as a test? I recognize this isn't a solution but it would show us the font render is or is not the pr9

**Comment by PieterVanB** [comment]
Anki (app) >Settings > Appearance > 'Default font' shows 'System default' already.

I tried changing it (to OpenSans-Bold), Anki still exhibited lag.
Changed it back to System Default, Anki still exhibited lag.

**Comment by mikehardy** [comment]
This was noted by @Anthropos888 also and he worked around it by uninstalling chrome updates. It was a chrome update that did it. There is a related (closed) issue here related to rendering Japanese and chinese fonts where you can see how to debug it. With the chrome team. Even if you specify system fonts for the app your card templates can load whatever they want with fonts or Javascript so it is likely that.

**Comment by Anthropos888** [comment]
Very interesting:
1) yes, I could solve the performance issues by uninstalling Chrome updates
2) it seems that now also non-system fonts loaded via CSS (Japanese in my case) are loading way faster. In the browser preview they are shown almost immediately. In the reviewer there's only a short lag of around 100ms instead of ~500+ before (and ~2000+ with the newest Chrome version which seems to be really buggy)

That means, another "workaround" for showing Japanese fonts is to simply uninstall all Chrome updates (the resulting version may differ on each phone). Maybe it's worth mentioning that in the manual or here at github.

BTW: I don't know if this link was posted before, but for my cards I used this list of Android fonts (with pictures) as a reference:
https://stackoverflow.com/questions/19691530/valid-values-for-androidfontfamily-and-what-they-map-to

**Comment by mikehardy** [comment]
Yes - item 2 you mentioned above was because of this regression (that they declined to fix) - #4856 

I'm not really sure what I learned on that linked issue (and the linked + linked issue in the chromium tracker) except that they were of the opinion a lot of fonts were simply terrible and were loading slowly (even though they were fast before?). So maybe if you try other fonts you can get fast renders even with an updated Chrome?

I'm not sure if there's anything else we can do because I checked and we do actually re-use the WebView in a single review session. After the first card is reviewed with a given font, it should have the font loaded and be fast? Maybe there is some type of caching we could do that I'm unaware of

**Comment by Anthropos888** [comment]
I just tried again with a Japanese font of 4.7MB loaded via CSS. It's loading very fast now in the reviewer, almost no delay. Chrome version is 64.

With the newer version of Chrome (>64 but <72) I couldn't use this font cause it was loading way too slow, around 500-1000ms.

Also there was no caching, every card needed exactly the same time to load. (I know that because my CSS animations are set to 500ms and the fonts needed more time than this to load)

As for now, I'm totally satisfied with Chrome 64 + AnkiDroid, but it's obviously not the solution to tell everyone to downgrade Chrome. 

Regarding the font loading performance: If AnkiDroid could cache the fonts in order to load them faster starting from the second card, this sounds like a good solution.

**Comment by PieterVanB** [comment]
@Anthropos888 Could you tell me in a few sentences how to uninstall chrome updates on an android? 

I've done settings > app > chrome > uninstall updates. I presume i now need to use an apk mirror to download the specific version i want and then disable updates?

**Comment by PieterVanB** [comment]
I've got Chrome version 52 on my phone right now and though the lag is less prominent now, it is still quite there. 

Last week there was zero lag, even with Chrome 52 there is still some. 
Perhaps ~200ms instead of the previous ~300-400ms.
The chrome trick helped but the problem is definitely not resolved.

**Comment by Anthropos888** [comment]
Which version do you have now? You can uninstall updates via PlayStore (for system apps it's the button left to the update button) or via settings as you did it. If you have any version below 72 it should be fine now. No need for further steps.

**Comment by PieterVanB** [comment]
Chrome version 52.0.2743.98

The lag is still very much existing, unfortunately. It did not resolve my issue. Could it still be the fonts?

**Comment by Anthropos888** [comment]
Interesting. For me Chrome 64 + Ankidroid 2.9alpha60 works just fine. Before I had Chrome 72 and the exact same problem as you, uninstalling Chrome updates solved that problem completely. Sorry to hear that it is different for you. Maybe you give the newest alpha a try?

**Comment by PieterVanB** [comment]
Might be useful: Anki is still 2.8 on my phone.

Doing a quick backup before i try to install 2.9alpha60.

**Comment by Anthropos888** [comment]
If you join the Ankidroid alpha testers group you'll get your 2.9 update and all further updates via PlayStore, no need to install from github

**Comment by PieterVanB** [comment]
Installed 2.9alpha60 succesfully. Chrome still on version 52. Lag still exists. Changing font has no effect.

**Comment by mikehardy** [comment]
I still experiencia no lag on Android 9, all updates (chrome 72.0. 3626.76)., alpha61. It's something in your collection. If you could share an export with a minimal reproduction we might move forward otherwise I can't reproduce

**Comment by Anthropos888** [comment]
Mike, I can confirm that Chrome caused the lag on my phone. Here a gif that shows the cards with AnkiDroid 2.9alpha60 and Chrome 64

https://imgur.com/Eddttdx

The font is 15MB and needs around 2s to load on the first card. All other cards are super fast

After that I updated Chrome again to version 72, now every card loads 2-3s, everything is way slower than before:

https://imgur.com/FWdthUD

**Comment by mikehardy** [comment]
Seems like it should do it thanks. The next step (if anyone has time before me) is to follow the Javascriot/html debugging steps from our development guide on the wiki to get the actual rendered HTML card and try to reproduce it in Chrome on the desktop, then we can either fix easily or open an upstream issue. This is user accessible by enabling html/js debugging in advanced preferences by any user if you want to try it.

**Comment by Anthropos888** [comment]
BTW: both the Anki and AnkiDroid manuals say that only TTF fonts are supported. That's not true. The font I use in the examples above is OTF and it works fine on both Anki and AnkiDroid.

Now that I can use these fonts I enjoy AnkiDroid even more (I couldn't use it before due to the bad performance). So please mention in the manual that OTF fonts "might" work as well, or users will limit themselves to TTF which is not necessary.

**Comment by mikehardy** [comment]
Hi @Anthropos888 - could you try a PR for the docs? I have no experience with altering fonts and PRs for text files can be done right from within the GitHub interface - it handles all the branching and everything if you just hit the "pencil" icon while viewing the file you want to edit on a desktop browser - I think it is this one: https://github.com/ankidroid/ankidroiddocs/blob/master/manual.asc

**Comment by Anthropos888** [comment]
My phone got an update to Android 9 Pie (from 8.1) and now the default version of chrome is 70 and AnkiDroid is so slow that I can't use it productive. I can't downgrade to Chrome 64 anymore (which was fast).

Anything that Ankidroid can do to provide a better support of newer Chrome versions?

The only possibility I see for me is to reset my phone to Android 8.0 but then I'll loose all data as well. Not a good compromise.

Btw: Ankidroid crashed many times already on Android 9 without sending a report. Also the new features of Pie are really horrible, everything takes 5x more time. So I really might go for a factory reset.

**Comment by timrae** [comment]
> Anything that Ankidroid can do to provide a better support of newer Chrome versions?

Not that I'm aware of

> The only possibility I see for me is to reset my phone to Android 8.0

Well presumably you could also just find a different font that doesn't suffer this issue

**Comment by timrae** [comment]
How does Google Noto Japanese work for you?

**Comment by Anthropos888** [comment]
The font is unfortunately just one part of the problem. But even with default font everything is loading slowly (as described in the first posts): JavaScript, pictures, sound.

Only plain text cards without any modifications work fine, but that's obviously not a solution.

Do you have an idea why with Chrome 64 the font was cached after showing the first card, so that all other where loading very fast? Why does Ankidroid with Chrome 70 and above not cache fonts anymore?

**Comment by timrae** [comment]
I exported some cards from my Japanese deck that use Google Noto and load without issue on the latest Chrome. Do they lag on your device?

[Test.apkg.zip](https://github.com/ankidroid/Anki-Android/files/2896345/Test.apkg.zip)

**Comment by Anthropos888** [comment]
Can't open zip on my phone, I'll try it later on PC. But I'm sure it will work without issues if it's a simple deck.

If I don't use Javascripts, CSS animations, special fonts and pictures, everything works fine. But I can't sacrifice these features just for a better performance.

I'll try to find a way to install Chrome 64 on my device and report if I succeeded.

**Comment by timrae** [comment]
It's not a zip file, I just added that to the apkg file to keep GitHub happy. JavaScript,  CSS animations, and non-standard custom fonts are all completely unsupported features, so you're on your own there. Please feel free to open a pull request if you find an optimisation that works for you, or re-open the issue if it occurs even outside of "unsupported territory".

**Comment by timrae** [comment]
To reiterate what I wrote on the forum, the "official" solution for this is to change the font to Google Noto Japanese. Google Noto is the only font which is semi-officially supported by us. Anything else is at your own peril. Uninstalling chrome updates is not secure, and highly discouraged. Here is my personal card template that I use for Japanese Core n-k cards, you should be able to import it and use the font in your Japanese cards:

https://drive.google.com/open?id=1cMjppTtwdZZ7w2l8ZZQYNRMrCeyKBnYf

**Comment by tobia** [comment]
I replaced the (professional) Japanese font I was using with Google Noto and I get a similar slow loading. It's a bit less, say 300ms instead of 500ms (judging by eye) but it's still a lot, considering I'm using a fast device with plenty of RAM. The delay is at every card, front and back. The default font incurs no delay at all.

**Comment by timrae** [comment]
Do you see the delay with the cards in the apkg that I attached? The delay is on every card, or just the first card of the review session?

**Comment by tobia** [comment]
The delay is still there in your test deck, although it's reduced to 100-200ms. You can clearly see it if you add something to contrast with, in the device's default font:

    <div class=default>Default font</div>

    .default { font-family: sans-serif }

If you use Google Noto **Serif** JP, that one seems to show a more marked delay.

**Comment by timrae** [comment]
I double-checked my test deck with the Android emulator on Android Pie using both Chrome 69 (the default) and Chrome 72 (after updating Chrome). I agree that if I compare Noto with a standard sans-serif font on the same card, clearly Noto has a visible delay, but the delay is not very long, and I don't think this is a performance regression (i.e. I believe it's always been that way)...?

If you're sure there's been a regression in rendering performance using Google Noto, please post videos showing the difference with the two different chrome versions, ideally using my test deck, and also include the exact chrome versions used in the videos.

**Comment by Anthropos888** [comment]
> Noto has a visible delay, but the delay is not very long, and I don't think this is a performance regression (i.e. I believe it's always been that way)...?

Not with Chrome 64. See my gifs above. Everthing is super fast even with large external fonts. No lags after the font got "cached" for the first time.

**Comment by timrae** [comment]
Your gifs are using animations and a non-supported font, right now I'm only concerned with whether or not there is a regression in Chrome using Google Noto JP font, so I'll need you do some comparisons using my test deck

**Comment by Anthropos888** [comment]
Ok, I might be able to get a friends device to check it (my device can't go below version 70 anymore).

**Comment by timrae** [comment]
How does my test deck work on your device with 70?

**Comment by Anthropos888** [comment]
Yes, with lag of about 500ms.

Another question: is it normal that the import needs around 4 minutes for a tiny deck like this? 
And is there any way that I can delete the deck and the note type without forcing a full sync?

**Comment by timrae** [comment]
Presumably that's the time required to unzip and copy the font across on your device. It's a big font so I guess it's not totally unreasonable, especially if you have a cheap phone.

I definitely don't see 500ms lag on my device. So it could be something specific to your device.

I'm not sure about deleting the note type whether it causes full sync or not. AnkiDroid will warn you before taking any action that requires full sync though, so you can easily find out.

**Comment by Anthropos888** [comment]
I have a fast quad core and 4GB Ram. With standard font theres no lag at all. With your Noto font the lag (I'd say it's even more than 500ms) is so annoying that I would not do reviews with this deck. It's even slower than with my decks with loads of CSS, JS and large external fonts.

And there are many users with way slower and older phones.

**Comment by timrae** [comment]
I have a very average mid range phone (Motorola moto 4g) with 2GB ram. On my device it takes less than 2 seconds to import that apkg, and the Noto font renders instantly. Same on the Android simulator.

Please try it on your friend's device and let me know.

**Comment by Anthropos888** [comment]
Ok, thanks for that information. Then I'd like to see if clearing the app cache/memory changes anything. Just to make sure: I won't lose any collection data when I clear the Ankidroid app cache/memory, right?

**Comment by timrae** [comment]
Yeah your collection will not be modified in anyway

**Comment by tobia** [comment]
Something I've just discovered: compressing the font in WOFF or WOFF2 format seems to substantially reduce the lag. Additionally (coincidentally?) it substantially reduces the font size.

You can do that using the `sfnt2woff` and `woff2_compress` utilities, resp. from `woff-tools` and `woff2` Debian packages (or any number of online services I guess).

**Comment by Anthropos888** [comment]
Interesting, when I use an online converter with the Noto font I get a 3.2kB (!) small woff2 file and this one loads indeed without lag (what file size is yours?). But it looks exactly like the Android default font so maybe this small Noto woff2 file can't be interpreted by Ankidroid and it uses the default font instead.

When I compress my other fonts with woff2 the result is the opposite. The files are around 30% smaller in size but the lag is a bit longer. Seems that Ankidroid can handle ttf better than woff2.

**Comment by tobia** [comment]
@Anthropos888 then that online converter is bogus. Try to use the actual `woff2_compress` utility.

My font is Morisawa's "G-OTF Kyoukasho ICA Pro R" (7.2MB otf -> 5.6MB woff2) and it loads quicker in woff and woff2.

By the way, if anybody can recommend a smaller Kyoukasho-style Japanese font, that would be great. I tried using the one from the free Epson fonts (4.0MB ttf -> 2.0MB woff2) as well as "YuKyokasho Yoko Medium" taken from my MacBook (6.8MB otf -> 3.8MB woff2) but they don't work on Android, most probably because they are Type 1 / CFF internally, instead of TrueType / CID.

**Comment by tobia** [comment]
Ok, I managed to get the free Epson Kyoukasho font to work on Android. I opened it in FontForge, fixed some encoding jibberish in the Font Info dialog, and saved it again as TrueType, then I converted it to woff2.

This one (2.0MB in woff2) loads much faster, with a speed comparable to Noto Serif (while being a perfect Kyoukasho font suitable for studying kanji.) This seems to show that the lag on each card, the subject of this issue, is due to the complexity and/or size of the font.

While I had the font open in FontForge, I also deleted the (ugly) ASCII glyphs, so that English text will fall back to the device's default font. Unfortunately the license prevents me from distributing my changes, but they should be easy enough to reproduce.

**Comment by Anthropos888** [comment]
@timrae I imported your deck on my friends phone (Honor X6) with Android 8, AnkiDroid 2.8.4 and Chrome 72. The import was indeed done within 2 seconds.
However, the cards show the same delay as on my device (around 500ms). I then installed an older version of chrome (64) from an apk source, but this didn't improve the speed on my friends phone. So I was not able to reproduce the good performance that I had with Chrome 64 on my phone with Android 8 (where the fonts got cached after the first card so that all other cards where loading without lag). 

Also, clearing the cache and app memory on my phone didn't help anything.

I'll hope for upcoming Chrome updates then.

**Comment by timrae** [comment]
Can you show a video of this?

**Comment by Anthropos888** [comment]
Here:

[anki-noto.zip](https://github.com/ankidroid/Anki-Android/files/2923150/anki-noto.zip)

**Comment by timrae** [comment]
Ah thanks, actually I just took a look at my collection properly and realized that I haven't synced any of the media files on this device yet, so the Noto font was not actually loading (i.e. it was using the default font). Finally I was able to reproduce the issue on my Moto 4G. If Noto is having trouble loading then I don't think Google can use the "your font sucks" argument. It's quite a lot of work to submit a reproducible regression report to them though.

**Comment by mikehardy** [comment]
There is already a pretty complete and good reproduction attached to one of these issues - the old one I think #4856 - with a linked Chromium issue and it is even reproducible on Desktop. They closed it with the your-font-sucks argument but if we can show it with Noto then there's hope?

**Comment by timrae** [comment]
I'm actually not able to get the Google Noto font to load properly on Chrome for Android. Have you tried it?

**Comment by timrae** [comment]
(When I say "can't load Google Noto", what I mean is I can't figure out how to load an arbitrary custom font file on the file system with Chrome for Android.)

**Comment by timrae** [comment]
It seems it was just not loading when opening the html with my file explorer's content provider. I was able to reproduce the issue with Google Noto on both chrome for Android and Chrome for desktop.

**Comment by timrae** [comment]
I spent a few hours testing this today, and posted the results as a [comment on the upstream Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=866244#c21). It seems unlikely to get fixed on the Chrome side, unless someone puts the work in to find out exactly which build of Chrome introduced the regression. The most efficient way to do this is to use the `git bisect` tool, but even that's probably about half a day of messing around, which I'm not able to do, so one of you guys experiencing the issue will have to put in the hard work if you want it fixed in the long-term.

**Comment by Anthropos888** [comment]
Would it make sense to just download and try all available Chrome versions (i.e. on apkmirror) from version 55 to 70?

**Comment by timrae** [comment]
Yeah that would definitely help, but after that they'd also need to know
the exact build number to identify which code change caused the error

**Comment by kelciour** [comment]
As a temporary workaround, maybe this deck can be of any help. It's a slightly modified version of the test deck by @timrae https://github.com/ankidroid/Anki-Android/issues/5213#issuecomment-468229932 with a suggestion by @tobia https://github.com/ankidroid/Anki-Android/issues/5213#issuecomment-468346160 to make the delay more noticeable.
The Slow subdeck is to illustrate the problem and the Fast subdeck is an attempt to provide a workaround and reduce the delay a little bit :).
It's here - https://drive.google.com/open?id=1LoJOWVZ30Tb5-0SX8UjEp2bcTNsrNvaM

**Comment by mikehardy** [comment]
This would be extreme but I just cross-referenced https://github.com/ankidroid/Anki-Android/issues/4828#issuecomment-469863954 - and if the only solution to this was to alter Reviewer card loads so it was a DOM rewrite instead of a new page load, it seems technically possible on API>=23 at least. Similar to the other ideas, a stripped down example of each thing (including this one, though using slightly different APIs for the web message channel) could be done to show whether it was performant or not

**Comment by timrae** [comment]
I tried all of the font-display values, and it didn't help.

**Comment by timrae** [comment]
https://nakedsecurity.sophos.com/2019/03/06/serious-chrome-zero-day-google-says-update-right-this-minute/?fbclid=IwAR0t4kAoPOxrDa6dGPlx1CeuNrV6n3LJmYas28djWbZLOW2CCjMW3AEcvjk

**Comment by Anthropos888** [comment]
I fear the answer is 'no', but is there a way to install custom fonts into the Android (Pie) system on an unrooted phone?

**Comment by LorisB** [comment]
The answer is yes/no, because some phones (such as HTC, Samsung...)  and
custom ROMs (Havoc-OS, "many others"...)support that function root-lessly,
but generally that's not the case.

**Comment by mikehardy** [comment]
I looked at installing fonts as a suggestion briefly but it seemed like a no to me for un rooted phones

**Comment by timrae** [comment]
It seems the Chromium team are not very willing to put the time into doing the bisect on this, so unless they change their mind, moving forward with this issue will most likely require someone with a lot of time on their hands to build chromium for Android from source code, install it on an Android emulator, test loading of my sample html file with Google Noto in Chromium browser, and repeat a bunch of times using git bisect until the exact commit which caused the performance regression is found.

I don't have time to do that, but if someone here does, please join the issue on Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=866244#c22

**Comment by Anthropos888** [comment]
You described the issue very precisely on that chromium tracker, I just wanted to say thanks for still putting effort into this!

Regarding your previous post about the recommended Chrome update: will this risk persist even if Chrome is disabled (in app settings)?

To prevent forced Chrome updates I just disabled it and now Android System Webview (version 70) is my webview and I'm using a different internet browser.

Has Android System Webview the same vulnerability as Chrome?

**Comment by timrae** [comment]
Honestly, I don't really know the details of how Chrome and Webview are packaged on Android sorry, you'd be better off asking on the chromium tracker.

**Comment by Anthropos888** [comment]
Here some good news: the "Webview implementation" in the developer settings allows to choose one of the 4 supported Chrome browser which are 'stable' (72.x), 'beta' (73.x), 'dev' (74.x) and 'canary' (75.x). 'Android System webview' can also be choosen after the standard Chrome is being disabled, but in this case the Android System Webview it is based on Chrome 'stable'.

I tried all Chrome versions and 72.x - 74.x all have the same extremely bad performance with fonts, JS and CSS. Fortunately, Canary (75.x) has a very good performance. Fonts, JS and CSS are loading significantly faster than 72-74. The fonts load even faster than on Chrome 70. But still they are not cached (e.g. as in 59) and every reload of the webview will have a noticable lag. However, I'm using 10 TTF fonts in my decks (randomly set for each card) and the smallest one with 2MB is loading almost without lag.
(OTF and WOFF2, which are not officially supported, need indeed more time to load. Only WOFF is loading within the same time as TTF).

That said, for now 'Canary' is a good compromise for users with Android 9 who cannot downgrade anymore to Chrome <65. 

Assuming that any security issues which got fixed in the latest stable Chrome got fixed in Canary as well, Canary is for now probably the fastest and most secure Webview for Ankidroid.

**Comment by mikehardy** [comment]
That is fantastic news. Yes, anything fixed anywhere should be fixed in Canary as they I believe their process is to fix in Canary and backport to previous versions. Can  you write up your exact steps to get Chrome Canary installed and activate it for use in AnkiDroid? To make sure others can follow your work to see if it benefits them (and on what devices they can do it - by which I mean, how far back in Android APIs they can achieve this - back to Android 6? 5? I know 4 can't because my crap-tablet is stuck on ancient Chrome...you are on 9 so that's set at least)

**Comment by Anthropos888** [comment]
Setting up Canary as WebView is easy:
1) download it from PlayStore (https://play.google.com/store/apps/details?id=com.chrome.canary)
2) deactivate Chrome 'stable' in Settings > Apps > Chrome > deactivate
3) go to settings > developer options and choose Canary for 'Webview implementation'

Since Canary is getting loads of updates, it can be a good idea to backup the apk regularly (i.e. with Google 'files') in case the performance should drop again. Then it's easy to unistall it and re-install from the backup.

**Comment by aphirst** [comment]
I can confirm that at present, using Chrome Canary as the Webview implementation brings a large speedup to my decks (using either manually-supplied `Noto Serif CJK JP` or the `kanjistrokeorder` font). There is still a lag, but it is noticeably shorter than when using stable Chrome or the stock Webview. (I am running Android 9 on the current latest LineageOS.)

I haven't had chance to test out this "wof" approach which is also discussed here, but if I have chance later, I will edit my results into this post. I'd be curious as to whether on my setup I get an additional benefit there for either of the fonts I've mentioned.

(For `Noto Serif CJK JP`, my original issue was that despite the font being in the android /etc/fonts folder, I seemed unable to "summon" it through Anki, and was unsatisfied with the lag associated with supplying the font Anki-side - and my original workaround was a crude tweak in the system fonts.xml to move the Serif CJK JP font higher up the fallback precedence list.)

**Comment by mikehardy** [comment]
I understand this can affect reviewing significantly but it appears the chrome canary approach (possibly in combination with some specific font tweaks) works well, and either way there does not appear to be anything we can do. I'm going to close this

**Comment by aphirst** [comment]
@mikehardy Would you be able to recommend a single, canonical place for longer-term discussion about the possibility (discussed both here and elsewhere) of ultimately changing how Anki renders the "pages" such that the font reloading could be avoided entirely? That might be really useful closing information for anyone who, encountering similar issues, finds this thread and sees it closed.

**Comment by mikehardy** [comment]
@aphirst absolutely - and good idea - I think the best place is probably our wiki, it's open to edit so the community can collaborate without delay or restraint

**Comment by epistularum** [comment]
Was there any development/trick for this issue? Using the official .otf noto font I'm getting a full 2-3s wait for each side. Using both the google apis trick for noto and the woff2 trick for other fonts I can significantly reduce the load time to 500ms but it's still sub-optimal.

**Comment by mikehardy** [comment]
Not that I'm aware of. If I understand correctly AnkiDroid uses WebView, it uses Chrome, Chrome handles chunky fonts poorly. Not sure what we can do except say "use really light fonts"
