### ISSUE TITLE
Images are not loading while in additional directory of collection.media

### ISSUE THREAD

**Issue by HubberGot** [ankidroid/Anki-Android#5218]
###### Reproduction Steps
1.  Create deck with images and put images into the folder (`<img src="folder/image.png">`)
2.  Import deck into the AnkiDroid (e.g. sync via AnkiWeb or manually)
3.  Study

I confirmed folder is present in collection media path (`<root>/AnkiDroid/collection.media/<folder>`)
Everything is working fine if I put images into the collection.media directory.
Problem is with directories inside collection media - cards are not able to read images.

###### Expected Result
Images should be present on each card

###### Actual Result
Missing images on the cards.

###### Debug info
AnkiDroid Version = 2.8.4
Android Version = 7.1.1
ACRA UUID = 540caa56-ae55-431e-a128-5c53e84b871a

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
As far as I know, AnkiDroid just doesn't support sub-folders. I'm not 100% on that point, but I'm 99% - @timrae - are sub-folders for media just a hard no?

My thinking is based on this FAQ, where too many media files can cause a problem on older (FAT-formatted) devices because FAT doesn't handle large numbers of directory entries well, and there was essentially no solution for it https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-have-too-many-media-files-and-cant-copy-them-all-to-my-device

**Comment by timrae** [comment]
Yup, totally unsupported on the Anki platform. It may work in some limited contexts on some platforms, but it's always been discouraged by Damien.
