### ISSUE TITLE
Scrolling in the deck selection menu jumps to current deck on touch/hold

### ISSUE THREAD

**Issue by weirdalsuperfan** [ankidroid/Anki-Android#5262]
###### Reproduction Steps

1. Import [this deck series](https://ankiweb.net/shared/info/779483253), or perhaps any other long series of decks. The more the better. Even more decks can be found [here](https://mega.nz/#!VAxziKJL!6P7AClhpQ-l87N5-H6P_HCL1rOU6v7lJIJ4LwCBCfew) which contains a series originally put together/linked by the people in [this thread](https://www.reddit.com/r/LearnJapanese/comments/41wxll/complete_genki_deck_for_anki_with_internal_ime/). I'm not sure how many decks you need, but I think I have seen observed this bug since having about 30, if not fewer. I don't think you need a bunch of subdecks, either, just a bunch of a decks. They can probably even be empty if you don't want to download anything from the Internet.
2. Open the card browser (or add a new note), make sure you're viewing a deck already (although it works even if "all decks" is selected; but for the most obvious effect you might want to select a deck a bit of the way down), and then select the deck dropdown menu, and scroll up or down with a single swipe (whichever direction you can go)
3.  Tap/hold to stop the scrolling/hold the screen but without trying to open a deck. The scrollbar will jump back such that the deck that is currently open in the browser is positioned at the top of the dropdown menu, shifting away from where you put your finger down. The same effect can be seen when you try to select a deck during card creation.

###### Expected Result
When I'm browsing through my decks for the right one to pick and just want to stop the scroll movement, e.g. browsing with my thumb, scrolling little by little, I expect the scrollbar to move little by little and not change position away from where I've put my thumb down (until I move my thumb off by swiping to scroll).

###### Actual Result
It looks like this might be related to the function scrollDecklistToDeck in [DeckPicker.java](https://github.com/ankidroid/Anki-Android/blob/eeaed149a86f871d58d2f76b340b8dd62918f385/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java)

While swiping and releasing usually works well once, what actually happens when you put your finger back down is that the scrollbar jumps back, limiting deck selection to the visible decks by making it impossible to scroll up or down unless you do a swipe and hope that it stops with the deck you want in view so you can then select it with pinpoint accuracy. But if you don't select it perfectly, you might cause the menu to register your touch again before it selects a deck, jumping back to the original position it was in when you first opened the dropdown menu (i.e. the position with the deck the browser is currently displaying at the top). The end result is that changing decks in the browser/in card creation is a pain.

In card creation it's particularly bad because sometimes your keyboard will be open, cutting your screen real estate, and thus the probability that the right deck will come into view when you scroll past the first 5 or so decks, in half. Pressing the "back" button on your device doesn't always close the keyboard, either, so there's no convenient way around this bug.

I've been dealing with this bug for as long as I can remember, but as I add more decks (and I know I have too many) and start to add more cards through the Ankidroid interface at this stage in my studies, it's become unbearable. I can see how it's maybe one of those bugs that's actually a "feature," but I think it's a bad feature (and hopefully, being a feature, one that can be easily disabled).

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 8.0.0

ACRA UUID = 3dd0fca9-c28c-4b0b-973f-21ed54fd5224

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there - the new alphas have an undergone a huge amount of change with regard to the support libraries they use (where this is mostly implemented) and there has been some change with regard to "current deck" modeling in our code. Can you follow the installation steps to sign up for pre-releases from Google Play and join the "alpha" tester google group so those are the alphas? If you can reproduce this in the alphas I'll look further: https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

(full disclosure - they are backwards and forwards compatible right now so if it doesn't work you can go back to 2.8.x, and they are very stable - I use them as my daily review tool since months)

Thanks!

**Comment by timrae** [comment]
Actually I can reproduce this on the latest alpha versions as well, it's
very annoying

**Comment by weirdalsuperfan** [comment]
I installed the alpha (and confirmed that I have the alpha), and I was able to reproduce the problem. If that function I mentioned is still there, I'm pretty sure it's the cause.

**Comment by mikehardy** [comment]
thanks very much for trying with the alpha - at least now when there is a fix you'll get it immediately

that function is still there - here it is https://github.com/ankidroid/Anki-Android/blob/eeaed149a86f871d58d2f76b340b8dd62918f385/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1928

And by the way, love the handle, if you mean Wierd Al the musician, I may have been the only boy in the theater when UHF came out. So nerdy. And I'm older than dirt now, apparently. Cheers

**Comment by timrae** [comment]
The function that you mention is in the `DeckPicker` class, whereas the problem is in the `CardBrowser`. I don't see anyway that particular function could be responsible... 

Actually the same problem exists in **every** spinner in the AnkiDroid app at the moment!!!
When you long tap on an item in the spinner, without actually selecting it, it will scroll the position up to the last selected item. It must be an issue with one of the Android support libraries. For example, this bug seems like a strong candidate, and upgrading to 1.1.0 beta1 might fix it:

https://issuetracker.google.com/issues/124274573

I couldn't get compiling to work with 1.1.0 though, @mikehardy might enjoy that ;)

**Comment by mikehardy** [comment]
@timrae snipes it! linked PR implements his suggestion, seems to work
