### ISSUE TITLE
V2 scheduler stuck on 1 day intervals

### ISSUE THREAD

**Issue by dejiapps** [ankidroid/Anki-Android#5279]
I'm having issue with the V2 scheduler. If I get a question wrong and choose again, good and easy get stuck at 1 day. From another thread it was noted as fixed, however I still have it. 

I'm using Version 2.1.11 on my mac and 2.9alpha67 of ankidroid. 

![Screenshot_AnkiDroid_20190403-180317](https://user-images.githubusercontent.com/21183832/55523207-115d1580-5656-11e9-9f8b-6daf3b400647.png)

**Comment by hssm** [comment]
What do you mean it gets "stuck"? What do you expect to happen, and how does it differ from the desktop client? The screenshot depicts normal behaviour that happens on the desktop client as well.

**Comment by dejiapps** [comment]
By stuck I mean if I get the question right the next day, good and easy will still be stuck at 1 day instead of changing. And also shouldn't easy be a different interval? Like 3 or 5 days?

**Comment by hssm** [comment]
Did you mean to close this issue?

If it still persists, would you be able to send to me a copy of your collection with a card stuck in this state so I can investigate? Thanks

**Comment by dejiapps** [comment]
@hssm Yes I did decide to close this issue till I can investigate more, and make sure this is actually an issue or intended behavior. And also is it is an issue, to see if there is a pattern to it. Thanks for following up.

**Comment by Blauelf** [comment]
@dejiapps Is 1 day the first step for lapses in your deck?

I did see something similar, not sure if it is the same thing. The single re-learn step would repeat over and over on pressing "good". The issue in my case is that the `left` value got set to the length of the *new* `delays` list, while the card was actually in relearn, so that index was matched to the *lapse* `delays` list, which in my case has only one entry. And I have no idea why the code would do that. Totally confusing, since I could not find any difference between Anki and AnkiDroid (even if they are identical, it could still be a race condition due to some asynchronous database operations, which I would not see in the code unless I knew what I was searching for).
