### ISSUE TITLE
is:due not working for cards reviewed today when rebuilding filtered deck (v2?)

### ISSUE THREAD

**Issue by Blauelf** [ankidroid/Anki-Android#5308]
###### Reproduction Steps

0. Maybe prerequisite: Use v2 scheduler (so reviews should be consistent for learn or relearn cards)
1. Build a filtered deck "is:due prop:due>-1" (in my case currently includes cards mostly somewhere in "relearn")
2. review that deck until none of its cards is due
3. rebuild the deck

###### Expected Result

Since no cards are due, none should be in there. Anki Desktop 2.1.12 behaves that way.

###### Actual Result

Cards that were reviewed are shown as due again, even if they are scheduled for tomorrow.

I can repeat this cycle, and the same cards will show up every time.

###### Debug info

AnkiDroid Version = 2.9alpha68

Android Version = 6.0.1

ACRA UUID = ff44a484-01ff-4f08-9bd4-fb5454c0504c

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens
