### ISSUE TITLE
Calculation estimated time for long answers is wrong

### ISSUE THREAD

**Issue by Tibsun75** [ankidroid/Anki-Android#5315]
###### Reproduction Steps

1.Many of my cards contain more than 30 words in answer. Unfortunately the long answers are necessary to memorize and i am not able to split this in smaller steps.

###### Expected Result
For ten questions i needs between 30-45 minutes. 
İt would be very helpful for time planning  if the calculation for the estimated time considers the number of words in the answer, or another option to handle this.

###### Actual Result
İ am not sure but i think Anki does not consider the sum of words in the answer. Anki's estimated time is often only a few minutes for ten questions with long answers.
The calculation is correct for answers with only one to three words in the answer.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.4

Android Version = 7.0

ACRA UUID = 906a7350-6ca5-4f57-84c8-079b9acb5425

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I'm not sure but I think this would be an upstream issue - on the Anki Desktop site

**Comment by Anthropos888** [comment]
Similar thing here: the calculation for new cards is definitely wrong. Example from today: I have 200 cards in total, 20 of them are new. AnkiDroid shows me 120 minutes left.
I need 30 minutes to learn the 20 new cards. After that, AnkiDroid still shows me 120 minutes left! (The new cards are now red learning cards, so the total is still 200 cards)

I think the problem is that the calculation only uses the average for all cards. But I need 1-2 minutes for each new card and 20-30 sec for each review and learning card.

In my example above, the estimated time should be calculated depending on the number of new and learning/review cards:
20 new cards = 20 x 1.5 min = 30 min
+ 180 review cards = 180 x 0.5 min = 90 min
+ 20 learning cards = 20 x 0.5 min = 10 min
= 130 min total. 
After learning the 20 new cards AnkiDroid should accordingly show me 100 min left.

Is that an upstream issue or does AnkiDroid calculate somewhat different from Anki?

**Comment by mikehardy** [comment]
Unsure, it would require cross-reference with them https://github.com/dae/anki/blob/master/anki/stats.py

**Comment by Anthropos888** [comment]
I just tried to compare the estimated time shown in AnkiDroid with Anki (since I never do reviews on desktop) but there is no estimated time shown in the Anki deck view or during reviews. Seems that it is (at the moment) an AnkiDroid only feature. So it's not directly an upstream issue. 

Your link is about the stats page, I think? Are the calculations for the forecast/review time (next 30 days) the same as for the "remaining time" for the current session?

**Comment by mikehardy** [comment]
Hmm - I think you are right (my link was to their stats page), but I'm useless on the calculations. I love programming and memorizing things (thus my work here) but avoid arithmetic unless I must ;-)
