### ISSUE TITLE
Repeated, never ending forced database checks in recent alphas

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#5362]
###### Reproduction Steps

1. Update from 2.9a73 (or so) to 2.9a78
2. Relaunch AnkiDroid

###### Expected Result

Start straight to deck list.

###### Actual Result

Occasionally the app starts normally, but more often a forced database check begins that either takes ages (10m+), then restarts during the next relaunch, or doesn't end at all.

###### Research

Only occurs on one of two devices, the other ran the check once and not since (both run Android 9 r40).

The check doesn't report status in %, but instead counts to 56 on both devices. On the affected, it sometimes doesn't proceed to count at all (remaining at "checking database…") or remains stuck at "55 / 56".

There's no apparent reason for the check and it cannot be aborted. Never occurred after prior alpha updates, either.

**Comment by mikehardy** [comment]
Hi there - sorry this is happening for you! That would be frustrating

some points (as many of your observations are implicit questions):
- time taken is relative to size of collection and speed of device, out of our control
- status is a count not a % because the steps in the check are of uneven size
- the 55/56 step is database optimization and compaction I believe. It takes a while on my phone as well, but it does complete
- users are typically not interested in technical details that prompt checks, but if we find (and fix) a bug that involves possible data corruption, we typically right a database check step to fix it, and flag the next upgrade as needing a check. So any upgrade could require a check, based on development progress
- this check was flagged after alpha73 I believe, with alpha74 being the first where folks upgrading from prior to 74 would trigger a check

So that’s the what and why and how of the check

Why is it failing for you? I’m not sure but I would treat that as database corruption. If you are synced with ankiweb (sounds like you are?) and assuming you have a backup just in case, on the affected phone I would delete /sdcard/AnkiAndroid (or move it aside or similar), delete AnkiDroid app, reinstall app, and resync. Effectively start fresh

This is a vital mechanism in the app, I’m very curious to hear your results if you try this, or any steps taken and what happened. I’ll keep my fingers crossed it works out

**Comment by rathsky** [comment]
It doesn't seem to be actually failing, rather it's that the 55th step takes forever (and it's pointless, the two times it succeeded it was a whooping 3kB saved at 1st and none reported on 2nd) and no reason for the 
rechecks discernible (esp. as there's no report shown to me what the check actually did, like if any/none issue was found). No heat felt on the device to suggest it's scheduled with priority, for that matter.

I'd actually rather not try to reinstall, my collection is fairly huge (some 46k notes with 77k media) and takes very long to download it at these "25 files (or so) at once" increments, where one timeout/suspend is enough to have to restart.

But it's been working fine now for the past hour without a recheck, despite me trying to provoke one by force-closing from the app list and restarting the device. Maybe it just works now…

No database corruption reported on Anki desktop at any point, for that matter.

**Comment by mikehardy** [comment]
Right, so if it’s done most of the optimization it is expected it can’t do more.
The work it does in that step is storage-based, so doesn’t burn CPU, you’re maxed on I/O bandwidth
If it found problems it could not fix, it would say.

Basically, it sounds like it’s working, just with enormous collections it takes a while

I realize that may be disconcerting and take time, but a corrupt database is unacceptable, so this is a necessary evil

If it recurs and you have details, I’ll re-open but this sounds resolved…
