### ISSUE TITLE
 [Feature Request][Bounty Offered] Popups on Ankidroid after selecting a word

### ISSUE THREAD

**Issue by Kewell35** [ankidroid/Anki-Android#5398]
I already have the ankidesktop add-on for this but would like it work on ankidroid. When I select a word while reviewing cards, a popup automatically appears that brings up all the cards in the deck that contains that word.

I would like to have the same thing work on ankidroid. When I select a word on ankidroid, a popup box appears that shows you all the previous cards in the current deck with the same word.

I already have the original add-on so it's just to make it work for ankidroid.

I'm willing to hire someone to code this for me. Is anyone interested?

**Comment by adamwolf** [comment]
It would make it much easier to think about this if we had a link to the
original add-on.

**Comment by Stahlfisch** [comment]
Hey Adam, here is the link to the original add-on: [https://ankiweb.net/shared/info/153625306](url)

**Comment by Kewell35** [comment]
Yes. That's the link for it (https://ankiweb.net/shared/info/153625306). Thanks.

**Comment by timrae** [comment]
Closing this issue as it's not something that we'd merge into the main codebase (since it's not in Anki desktop). This issue will still be searchable from Google though, and you can start a thread in the forum as well if you like.

**Comment by timrae** [comment]
You might have more luck getting it accepted into here than the main AnkiDroid:

https://github.com/lucwastiaux/AnkiReview

**Comment by mikehardy** [comment]
Possibly worth noting that any application can add items to the Android system context-menu that pops up on word selects (AnkiDroid adds a couple for instance), and there was a separate enhancement request here for card browser direct-searching (which I would describe as "send a search term to AnkiDroid somehow so that it opens on the Card Browser with a search  #4496 

Perhaps if someone was motivated to make the CardBrowser open-able in that way from other apps, then a tiny separate app, an AnkiReview add-on, or just enhancing the existing AnkiDroid context menu would be possible?

Just a bit of a brainstorm on the idea since I was reminded of the related request

**Comment by kelciour** [comment]
One possible workaround is to set-up a server, i.e. something similar to AnkiConnect, and use JavaScript on the card template to fetch results from the server.

**Comment by Kewell35** [comment]
Thanks but I'm not sure which forum to post the request. The link sent
doesn't have anywhere to post the request.

**Comment by mikehardy** [comment]
@Kewell35 I think this is the right place? https://github.com/lucwastiaux/AnkiReview/issues - or by "forum" I think Tim meant public-forum@ankidroid.org - which goes here https://groups.google.com/forum/#!forum/anki-android
