### ISSUE TITLE
Syncing issue with Experimental Scheduler V2 + 2.9beta12

### ISSUE THREAD

**Issue by chickendude** [ankidroid/Anki-Android#5457]
###### Reproduction Steps

1. Turn on Experimental Scheduler V2 via Anki Desktop.
2. Do all reviews (new and reviews) for the day on Anki Desktop.
3. Sync to AnkiDroid.

###### Expected Result
New cards show up as zero like they do on Anki Desktop.

###### Actual Result
New cards are reset to daily maximum new cards.

###### Notes
I thought it might just be an issue with the database when switching from the old scheduler to the new one so i tried deleting everything but the collection.media folder in the AnkiDroid folder and re-syncing, but the issue came back. I also tried turning V2 off and back on. Turning it off from within AnkiDroid and syncing caused the correct number of new cards to be synced across to Anki Desktop, turning it back on however synced back to the maximum number of new cards when saving my progress from Anki Desktop to AnkiDroid.

###### Debug info
AnkiDroid Version = 2.9beta12

Android Version = 9

ACRA UUID = 9c7fa80a-d2d7-46ee-ac94-a3352c1ade0f

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

**Comment by hssm** [comment]
The `New cards/day` setting for the deck has the same value on both sides after you sync, right? So your issue is that *more* new cards are scheduled for the day after you sync?

So for example:
New cards/day = 12

Due/Learn/New:
Desktop: 0/0/0
-> Sync
AnkiDroid: 0/0/12

Is this what you mean? Any more details or screenshots to help me understand would be good.

**Comment by chickendude** [comment]
I did all my reviews on AnkiDroid (until i hit new cards):
![image](https://user-images.githubusercontent.com/2564517/66431450-49d21780-ea1c-11e9-80bb-a4bbf7e51785.png)

Then i synced to Anki desktop:
![image](https://user-images.githubusercontent.com/2564517/66431518-6cfcc700-ea1c-11e9-930e-ad2d65d01b2b.png)

I finished the remaining reviews and started one new card:
![image](https://user-images.githubusercontent.com/2564517/66431576-81d95a80-ea1c-11e9-9d82-7d3f18294b24.png)

After syncing back to AnkiDroid, it reset the new cards to 15:
![image](https://user-images.githubusercontent.com/2564517/66431406-3e7eec00-ea1c-11e9-81a2-0480d175ddde.png)

**Comment by hssm** [comment]
It might help to have a copy of your collection. I've spent months syncing back and forth with a surplus of new cards and never encountered it myself. *However*, I only review from top-level decks, and yours is a nested one, so that might be a clue.

If you're interested in looking into this yourself, the `perDay` and `newToday` deck configuration items are where you'd want to look. You'll notice there's a different function for decks [without](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L749) and [with](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L707) parents, which might be where the issue lies. Why this only happens on sync is a mystery though.

**Comment by chickendude** [comment]
I'll try to run it through the debugger to see if i can figure out where exactly it's going wrong, but it'll probably be next weekend before i can really spend any time with it. I've also sent a copy of my deck to the e-mail listed in your profile.

As a side note, yesterday i had the opposite happen: i did all my reviews + new cards on the bus and when syncing to my desktop at home my AnkiDroid deck showed 0 due/0 new whereas Anki Desktop showed 0 due/15 new.

**Comment by matiya** [comment]
I believe I also have the same issue. I'm on ankidroid 2.9.3 on android 7.1.2

Now, I experience the following:

1 - Review cards in ankidroid, get X new cards. Review all of them.
2 - Sync from ankidroid to cloud
3 - Sync from cloud to anki desktop. Don't review anything.
4 - Sync once again from cloud to ankidroid
5 - There are once again X new cards in ankidroid. They are different cards than that of step 1. 

Previously I had set the beginning next day at 6 PM. When I enabled the V2 scheduler, this setting changed to 4AM. I don't know if this is related to that.

**Comment by matiya** [comment]
Apparently in my case at least, the problem went away when I manually changed the beginning next day to the same time in Ankidroid and anki desktop.

**Comment by chickendude** [comment]
The issue seems to have resolved itself on the latest Anki desktop version 2.1.20 (at least syncing from desktop to AnkiDroid, i haven't tried studying new cards on AnkiDroid yet).

**Comment by mikehardy** [comment]
I'm so glad to hear this! Thanks for reporting
