### ISSUE TITLE
[2.9 ACRA] crash creating CardBrowser options menu

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5510]
Somehow the Collection can be null while creating the Card Browser options menu?

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/72712c17-04a8-4011-911f-9bef4dff37a6

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
at android.app.Activity.onCreatePanelMenu(Activity.java:3568)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
```

**Comment by Arthur-Milchior** [comment]
This ones makes no sens at all. 
In `cardBrowser`, the collection `getConf` is called a single time. On the result of `getCol`.
CardBrowser is not inherited, so we know it's `CardBrowser#getCol` which is used, and not an overriding method.

`getCol()` returns `CollectionHelper.getInstance().getCol(this);`
`getInstance` is static, so no risk of calling a child instead of calling this method.
`getInstance()` returns `LazyHolder.INSTANCE`, which is initialized to `new CollectionHelper()` and then never modified (it's private anyway). So we can look at `CollectionHelper#getCol` without risking it to use a child method.

This `getCol` returns `mCollection`. This value is only set in this method, so once it's non null, it can't be set to null again. (This variable is private, and the class has no child, so no risks here)
Initially `mCollection` is null, however, if it's null, then `colIsOpen` returns false, and mcollection is set to `Storage.Collection(context, path, false, true)`. So as long as this call returns non null, `getCol`  can't return a null value.
`Storage.Collection` only returns `col`, which is a local variable, initialized with `new Collection(context, db, path, server, log);`. So it's non-null. Then this variable is never assigned again. So it can't be null.

I thus proved that there is no way with current code that this bug did occur. Which technically means it could have been solved by updates since 2.9. I'm going to take a quick look at it. However, I'd be surprised if I find an explanation.

Is there an easy way to see exactly which commit corresponds the version of the code run here ?

**Comment by mikehardy** [comment]
Sure - these were all reported against version code 20900300 which references code from this tag https://github.com/ankidroid/Anki-Android/commits/v2.9

**Comment by mikehardy** [comment]
Total wild guess but I wonder if this is like the ContentProvider that can start in a race with Application.onCreate() - is this stack what we'd see when people long-press on text outside of the app? I don't know if that's even a reasonable question, the ContentProvider bug and null pointer exceptions just has me thinking paranoid about re-entrant code

**Comment by Arthur-Milchior** [comment]
I just did the same check in commit v2.9 and I can state exactly the same thing. There is no way I know for this value to be null. 
Second time is quite quicker to do since i already know what to expect

**Comment by Arthur-Milchior** [comment]
I personally don't know what you're talking about. I assume you're referring a problem you solved I've heard of.

**Comment by mikehardy** [comment]
Sorry - #5557 the comments there are interesting. Android is multi-threaded so there's always the possibility (unless you're using an API that protects against it) that there's another CPU executing against the same objects in memory, and maybe one of them is faster than you expect and makes it to a part where it reads a variable before it's initialized. That was #5557 - no idea if it applies here, but it was null. It did crash. It must be possible somehow?

**Comment by Arthur-Milchior** [comment]
As far as I understand, race condition needs to access shared variable.
So no problem here for onCreateOptionsMenu
No problem in AnkiActivity#getCol
in collectionHelper.getInstance, it acces a private static final variable, so no race here either. Especially since anyway this in not the null value. 
CollectionHelper#getCol could have a race for the instance variable mCollection. 
However, here, the result of the race would be to set mCollection twice, and not to let it unset. And anyway, this is only a theory since this method is synchronized, so actually race is impossible here. 

In Storage#collection, the variable col is local, so there should be no race here either.


As you state, the bug did occur, so I'm surely missing something. But I surely have no clue what it could be

**Comment by mikehardy** [comment]
I looked at this again yesterday since this is now just about our top crash, now that I have worked through most of the other even-more-frequent crashes.

I still don't understand it!

It obviously happens I just can't reason out *how* or *why* it happens, or even if I just assumed that the object could be null then I don't know how to handle it (as the whole options menu is then suspect and rendering the screen seems like a fail).

Any and all help appreciated - this affects a lot of people

**Comment by david-allison-1** [comment]
Cause: #5097 

A corrupt "deckPath" which mutates the result of the collection path to point to a read only file system.

This throws an exception, which returns null.

https://github.com/ankidroid/Anki-Android/blob/646de8556ea28f178a4c7c8dbb8240622a7dbe80/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L85-102

**Comment by david-allison-1** [comment]
Cause was: #5930
