### ISSUE TITLE
[2.9] Font size is bigger than usual with appcompat-1.1.0 (not seen with appcompat-1.1.0-rc01)

### ISSUE THREAD

**Issue by goodwins** [ankidroid/Anki-Android#5512]
Since yesterday and the update to 2.9, all the text on the cards are bigger. I tried to update the font settings (https://docs.ankidroid.org/manual.html#_fonts) but the text stays bigger than with the previous AnkiDroid version. I checked my phone settings, and font parameters were not updated.

Likewise, in the card browser when you setup "Card browser font scaling" to 50% the text is actually bigger instead of smaller. Same issue for font scaling >= 30%. No issue for 10%, 20%.

###### Debug info
AnkiDroid Version = 2.9
Android Version = 7.0
ACRA UUID = 059134f9-ddeb-40b2-a884-ea18b8fb6b2c

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**Comment by Ai-rin** [comment]
I have exactly the opposite - since the update, all the fonts are much smaller. 
Android 7.0 / MIUI 10.2

**Comment by mikehardy** [comment]
None of the font changes are expected - it seems there may have been a difference both between 2.8.4 -> 2.9.0 *and* 2.9.0 -> 2.9.1. Can anyone say whether that is the case and 2.9.1 changed things?

**Comment by Ai-rin** [comment]
With 2.9.1 things returned to normal for me :)
Thank you.

**Comment by mikehardy** [comment]
That is most unexpected. What it means is that the appcompat-1.1.0 vs appcompat-1.1.0-rc01 library difference also affects fonts somehow. @Ai-rin - sorry to bother with questions, but what phone / Android version / are you on (with vendor data if you have it, e.g. I would say "OnePlus 5 / Android 9 / OxygenOS")?

Do you have any non-default font settings in your phone (different font, larger or smaller) or in AnkiDroid (zoom levels etc)?

I'm trying to save enough information so that later when we move to upgrade this library again I have a couple things I can test before/after to see how the fonts are working.

**Comment by Ai-rin** [comment]
@mikehardy - it's Xiaomi Redmi Note 4X with Android 7.0 (MIUI Global 10.2.3.0).
I have font settings in the phone set to "XXL" (non-default, maximal size).
AnkiDroid settings are more or less default. Note that every UI text was changing, not only the card browser.

**Comment by mikehardy** [comment]
Very interesting - thanks for the extra information @Ai-rin. The issue I'm tracking for the WebView crash was pinned down to all android 5 + 5.1, and Android 6 through 7.1 where the phone did not have Google Play Services installed - I know some of the Xiaomi phones have Google infrastructure and some don't - does your phone have all the google stuff installed? It might end up being the same issue (but with very different side effects) since both had to do with resource loading

**Comment by Ai-rin** [comment]
@mikehardy - Yes, it has full set of Google apps installed.
It has non default launcher, if it matters - Nova Launcher.

**Comment by mikehardy** [comment]
@Ai-rin I use Nova Launcher as well :-), okay I think I have all the information I need to try to replicate it when we attempt to update appcompat library again. Thanks for the help!

**Comment by Ai-rin** [comment]
@mikehardy No probs, thanks for the support :)

**Comment by goodwins** [comment]
AnkiDroid 2.9.1 is solving my issues. System font size is taken into account again.
Thanks for the quick update.

**Comment by mikehardy** [comment]
@goodwins I'm really glad to hear this is working for you but I want to leave this open as the solution was ugly - for unrelated reasons we downgraded a basic android library to a "release candidate" vs the general release. Eventually we will need to move forward again, and if this is not open we may forget it has all these font side effects

**Comment by mikehardy** [comment]
You may feel free to "Unsubscribe" if notifications about it will be bothersome though - that's not the goal ;-)

**Comment by mikehardy** [comment]
#5620 may be related, requires testing after it merges

**Comment by mikehardy** [comment]
I will mostly likely attempt an appcompat library update shortly as the crash bug stopping it previously has been - hopefully - fixed and will have the fix released in appcompat v1.2.0-alpha02 - https://issuetracker.google.com/issues/141351441#comment27

At that time we'll need to re-test this, so please pay attention, affected people :-)

**Comment by mikehardy** [comment]
@goodwins @Ai-rin I have updated the appcompat library that we think caused this problem, it moved a couple versions at once so I'm not sure what effect it will have. If you check the 2.10alpha64 or higher I will be curious how it looks now though?
