### ISSUE TITLE
[2.9 ACRA] crash in Collection.addNote - null DB reference?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5524]
There are a couple similar crashes related to null references in DeckTask working in the background, and one already referencing the DB object, but this stack is different - might be the same root cause, might be different

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/5d9185ba-44ef-4892-95ee-0906951368ce

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String)' on a null object reference
at com.ichi2.libanki.Note._preFlush(Note.java:1)
at com.ichi2.libanki.Note.flush(Note.java:3)
at com.ichi2.libanki.Note.flush(Note.java:2)
at com.ichi2.libanki.Note.flush(Note.java:1)
at com.ichi2.libanki.Collection.addNote(Collection.java:3)
at com.ichi2.async.DeckTask.doInBackgroundAddNote(DeckTask.java:6)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:51)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by Arthur-Milchior** [comment]
This is a general question for any acra bug.
you give a link. Is there more detail behind the link ? Is so, how can I access it ? Because currently, when I click I see an empty page. I assume I must be logged to see the actual content but i've got no place to sign in.

I would like to now also, is there a way to ensure I didn't send bug report during my tests ? Because I did have a lot of bug; and I wonder whether I did send you bug report that you'll never be able to understand because it relates to a version of the code which exists nowhere anymore

**Comment by mikehardy** [comment]
For ACRA you have to have a user id in the system to get in - I put the links mostly for reference, but I paste the stack trace in after an initial investigation

You may send crash bugs in during development but that's okay, if you're up to date it will show up as against an alpha version in debug mode and I don't pay attention to those :-)

**Comment by Arthur-Milchior** [comment]
Intuitively, I believe that adding DeckTask.waitToFinish(); in Collection#cloze may solve the trouble. Just before https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L393

This is already what is done in Connection#doInBackgroundSync; except
that there is a timeout of 5 seconds. If this times out, Ankidroid
believes there is a bug and ask for a full sync. Here, we don't have
anything like a full sync to save us; so I believe I wait for
everything to ends.

Another solution would be to warn the user after 5 seconds that the process seems to be stuck, and gives the user a button to stop backgroup process and indeed close, instead of waiting more. 

Note that adding this call to Collection#save may make more sens that adding it in Collection#close; however, I assume that background task may want to save, which would create an infinite loop. On the other hand, I don't see any background in DeckTask task which would requrire to close the database.

**Comment by dae** [comment]
Should be fixed in new backend.
