### ISSUE TITLE
No notifications after update 2.9 and 2.9.1

### ISSUE THREAD

**Issue by marieness** [ankidroid/Anki-Android#5535]
Hey :)
After tue 2.9 Update, my S8 does not display a notification reminder for the remaining cards anymore. I have since deinstalled and reinstalled and checked the settings and permissions and all seems in order. However, the notifications have not reappeared :)
Thank you for any help!

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! I have answered a few people on the play store and have a workaround for most but it is good to have an issue here to collect the most important differences in notifications between 2.8 and 2.9 so we can maybe address them

First the workaround: I would recommend long-pressing the deck that you want notifications for while you are in the deck list, then selecting deck options, and configuring notifications there. This is a setting that is per-deck-group, so it will trigger a notification for each deck in that group. This should work

Second, a change not everyone likes: apparently in 2.8 some people were relying on the notification being persistent - what I mean is that if it had triggered then it would update with new counts of cards due while you were reviewing / when you were done, but it would not go away until you had finished and gotten the card count below the threshold? I am not sure it still behaves the same way

I do not believe you still need to have the widget on the launcher screen in order to have notifications, but this may be a way for people to simulate the persistent reminder at least, and if you do still actually need the widget on the launcher than that is unexpected.

@marieness not all of the info is targetted specifically for you but hopefully the workaround helps and you get notifications for the decks with due cards?

**Comment by mikehardy** [comment]
I have added a FAQ https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-dont-i-get-notifications

**Comment by tomshaffner** [comment]
I would simply add a note that I was one of the users that was indeed depending on the persistent behavior described above, and with the update this has stopped working. As worded in the settings persistent behavior seemed intended. The workaround above is a helpful stand-in but the original general notification was a more effective feature.

**Comment by mikehardy** [comment]
@tomshaffner I agree! Working through some stability things (actual crashes) on 2.9 as a higher priority but I agree this was a regression and I intend to fix it as I have time available, unless someone beats me to it. Sorry it affected you

**Comment by viivgit** [comment]
I can confirm this very issue on Samsung Galaxy S9, I don't have any notifications on the lock screen or the notification drawer, and would appreciate to get them back without the workaround. It's since the last update indeed.

**Comment by viivgit** [comment]
Also I want to point out that I never added the widget and I had on the lockscreen and notification drawer an up-to-date persistent notification with the current number of revisions to do.

Also, The proposed workaround is not persistent so it is not ideal.

**Comment by topherbuckley** [comment]
I'm on Motorola Nexus 6, non-stock Android 9 Havoc OS, AnkiDroid 2.9.6. I have the widget installed on my main home screen. 

I still don't see any notifications, persistent or not. I've checked all system notification settings including battery optimization settings, and see nothing that should block. I receive notifications for other apps without an issue. 

According to the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-dont-i-get-notifications):
>In the 2.9 version notifications should work with or without the widget. However, you may need to configure "per deck group" notifications to receive them in 2.9

>    Open the deck list
    Long-press on the deck you want notifications for
    Choose "deck options" from the popup menu for that deck
    Configure notifications as you like

But I only see "Options" not "deck options in the popup menu (assume this was intended), but then I see nothing regarding to notifications. I see "Reminders" which appears to just a one-off alarm every day, which is not the same by any means to notifications when 10 reviews are due. Is there a more accurate description of how to get to these deck-specific notifications? I'm not finding them anywhere.

**Comment by mikehardy** [comment]
The FAQ entry was written quickly, you've discovered several wording inconsistencies as a result - however the behavior of the system in code is that *if* you have general notifications on or *if* a deck has notifications, it enters the check for whether there are enough due to trigger the notification, so the descriptions and functionality should be roughly the same. Could you experiment and true up the FAQ entry?

**Comment by topherbuckley** [comment]
Sorry for the delayed reply. Looks like I also need to improve my github reminders! :stuck_out_tongue:

Yeah, the wording is a bit off, but more importantly I see nothing related to notifications in the deck-specific options other than this one-time alarm-clock style one-off functionality. I see the Notification's setting in the General Settings, but nothing anywhere near what was described in the FAQ regarding Deck Options. I'd be happy to tidy up the FAQ if I could figure out a way to actually make the notifications work first :sweat_smile:. 

I just tried this out on a new(ish) phone (Pixel 3a) Android 9. Ankidroid 2.9.7. Seeing the same lack of notifications regardless of what settings I use. I ensured the following are not blocking:

- AnkiDroid has all requested permissions granted
- Long press app icon -> Notifications -> On
- Long press app icon -> Background restriction -> Off
- Battery optimization -> Not optimized. 

Is everyone else getting these notifications? If so, is there any screenshot of what this should look like? Maybe I am searching for something that doesn't actually exist? Are the notifications not Android Drawer Notifications, but instead just a read out on the desktop widget?

**Comment by mikehardy** [comment]
I get notifications
I have the widget dropped on my desktop - not sure if I will still get notifications otherwise but I *should* just haven't tested, you could try both
I have general settings to notify when pending messages available
I have Deck Options groups generall set to enable reminder notifications and remind at 19:00
On my Android 10 device settings I have all the notifications stuff toggled on for the app
On my Android 10 device settings I have battery optimization set to 'Intelligent Control' but these things are likely vendor specific and you might consult https://dontkillmyapp.com

**Comment by topherbuckley** [comment]
Without changing a thing, I now have notifications as expected. This seems to have come with the recent Play Store update on May 14th (2.10.2). Strange that I do not see anything related to this fix in the update notes, but glad to see it working now regardless. I updated the FAQ to reflect better what I am seeing now and added a note that users should update to 2.10.2 if they are seeing similar issues to what I was seeing.

**Comment by david-allison-1** [comment]
@topherbuckley Thanks so much for the wiki change and feedback 🙏 

We've heavily been fixing bugs since 2.9.x came out. I can think of a change in the beta that may have fixed it, but nothing in the stable release. Nonetheless, it's good to know that things are getting better.
