### ISSUE TITLE
Full sync required after checking database in 2.9.1 

### ISSUE THREAD

**Issue by thoral** [ankidroid/Anki-Android#5541]
In the past I never experienced a full sync demand after checking the database of a mobile device. (Nor did this check found any errors.) Now, after updating to 2.9.1 the database check took much longer than before, and, much worse, the app requested a full sync because of a reputed 'sync conflict'.  

My other devices which are running with 2.8.4 do not show any sync conflict at all after a database check. Obviously there is no corruption in my anki web data because everything works fine since years (no database problems before, no syncing issues).

Is this full sync request correct (and necessary)? Why does the database check alters the data so that a sync conflict is displayed? 

I deciced to abort this full sync request until I am sure that the db check of 2.9.1 will not damage my data. I have not seen any sync conflict before after performing a db check.

I reproduced this behaviour on Android 6 and 8. I can send you my complete database if you want to reproduce this issue. 

Thorsten

**Comment by mikehardy** [comment]
You can always examine the code for the check it is open source. If you're that paranoid about your data (not a bad thing, mind you) nothing I can say should help, so check yourself

Be assured we would never trigger the check unless we found a bug in code that corrupts databases. The main one added was that we found corruption was possible with card template editing, and the specific corruption can lead to crashes. Luckily the fix was to prune orphan data, the corruption was not in any data users meant to save and use.

Here's a nifty way to see what's going on in the integrityCheck: https://github.com/ankidroid/Anki-Android/blame/master/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1557

You can see it's an area of much work - it's not easy managing these complex data structures

In this case it was a type of corruption (orphaned ordinals on note types) that was already handled, so the "fix" was just to trigger that it was necessary again after crossing this version boundary

**Comment by thoral** [comment]
Sorry, this was my fault. Therefore I already closed this issue. (Deleting it was not possible...)

FYI The integrity check in Anki Deskop provoked the same full sync as the new version of AnkiDroid. (I never did those integrity checks before in the deskop version.) Only Ankidroid 2.8.4 did not provoke a full sync. Therefore I was a little bit confused what to do until I checked the desktop version.
