### ISSUE TITLE
Daylight saving time in Brazil causes problems with syncronization.

### ISSUE THREAD

**Issue by JoaoMarcosCSilva** [ankidroid/Anki-Android#5627]
Every year on Brazil, we started daylight saving time on November 3, when everyone in the country changes their clocks to 1 hour earlier.

You can probably guess how this could create problems with Anki syncronization, as the time on the server and the time on the device must be the same (if you manualy change the device's time, instead of letting it on automatic, you can't sync)

However, interestingly enuogh, this was never a problem. I believe, therefore, that Anki's servers must somehow be aware of Brazil's time change to allow syncronization.

There is only a problem. In 2019, the new brazilian president cancelled the daylight saving time, so we don't have to change our clocks anymore. However, Anki still thinks we do, and won't let me sync unless my phone's time is on daylight saving time, which is not active in Brazil anymore.

###### Reproduction Steps

1. Change your android phone's time manually (in configurations)
2. Try to sync AnkiDroid

###### Expected Result
You are able to syncronize

###### Actual Result
You get an error message about how the time in your device is wrong by 3600 seconds (the time that was changed manually) and are unable to sync.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
There is nothing more irritating in multi-node systems then time synchronization, especially with daylight savings time

Have you looked into any of the info here? https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-i-get-an-error-about-the-timezone-when-i-try-to-sync

The problem isn't that the server knows the time zone you are in, the problem is the device still isn't right somehow. The sync times are all based off of UTC internally. So I think it is just that your phone doesn't have the right timezone definitions yet.

It is possible sometimes to select a nearby country that is correct (vs UTC and for your local time) and use manual settings in your phone for that - others have reported success with this strategy. Or maybe just setting to the UTC offset for your region directly? https://www.timeanddate.com/time/zone/brazil

**Comment by JoaoMarcosCSilva** [comment]
Thank you for your help!
Changing my timezone from Brazilia (which was wrong) to Buenos Aires worked, and now I can sync normally.

**Comment by mikehardy** [comment]
excellent! If your vendor sends an update to your phone's ROM at some point in the future you might be able to put yourself in the correct region again, until then workarounds will rule the day :-). Cheers
