### ISSUE TITLE
Forward-port build to Gradle 6 (remove deprecations)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5634]
###### Reproduction Steps

1. Upgrade to Gradle 6 (#5633)
2. Run build with deprecation on `./gradlew --warning-mode all  jacocoTestReport`
3. See output

###### Expected Result

No deprecation warnings about removals planned for Gradle 7

###### Actual Result

A few categories of error:
1- upstream issues (looks like android gradle plugin has issues)
2- forward porting issues (api publish needs to migrate from 'maven' to 'maven-publish'
3- some minor usage stuff

**Comment by Vaibhavi1707** [comment]
Hi, These were my findings when I was working on [#8361] (https://github.com/ankidroid/Anki-Android/pull/8361). When I ran `gradle build --warning -mode all` (Gradle version 7.0) the message prompted me to: 

-  use `maven-publish` plugin instead of maven.
-  use 'destinationDirectory()` property instead of `destinationDir` property in `AbstractArchiveTask`
-  use 'archiveFileName` instead of `archiveName` property in `AbstractArchiveTask`

The point below is just an elaboration of the prompt, although it might have occurred due to an installation error at my end, diagnosed due to the file not found exception found at the end.
In addition to the above `extractDebugAnnotations` task execution fails. This is due to inability to resolve files for `:api:lintClassPath` configuration such as `com.android.tools.lint:lint-gradle:27.1.3.`, due to inability to get https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.1.3/lint-gradle-27.1.3.pom which is further attributed to `org.apache.http.ssl.SSLInitializationException`.

**Comment by mikehardy** [comment]
Gradle 7 is out so this is more interesting now https://docs.gradle.org/7.0/release-notes.html - upgrading to gradle 7 will unblock #8434

**Comment by mikehardy** [comment]
I'm going to see what I can do about this one prior to release-2.15 cut - in my mind it is not a hard blocker but I am irritated as I perform point releases on old release branches when the build toolchains diverge a lot, it makes backporting and testing heavier than it needs to be.

**Comment by mikehardy** [comment]
For reference, here is their forward port guide from gradle 6.8.x (which we are on now)

https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#changes_7.0
