### ISSUE TITLE
A point appear in the center of Card Browser when only one card in a deck

### ISSUE THREAD

**Issue by chenminken** [ankidroid/Anki-Android#5669]
###### Reproduction Steps

1.  Add an new deck.
2. Add an new card in this deck. In deck view check this 
3. Open Card Browser. 

###### Expected Result
Only one card show in the screen, no other things.

###### Actual Result
A point flashing in the center
![341577019427_ pic](https://user-images.githubusercontent.com/20356658/71322060-b62dc480-24fd-11ea-9286-ecd5e648250e.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This is almost always because of an accidental edit to the card templates, where an unexpected/incorrect character is left there and then the template is saved: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-my-cards-display-incorrectly

I am going to close this provisionally because I am 99% that is the reason but please report back and if it is not the reason we can open it and figure out what's going on

Cheers
