### ISSUE TITLE
New ★/⚑ signs flashing annoyingly on every card

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#5695]
The two "new" ★/⚑ symbols (from a26) flash on every single card once it renders – twice, once on front and again on the back site – briefly (perhaps 0.5s) but very visibly. Only then are they removed from display again as none of my notes has such attribute.

It also delays the Javascript on the cards, causing further visible glitches. The device is an older 2013's Nexus 7, but running Android 10.

NB: I understand that this was introduced to bring handling more in line with Anki desktop. But frankly I also have to doubt the meaningfulness of rendering these attributes on the card itself, with both attributes already cleanly shown their buttons. I'd very much prefer if the additional on-card rendering was opt-in/an option.

**Comment by mikehardy** [comment]
Hi there! Not disputing the flashing being unwanted, but I think in the preferences you can select which buttons show and which don't? Which is another way of saying that if I understand correctly until flashing stops you might be able to work around it

@Arthur-Milchior / @timrae you guys were collaborating on the UI/UX of this feature so you might both be interested

**Comment by rathsky** [comment]
Ah, I missed that ⚑ indeed already has its own optional button. Edited the report accordingly. (The colors for the "no flag" flag don't match the rest of the UI, making them invisible in night mode, but I guess that's known.)

Still, the new additional ★/⚑ sings are rendered as part of the cards – not the UI – unconditionally (ie. no workaround) as far as I see, regardless of whether their buttons are already shown. That's what I'd like to disable again.

**Comment by timrae** [comment]
@Arthur-Milchior 
I can reproduce this as well on my Xiaomi A3.

Go through and review a bunch of cards from a deck which *does not contain any cards with marked notes*, and you will sometimes see a star briefly appear and disappear during rendering

**Comment by timrae** [comment]
Another issue I noticed is that my text alignment changes on cards with stars / flags, whereas this does not occur on Anki Desktop.

**Comment by timrae** [comment]
@adamwolf 
Did some work on solving flicker during mathjax rendering and might have some useful advice

**Comment by Arthur-Milchior** [comment]
Solution to the flashing problem is in https://github.com/ankidroid/Anki-Android/pull/5696 Thanks for telling us about it. Sorry that my code created a problem.

@mikehardy As far as I understand the problem, this was not related to the buttons. But to the star and flag symbols that @timrae wanted to add.

@timrae 
This alignment problem does not exists on anki. There is a good reason for it. In anki, there is a 20px padding margin around the whole reviewer. And the star and flags are almost outside of the margins. I didn't add such a margin, because some phone's screen are really small. So this is far costlier for phones than for desktop. Which means that, if you have a card whose CSS is not centered, then the star will be over the start of the text (and the flag over the end of the text if the text covers the whole first line)
So we must deicde whether:
* either we accept to cover the text with the star
* to add a margin, and loose some space
* to keep stars and flags in toolbar only; in which case this commit was useless. I think personnally that's the best solution; informations are already shown in toolbar; showing them in the card display is redundant.
* to add a margin only when star/flag is dipslayed. 
* keep what I have choosen, which is to ensure that text is not shown over the star/flag, while still using as much space as possible
* adding a preference option to choose between some of those options

**Comment by timrae** [comment]
Does anyone know how it's handled in Anki Mobile?

Personally I think that, if we are going to deprecate the mark note feature then I would also be in favour of only using the toolbar as we have been doing with the mark note feature, so that we can simply replace the star icon with the flag icon. However if we are going to support both then that approach will not work well as there is not enough space for another icon in the toolbar on most phones.

So we come back to the same discussion from #5571

**Comment by Arthur-Milchior** [comment]
The answer to your first question is: dae.
I think I'll be lazy on this one. When you know what exactly you want, let me know. Hopefully it won't take long to code. If you need technical informations, I'll help as much as I can.
However, I'm not interested in being part of the decision making related to an interface usage. Once again, I don't think my opinion is really relevant compared to the one of an average user.

**Comment by rathsky** [comment]
The space issue could also be resolved by introducing another swipe-in menu (from the right).

**Comment by Arthur-Milchior** [comment]
I think the space issue should really be in another thread. Because the title is misleading here

**Comment by mikehardy** [comment]
I believe flashing is no longer happening, which indicates the original issue is closed? Can reopen if not.

The spacing issue is captured here #5806 and should have same effect as Anki Desktop (they are rendered, but not in a way that impacts layout)
