### ISSUE TITLE
Mathjax and cloze deletion bug duplicate portions of the card

### ISSUE THREAD

**Issue by michael-angelozzi** [ankidroid/Anki-Android#5703]
###### Reproduction Steps

1. Create a cloze card with:
`\(A\) {{c1::x}} \(B\) {{c1::y}} \(C\) {{c1::z}} \(D\)`

###### Expected Result
A x B y C z D

###### Actual Result
A x B y C z D y C z D

Works fine on the desktop version, but quite a few of my cards in the android app have duplicate chunks of the card, and have simplified into this easily reproducible test case. As you can see in the above case "y C z D" appears twice.

Might be related to #5552 (closed)

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Have you tried the latest alphas?https://docs.ankidroid.org/manual.html#betaTesting

**Comment by michael-angelozzi** [comment]
I haven't tried alpha testing, but I did first make sure I was on the latest offered by the app store.

**Comment by mikehardy** [comment]
That is unfortunately not specific enough, as the app store (really the "play store", apple is the app store - but I do know what you mean) can offer the stable, beta or alpha version. If you sign up for betas in the play store app and do nothing else, you'll start getting the betas. 

This one should be fixed in 2.9beta2 according to the linked issue though, so if you are definitely on that version or higher (you can see at the bottom of advanced preferences) then the bug still exists.

If it does exist, then any future fix will be in an alpha - to get those you'd need to also follow the link above and join a special google group signalling alpha interest. There is zero traffic on that list, but it is important because the play store uses membership in that list to offer you the alphas or not. Then you can test it

But first we need to know your exact current version to make sure it's reproduced well

I'll also tag in @adamwolf who has so far generously been our mathjax expert :-)

**Comment by adamwolf** [comment]
If this is still a bug, I can jump in and make sure it's fixed.  I am
currently drowning in work that I delayed over the holidays, so before I do
that, could you please check that you are on 2.9beta2 or newer?  If not,
please update to that or newer.

Thank you so much for including a good example, if this is something I have
to jump in and fix that will make this relatively quick.

**Comment by michael-angelozzi** [comment]
Thanks guys. I just joined the alpha group. 

Then with regards to:

> To get a beta or alpha update with no delay instead of waiting, may manually tap the button to scan for updates in the Google Play Store app on your device, then update via the update button in the list of app updates found (not in the app details section).

I scanned for updates, and under updates available, there is none for Anki. I don't think I am using the alpha version (under app info is says 2.9.1). But to reproduce the bug, one just needs to create a cloze card and paste in:

    `\(A\) {{c1::x}} \(B\) {{c1::y}} \(C\) {{c1::z}} \(D\)`

**Comment by mikehardy** [comment]
Sometimes if you go to the "beta" tab at the top of the play store app, you can see the updates earlier than if you wait for it's daily-or-about-daily update cycle to run

**Comment by michael-angelozzi** [comment]
It is fixed in 2.10alpha30. Thanks guys.

**Comment by mikehardy** [comment]
Yes! Thanks for coming back and updating
