### ISSUE TITLE
Play a sound when the answer is correct

### ISSUE THREAD

**Issue by ultraomid** [ankidroid/Anki-Android#5772]
Can you add a feature which plays a sound when the answer is correct? It has proven psychological effect on users. 
I appreciate your efforts ❤️

**Comment by mikehardy** [comment]
No, sorry. No argument against a psychological argument but ankidroid has a very very focused review experience on purpose. You may like AnkiReview as it uses ankidroid as a library for scheduling etc but had a different reviews experience

**Comment by adamwolf** [comment]
Mike, sorry to reopen this and feel free to just close and I'll keep quiet
next time... Is there something we can enable so folks can do something
like this with Tasker or something?  Is this something you can use Tasker
already for?

**Comment by mikehardy** [comment]
Not that I'm aware of. If something really loosely coupled like that were possible, I'm open to it. So far hooks and plugins were a bit of a bust from platform restrictions

**Comment by adamwolf** [comment]
I maintain another app that has a Tasker hook thing, but it was put in
before I started maintaining it. Plus side, however, I haven't had to touch
it in the past 2 years and it still works!  I cannot see me looking at this
within 3 months but it's a feature I'd love to see.  Thanks for everything,
team!

**Comment by mikehardy** [comment]
We actually have a Tasker hook for syncing already. It is stable, as you mention, which is why a coupling at that level is something I'd consider - it could be generally applicable without needing much in the way of work here - which is important because I see the value but I really don't want to go down the whizzy features path for review, I think that's an endless task
