### ISSUE TITLE
negative review times

### ISSUE THREAD

**Issue by Trevie3** [ankidroid/Anki-Android#5792]
When I'm doing reviews anki gives a huge negative number for the number of minutes it estimates I have left, like -5000 minutes. Also looking at my statistics it says I spent an average of -24.3 minutes/day. I believe I actually spent 24.3 minutes/day. 

I will try to attach a photo. 
![Screenshot_20200305-224116_AnkiDroid](https://user-images.githubusercontent.com/10750829/76056058-b9e4bb00-5f32-11ea-9324-932ee38a9880.jpg)

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info

AnkiDroid Version = 2.9.4

Android Version = 9

ACRA UUID = efeaa499-111a-4b9b-9ddb-63af55f4eee3

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
@Trevie3 can you please join the alpha program following these instructions: https://docs.ankidroid.org/manual.html#betaTesting (and verify after a day or so that the Play Store app has delivered the app by looking at the bottom of the advanced settings to get the version string)

There has been work in this area and it might already be fixed
