### ISSUE TITLE
It seems pycmd('ans') not working?

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#5808]
I am using Memrise template for making card but it seems that pycmd('ans') not working.

It is working fine on anki desktop.

Also what should be option to call show answer and other button using JavaScript in Ankidroid?

https://ankiweb.net/shared/info/289642102
![20200312_013939](https://user-images.githubusercontent.com/12841290/76459548-67a80c00-6402-11ea-90fa-12f2ce46afff.jpg)

**Comment by mikehardy** [comment]
AnkiDesktop is written in Python and allows all sorts of plugins and hooks and things that work because it is not a secure environment and it is an untyped language.

AnkiDroid is written in Java and does not allow any plugins or anything because it is a secure environment and a strongly typed language. You might be able to do things using javascript but this is not something we will be able to support, you'll have to develop it yourself

I offer 2 items that might be interesting though - an example of complex javascript code using modern features: https://github.com/pigoz/anki-canvas

And that we expose the WebView we render the card with to powerful development tools so you can effectively develop things if you want: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

More than that is unsupported though - so I will close this

**Comment by TowelSniffer** [comment]
I made an updated version of the memrise template you are using here which has some nice improvements you may like: https://ankiweb.net/shared/info/1018121283

a substitute for `pycmd('ans')` that works across devices is 

```
<div style="display:none">
{{type:SOMEFIELD}}
</div>
<script>

function clickFunction(){
// Write the button's text into the type:Answer field.
var input = document.getElementById("typeans");
input.value = this.id;

// Simulate pressing enter on the input field.
var ev = document.createEvent('Event');
ev.initEvent('keypress');
ev.which = ev.keyCode = 13;
input.dispatchEvent(ev);
};

</script>
```

and then call with `clickFunction();`
