### ISSUE TITLE
Audio recording failure removes working audio preview

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5813]
Context: Was down the rabbithole of fixes for the infinite permission request loop. Failing a permissions check also produces this.

###### Reproduction Steps

1. Go to "Add Note" screen. 
2. "Record Audio", grant permissions
3. Record some speech
4. Cause an error by quickly double tapping the "Record Audio" button.  ([known error](https://github.com/ankidroid/Anki-Android/blob/7f8272b4519319fa88c081b36cf4809b22d08757/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java#L165))
5. Press "Play"

###### Expected Result

The previously saved recording is played

###### Actual Result

The recording has been deleted. "Playing Failed" toast message is shown.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Cause: A temporary file is not moved after recording. The same temporary file is used for multiple recordings. The following blanks the provided file.

https://github.com/ankidroid/Anki-Android/blob/7f8272b4519319fa88c081b36cf4809b22d08757/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java#L204

Fairly minor issue, I'd prefer not to step on anyone's shoes via conflicts, and will hold off on a fix for this until the area seems to have settled down.

**Comment by mikehardy** [comment]
Yeah - in fact this is an issue in general, because of this we can't reliably delete the file if there is a problem either, which means that after running an audio recording test (but not saving the card edits) you'll orphan a file (which you can then see with check media from the deck list)

I suppose the right fix would be to use a new temporary file each time (and correctly clean up after it) but that's a medium sized change and I'm mostly doing targetted crash fixes and shaping up existing PRs for merge now. If you've got the appetite for it, that's the direction though. Otherwise this will go in the queue for anyone else in the future

**Comment by mikehardy** [comment]
A quick note that part of the PR for #5426 / #5437 starts allowing for the recording target file to be plumbed through and returned (which would subsequently allow for an error recording to be removed and only a successful file to be saved)

**Comment by mikehardy** [comment]
Keeping this open at least through one stale cycle as it's a potentially good first issue
