### ISSUE TITLE
How to incorporate requery in code source

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5969]
While looking at profiler, I believe I found some inefficiency which can be easily corrected, but it requires to modify requery code a little bit.
Before making a PR to requery, I want to check my intuition. Do this change, put ankidroid with this change on my phone, and profile it.

I can't figure out how to do it.
I tried to open `sqlite-android-3.31.0-sources.jar` and put it in the path folder. I removed ` << "-Werror"` and `implementation 'io.requery:sqlite-android:3.31.0'` from build.gradle

But there is the error java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ichi2.anki-XbXGXl4DaXHWBSk7eQIxnw==/base.apk"],nativeLibraryDirectories=[/data/app/com.ichi2.anki-XbXGXl4DaXHWBSk7eQIxnw==/lib/arm64, /system/lib64]]] couldn't find "libsqlite3x.so" and I can't figure out how to remove it, how to try to use my version of requery.

For your information, I believe that in SQLiteStatementType.java the method getSqlStatementType could be more efficient. Scheduler check spends more than a second in it; mostly in the substring method.
Instead of doing it, doing a switch on the first letter, second letter and third letter would probably be faster (even if less beautiful)

**Comment by mikehardy** [comment]
You'll need to fork requery locally, make your change (so you will be most of the way to a PR anyway...) and build it publishing it to a *local maven repository* (this is actually very very easy to do but hard to learn how to do)

Then you alter the build.gradle so that your local maven repository is searched for dependencies when gradle does builds (again, easy to do, maybe hard to *learn* how to do), and you alter the dependency to be whatever you called your local requery build (maybe a SNAPSHOT build or something)

**Comment by Arthur-Milchior** [comment]
Doing an actual PR is easy. That's really not the part I want to consider right now.
I first want to check whether this will indeed improve ankidroid speed. This may justify doing a PR. I won't do one if it does not help in any way
