### ISSUE TITLE
Add cards to deck

### ISSUE THREAD

**Issue by walttheboss** [ankidroid/Anki-Android#6072]
I create decks in Calc.
I import them into anki on Linux desktop.
I put them on my phone in .akpg format
I import them into ankidroid.
I create a new deck. (it is empty)
I cannot figure out after an hour how to get my imported cards into that deck I just made.
YES it seems obvious. I have tried for a long time.
I now realize that even on the desktop I cannot put imported cards into a deck. 
PLEASE can someone tell me where in the manual it tells you how to add existing cards to a deck?

**Comment by mikehardy** [comment]
Can you search for them in the card browser? That's probably the easiest way (and note the manual has a great section on powerful searches you can do in the browser in order to really get just the cards you want)

Then you long-press there to pop into multi-select mode, select all (assuming your search is good!) and change deck

Should work?

**Comment by walttheboss** [comment]
Thanks @mikehardy.  That was great.  I felt so dumb but it is working now.

**Comment by mikehardy** [comment]
Glad that worked. The multi-select is kind of a hidden gem of a feature, maybe we need to add it as an explicit option in the menu so people know it is there
