### ISSUE TITLE
Synchronization takes ages after installing latest version of Ankidroid

### ISSUE THREAD

**Issue by patamat1** [ankidroid/Anki-Android#6079]
When synchronizing the app, it takes several minutes till it finishes- either it is stuck at uploading changes, or checking database.

Even when it finishes, no changes are made on the other side (Ankiweb and eventually Anki desktop).

Have to resynch several times before it actually sends changes to ankiweb.

**Comment by david-allison-1** [comment]
Hi @patamat1,

Could you post your debug information: `Settings - Advanced - About AnkiDroid - Copy Debug Info`. Which version were you using previously?

**Comment by patamat1** [comment]
AnkiDroid Version = 2.9.6

Android Version = 4.1.2

ACRA UUID = e920e920-d917-4b52-9f53-e465ff8cefa2


I believe it was the one before the latest update.

**Comment by mikehardy** [comment]
You should try the latest alphas - it has several modifications to the networking code and may resolve the issue https://docs.ankidroid.org/#betaTesting

If it does not, I'd assume there's something wrong in the network path between you and AnkiWeb, or AnkiWeb is having problems. If you are certain your network path is clear (high throughput, low latency, no packet loss) then you might try syncing to a fresh profile on AnkiWeb - some users report success doing that

**Comment by mikehardy** [comment]
Hi there! We found a couple things causing full sync to happen repeatedly, but otherwise we are not aware of syncing problems with the current code (2.10.2). If you can reproduce this with the latest stable we can reopen, but please please make sure you are on a good network first - we use TLS1.2 now and in general encrypted connections are more sensitive to lossy or low-quality networks
