### ISSUE TITLE
Anki hasn't created a test part yet! 

### ISSUE THREAD

**Issue by Drakedr** [ankidroid/Anki-Android#6084]
I've been using Anki for a while but I knew it many years ago when it was released first. 

All these years, I have used quite a few flashcards apps and many failed to satisfy my requirements and needs. Many on the other hand, came quite in handy featuring many options to develop study further. 

One of these features is a test or practice part where the student can evaluate his progress by having a select definition/ match cards/ writing review/ or just a simple review.

I'd appreciate it if you put this in the app. 

Also one more thing that can be extremely useful is having a choice to select if the user wants to see the word itself first and guess the definition or vice versa.

I find it very easy to guess the definition by reviewing the word several times. But what bugs me is that I won't be using the word that way.

In specific situations most probably I have a definition in mind and I search for a word to match that definition. So it'd be very helpful if the app can support this feature. 

I look forward to hearing from you 
Thanks

**Comment by mikehardy** [comment]
Hi there! That's not going to be an addition here unless it goes into Anki Desktop yet (http://anki.tenderapp.com)

I will say it likely won't happen there because literally every flashcard is a test (it's all "active recall"). You could do custom study on the cards you want based on a search for them, and check your stats and you have roughly the same feature at any rate. It sounds like your other concerns mean that you should add cards that connect the fact in your mind with a different recall method - hit the plus sign and add a new note? For searching the card browser is likely best

Either way, all new features go in Anki Desktop first - we focus on interoperation  and it is difficult enough simply keeping pace with Desktop that we don't add new features on our own,
