### ISSUE TITLE
Bug of the very last "red" flashcard

### ISSUE THREAD

**Issue by MisterYasai** [ankidroid/Anki-Android#6156]
Hello,
I'm french and sorry for my bad english... I use anki to learn japanese for few months to my computer, phone (ankidroid not an iPhone) and yesterday a bug has begin. I learn something like hundred or two hundred words and when there is just ≈10 flashcard  at the end...the app says it's finish ! But it's not ! 
Can somebody help me ? 
If somebody can help thank you so much.
![Screenshot_20200512-185443](https://user-images.githubusercontent.com/65246614/81725319-f9290e00-9485-11ea-80f5-f3d71c068e43.png)
![Screenshot_20200512-185451](https://user-images.githubusercontent.com/65246614/81725346-00501c00-9486-11ea-9b6f-b5691eddc840.png)

**Comment by david-allison-1** [comment]
I have replicated this, but Anki Desktop exhibits the same behaviour.

My Deck Picker shows no cards, and the summary page shows 18 today. 

Clicking "Study Now" in Anki Desktop displays "no cards are due yet".

AnkiDroid does the same, but brings the user back to the DeckPicker to display the notification.

**Comment by MisterYasai** [comment]
This is your problem too !! So there is no solution ?

**Comment by david-allison-1** [comment]
From my understanding (happy to be corrected: @mikehardy): 

We typically aim to emulate Anki Desktop perfectly when it comes to scheduling, it'd be best to request the feature at the tenderapp: https://anki.tenderapp.com/ so we can emulate it correctly.

I've had a quick look, and I believe that this inconsistency is already fixed by enabling the V2 Scheduler: https://anki.tenderapp.com/kb/anki-ecosystem/the-anki-21-scheduler

> The learn count is now the number of cards, instead of the number of steps required to complete.

Be aware of the caveats to upgrading, which are listed on the linked, but I expect this problem is already fixable.

**Comment by mikehardy** [comment]
Correct - we will mirror Anki Desktop even in it's inconsitencies and work to fix upstream then mirror that here. And if investigation shows the v2 scheduler doesn't behave that way I would recommend switching to it - that is definitely where the scheduling work is happening these days and in general if a fix exists, use it...

I'm going to close this based on the research as it is not actionable (we match upstream behavior) but don't let me discourage you from pursuing it upstream at anki.tenderapp.com at which point this could be reopened and pursued again here for a port
