### ISSUE TITLE
[feature req]: remnotes.io support

### ISSUE THREAD

**Issue by pihentagy** [ankidroid/Anki-Android#6162]
Is it planned to support remnotes.io?

**Comment by mikehardy** [comment]
remnotes.io does not even load for me, so...no?

Basic tactics for inclusion of new feature:

1) petition upstream in anki desktop first - we typically don't include features that aren't upstream, even if they are contributed fully working by the community, because any feature creates an ongoing maintenance burden and maintainers come and go, it's not fair to them if it's not important for the whole ecosystem
2) for Android specific items it is possible to include something not upstream, but in general you will have to code it up and contribute it yourself following the contributors guideline (which includes a discussion - likely here - where you should make a strong argument for inclusion and you propose a design that seems good)

We can re-open this if/when 1 and/or 2 happen

**Comment by pihentagy** [comment]
Sorry, mistyped the host. But now I guess you have not come across remote.io, which is a hopefully upgraded alternative to anki. See https://twitter.com/rem_note/status/1257044620825034754

**Comment by mikehardy** [comment]
Interesting, but not that interesting, to me. Closed source, pricing pages, API licensing etc etc. :man_shrugging: 

My statement stands though, work through desktop, if it goes in there make PRs here.
