### ISSUE TITLE
[2.10] - Fields containing {{type:Back}} no longer render

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6176]
Reported on reddit

* Note Type: Basic

Front:
```
AA{{type:Back}}
```

* In 2.9, this renders as a "Type Answer" card.

* In 2.10, this shows `AA{{type:Back}}`

**Comment by david-allison-1** [comment]
Regression test, will update with a bisect ASAP

<details><summary>TemplateTest.java</summary>

```
/*
 Copyright (c) 2020 David Allison <davidallisongithub@gmail.com>

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free Software
 Foundation; either version 3 of the License, or (at your option) any later
 version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with
 this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ichi2.libanki;

import com.ichi2.libanki.template.Template;

import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.HashMap;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

@RunWith(AndroidJUnit4.class)
public class TemplateTest {

    @Test
    public void testDataInField() {
        HashMap<String, String> context = new HashMap<>();
        context.put("Front", "AA{{type:Back}}");
        Template t = new Template("{{Front}}", context);

        String rendered = t.render();

        assertThat(rendered, is("AA[[type:Back]]"));
    }
}

```

</details>

<details><summary>Stack Trace</summary>

java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 
Expected: is "AA[[type:Back]]"
     but: was "AA{{type:Back}}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.ichi2.libanki.TemplateTest.testDataInField(TemplateTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	... 6 more
```
</details>

**Comment by Arthur-Milchior** [comment]
Can you please confirm that I understood the bug report correctly, and that the bug is with a card similar to the one in:
[tag_in_tag.zip](https://github.com/ankidroid/Anki-Android/files/4631334/tag_in_tag.zip)
?
Because if it's the case, you may want to try it in anki too. In upstream anki, it renders as "AA{{type:Back}}"
Note that in older version of anki it rendered only as "AA". But I can't find any version (I tried 2.1.9 and 2.1.15) where it actually asked for the back of the field.

That was actually a change that occured when anki moved to rust, for efficiency, it assumed that a field content had no tag. 
This also mean that if ever expect to use rust in ankidroid, you'll have exactly the same problem than the one mentionned in this bug report. 

I do recognize however that it is a regression and it is totally my fault. I would like to state for my defense that I assumed that we were following Anki's behaviour and so I didn't thought about improving behaviours which were differente from ankidroid. I believe I can state that I know anki code very well, and it's my mistake to assume that you want to stick to anki's behaviour 100% of the time.

**Comment by mikehardy** [comment]
I do want to stick to upstream, but upstream isn't perfect, and we have an installed base. So there are not absolutist positions worth taking, perhaps upstream needs a change, perhaps a quick change can help the installed base, those are possibilities even with a strong upstream fidelity goal

**Comment by Arthur-Milchior** [comment]
I fill that I should be that your change is going to create a problem as soon as we get an user which have
```
{{foo}}
```
in field foo
Because it will create an infinite sequence of never-ending replacement.

I should note that this problem is not new. It would actually already be a problem before the PR I created which made so many regression. Upstream used to have a limit to 100 iterations of the loop to avoid this problem. 
Actually, if you want to really crash your software, just use a field `foo` with content `{{foo}}{{foo}}`. It'll create an exponential explosion and quite quickly you won't have any more memory available

**Comment by Arthur-Milchior** [comment]
I guess that my question is: what are the rules to decide that you want to keep a feature that upstream decide to drop. I assume it might help me in the future when I try to port upstream improvement. 

I wish you good luck when you want to use Anki's Rust, because I don't see how you'll keep this feature while using upstream's rust code

**Comment by mikehardy** [comment]
> I guess that my question is: what are the rules to decide that you want to keep a feature that upstream decide to drop. I assume it might help me in the future when I try to port upstream improvement.

It depends? How big is the installed base that uses the feature? Was it dropped intentionally or was it just something no one thought of and hasn't been seen by enough users upstream to know?

> I wish you good luck when you want to use Anki's Rust, because I don't see how you'll keep this feature while using upstream's rust code

That assumes it was intentional and won't be re-added, and that we'll wrap the Rust and use it here in soon. Either way, good luck will help so despite detected sarcasm I'll take it.

**Comment by mikehardy** [comment]
> I should note that this problem is not new. It would actually already be a problem before the PR I created which made so many regression. Upstream used to have a limit to 100 iterations of the loop to avoid this problem.
> Actually, if you want to really crash your software, just use a field `foo` with content `{{foo}}{{foo}}`. It'll create an exponential explosion and quite quickly you won't have any more memory available

PRs welcome, ideally with tests included to prevent regressions.

**Comment by Arthur-Milchior** [comment]
> > I guess that my question is: what are the rules to decide that you want to keep a feature that upstream decide to drop. I assume it might help me in the future when I try to port upstream improvement.
> 
> It depends? How big is the installed base that uses the feature? Was it dropped intentionally or was it just something no one thought of and hasn't been seen by enough users upstream to know?

For the user base, I can't answer. For the last question, I can answer easily. It was a bug that tags occurring in field were considered as field, and this change was noted in an update note as a bug correction:
https://anki.tenderapp.com/discussions/beta-testing/1706-anki-2120-updates-to-card-template-rendering states
> {{field}} references are ignored inside fields, so there is no risk of LaTeX/MathJax being interpreted as a field reference.

To be more precise, I did encounter this bug, and many user of LaTeX did too; I saw it mentioned a few time, because it's really not intuitive. Even if it had an easy solution, since "{ {" is the same thing as "{{" in LaTeX and the first one does not lead to a bug.

> > I wish you good luck when you want to use Anki's Rust, because I don't see how you'll keep this feature while using upstream's rust code
> 
> That assumes it was intentional and won't be re-added, and that we'll wrap the Rust and use it here in soon. Either way, good luck will help so despite detected sarcasm I'll take it.

I beg your pardon. I didn't intend sarcasm. I really wanted to warn you that this is a problem that you'll meet the day you'll use rust. I was thinking that it was worth mentioning this risk, as it may not be clear to everyone.
As I don't expect to work on doing the actual work, and I'm not a mainteneur, it made sens to me to wish you "good luck", since David, you ,or someone else will be doing the hard work.

I also thought I did read discussions stating that rust was already an idea seriously considered. Of course my warning is useless if rust code is not introduced in ankidroid.
