### ISSUE TITLE
Reverse card for Sinokorean card

### ISSUE THREAD

**Issue by sringe** [ankidroid/Anki-Android#6195]
I really enjoy learning with Anki. I am now using a deck downloaded from the internet in the sino korea card type. However they are only in one direction. Is there a possibilty to add the same card deck also reversed? I know that there is a reverse card option for the normal card type but not for sino korean

**Comment by mikehardy** [comment]
Hi there! The theory here is covered in the manual, but the exact steps are basically to go into any of the notes of that card type, and in the note editor you will see a bar at the bottom that should say "Card 1". Tap that, and you will be in the "card template editor". Use the options menu at top right to add a card. By default if there is only one card in a card template, the second one you add will be auto-reversed, so that should do it. Save that and you're set.
