### ISSUE TITLE
Autosync status circa May 2020?

### ISSUE THREAD

**Issue by adamwolf** [ankidroid/Anki-Android#6201]
Hi folks!  Great work!

I'm curious as to the thoughts and plans and hopes and dreams around "starting a sync when you finish the last card of a day".  I know a few folks have worked on it a few different times, and I'm a little lost looking at the PRs and discussions.  If this is a sore spot, feel free to just delete without a second thought :)  (Is there a better way to have dev-to-dev discussion than this?  If you have recommendations please let me know!)

Thanks everyone!

**Comment by david-allison-1** [comment]
Hi @adamwolf 

We set up a discord about a month ago: https://discord.gg/J2rctZ

**Comment by mikehardy** [comment]
I would love for it to happen. The last hang up was that there were so many auto sync options it seemed like we should try to organize them. I only see one though "sync on start/exit".

I would love for there to be just one more option there that was basically "sync when reviewed last card of the day". That's a ...sore point in my own household with *one* parent always forgetting to sync the child's collection leaving the *other* parent out of sync.

This seems achievable.

Syncing on exit or app death is fraught and I wouldn't go there. But it seems like the transition state from "scheduler has cards still due" to "scheduler is all out of cards" is useful.

Extra credit ideas / thinking out loud:
- add a third option "Prompt to sync when completing a deck" that does what it says, for those people that have lots of due cards but a deck or three that they really focus on and stay current with. Prompt could be a modal or an extra toast / part of toast
- alter the sync to use the new material design / google recommended notification style instead of the nasty modal, so it is less intrusive
- once it is less intrusive, make sync-when-complete per-deck
- expand idea of "sync when done for day" from just transition to empty scheduler to also if hit the time limit for the day

**Comment by mikehardy** [comment]
There is some old related work laying around that I just rebased to current master and pushed to a local branch of mine, which had the preferences work I think? https://github.com/mikehardy/Anki-Android/tree/feature/auto_sync_after_studying_last_card

**Comment by adamwolf** [comment]
Hi folks, I was too poky and the invite expired.  Could I got another invite?  Thanks!

**Comment by david-allison-1** [comment]
> Hi folks, I was too poky and the invite expired. Could I got another invite? Thanks!

My fault. Non-expiring invite: https://discord.gg/qjzcRTx
