### ISSUE TITLE
Language settings should be displayed in their own language.

### ISSUE THREAD

**Issue by Sc-Weng** [ankidroid/Anki-Android#6251]
###### Reproduction Steps

1. Go to Settings -> AnkiDroid -> language

###### Expected Result

Different languages' names should be displayed in their own language. 
It is possible to set a wrong language. Display languages' names in their own language can help user to change language in an unfamiliar environment.

###### Actual Result

Different languages' names are shown in the same language.

###### Debug info
Android Version = 7.0
AnkiDroid Version = 2.10alpha

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
I mentioned this in Discord yesterday. Totally agree. 

Probably best to include both the current language and the language in the native name.

**Comment by Sc-Weng** [comment]
> I mentioned this in Discord yesterday. Totally agree.
> Probably best to include both the current language and the language in the native name.

Compared with Android system language settings, probably display them in their own lanugage is good enough. Including both current language and the language in the native name might make the UI become crowded.

**Comment by mikehardy** [comment]
The crowding was my only reservation when I saw that in Discord as well. I'm okay with just in the native language. If you can't understand the name of the language in it's native language, you *really* shouldn't switch to it because life isn't going to get better. And if you accidentally switch to it, seeing only language names in their language so you can read them is a good enough "save me now!" escape hatch. I've already seen the related PR (awesome!) and just want to see a quick screenshot then it's probably good to merge
