### ISSUE TITLE
[Suggestion] Allow Logging to text file for alpha/beta builds

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6264]
For issues that are hard to reproduce, it would be useful to provide users with a means to turn on debug logging, and dumping the results to a file so they do not need a dev environment: #5142

**Comment by mikehardy** [comment]
Different way perhaps - I think acra can attach files? (not sure if acralyzer can handle it though?) - turn on debug logging as a preference, then send debug log with error report that does an acra post with a logcat like the one we have now but with much bigger filters (since we have a file). Or if file posting doesn't work (or just sucks for some other reason) and acra+acralyzer can handle like 1000 lines of logcat, just "turn on debug logging" and "send error report"?

That's one way anyway. That's not particularly empowering though as the user can't see it themselves and one of the reason the HTML/JS debugging works well (it has in the past) for people willing to work is that it requires no coordination with anyone - it's all self-contained

Maybe "turn debug logging on" and "save debug log to file" that does an SAF save file intent with logcat filter query contents, and still maybe a send error report. Although that sounds gold-plated now

Thinking out loud

**Comment by david-allison-1** [comment]
We'll get this one 2.14/15 - maybe in a related issue, but providing beta/alpha testers with actionable crash data will help us.

**Comment by david-allison-1** [comment]
This is less relevant now we have "send exception report" but will still help users self-diagnose issues.

**Comment by david-allison-1** [comment]
This is a "nice to have". Now we can manually send an exception report, it's much less useful
