### ISSUE TITLE
Card Browser: Fail to searching certain cards containing brackets and stars

### ISSUE THREAD

**Issue by jianersswlq** [ankidroid/Anki-Android#6298]
###### Reproduction Steps

1. Create a card with a question that contains _*hello(world)_
2. Open Card Browser
3. Use _*hello(world)_ as the input of searching
4. Result display

<img width="177" alt="image" src="https://user-images.githubusercontent.com/60961497/83263962-ff431c80-a1f1-11ea-9dd5-62f2b3ae1aa2.png">

###### Expected Result

Show the card with _*hello(world)_ 

###### Actual Result
Nothing to show

###### Debug info
AnkiDroid version = 2.11a

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Sc-Weng** [comment]
@david-allison-1 Hi, I am trying to fix this issue and find the cause of this issue is due to char '('.
https://github.com/ankidroid/Anki-Android/blob/be587b4553854b1d6c7a07fb5f3693a937de3966/AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java#L181-L190
In this code, '(' has been separated and cause the tokens become "helloworld" and "(". Rewrite this part of code is simple but I not sure what did the original function do. I need your advice on how I can fix it.

**Comment by david-allison-1** [comment]
@Sc-Weng, I'm really sorry, I haven't had time to look at this yet.

Your first bet would be to check to see if this behaviour is consistent with Anki Desktop, anything in `libAnki` was a port of the python code in Anki Desktop.

The Python code has likely changed significantly due to a rust conversion, but this file used to be finder.py in the history, and you can trace it.

To answer your question, it's likely related to this section of the Anki manual: https://docs.ankiweb.net/#/searching?id=simple-searches
