### ISSUE TITLE
New skin -- Suggestions about UI

### ISSUE THREAD

**Issue by zyllzy** [ankidroid/Anki-Android#6300]

**Comment by mikehardy** [comment]
In my experience, in open source, everyone has an idea about what the UI should look like, and everyone dislikes everyone else's UI. In the end projects develop full theming engines in order to handle this and those become a source of bugs and maintenance effort and frequent change anyway so that user themes are always broken.

Which is all to say, I am personally not really interested in changing colors. Lots of work and collaboration and effort, very little gain. I suggest using the night mode, or editing your card templates and turning on immersive mode with gestures.

I would be open to modernizing the current implementation of the UI as material design itself has advanced - with the restriction being that any changes should be defensible from the perspective of the material design guidelines - but that has been attempted before and near as I can tell no one has the free time available to finish it: #5126

So I'm closing this, but would accept a material design refresh PR as indicated.
