### ISSUE TITLE
Improve "AnkiDroid Directory is Inaccessible" when user has no permissions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6334]
Presumably happens when the user has ticked "remember & reject permissions".

Instead, we should explain what we need to do, instead of booting them to the preferences with no hint to grant us permissions.

**Comment by mikehardy** [comment]
This is not a great pointer because it relies on a mix of typescript and android to do the implementation but the flow-chart is worth understanding. 'WRITE_STORAGE' is available on all devices, so this would go into the "requestable or not" decision immediately

https://github.com/react-native-community/react-native-permissions/blob/master/README.md#android-flow

That react-native module also does have android code how to open settings on the app as well, which you could do behind a dialog that said something like "we've noticed that the storage permission we requires is blocked. Once blocked, it may only be changed in settings. Open settings now?" - stackoverflow probably has code for it as well if that's easier

**Comment by david-allison-1** [comment]
We already open settings, but users don't seem to get that we're hinting they need to change something. This mostly refers to the Toast which is displayed, and seeing if we can get a specific "Give us permissions please" before moving them to another app.

**Comment by david-allison-1** [comment]
Fixed by #6477 (ec68b00321c01babdc223beb1f9c6ae54b852eb0)
