### ISSUE TITLE
Feature request: support regex searches in libanki/finder.java

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6427]
This isn't something I'd use many times, but I might attempt implementing. [Anki 2.1.24+ supports regular expression searching in the browser](https://docs.ankiweb.net/#/searching?id=regular-expressions)(and also filtered decks? Need to confirm) using a syntax of `re:`. If there's nothing holding back changes to finder.java, I'll give this a try.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Hi is this still open? if so can i work on it after my current PR gets closed?

**Comment by david-allison-1** [comment]
We'll be ripping out the search backend as part of the Rust conversion, the code's there, just needs integration in 2.16

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens
