### ISSUE TITLE
Move marketing assets to own repository

### ISSUE THREAD

**Issue by nicolas-raoul** [ankidroid/Anki-Android#6431]
- Many assets are at https://github.com/ankidroid/Anki-Android/tree/master/docs/marketing
- Other are lost in issues, for instance [this excellent one](https://github.com/ankidroid/Anki-Android/issues/6294#issuecomment-637982202)

Both are far from ideal, the first makes the source code repo heavier and the second is unmanageable.

Solution: Create a separate repository such as https://github.com/ankidroid/ankidroid-marketing for these.

Example of another app using this strategy: https://github.com/commons-app/marketing

**Comment by mikehardy** [comment]
I actually disagree a bit - only because I think using git and full version control is a barrier for lots of contributors who otherwise are good at graphics. But github also gives us a free wiki site, so just doing a wiki page and putting them there might work. But a separate repo could also be fine, this would be well within my "implementor's choice" criteria where who ever was doing the work should do what they like ;-)

**Comment by sudomain** [comment]
The wiki is technically a separate git repo on it's own that Github gives a special UI for (see https://github.com/ankidroid/Anki-Android.wiki.git). It should also be noted that `git rm` will remove files, but not from previous commits so the source code won't get lighter. To remove files from previous commits, one of [these tools will be needed](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository)
