### ISSUE TITLE
White LaTeX unreadable due to white background 

### ISSUE THREAD

**Issue by matoototo** [ankidroid/Anki-Android#6439]
###### Reproduction Steps

1. Generate some LaTeX in white.
2. Open the flashcard in AnkiDroid

###### Expected Result

Captured on my PC setup:
![](https://i.imgur.com/NrmtNIL.jpg)

###### Actual Result

Android phone running Anki 2.11.1
![](https://i.imgur.com/QBCWiPg.jpg)

###### Debug info
 
AnkiDroid Version = 2.11.1

Android Version = 8.0.0

ACRA UUID = dac71b8a-391a-4055-840e-7a9938e1ef1a

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @matoototo, thanks for the report!

@Arthur-Milchior, looks like fallout from https://github.com/ankidroid/Anki-Android/pull/6246 (c2103bacea1db395250eb22720942176f0a7f559)

**Comment by Arthur-Milchior** [comment]
I guess it means that someone who really understand CSS should start understanding why
```css
.night_mode .latex {
    filter: invert(100%);
}
```
did fail.
I'll try it on my phone. If it only fails on emulator, it is not a serious problem. But I can't imagine how it fails on emulator and not on phone.

**Comment by Arthur-Milchior** [comment]
I posted on https://github.com/ankidroid/Anki-Android/pull/6440 some code to remove white background and do the same thing as desktop anki: invert colors.

I just realized: if the LaTeX is really white, and since we inverse color in night mode, the text will become black. So instead of white on white, they'll get black on black.
Normal usage will be more beautiful, (i.e. for black LaTeX it'll become white on black), but I don't know whether it'll solve your problem. 
Actually, I'd have expected that you'd have the  problem I'm describing on anki desktop. If you generate image with white text, since anki's night mode invert color, you should get black text in night mode...

**Comment by matoototo** [comment]
On desktop they're generated as \color{white} text with a transparent background, if that helps. Nightmode doesn't invert it (the setting is ticked off) so there's no problem there.

**Comment by Arthur-Milchior** [comment]
Can you please elaborate which setting you're referring too ? I don't believe we have any similar setting in ankidroid, so the problem may occur

**Comment by matoototo** [comment]
I have fixed the issue by adding `.nightMode .latex { filter: invert(0%); background-color:transparent; }` to my styling. The problem was with me being on Anki 2.1.15, while Anki started inverting LaTeX in 2.1.20. Additional confusion arose from me having the night mode addon installed which has an 'Invert Latex' option so I thought you were referring to that. Apologies for the bother.
