### ISSUE TITLE
Improve sync between devices

### ISSUE THREAD

**Issue by subbota-a** [ankidroid/Anki-Android#6520]
###### Reproduction Steps

1. I do my exercises in the app on a Android phone
2. On the next day I get Android tablet (another device) and want to do my exercises
3. The tablet doesn't sync with the phone

###### Expected Result
The phone has to sync with server my progress after some time I close the app. So when I get another device the server image is already actual.

**Comment by freemedom** [comment]
Did you go to Settings and say "Get Media while Syncing"?

**Comment by freemedom** [comment]
> ###### Reproduction Steps
> 1. I do my exercises in the app on a Android phone
> 2. On the next day I get Android tablet (another device) and want to do my exercises
> 3. The tablet doesn't sync with the phone
> 
> ###### Expected Result
> The phone has to sync with server my progress after some time I close the app. So when I get another device the server image is already actual.

Did you go to Settings and say "Get Media while Syncing"?

**Comment by subbota-a** [comment]
Yes, I have it enabled. And the option for automatically uploading too. If I run a sync manually everything is ok. 
--
Отправлено из myMail для Android воскресенье, 21 июня 2020г., 10:11 +03:00 от freemedom  notifications@github.com :

**Comment by Arthur-Milchior** [comment]
You have option to automate sync when you quit the app. Is there anything wrong with it ?

**Comment by mikehardy** [comment]
@Arthur-Milchior this is the subject of much discussion previously #3798 it is not viable because the system has the right (and frequently exercises it!) to shut the app down without calling the onDestroy() methods, and those are the only app-level hooks we get on exit. I think the best thing is to use Tasker, set up an on power hook to call AnkiDroid and we have that hooked up for sync.

I have actually been working on a different app that hooks in to some of the broadcast intents from the system and it might be possible to set up auto-sync on plugin for us but that's still unreliable. We could set up a time-based sync where we attempt to sync at a pre-defined time so people could do it overnight but that's a lot of feature for a still-unreliable case.

The only thing we can rely on is the case I think we have settled on but not implemented yet: option to sync after finishing a deck #6201

**Comment by adamwolf** [comment]
Ah! Is there currently a way to trigger a sync from Tasker? Do we have a
guide/tutorial/paragraph on that?

**Comment by david-allison-1** [comment]
@adamwolf https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API#sync-intent
