### ISSUE TITLE
[QUESTION] Gamification Sounds Upon Answering Correctly

### ISSUE THREAD

**Issue by jeffshek** [ankidroid/Anki-Android#6542]
Random question here - would there any desire to add some type of gamification sounds to answering correctly? 

It would have configuration to turn on/off this setting, but if the user answers correctly, it makes a pleasant "ding". (or double ding if easy, etc).

I wouldn't mind doing the work and adding this, just not sure if it would be accepted. I'm thinking about this from Duolingo's gamification where the sounds can make a user continue doing more cards than normal. Thanks!

**Comment by mikehardy** [comment]
Hi there - how do you know if the user answers correctly? What I mean is, it's self-evaluation right? So you just assume if they hit one of what we call the "Ease" buttons and it's not "again" (aka "EASE_0" or 1 I forget sorry) then you play the sound?

If so, then this might be the right spot for our new javascript API rather than having it go in the core code

We're trying our best to not add too much reviewer / UI stuff in the core as it's already massive and hard simply to maintain and the demand for reviewer features is endless

Javascript lets you play sounds
If you made a template that replaced the reviewer buttons with your own then as you called the existing JS API we have that answers the card you could play the sound you like

@infinyte7 I think already has some templates close to this, just not with sound

**Comment by infinyte7** [comment]
Yes, that can be done using AnkiDroid javascript api.
By default we can not know which button pressed but js api and putting custom designed buttons on screen can let us to play desired sound for respective button.

**Comment by david-allison-1** [comment]
Related: #5325

At the moment (AFAIK), the JS API can only be hooked via a specific note type/note fields.

For this, we'd likely need to load user-specified JS, so we can apply the feature globally, rather than requiring that a user modifies all their note types. 

We're also trying to perform an action just before the WebView is refreshed for a new card, so I presume this would require the WebView an ability to send a "playSound" to the Reviewer, so we have persistent sound after the review is completed.

There's also the question of interference with audio cards (should we duck the success chime if the next card has audio, or just queue up the next audio file after the chime completes).

This is a wanted feature, as it makes hands-free reviewing easier. Also (probably) good for accessibility.

**Comment by lucwastiaux** [comment]
@jeffshek if your deck is simple plain text (no images no cloze), you might want to take a look at AnkiReview, built on top of AnkiDroid's API. It's designed to make the reviewing experience a bit more fun. There's a single set of answer sounds currently but that could be expanded. 

https://github.com/lucwastiaux/AnkiReview

**Comment by infinyte7** [comment]
Possible implementation using Js API
```html
<button onclick="myBtnClick()">Show Answer</button>
<script>
function myBtnClick() {
     playSound();    // add any sound to the function
      // After 1 second
     setTimeout(function(){ 
        showAnswer();   //JS api
     }, 1000);
}

function playSound () {
      // Add here play sound script
}
```

**Comment by mikehardy** [comment]
Out of curiosity - @infinyte7 - is there any way to access the media files from the JS? I think they are just generally available, so this can sync across devices as well, if it is in the template (or in the "general javascript plugin" location that we create whenever we create that...)

**Comment by infinyte7** [comment]
It is accessible.
```
function playAudio() {
        var audio = new Audio();
        audio.src = "_myAudio.mp3";   // in collection.media folder
        audio.load();
        audio.play();
    }
```

**Comment by lucwastiaux** [comment]
It doesn't make sense to me to continue hacking this way. AnkiDroid should split into collection management and reviewer modules. Then the reviewer modules can be extended to have feedback sounds, themes, etc.

**Comment by mikehardy** [comment]
@lucwastiaux and how do you propose to load these modules? My best guess, and where we are headed, is that the only way to do so without signing / encryption and other platform needs related to native code is to expose as much as possible in Javascript, which is strongly supported by the platform instead of discouraged.

In other words, you and I agree, and we're a good chunk of the way there already.

Have you seen the demonstration videos posted on the javascript versioning PR? To see what's possible now if you effectively ignore the "built in" reviewer experience entirely by hiding it's elements and building your own reviewer in Javascript? The future's here now, we just need to work on a way to have these "reviewer modules" (or as I think of them, "javascript files you apply on each card display") stored in a discoverable place that's synced (for safety) and easy to manage (create/replace/update/delete). But they already work.

**Comment by lucwastiaux** [comment]
I see what you mean, I think the essence of what you are saying is: technically, this is already possible. And what is missing is the "marketplace" component which would allow novice users to apply those customizations to their decks without manual editing of their templates.
AnkiDroid is an innovator here and may get a chance to influence the design of Anki/AnkiMobile. Should be interesting !

**Comment by mikehardy** [comment]
Yes - once we have management of the JS blobs down - then however people want to curate them (probably just starting as a wiki page here) and we're off to the races to see what people can do, and what it popular (or what is just niche but totally doable if you are in to it..). And if something is really popular it might be ingested on all platforms (like calendar heatmap) or if the style in general is popular it *should* be fairy trivial to emulate our exact mechanism on all the platforms since they all render WebViews same as us and we all have a collection etc

It will take some months yet before the JS-blob-management components are done, at least, as they're not really on a roadmap at the moment, but it will happen I'm sure

**Comment by lucwastiaux** [comment]
Sooner or later I'm going to experiment with the JS customization features. Didn't get around to it yet. But i'm planning on, this is something i'm very interested in.

**Comment by mikehardy** [comment]
If you wanted to decide where in the collection to put them (media I guess? maybe just mandate a file prefix?) and make a quick CRUD (create/replace/update/delete) interface for them, then alter card render to just apply anything it found in there, we'd be done :thinking: :smile:

**Comment by lucwastiaux** [comment]
Putting themes and javascript in collection is the easy way to do, and it's supported by AnkiWeb. But it's not strategic because it doesn't allow themes to be updated by their creator. It requires the user to apply a theme multiple times, to all of their decks (if they don't share a note type).
So I would suggest trying as hard as possible to not store it in the collection, unless Anki/AnkiMobile introduce support for themes that lives independently of the decks.

**Comment by mikehardy** [comment]
we already have semantic-versioning and a developer contact feature, no reason we couldn't have an update URL and manifest description format (sort of like npm...maybe just npm) and have an "update" button that scanned the updates URLs for new versions. Media already lives outside of decks in the form of fonts, I believe if it has a special prefix (underscore?) it will be synced but not pruned on media checks.

**Comment by lucwastiaux** [comment]
If you can segregate data inside the collection/media folder then I guess it could work. At a high level I'm hoping that novice users can "apply" a theme and continue to get updates with the same ease as downloading an app from the iOS app store.
