### ISSUE TITLE
AnkiDroidJS.ankiGetNextTime4() is empty when "Show button time" option is disabled

### ISSUE THREAD

**Issue by danZ4C** [ankidroid/Anki-Android#6656]
AnkiDroidJS.ankiGetNextTime1()
AnkiDroidJS.ankiGetNextTime2()
AnkiDroidJS.ankiGetNextTime3()
AnkiDroidJS.ankiGetNextTime4()

All 4 return empty values if the following option is disabled:

"Reviewing > Show button time (Show next review time on answer buttons)"

If it is enabled, they all work fine.

**Comment by Arthur-Milchior** [comment]
If I understand correctly, you want to have access to those number in you're JS, but don't want them displayed on buttons. Right ?
I guess it used to be assumed that the text for next time was only used for buttons so it was a correct place to check whether the user want review or not.

You'd prefer to have access to this number has a string, or as a number of seconds ?

**Comment by danZ4C** [comment]
Sorry, if that is intended behaviour thats fine, Ideally id be looking to hide the answer buttons entirely (not be in full screen, i still want to see the top bar and the system bar) and use my custom user interface in JS entirely.

I just hid the time shown on the answer buttons in order to reduce the interface, but i assumed the JS functions should work independently of the UI setup. If it is incorrect assumption I do apologise.

In terms of string/seconds, i have no preference really, either has its pros and cons.

**Comment by mikehardy** [comment]
@danZ4C no worries, the focusing questions are because the JS interface is completely brand new, it may not function in a useful way at all until we have feedback from real users and tweak it a bit. I think availability of information and presentation of information should be separate personally, and making it available to JS can happen all the time. I think we should stay with the formatted string though, one of the "services" AnkiDroid can provide to the presentation layer is that we centralize translation efforts and formatting (a big part of the project by effort if calculated in person-hours!), so we should sent those through. I could see sending formatted and raw but I wouldn't get rid of the formatted strings, taking advantage of the translation effort is a big win
