### ISSUE TITLE
..."APP_READ_DATABASE" detected

### ISSUE THREAD

**Issue by starblade09** [ankidroid/Anki-Android#6683]
Can you give me a full and honest breakdown of what your app does  and what permissions are utilized, on the back end? Why am I finding such dangerous permissions on this? on an app I thought was said to be open source and privacy friendly? 

Does this app operate on its own local database? Or what's going on here. *You are utilizing SQL of some sort: give me a full breakdown on what is being done here as well.

**Comment by mikehardy** [comment]
Hi there!

You have the wrong app I think, or are mis-reading things. You're worried about privacy, so if you intend to understand my answers, you must be very precise.

I can only respond to my guess as to what you meant.

`APP_READ_DATABASE` is not an android permission: https://developer.android.com/reference/android/Manifest.permission

`com.ichi2.anki.permission.READ_WRITE_DATABASE` is (as should be obvious by the name) an AnkiDroid-specific permission. We define it ourselves. 

https://github.com/ankidroid/Anki-Android/blob/e0be1ff0dee48bf6f1fbf98a24665d71daba63a2/AnkiDroid/src/main/AndroidManifest.xml#L38-L42

That's the permission required by *other* apps in order to our low-level programming API to modify your flashcards database. That's a neat trick where other dictionary programs can export a word you just looked up directly to your flashcards so you can memorize it.

And you better believe we use SQL in order to maintain our flashcards database, because losing data is bad, right? And fast operation on potentially hundreds of thousands of flashcards is good, right? So we trust sqlite (a SQL implementation) to hold our data.

The only privacy things that are worth knowing about AnkiDroid are that:

1. we require WRITE_EXTERNAL_STORAGE which is write access to all of your external storage. We certainly don't abuse it (but audit the code yourself) and will transition to "scoped storage" as soon as we can #5304 but we're volunteers so it'll happen when it happens. We have to put the database somewhere though, and it can be massive so it needs to be external. The app's existed more than 10 years before there even was a permission, so it is just a 10 year old legacy decision and here we are.
1. we may request camera or audio permissions if (surprise) you ask to include a photo or audio in a flashcard you are creating. Fairly necessary for that. But optional, deny them if you like.

Now I want to be clear on one thing though: your tone is unfriendly. "said to be"? seriously? Do you approach all volunteer projects, asking for detailed answers, with language like that? And assumptions about danger? I must admit I almost didn't take the time to answer you.

But, I did. Hope the information is sufficient for your flashcard needs.

**Comment by starblade09** [comment]
> Hi there!
> 
> You have the wrong app I think, or are mis-reading things. You're worried about privacy, so if you intend to understand my answers, you must be very precise.
> 
> I can only respond to my guess as to what you meant.
> 
> `APP_READ_DATABASE` is not an android permission: https://developer.android.com/reference/android/Manifest.permission
Hey. Yes , I was in such a rush when I made this post response. I do apologize as coming off to be rude. I am seriously just concerned about my privacy , though at this point. I would greatly appreciate one last answer.


> `com.ichi2.anki.permission.READ_WRITE_DATABASE` is (as should be obvious by the name) an AnkiDroid-specific permission. We define it ourselves.
> 
> https://github.com/ankidroid/Anki-Android/blob/e0be1ff0dee48bf6f1fbf98a24665d71daba63a2/AnkiDroid/src/main/AndroidManifest.xml#L38-L42
> 
> That's the permission required by _other_ apps in order to our low-level programming API to modify your flashcards database. That's a neat trick where other dictionary programs can export a word you just looked up directly to your flashcards so you can memorize it.
> 
> And you better believe we use SQL in order to maintain our flashcards database, because losing data is bad, right? And fast operation on potentially hundreds of thousands of flashcards is good, right? So we trust sqlite (a SQL implementation) to hold our data.
> 
> The only privacy things that are worth knowing about AnkiDroid are that:
> 
> 1. we require WRITE_EXTERNAL_STORAGE which is write access to all of your external storage. We certainly don't abuse it (but audit the code yourself) and will transition to "scoped storage" as soon as we can #5304 but we're volunteers so it'll happen when it happens. We have to put the database somewhere though, and it can be massive so it needs to be external. The app's existed more than 10 years before there even was a permission, so it is just a 10 year old legacy decision and here we are.
> 2. we may request camera or audio permissions if (surprise) you ask to include a photo or audio in a flashcard you are creating. Fairly necessary for that. But optional, deny them if you like.
> 
> Now I want to be clear on one thing though: your tone is unfriendly. "said to be"? seriously? Do you approach all volunteer projects, asking for detailed answers, with language like that? And assumptions about danger? I must admit I almost didn't take the time to answer you.
> 
> But, I did. Hope the information is sufficient for your flashcard needs.

It does indeed. From my memory of deeper analysis on your app, I did discover that there were some questionable permissions , in my opinion. And no disrespect at all. I am, again, concerned about my privacy. From my understanding ,everything works on a local level, and now I'm just generally confused.

`READ_WRITE_DATABASE` was what I did spot, yes. You solved the exact problem I was specifying. The problem is, the rest of the permissions and their capabilities. 

Although that permission is put to rest, what about `ACCESS_MEDIA_LOCATION` ? Does this not expose geolocation silently? Just a hypothesis. I'd like to be knowledgeable about these permissions so that I am aware of what's going on.

**Comment by david-allison-1** [comment]
> Although that permission is put to rest, what about `ACCESS_MEDIA_LOCATION` ? Does this not expose geolocation silently? Just a hypothesis. I'd like to be knowledgeable about these permissions so that I am aware of what's going on.

Where do you see this permission being requested? It's not in our manifest and it's neither on Google Play, nor FDroid.

https://github.com/ankidroid/Anki-Android/blob/983ed0269ffdd6960f22c90a9f2df5959bb5ec5d/AnkiDroid/src/main/AndroidManifest.xml#L26-L42
