### ISSUE TITLE
Due cards calculation - deviation between AnkiDroid/Anki desktop (and AnkiMobile)

### ISSUE THREAD

**Issue by p4nix** [ankidroid/Anki-Android#6687]
Anki2.1.28beta5
AnkDroid 2.12.0beta5

I think I can recall this error on earlier (non-beta) versions of AnkiDroid and Anki though, but I am not exactly sure (could have also been deviations between AnkiMobile/Anki Desktop). It was always resolved with a bold full sync there.

###### (Reproduction Steps)

Alright, I don't have *real* reproduction steps. I have, however, a saved state of the collections of Anki. I am not sure if they turn out to be helpful, I might try if they can indeed reproduce the error - but I wouldn't like to share them publicly anyway.

Yesterday, I went to sleep with AnkiDroid and Anki Desktop having the same amount of due reviews. When I started reviewing today, I realised that there is a deviation between AnkiDroid and Anki Desktop:

Anki Desktop: 2134 due cards
AnkiMobile: 2134 due cards
AnkiDroid: 2045 due cards

Private messages with @david-allison-1 indicated that the issue might be with calculating daily limits across the different options groups.

I decided trying to find the cards which wouldn't show up on AnkiDroid by using filtered decks, and pulled out more and more cards. This was after a few reviews, with Anki Desktop at 1980 due cards, AnkiDroid at around 1920 due cards:

![image](https://user-images.githubusercontent.com/7038116/87789271-0fb16400-c83f-11ea-80bf-d7df16098d6d.png)

To my surprise, the deviation between AnkiDroid and Anki Desktop got less and less (as seen in the "Über" deck) - until it was zero. I tried to find which subdecks were calculated wrong by deleting the filtered decks, but (again) to my surprise, the error wasn't reintroduced and AnkiDroid stayed at the correct amount of due cards: 1980.

This is a hint that something is going wrong in the calculation of due cards across subdecks in AnkiDroid - at least, sometimes.

Notable things:
* I don't cap reviews
* Subdeck structure goes down to 4 levels Über::B::C::D, but errors were definitely already present in a subdeck with 3 levels (Über::X::Y).
* all of my decks have a different option group

As soon as I have the time, I will try to reproduce the error with the backups I have made, but maybe someone has an idea earlier. I would be happy to share the collections with a few developers here I trust, but would still like to avoid it. If there are somre more general statements I can make to pinpoint the error, I would be glad to provide them.

The bug isn't critical, as it likely normalises with less backlog :P

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by p4nix** [comment]
As of today, AnkiDroid has *more* cards than Anki in review. I can not tell if it's related, but I will watch what's happening after I got some reviews done - if it normalises or if the difference stays the same.

**Comment by david-allison-1** [comment]
@Arthur-Milchior Is this an instance of the new desktop behaviour that we replicated in 2.13?

**Comment by Arthur-Milchior** [comment]
I can't recall any change in the desktop behavior related to counts that I ported to AnkiDroid.

I may imagine the desktop changed and that we did not port this change. It would be interesting to know whether there would have been the same problem with anki 2.1.15 by example, a version which still did not use rust. The computation of those numbers now belongs in the rust part of the code. Until I can read rust, I've no way to really check the upstream code and see what's going on.


@p4nix, it would be useful to know whether it's sched v1 or V2, they don't count cards the same way. It would also be useful to know whether the error was in a subdeck, or only on top level deck, and whether there is card in the inner-most deck with the error. Did you take into account cards in learning ? Because anki counts cards in learning and review card together while we show them in separate columns

Please note that we had difference with upstream when a deck has more than a 1000 new/rev card to see today. This is not new at all. Anki used to limit numbers to a thousand card to see in each deck while we had the `mReportLimit` at 99.999. But this should not by itself explain why there is less card in ankidroid.

**Comment by p4nix** [comment]
Scheduler V2. I haven't run into troubles again and also had issues reproducing the behaviour back then etc. No cards were in learning that time, as I was currently catching up on reviews. Even so, I am aware of the difference between Anki/AnkiDroid in terms of learn/review cards. If I remember correctly (let's give it 85 % probability), the issue was seen in the lowest subdeck.

**Comment by Arthur-Milchior** [comment]
Please let us know if it occurs again and if you can, mention me so I see the bug.
