### ISSUE TITLE
Ankidroid keeps crashing after enabling whiteboard in custom study session.

### ISSUE THREAD

**Issue by kodovanie** [ankidroid/Anki-Android#6710]
Hi all,

I created custom study deck by choosing review ahead. I was going through many cards. While reviewing cards, I accidentally touched "enable whiteboard" and Ankidroid crashed. When I reopen Ankidroid, my custom study deck is still there, remaining amount of cards to go through seems to be ok, but when I try to open this deck in order to continue reviewing cards, ankidroid crashes every single time.
The crash does not seem to happen when I try to open other decks (i.e. non-custom ones).

When the crash happend for the first time, report was being generated and sent - however my wifi connection was off. When I turned on the wifi and had these crashes again, I did not have a message that ankidroid has stopped working and message was being sent to developers.

Can I delete (send back) cards from custom study session or am I risking moving this "error" to other decks?

I have:
Android 4.1.2.
Ankidroid 2.12.0beta5
ACRA UUID = e920e920-d917-4b52-9f53-e465ff8cefa2

**Comment by david-allison-1** [comment]
Thanks for testing!

This is: #6665

Fixed in later versions of the 2.12 beta, please upgrade to 2.12.1, or the 2.13 alpha branch if you want to continue testing

All the best,

David

----

Please let me know if your require more assistance. If you can't upgrade, remove the pen colour icon from the reviewer in the settings
