### ISSUE TITLE
Investigate NoteEditor.mCurrentEditedCard - it is static, why?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6728]
I think the main question to ask (likely for a future PR) is whether the variable needs to be static in the first place.

It's persisted from a previous instance of the screen, and doesn't seem like the correct action to take.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/6727#issuecomment-663065340_

**Comment by Arthur-Milchior** [comment]
This was introduced in 2014 in 0edd4404a5cbd7922394edf08537358879d7d631 by @timrae. It speaks of JoltaTech and I don't know what it is. The best hope is that Tim recalls the reason 6 years later :p

**Comment by timrae** [comment]
Lol I believe this was the very first commit I made to the project, when I had absolutely no idea what I was doing in terms of the AnkiDroid code base, Android programming, Java, or Git... 😆 

Jolta Tech is the name/alias of the developer who did the work adding [`PreviewClass.java` ](https://github.com/ankidroid/Anki-Android/commit/0edd4404a5cbd7922394edf08537358879d7d631#diff-1156b8df96d68f69eac3db9f367f13db) to AnkiDroid. I believe he did it on an a branch with a new version of the note editor that never got accepted due to bugs and missing functionality without creating a pull request and then dropped off the radar, and I was the one that copy pasted his class into master, made it compile, and submitted the PR. Unfortunately there wasn't much happening in the way of strict code review back then, and it was accepted as is without any .

**Comment by timrae** [comment]
As for why it was `public static` it would have just been my misguided way of making the card in the `Reviewer` accessible by the `PreviewClass`. By all means please fix it.
