### ISSUE TITLE
Autofocus focuses clozed question, but unfocuses answer reveal

### ISSUE THREAD

**Issue by PaperOrb** [ankidroid/Anki-Android#6767]
This is part bug, part feature request. 

I like to have pages of questions when studying where I'll fill in the answers as I go, and then place those pages all into a single note and cloze out the answers/definitions. 

The clozed portion is auto focused successfully in ankidroid when going to a new card, but when the answer is revealed, it scrolls back to the very top of the card. Not to seem ungrateful, but pretty much stuck using the desktop client until anyone has time/interest to adjust this.

**Comment by freemedom** [comment]
phone's screen  is  too small ,（=´∇｀=）

**Comment by freemedom** [comment]
I think the code to solve this problem is going to be very complicated

**Comment by david-allison-1** [comment]
Hi @freemedom, could you please try and make sure that comments will help move the issue along?

----

Hi @PixelGold, thanks for the feature request! This is functionality which can already be implemented via JavaScript and the [Anki Persistence](https://github.com/SimonLammer/anki-persistence) library on your note types. 

We currently follow Anki and move to `#answer` if it exists, I can't see this changing, as it will be confusing for the majority of our users. But, as it's implemented in JavaScript, you're free to change the functionality to suit your needs.

https://github.com/ankidroid/Anki-Android/blob/7d68b87a7e2f37a99dabdfabc6225d614a540146/AnkiDroid/src/main/assets/scripts/card.js#L179-L181

If you're not familiar with JavaScript, you can likely get some help online. The [Anki subreddit](https://www.reddit.com/r/Anki/) is typically very helpful.

Thanks!

David

**Comment by freemedom** [comment]
I just want to express some views on this feature(￣▽￣)",
I am not very familiar with programming languages such as Java JS.
Maybe it will be a year or two before I can make along with some programming development. @david-allison-1

**Comment by PixelGold** [comment]
Hey @david-allison-1, thanks for the link, though I'm confused how I would apply that to my situation.

> We currently follow Anki and move to #answer if it exists

I think we're talking about two different note types here--I'm referring to the cloze note type. In the desktop anki client, on a cloze card, anki will a) scroll down to the clozed text so that its visible and b) upon hitting show answer, remain at the same location so the revealed text is visible. In ankidroid, part A works as expected, but part B does not--it moves back to the very top of the card so that the revealed cloze-text is no longer visible.
