### ISSUE TITLE
Statistics: Review Heatmap

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6778]
Anki 2.1.28 includes a 'Calendar' in the statistics section. We should port this.

**Comment by mikehardy** [comment]
Oh interesting - that was an add-on forever, ingested I guess? I liked that one

**Comment by mikehardy** [comment]
I need to get #6462 done then...

**Comment by david-allison-1** [comment]
Likely best to wait until we port the stats from Rust

**Comment by mikehardy** [comment]
Just got a reviewer on google play store saying a streak mode (which I think calendar / heatmap would effectively cover) would be motivating. So there is user interest, FWIW.

**Comment by david-allison-1** [comment]
There's massive user interest in this, but it'll be a little later (V2/V3) in the rust conversion - we'll get the HTML for free, but Anki/AnkiMobile get the data from a server on localhost. This may or may not be possible via Android

**Comment by david-allison-1** [comment]
Stats is done using svelte/TypeScript for the UI: https://github.com/ankitects/anki/tree/2.1.33/ts/src/stats

This calls a python wrapper over the rust backend, we're able to perform a similar function in the Java.

So, we should get this for free after the rust conversion if we include and compile the svelte libs.

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens

**Comment by Myzel394** [comment]
@mikehardy any news?

**Comment by david-allison** [comment]
It's out in 2.16 if you enable the new backend, or 2.17alpha2 as a default

**Comment by dotarjun** [comment]
> It's out in 2.16 if you enable the new backend, or 2.17alpha2 as a default

But how do I add it? 

It's not here
https://github.com/ankidroid/Anki-Android/wiki/Third-Party-Apps

**Comment by david-allison** [comment]
There's a heatmap in Statistics in 2.18
