### ISSUE TITLE
Factorizing scheduler

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6819]
This explain the goal of https://github.com/ankidroid/Anki-Android/pull/6780 and the lot of related smaller PR. The goal is also to answer David remark, which in https://github.com/ankidroid/Anki-Android/pull/6792#issuecomment-668981491 and https://github.com/ankidroid/Anki-Android/pull/6785#pullrequestreview-461352831 lead to a duplicated discussion. This risks to be really multiplied a lot because I split this PR in a lot of smaller and simpler to understand PRs which will all lead to the same discussion.

One thing which I hate when working with scheduler, is that if I am looking for the definition, I go to AbstractSched instead of going to anything useful. I need to access methods often to debug any scheduler related bug such as https://github.com/ankidroid/Anki-Android/issues/6768#issuecomment-669079499 so this is a real loss of time. Especially if I want to investigate without knowing whether it's sched V1 or V2, it's really helpful to know what is the difference (if any) between both schedulers.

When two methods are almost identical except for a small difference, it's clearly far easier to just see the difference than to see the whole methods and needing to guess why they are two methods.
There are two ways to deal with those small differences. Either the method takes this difference as a parameter and use this parameter. Or this difference is delegated to an abstract function. I prefer the second case, I find it cleaner, so that's how I did my implementations.

**Comment by Arthur-Milchior** [comment]
To answer https://github.com/ankidroid/Anki-Android/pull/6780#issuecomment-669336547 by @mikehardy 

Upstream does not have "AbstractSched". When I created this class, in Python, there was no inheritance at all between schedulers. Since Python is not typed, that's not actually a problem, as long as they have methods with same name and arguments, it works. In Java, we needed to have a parent class for typing.

Then upstream changed Sched so that it inherits from SchedV2, which allowed to remove code which is literaly duplicate. I mostly copied those change in AnkiDroid. But we still have a class AbstractSched which does not exists upstream.

If we want to copy upstream, we could delete AbstractSched and simply uses SchedV2 everywhere, understanding that Sched inherits SchedV2 so when the type states "SchedV2" it actually means "Sched or SchedV2". I find it ugly. Instead, having methods in Abstract Sched all methods which are upstream in SchedV2 and are used as in in Sched seems to me to make a lot of sens. It just means that we are splitting schedv2 in two, with one part containing functions that are also in sched.py (AbstractSched), and one part which contains the code specific to SchedV2. It would not make anything more complex to debug, to port from upstream, because the methods will still be the literal python->java translation of methods. So I do believe that the PR https://github.com/ankidroid/Anki-Android/pull/6780 can be accepted without creating any problem with upstream.

Furthermore, this PR factorize getters and setters. Those does not even exists upstream, because python does not have anything private. I do not expect that it makes any sens to have code duplication in getter, and this is not related to question about upstream at all.

On the other hand, all other PR change the methods and factorize them in a way in which they are not factorized upstream. I may create PR upstream to factorize and see how they goes. I still believe that it makes current debugging more complex, but I understand your point and following upstream would justify to reject all factorizing PR except https://github.com/ankidroid/Anki-Android/pull/6780

**Comment by mikehardy** [comment]
AbstractSched, SchedV2, Sched, they are just names, I don't find names ugly or not in this case. If upstream scheduler will live on, and AbstractSched doesn't exist, then using SchedV2 as "the main implementation" (instead of AbstractSched) seems to make a lot of sense to me, strictly on the criteria that it follows upstream. Then refactors can (and should) proceed on that basis assuming they track upstream as well.

**Comment by Arthur-Milchior** [comment]
It's not the name that I find ugly. It's the idea that each people who is going to read our code and does not know the specificity will believe that "SchedV2 sched" is a variable representing the version 2 of the scheduler why it may actually be sched V1. It is going to make ne sens for anyone not knowing our codebase well. The only reason this problem would exists is that we have type indication. This is not a problem upstream because python does not force up to give type indication. In this case, removing AbstractSched would be extremely misleading because of java type system. I believe that, given java type system, it is justified here not to follow upstream because it solves a problem that does not exists upstream

**Comment by mikehardy** [comment]
counterpoint: no one (and I mean really no one) that does not know the codebase well or is not willing to read a comment on the top of Sched.java and SchedV2.java explaining their hierarchy should come anywhere near the scheduler. It's the farthest thing from a toy ever. So I don't put weight on that argument

*I* don't even touch the scheduler :-)

Tracking upstream is a real benefit though, because the few times I have touched it, I was staring at the python code side by side, each time and it was important I could do so

**Comment by Arthur-Milchior** [comment]
Concerning the willingness to read comment, I entirely agree with you.
Concerning the need to know the codebase well, I wish to disagree.
Scheduler is complex nowadays, that's a sad truth. Does not need that it needs to be. I tired to explain what scheduler is in https://github.com/Arthur-Milchior/anki/blob/commented/documentation/scheduler.md (I would prefer it to be in anki codebase, but I'm not the one to decide this)

The rules to decide the next interval are complex. This is not a problem of code, it's a problem of modeling human reasoning. The current rules are far from optimal, and optimizing is a problem that is independant from ankidroid. However, the rules for computing the numbers of cards in each deck have no reason to be complex. The rules to compute the number of cards to review in current deck has no reason to be complex. I mean, it's simply: apply the limit of current deck and of parents, and sum the cards of current deck and its children. (And do it recursively to have the correct number of cards for each child). Creating the tree of deck is not complex, a deck A::B is a child of deck A, that is all there is to know. (Actually, I believe constructing the tree has nothing to do in the scheduler, but that's another question.)
If you want to make changes as simple as : load the deck tree without numbers so that the main screen display some content faster, you really really don't need to understand the scheduler, you just need to understand where the tree is computed and where the numbers are computed.

I would agree that, in order to pre-compute next card and save a fraction of seconds between two cards display, you need to have a good understanding of the scheduler queueing system, and how it interacts with undo, sibling burying, etc... Those are changes that require time to do properly (and unit test...). I am not expecting that this means the whole scheduler should be complex; instead, I believe it means that it should be simplified as much as possible so that it does not become confusing.

If we keep schedv2.py split between SchedV2.java and AbstractSched.java you can still look at code side by side. We'll need to add a comment on top of AbstractSched to state that the code comes from schedv2.py. I understand that it means you do not want any change to the function from upstream. I am not as convinced that it means that we can't have a very clear separation between methods that are overriden (and so that are really specific to V2) and methods that are not overriden (and so that are use in both schedulers)

**Comment by dae** [comment]
Re: https://github.com/ankidroid/Anki-Android/pull/6780#issuecomment-669336547, the daily cutoff code and deck tree code are already in Rust, and more of the scheduler is expected to follow once the current release has settled down a bit, so it's probably not the best time to be making changes to match the current Python implementation if AnkiDroid plans to use the Rust code in the near future.

**Comment by Arthur-Milchior** [comment]
I am not sure how "near" this future is. If I was sure we would have it in a month, I would not deal with the scheduler. But the rust project is probably going to take some time, and I'm still having a visible delay when I try to get a card to review, so I'm still going to try to go through with the improvements I made to pre-fetch the next card/get the first card as soon as possible. I don't actually need scheduler factorized, I just would have expected it to make things simpler.

I will then delete `AbstractSched` and simply uses SchedV2 as type everywhere, similar to current upstream; so that at least, android studio show me a definition (and I'll systematically write a comment to warn when the method is overriden in V1)

**Comment by mikehardy** [comment]
@Arthur-Milchior that sounds like it tracks current python a bit more which I like and results in less change here which I also like. When thinking of time scales like "1 month" there is likely around 2 months worth of backlog in the PR queue here already, so 2 months or longer is likely a reasonable expectation to get new refactoring type code in here. That may not feel reasonable but it's based on our objective throughput, if that helps you focus your effort on things likely to merge here based on time available

**Comment by Arthur-Milchior** [comment]
I was making a reference to PR I made in April, not any new PR

**Comment by david-allison-1** [comment]
(all of this is prefixed with "in my opinion", take it with as many smileys as possible to show good faith)

I think our velocity on the scheduler is too fast right now (namely the refactorings).

We should avoid doing work on the scheduler unless we can prove some tangible benefit. 

If we're going to be doing refactoring, we have to question who the audience of the refactoring is going to be, and how it's going to affect them. We're unlikely to get new contributors who are going to jump into looking at the scheduler, the core contributors will be using the python as a reference so we should be aiming for:

* Results of the scheduler being identical to Anki Desktop
* Rough parity with the upstream code whenever possible (to allow people to compare the implementations)
* Clearly marked and commented deviations from the scheduler, primarily for Android platform/performance reasons
* Heavy regression testing

>  I believe it means that it should be simplified as much as possible so that it does not become confusing.

I'll disagree here - unless upstream's going to go through the same simplification, then being able to compare the code to the Python is important (within reason).

From a selfish point of view, every move we make that takes us further away from `sched(v2).py` makes the code harder for me to review, reason about, and change. That's the opposite effect of what a refactor should do.

----

My ideal for changes would be:

Define the work up-front, and have a quick "is this worth it" discussion (as we're doing here - but a lot shorter). Each change that we introduce brings risks, and this is the one aspect of the software that is hard to get right, and catastrophic if we get wrong. We can reduce this risk with testing, but it'll always be nonzero.

If we have some long-term goals: (off the top of my head: 100% match of functionality with upstream, continued performance, allowing pluggable scheduler implementations, especially the rust implementation), then we should question whether each of our changes is bringing us closer, or further away from the goals.

----

In closing:

I'm worried that our changes have already introduced a change of /something/ into the sched of 2.12.X, and that these additional changes (both the refactorings and the performance changes) could obscure the cause of that. If we're going to take on the risk of bugs, fixing or adding tooling to diagnose an issue should take place before moving the codebase forward.

I think we understand the scheduler as it is now - I feel that some of the refactorings are reducing clarity in favour of reducing repetition, I don't think this is the right move to be making at the current time, especially as we're constrained for what we can do architecturally in order to keep in line with upstream.

I /really/ want to see the performance improvements once we're stable - if I were writing goals for AnkiDroid, one of them would be to allow the user to smash the spacebar as fast as humanly possible without any visible latency - and the pending performance refactorings get us much closer to that goal. It'll make me really happy to see them in.

----

Action items:

> One thing which I hate when working with scheduler, is that if I am looking for the definition, I go to AbstractSched instead of going to anything useful. 

Isn't this a tooling issue? Are you using "Go to Declaration/Usages" rather than "Go to Implementation"?

If we were voting, my vote would be to:

* Leave the sched classes as they are in terms of refactorings
* Get to the bottom of why some of our users feel the scheduler has changed recently
* (Optional) Discuss how we get the remainder of the ported python tests into a workable state
* Push through the performance changes and the count changes - that's where users are going to see the beneift

After that, I'd hope the refactorings wouldn't be necessary, as we wouldn't have a reason to look at the scheduler code for quite a while.
