### ISSUE TITLE
Collection not opening

### ISSUE THREAD

**Issue by toffiexoxo** [ankidroid/Anki-Android#6885]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info

AnkiDroid Version = 2.12.1

Android Version = 8.1.0

ACRA UUID = be10c482-7711-41d6-a7b0-5ff62c3b9424

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @toffiexoxo,

There's no reports under that ID. Did you enable crash reporting in the settings?

First of all, could you use options -> Check Database and see if that fixes the problem.

If not, could you provide us with your collection.anki2 file. This contains all your Anki data except media. 

You can provide this to a developer via email privately if you have sensitive data in your Anki collection. I won't be available to debug until next week due to computer issues.

If you don't have sensitive data, you can zip the file and upload it to this issue.

All the best,

David
