### ISSUE TITLE
Adding new cards while reviewing does not update counters

### ISSUE THREAD

**Issue by tobia** [ankidroid/Anki-Android#6887]
###### Reproduction Steps

1. Open a deck that is below the new card limit
2. While reviewing, add a new card
3. Keep reviewing

###### Expected Result

The new card counter (blue) should be increased as soon as the new card is added.

###### Actual Result

The new card counter is not increased and will eventually become negative.

###### Debug info

AnkiDroid Version = 2.12.1

Android Version = 10

ACRA UUID = 89032829-485f-4afd-a966-61ad635fd68c

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
hi

Thanks for the bug report.
Do you know whether it's a new bug ? Whether it did occur with previous version of ankidroid ?

**Comment by tobia** [comment]
I don't know, I just noticed it

**Comment by Arthur-Milchior** [comment]
Thanks.

I actually didn't know we could add a cad from the reviewer. Can you please let me know how you do it ? I can't easily find this feature

**Comment by david-allison-1** [comment]
@Arthur-Milchior Settings - Reviewer - App Bar Buttons - Add Card

Or, Rviewer -> edit a note -> Menu -> Add/Clone Note

**Comment by Arthur-Milchior** [comment]
I can't reproduce. I can't get the counter negative. The new card is not taken into account and is not shown, which is a problem by itself, but I can't figure out how to see the new cards while getting anegative number.

Do you use subdeck (decks with :: in their name) ?

**Comment by Arthur-Milchior** [comment]
Reproduction step:

* Create decks "foo::A" and "foo::B".
* Add one card to foo::A and one to foo::B
* Open the deck foo. Add two cards to foo::B
* Review three cards. You'll then get the number -1 for new card

This works on 2.11.1 and 2.9.7. I thus assume that, this time, I'm not the one guily of this bug. It's not defer Reset or anything like that. Just that we should call deferReset each time a card is added

**Comment by Arthur-Milchior** [comment]
On a related note: if you edit a note and it generate new cards, those new cards are not taken into account in counts. 

I really believe that when the editor is closed, reset should be called in background. I don't expect any trouble here and

**Comment by david-allison-1** [comment]
@Arthur-Milchior I believe we used to perform `reset` on that case. Would be best to add it back in (ideally with a test, and a quick comment explaining why).

**Comment by Arthur-Milchior** [comment]
If we removed it, I would prefer to figure out why before adding it back. Otherwise we risk adding back a corrected bug. Do you know whether reset was called in the reviewer or in the editor ?

I should note that "reset" is long, so we probably didn't do it each time a card is flushed or created, otherwise it would be quite slow.
I went back to 2.8 and I still don't see any reset in NoteEditor nor in Reviewer related to note edition.


FYI @tobia you can unfollow this bug report. I don't expect to have more question for you, it seems we found out the cause behind it. Unless you're curious to follow the discussion of course

**Comment by tobia** [comment]
I didn't use sub-decks (I don't even know what they are) and I should have written "note" instead of "card" in my description above.

I was reviewing and I just used the reviewer menu, Add note, then I kept reviewing and I noticed the number getting to -1.

**Comment by Arthur-Milchior** [comment]
@tobia  the last card you see are the cards you added today ? The blue number is limited by the actual number of cards,  not by the daily limit in the deck option?

**Comment by tobia** [comment]
Yes, that was the main condition for reproducing this bug:

> 1. Open a deck that is ***below the new card limit***

**Comment by Arthur-Milchior** [comment]
Oops my bad. Sorry.

**Comment by Arthur-Milchior** [comment]
> I didn't use sub-decks (I don't even know what they are)

That is why I gave the explanation: decks with "::" in their name.

> I was reviewing and I just used the reviewer menu, Add note, then I kept reviewing and I noticed the number getting to -1.

I was able to reproduce as follow

1. create an empty deck without burying new sibling
1. add a note N with two cards NF and NB
1. open the deck
1. Add one two note N2 and N3
1. review

You'll get negative numbers

What occurs is that when the deck is selected the counter is 2 and queue contains NF and NB. When NF is reviewed, its sibling NB is removed from the queue for same day spacing. When a note is added, the counter does not change. When a new card si fetched, the queue is filled with NB, and cards from N2 and N3, but counter remains 1. Then getCard returns NB, a card from N2, a card from N3. There was no problem for fillNew with the fact that the filling lead to more card than the counter. Indeed, the limit used is recomputed for the current subdeck instead of using global limit.

Furthermore fillNew check whether a number is 0, not wether it is positive. So ounce the counter is 81, it will believe that there is some cards to review, so it will fetch them. Which should not have been a problem if the counter was correct

My fix correct this bug too since resetting corrects everything
