### ISSUE TITLE
Support for LocalStorage for persistent storage

### ISSUE THREAD

**Issue by phu54321** [ankidroid/Anki-Android#6971]
Hello, I'm an Anki addon developer. This issue is related to implementation of [Remaining Time](https://ankiweb.net/shared/info/1508357010) addon.

Here we need to persist some data (user's review process) during review session, however AnkiDroid doesn't allow localstorage api. Unexpectedly AnkiDroid supports cookies (!!), so I'm now using that for persistent data storage. [code](https://github.com/trgkanki/remaining_time/blob/692778feb73bc2208c34e61d617ea1e5096dde95/jssrc/utils/ankiLocalStorage.ts#L9) Aside from this seemingly absurd, cookies have 4kb size limit and requires specific [apis](https://github.com/js-cookie/js-cookie) to manipulate. You can try with plain JS, but pain will follow...

###### Reproduction step

```js
localStorage.setItem('key', 'value)
```

###### Expected Result

No error

###### Actual Result

localStorage not supported

###### Solution

Put this code somewhere among [here](https://github.com/ankidroid/Anki-Android/blob/ab5472d710bf106aa70301b1cad9194d599ebe72/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1560)
```
webview.getSettings().setDomStorageEnabled(true);
```

I could make this a PR if this change seems feasible by the devs.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
  > you should put a link to the *user forum* here. All I know is r/anki.
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there @phu54321 - I would welcome a PR to implement it - I can't think of a reason why we couldn't have that enabled though once we see the PR I can read up on the related APIs to make sure it's okay

Also, have you looked at our new https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API?

As an add-on developer I want to say that our general thinking is that we have an API now, and we have versioning and developer contact and compatibility support checking for API users built in. Our next steps should be to allow users to have "javascript API add-ons" that are applied to each card (instead of included in a card template).

For "javascript API add-ons" to work well we need:

- to store them somewhere that syncs (I think files that go in media with a `_` prefix are safe? I believe custom fonts use this?)
- to allow users to see the installed add-ons and manage them (create, replace, delete) (maybe possible by having a common prefix for them like `_js_addon_<Add-On-Name>`?)
- any add-ons included on each card view

If you're interested in any of that, we'd be very interested in PRs that move it forward. We're very close to having something amazing here I think

**Comment by phu54321** [comment]
> Also, have you looked at our new https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API?

Haven't known it was in active development. I'm definitely very interested in it.

> Our next steps should be to allow users to have "javascript API add-ons" that are applied to each card (instead of included in a card template).

May I ask you why the code should be inside each card? What kind of example addons are you thinking of? My current implementation of AnkiDroid-compatible addons injects custom <script src=~~> tags to each note type template. It's much space-wise better I think? 

> to store them somewhere that syncs (I think files that go in media with a _ prefix are safe? I believe custom fonts use this?)

Yes this is safe. Anki apparently doesn't support folder structure inside media folder, so that might be a problem.

> to allow users to see the installed add-ons and manage them (create, replace, delete) (maybe possible by having a common prefix for them like _js_addon_<Add-On-Name>?)

This is something to be also discussed with [dae](https://github.com/ankitects) I think?

**Comment by mikehardy** [comment]
To be honest, we are still at the "what is even useful?" stage, as an idea. So you raise interesting questions (and of course I'd love @dae input if he's interested - I *think* this could be really cool and easy to do cross platform - that would be the hope anyway - assuming we arrive at something useful to users.

Your specific question - why code in each card? Our "most useful" use case at the moment is peeling off all the niche ideas for reviewer UI and saying "okay everyone, we have a default review UI, if you don't like it, here are some replacement options...". The main implementer of the Javascript UI was doing so in order to have a full featured, full-screen replacement review UI experience. So that would be on every card. Other ideas would be gamification (play sounds, progress bars, micro-rewards etc). Scheduler/interval modification (that would need to be hooked each time as well I think?). Things like that.

But perhaps different classes of add-on would only apply in different places. And there could be "stats" (which uses a WebView in AnkiDroid, so could work), "reviewer", and...whatever is useful and can be implemented with simple easy-to-maintain API integration boundaries so it doesn't take the codebase in a bunch of directions

**Comment by infinyte7** [comment]
I have implemented this using following example. Don't know it is good implementation or not, but tried it.

Benefits, it will help in updating without touching deck, just update js. 

**But, sync is not uploading js files.**

This simple implementation of progress bar addon.

Just this script tag can be added to any card template using
```javascript
<script src="_js_addon_progress_bar.js"></script>
```

And saving this js file to ```collection.media``` folder.
https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/JS%20addon/_js_addon_progress_bar.js

, will give following results.

<img src="https://user-images.githubusercontent.com/12841290/91357270-967a3900-e80e-11ea-90b0-49dc5b382d22.gif" height="520"/>

**Comment by phu54321** [comment]
If in doubt, I'd like an agile/TDDway. (I know it's kind of fragile)

To know what API would be helpful, I think you should make your own addons. Not an example-level one, but a real one you maintain for some time.

**Comment by mikehardy** [comment]
Ah cool - thanks for stopping by @infinyte7 - @phu54321, Mani is the driving force behind the JS API so far, adding in all the general features we asked for (semantic versioning on APIs, developer contacts etc)

interesting that it is not syncing, if I understand correctly - I may not - if you run media check after just "adding" something in the collection, then it will be ingested in the media collection properly and sync. Easy to test anyway?

There is a separate effort to add an API for adding media - necessary because we are about to lose the 'WRITE_STORAGE' permission from the Android platform so we need to encapsulate the current collection directory / disallow media additions by just copying, and give developers a way to programmatically add media - it might offer clues? #6641

**Comment by infinyte7** [comment]
Thanks, Check Media solved the sync error. 

That feature is really useful.

**Comment by mikehardy** [comment]
I'd like this to stay open a little bit
