### ISSUE TITLE
Docs: mention Opus support

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#7035]
The [FAQ entry about media](https://github.com/ankidroid/Anki-Android/wiki/FAQ#but-still-ankidroid-does-not-play-my-media) doesn't list Opus.  Opus codec in `.opus` files works on AnkiDroid and desktop Anki.  Unfortunately I can't test the iOS app.

(Presumably Opus codec in an Ogg container works fine as well, but I didn't test this.)

**Comment by tbm** [comment]
I forgot to mention that I confirmed Opus working in AnkiDroid on Android 9 and 10.

**Comment by mikehardy** [comment]
In general we support any format android supports, but it does vary by API, we support down to Android 4.1 and I'm not sure Opus existed then. However - the most important thing to note is that the FAQ is a wiki page. If you can find a list of formats that Android's built in media player supports (ideally with the Android version the support began) please edit away! I'm going to close this because it is self-doable - no barriers to entry for the FAQ, just the general responsibility to do your best for your fellow users of course
