### ISSUE TITLE
Allow reviewing a card from browser

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#7048]
I am trying to learn to recognize musical intervals. I am using both Anki and another separate program for that, but each time I make a mistake in that separate program, I create an Anki note for this specific mistake. Sometimes, when I make a mistake in the external program, I discover that the corresponding note in Anki had been already created. I need to "Review" that specific card and mark it as "failed", so Anki would know that I made a mistake. I would like to be able to do it quickly and easily, without closing the browser. 

If I provide a good quality patch for this feature, will it be merged?

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Hello,

Thanks for offering to create a patch yourself. 
Do you know whether there is a way, without add-on, to do this feature in Anki Desktop ? I can't find a way to review a card in advance from the browser. The closest thing I see would be to review in advance in a deck.
The usual rules for AnkiDroid is to stay close to desktop version, so I doubt it would be accepted as long as we keep this rule.

Could you please state what you would expect the scheduler to do in this case ? Because the method `answerCard` usually assumes that the card is already due when it is reviewed. It deals correctly with cards seen late, but it seems it does not deal correctly with interval when a card is reviewed in advance.

Depending on how you create/find the card in ankidroid, you may also want to consider using our API. It may be simpler to write your program which directly does this change without needing to change ankidroid codebase. 

Do you have more informations written somewhere about your method for training to recognize interval. I am really interested in it and have never been able to train myself, and I am really sad about it. I swear than, even on a simple task such as "is this a major third or a minor third" I get the answer wrong more than 50% of the time. Even when I try to take this fact into account and answer the reverse of what I believe, I still get more than 50% of the answer wrong, which should not even be logically possible !

**Comment by Andrej-Adamenko** [comment]
Hi Arthur,
  I do not yet know how to implement it, I am new to Anki. I used Supermemo for many years, and Supermemo always had this feature and I thought, since Anki uses Supermemo algorithm, it should be possible.  If is is possible only via a temporary deck, I would create one automatically in the program, if I needed to, and then do a review and delete it automatically.

I use ["Perfect Ear"](https://play.google.com/store/apps/details?id=com.evilduck.musiciankit&hl=en
) Android app in combination with AnkiDroid to learn the intervals. I have some progress, but am still doing "compare intervals" exercises, I have not yet started identification exercises. When I fail a task, i make a screenshot of Perfect Ear and capture the sound of the intervals and create a note in AnkiDroid with the sound in Front and with the screenshot in the back.

@Arthur-Milchior, do you know when I can expect the answer about merging?

**Comment by mikehardy** [comment]
Browse for the card in card browser and "reset progress" may do the trick nicely?

**Comment by Arthur-Milchior** [comment]
I honestly can't state whether it would be the case. This would not take previous interval, easiness... into account. This is different than pressing 1 during a real review.
Not clear to me what is the ideal action for the scheduler here

**Comment by Andrej-Adamenko** [comment]
@mikehardy I agree with @Arthur-Milchior , "reset progress" is not the same. When I do "review" and mark it as failed, the scheduler would remember how many times I failed that specific card (lapses count) and then later, on the next review in Anki, even if answered it correctly, it would increase the interval slower for a card with many lapses. "Reset progress" would remove all that information and start anew.

**Comment by mikehardy** [comment]
Then it falls on "does upstream do it?" - if upstream has a way to do it, we can follow their lead here. If upstream does not do it, then it needs to be added there first, otherwise reset progress is the only avenue to easily pinpoint a specific card alter it's next scheduled appearance I think

**Comment by Andrej-Adamenko** [comment]
Anki desktop for Windows does not allow to review a card directly from the browser. Does it mean the answer about a merge is a "no"?

**Comment by mikehardy** [comment]
That's correct, this would not merge. It is not a platform-specific feature where the mobile form factor forces us to do something different than Desktop to be reasonable. It's a generic feature - lobby for it in Desktop and we will copy if/when they implement

**Comment by Andrej-Adamenko** [comment]
Thanks for clarification. I will.

**Comment by Andrej-Adamenko** [comment]
I created a simular request for Anki Desktop: https://forums.ankiweb.net/t/allow-reviewing-a-card-from-browser/3235

**Comment by Andrej-Adamenko** [comment]
There was a reply about implementing it in the desktop version:

> dae
> 19h
> 
> I don’t have any objections to the concept, but it’s difficult to cleanly implement with the current code. I’m currently in the process of updating the scheduling code, and I’ll keep this in mind as I work through it. In the mean time, you can approximate a fail by resetting the card in the Cards menu.

**Comment by mikehardy** [comment]
Haha - same general workaround advice. I'm going to close this as an upstream thing but we can/will follow if/when that happens. Worth noting that as part of the rework of code that Damien is doing, it is mostly being ported to Rust, and we are actually going to be able to reuse that same Rust code here internally, so future scheduler features from upstream will be easier for us to adopt
