### ISSUE TITLE
2.13 - Answer Button animations are not disabled by "Safe Display"

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7114]
This drains the battery on eInk devices

https://github.com/ankidroid/Anki-Android/commit/d5348330f9e1bff5db473a2db30d8d92a117d285 went in.

Needs further investigation

**Comment by david-allison-1** [comment]
Cause: ripple tag - https://github.com/ankidroid/Anki-Android/blob/d250542d593222f4476bb55daa86b44a64f85dc7/AnkiDroid/src/main/res/drawable-v21/footer_button_again.xml#L2

**Comment by david-allison-1** [comment]
@dotancohen

Ripple animations don't display if I disable animations in the developer settings on Android. 

Could you let us know whether this is a problem that we need to take action on, or if your Nook already has animations disabled by default?

Thanks

**Comment by dotancohen** [comment]
@david-allison-1 In the developer options on this device, the only options related to animations seem to be "Window animation scale" which is set to "animation off", and "Transition animation scale" which is set to "animation off". So I assume that there is no global "disable animations" option, as the Ankidroid spinner is animated when syncing. For reference, it is running an extremely stripped down Android 4.4.2, kernel 3.0.35. I do have Ankidroid's "Safe display mode" option set.

I don't have a way to test current battery drain, nor do I even have a batter status indicator in regular use on this device! So I'll get back to you after using 2.13.0 for some time to see if I perceive a faster-than-normal battery drain. I apologize that there is no objective test to check this.

Thank you!

**Comment by david-allison-1** [comment]
>  So I assume that there is no global "disable animations" option, as the Ankidroid spinner is animated when syncing. 

Understood. I'm hoping all is good if you're not seeing the ripple effect in 2.13.0

**Comment by dotancohen** [comment]
Here is a video of clicking two cards with Ankidroid 2.13.0 on the Nook:
https://i.imgur.com/dr9dkxx.mp4

It can be seen that there is just a touch of animation happening before the e-ink screen refreshes. I'll use it much today to try to determine how badly it affects the battery.

**Comment by david-allison-1** [comment]
@dotancohen Is this better in 2.13.1, or do we still have work to do?

**Comment by dotancohen** [comment]
I really can't tell if there is much difference in battery drain, though that doesn't mean there isn't.

2.13.1 feels much snappier when answer cards than did 2.13.0. I'm actually surprised that the difference is so obviously felt. Maybe there's a bit of placebo effect! ))

I now realize that there was an animation when opening the menu. I never noticed it, because on the Nook nothing can be really animated, but on 2.13.1 I see that the menu opens much snappier. Thank you! The only animations that I still see are the active scrolling when scrolling the deck list, which I do often enough that it is annoying, and the sync spinner, which I do infrequently enough that it is not a real issue.

If at all possible, when animations are disabled, a swipe up or down on the deck list should probably move the list a proportionate amount without actually showing the scrolling animation.

Thank you very much!

**Comment by david-allison-1** [comment]
Sync spinner is disabled on my device when I have no animations, scrolling will be interesting to handle, but I'll add it to the backlog.

I'll close this as the underlying problem (new animations) is solve. Please watch/follow #7163 for follow-ups for the other animation removals

**Comment by dotancohen** [comment]
Terrific, thank you! Ankidroid is getting better by the minute.
