### ISSUE TITLE
Play audio outside of review? 

### ISSUE THREAD

**Issue by sourstripe** [ankidroid/Anki-Android#7355]
Suggestion for possible feature :
This might be too much and out of the scope of Ankidroid, but is it possible to play audio files outside of reviews? Audio files from cards due for review or that you recently reviewed? Kind of like condensed audio for listening practice?

**Comment by mikehardy** [comment]
Hi there! This is out of scope but I'd support a PR to the AnkiDroid API to fetch audio files for a card (similar to, but the reverse of #6641 where we added audio). Then you could use the AnkiDroid API to fetch cards do (or search for cards or however you want to access the cards but you'd have a list of cards) and you could use the API again to get the files for them and do what you like with any audio files returned

It is not a desktop feature though so would be to be API type access like I describe

I'm going to close this since the only way it will happen is with the contribution of a PR from someone interested, but I will be clear I am not closing with malice or anything - I'd love to merge a PR that added an API for media file fetching for a card or list of cards.
