### ISSUE TITLE
Error message - Card Content Error: Failed to load 'googleapis.css'

### ISSUE THREAD

**Issue by somnus7** [ankidroid/Anki-Android#7356]
###### Reproduction Steps
1. Open the problematic deck

###### Expected Result
No error messages.

###### Actual Result
The error message - Card Content Error: Failed to load 'googleapis.css' will be shown up for the first several cards. After this, it will not pop up again. However, if we close the app and reopen it. It will happen again.

###### Debug info
AnkiDroid Version = 2.13.4
Android Version = 10
ACRA UUID = 18faa7d7-70bc-4c21-9539-cb02afe6c3c8
Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @somnus7 

This error has been happening on your card for some time. The error message was added recently.

This is a problem with your card template. Please see https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

You can fix this either by having yourself or the deck author:

* Remove the reference to `googleapis.css`
* Download `googleapis.css` and move it to `collection.media`

You can do this yourself by:

* Editing a card which displays this message
* Clicking "Cards" at the bottom of the screen
* Backing up the data to a file
* Removing the reference to the file which no longer exists in either the CSS, or the front/back template.

----

In all likelihood, the problem is that the file should have been named `_googleapis.css`.

If a file is without the leading underscore, then it will be seen as unused by "Check Media". 

Thanks for using AnkiDroid,

David

**Comment by somnus7** [comment]
Understood. Thanks for your detailed explanation.

Actually, the first thing I had done was to look up the card template and locate the reference to this CSS file. However, I am failed to do so. - -!

I think it would be fine for me to add a dummy 'googleapis.css' file under my media folder to get rid of this error message. Just want to make sure that this is not a bug. ^_^
