### ISSUE TITLE
Travis: Migrate to travis-ci.com

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7454]
travis-ci.org will apparently be [decommissioned on December 31](https://travis-ci.community/t/org-to-com-migration-deadline/10260) 

And they're [moving infrastructure](https://travis-ci.community/t/builds-hang-in-queued-state/10250/6) to travis-ci.com, which appears to have started heavily impacting builds.

https://www.traviscistatus.com/#month

**Comment by mikehardy** [comment]
Oh interesting - this has been on my mind for a while but did not realize there was a deadline nor have the doc link needed, now I do: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by mikehardy** [comment]
1- I have installed the Github App for Travis CI in the GitHub organization: https://github.com/organizations/ankidroid/settings/installations/12564680
2- I have asked to join "beta" for the open source builds on travis-ci.com (why is it beta?? it's been 2 years since the announced public orgs on travis-ci.com but ok) https://travis-ci.com/organizations/ankidroid/migrate
3- they sent me the email that said we were approved
4- I started the migration https://travis-ci.com/organizations/ankidroid/migrate
5- we appear to have status for the repos on travis-ci.com now https://travis-ci.com/github/ankidroid

We should start seeing new builds go to travis-ci.com - once verified I'll post about it in discord

**Comment by mikehardy** [comment]
everything seems good to go, resolving - thanks @david-allison-1 for the heads-up
