### ISSUE TITLE
Sync dialog always displays 0 bytes downloaded

### ISSUE THREAD

**Issue by gaul** [ankidroid/Anki-Android#7465]
###### Reproduction Steps

1. Press synchronization icon
2. Look at dialog
3. Sync succeeds but reports 0 bytes downloaded

###### Expected Result

Sync reports a non-zero number when downloading changes like new decks.

###### Actual Result

Sync reports zero bytes.

###### Debug info

AnkiDroid Version = 2.13.5

Android Version = 11

ACRA UUID = 7711c2bd-3fb4-46ef-9f9d-28911d96e09c

Scheduler = std

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Screenshot

![Screenshot_20201024-145042](https://user-images.githubusercontent.com/848247/97069131-f15ebf80-1608-11eb-9da5-3658ed222673.png)

**Comment by senorsmile** [comment]
This same thing has been happening to me for several versions now.

**Comment by mikehardy** [comment]
Yes! This has been happening for quite a while, it was an artifact of a successful (in that it works...) forward port to a new way to handle network connections but that messed up the download tracking (my fault)

It hasn't been a priority to fix since it is actually downloading things, just not tallying them, but it is definitely an issue

If anyone wants to take it on, it is something about this PR https://github.com/ankidroid/Anki-Android/pull/5658

...and the CountingFileRequestBody object there *does* count correctly when media is fetched, it's the database chunks that aren't tallied - that's my hypothesis - just not sure why

**Comment by mikehardy** [comment]
I think I finally fixed this :laughing: - will be in next 2.15alpha

**Comment by david-allison-1** [comment]
![](https://media.giphy.com/media/KEVNWkmWm6dm8/giphy.gif)
