### ISSUE TITLE
Font error: Failed to load '_NotoSansJP-Regular.otf'

### ISSUE THREAD

**Issue by leopard20** [ankidroid/Anki-Android#7479]
I keep getting this error when I want to see my deck:
> Card Content Error: Failed to load '_NotoSansJP-Regular.otf'

I'm not sure if this happened because I updated AnkiDroid or because I updated my ROM. (kinda did both at the same time, and my AnkiDroid was very old at the time, like v2.10 or something). It was fine before.

The notes don't specify any particular font, only something like:
```
<font color='#000000'>Text</font>
```
So I'm not sure why I get that error.

The displayed text looks okay though.

Using AnkiDroid v2.13.5

P.S: Not sure if this matters, but I don't have that font in my system fonts folder (just wanted to let you know in case AnkiDroid is forcing it)

**Comment by mikehardy** [comment]
Hi there! This is a warning we put in for missing media recently, historically it is the root cause of a great deal of our support requests. In the process it has flagged a few people that had missing media but just never knew it. In this case, it means just what it says: you have card template referencing media (a font file in this case) but AnkiDroid can't actually find that font file anywhere.

If you install the font correctly or update your template(s) so they no longer reference the missing media, this warning will go away

https://docs.ankidroid.org/manual.html#customFonts

**Comment by leopard20** [comment]
Ah I see. Thanks for letting me know

**Comment by leopard20** [comment]
@mikehardy According to that post:
> Only fonts in the ttf format are officially supported in Anki/AnkiDroid

How am I supposed to fix this?

**Comment by mikehardy** [comment]
that's up to you, OTF fonts might work fine, works is different than "official support"
in general this is user generated content (your card template) referencing a non-existent file. You could simply stop referencing the font in your template, since the file isn't there anyway, and that would also "fix" it

**Comment by leopard20** [comment]
ok. I tested it as it was and it seems to work.

**Comment by mikehardy** [comment]
great to hear! happy reviewing

**Comment by leopard20** [comment]
@mikehardy Sorry for pinging you again!

When I select "default font applicability", and I select a default font (Open Sans Regular), I don't see the error anymore.
But when I select "System Default", the error appears again.
Isn't this a bug? I mean it should always use whatever font it uses as default despite the error right? (because like I said the text looks fine anyway)
Basically I was hoping I could use the old font again by hiding the message because both NotoSansJP-Regular and OpenSans-Regular fonts look too thin for me and I don't like them.

**Comment by mikehardy** [comment]
Edit your card templates to remove the reference

**Comment by leopard20** [comment]
So I can't just hide the message right?
