### ISSUE TITLE
AnkiDroid not showing hint

### ISSUE THREAD

**Issue by excaptor** [ankidroid/Anki-Android#7503]
Hint prompt is not shown where template has it.

###### Reproduction Steps

Front template:

```
<div class=big>{{Entry}}</div><br>
{{#Hint}}<div class=left>{{Meaning}}</div>
{{/Hint}}
```

The note has non-empty Meaning. It is shown on the back as expected, as part of the answer. Back template:

```
<a href="kanjistudy://word?id={{ID}}"><div class=big>{{furigana:EntryFurigana}}</div></a><br>
<div class=left>{{Meaning}}</div>
```

###### Expected Result

Show hint prompt should appear under the {{Entry}} value. On tap it should show {{Meaning}} value.

###### Actual Result

It only shows the {{Entry}}, but not offering to show hint
<img src="https://user-images.githubusercontent.com/8013202/97096830-75737000-1626-11eb-9814-1301d6196473.png" width="250pt">

###### Debug info
AnkiDroid Version = 2.13.5

Android Version = 11

ACRA UUID = 87f63879-f42d-4077-9980-83e7d553cbcc

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by excaptor** [comment]
Oops, template tags aren't escaped. I can do better
Front:
```
<div class=big>{{Entry}}</div><br>
{{#Hint}}<div class=left>{{Meaning}}</div>
{{/Hint}}
```

Back:
```
<a href="kanjistudy://word?id={{ID}}"><div class=big>{{furigana:EntryFurigana}}</div></a><br>
<div class=left>{{Meaning}}</div>
```

**Comment by sudomain** [comment]
As an example, the `{{#Hint}} show this {{/Hint}}` syntax will show the text "show this" if the Hint field is not empty. In your case:

`{{#Hint}}<div class=left>{{Meaning}}</div>
{{/Hint}}`

Means to show the content of the field named "Meaning" wrapped in a div if the "Hint" field is not empty. In order to show the actual value of the hint field (and not use it as a conditional), you'll need to use `{{Hint}}`

> On tap it should show {{Meaning}} value.

There are various ways to do this, my favorite is a [details element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)

<details>It works like this</details>

**Comment by excaptor** [comment]
Thank you @sudomain for explanation. I should've been more attentive when skimming through docs looking for functions needed.
