### ISSUE TITLE
[FEATURE REQUEST] Let user know which side is more recent when synchronizing

### ISSUE THREAD

**Issue by tpondant** [ankidroid/Anki-Android#7510]
###### Reproduction Steps

1. Make changes to a deck on anki computer
2. Open AnkiDroid and synchronize.

Or 

Vice-versa, make changes first on AnkiDroid and sync on your desktop.

###### Expected Result
Sometimes, I don't know on which of my devices I made the last changes to a deck.
It would be useful to be told, when synchronizing and when Anki asks you if you want to download or upload changes, which of the cloud or the device on which you're trying to synchronize, has the most up to date changes. I'm thinking of a timestamp, like, the cloud was updated last time at this hour, your device was updated/synchronized at that time. That way, I could avoid losing changes if I choose the wrong option. It already happened to me once because I didn't know which of the options between download or upload would bring me the latest changes . Generally, I just want the device that I am synchronizing to always download the changes.

###### Actual Result

Not showing a timestamp of download or upload.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, to the best of my knowledge, AnkiWeb does not provide us with this information.

I feel this will lead to more confusion - a sync conflict is when the two collections are out-of-sync, either due to explicit user action, data corruption, or due to trying to sync two different collections. 

You can review 100 cards on your phone, then 1 on your desktop. The Desktop would show as the 'latest' and this would cause data loss.

Regardless, feature requests for AnkiWeb can be added: https://forums.ankiweb.net/
