### ISSUE TITLE
Translation with Glosbe.com not working

### ISSUE THREAD

**Issue by StillerHarpo** [ankidroid/Anki-Android#7595]
###### Reproduction Steps

1. Press add button
2. Type in a word
3. Select add
4. Press media button
5. Select advanced editor
6. Press translation button
7. Select Glosbe.com
8. Press translate button

###### Expected Result
Translates the word

###### Actual Result
Gives back error "Getting translation failed"

###### Debug info
AnkiDroid Version = 2.13.5

Android Version = 10

ACRA UUID = 4940c10c-177d-41da-83dd-c49c6b469afe

Scheduler = std

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! We actually scrape the glosbe.com HTML under the covers which makes this feature really fragile. Last time it broke it was some update to their site that we did not handle yet, I *imagine* (could be wrong) this is a similar problem, but I'm mainly replying that if it is possible for you to use a different workflow, I'd move personally - glosbe.com won't be reliable ever since they don't have a real API for us unfortunately

**Comment by david-allison-1** [comment]
@StillerHarpo 

We use the globse API, but it seems to be returning a 429 Error for me, is this the same for you?

https://glosbe.com/gapi/

**Comment by StillerHarpo** [comment]
Yes

On November 13, 2020 6:34:48 AM GMT+01:00, David Allison <notifications@github.com> wrote:
>@StillerHarpo 
>
>We use the globse API, but it seems to be returning a 429 Error for me,
>is this the same for you?
>
>https://glosbe.com/gapi/ 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ankidroid/Anki-Android/issues/7595#issuecomment-726531769

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TarekkMA** [comment]
@david-allison-1 should this be reopened?

**Comment by TarekkMA** [comment]
I think the api has changed, I did monitor the website network requests and I got this URL
```
URL: https://translator-api.glosbe.com/translateByLangWithScore?sourceLang=en&targetLang=ar
Body (json content type): test
```
Response
```json
{
    "translation": "الاختبار",
    "scores": [
        -0.513063
    ]
}
```

**Comment by david-allison-1** [comment]
Ah, page has changed since I last looked. I don't think this feature is well-used, but it's open to fixing

**Comment by lukstbit** [comment]
Note that the Glosbe API is no longer available, as stated [in their documentation](https://v2.glosbe.com/help/api).

At the moment we have one other translation service `ColorDict`(this isn't available on Chromebooks so there we have no translation service working). We should decide what to do with this feature:

1. Find another service to replace Glosbe. I don't think there's a good(free, available) solution out there.
2. Remove the Glosbe option for translation and improve the UI for translation(like disabling the button to translate on Chromebooks where there's no service available).
3. Check analytics data and see if this feature is actually used, and if it is not really used we could scrap it completely.

**Comment by mikehardy** [comment]
This feature is one of our most lightly used features, and is an interesting workflow (that is: I can see how it is useful) but is not really supportable. I think we should drop the feature and encourage people to alter their workflow to have a translation app (or website) of their choosing installed if they need it.

This is actually the value of analytics - I'm really glad I integrated it so long ago as it allows me to confidently make seemingly-harsh decisions.

We instrumented the translation events a long time ago in order to answer this question and now we have the answer.

In an entire month, this was the usage (note: contains only data from users that opt-in, current ratio is 65,000 / 2,200,000 for 33x expansion, and only a 10% sample of those users at any time so while users all show up in the sample over a month statistically, events are only 10% recorded. So 330x events, that's 330x 35 total or ~11,800 total translation events across the entire user base

<img width="979" alt="Screen Region 2022-04-22 at 07 25 35" src="https://user-images.githubusercontent.com/782704/164714733-9776a8ef-899f-43e1-94be-d3c88983c908.png">

For comparison, 3x as many people configured the custom sync server preference (which almost no one uses) and the NoteEditor was used literally 10,000x as often

A bad user experience, unsupportable business model for the providers (they'll never offer these APIs for free, they need ad money) and low usage means remove the feature, to me

**Comment by BrayanDSO** [comment]
I only knew this feature existed because I found it on the source code while trying to remove the `Lookup dictionary`.

I don't know exactly how it worked, but I think people can just use some app like Google translate which allows to select the word and translate on the context menu without leaving the app

**Comment by mikehardy** [comment]
Yep - it's been around forever, it's not really used, and translation in general in apps is so much better now then it was
