### ISSUE TITLE
Importing.csv files

### ISSUE THREAD

**Issue by kmz123** [ankidroid/Anki-Android#7686]
Are there any plans to enable importing .CSV files into ankidroid?

**Comment by david-allison-1** [comment]
Hi @kmz123 

I did the backend a couple months back. It needs a GUI - I lost my progress due to needing to dispose of my laptop.

I'm working on other things right now, it's on our backlog, and it's open if you'd like to take it on: https://github.com/ankidroid/Anki-Android/issues/6772

All the best,

David
