### ISSUE TITLE
Include lint unit tests in CI

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7735]
Interesting - I don't think we've set them up! I just run them under my local machine.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/7707#issuecomment-731153891_

**Comment by mikehardy** [comment]
Thanks for logging this - I didn't want to gate the other PR on them because it was good and self-contained.
Where to run these though? I think it makes sense to actually run them just as part of the lintRelease personally - seems odd but it keeps the lint stuff all in one place and puts it in required one
