### ISSUE TITLE
2.14.1图片裁剪功能有问题！

### ISSUE THREAD

**Issue by z18356842086** [ankidroid/Anki-Android#7775]
图片裁剪后会恢复原状，需要再度裁剪！！！
请尽快修复此bug，考试月来了，谢谢作者。

**Comment by mikehardy** [comment]
Hi there! This should be fixed in the next alpha, building now. You may try the latest alpha here (I recommend getting the '.A' parallel version so you can just try it side-by-side to see if it works for you):  https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha8

Bug was originally logged as #7768 and fixed here #7769
