### ISSUE TITLE
Add Option: Hide Note Editor Toolbar

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7785]
Had a few users ask if the toolbar can be hidden. Feels like it's enough to warrant a feature switch in the options + analytics integration to see if it's worth keeping in the long term.

Related: #7124

**Comment by mikehardy** [comment]
Agreed - note editor "real estate" (amount of screen available to actually perform edits) is a sensitive area for people on small screens already and I can understand the real estate taken by the toolbar might be just too much for some

I mention that because a more general scrub of "screen real estate available to view and edit field contents" (with an eye towards maximizing it) is a theme

**Comment by voussoir** [comment]
Hi, I'm grateful for this change. However it seems that though the toolbar is hidden, the occupied area is still covered up by something:

![2020-12-25_214724](https://user-images.githubusercontent.com/7299570/103146324-52d00700-46fc-11eb-95f8-6a938b17d581.png)

![2020-12-25_220011](https://user-images.githubusercontent.com/7299570/103146395-6039c100-46fd-11eb-8171-7bf4df40f282.png)

Is this known?

AnkiDroid 2.14.2 on both Android 7 and Android 10. Thanks to you both!

**Comment by mikehardy** [comment]
Fascinating! This is unknown I think. I'll reopen this

**Comment by voussoir** [comment]
Thank you very much!
