### ISSUE TITLE
intermittent render issues

### ISSUE THREAD

**Issue by ezzieyguywuf** [ankidroid/Anki-Android#7830]
###### Reproduction Steps

1. Review cards
2. Sometimes a small popup says there was an error
3. 
Note: it reloads the card then everything is fine

###### Expected Result

No errors

###### Actual Result

The error says something about fonts

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.14.2

Android Version = 11

ACRA UUID = 38ffbfab-fc14-487a-bd46-735a7e419498

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Is like to help debug this,is there a way to view the logs?

**Comment by mikehardy** [comment]
Sounds like a renderer crash, usually caused by fonts being very large and exhausting WebView memory:

Looks like you are running into the work we did here where previously this would crash things completely, and now we just try to gracefully let you know something is going on but without breaking review flow (except for the message): https://github.com/ankidroid/Anki-Android/pull/5820

You might examine your card templates to see what exactly is loading that could be causing the WebView to crash? It will be a user content / card content problem in the end I think

**Comment by ezzieyguywuf** [comment]
Mike,

I can dig in to this. I can say, though, I've been using the same deck
(with the same fonts) for years and never experienced a crash.

**Comment by mikehardy** [comment]
@ezzieyguywuf the Chrome team giveth (stability over years in their WebView) and the Chrome team taketh away (with some update that breaks things - it's happened before...)
