### ISSUE TITLE
Filter Decks: Improve UX

### ISSUE THREAD

**Issue by ScottON** [ankidroid/Anki-Android#7835]
###### Reproduction Steps

1. Click search icon on main screen 
2. Type a word that is in deck(tested with multiple words, in multiple decks)
3. Click search.

Note: this was happening in previous version too. I was busy and didn't have time to report it.

###### Expected Result
Show all cards with that word.

###### Actual Result
Blank results page.

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 4404996a-5611-400a-96e4-e18736e3f0fb

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here.
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @ScottON,

Thanks for the report!

This feature filters decks based on the name, rather than by their content. If this is a translation issue, could you help us improve: https://crowdin.com/project/ankidroid and if there's any additional UX improvements that can be made, please let us know.

I've had a test of the filtering, and it works fine on my emulator, if the filtering by deck name is problematic, we'll need more details to reproduce and fix the issue. 

Please let me know either way,

David

**Comment by ScottON** [comment]
Hey David,

Thanks for the quick response

I feel silly now. I could have sworn that used to be a shortcut to the card
browser... my apologies. It works as you said.

I've only got a couple of decks so I didn't even consider that this would
be a feature people use.

It's not a translation issue. Perhaps a tad ambiguous though. "Search
decks" could be interpreted either way. You could possibly add a message
clarifying the behaviour if someone searches and there are no results
returned?

Thanks again for your help,
Scott

**Comment by david-allison-1** [comment]
Improved UX in #7529
