### ISSUE TITLE
Save Whiteboard: Plain Whiteboard is incorrectly inverted

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7836]
* Settings - Reviewing - Disable "black strokes"
* Settings - Appearance - Select Plain Theme
* Enable whiteboard, draw and save

Expected:

* Blue on white background

Actual:

* Blue on black background

Cause:

https://github.com/ankidroid/Anki-Android/blob/ada67bc3d304193eab15d42badaafe9863d340cf/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java#L500-L504

Related: #6451

**Comment by mseh1128** [comment]
It looks like the inclusion of additional pen colors might have broken other functionality or made them useless.\
\
 From what I can see, “black strokes” currently does nothing and is no longer needed as the color picker is used to choose stroke color. However, the Whiteboard foregroundColor (used as the Whiteboard canvas when saving it) is currently determined by `inverted` and `monochrome` (with `monochrome` coming from "black strokes")

https://github.com/ankidroid/Anki-Android/blob/b1def328b12c03af04887885f6264e55ce6677bc/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java#L93-L106

In the past this was probably useful since there was no way to prevent a user from choosing “night mode” and “black strokes” at the same time. Also, there were no other colors to choose from. However, the color picker makes this useless.

 Given that, I think the simplest course of action would be to:
* Remove the “Black strokes” setting from the UI 
* Remove any references to the “black strokes” preference from Reviewer/Whiteboard & `monochrome` from “Whiteboard” 
* Make foreground color solely based on `inverted` (night mode) 

Also, it might be wise to remove the black/white pen color based on the night mode toggle. For example, if we are in Night Mode, remove the “black” pen color. If nobody else is working on this, I’d be happy to.

**Comment by mikehardy** [comment]
Very interesting! What you propose sounds reasonable to me and that is fantastic that you'd be interested in doing it, but I'd like a 2nd from @david-allison-1 just since he was in there last, just to make sure

**Comment by david-allison-1** [comment]
Yeah, that's exactly the issue. Thanks for looking at this @mseh1128!

From memory, "black strokes" was designed as a method to only use low (1?) bit colors as a memory optimization.

I think the "whiteboard pen colors" PR removed all the good that this did, and nobody's complained, so we're fine to remove it.

Your suggestion sounds good to me. I'd be more than happy for you to take this on if you're comfortable with it. 

Do reach out to either of us if you need any guidance.

**Comment by mseh1128** [comment]
Ok, I definitely will. Thanks!
