### ISSUE TITLE
Next note slow to reveal

### ISSUE THREAD

**Issue by kylepl** [ankidroid/Anki-Android#7841]
###### Reproduction Steps

1. Review a note.
2. Press Hard / Good / Easy
3. * wait 2 seconds *
4. Next note shows

###### Expected Result
I'm expecting the next note to show essentially immediately, and was what I was used to for a long time.

###### Actual Result
Extra wait of 2 seconds.

Note this occurred in two decks of mine.

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 11

ACRA UUID = b72d134b-8292-4685-81ba-d96b063e6bcb

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! I suspect your card is downloading something like a heavy font from an online source.
The only way we will be able to know for sure what the problem is will be for you to share your collection (or at least a deck that reproduces the problem) by attaching it here (change the extension to .zip and github will let you attach it)
One other thought I have is that Chrome just changed to a segregated cache per website, so perhaps it's asset loading performance is affected
