### ISSUE TITLE
Padding/Margin issues (answer counts truncated) on OnePlus 7 Pro

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7854]
Had a user report that the answer counts are truncated on a OnePlus 7 Pro (possibly due to the curved screen)

As can be seen by the pictures (without phone case), there is a large amount of the left hand of the margin missing. 

I'm not sure what to do here - adding a workaround for larger padding may be the best option.

![image](https://user-images.githubusercontent.com/62114487/101770508-72521780-3ae0-11eb-8e8f-6537f974ce06.png)

![image](https://user-images.githubusercontent.com/62114487/101770595-8eee4f80-3ae0-11eb-89fe-9d33ccd2b9b3.png)

> About the screen shifting part-- No, there was another entirely different app which is used and I don't remember the name. Couple of them had this same issue because it was a curved screen. And the dev introduced something called "extra padding" for curved screen to turn on in settings

User did not post UUID for privacy 
```
AnkiDroid Version = 2.14.2
Android Version = 10
Scheduler = std
Crash Reports Enabled = true
```

**Comment by mikehardy** [comment]
interesting - the picture helps this a lot. this has something that has come up in my react-native area a bunch and the term of art is I think "insets" vs "safe area".

It's a more general problem which needs a more general solution but I think it should be possible to find one - the problem is that there are also "punchholes" (think, a camera in the top middle or on the right but the display continues around the punchhole area) as well as curved tops now etc - it used to be you could assume  a rectangular bounding box guided by max height and max width but that's not the case now, you have to find the height + width of bounding box *not* occluded by something that creates insets and then use that / mask the rest

https://developer.android.com/reference/android/view/WindowInsets#getInsets(int)
https://github.com/th3rdwave/react-native-safe-area-context

**Comment by david-allison-1** [comment]
We need to handle insets (I was considering adding an issue for it), but I think this is a separate issue (safe area). I could also be incorrect with my mental model of what an inset is.

AnkiDroid works (albeit without using the area around the cutout) when a cutout is enabled in developer tools.

I don't think this is an inset issue as display cutouts should not be attached to the side edge according to the [android guidelines](https://developer.android.com/guide/topics/display-cutout).

In the DeckPicker screenshot, all of the left side of the screen is truncated.

**Comment by david-allison-1** [comment]
Got it, probably a fullscreen issue: 

> For full screen mode on rounded corners devices, any UI elements very close to the corners may be outside of the curved corner viewable area. Imagine if a commerce app's "Purchase" button was partially obstructed? We recommend referencing Material Design guidelines by leaving 16dp side margins in layouts.

https://android-developers.googleblog.com/2017/12/tuning-your-apps-and-games-for-long.html

**Comment by mikehardy** [comment]
Interesting - perhaps I was conflating (or, likely I was conflating) but to me if the 16dp aren't useable they shouldn't be part of the safe area and that's a 16dp inset :), but I suppose I need to learn more so I can use the terms precisely!

**Comment by david-allison-1** [comment]
I'm so far in the unknown unknown territory that I can't image how lost I am

 `getInsets` seems to be API 30, which wouldn't be usable on Android 10, but I'm sure cutouts aren't that new?

**Comment by mikehardy** [comment]
it appears it just moved around ? https://github.com/th3rdwave/react-native-safe-area-context/blob/d95b5d5e8be54106baba2db5b1692e2deb3f5875/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaUtils.java#L13-L15

**Comment by david-allison-1** [comment]
In-app screenshot from user:

![Screenshot_](https://user-images.githubusercontent.com/62114487/101777423-61a69f00-3aea-11eb-8019-3dae59c20a70.jpg)
