### ISSUE TITLE
Anki fails to track LaTeX images it needs to keep if the LaTeX delimiting code only exists in the note type template code.

### ISSUE THREAD

**Issue by WraithGlade** [ankidroid/Anki-Android#7856]
###### Reproduction Steps

1. Download the following deck (an example with the problem present (as of 2020-12-10): https://ankiweb.net/shared/info/205388282
2. Find the note type in the deck that only has a Front field and no other fields. That's the type that has the problem.
3. Open that note type's template and notice that all of the LaTeX delimiters (e.g. [$]...[/$]) exist only in the template and never directly exist in any of the fields for the note type.
4. Run "Check Media" after previewing some of these notes and notice how Anki incorrectly deletes the images, thinking that they aren't needed when in fact they are needed.
5. (optional step) In contrast though, notice that if you change the note type to use both a Front and Back field and then laboriously copy paste the fields and put the LaTeX delimiters into the Front field (but not the Back field) and then remove the LaTeX delimiters from the template code then Anki starts realizing that it needs to keep the images. This essentially proves that Anki isn't detecting LaTeX code in templates correctly. It seems to only be fully aware of LaTeX code that is directly written into fields and not written into templates. This is very unexpected behavior and will make it very easy to accidentally create LaTeX Anki decks that have invalid awareness of their own LaTeX image dependencies. Also, MathJax in inadequate for fully general mathematical use.

###### Expected Result

Anki on both Desktop and Android should remember that the LaTeX images generated for this note type need to be kept in order to be displayed correctly.

###### Actual Result

Anki marks all images temporarily generated to display previews for this note type as being unreferenced and hence deletes them whenever "Check Media" is run. 

Also, when "Check Media" is run for this note type then Anki will fail to realize that Anki needs to generate images for all of these notes and will instead only ever delete them or else do nothing with them. Thus, decks that try to use this kind of technique (like the example deck above) are very fragile and easily become unusable because of this bug.

(NOTE: This problem exists on both the Desktop and the Android versions of Anki, but in somewhat different forms.)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Hello @WraithGlade.

I love this bug report. I believe this is the first bug report I ever made, when I started using ankidroid more than 3 years ago.
This seems to be a rare problem, but it brings back a lot of memory to see someone having the same trouble than the one I had.

I'm going to tell you almost what I've been told at that time: https://docs.ankiweb.net/#/math?id=example state explicitly that LaTeX tag should be used inside of field, and not in card template. So this probably won't be fixed. 

Concerning step 5, you could automate replacing the fields. E.g. adding a second field, using https://ankiweb.net/shared/info/1898445115 to copy first field in second one, using https://ankiweb.net/shared/info/291119185 to batch edit and add `[$]` before each element and `[/$]` after them.
You can also replace `[$]` by `\[` in the template, to use MathJax instead of LaTeX, it should solve most problem. MathJax symbol should work even in template

The main difference between Computer and Android version is that if an image is missing (and you installed LaTeX), then the image will be regenerated. You'll lose a fraction of second, and that's it. Android can't regenerate LaTex (even if there were a LaTeX compiler in android, I really do not wish to ever deal with plugging it in AnkiDroid)

As you correctly understood, to check whether a LaTeX image is needed or not, Anki looks at each field. We follow the computer version, so, unless you convince Anki's author to look at card content instead of field, we will continue to do the same thing as what computer do. We really don't want to encourage people putting `[$]` in template, because it would make "check media" slower. Indeed, instead of just looking at each field, we would need to generate each card and see which LaTeX appears in each of them. Might be even worse if you mix that with cloze deletion in some LaTeX by the way. 
Generating card is not really really slow, it usually takes far less than a second (that was not always the case a few years ago, that was greatly improved). But if you have got a hundred thousand cards, then even 0.05 seconds by card would mean that checking media would take more than an hour.

I should note that we could limit the card generation to cards whose template actually contains `[$]`. This would make it slow for those cards, and still fast for the other one. If @mikehardy or @david-allison-1 accept this idea, I could implement it really quickly. But that would make AnkiDroid different from computer, which we usually avoid. But I could argue that, since we can't generate LaTeX image, this would seems to be a case where the difference makes sens
