### ISSUE TITLE
Why not start from scratch as PWA?

### ISSUE THREAD

**Issue by guettli** [ankidroid/Anki-Android#7904]
Hi, I use Ankidroid since several years.

I think it would be a perfect fit for a progressive web app.

This way you could get a nice web-gui and a nice native-gui.

Why not start from scratch as PWA?

**Comment by Arthur-Milchior** [comment]
Hello,

I believe the answer is extremely simple. It would be a massive rewrite, and currently nobody wanted to take the pain and the months it would take to have feature parity. 
And even if there were no question of code writing, a web app should be hosted. Recent stats indicates 1.8 millions active user monthly. Probably more because we don't get stats from all app. This would have cost, we would need to figure out how to pay for the servers. AnkiWeb is paid by people who buy IOs, we don't even have this revenue source. 

If anybody want to try doing this, they can reuse the codebase of anki and ankidroid. They can probably get support on discord and reddit and anki forum, to try to get help if any thing in the datastructure is confusing. I sincerely wish you good luck if you want to do this. I would even be quite happy as a user if you can create something which is actually better on smartphone than ankidroid, especially if it can be used offline. 
I hope it answers your question

**Comment by guettli** [comment]
Thank you for the fast answer
