### ISSUE TITLE
Feature request: autocomplete recent searches

### ISSUE THREAD

**Issue by tobia** [ankidroid/Anki-Android#7912]
(Sorry, I submitted the form before it was ready)

I think it would be useful to have a popup suggestion list with the recent search expressions, in the browser search box.

I, for instance, have a few searches I always use to filter the lists, such as `-is:suspended -is:new` or similar, that I would like to do without having to write them every time.

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by tobia** [comment]
I mean, I thought it was a useful feature, but whatever.

**Comment by mikehardy** [comment]
Could be, but as an open source project, useful features mostly depend on the people that think they are useful (you) to implement them. "Free" doesn't include the cost of people's time to implement

**Comment by tobia** [comment]
@mikehardy Of course. I didn't mean to imply otherwise.

**Comment by legarspol** [comment]
I have been thinking a lot about autocomplete too.
That would be something I would be interested to implement if it ever reach my priority list, find some enthusiasm, is approved by project owners but for now happy to contribute in fleshing out the feature idea: 

- **Tag completion**: I would love that if I type "tag:"  it suggests the names of tag in that deck. Some deck use complex tag names and it can be annoying to have to leave the view, get back to the tag list to find the right one, go back to the search bar.
- **Command suggestion**: it would suggest things like "is:" or "-is" or "tag:"  when the cursor is after a space. Would help with typing speed and education.
- **Educational search placeholder**: At the beginning of using Anki, and still again today, I find myself looking at the documentation on how to express simple things like a negation (is it a "NOT"? is it "-"?), should I use AND or &&, OR or ||. I think having a placeholder in the searchbar that shows you exemples of what a request can look like would help with education of the users.

I understand that the original suggestion was around suggesting the whole request instead of just singular request parameter (e.g. "-is:suspended"). I think if we go by simply by recommending request parameters, we can prioritise the request parameters by last uses to achieve a similar result. It would be an approach more composable that would fit the use cases of more users. Also I think it would avoid an overlap too big with the "saved search" feature.

**Comment by david-allison** [comment]
@legarspol 

I'd prefer we looked into reviving and implementing https://github.com/ankidroid/Anki-Android/issues/12554 rather than autocomplete. 

I feel 'chips' are much more discoverable, more intuitive for 'new' users, and the UX would be much easier to do correctly, rather than trying to handle autocomplete across different types of virtual keyboards
