### ISSUE TITLE
[Feature Request] Save queries with parameter / Default filter for "Card browser" context menu searches

### ISSUE THREAD

**Issue by duydl** [ankidroid/Anki-Android#7942]
**Is your feature request related to a problem? Please describe.**
This is probably a duplication of [Issue 5234](https://github.com/ankidroid/Anki-Android/issues/5234) and would be closed soon. I just want to suggest features that would allow Anki to be used as a lookup dictionary and maybe go to investigate the solution myself. 

**Describe the solution you'd like**
There are many features being suggested in the original issue but I believe the two below would do it: 
- Adjust the 'Save search' functionality to save queries with a parameter. For example: 
`犬` --> ` deck:kanji_heisig kanji:犬` after toggling the saved query ` deck:kanji_heisig kanji:%s`. 
- Add a preference to select and apply a default filter from the saved queries to all searches by the "Card browser" context menu. 

**Describe alternatives you've considered**
At first, I was trying to make a separate application that could query from Anki database, but the above solution seems much more elegant.

**Comment by Arthur-Milchior** [comment]
Hi,

Thanks for posting this feature request.
I believe you are willing to try to implement this (with my help), and so the goal here is to discuss this to choose and agree on whether this feature request should be accepted and how the user interface should be designed before starting to work on an actual pull request.

As you know @duydl, I believe this feature would make perfect sens. I don't expect a lot of users to know it exists, but maybe quite helpful for all of those who use card browser to actually look at data.

I believe there is a problem remaining with your idea that we need to solve before this is a correct user experience. The user should be able to test their search before saving it. And `deck:kanji_heisig kanji:%s` is not something that you can directly enter in the search bar to test. The more general problem is that `deck:kanji_heisig kanji:%s` is not a valid saved search, since it is not expected to return a result without change made to it.

I see a fe options that would make sens to me:

# We use actual saved search
This mean that we can save `deck:kanji_heisig`, and when the user select `犬` in a field, and open the card browser, it will lead to `deck:kanji_heisig 犬`.  This is not what you want, but I'd expect it to be first approximation which would be simple to create, and already be an improvement. The main change in the graphical interface would be to add a menu to let the user choose a saved search. It would reuse all currently existing saved search features, it would allow to test a saved search and you'll know that when you select text, and open the card browser, the result will be a subset of the saved search.

# We used a parametrized search
In this case, I believe the interface should allow the user to enter the parametrized search, and one example of text, to check that for each text, the card browser show the expected result. This will ensure that the query is done correctly. This seems more complex, but we can work on it.  This is ideal when you want your search to be restricted to a single field, or when you want the word to appear multiple time in the query.

If we choose this path, I believe we'll need to draw quickly an example of the interface we want before starting to implement, but that should be easy. It should be similar to the current card browser, with an extra field and an extra button.

I don't think that `%s` is a good symbol to replace. If someone already know formatting in any standard language, they'll think that this is some formatting rules and that `s` mean strings. That is confusing. And furthermore, `%s` in a query already mean `any sequence of letter ending by a s`, and we don't want to forbid it. I believe that `?` is probably simpler to use. And we can state that `??` represents a single `?` in the query, so that user can still easily uses interogation mark.

# Intermediate option

We can also decide to use a saved search, and add a limited kind of restriction, such as "Restrict the selected word to be searched in the search field", or "to be searched in the field 'FOO'". So that the graphical interface is simpler, but the choices are more limited

**Comment by Arthur-Milchior** [comment]
A few extra notes, to keep track of a discussion I had with @david-allison-1 on discord.

# Saved search

Saved search is a feature which has parity on Android Desktop and ankidroid. It was introduced in AnkiDroid in 2015 in 8dc45532d54f210fd092f9051b714a134f504aa1, and the same list of saved search is shown in both app. It is saved in the collection's configuration under the key "savedFilter". So there is nothing new here.

# Context menu search

Context menu search is a feature which is exclusive to ankidroid. It is entirely unrelated to anki desktop. I believe there are add-ons on desktop doing similar task, but there is no interaction with ankidroid in any way. The question here is whether we accept to improve this feature which is exclusive to us. 

I do agree that any change we make to this, whether it used saved search or something else, should ensure saved search so that it remains compatible with anki desktop, i.e. should not put in "savedFilter" anything that anki desktop can't read. 
This means that whatever we choose here, as long as it satisfies this small criteria, would have no impact whatsoever on the desktop app

**Comment by mikehardy** [comment]
As long as we maintain ecosystem compatiblity and are only adding "new" (non Desktop) things that make sense in a mobile environment, I believe we are philosophically doing the right thing and as a maintainer it seems reasonable to say "ok" too, so, seems "okay" to me
