### ISSUE TITLE
[Bug] External page links don't work any more, and yes, I am a human

### ISSUE THREAD

**Issue by SamuelVilz** [ankidroid/Anki-Android#7944]
Hello there,

since today, AnkiDroid shows two error messages I'm not used to:

One is "External page link in card is not supported", whenever I open one of my cards in which I use embedded videos.

The other is "Detected automated test. If you are a human, contact AnkiDroid support", upon starting the app.

Screenshots are embedded down below.

Also, here's my debug info:

AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = c857ffb4-acf2-42dc-a2cc-4426f2a77ede

Scheduler = std

Crash Reports Enabled = true

Cheers and thanks a lot for your great work!
Samuel

![Screenshot_20201222-082840](https://user-images.githubusercontent.com/56087559/102861724-61829980-4430-11eb-8f41-8d4c4524f176.png)
![Screenshot_20201222-082848](https://user-images.githubusercontent.com/56087559/102861736-634c5d00-4430-11eb-8eaa-4a39107dd655.png)

**Comment by mikehardy** [comment]
Oh no! That is most unexpected. We detect "robots" using the app and restrict external page links when that happens, so these are related. Let me explain and then you may see why:

- whenever we release a new version to google play, they run automated tests on devices in the "Firebase Test Lab" which is an awesome service and helps us find errors in alphas. But the users are just robots, they click everything and sometimes leave the app by clicking external links, which means they are no longer testing the app so it is less useful
- so for robots we restrict external links to make sure they stay in the app and we get really valuable automated alpha testing

So that's the "why"

But why is your device being detected as a robot device? Here is the actual check:


https://github.com/ankidroid/Anki-Android/blob/96dd1bd16b90a074dc83458777ab6e8ea3520eae/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java#L54-L78


Why is this returning "true" in your use case ?


Then you can see where we check if you have a web browser (and thus support external links) and the first thing it does is see if you are a robot (followed by a few other checks to see if you are on a restricted learning device or have a system browser etc etc but the robot check is the problem)

https://github.com/ankidroid/Anki-Android/blob/96dd1bd16b90a074dc83458777ab6e8ea3520eae/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java#L81-L136

**Comment by SamuelVilz** [comment]
Hello Mike, thank you for your kind and fast reply!
While I'm not sure why it returned true for me (since I'm not a monkey or firebase user either, as far as I know) and how I should have found out, I'm glad to report that it works again!
Also, for everyone with the same problem: I didn't do anything that could have fixed it, I'm afraid.

Thank you very much :)
