### ISSUE TITLE
{{! is different in AnkiDroid and anki

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7960]
If you put `{{!foo}}` in a card template, anki rejects by saying 

> Found '⁨{{!foo}}⁩', but there is no field called '⁨!foo'

On other hand, in AnkiDroid, it's considered as a comment and ignored

Unless of course if there is a field "!foo", in which case it's ignored in AnkiDroid.

In my opinion, we should remove this feature. First because if someone actually want a comment in a card template, they can just use 
```html
<!-- comment -->
```
, it does not seems to be documented anywhere, and a change like this could be easy to miss and hard to understand by someone using both support.

The reason why I'm particularly interested in this is that I want to port card generation rules from 2.1.28, and I can either keep or remove this feature, but I'll need to know what I do.

**Comment by mikehardy** [comment]
Is there some `!` feature in Anki upstream that would work if we did it correctly? Just curious - I see the PR already but we can discuss compatibility here. I'm just unaware of how `!` is supposed to work at all - it does not seem to be documented I could not find anything on it in docs.ankiweb.net 🤔 

In general I trust your opinion so I would lean towards saying yes, just wanted to cross-check just in case, since I know it always makes my work better when you guys have time to cross-check me :-)

**Comment by Arthur-Milchior** [comment]
No. I tested and starting a tag with ! has no special meaning in anki currently. It just consider `{{!foo}}` to mean "the content of field '!foo'".
I've not checked whether at some point in the past it had meaning, but if it did, it was removed.

**Comment by dae** [comment]
The old template code was based on https://mustache.github.io/mustache.5.html. Anki never documented the commenting feature, and I doubt it was widely used - if it was used at all.

**Comment by mikehardy** [comment]
Thank you @dae! With that context, I'm okay with purging then
