### ISSUE TITLE
[Bug] SchedV1: Learn cards are not fully completed 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7984]
###### Reproduction Steps

**Note: This may no longer be reproducible in the future due to clock changes.**

1. Import https://drive.google.com/file/d/1-xn8E7xKcFj_Jf0vuqSaGYJvO21yPSlh/view?usp=sharing
2. Set "New Cards" to 0
3. Review 1 card

Note: This is triggered when only learn cards are available.

###### Expected Result

* A second card is shown (v2.10.4)

###### Actual Result

* Deck is completed (v2.15alpha19)

###### Debug info

Reproduced on 2.15alpha19
Works on 2.10.4

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Edit by Arthur according to Discord conversation:
Scheduler is V1

**Comment by david-allison-1** [comment]
@Arthur-Milchior 

During getCard()

* mLrnQueue.size() = 65
* mLrnQueue.isEmpty() = false
* mLrnCount = 0 ⚠️ - this doesn't seem to be causing a problem, but is wrong

After getCard() - `reset()` is called

* Sched.reset() is called
* `mLrnQueue.size() == 0`
* `mLrnCount == 90`

After answering (getCard call 2):

* mLrnQueue.size() = 1 ⚠️ 
* mLrnQueue.isEmpty() = false
* mLrnCount = 91
* _fillLrn returns true, as there is a card in the queue

* The card which we just answered is at the head of the lean queue
* Therefore `mLrnQueue.getFirstDue() < cutoff` returns false
* Therefore the next card is null
* _getLrnCard returns null

There are no other card types in the scheduler

So `getCard()` returns null, and the scheduler stops early.

**Comment by Arthur-Milchior** [comment]
I assume the states you describe appear just after you start opening the deck, not when the deck was already being used. Right?

Counts are an heuristic that's useful, but slow to compute, so I deactivated for the first card, and it is only used for the next card selection, so it's normal that `mLrnCount` is wrong at start. As it seems you noticed, its value is only used if `mHaveCounts` is set to true, and it should be false in this part of the run.
Arguably, this improvement is absolutely useless until https://github.com/ankidroid/Anki-Android/pull/7127 is merged, since the reviewer still require to know the counts before it accepts to show the question

**Comment by Arthur-Milchior** [comment]
In the deck I downloaded, I only found review and new card, no card in learning

**Comment by Arthur-Milchior** [comment]
Thanks for the report. I indeed would never have seen this myself, has I always has essentially an infinity of new card each day and never do all new cards, only all reviews
