### ISSUE TITLE
Problem Latex cloze Ankidroid

### ISSUE THREAD

**Issue by wapiti333** [ankidroid/Anki-Android#7994]
**Is your feature request related to a problem? Please describe.**
Hello, I have been using Anki for a few years and everything was working fine. 
However, for some time now, when I want to create a new "cloze" type card I am having a problem with Latex. 
When creating on Windows PC, everything works fine. But when I export and open the card on Ankidroid, the Latex code is not recognized. 
I am not having this problem with a Basic card. 
Can you explain the problem to me?

**Additional context**
![image](https://user-images.githubusercontent.com/76875900/103460427-68ee5080-4d16-11eb-8bd5-30e30551a9f5.png)
![image](https://user-images.githubusercontent.com/76875900/103460453-8f13f080-4d16-11eb-8832-6c759dc05400.png)

**Comment by Arthur-Milchior** [comment]
Salut,

Thanks for the screenshot.

When you opened the bug report, you should have received a few question, can you please answer them ? In particular, knowing your version number may be really useful.

Can you please export the card with the problem and share it to us, so that I can take a look directly. This is not a normal behavior, but seeing a card code may help reproduce it.

As an note, it was also reported on https://forums.ankiweb.net/t/latex-with-cloze/6203/6

**Comment by wapiti333** [comment]
Salut,

my version number is Version 2.1.35 

I have attached the file from which my screenshots come.
I already tried with [$] instead of $ and it didn't work any better.

Thank you in advance for your help

[fichier.zip](https://github.com/ankidroid/Anki-Android/files/5772751/fichier.zip)

**Comment by Arthur-Milchior** [comment]
I can't reproduce.
Did you use "Check media>render LaTeX" in anki on computer (I don't know the button in French, je peux chercher si nécessaire)

**Comment by wapiti333** [comment]
I just saw the "support page" and I got 
"AnkiDroid Version = 2.14.2 Android Version = 8.0.0 ACRA UUID = 7fdf0c7a-035f-4917-8279-05d8ad2f80be Scheduler = std Crash Reports Enabled = true"
I try also "Check media>render LaTeX" but it didn't produce anything...
The version of ankidroid is 2.14.2

**Comment by Arthur-Milchior** [comment]
When you do "render latex" it's not supposed to do anything visible directly. It'll generate the formulas. However, once you've synced everything (from computer to internet) and then synced on the smartphone (from internet to android), every mathematical formula should become available on your phone. 

So can you confirm you did "render LaTeX", then synced computer, then synced ankidroid, then checked a card with a mathematical formula?

I should note that usually, LaTeX is added around the actual formula, suing `[$]formula[/$]`, I don't know any case where the entire field is in `[latex]...[/latex]`, so this may be less tested than more standard usage. However, it should theoretically not have changed anything.

My thoughts for other devs (wapiti333 don't worry if it makes no sens to you): 
I could imagine that the problem may come from rewritting `\n` to `<br>` or some similar actions which would change the result of hashing the formula, which would mean that the image is not found in the media folder. However, I can't test since I was not able to reproduce.

Another possible cause would be that ankidroid believe by accident that the media is already in the media folder and so does not download it again. I don't know how to check this easily

**Comment by wapiti333** [comment]
I did what you told me: "render latex", then use [$] rather than [latex] (although it worked very well before) and finally synchronize to Ankiweb then Ankidroid. It worked !
I tested again with another package but exporting the package directly and I had to start over again (I had to click on "render latex" again)
Thank you for your help and advice !!

**Comment by Arthur-Milchior** [comment]
You're welcome.

Why do you need to "export" anything ? I assume you mean "deck" instead of "package" (I think they are translated by "paquet" in French, that may raise confusion I admit)
I'm really sorry because I realize how much more work this create for you, to rewrite the cards, and ankidroid should have worked anyway

**Comment by wapiti333** [comment]
As a math teacher, I write Anki cards for my students to review. I use Anki on the computer so I can write in latex. Until now, I write my cards, I export them and my students download them. it doesn't take a lot of my time, that's okay.

**Comment by Arthur-Milchior** [comment]
Ok, merci pour votre aide.
Ça ne sera pas "okay" pour moi, parce que je déteste laisser un bug irésolu, que ce n'est pas le comportement attendu et que je ne peux pas le coriger sans pouvoir le reproduire.
Cependant, je comprend mieux pourquoi c'est l'export et non la synchronisaton qui est concernée ici
Ceci dit, ça reste surprenant, puisque j'ai regardé et les images sont bien dans le fichier que vous avez exporté, donc ça ne semble même pas être un problème de génération
