### ISSUE TITLE
Hand Gestures on Ankidroid

### ISSUE THREAD

**Issue by i-zanis** [ankidroid/Anki-Android#8048]
Review without the use of eyes. Basic manipulation of TTS.  Currently only replay is implemented.
Add functions to allow for Pause and Resume of TSS.

Tap and Hold to pause. Release to resume.

I could not find alternatives. I had to avoid using high speed TTS. I used the speed setting so everything remains intelligible without the need to swiping for replay. I used swipe up for replay (very intuitive; the same as reload).

**Comment by Abanoub-Asaad** [comment]
I want to work on this issue.

Is the problem here when you're adding a note contains audio and trying to review it,
1. You can't stop the audio 
2. You can't resume it.

Am I right?
Is there anything else?

**Comment by i-zanis** [comment]
There is no 'issue'. This is a feature. 

Ability to pause the native TTS(Google) by pressing and holding the anywhere in the screen. 

Alternatively it could be by replaying the last 0.5 seconds instead of the whole card and resume going forward. 

This feature would be incredible for lengthy, Mathematics and Physics cards.

**Comment by mikehardy** [comment]
Interesting - I could see a general set of gestures for audio being useful, with "touch" being pause, "release touch directly" being resume, "release touch to screen start (usually left side, e.g. for LTR locale)" meaning scrub back x seconds then resume, and "release touch to screen end (usually right side, e.g. for LTR locale)" meaning scrub forward x seconds then resume. Could be configured in normal gesture area

Then if those are enabled they could be detected during review and if audio or TTS was playing it could be handled like that.

Definitely an enhancement, and @Abanoub-Asaad - for enhancements (or bug fixes to really), *any* literally *any* incremental progress towards the full feature or fix is valid as a standalone PR, just to start getting code through and enabling things. What I mean by that specifically is that maybe just adding a TTS pause/resume feature and hooking it to existing gestures is a start. Then you could configure it to to one of the existing 9-point gesture system points and already be using it

That would avoid thinking hard about how to handle webview long-press detection / collision with copy-paste. It would avoid having to handle collisions with intentional taps on links in the webview etc.

**Comment by i-zanis** [comment]
These would be all fantastic ideas but let's not forget the left/right
swipe of get wrong/right that most people use instinctively. Ankidroid
doesn't have many options for gestures.

I am not aware of what other gestures android supports without installing
something else.

**Comment by mikehardy** [comment]
It has 9 point border touch, 4 cardinal direction swipes, vol up / vol down,  and double touch :sweat_smile:

**Comment by Abanoub-Asaad** [comment]
> Interesting - I could see a general set of gestures for audio being useful, with "touch" being pause, "release touch directly" being resume, "release touch to screen start (usually left side, e.g. for LTR locale)" meaning scrub back x seconds then resume, and "release touch to screen end (usually right side, e.g. for LTR locale)" meaning scrub forward x seconds then resume. Could be configured in normal gesture area but this would be hard to get right as it collides with the WebView wanting and needing to handle long-press and taps.
> 
> Definitely an enhancement, and @Abanoub-Asaad - for enhancements (or bug fixes to really), _any_ literally _any_ incremental progress towards the full feature or fix is valid as a standalone PR, just to start getting code through and enabling things. What I mean by that specifically is that maybe just adding a TTS pause/resume feature and hooking it to existing gestures is a start. Then a user could configure it to to one of the existing 9-point gesture system points and already be using it
> 
> That would avoid thinking hard about how to handle webview long-press detection / collision with copy-paste. It would avoid having to handle collisions with intentional taps on links in the webview etc.

https://github.com/ankidroid/Anki-Android/issues/8048#issuecomment-832122166


Yes, great ideas!

But I suggest adding firstly the stop and resume buttons when I add audio to notes. 
And then handling gestures. What do you think about that?

Also, there're some acronyms that I couldn't understand, like TSS.
Does "TTS" here means "Text to Speech"?

**Comment by mikehardy** [comment]
TTS is always Text to Speech for me yes :-), sorry for throwing acronyms around, it does make things ambiguous

Yeah, just getting basic control of audio would be an incremental improvement yes. Exposing for TTS would be another increment, allowing control via gestures, an increment more...

**Comment by Abanoub-Asaad** [comment]
> TTS is always Text to Speech for me yes :-), sorry for throwing acronyms around, it does make things ambiguous
> 
> Yeah, just getting basic control of audio would be an incremental improvement yes. Exposing for TTS would be another increment, allowing control via gestures, an increment more...

Ok. 
I'll divide this issue into some issues "parts" to make it easier. But firstly, I've started with this [[issue](https://github.com/ankidroid/Anki-Android/issues/8771)].

**Comment by Abanoub-Asaad** [comment]
@mikehardy  Could you please check this [PR](https://github.com/ankidroid/Anki-Android/pull/8781) that related to Adding play/pause audio?

**Comment by Abanoub-Asaad** [comment]
@mikehardy  Could you please check this [PR](https://github.com/ankidroid/Anki-Android/pull/8781) that related to Adding play/pause audio?
