### ISSUE TITLE
[Bug] AnkiDroid tries to open zip files

### ISSUE THREAD

**Issue by ericsliu** [ankidroid/Anki-Android#8073]
###### Reproduction Steps

1. Sent myself a Nova Launcher backup file, which is just a `.zip` renamed to `.novabackup`, over Slack
2. Disabled AnkiDroid's default file associations in Android settings
3. Tried to open the file attachment I sent to myself

###### Expected Result
To be able to download the file normally.

###### Actual Result
AnkiDroid interrupts the download, giving the "this isn't a valid apkg file" error message. I am unable to continue downloading the file and needed to uninstall AnkiDroid before being able to continue.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! I think just replied to you on play store review comments, ironically (assuming it's the same person) I don't just use a OnePlus, I *also* use Nova Launcher. As mentioned in the review reply this is not something we do. Or at least not something that we drive as a default that is not changeable in any way

https://github.com/ankidroid/Anki-Android/blob/0edd4c82d6c92fe91ffbb3a8297b808548b16cb9/AnkiDroid/src/main/AndroidManifest.xml#L149 does show that we will *accept* .zip if people attempt to send them to us but Android is supposed to manage these associations based on user preferences on a per file type basis, allowing default associations, changes etc

This feels like something at the OS / launcher level to me? Perhaps it would work with the standard (non-Nova) launcher - acknowledging that we want Nova to work (I use it, it does?) but it could help isolate the problem you are having

**Comment by david-allison-1** [comment]
This is an issue - it's likely not solvable. But we can work around it.

* By default, my Android 11 has no associations for `application/zip`
* AnkiDroid adds an association. If there are no other apps, it becomes the default
* Opening AnkiDroid with a `.zip` shows an unhelpful message:

![image](https://user-images.githubusercontent.com/62114487/113328701-939b7580-9314-11eb-9622-5b6cc4b2068e.png)

We should improve this message (and possibly the dialog infrastructure for importing files) to explain that the user will need to install another app to open zip files.

https://github.com/ankidroid/Anki-Android/blob/aec219d7934473553a7e8a333f3a0716c8e5d0c7/AnkiDroid/src/main/res/values/02-strings.xml#L163

**Comment by mikehardy** [comment]
When are zip files used as an interchange format for anki files? May be that we could just remove that file association but that's of course a bit riskier, maybe they're useful

If we can't remove it, then just changing the message seems fine + easy for zips that don't appear to be anki data

**Comment by david-allison-1** [comment]
From the comment: 

https://github.com/ankidroid/Anki-Android/blob/4030ac3d4b29569ff35a35adcc251f9026c59e92/AnkiDroid/src/main/AndroidManifest.xml#L140-L151

It's very possible for `.apkg` files to match `application/zip`, so I feel the code's still necessary:

```
david@Auxiliary:/mnt/c/Users/David/Downloads$ file --mime-type WorldFlags.apkg
WorldFlags.apkg: application/zip
```

I think we might be able to get away with a naughty(?) hack: Open the app with no UI & display a toast.

**Comment by alxs** [comment]
Thanks for keeping this alive @david-allison-1!

I came here to find this issue since it's been driving me nuts for the last few months (ever since I started using AnkiDroid again). I really think AnkiDroid is doing something very wrong here since I've never experienced this sort of situation with other apps. I'll briefly describe my experience:

- When opening certain file types that aren't associated with any app, the confusing error message above is displayed.
- 99.999% of the time this wasn't a file that was meant to be opened with AnkiDroid in the first place.
- This doesn't just happen with zip files, but also with a number of other extensions, many of which leave me scratching my head as to why there was an association in the first place. For example, it just happened to me with a `.log` file.
- The way I see it, the average user is going to import decks this way a very little fraction of the time they'll be opening a zip file (not sure what other extensions AnkiDroid actually handles, but the same applies as long as they aren't Anki-specific). I think file associations should and are meant to _only_ be used for apps that can unconditionally handle a given file type. Otherwise, this sort of situation is unavoidable. I.e. while a file archiver rightly needs an association for these files, AnkiDroid should just allow users to import decks from the apps which I think is an fully reasonable thing to expect.
- More importantly, they will never actually want to open `.log` files or any other random stuff with AnkiDroid and the association for all of these is clearly a bug.

**Comment by alxs** [comment]
@krmanik @david-allison this is still an issue.

**Comment by pucgenie** [comment]
Could someone explain to me why 
<data android:mimeType="application/octet-stream" android:scheme="content"/>
is even there? This causes me headache at least once per year.

**Comment by david-allison** [comment]
Just looked into this.

`application/octet-stream` appears to still be necessary:

* Open Gmail
* attach an `apkg`
* close the draft after attachment uploaded
* View draft email
* tap attachment
* AnkiDroid is only selectable as an app if `application/octet-stream` is listed in the manifest

Intent is:
* `data` `content://com.google.android.gm.sapi/<redacted>@gmail.com/message_attachment_external/%23thread-a%<redacted>account_type=com.google&mimeType=application%2Foctet-stream&rendition=1`
* `type`: `application/octet-stream`
* `action`: `android.intent.action.VIEW`

https://stackoverflow.com/questions/14256916/open-custom-file-type-gmail-attachment-in-app

Source history

* Added in 276c320d592434f66146258b3302a4be1bac6bdf
* Modified in e5f5a2f618f94b80c4994aa655bbfd900643b1ab
* Modified in 05cdd6e6b3e539668a6950e36e8062208d8c1b55
