### ISSUE TITLE
[Bug] New "Default" deck appears on AnkiDroid (but not on desktop), and crashes the app when opened

### ISSUE THREAD

**Issue by lucainnocenti** [ankidroid/Anki-Android#8089]
###### Reproduction Steps

Everything was working fine until this morning. When I opened the desktop version I was prompted to update an add-on (I _think_ it was either "More Overview Stats 21" or "Review Heatmap", I didn't pay much attention because I didn't anticipate it being an issue). I do not know if this is what caused the issue but it's the only unusual thing that happened before I experienced the problem.

I then opened AnkiDroid, but now the deck list shows a "Default" deck that wasn't there before, and is not there in the desktop version. Opening this "Default" deck gives the error "_Collection not opened. An error occurred while accessing your collection. (...)_". I tried to do a full sync from AnkiWeb, synchronizing multiple times both desktop and AnkiDroid, and also deleting the full collection from AnkiDroid and downloading it from scratch, but the "Default" deck remains. Trying to delete it gives the error "The default deck cannot be deleted".

I also tried disabling all add-ons from the desktop version but to no avail.

I uploaded the collection as exported by AnkiDroid [here](https://www.dropbox.com/s/pre58ppgupqd9x6/collection-20210206164735.colpkg?dl=0).

###### Other details

Desktop version is 2.1.33 (3f403040), on ubuntu.
AnkiDroid Version = 2.14.3
Android Version = 6.0.1
ACRA UUID = e0119105-c9f1-4481-97ab-058990da8b19
Scheduler = std2
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
How does it work when you use a collection that hasn't potentially been corrupted by add-ons?

Note that the default deck is actually *always* there. If I recall correctly it is either deck 0 or 1, but it's hard-coded, it's the deck that always exists in a collection and is used for various internal purposes *or* you can just use it as a normal deck.

The only thing special about it (other than it always exists and has a fixed deck id number) is that if it is empty, it is typically hidden in the deck list.

Sounds like something in one of the add-ons is putting something (to be specific: something incorrect) in this default deck.

Here's the stack from the crash report (thanks for providing that info, really helps!)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.sqlite.db.SupportSQLiteDatabase com.ichi2.libanki.DB.getDatabase()' on a null object reference
at com.ichi2.libanki.sched.SchedV2.eta(SchedV2.java:11)
at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:7)
at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:11)
at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:15)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.CollectionTask$TaskListener.onProgressUpdate(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:671)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5608)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
```

**Comment by lucainnocenti** [comment]
Thank you for the prompt reply. I did try disabling all add-ons and synchronizing/checking dataset etc, but that didn't help. I guess because the corruption introduced by the add-on (assuming that's the problem) is not detected as such by the desktop program?

By trying to use a collection that was not corrupted you mean a completely different one? I actually don't have one at hand. Should I just make a new one from scratch to try it?

Also to be clear, the "Default" deck doesn't appear in Anki Desktop, so I suppose whatever is being added is processed differently between AnkiDroid and Anki Desktop.

By the way, I actually didn't know I provided the crash report info :). Out of curiosity, was it included in the exported deck I attached, or did you import that deck, reproduced the problem, and obtained the crash report?

**Comment by david-allison-1** [comment]
@lucainnocenti Thanks!

The ACRA UUID (e0119105-c9f1-4481-97ab-058990da8b19) provides crash report info.

The crash report isn't useful on its own, but we should be able to easily import the collection you provided and reproduce the crash.

Since you're around, could you also include the file located at: `AnkiDroid/collection.anki2`. There's rarely issues that occur which aren't reproducible for an import - mostly timing related.

Best,

David

**Comment by lucainnocenti** [comment]
@david-allison-1 I see, thank you for the information. I uploaded the `AnkiDroid/collection.anki2` file [here](https://www.dropbox.com/s/nm6lxonwqh2pvdj/collection.anki2?dl=0). Let me know if there's anything else you might need.

**Comment by Arthur-Milchior** [comment]
> The only thing special about it (other than it always exists and has a fixed deck id number) is that if it is empty, it is typically hidden in the deck list.

I beg your pardon, but there are other special features.
For example: if a card lost its deck, then it's moved to Default. That's I believe the main reason for the deck to reappair, cards where added in it. 
1. Create deck A and sync it between two devices
2. On a device, create a card C in deck A
3. On another device, delete A.
4. Sync both devices.
5. C won't have any existing deck anymore, and so will be moved to default.

This can be reproduced, and I believed I warned DAE about it years ago, but there is little that can be done. His answer was mostly that you are supposed to sync each time you switch device. Doing change on two device and switching has no guarantee to always work perfectly.

If you look in the browser at the default deck and move cards out of it, it should disappear.


I'd also like to add that the deck is not really hard coded to always be here. It's hard coded the same way that Basic and Cloze
 note type are hard coded, they are here at startup, but once the collection is created, they behave as any normal deck/note type (Which leads to an internationalization problem. Indeed, "default" and "Basic" are in the language in which the collection was created and not in the current language, since usually names of deck and note type are not translated). Indeed, anki(droid) forbids to delete the deck with ID 1, however, there is nothing stopping an add-on to delete it from the collection, after all add-ons have total freedom over the collection.

**Comment by lucainnocenti** [comment]
I'm not sure why, but this problem actually disappeared yesterday. The "Default" deck stopped showing up in AnkiDroid and everything went back to working as intended. I don't think I did anything in the meantime except reviewing a bunch of cards from the desktop. Did something change on AnkiDroid's part yesterday?

For what is worth, the "Default" deck that was created contained almost all of the ~200 cards that were due for review that day. Thinking about it, I also had a "filter deck" created that contained a similar amount of cards when the add-on was updated, and I then deleted that deck, and the problem might have appeared at that point. I wonder if this custom deck somehow interacted in a weird way to cause this, and then the next day the problem solved itself? I don't really know how it works under the hood so hard to say for me.

Anyway, unless you can reproduce the problem from the attached collection, I guess this issue can be closed. Let me know what you think.

**Comment by conman1395** [comment]
I'm having the same issue, and have for a while. Unfortunately I can't get it togo away. I do Anki on my laptop, desktop, iPad and Android phone and my phone is the only one with the same exact issue you're describing. I'd be happy to provide any more info.

**Comment by Arthur-Milchior** [comment]
I don't know rememorize. You may want to also report the bug here. @lucainnocenti do you use rememorize?

**Comment by conman1395** [comment]
It's my understanding that ReMemorize just modifies the interval. I go in and out of using different filtered decks that I make depending on what I'm trying to do during the day. I wonder if that's the problem since it's pulling stuff in and out of the deck? I can't imagine why else it would say [no deck] "..." with the actual deck it's supposed to go in in replacing the quotation marks. At least it's an easy fix by just going to the browser.

**Comment by lucainnocenti** [comment]
@Arthur-Milchior I do not. The only add-ons I had/have active are "Frozen Fields", "Image Occlusion Enhanced", "More Overview Stats 21" and "Review Heatmap"

**Comment by sathishkannan162** [comment]
I faced this problem too. But I was able to resolve this by force syncing from laptop to web in one direction. Then I opened ankidroid and clicked overwrite.

**Comment by chibigit** [comment]
I just had a similar problem. A default deck of 69 cards on ankidroid but no corresponding one in the desktop app. When I clicked on it, ankidroid crashed. I just did check database and by strange coincidence it picked up 69 invalid cards and put them in a recovery deck. They were all from my kanji deck. I rescheduled them and put them back into the Kanji deck. Then I did a full upload from the desktop and download to ankidroid and the default deck has gone.
