### ISSUE TITLE
Does AnkiDroid prevent normal decks from being nested under a filtered one?

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#8095]
Re: https://forums.ankiweb.net/t/error-on-clicking-options-button-of-my-deck/7335/4

Filtered decks are intended to be leaf nodes, so if a normal deck is nested under them, it will cause problems.

**Comment by Arthur-Milchior** [comment]
We do. We even have have a unit test ensuring that renaming under a filtered deck is forbidden https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java#L174
I ported last year most unit test from libanki to ankidroid, so if you test it, we probably do. But I can't find a test ensuring no deck is created under a filtered deck.

I'm pretty sure I did list ways to still get decks under filtered deck, even with anki, some time ago. Can't seem to find it exactly.
One of the way to do it require using two accounts.
On the first one you create a filtered deck A
On the second you create a deck A::B
then you sync both. It is possible that non filtered A gets renamed as A', and that A::B keeps his name  

But I'd suspect an add-on to be a more probable cause here

**Comment by Arthur-Milchior** [comment]
Never mind, I should have done things the other way around, looking on my phone first and on code later.

Indeed, we are not preventing creating subdeck of filtered deck. I've no idea what's going on, because I was pretty sure I had to deal with this at some time. I'll correct it.
check database does not deal with it and that's strange.

**Comment by Arthur-Milchior** [comment]
@dae Normally, renaming/creating deck fails when an ancestor is a filtered deck. Of course, we can't do anything for versions that are already online, as you surely know it.
Concerning failed deck, I corrected it in a simple way. If a deck A::B::C::D exists and A::B is filtered, then it becomes A::B'::C::D and so on, ensuring that the name change as little as possible without being a descendant of a filtered deck. If you have a canonical solution, please let me know. I assume it should be rare enough that it's acceptable. We'll see if we get plenty of report stating I was wrong.
This is done during deck tree check, i.e. before even displaying the deck tree, so that should be catched immediately.


@mikehardy It's a real bug, no idea for how long we had it. I don' believe it's important enough to require to be in some 2.14, since it's hard to create. I.e. a user should know how to create subdeck and do it on a filtered deck, and it's simple to correct (movig the subdeck elsewhere). Feel free to disagree.

**Comment by dae** [comment]
If the UI is preventing users from easily getting into that state, that is probably going to get us most of the way there. The restriction on nesting under a filtered deck may go away in the future, it's just not something the Python code accounted for.
