### ISSUE TITLE
Adding cards using activity manager

### ISSUE THREAD

**Issue by ElModdy** [ankidroid/Anki-Android#8125]
**Is your feature request related to a problem? Please describe.**
I would like to add cards to a specific deck from termux, for example, using `am` like for synching.

**Comment by mikehardy** [comment]
If you send the right intent it should work already

https://github.com/ankidroid/Anki-Android/blob/4e84ce3c6d4e3428124fb5853796a673569776f6/AnkiDroid/src/main/AndroidManifest.xml#L276-L302

**Comment by ElModdy** [comment]
I've searched a lot in internet and tried to figure it out but with no result.
I'm looking for something like this:
`am start -a "<something>CREATE_FLASHCARD" -deck "test" -front "front page" -back "back page"`
to run on Termux

**Comment by mikehardy** [comment]
I dunno - I think what you might be looking for is the API? Is it possible code up a quick API client based on the sample? https://github.com/ankidroid/apisample

It's just not as easy as it sounds because what if the deck selected doesn't have fields named front or back? what if the deck name has special characters? etc etc. 

If you really want to create a card programmatically, you use the API, if you are willing to just open the NoteEditor with the given text pre-populated in the first field, I think you can send an intent

**Comment by ElModdy** [comment]
The problem is the following.
I wrote a program in nodejs that generates two images for each page of a pdf file. From Termux I save those images directly in collection.media. I would like to add the cards using the am command. 
My cards are simple:

**Front**: `'<img src="123top.png">'`
**Back**: `'<img src="123down.png">'`
**Deck**: `'<deckname>'`

**Comment by mikehardy** [comment]
I believe I understood that. Your use case is not general, it makes assumptions about shape of card template in a given deck

> It's just not as easy as it sounds because what if the deck selected doesn't have fields named front or back? what if the deck name has special characters? etc etc.

I still believe what you want is small helper program using the AnkiDroid API, and the apisample provides this basically out of the box, you just need to add an Intent handler
