### ISSUE TITLE
Whiteboard: erasing / better stylus support

### ISSUE THREAD

**Issue by NicoWeio** [ankidroid/Anki-Android#8129]
I find it a little annoying that I can't use the button on my S Pen (Tab S3) to erase (stroke-wise) on Anki's whiteboard. I'm not sure how well this could be implemented using MotionEvents (which the whiteboard currently relies on), but if it's possible with a reasonable amount of code and work, I would consider it a great addition. 

Regarding MotionEvents, see e.g. [MotionEvent#TOOL_TYPE_ERASER](https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_ERASER) in the Android reference.

Currently, there is no eraser functionality implemented AFAIK. See [here](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java).

Alternatives: Currently, I rely on clicking the _erase last stroke_ button, which is a little annoying when the stylus could do it.

**Comment by mikehardy** [comment]
Very interesting - there usually is not a lot of appetite for vendor-specific additions but if there is an event type we can handle in a switch statement that's in the standard android library, this seems quite possible. The key / gesture handling system is pretty generic this days so may not be hard to extend and cover this case

**Comment by NicoWeio** [comment]
After a few hours of experimenting, this is what I came up with: https://github.com/ankidroid/Anki-Android/compare/master...NicoWeio:whiteboard-erase

I'm not 100% happy with my code, e.g. `interface WhiteboardAction` looks rather hacky, but it works fine, and I don't know how to improve it. 
Anyone who doesn't use a stylus with a button shouldn't notice any difference. 
For some reason, `event.getActionMasked()` returns undocumented numbers when using the stylus' button, which means I have no idea if this works on other devices with stylus support, because I don't own them. 

What I did:
- added handling for the new `MotionEvent`s
- made the `UndoStack` an `UndoList` so that arbitrary lines/dots can be deleted
- added logic that checks for intersections of lines/dots and eraser, to determine if something should be deleted
- made `private interface WhiteboardAction` uglier

Also, Android Studio reformatted the file (mostly added some blank lines). Let me know if I should keep it this way.
And let me know if you think I should open a PR by now.

**Comment by mikehardy** [comment]
I think you should definitely open a PR! 

I just read the diff and it looks reasonable as a set of changes - I agree that at minimum it should do no harm as it won't affect anyone not triggering those magic numbers representing the S-pen events, and also as a code maintenance issue the changes seem sane

We do have a fairly strong preference in PRs that affect functionality to not touch anything unrelated in the same commit, so I will say it is best if no formatting is done - no indents or new lines, no unrelated comment changes etc.

Not sure how strong your git commands are (mine were very weak, until very recently) but in order to remove unexpected changes I usually do a `git reset --soft HEAD~1 && git reset` in order to pop the last commit and have the files local + dirty again, then `git add -p -A` in order to only add the specific patch chunks I want to a fresh commit. But obviously do whatever works :smile:

**Comment by NicoWeio** [comment]
Alright then, thanks for your feedback! Opening a PR now…
