### ISSUE TITLE
[Bug] MIUI-specific - system dark mode / AnkiDroid dark mode interaction is wrong

### ISSUE THREAD

**Issue by NicoWeio** [ankidroid/Anki-Android#8150]
I'll go ahead and ignore the bug report template, because I think a bunch of screenshots will explain the issue best.
I use AnkiDroid _2.15alpha27_. No manual restarts were performed between the screenshots.

|  | Anki off                                                                                                                     | Anki on                                                                                                                      |
|--------------------|-------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|
| system-wide off                | ![1615154400563](https://user-images.githubusercontent.com/12870528/110256432-2dcc0000-7f99-11eb-9218-49763e5c3ef6.jpg) | ![1615154400550](https://user-images.githubusercontent.com/12870528/110256449-420ffd00-7f99-11eb-880b-f12bdfc34f61.jpg) |
| system-wide on                 | ![1615154400607](https://user-images.githubusercontent.com/12870528/110256471-5eac3500-7f99-11eb-9a4f-39f9c9d3c033.jpg) | ![1615154400574](https://user-images.githubusercontent.com/12870528/110256478-65d34300-7f99-11eb-8905-3b136775aeb6.jpg) |

As you can see, MIUI seems to _modify_ an app's look, instead of just telling it to switch to dark mode. I only noticed that because of the empty flag icon being "invisible" (black on black), despite not seeing any code that would change its color, which is white by default.

I'm not a "dark mode expert" at all, but maybe there's something we can do about it. 
I know that automatic dark mode switching is in progress (#5685), but note that having dark mode enabled both system-wide and in Anki should be a reasonable combination.

###### Research
Apparently, such bugs are a MIUI-wide problem. See [here](https://www.reddit.com/r/PocoPhones/comments/j5esk7/dark_mode_appears_to_have_a_few_glitches_on/), for example.

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mrudultora** [comment]
Turn off dark mode for AnkiDroid  by going to Display -> DarkMode -> Individual Apps. This issue had been seen in many apps on MIUI.

**Comment by NicoWeio** [comment]
Great, that worked. Though the questions remains, whether we can/should do something about it.

**Comment by mrudultora** [comment]
@NicoWeio If you don't mind this issue can be closed. Because, this issue is from MIUI side and not a bug inside this app (I guess this occurs mostly in MIUI 12).

**Comment by NicoWeio** [comment]
Okay. I'm just not sure whether this should have a place in FAQ, for example.

**Comment by mikehardy** [comment]
We actually work around a couple of MIUI specific issues. Even though they are vendor-specific MIUI has a very large market share, and this app has a large enough user base that MIUI-specific issues start to cover more people than most apps even have as users.

An example #7756 

I would like to keep this open for investigation.

**Comment by mrudultora** [comment]
@mikehardy Okay! Sorry for asking to close the issue without your consent.

**Comment by mrudultora** [comment]
@mikehardy Sir this can be resolved if we don't allow **forcedDarkMode**. Probable solution would be to set it to false on some particular view or in `styles.xml`. Would you please have a look at this [documentation link](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#force-dark).

**Comment by rajat7k** [comment]
@mrudultora I recently start using this app and  notice...that something is wrong with dark mode of this with system dark mode
but when I cross check this same issue with telegram which has same feature of in app dark mode than their is no such issue like that dark mode of app and system, work fine... so I think this is not Miui issue...because if this issue is miui issue than telegram has also unable to switch to light mode while system dark mode is On.

**Comment by mikehardy** [comment]
I don't believe any work has been done to integrate the "new" system dark mode that Android has implemented, AnkiDroid itself has had a dark mode forever, long before Android did, so they likely just do not coexist well.

I would assume that the reference documentation (https://developer.android.com/guide/topics/ui/look-and-feel/darktheme) needs to be read, and the entire app scanned for (mis-)use of Themes, in a way that gets AnkiDroid correctly extending DayNight theme - that is the correct solution I think.

Additionally there is some discussion on how to integrate selection from among our current 4 themes (black / dark / light / "plain light") with the system theme. That is covered #5685  I believe.

I think for Android APIs that support system dark mode the main "Night Mode" toggle should be removed from the navigation drawer, and we should extend DayNight theme. The settings should have a new "follow system" toggle, with our 4 themes unavailable if "follow system" is enabled, and the 4 themes available if "follow system" is disabled.

I *think* this would get rid of the MIUI issue and resolve all our dark mode issues at once.

A quick check could be made by anyone set up for AnkiDroid development work that has an MIUI phone by just crudely hacking the current theme stuff out and using DayNight theme in order to see if the issues are resolved with that theme. If so, then getting all the configurability right is the correct solution and the logical path for implementation

**Comment by mrudultora** [comment]
@mikehardy I am taking this up ;-)

**Comment by mikehardy** [comment]
Great!

please report status of the preliminary test prior to doing any settings work. We should know conclusively that if we at least just use the default DayNight theme that things work on MIUI before continuing down this path as we will still have this issue if that does not work, and solving it well may alter everything solution-wise

Also, for work that affects appearance in the app, the gold standard is to show screenshot before and after so people can look - otherwise we have to pull a branch to test (and it would depend on hardware - MIUI - we may not have)

**Comment by mrudultora** [comment]
@mikehardy I will report the progress on discord channel of AnkiDroid. I am having MIUI. I will thoroughly test it.

**Comment by mikehardy** [comment]
Please do not do that, Discord is not really searchable or persistent.
Keep all communications related to an issue on the issue, or in a related PR please

**Comment by mrudultora** [comment]
@mikehardy Okay, I will remember this in future. I think then going with draft PR will be a nice option. Is that ok?

**Comment by mikehardy** [comment]
Yes - and I will keep my fingers crossed that a simple extension of DayNight theme as proof of concept works for you (I assume you have a MIUI device to verify?)

**Comment by mrudultora** [comment]
@mikehardy Yes, I have MIUI to verify.

**Comment by mrudultora** [comment]
@mikehardy I tried extending DayNight theme, but app crashed in almost every activity I opened. In almost all the cases there was an error inflating **xmls** (It happened due to attributes in one case). What are your suggestions on this ?

**Comment by mikehardy** [comment]
Without meaning to be rude or anything, the suggestion literally is "watch adb logcat, trace the code, read all the relevant documentation to understand the problem, fix the problem"

You are blazing trail here :-), good luck? :sweat_smile:

**Comment by mikehardy** [comment]
This is a live issue

**Comment by mikehardy** [comment]
This will be fixed in the next alpha, although it won't be delivered through the play store until #9123 is merged and we can resolve #7348 as the play store is currently rejecting our binary uploads - it'll be on releases page only
