### ISSUE TITLE
[Bug] Card Browser becomes empty on toggling night mode.

### ISSUE THREAD

**Issue by ritvij14** [ankidroid/Anki-Android#8169]
###### Reproduction Steps

1. Open the Card browser.
2. Toggle Night mode (on/off).
3. Cards in the Card browser disappear.

###### Expected Result
Cards stay as they are in the card browser.

###### Actual Result
The Card browser is shown empty.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter a [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ritvij14** [comment]
@Arthur-Milchior I am working on this. I think when we toggle the Night mode, it rebuilds the complete UI tree, but doesn't load the data again. We need to reload data as well. 

Did I get that right?

**Comment by Arthur-Milchior** [comment]
Seems to make sens. I've not had time to investigate precisely, but if it works and make a sensical change, that's great!

**Comment by Akshay0701** [comment]
this issue only occur when we change app theme after selecting all decks option ,
if we select other option and then change app theme , it work fine (it shows all data),
can anybody have idea , why this happening only for all deck option ?

**Comment by mikehardy** [comment]
This is probably a special case of #3654 - the Activity not handling restarts correctly. So some state the Activity relies on is not saved correctly in the Bundle or restored correctly from the Bundle as the Activity goes through the Android Activity lifecycle

**Comment by 4D17Y4** [comment]
Is this issue being worked on ?
I can try this one if its not , in my case it happens at random time on any random deck.
Mostly while switching to dark mode and sometimes on disabling it.

**Comment by david-allison-1** [comment]
@ritvij14 , are you still working on this?

**Comment by ritvij14** [comment]
No I am not working on this. I tried figuring it out but couldn't. Please assign it to @4D17Y4

**Comment by DuguMingyue** [comment]
@Arthur-Milchior 
I 've tried to reproduce this issue and find that only the cards are small and short may cause this issue. If I add some cards with many contents in thiem then the bug cannot be triggered. I guess the issue is just affected by the speed of the thread that holds the onDestroy() method so I make onDestroy() sleep 200ms before invalidate() and the bug never appear again. (Before editing the code on Anki 2.14.6, the bug is not 100% appears each time we change the theme).

**Comment by Arthur-Milchior** [comment]
I'm sorry but I've a hard time following. The size of the cards should not matter at all here, so that's really strange. What do you call a small card?
This is especially strange because the content of the card should not be loaded at any point, even if there is a lot of media, image, video, sound, it should not matter

Did you check the two linked PR? People already started working on it.
I'd prefer something that do not add a sleep, because it's not clear that it will work everywhere
