### ISSUE TITLE
Restructure the README file and add a Code of Conduct File 

### ISSUE THREAD

**Issue by aflah02** [ankidroid/Anki-Android#8194]
Since Anki-Android is now going to reach larger audiences who will be willing to contribute it seems to be essential that the README file has additional information about the tech stack used. Link to other related repositories such as the Anki Documentation one. Also similar to other projects we need a basic code of conduct file to refer to users in case there is some scuffle. This could be a good reference - https://github.com/facebook/jest#credits
Finally a section acknowledging contributors could be a huge morale booster some what like this - https://github.com/facebook/jest#credits

**Comment by aflah02** [comment]
I can work on this and finish these tasks

**Comment by aflah02** [comment]
To adopt the following code of conduct which is used by almost all other open source projects we'll need to give an email id for people to anonymously voice their concerns.
https://www.contributor-covenant.org/version/1/4/code-of-conduct/

**Comment by Arthur-Milchior** [comment]
There is plenty of questions such as:
* do we want one
* do we need one
* which one to choose
* is it the right time to consider it

Since we suddenly have a big explosion in contributors, it may be the right time, as the risk of needing one increase. However, this one is clearly not appropriate right now. For example "A working group of community members is committed to promptly addressing any reported issues" is utterly false. We can't just write this first and create the group later. In 2020, we were 20 contributors to code. I have spoken with half of them, most are not really active in the community.  You used pandas email address, maybe pandas is big enough to have people taking time on it. Seriously, we are having trouble just dealing with GSoC candidate, which are all very nice and contributing constructively. There is no way we get enough time to find a way to create a group and process to work on those issues or to form to really understand what exists elsewhere.

**Comment by aflah02** [comment]
@Arthur-Milchior Hmm I got your point. Thanks for the feedback.
I'll now start with smaller issues first such as adding the techstack and stuff
