### ISSUE TITLE
Allow to update translation with minor version

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8224]
Currently, translations can be updated only with major version or alphas/betas. This bug will be resolved when translations can be updated more often without breaking anything. It means a new translation may wait for months for being release, which lead to a bad experience for new translators

Currently, our process to get translations is done with https://github.com/ankidroid/Anki-Android/blob/master/tools/update-localizations.py and consists in:
* sending English version to Crowding
* downloading all translated documents and replacing current document with them

So a translation commit consists in changing the translations xml file, the English one is kept unchanged. 

We can't use the new file in minor release, because otherwise, all strings that are deleted in "master" branch but still present in the minor release will be missing from the xml files. 

My suggestion would consists in merging the xml files instead of deleting them. This would ensure that all updated translations are updated, all new translations are added, and all removed translation are kept. There will be some useless string in the xml, which is not a problem at all. Ensure that all new useful strings are available more quickly, ensure that as soon as there is an update, even a minor one, translator see the result of their work, and that nothing breaks.

We should also keep the current script, because when we finally release major update, we want to delete useless strings.

Note that this will be hard to actually run, because translation with crowdin requires a private key. However, you can already create test for merging two xml documents, ensuring that in case of conflict, the downloaded version as priority. This can be tested by trying to merge the files from 2.14.6 release and from the master branch.

**Comment by ritvij14** [comment]
I would like to work on this.

**Comment by Arthur-Milchior** [comment]
If you're not already working on something else, fine by me. I won't have time to do it myself

**Comment by david-allison-1** [comment]
I'd be interested in hearing @mikehardy 's opinion on this

I don't know if translations qualify for a patch release unless they're directly fixing a bug

> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

https://semver.org/#spec-item-6

**Comment by Arthur-Milchior** [comment]
Can you please let me know why we must care about that? I don't expect it's required by Play store. It's rational consider dependencies. So the question is, what is depending on ankidroid ? Card who use the JS Api and apps that use the CardTemplateProvider api. Both of them seems to be quite independent of the translations. I could not swear that there is no way to get a resource string from any of our many API call, but normally, those are very loosely coupled and adding a new translated string should in no way breaks current API.

If you were convinced that we should care, then I'd argue that this is technically a bug fixes. It's an internal change. If we don't delete strings, it remains backward compatible. And either a string is updated (meaning it had a typo), or created (meaning it will be localized instead of English), which can be considered an incorrect behavior

**Comment by mikehardy** [comment]
I actually like this idea - I consider translation fixes to be bug fixes and I would love to be able to cherry-pick new translation downloads onto the release branch with confidence

Right now it takes a bit of thought on my part to decide when we finally have a backwards-*in*compatible translation change and then stop cherry-picking them.

I can't see how a merged file would be technically incorrect from the perspective of translations themselves (all keys needed would provably be there, when merged with existing released keys)

However: lintRelease will need a slightly new profile where it does not throw an error on unused keys anymore, and we would have to make very sure that lintRelease was working well otherwise, as the translations have been incorrect on first download every single time for weeks, requiring fixes on crowdin (typically they remove the `%s` in format strings and we have to re-add them)

So:
- I like the idea
- the current release mode lint check must be tested for the case where on main branch a key was deleted / added with a different name - so now there is an unused key in the release branch merged file from the perspective of the release branch code - it should not fail this case but should still fail the "missing `%s` in a translation" case
- the translations script should still be a single script, whether it deletes + clobbers (main branch) or merges (development branch) should be an argument to the script called `--merge-translations`, and default to off - seems most clear to future users

**Comment by david-allison-1** [comment]
Okay, sounds good. 

I think we'll need additional testing around String Arrays (maybe to the extent of blocking until #7794 is completed), I can see changes in the length causing problem there (especially adding in a new language where it'd be an "add" with a different length).

**Comment by mikehardy** [comment]
Mmm - good point, it may be that some cases are not solvable (string arrays as David mentions) but solving *most* cases at least in a first pass would allow merging translations back in almost all cases. String arrays do not change often, and the tool could just have an error that says "sorry, this type of merge is not possible / must be done by hand", while handling 98% (or similar) of the use cases

**Comment by Arthur-Milchior** [comment]
Thank you very much for this feedback. I clearly had no idea where it could fail. 
I agree that this "first pass" idea seems nice, and seeing what are the actual failing case we encounter are will help figure out what need to be done.

**Comment by david-allison-1** [comment]
Agreed - failing on string array changes seems like a sensible workaround. 

I expect our only future changes will be to get rid of them from our translatable input, and salt the earth

**Comment by Arthur-Milchior** [comment]
Answering a discord question by @ritvij14 :

You can start working on it already.
It is possible, but far from sure, that you may have a problem with arrays, as array will be harder to merge correctly than strings. In the worst case, you'll be blocked, and this is a warning that if you're block, then we can't yet tell you when it get merged.

But if you are able to do a good PR even with the array problem, that should be perfect.

**Comment by TarekkMA** [comment]
I will take a shot at this issue and #7794

**Comment by Arthur-Milchior** [comment]
@TarekkMA 
Is #8271 a blocker for this task? Or do you think you can work on it?
