### ISSUE TITLE
Implement Create New Deck Function In Add Note Activity

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8275]
## Problem
With Current Spinner in add note activity user can select any deck , but
1 if user don't found particular deck in list then user have to go back to main activity to create that deck and then user have to create note and select that particular deck , it is lengthy process.

## Solution
We can implement add new deck function at top left corner ,so that if any user don't found deck , then user can directly create new deck from there without aborting whole process to create new deck.

## Work done till now:
I will keep this section updated with work done in this issue ,so that admins don't need to read for all conversions again.

## Prototype of select deck design in add note
![Capture](https://user-images.githubusercontent.com/52353967/111763780-85873700-88c8-11eb-83c4-23af07c19760.PNG)

Note : I am not started working on this yet,i wanted to make sure that what admins thinks , whether this will be feasible for 
          user or not ?In my opinion, it will be beneficial because ,it let user to create deck directly from add note activity so that user don't need to abort all process and data from add note activity.

**Comment by Akshay0701** [comment]
and i also understand ,this is not like easy feature that i can be build overnight ,this might need a lot of discussion .

**Comment by Akshay0701** [comment]
and i also understand ,this is not like easy feature that i can be implement overnight ,this might need a lot of discussion .

**Comment by Arthur-Milchior** [comment]
Unless there is a strong reason to do both things together, I believe you should do two feature request.
The main problem with adding new deck here is that, let's say you have a deck D and you can to create the deck D::S, as subdeck of D. It would be nice to be able to select D and state that you want a subdeck of it. Best solution in my opinion would be to prefill the text field with "D::" and put cursor on right, so that user can start to type "S" or choose to delete "D::" quickly.

I like both features personally. Not really sure how the search would be done. But if the arrow on the right open a widget, similar to the tag widget, with the list of deck (similar to current list of deck which opens) and a field to search, I believe it would be really nice. furthermore, the change would be small enough that current user don't loose anything

**Comment by Akshay0701** [comment]
yes i got your point , that's really nice suggestion , actually we can implement this new create deck function in this two way 
1 if user want to create completely new deck then user just have to click icon at top right corner ,
2 if user wish to create sub-deck of deck then in that case we can implement onLongClickListener in deckAdapter ,so that user can long press on deck in which he/she wants to create sub-deck ,exactly same implementation like in deck-picker activity

**Comment by Akshay0701** [comment]
i will keep this issue as "Implement Create New Deck Function In Add Note Activity",
and i will create new feature issue for "Implement Search Deck Function In Add Note Activity"

**Comment by david-allison-1** [comment]
Note that we already have: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java which will significantly reduce the amount of work needed

<details><summary>Screenshot</summary>

![](https://user-images.githubusercontent.com/62114487/88676838-77d83380-d0e4-11ea-9f79-44e00a84c510.png)
</details>

**Comment by mikehardy** [comment]
Does Anki Desktop do anything like this? If they do not, I think we have other priorities

**Comment by david-allison-1** [comment]
Anki Desktop allows this 
![image](https://user-images.githubusercontent.com/62114487/111894453-b2d80000-8a02-11eb-96c2-fba0efdf8960.png)

**Comment by mikehardy** [comment]
Yep - then needed for ecosystem compat -> works for me :-)

**Comment by Akshay0701** [comment]
I will start work on this : )
