### ISSUE TITLE
Implement Search Deck Function In Add Note Activity

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8276]
## Problem
With Current Spinner in add note activity user can select any deck , but
->If number of decks is very big it will be hard for user to search particular deck in spinner ,

## Solution
->We can implement search option for user to find any particular deck to select in add note activity.
(the only thing i am unsure about is searching for sub-deck which is present under parent deck).

Work done till now:
I will keep this section updated with work done in this issue ,so that admins don't need to read for all conversions again.

Prototype of search deck design in add note
![Capture](https://user-images.githubusercontent.com/52353967/111763780-85873700-88c8-11eb-83c4-23af07c19760.PNG)

Note : I am not started working on this yet,i wanted to make sure that what admins thinks , whether this will be feasible for 
          user or not ?In my opinion, it will show large number list in more neat way and it will also save user time to search 
          deck.

**Comment by david-allison-1** [comment]
Note that we already have: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java which will significantly reduce the amount of work needed

<details><summary>Screenshot</summary>

![](https://user-images.githubusercontent.com/62114487/88676838-77d83380-d0e4-11ea-9f79-44e00a84c510.png)
</details>

I personally think this would be a good change, but would like to see what others think

**Comment by Akshay0701** [comment]
Thankyou so much @david-allison-1 ,This actually made things much easy for implementation of searching decks and i also personally want to take guidance from other mentors as well before starting implementation.

**Comment by mikehardy** [comment]
Having a standardized deck selection dialog (where maybe you just pass in the strings to use? but the deck selection widget is implemented once and re-used is a big plus, and I would approve that change

As an enhancement on that it would be nice to also add the ability to actually *search* in the dialog for the deck you want (in case you have 1000s of decks - some users do, and that's the problem you are actually trying to solve right?).

I would do 2 PRs, or at least separate the commits so that once change was to make the dialog re-usable, and re-use it here, second change is to add a search feature in the dialog

**Comment by Akshay0701** [comment]
okay i will make consider that in mind while making PR's.

**Comment by Akshay0701** [comment]
yes i wanted to make searching easy in large number of decks , and about two pr , i think making two pr is not need as there is searching of decks is already implemented in `DeckSelectionDialog` class , but i will make 2 different commit for this.
