### ISSUE TITLE
Review scroll lagging

### ISSUE THREAD

**Issue by KidaYuushi** [ankidroid/Anki-Android#8328]
Recently when I review my large cards and need to scroll, the "FPS" drops for some reason (Not just the scroll, everything that moves, like the options and menu also lag when I review a card)

I tried uninstalling, deleting all cards, deleting all codings (cards templates) and note types, but the error is still there, can someone help me?

**Comment by mikehardy** [comment]
Hi there! You did not include any version information or anything, but you are using AnkiDroid 2.14.5 or 2.14.6 (likely 2.14.6 and your device is running Android 8 or 8.1 right?

We had to turn off hardware render for Android 8/8.1 because of a webview bug #8154 

It was a difficult choice, but was necessary to stop total reviewer failure for affected people, at the cost of lower FPS for some. For 2.15 we will make it a preference so if you are unaffected by the WebView bug but are affected by performance you can experimentally toggle hardware rendering back on #8160 - until then if you use the 2.15alpha versions you'll get hardware rendering right now, but, your reviewer buttons might disappear

alpha test enrollment info here: https://docs.ankidroid.org/#betaTesting

Unfortunately the WebView is out of our control, we can only work around it

If I'm wrong in any of this we can reopen and triage, but I'll bet a $1 I'm correct and close it with apologies for the hassle

**Comment by mikehardy** [comment]
The latest 2.15alphas have an advanced setting that must be used to turn hardware render on for Android 8 https://github.com/ankidroid/Anki-Android/pull/8458#issuecomment-813055838
