### ISSUE TITLE
[App is getting restarted when switching between day and night mode]

### ISSUE THREAD

**Issue by prince-09** [ankidroid/Anki-Android#8351]
###### Reproduction Steps

1.  Click on the night mode button
2.  You will see splash screen again

###### Expected Result
It should not show splash screen, it should change current be on current activity.

###### Actual Result
We see splash screen again

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prince-09** [comment]
@david-allison-1 please look into it

**Comment by david-allison-1** [comment]
Thanks for the report! Do you have a proposed solution?

**Comment by Prashant830** [comment]
I want to solve this issue ,can I take this issue?

**Comment by david-allison-1** [comment]
> I want to solve this issue ,can I take this issue?

Do you have a proposed solution? This isn't likely to be an easy one to solve.

**Comment by prince-09** [comment]
@david-allison-1 I have proposed a solution and I want to solve this issue as I raised the issue.

**Comment by Prashant830** [comment]
@prince-09 Ok you solve this issue, I will look at some other issue. 😉

**Comment by david-allison-1** [comment]
> @david-allison-1 I have proposed a solution and I want to solve this issue as I raised the issue.

Sounds good to me, how do you plan to tackle this?

**Comment by Arnold2381** [comment]
Hey @david-allison-1 I want to work on this.

**Comment by Akshay0701** [comment]
**Just an Improvement (Not necessary to implement)** ->what if we handle changing of the mode in dynamic form?
### Then how we can achieve that?
Thanks to the developers of the Telegram app for making code open sourced, so we can take a look at how developers implemented this feature in the **[repository](https://github.com/DrKLO/Telegram/blob/1eea3ab6f7fa8ff5b90282a2bb0e919aabea7d35/TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java#L3142-L3181)** (lines highlighted).
There is a lot of code, so let’s get the idea of the whole algorithm.
In Android 9 we have native Dark Theme support. The issue is that it is part of configuration and Android UI Toolkit doesn’t allow to change configuration dynamically and to change theme it is needed to restart all the activities in the app. That is clearly not the solution we are looking for.
Basic support for Dark Theme with app restart is fine and is better than only providing just light theme. But to provide a really good UX it seems without custom theming we’ll not be able to achieve what we want.

The main algorithm is the following:

- we have some hidden ImageView on the screen
- on request to change theme we draw all the content of the screen on the Canvas
- convert content of Canvas into Bitmap and put it into ImageView
- change theme on all views
- start circular reveal animation for our content of the screen (from 0 radius to full size)

This will create animation when new theme reveals with animation over old theme.
Sounds hacky, though pretty working solution.

@prince-09

**Comment by mikehardy** [comment]
I would much rather all the Activities just handled Activity restart correctly by persisting state to bundle onSaveInstanceState and recreating state in onCreate, seems like it is working with the system instead of fighting it, in my experience fighting the system is painful and expensive

**Comment by Arnold2381** [comment]
https://user-images.githubusercontent.com/46752548/115993514-c1609b00-a5f0-11eb-8960-67ff94b19f9b.mp4

@mikehardy I tried some changes got this.

**Comment by mikehardy** [comment]
The video is interesting - sure - but I usually stick to text that talks specifically about how code will be organized or reviews of actual code. Can you describe the design of your changes with reference to the code or propose a draft PR?

**Comment by Arnold2381** [comment]
Sorry I missed this! Sure I will create a rough draft.
