### ISSUE TITLE
Readme.md: Update "build" to point to GitHub actions on master

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8382]
It currently points to TravisCI, which we no longer use

https://shields.io/ will provide a badge

Use `build` as the shield text

**Comment by Arnold2381** [comment]
@david-allison-1 I was just out of curiosity looking for what badges are and what this issue actually wanted and after my research, I think we cant set a badge of actions using shield. I maybe wrong but I tried forming  a link but couldn't because the parameters required do not match with Github link
![image](https://user-images.githubusercontent.com/46752548/112889619-80f62600-90f3-11eb-8e53-e4cd47137aee.png)

And please if u can go through this issue, I think they have discussed the same problem
https://github.com/badges/shields/issues/4559

**Comment by david-allison-1** [comment]
"GitHub branch checks state" should work

**Comment by Arnold2381** [comment]
@david-allison-1 
https://img.shields.io/github/checks-status/ankidroid/Anki-Android/master?color=green&label=build
Does this work?

**Comment by david-allison-1** [comment]
It does, but you need the provided URL from shields, not a permalink to a green check.

**Comment by david-allison-1** [comment]
Sample: ![GitHub branch checks state](https://img.shields.io/github/checks-status/ankidroid/Anki-Android/master?label=build)
