### ISSUE TITLE
[Minor Bug] SQL window size calculation

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8421]
https://github.com/ankidroid/Anki-Android/blob/1476aa95bd5e5b69a9b8329747b999b200b815b4/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L333-L335 will return 0 if it's hit - not what we're expecting. Theoretical bug as it hasn't hit us.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/6040#issuecomment-811613816_

**Comment by Vaibhavi1707** [comment]
Hi, I would like to work on this issue.

**Comment by Vaibhavi1707** [comment]
The expected return value, in this case, should be calculated from the default `sCursorWindowSize` as initialized on line [328](https://github.com/ankidroid/Anki-Android/blob/1476aa95bd5e5b69a9b8329747b999b200b815b4/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L328) of the same file. As in this condition since `db` is not an instance of `DatabaseChangeDecorator`. Therefore we don't have `db_name`. Hence the condition further cannot pass. In this case, if the condition mentioned in the issue were to be ignored, the `sChunk` val could be calculated from the default itself.
Am I right about the expectations? The hypothesis is based on line [354](https://github.com/ankidroid/Anki-Android/blob/1476aa95bd5e5b69a9b8329747b999b200b815b4/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L354)

**Comment by david-allison-1** [comment]
Yep - we'd be best to extract the method, so we can apply the 15/16 operation to all possible results

**Comment by Vaibhavi1707** [comment]
Okay, I'm on it!

**Comment by Vaibhavi1707** [comment]
Do I need to write a test for `loadColumn`? As that's the method accessing `getChunk()` which is private?

**Comment by david-allison-1** [comment]
I don't think there's much value, it's tested implicitly by our startup code

**Comment by Vaibhavi1707** [comment]
Okay, creating a pull request right now.
