### ISSUE TITLE
Collection not opened - No SD Card Permission

### ISSUE THREAD

**Issue by matador94** [ankidroid/Anki-Android#8554]
**DavidA EDIT**: 

> I just needed to give permission for the SD card, it's solved now. thanks! 

We can do better with our error message here

----

Collection not opened  
An error occurred while accessing your collection. It may have been caused by a harmless bug, or there may be a problem with it.

I tried check database option and it didn't help

Debug info: 

AnkiDroid Version = 2.14.6

Android Version = 9

ACRA UUID = 1b6ca65c-028c-404c-b14c-e06779599305

Scheduler = std2

Crash Reports Enabled = true

**Comment by farjadilyas** [comment]
I can reproduce it when I open the app after denying the storage permission. I think it was introduced in the April 5 commits, around 732eb1a.

This occurs due to the collection not being initialized before the```handleStartup()``` call once storage permission is granted. Collection is only initialized once getCol() is called. So this can be fixed by calling firstCollectionOpen() inside handleStartup(). We can remove the explicit firstCollectionOpen() call in DeckPicker's  onCreate(). Then, we can simply call handleStartup() once in onCreate(), and once when permission is granted.

Can I work on this?

**Comment by david-allison-1** [comment]
@matador94 

Hi, if you've also got AnkiDroid 2.15alpha open, then close it.

Otherwise, we'll need a copy of the file at `AnkiDroid/collection.anki2` to diagnose this further. There's no reports in our crash tracker

**Comment by matador94** [comment]
I just needed to give permission for the SD card, it's solved now. thanks!

**Comment by OCzarnecki** [comment]
Can I work on this?
