### ISSUE TITLE
[Bug] Installing stable version over previous alpha version deletes ALL settings

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#8573]
###### Reproduction Steps

1. uninstall alpha version
2. install stable version after that

###### Expected Result

my setting are saved and I can just continue as in the previously installed version.

###### Actual Result

ALL setting are gone. Preferences, gestures, login, everything :-( I have to set up everything again.

I'm a long time user and I'm overwhelmed of how many new features you guys added into AnkiDroid. But first of all the basic features of an Android app must be save. And that doesn't seem to be the case here. Didn't have that issue with other beta/alpha apps before 👎 

###### Debug info
 2.15alpha40 on Android 9. Now latest stable.

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hmm - that's unexpected and not the experience of previous people, however I think the root of it might be "uninstalled" - if you uninstall and you don't have your settings backed up by Google (they have some systems outside AnkiDroid / not in our control that can do preference saving) then how would your preferences be saved? They are a file in the installed app's directory so an uninstall will remove them 🤔 

There are quite a few settings that are in your deck config and those persist correctly yes?

At this point if you are just testing alphas we don't recommend uninstalling anything or getting rid of your stable version, we recommend the parallel builds from the releases page so you can work side by side without a risk of deleting settings.

To investigate this further in order to see if there is anything we can do, we will need to know every single step you took starting with "I'm running the stable version and think to myself...I'll try the alpha". Every action from that point is important to see when the settings loss may have ocurred

**Comment by Anthropos888** [comment]
Hi, I'm on alpha since 2 years or so and had to switch back to stable a few times before, when bugs occured. Can't remember exactly if all settings got deleted as well back then.

This time I did the following: after the gestures bug in the latest alpha I pressed "leave" for the beta programme in Playstore and waited maybe 10 mins. After that Playstore said "You're still on beta, you might consider uninstalling and installing again". So I pressed "uninstall" button in Playstore and 5 seconds later "install".

I didn't expect my settings to be deleted, it just felt like "I'm leaving the beta program to get the stable version". 

What other ways are there to switch to stable version from alpha/beta if it doesn't work via Playstore?

(I'm also using parallel builds, but only for testing. The alpha version was my main version cause I didn't encounter many bugs in the past years.)

**Comment by mikehardy** [comment]
Thanks for the update @Anthropos888 - and I know you've been a dedicated tester with great bug reports before. I am sorry this happened. The steps you detailed *seem* totally reasonable! I can't imagine what happened. But hopefully we can try to reproduce and fix them

**Comment by david-allison-1** [comment]
@Anthropos888 I'm glad you're still around! I'm sorry about the stability recently, and I'm sorry this happened.

I've been handing regressions to GSoC candidates; I should have taken on more myself in order to ensure that they're fixed quickly. I'll be doing this much more from now on.

I don't think there's anything that we can do about uninstalls. It's the same as a "clear data", which will wipe settings,

We might be able to add in a "backup/restore settings" in the advanced settings. I'd only personally be comfortable about this in alpha/dev releases - allowing users to manually edit settings before we've hardened the validation is a recipe for issues
