### ISSUE TITLE
Reviewer: Animate answer buttons if gestures are used

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8583]
When:
- [x] Pressing Keyboard input (regression in 2.15)
- [ ] Using gestures

The answer buttons should animate as-if they'd been touched to provide visual feedback to the user of the action that has occurred.

This is much less subtle than the 1-4 dots at the top of the screen, and helps ensure against misclicks

----

Hmm.... interesting. No regression here at all. I don't use gestures, but from the method name, I would have presumed that they would have animated the answer buttons

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8579#issuecomment-817391958_

**Comment by david-allison-1** [comment]
This was enabled for keyboard input, so is a regression ref: #5683

When we fix this, it would also be useful to apply this to the button animations, if possible

**Comment by kuroni** [comment]
Oh I think this is much worse than just gesturing; even touching does not return feedback anymore.

https://user-images.githubusercontent.com/13513478/114326650-c4915c80-9b03-11eb-9c0e-0221a7643797.mp4

**Comment by farjadilyas** [comment]
No feedback on touch can be fixed by calling ```view.setPressed(true)``` in the event.getAction() == MotionEvent.ACTION_DOWN block, and ```view.setPressed(false)``` in the ACTION_UP block in the ```onTouchListener``` for the buttons. For the gestures, however, I think we'll have to manually decide which view corresponds to the desired button, i.e. if swipe left clicks the green button, we'll have to use setPressed similarly on the corresponding layout.

**Comment by david-allison-1** [comment]
Sounds good to me, better to move forwards
