### ISSUE TITLE
Regression test for startup: new user granting permissions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8603]
It'd be great to get a regression test for this path in another PR

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8561#issuecomment-817213318_

**Comment by mk-94** [comment]
Hi i would take it. It is my first issue in ankidroid. But would be great to try to implement it. :)
Can you tell me what I need to pay special attention to and how to start?

**Comment by david-allison-1** [comment]
@mk-94 - This is going to be a somewhat involved test, and it'd be better to start with a "Good First Issue"

**Comment by mk-94** [comment]
I would try to work on. Sure, i will have some questions, if it is ok for you.

**Comment by david-allison-1** [comment]
Ok

**Comment by mk-94** [comment]
Thank you, i will start to work in it today. :)

**Comment by mk-94** [comment]
Could you please give me a short briefing, how i should start with this issue and if there is something i have to pay special attention for?

**Comment by david-allison-1** [comment]
* Make a branch
* Git reset to before https://github.com/ankidroid/Anki-Android/pull/8561#issuecomment-817213318 went in
* Build & reproduce the crash on your phone
* Make a unit test which reproduces the crash - ensure it fails
* branch from master and cherry-pick the unit test, ensure it now passes
* Submit a pull request

Useful reference functions are called: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java

These won't exist at the time before the PR was made.

You'd be best to make a new, isolated test class during testing on the old commit, then integrate it into `DeckPickerTest.java` after the cherry pick, and delete the repeated functions

**Comment by mk-94** [comment]
Okay thank you very much. :)

**Comment by mk-94** [comment]
Hi again, i have one more question, to reproduce the issue. 
At first i tried to reproduce the issue on the emulator. Before i did a hard reset on my branch before the issue #8561 (comment) was merged. I created a deck and some nodes. Then I revoked the permission for files and media for the ankidroid app, grant permissions again and the decks are there again. 
I also grant permission via the app and via android settings. 
Same behaviour on my personal smartphone.

**Comment by david-allison-1** [comment]
What does `git rev-parse HEAD` show?

**Comment by mk-94** [comment]
392e6b48dcbbb20d534e9816523cc72ff7a22cd4

**Comment by david-allison-1** [comment]
@farjadilyas I can't repro #8558 at this commit, do you have repro steps?

**Comment by farjadilyas** [comment]
@david-allison-1 The solution for #8558 was merged in #8561 so it shouldn't be reproducible. However, the repro steps are the same as mentioned in Issue #8558:

1) Clear App Data/Deny Storage Permission
2) Open the app: handleStartup() will always lead to handleStartupFailure()

**Comment by david-allison-1** [comment]
@farjadilyas We're at 392e6b4, I believe before the fix was merged.

**Comment by farjadilyas** [comment]
Oh, that's two commits before handleStartup() was introduced in 732eb1a. That introduced #8558

**Comment by farjadilyas** [comment]
@david-allison-1 Oh, that's two commits before handleStartup() was introduced in 732eb1a. That introduced #8558. Tested this by checking out to the previous commit.

**Comment by mk-94** [comment]
Yes i wanted to reproduce the error before the fix from #8561 was merged. So i have to reset before #8558?

**Comment by farjadilyas** [comment]
@mk-94 No, if you want to reproduce the Bug described in #8558, you have to reset to any commit _including/after_ 732eb1a (when the bug was introduced), and _before_ 3451cc5 (when it was fixed). When I run ```git log```, the commit right before the fix #8561 is fdeeef0dbe68c4d4b164cf4df4998373afda2b28. So you should be able to reset to that! Let me know if you can reproduce it then.

**Comment by mk-94** [comment]
Ok, I reset to fdeeef0 and try to reproduce and let you know if i can reproduce it.

**Comment by mk-94** [comment]
Ok I got it, thank you. Collection not opend...

**Comment by mk-94** [comment]
I debugged and reproduced the bug and would now start to write the test. 
Just to be sure. I'll write a test, which starts the app at first time, grant permission for storage and check if StartupFailure.DATABASE_LOCKED-Dialog will not open. Is it right?

**Comment by mk-94** [comment]
Hi, i need some more help. I work with the robolectric-testing-framework for the first time and iwant to reproduce the error #8561 not only with the emulator, but with the test. In the comments are the steps which are necessary to reproduce the error in the emulator. And i know that the method colIsOpen() in AnkyActivity.java is repsonsible for the error in the emulator because it returns always false at the initial startup of the app, 'cause of a nullpointer. But the behaviour of robolectric is quit a bit different, so colIsOpen() is true and not false what i need. So i tried to mock the return-value of colIsOpen() to falls but it doesn't work. Does somebody have a tip how i can move forward to implement this test? 

I forked the project, so here is my current status. 
https://github.com/mk-94/Anki-Android/blob/Before732eb1a/AnkiDroid/src/test/java/com/ichi2/anki/GrantPermissionTest.java

Thank you very much. :)

**Comment by oakkitten** [comment]
this is a bit off-topic but if i may ask; why does AnkiDroid needs storage permission? why not use any of the locations that don't require permissions, etc?

**Comment by mikehardy** [comment]
@oakkitten mostly because AnkiDroid started when Android was on version 2 or 3 I think and there were really no permissions. It was 2008. And storage was insanely expensive internally so everyone used little sdcards and wanted the collection stored there. Hey! Why don't we store that in `/sdcard/AnkiDroid/`? Sounds perfect right?

And here we are

https://github.com/ankidroid/Anki-Android/issues/5304
