### ISSUE TITLE
Freeze field

### ISSUE THREAD

**Issue by kyo-kyoto** [ankidroid/Anki-Android#8673]
Hi 
I want to freeze a field while making cards on ankidroid,like the add on in anki.
Thanks .

**Comment by kartikeysaran** [comment]
Great feature to include, If this issue is accepted I would love to work on this ! :)

**Comment by mikehardy** [comment]
If I understand correctly we already take into account whether a field is frozen or note and behave correctly but the ability to toggle a field as frozen or not is not exposed? I've never used the feature myself so this is just vague memory from prior pull requests

Here is the thing though: if it is from an add-on on desktop we will not support it. We support core functionality of anki desktop.

So job #1: what does anki desktop do here with no add-ons? We will attempt to do that. If that means there is nothing to do because anki desktop does not do it by itself, then this issue is closed and if you want the feature you should open a discussion with them about supporting it in core functionality

**Comment by mikehardy** [comment]
no feedback
