### ISSUE TITLE
All dekcs Synced when Longin a new account

### ISSUE THREAD

**Issue by PANG-hans** [ankidroid/Anki-Android#8677]
**Is your feature request related to a problem? Please describe.**
Sometimes the whole decks is too big to download/upload. Maybe it is better to take a choice for decks.

**Describe the solution you'd like**
After ckick `sync` button, give a list to choose which deck(s) sync to this device.

**Describe alternatives you've considered**

**Additional context**
NONE

**Comment by PANG-hans** [comment]
I think i can work on this later if considered as a feature

**Comment by mikehardy** [comment]
@PANG-hans selective sync is not supported by Anki Desktop and will not be supported here

I understand from this comment "Emmm, maybe it's a better choice. But i'm still a freshman for github and required to use git fix some issues in the course brfore tomorrow" here https://github.com/ankidroid/Anki-Android/issues/8593#issuecomment-826112464 that you feel time pressure to do something / anything but please understand that this project does not work that way.

If you had approached us earlier we may have been able to do something, but I'm not going to be able to coordinate work for you between now and your deadline tomorrow. We just had a huge group of new contributors come in for the Google Summer of Code project so most of the easy things are gone. You may find better luck in another project

**Comment by PANG-hans** [comment]
Thanks for replay, i'll find some others to do(but still in this project because it is decided by the group, sorry again for that if you see me later). 
BTW, i wonder wether the kernel fuctions in AnkiAndroid all depends on Anki Desktop(implement firstly in desktop and then Ankiandroid)?
Maybe the disk space on PC and drive(i didnnot find the ceil limit of space) is enough to store the decks and cards. It may hard to load all in the remote devices, it takes also such a huge time. Also it can not deal with the case that some devices may offline when using. Thus i put this feature here, not for just deal with the homework. 😀

**Comment by mikehardy** [comment]
AnkiDesktop is what we consider "upstream", we are a port. Anki Desktop was first, in Python (now in a mix of things including Rust), and the Python code was ported to Java here.

AnkiDroid works great offline, that's one of it's major features. Offline function is perfect, then you sync.

Syncing is done to AnkiWeb because it is a database-level differential sync (very efficient even if your collection is multiple gigabytes, just a few kilobytes will sync). Syncing to external sources is not and will not be supported, you can just use file copies for this from external programs.

You should really read the wiki pages on contributing and the development guide
