### ISSUE TITLE
[Feature Request] Hourly breakdown tab suggestion

### ISSUE THREAD

**Issue by sankayop** [ankidroid/Anki-Android#8736]
Dear Ankidroid dev,
First of all, thanks for your amazing job, the app is incredible!
This is not an issue! it's a feature request :)

I had a few idea and wanted to share them.
In the "statistics" section, tab "Hourly breakdown", what do you think of exchanging the "% correct" color and shape for the "Answers"?

Currently, in the background, there's the "% correct" in large dark grey columns, and in the foreground, the "Answers" in thin light grey columns.
Below a printscreen:
<img src="https://user-images.githubusercontent.com/23059127/116701223-f3df0f00-a9c7-11eb-84f5-059120d7a9d2.png" width=50% height=30%>

I thought it would be more apparent (IMHO) to have in the background, in large dark column, the "Answers" info ; and in the foreground, thin light column for "%correct" info.

Ok, it is a very small "insignificant" modification (might seem but not for me :) ) but if you think of it, first, you answer, then you answer correctly or not, no?

Voila,
if it does not take to much energy to implement, at least I would be greatful :) If it's more complicated than it looks like, no problem, it's just a personal suggestion.

Have a nice day,

**Comment by david-allison-1** [comment]
Hi! Thank you for the thank you!

We're going to be completely redoing the Statistics screen in AnkiDroid 2.16/2.17 to look like Anki Desktop.

Our main aim with AnkiDroid is to maintain compatibility with Anki Desktop (in this case, their legacy stats):

![image](https://user-images.githubusercontent.com/62114487/116714470-b7aead00-a9cd-11eb-8a21-6baa34b7d667.png)

For the above reasons, we're unlikely to make the change unless there's a compelling reason to (typically because something works better on Android). If you feel it needs to be made, or if you feel we don't match Anki Desktop, please let us know.

If you request a change in Anki Desktop, and it gets accepted, please let us know and we'll follow it. You can request changes on their [forums](https://forums.ankiweb.net/)

**Comment by david-allison-1** [comment]
I'll close this due to the above, please treat this conversation as still open if you want to take things further🙂

Likewise, have a great day!
