### ISSUE TITLE
[Feature] Help option in Setting Pages

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8737]
## Feature 
it'd be great to have "help" icons for the different settings, which launch a small popup as an explanation, with a larger link to the manual

## Solution 
After clicking on the help icon we should show a dialog (likely not a material dialog) with a small summary, which contains a link to the manual for further information

## Desire output 
<img src="https://user-images.githubusercontent.com/52353967/116706413-3cf48a80-a9eb-11eb-8950-4c3948202a26.png" width="400" height="600" />

**Comment by david-allison-1** [comment]
I really like this! (given that I suggested it, that's not a surprise, but the design is awesome 💝)

@Arthur-Milchior @mikehardy @infinyte7 thoughts?

I think we'll need a follow-up issue to determine **where** to place these.

It'd be great to see what the dialog looks like - I don't think a material dialog would be useful here

* Maybe: on click, add a tooltip, and turn the (?) into a (web) button, so the user sees they can press again to view the manual?

Note: my design skills are terribad. Suggest what you think is good

**Comment by david-allison-1** [comment]
> > on click, add a tooltip, and turn the (?) into a (web) button, so the user sees they can press again to view the manual?
> 
> nice idea, I have to see how we can implement this,
> my thought : instead of changing the (?) into (web) button, can we add href link in a tooltip, I am not aware if we can add a href link in a tooltip?

It's code - we can do anything! I think that will work (maybe with the web icon as a supplement), but we'll need to keep accessibility guidelines in mind - the link will likely need to be much larger than the rest of the text.

Do you think this would work?

**Comment by david-allison-1** [comment]
I forgot to mention, but I don't feel we should have the icon on "language", as the two clash.

I think it's better to keep "help" on the right, to ensure that the user won't accidentally trigger a setting

**Comment by Akshay0701** [comment]
> Do you think this would work?

now, it's making proper sense to me, but let's first see what other mentors think.

> I forgot to mention, but I don't feel we should have the icon on "language", as the two clash.


yes i will take care of that

**Comment by prateek-singh-3212** [comment]
@Akshay0701  Such an amazing design.
I would like to know everyone's opinions on this design.
![Group 9](https://user-images.githubusercontent.com/76490368/116711066-184ee180-a9f0-11eb-9f4b-a166886fd4fb.png)

**Comment by david-allison-1** [comment]
I like it more, but it breaks accessibility guidelines:

> Consider making touch targets at least 48x48dp

https://support.google.com/accessibility/android/answer/7101858?hl=en

**Comment by oakkitten** [comment]
I don't think I have seen any applications do this. I suppose there's a good reason for this; it's akin reading a book where every sentence has a footnote and you have to jump all over the page all the time. This is perhaps useful if the user is changing their preferences daily. Most users don't, though.

I think preferences are very confusing, and some preferences definitely need lengthy explanations. But most would benefit from simple rewording and shuffling around. Helper preferences, and explanatory preference screens, are common ways to add explanation to preferences. In many cases, not adding more text, but removing some, will help. See #8710

I think there should be at most one help button (or a “Learn more” kink) on every screen. A screen should only contain related preferences, so that link would take you to a piece of text can succinctly explain all of them, not as a bunch of footnotes, but a chapter of text. This should be something you only have to read *once*, if you do at all.

P.S. What exactly would you put into help text for “Show button time”?

**Comment by infinyte7** [comment]
I think it will be better to have long press and popup with text explaining settings (`content description` may be reused from `strings.xml`). It will make UI clean. But if we put button for every options then some options are self-explanatory and we may skip those. May be more better option can be implemented.

**Comment by david-allison-1** [comment]
I'm going to preface this with the fact that my previous responses revolve around using this for "Deck/Filtered Options", rather than the preferences. I was unclear.

----

> I think it will be better to have long press and popup with text explaining settings (`content description` may be reused from `strings.xml`). It will make UI clean. But if we put button for every options then some options are self-explanatory and we may skip those. May be more better option can be implemented.

Long press isn't discoverable by default: I expect we probably have a lot of users that don't know they can long-press decks, we're targeting users who are unfamiliar with Anki, and I feel the explanations need to be prominent in the UI of the deck options screen.

I don't think these are anywhere near as useful for the general preferences.

From my viewpoint/desires: "I don't understand the settings" is a prominent complaint, and in my personal experience, users commonly mess up the settings, so we should provide more guidance in this aspect.

**Comment by Akshay0701** [comment]
So let me summarise,

## problem 
"I don't understand the settings" is a prominent complaint

## solution 
Creating a "help" icon button for those option which are not self-explanatory and confusing to users, 
After clicking on the icon, a tooltip will show with a href link to Anki manual and an explanation of option usage to the user.

Correct me If I miss something.

**Comment by oakkitten** [comment]
> Correct me If I miss something.

At this point I have to wonder if I am shadowbanned here.

> I'm going to preface this with the fact that my previous responses revolve around using this for "Deck/Filtered Options"

I feel like in this case my previous comment is even more relevant. It'd be much easier to explain "Graduating interval" and "Easy interval" together, instead of duplicating information for each of these options, or deciding which one should have the bulk of information and which one has to read "See help for the other option".

**Comment by david-allison-1** [comment]
> I feel like in this case my previous comment is even more relevant. It'd be much easier to explain "Graduating interval" and "Easy interval" together, instead of duplicating information for each of these options, or deciding which one should have the bulk of information and which one has to read "See help for the other option".

Is this an argument from viability of translation (duplicated work), or from a user's perspective? We can definitely work on combining the manual, the app, and Anki Desktop if that's an issue. 

I intuit that we immediately lose a lot of user interest as soon as we mention "look at the manual": we quickly cause information overload if we link a section of the manual without it being extremely well-curated (possibly one item per page). We had users who don't understand how to navigate our changelog page which had a single button marked "continue", and I worry that getting users like that to read even a small section of the manual will be a stretch too far. I'm really going for lowest common denominator with this.

As an aside, I think we need to work more on the manual in general and I haven't thought about how to handle this. It's not on CrowdIn, and we need better mechanisms for content updates and segmentation of sections.

PS: I think you're absolutely correct in #8710, this'll be a larger undertaking, and I'd like to see how adding a search bar to the preferences will change user interactions to see if the problem is still as apparent.

----

Reducing the preference width is a good point. I could argue for a two step: `tap help, then tap something to explain`.

----

What do you think? Are my concerns valid? Can we modify the manual to accomplish the above goals without the individual help for preferences?

**Comment by mikehardy** [comment]
@oakkitten you're not shadowbanned, and your comments about being able to have longer (multiline) preference titles are applicable as well.

If I understand all your comments as a coherent thought correctly:

- multi-line preference titles (no ellipses...) would help make some things clear and eliminate tortured phrasing to fit into an arbitrary line length (42chars or similar)
- preferences themselves should be considered one by one and grouped in to "coherent groups" where "coherent" may be judged by "one help section works well to explain the entire group"
- each coherent group of preferences should have one prominent touchable thing that displays the relevant help?

**Comment by mikehardy** [comment]
I would prefer it all be manual links personally so that we only have one document. Downside is that the manual almost never gets translated to any other languages in reality but short strings do. Perhaps the manual could be auto-built from short translated strings or similar so it wasn't an all-or-nothing blob of text that is so frequently the "nothing" case.

**Comment by david-allison-1** [comment]
> I would prefer it all be manual links personally so that we only have one document. Downside is that the manual almost never gets translated to any other languages in reality but short strings do. Perhaps the manual could be auto-built from short translated strings or similar so it wasn't an all-or-nothing blob of text that is so frequently the "nothing" case.

Long-term: Maybe we should split this off into a separate issue about how to deal with the manual. I definitely don't want to see duplicated content.

Short-term: I disagree that a single help link is the best way forward. But it's better than what we have, I'd like to discuss alternatives for a little longer, probably add bullet points to my concerns and aims for this, but I support a single help link.

Aside: A "did this section help you", on the manual, followed by a link to a discussion forum if the user is dissatisfied would be useful, but likely not viable while we have other more pressing issues.

**Comment by oakkitten** [comment]
> Is this an argument from viability of translation (duplicated work), or from a user's perspective?

It's both, but mostly from the user perspective. If this proposal goes through, in order to understand what's going in e.g. “New cards” screen, the user would have to tap on up to 7 help buttons, where some information is repeated. And then they would have to tap on those buttons again to read help text they missed.

And then, when they return to this screen again, and for filtered decks this is is something that they *will* do, they will have to tap those buttons *again*, because the preferences themselves are *still* confusing.

Besides, as translators will have to fit new titles into more limited space, this would lead to even more confusion.

> I intuit that we immediately lose a lot of user interest as soon as we mention "look at the manual": we quickly cause information overload if we link a section of the manual without it being extremely well-curated (possibly one item per page).

Unless I'm missing something, currently there's no way to open the manual from the preference screen. I suppose if the user has to google it themselves then indeed it would be poor UX. But if there's a link on a preference screen that explains that preference screen, and it's well-maintained, that's a different situation.

Yes, it would have to be well-curated. And there will be problems with translating it. But then you have to translate help text for each help button here as well. Translating text, as opposed to individual pieces of help info, is usually easier at it allows for more freedom. And as there's more context, the translations are of better quality. This might not be an issue if the crowdin pages are sufficiently commented (screenshots, etc), but this is yet more work.

Either way, I think it's best to try improve the quality of preferences themselves. And *then* assess whether or not each preference needs a help button, or something else.

>  I think you're absolutely correct in #8710

The thing about #8710 is that the bulk of the proposal is creating more readable titles. If you have a help button for each preference, I don't think it will work with multiline titles, and with some of the current titles. So you'll have to keep the confusing titles, and keep the summaries that duplicate title text. I think the bulk of #8710 is fundamentally incompatible with this proposal.

@mikehardy yep I think this is a good summary. But also I think some preferences need to have in-line explanation. The idea is that you never have to wonder, “What is this? Do I need this?”. Instead, should see from preference title and summary, or perhaps from adjacent help preference, what you are dealing with, and only refer to help for details.

For instance, I could see something like "Timebox" having its own preferences screen with an explanation of what it does. Otherwise, you are forcing the user to open the manual and search for this setting.

> Downside is that the manual almost never gets translated

This is another reason to use helper preferences/explanatory preference screens. I don't think you'll need too many of these, and these can be kept translated.

This might not be the best way to do it, but here's an illustration of the idea from my app (that's aimed at advanced users). Here I opted for very simple preference titles, as explaining something like "File field" can't be done easily. "The name of the primary file field of an emulated HTML form"? But as file pastebins usually explain usage in terms of curl, this rather huge helper preference gives most of the information you need to fill this in. If you follow the Learn more link, you can read the full documentation. But once you do, you will likely *never need to refer to it again*. Maybe this is a bad example in the context of Anki... Oh well, idk

<img src="https://user-images.githubusercontent.com/1710718/116755122-d9c22280-aa01-11eb-8640-bc187af83146.png" width=300>

**Comment by Akshay0701** [comment]
@oakkitten I agree with your points from your #8710 and I believe as David said "we could quickly get 60% of this done in one non-controversial change"

I am not sticking with static one idea, we might require to use a different approach and different UI for filtered Deck/deck option and preference options, 

### Creating “helper/explanatory” detailed screens :
	
- For that options which are not self-explanatory and complex for users to understand 
- We should give an idea/usage of each sub-option from Filter Deck/Deck options in one helper page.
- 	ex: new cards, lapses, group management options from deck/filtered deck, this option have sub-option which need to be explained in detail.

### Using Tooltips for small options :
	

- Use android tooltip to explain and give useful links for options that can be explained in few lines.
- 	Some of the preference options can be explained in short text and context using tooltip and useful links 
- 	ex: card browser font scaling, Automatic display answer, etc.

### Instead of giving text explanation to all pages, we can show a preview of outcomes after selecting an option 
	

- for example, we can show what the answer button will actually look like after changing its width.
- another example: Change width stroke, answer button size, image scaling,(GitHub and other app shows  preview)

Can skip some of the self-explanatory options

Adding manual links to an explanation where we can’t explain in detail (we will try to explain and make things easy for the user in-app only, but still if user fill any confusion, then there should useful links for them to get the detailed idea)

the most important thing, we can translate in-app strings, which may help non-native English speakers.

I will try to make a sample UI of my current imagination, definitely this may be going to be an iterative process.

**Comment by oakkitten** [comment]
> Use android tooltip to explain and give useful links for options that can be explained in few lines.

I'm assuming you are talking about Toasts or Snackbars here. What would be some concrete examples where you think these would be preferable to preference summaries (smaller text under preference title) and other things?

> Instead of giving text explanation to all pages, we can show a preview of outcomes

For some options this would be the deal solution! But these things might require considerable effort to implement. It's definitely useful to keep this idea in mind, though

**Comment by Akshay0701** [comment]
@oakkitten I want to ask you
What's your view on filter deck/deck option activity, do you think the "helper" page should be a solution, or do you want to propose any other way? (I personally think , In filter deck/deck option each option have their sub-options , so having a "helper" page for each option is the solution)

One more question 
Are you familiar with Android Development? 
I wanted to make this collaborative work, can you modify bit parts of android applications?

**Comment by Arthur-Milchior** [comment]
> I like it more, but it breaks accessibility guidelines and I don't think there's a way to fix it:
> > Consider making touch targets at least 48x48dp
> https://support.google.com/accessibility/android/answer/7101858?hl=en

Why ? The touch area should be 48p, it does not mean the button itself should be this big. Having the area near the icon touchable is okay. Actually, it seems that it's usual, since the icon should be suggested in https://material.io/design/iconography/system-icons.html#system-icon-metrics

@prateek-singh-3212, it would be wonderful if you could edit the top level message. This took a lot of discussion in a few days and seeing all/the latest proposal would immensely help following

I'm against web link.
* it would be a nightmare to keep updated what is and is not translated and put correct link. Sending to an english only page seems a bad idea, and most language have no translation
* some users uses ankidroid without internet; maybe not a lot, but I'd prefer that we remain this way. 

As I don't expect we'll find a way to easily allow manual translation, and keeping track of what part is outdated, even if it leads to duplicate English documentation, the fact that it will help users have very simple narrow task for translation is great. We'll have ONE duplicate work allowing to get arbitrarily many documented properties. That's really a good tradeoff.



Do we have any idea which options are the more confusing? I mostly agree with @oakkitten, and there are plenty of cases where I can't imagine what more to add. I also believes you are right in the fact that some options are so related that they should have a single explanation for all of them.
As a user, I believe that splitting preferences into smaller window would also help to find what I'm looking for quicker, I like the idea very much.


Regarding multi-line rpeferences, @oakkitten, would you accept to open a new issue, documenting in one place your whole argument. You gave quite convincings remarks in a lot of place, and it's hard to keep track of them. I would like to get all of them, with the screenshot you shared, at one place. I believe it'll be quite simpler to figure out what should be done. Ideally, if you have a suggestion of solution, showing up on one screen what you suggest to replace the current status, it would be ideal. I would find far far easier to consider your point with images of proposed corrections. (Correct me if I'm wrong, I think it's not in #8710 )

**Comment by oakkitten** [comment]
@Akshay0701

> What's your view on filter deck/deck option activity, do you think the "helper" page should be a solution, or do you want to propose any other way? (I personally think , In filter deck/deck option each option have their sub-options , so having a "helper" page for each option is the solution)

First of all, I'm not sure if filtered deck settings should look like settings.

I think settings should be mostly passive, as in they shouldn't perform actions, unless clearly labeled (e.g. “Forget certificates”). Correct me if I'm wrong, but changing search/limit rebuilds the filtered deck. If I set limit to 100 cards, then go review a few, total card count can read e.g. 80. Then I go change search term, and boom total card count is 100 again. So these “settings” are very active and probably shouldn't be settings at all. 

As for deck options... Well, “options group” is extremely confusing, and I don't understand some settings. But I'm supposing AnkiDroid is following Anki's naming here, so it's reasonable to keep the same titles. Individual preference screens (“New cards”, “Reviews”, etc) seem to be well-grouped, so yes, a single helper page for such a screen sounds good to me. However, in this case you'd have to make sure that at least this portion of the document is kept translated

> Are you familiar with Android Development? I wanted to make this collaborative work.

I am but I'm not sure if I'll have the energy to do anything soon :s

@Arthur-Milchior

> I'm against web link.

I was hoping that “Learn more” links would lead to a document kept internally. You can have these links perform any actions at all. Again, these links are only there to provide deeper understanding of preferences, should you wish. Normally, except in specific cases where it is not feasible to provide inline help, you shouldn't have the need to tap on them. Currently the user has to look it all up themselves on Google.

Let me give yet another example. For instance, for time boxing, you can have...

> * [Screen] Reviewing
>   * [Group] Behavior
>     * [Screen] Timebox settings. {Disabled, <n> minutes}
>       * [Checkbox] Enabled
>       * [NumberPreference, depends on ↑] Duration. <n> minutes
>       * [HelpPreference] Timeboxing is a technique to help you focus by dividing a longer activity (such as a 30 minute study session) into smaller blocks. If you set the timebox time limit to a non-zero number of minutes, AnkiDroid will periodically show a message saying you how many cards you’ve managed to study during the prescribed time limit. [sic]

I copy-pasted the entire text from the manual here. So I don't think there's need to have any more links here at all!

> Regarding multi-line rpeferences, @oakkitten, would you accept to open a new issue, documenting in one place your whole argument.

I'm not sure I could put there more than I already said in #8586... Trying to cram text into a limited space can lead to poor results, that's the whole idea

**Comment by Arthur-Milchior** [comment]
@oakkitten simply copy and pasting this into a new issue would help keep the discussion focused

**Comment by oakkitten** [comment]
i don't really have anything substantial to add to what i said in #8586. since that was rejected it would be rude of me to push it
