### ISSUE TITLE
[Bug] Study option do not appear on start

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8755]
###### Reproduction Steps

1. Open the app on a tablet
2. Check for study option (right side)

###### Expected Result

The selected deck's study option are shown

###### Actual Result

The study option remain empty

###### Debug info
Current master 425701e

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by mikehardy** [comment]
Great @ShridharGoel ! You are probably 100% aware but just in case, it's pretty trivial to set up the emulator in a tablet form factor (in fact, you can even get a chromebook emulator with some more effort!). Just mentioning because I don't actually have a tablet in real life any more so only can access the different form factors with emulators

**Comment by ShridharGoel** [comment]
@mikehardy Yes, I'll be using an emulator for this purpose.

**Comment by oakkitten** [comment]
by the way, you can simulate a tablet by setting display size to the minimal value on your phone
