### ISSUE TITLE
Setting custom note fields using intent API

### ISSUE THREAD

**Issue by shocklateboy92** [ankidroid/Anki-Android#8893]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to add AnkiDroid integration to a progressive web app that I use on phone daily. Unfortunately, (to the best of my knowledge) it's not possible to use the AnkiDroid instant add API from within a browser. However, it is possible to [send intents](https://developer.chrome.com/docs/multidevice/android/intents/) from one which means I _can_ use the `ACTION_SEND` intent.

My problem is: the notes I want to create have a lot more fields than Front and Back; one of them even has an image. As far as I can tell from the documentation, it's only possible to set those 2 fields.

**Describe the solution you'd like**
Would it be feasible to make that intent take arbitrary note fields as extras?
Launching the note editor directly with all the form fields pre-populated would also be good enough for my use-cases.

**Describe alternatives you've considered**
Keeping an anki desktop instance with [AnkiConnect](https://github.com/FooSoft/anki-connect) running on my local network and having do the actual note creation. However, I do think it'll be much smoother if I can do it locally and (I'm assuming) AnkiDroid will give me chance to edit the contents of the note before I hit share.

**Comment by shocklateboy92** [comment]
Uh... the reason I'm doing my project as a PWA is because Android and I don't get along 😏. I'll see what I can do. 

For getting around the size limitation, would you be okay with having AnkiDroid fetch the image if one of the field names end with `_img_url` and has a URL?

**Comment by mikehardy** [comment]
Mmm. Adding "media internalization" would greatly increase the size and fragility (network requests...terrible) of the feature. I'd rather not. For that I think you should just use the image via actual external link as if it was card data, then if you wanted your decks to work offline, periodically use Anki Desktop to run the "Media Internalizer" add-on on your collection.

Stated more simply: start small with the feature. Make it so that you can just send extra text fields through the Intent.extras first and we'll see how it goes. There is no limit to the number of PRs or iterations a feature can have, but it's always better to do things in small increments / integrate / release in my experience. Our integration+release is very low friction so it's not slow, but it's much more reliable, as a process for collaboration

**Comment by shocklateboy92** [comment]
Okay, dug a little deeper and realized that getting into android development would take wayyy more time than I have to spend on this project right now. So I'll go with the workaround of using AnkiConnect to create the note remotely (and maybe sending the sync activity to AnkiDroid). AnkiConnect has a media API to download images as well. 

However, I'll be watching this issue in case some other generous soul also needs this and implements it :crossed_fingers: 
Thanks for your prompt replies!

**Comment by mikehardy** [comment]
I actually had a slightly different thought that was a bit crazy, but if we want the general idea of a "javascript binding for the AnkiDroid API" we are working on that but it's always going to have a native component because it needs to be running in the AnkiDroid process, or a process with a Java library in it. So either a react-native type module that wraps the AnkiDroid API, or, you can package your javascript "app" (or make a new app) that works as a module inside the AnkiDroid reviewer itself and uses the AnkiDroid JS API (which is new - but we're trying to grow in this direction.

All of this is an "under construction" area, but I think in a year there are going to be all sorts of options for folks that want to use javascript/typescript against an Anki collection

**Comment by mikehardy** [comment]
I'm actually going to close this though, as we don't just leave items hanging around unless their actionable or serious issues we just don't have time for yet - and this doesn't quite qualify on either front

**Comment by dimatomp** [comment]
I'm willing to try extending the ACTION_SEND API to send custom text fields to the app, and also make the intent-filter `BROWSABLE`. My idea is to add integration with AnkiDroid to Yomichan, in case if the latter runs on Android browser with such extensions supported

**Comment by david-allison-1** [comment]
> I'm willing to try extending the ACTION_SEND API to send custom text fields to the app, and also make the intent-filter `BROWSABLE`. My idea is to add integration with AnkiDroid to Yomichan, in case if the latter runs on Android browser with such extensions supported

I wouldn't be opposed to this, but in case you're not aware, the functionality is supported by our [api](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API)

**Comment by dimatomp** [comment]
@david-allison-1 Yes I have checked the page. By API supporting this functionality, I guess you mean the react-native and Java APIs for third-party apps?
If the client is a browser application, looks like the only choice is to deliver the request to AnkiDroid via intent, and I did not find any intent-filters exposing schemas like e.g. `ankidroid://flashcards/send?subject=XXX&text=YYY`. Is there anything I am still missing?
That being said, I will definitely look at existing APIs and try to make the new one look similar to a subset of one of those.
Maybe it also makes sense for me to open a new issue, as the topic is slightly different...

**Comment by david-allison-1** [comment]
> @david-allison-1 Yes I have checked the page. By API supporting this functionality, I guess you mean the react-native and Java APIs for third-party apps?
> If the client is a browser application, looks like the only choice is to deliver the request to AnkiDroid via intent, and I did not find any intent-filters exposing schemas like e.g. `ankidroid://flashcards/send?subject=XXX&text=YYY`. Is there anything I am still missing?
> That being said, I will definitely look at existing APIs and try to make the new one look similar to a subset of one of those.
> Maybe it also makes sense for me to open a new issue, as my topic is slightly different...

You seem to be correct and it's a reasonable use case. 

I'll reopen this.
