### ISSUE TITLE
[Bug] Hourly breakdown chart is messed up

### ISSUE THREAD

**Issue by elias6** [ankidroid/Anki-Android#8920]
###### Reproduction Steps

1. Go to the hourly breakdown page.

###### Expected Result

I should be able to make sense of the chart.

###### Actual Result

The chart looks messed up. I think the labels on the x-axis are missing.
![messed up hourly breakdown chart](https://i.imgur.com/fahABmD.jpg)

###### Debug info
AnkiDroid Version = 2.14.6

Android Version = 11

ACRA UUID = e6f00704-5419-4b8b-bb9e-87ea6f666f41

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
That doesn't look right, no - can you try the latest beta to see if that still reproduces there? I've never seen anything like this https://docs.ankidroid.org/#betaTesting

**Comment by elias6** [comment]
I signed up for the testing program, and it said it would automatically install a beta version of AnkiDroid on my phone. I looked up the version and it says 2.15.2 now, which I'm guessing is the beta version, but I'm not sure. The chart is still messed up.

**Comment by mikehardy** [comment]
Okay - thanks for reporting back @elias6 - the beta program membership most precisely means "get me the most recent version that is stable *or* beta" and since there currently is not a beta issued, just 2.15.2 as the most recent version, you've got that one. I will probably just issue 2.15.3 directly as well so you may not get an actual beta again until 2.16 is nearly ready and start issuing 2.16.0beta1 etc

**Comment by elias6** [comment]
FYI I'm using version 2.15.4 now, and I the chart looks a little different now:

![image](https://user-images.githubusercontent.com/510781/121782464-6235f600-cb5e-11eb-9330-6fd91ceff35b.png)

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens
