### ISSUE TITLE
Feature request: style line between question/answer

### ISSUE THREAD

**Issue by bmaupin** [ankidroid/Anki-Android#8941]
I'm a bit embarrassed to request this since it's so nitpicky, but if I'm opening an issue for something this small I see it as a sign that this application is so good that I can only think of nitpicky issues :grin: 

The horizontal line between the question and answer on a card looks like it has a 3D effect reminiscent of websites from the 90s. I'm not familiar with the code but maybe it's an `<hr>` in a webview? A quick search in the repo turns up a lot of results for this string, so maybe that's the one: `<hr id=answer>`

![ankidroid-hr-current](https://user-images.githubusercontent.com/346123/119541898-f2053300-bd5c-11eb-8ef0-445721935f5c.jpg)

Would it be possible to style it to give it a cleaner/flatter look? I was just thinking a simple line might be nice.

I would be more than happy to submit a PR if there's a chance it would be accepted.

Thanks!

**Comment by david-allison-1** [comment]
Thanks!You can do this already since the cards are HTML:

* Edit a card
* Tap "cards"
* You can edit the CSS of the card template
* You can attach the Chrome Dev Tools via: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

Up to other maintainers if we'd want to accept this into `master`, I'd want a second opinion, but I'd be fine with it as long as it doesn't affect anyone's CSS

For reference, the file to edit would be: https://github.com/ankidroid/Anki-Android/blob/88d887fd47dec0dec73d5ac0ae72b1242fd98ec7/AnkiDroid/src/main/assets/flashcard.css

**Comment by bmaupin** [comment]
Oh wow, that's amazing!

I already got a much cleaner result with

```css
.card hr#answer {
  border: 0.5px solid #bbb;
}
```

![ankidroid-hr-styled](https://user-images.githubusercontent.com/346123/119546488-f849de00-bd61-11eb-8e82-38d10dc45021.jpg)

I guess I'll leave this open in case anyone is interested in a change to the default styling (in which case I still don't mind submitting a PR), but I'm quite happy. Thanks!

**Comment by mikehardy** [comment]
Changing default styling or UI anywhere in the app immediately (somehow, actually immediately) results in an issue logged by someone wanting a toggle to turn it of and go back to the way it was because everyone fears change

So given this is alterable and no one appears to feel strongly about it, I'm going to quietly close it.

But! Now you have seen the true power of Anki - the possibilities via card template styling are nearly endless. You might like https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
