### ISSUE TITLE
Improve bug reporting in special cases

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9075]
Sometime, we don't just prefer the user to report a bug, we really strongly need that the user report a bug. Because we can't reproduce it, because we have no idea what occurred, because we need a lot more of information and actual discussion with the user to understand what was special on their phone. #9067  #9065 and  #9064 may be such examples.

What need to be done:
[ ] Create a way to identify the important bug, potentially an enum
[ ] create a preference that records which of the important bug where met, how many time, when
[ ] if an important bug occurred, allow to report it thrice instead of once (change `stacktraceLimit` in special cases in `AcraLimiter`) so that we can know whether the same user get the same bug often or if it a one time event
[ ] a function to record this important bug in the preference
[ ] a new error message, that shows to the user that it is a very important error message and that if they care at all about ankidroid, we really need them to email us so that we can figure out what's going on and allow the app to evolve without breaking in the future

The last part is really important, we need to do it right so that the user can start the reporting process in a single click ideally, so that there is no barrier and we are sure we can get to help them. Maybe the best would be to allow the user to chat with one of us (if they use discord, a link to one of our account), or to open their mail app. I'm not sure what is the best way to really make an exceptional call to action

**Comment by mikehardy** [comment]
Yes and I like it - only saying that crash reports are not part of a statistical sampling strategy ("reporting only one out of ten cases" above) - analytics hits are part of a sampling strategy but bug reporting has it's volume clamped a different way. Bug reporting is reported once per stack trace (deduplicated via `AcraLimiter` configuration) per ankidroid version (limiter data is cleared during startup if it's a version upgrade).

That may change nothing about your proposal, but in my mind I think it means you want to say "exception report is sent every time", at which point we may suffer a thunder herd or DoS on the exception report system so I'm not sure that's right. 

Perhaps more as you mention then, that the analytics hit is simply set to 100% sample instead of current 10%, and that it is never throttled by AcraLimiter.

Note that this is similar to: 

> I would add a dialog for users that experience any RustBackendException for UnsatisfiedLinkError to try a restart, then try a reinstall in that order (taking care to make sure they have a collection backup - thinking to future when we do ScopedStorage)
>
> I would send an exception report as we do now even if we are not fully crashing (because of the dialog) and I would expand our crash report to note disk free/total reporting (example code here if we don't already have some around somewhere https://github.com/react-native-device-info/react-native-device-info/blob/7a87ea18dbe4076f063e08b74dbd42bb2a9c3dac/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L353-L405 - in fact I think we do for collection import / unpack pre-check but this code I just referenced is probably more modern!)
>
> I mentioned analytics elsewhere - I think we do analytics hits on exception reports but I'm not sure if we do them before or after the ACRALimiter / de-duplication happens - I think it's after so we will have incomplete stats. We should add a specific analytics hit for the UnsatisfiedLinkError with extras that specify the flavor of link failure for reporting
>
> I think with some investigating, a little user messaging, and a little stats addition we will have handled this about as thoroughly as possible? Then getting rid of Java collection touches will be the thing to do

From https://github.com/ankidroid/Anki-Android/pull/9066#issuecomment-854814307

...but a bit more fully developed. I like where this is heading with regard to a catalog of specific things we are very interested in, some related state, and a real plea for user participation

**Comment by Arthur-Milchior** [comment]
My bad, then I misunderstood what you meant about sampling. I thought it applied to bug too.

I would ask to change `stacktraceLimit = 1` to a at least 2, maybe leave the default of 3, at least for the bug we deem important if there is a way to do it. This would ensure that we know whether it's a one time bug that goes away at restart or whether it's something systematic for some users. I think it should avoid your thunder heard or DoS while giving us some important information we are missing.

In any case, I did delete: --if an important bug occurred, report systematically instead of reporting only one out of ten cases (assuming the user allowed for report to be made)--

**Comment by david-allison-1** [comment]
I'd like to get this done before the end of the week, ignoring this has the potential to slow down the Rust conversion, or force a subset of users to manually downgrade if we don't resolve the associated issues. The sooner we can start debugging, the better.

Proposal:

* `AnkiDroidApp.sendCriticalExceptionReport(Exception, enum exceptionType, Activity?)`
  * Add an analytics hit method which ignores the threshold and use it, pass in the exceptionType
  * See if we can up the ACRA limit to 2 for the specific exception
  * Display a Dialog:
    * (to bikeshed): AnkiDroid has encountered a critical error. Please contact the developers to resolve this. 
      * `Contact` (opens GitHub to a specific, known issue)
      * `Close`
      * Checkboxes: Enable Analytics and Enable Bug Reporting (if they're not already set). 
      * Checkbox "do not show this again" (or an `Ignore` Button)
         * "AnkiDroid may fail to open in the future". `Ignore/Back`

----

Thoughts on why I changed from the list in the issue:

> [ ] Create a way to identify the important bug, potentially an enum

LGTM

> [ ] create a preference that records which of the important bug where met, how many time, when

I don't see the use-case, that's what the analytics hit will do

> [ ] if an important bug occurred, allow to report it thrice instead of once (change stacktraceLimit in special cases in AcraLimiter) so that we can know whether the same user get the same bug often or if it a one time event

Seems sensible to me, but needs @mikehardy 's input

> [ ] a function to record this important bug in the preference

Again, I don't see the use case

[ ] a new error message, that shows to the user that it is a very important error message and that if they care at all about ankidroid, we really need them to email us so that we can figure out what's going on and allow the app to evolve without breaking in the future

LGTM

**Comment by mikehardy** [comment]
I like the idea of upping the exception stack trace limit to 3 - it used to be so noisy but now it really isn't since there are fewer bugs total and obviously we care about these a lot. That's a good idea (increase, in general) and 3 seems like a useful arbitrary number to peg it to for now

Agreed the analytics hit (assuming it's a "critical" hit that ignores our current sample) should simplify the whole feature idea by removing the need for preferences etc. Should work?

All the rest (the proposed dialog) seems like implementation detail to me - really important yes but what is discussed above seems fine, I have no desire to bikeshed any of it

**Comment by david-allison-1** [comment]
@mikehardy For the analytics, do you have advice on how best to set the reporting percentage to 100% for the hit?

The most sensible way given the API would be another `GoogleAnalytics` instance with the percentage set to 100, so we don't need to reinitialize, or risk the static variable being used by other consumers. 

There might be something here that I'm missing though

**Comment by david-allison-1** [comment]
I'll be back to working on this tomorrow

One pending question: How do we want to deal with "saving" an ignored exception?

I'd like to use `type` + `exception.message` as a key, and either store in:

1. shared preferences
2. a file in `/data`

I'd prefer option 2, but it's non-standard, and suggestions would be great

**Comment by mikehardy** [comment]
Oh yes - I'd saved this one but not ever answered. I don't think I ever imagined UsageAnalytics being used in different ways, and the API shows it. Could always just a parameter that forces a hit ignoring sampling strategy, or could make a separate instance (maybe something like "IssueCounters" as a name since at this point we're not tracking usage, and it's not analytics really, we're trying to get a hard count on a real issue right? But naming is hard and API design is hard and I don't feel strongly about anything other than the idea of getting a real count of times important things happened and it seems like google analytics is a reasonable tool for that job so whatever works with regard to that.

you can have the best of both worlds with regards to saving, use a shared preferences file that is separate and dedicated to this. It's not something we do often - but it works well and would handle all the storage and performance and everything (e.g., apply vs commit)
