### ISSUE TITLE
Feature request: Note Editor Toolbar custom button rename / reposition

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#9077]
**Is your feature request related to a problem? Please describe.**
![snipaste_20210605_180520](https://user-images.githubusercontent.com/10048069/120888044-d5a0aa80-c628-11eb-92c4-08c490cb84a1.jpg)

As the image, I'm in version 2.15.4. There is a long bar in that toolbar now, and my custom button will be at the end of the toolbar, which caused me to have to scroll it every time I use it.

**Describe the solution you'd like**

1. Reduce the width occupied by the buttons so that there are more buttons in a row.
2. Allow me to long-press to change the layout of the button myself
3. Allow me to change the naming of custom buttons

**Comment by Akshay0701** [comment]
> Reduce the width occupied by the buttons so that there are more buttons in a row.

don't you think reducing other's width of buttons will reduce their accessibility, and I personally think in this case custom button's (1,2) width is less as compare to others, so a nice solution would be to increase their width to make it easier to use.

> Allow me to long-press to change the layout of the button myself

do you want to change button's position?

> Allow me to change the naming of custom buttons

it would be great if you create new feature request issue for this

**Comment by Juddd** [comment]
> do you want to change button's position?

Yes. For me this is the most desired need, because I hardly use the current default buttons. I have to swipe that bar to the far right every time to use the custom button


> don't you think reducing other's width of buttons will reduce their accessibility, and I personally think in this case custom button's (1,2) width is less as compare to others, so a nice solution would be to increase their width to make it easier to use.

I'll tell you clearly, I never pressed the wrong button in the previous version (the width of the previous button is narrower than now). Of course, exactly how wide to set this is really a technical issue. But I think it should be narrower than it is now.

**Comment by mikehardy** [comment]
In order to reduce padding we would need to know for certain that it does not violate accessibility - that's something we are paying attention to now and anecdotal statements like "I don't mind if it's narrower" are not valid in this context. We have users with essential tremor for instance and your statement will not provide them comfort

**Comment by Juddd** [comment]
You're right. When you decide exactly how wide to use, could you please let me first be able to change the ordering of the presses? This is really very important to me. Also, the renaming feature can be done together? Please. :)

**Comment by mikehardy** [comment]
The problem I have with further development of this specific feature is that the "note editor toolbar" in general is a temporary solution on the way to #1377 ("what you see is what you get" editor). I'm not interested in seeing further feature development here as the Note Editor Toolbar as an entire feature should go away.

However, taking this as a sort of sub-feature request for the WYSIWYG editor ("there should be macro buttons", "macro buttons should be nameable vs just numbered", "WYSIWYG button order may be configurable" is reasonable) though not as important as simply getting WYSIWYG editing done. If we took these as feature requests there I think keeping the WYSIWYG button order stable in general is a good idea but if there are custom macros maybe they may be added as a second row or something, since the AppBar buttons as a similar feature is not something people use a lot and I imagine this will be similar - it's a niche use case so having it as a maintenance burden mixed up with the main the main set of editing buttons is not something I want to see

**Comment by Juddd** [comment]
@mikehardy Showing a button that can't be displayed on one line as two lines is really better than letting the user customize the position, IMHO. Also, it's really important to allow renaming.

**Comment by mikehardy** [comment]
These things are all exactly as important as your motivation to implement them, don't forget...

**Comment by infinyte7** [comment]
I have used single ascii character for showing addons button icon in note editor js addons.
So, may be single character will be better.
I used following in the addons.
For cloze js addons, [
For pinyin js addons, 文
