### ISSUE TITLE
Move js/java interface to asynchronous

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9104]
There is a problem, currently, that with Javascript interface, the data is expected to be returned immediately. That stop us from computing data in background, leading to either compute data in foreground, return inaccurate data, or (as it is currently done), computing all potential requested data before opening the card. 

Moving to asynchronous would solve this problem. According to @mikehardy, on discord, async javascript is now standard, so it's actually a very small extra burden to add-on users and free us to add interface that requires computation/database access if needed.

I don't know whether we would want to have all calls asynchronous, or only the one that may need computation. In any case, #7172 would require ankiGetLrnCardCount,  akiGetNewCardCount and ankiGetRevCardCount to be async. However, ideally, we would want a general system for async call, and not just a special case for those methods.

@infinyte7 would you accept to work on it?

**Comment by mikehardy** [comment]
Combined with this we should publish a typescript index.d.ts file that documents the typing of the Javascript side of the API. Without this devs will have a hard time remembering what is async, what is not, and when we do breaking changes it will be easy with the types to communicate exactly to devs what they changes are and for them to ingest them

**Comment by nicdard** [comment]
I would like to work on this feature, but I miss a little bit of context on where to find the js API bindings for example. Also maybe we can move the js code to typescript instead of just and the definition file. Having typescript would allow us also to use openapi specification for example and get typescript types and stubs from a specification either written or generated from java code. Last but not least this would help also documenting the APIs, but it's a proposta that maybe is not feasable

**Comment by infinyte7** [comment]
There are various JavascriptFunction in AbstractFlashcardViewer.java. Those functions work as JS API. So during review API like `ankiGetLrnCardCount` called then AbstractFlashcardViewer return learn card count immediately. 

So, here implementation is make this asynchronous.
 More info
- [AbstractFlashcardViewer.java](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3404)
- [card.js](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/assets/scripts/card.js#L78)
- [AnkiDroid-JS-API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API)

**Comment by nicdard** [comment]
I have investigated this, it was a new topic for me, since I never used webViews and Js bindings. As far as I have understood the `JavascriptInterface` annotation allows only to return primitives or objects, which are serialised into JSON, that makes usage of Future-like objects not usable. To allow an async interaction we would need then to have some other form of calling back js after the operation has completed. An approach that I have found is to call to load an url with `javascript:` protocol followed by the cb name, to call a defined function in the page, so the command should take the name of the callback to invoke.

I don't really like it, is cumbersome to be used and not really flexible for the developer, another way to go would be to use [MessageChannel](https://developer.android.com/reference/android/webkit/WebView#createWebMessageChannel()). However this is still not enough and maybe not the right solution to address the problem, also the API level for this call is 23.

The real issue here is that the Java to js binding is missing here. The way other than calling a global defined function through loadUrl, seems to be calling `evaluateJavascript` but this has the same down side as the previous approach. Do you have any suggestions?

If those are the only possibilities, I would say it would be better to convert the javascript APIs into postMessage apis, it seems to be more clean to me, but let me know your toughs! :)

Also this is gonna be a breaking change anyway

**Comment by mikehardy** [comment]
I don't have a concrete suggestion here, but it feels like we want to do exactly what (for example) react-native does, with a javascript/native bridge. I'm not sure how exactly they do it at this level - as in how the bridge is coded. This needs a lot more thought than I have time to offer here at the moment unfortunately

**Comment by nicdard** [comment]
@infinyte7 I have seen that we are using currently`onPageFinished` to run a javascript function with the same name which is defined in card.js. My question is, sorry for this as I said I am still new to the topic, is card.js always loaded into the WebView? Where is this performed? Because in that case it can be easier to set up a bridge for async functions based on messages.

**Comment by infinyte7** [comment]
AnkiDroid used webview to show cards/notes in reviewer UI, so HTML, CSS and JS used in `card.js`. 

You can view how `card.js` loaded in this image. Enable HTML/JS debugging from advanced settings in AnkiDroid then use chrome to debug/view it.
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection


![无标题](https://user-images.githubusercontent.com/12841290/125189204-7c501a80-e269-11eb-9f75-6b56c17969f8.png)

**Comment by dae** [comment]
Closing in favor of #14226. If something has been missed, please let us know.
