### ISSUE TITLE
API module lint settings can break builds in consuming app's release process (workaround included)

### ISSUE THREAD

**Issue by KursX** [ankidroid/Anki-Android#9214]
I use anki export api in my project

`implementation 'com.github.ankidroid:Anki-Android:api-v1.1.0'`

And see lint errors:

```
Explanation for issues of type "DirectCalendarInstanceUsage":
   Manually creating Calendar instances means time cannot be controlled during
   testing. Calendar instances must be obtained through the collection's
   getTime() method
```

```
Explanation for issues of type "DirectDateInstantiation":
   Creating Date instances directly means dates cannot be controlled during
   testing, so it is not allowed. Use the collection's getTime() method
   instead
```
   
```
Explanation for issues of type "DirectGregorianInstantiation":
   Creating GregorianCalendar instances directly is not allowed, as it
   prevents control of time during testing. Use the collection's getTime()
   method instead
```

Why library does check my project code?
How to disable it?

```
lintOptions {
    checkReleaseBuilds false
    abortOnError false
} <- bad solution
```

**Comment by mikehardy** [comment]
It is not easy to control these things, and we have very tight lint settings on our repos here, but it appears we have not actually fixed them in the API module (they're all clean on the main AnkiDroid module)

In the interim I suggest some gradle magic to disable things

Taken from a PR I made in a different repository I maintain https://github.com/invertase/react-native-firebase/pull/5208/files#diff-8c7646704677cc513072d797a0964327e03e234ff31da87325141f26427eaa90

The idea is to add a "subprojects" iterator in your main build.gradle - full block shaped sort of like this - it will be different for you though https://github.com/invertase/react-native-firebase/blob/870705bc136f38b24f9948ce3b05676427c7974b/tests/android/build.gradle#L62-L100

Then you select the ankidroid api project and turn lint off just for our project

It will be a little like this block, but instead of looking for firebase and turning things *on*, you're looking for api and turning it off

https://github.com/invertase/react-native-firebase/blob/870705bc136f38b24f9948ce3b05676427c7974b/tests/android/build.gradle#L83-L98

```groovy
    if (project.name.contains('firebase')
      && project.hasProperty('android')) {
      android {
        lintOptions {
          abortOnError = true
          warningsAsErrors false
          lintConfig file('./lint.xml')
          checkReleaseBuilds = true
          checkAllWarnings true
          showAll true
          textReport true
          textOutput 'stdout'
          htmlReport true
        }
      }
    }
```

so maybe more like this? needs testing, this is completely untested

```groovy
    if (project.name.contains('api')
      && project.hasProperty('android')) {
      android {
        lintOptions {
          abortOnError = false
          checkReleaseBuilds = false
        }
      }
    }
```

This is still a hack but it is under your complete control (no waiting on us!) and it is extremely precise so it is elevated more to "good temporary solution" vs "bad solution"

Hope this helps?

**Comment by KursX** [comment]
Maybe this is better solution
```
lintOptions {
    disable 'DirectGregorianInstantiation', 'DirectDateInstantiation', 'DirectCalendarInstanceUsage'
}
```

**Comment by mikehardy** [comment]
That could certainly also work!
I'm going to reopen this though to check the lint settings, we shouldn't blow up other people's release process with our lint rules when they ingest the api module as a dependency. As linked on react-native-firebase I've seen this happen before and it's an anti-pattern and I'd like to fix it

**Comment by david-allison-1** [comment]
Solutions that I see, second would be best. First is definitely easy to do

* Only have lint work on the `com.ichi2` package
* Remove the lint.jar from the API before publishing
