### ISSUE TITLE
Add help button in V2 scheduler confirm dialog.

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#9265]
![Capture](https://user-images.githubusercontent.com/52353967/125635875-8a334f59-70a8-4911-9a4b-d8c6f0ccee4c.PNG)

In V2 scheduler confirmation dialog, it's advising the user to look at documentation before activating this setting, 
so it would be good if there is a help button over the left side which will redirect to the right documentation of this [Anki 2.1 scheduler](wfaqs.ankiweb.net/the-anki-2.1-scheduler.html).

**Comment by mikehardy** [comment]
I noticed this the other day. I think a Help button is a good idea but the whole text needs a new string now.
It's no longer experimental at all, we're going to be forcing a migration to it shortly
The only downside is that during the actual switch, your cards may be scheduled differently for a short while?

What I would like to see is the string say:
- exactly what the scheduling effect is that might surprise people (this may need a little research or a consult with Damien)
- a link to a manual entry where we explain the v2 scheduler is the future state of anki, and explain the difference between v1 and v2, and what happens when you switch back and forth

**Comment by david-allison-1** [comment]
Once we move to a later version of the Rust, the scheduler upgrade doesn't have the downside of resetting the step-based cards, it's free, but will cause UX issues that we need to explain "why do my learn cards now have a "hard" step, what does it mean?

**Comment by Alphyn-gunner** [comment]
Since v2 is now the default scheduler (since 2.1.45), it looks like this issue sort of changed its scope. Moreover, now there's V3 scheduler, that brings a lot of important improvements, like proper handling of learning cards with steps longer than 1 day (in regards to burring related cards and counting reviews), proper mixing of new cads from different subdecks, better handling of daily review limits. V2 and V3 databases are supposed to be identical, so one can use V2 scheduler on Ankidroid an V3 on PC, so this is not a pressing issue, but is certainly nice to have. I haven't seen any issues open regarding the V3 so far, though.

So if the V2 is made the default scheduler in Ankidroid, it would make sense to make a disclaimer when switching to the legacy scheduler instead? Would another disclaimer be necessary when V3 is implemented, considering V2 and V3 are supposed to be fully compatible?

**Comment by mikehardy** [comment]
I'm not sure how much choice we should offer in the future, though I'm sure people will want to crucify me for that statement. I think in general we should run on the latest scheduler, or - if this is ever implemented - whatever pluggable scheduler is explicitly chosen by a user with a disclaimer for that.

So whatever is done here I think it should be opinionated. I think it should be pushy towards the V2 scheduler with a big disclaimer if the user attempts to toggle it off, and a help button that just goes to upstream documentation on scheduling and what happens if you switch between v1 / v2

**Comment by dae** [comment]
For reference, Anki dropped the option for v2→v1 downgrade in the 2.1.41 release in March. Users who really want to downgrade can still accomplish it by downgrading their app first. Currently they can continue to use v1 if they ignore the nag screen at the top of the deck list, but it will probably turn into a hard requirement in the not too distant future, as it's a significant maintenance burden.

Once v3 has stabilized, I'd like to phase out v2 as well, in a much shorter timeframe than the v1→v2  transition. With v2, we had the long wait for the timezone handling to be resolved, and some users preferred the presentation order of review cards that v1 used. Hopefully the improvements in v3 will make a v2→v3 transition easier, and once complete, we'll no longer have to hunt to implementation-specific bugs in the scheduler.

**Comment by mikehardy** [comment]
I agree completely with shorter rev times for scheduler transitions when/if they happen (V3, then v4 etc), and I would also agree with disallowing the V1 transition if Anki Desktop already does that it doesn't seem like it should even be a discussion, big :+1: 

Anyone that takes this up :pray: feel free to do the same
