### ISSUE TITLE
New cards appear in the wrong order[Bug]

### ISSUE THREAD

**Issue by hydeswag** [ankidroid/Anki-Android#9298]
I'm on 2.15.6

I've added cards to a deck and the new cards aren't showing up by order I added them. It's showing me the newest cards I added. I add new cards all the time so I'm never going to see the cards I added a few days ago

**Comment by mikehardy** [comment]
Hi there! This may be unexpected, but may also just be how the scheduler works. May I ask how this behavior compares to Anki Desktop? Additionally...on introspection, doesn't this use case (adding more card per day then your setting of new cards to show per day) seem like an invalid configuration, in reality? You say "I'm never going to see the cards I added a few days ago..." - that says to me you need to increase your new cards per day count to match your ambition with regard to adding cards. Or if it's a temporary thing, "study ahead" on the deck to get through the new cards?

**Comment by mikehardy** [comment]
(oh - a bit of explanation: I ask about Anki Desktop behavior because we *will* schedule the same as Anki Desktop or it's a bug, as the ecosystem should remain compatible with regard to scheduler behavior - so if this is how Anki Desktop behaves - forums.ankiweb.net is the place to go to query, then we'll adopt any changes if need be)

**Comment by hydeswag** [comment]
Okay well it seems to be an anki problem in general.



Also I add new words I encounter to my deck but I won't do all of them the same day

**Comment by mikehardy** [comment]
As long as you get to them eventually, I think the exact order in which new cards appear is not a "problem" per se, it is more of an existential philosophy question. What does it matter which card shows up when? Unless there truly is a rates problem where ingress (new cards) is more than egress (review of new cards) will ever be, but that is also a philosophy problem related to ambition vs effort. I suffer from this on occasion.

**Comment by hydeswag** [comment]
but i add sometimes more cards than i see in a day so it does become a problem

**Comment by mikehardy** [comment]
I do that as well. Study ahead or slow down on the adds I think.
If you want to change the way the scheduler shows you new cards, that's a general ecosystem-wide change and you'd want to start at https://forums.ankiweb.net (Anki Desktop - what we consider "upstream") and if they make a change we will mirror it here

**Comment by harrisonmg** [comment]
Based on Damien's comments in [this ankiweb forum thread](https://forums.ankiweb.net/t/bug-new-cards-dont-appear-in-correct-order/27719), I think this does constitute a bug. I'm not sure when the new card insertion order deck option was added though, perhaps after this issue was closed.

I'm seeing new card order get bungled on 2.16.0beta2 (and on 2.15.6), and my experience is identical to the user in the thread I linked, down to the outcomes of his debugging steps.

FWIW, I do consider new card order important if the cards tend to build on each other - e.g. a later card contains a word whose definition is on an earlier card. Additionally, my cards tend to be added in groups with a shared context that I find valuable when seeing for the first time.
