### ISSUE TITLE
Clickable tags

### ISSUE THREAD

**Issue by dumbdreamed** [ankidroid/Anki-Android#9404]
Hello my friend, really appreciate your efforts especially in the last updates.
Tags are an excellent way to organizing our workflow and seeing the bigger picture.
But it is very time consuming to select a tag while reviewing a card or when we want to see cards related to a specific tag.
Is it possible to implement a feature to see tags on review card and click on it to see related cards? Like this add on for PC version https://ankiweb.net/shared/info/380714095
It would be amazing.
Thanks again

**Comment by mikehardy** [comment]
This should be possible with the current state of the AnkiDroid JS API

Specifically I think it is possible to both:
- iterate over the tags [which are already present in the generated card](https://github.com/ankidroid/Anki-Android/blob/d08acb24174f60f3f380b909beb1c0ae83d12411/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1097), and thus available to javascript for programmatic use (so you may iterate over them and generate links in the card display)
- open the card browser with a specific search via the [`ankiSearchCard` JS API call](https://github.com/ankidroid/Anki-Android/blob/d08acb24174f60f3f380b909beb1c0ae83d12411/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L4225) (so any link generated for a tag may open the browser to a search for that tag)

We are building the Javascript API specifically so that we may support non-standard (read as: not in mainline Desktop code) features like this, and we expect users to take advantage of it where possible.

If you give it a shot please post the result javascript here, so others may use it

**Comment by dumbdreamed** [comment]
really appreciate it, my friend.it would be amazing that everyone could implement their features into ankidroid.
unfortunately, I don't know anything about java but i have some understanding of HTML, CSS, and a little bit of javascript.
this feature that I mentioned is it on your to-do list in the near future?

**Comment by david-allison-1** [comment]
The API is JavaScript. You're already able to accomplish what you're after in AnkiDroid 2.16: 

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

**Comment by mikehardy** [comment]
Yep - exactly that - whole point of the javascript API is to expose these powers for user, via javascript. You can code javascript in your card template, to do these things, based on the info from my links above

**Comment by dumbdreamed** [comment]
> The API is JavaScript. You're already able to accomplish what you're after in AnkiDroid 2.16:
> 
> https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
> 
> The feature's not on our roadmap, and likely won't be a native feature unless it's implemented in Anki Desktop.
> 
> It will likely be possible to include in an addon for AnkiDroid in the far future

really appreciate it my friend and thanks for the link and the guidance. I will look it up and try my best on it.

**Comment by dumbdreamed** [comment]
> Yep - exactly that - whole point of the javascript API is to expose these powers for user, via javascript. You can code javascript in your card template, to do these things, based on the info from my links above

thanks for the tips, my friend.
you and the other developers on this project are doing a fantastic job, please keep up the good work.
