### ISSUE TITLE
FR - Eliminate long press for Deck Menu

### ISSUE THREAD

**Issue by joshakaw** [ankidroid/Anki-Android#9427]
**Is your feature request related to a problem? Please describe.**
On the main Decks screen, you have to long-press on the title of the deck to open the deck settings menu. 

**Describe the solution you'd like**
For convenience and discoverability:
- the Deck Title click area should open the Deck Settings menu directly.
- the Deck Count click area should directly open the flashcards, possibly adding an arrow to the right of the counts (to indicate an instant study function).
-  add a unique-looking Study button to the current Deck Menu, (so if the user is new to the interface, clicking anywhere on the row provides a route to the primary function: studying cards).

**Describe alternatives you've considered**
None that I can think of that makes it more convenient
**Additional context**

This is a step towards a new Deck Menu interface that is more discoverable. 

Side note: I proposed this idea a few months ago while also including a Deck Menu interface idea, but I think going step-by-step would make better progress and allow for better input.

<img src="https://user-images.githubusercontent.com/84877484/130092094-e7c29f67-d4a3-481c-87b7-32c8378cf416.png" width="300">

**Comment by sudomain** [comment]
Hello, sorry for going off topic (I don't have an opinion on your deck menu proposal), but are the Math decks shown in your screenshot also shared decks? 

Sorry again, I didn't have another way to contact you. I'm not an active contributor to AnkiDroid but I browse the issues some times.

**Comment by joshakaw** [comment]
> Hello, sorry for going off topic (I don't have an opinion on your deck menu proposal), but are the Math decks shown in your screenshot also shared decks?
> 
> Sorry again, I didn't have another way to contact you. I'm not an active contributor to AnkiDroid but I browse the issues some times.
> 
> EDIT: I'm more than willing to delete this if OP or one of the contributors ask :)

Yea, I installed AnkiDroid on a work profile on my phone, separate from the one I usually use, and put on a random Shared Deck about math (the whole root Math folder). I don't exactly remember which one it was but I'm sure you could find it. Also, at least for me, it's completely reasonable to ask a question like that since it's related to the post.

**Comment by mikehardy** [comment]
I just want to apologize that I don't have the bandwidth just this moment to give this the attention it deserves. The discoverability of the deck options is terrible, and this seems reasonable - please be patient with us as we finish up the Google Summer of Code work that's currently got our review-meters pegged at 100% :sweat_smile:

**Comment by mindinsomnia** [comment]
![mockup-2](https://user-images.githubusercontent.com/15921126/131274791-01fd8bf8-20c0-4b23-859b-3965e5f78846.jpg)
Mockup for possible solution.

**Comment by david-allison-1** [comment]
With the grey background for the counts, how do we want to handle when the number of figures differs?

Real collections can have 100 | 100 | 100 and 0 | 0 | 0 on the same page, and the difference of 6 characters to the width of the box is stark.

![image](https://user-images.githubusercontent.com/62114487/131286152-c493ad13-ecde-4bbb-b665-293d034aaf1d.png)

**Comment by mindinsomnia** [comment]
Only two options, either make the pill wide enough to take a value such as "999 999 999", or make it expand in size as necessary.

Visually it's better to have consistency and alignment of elements, so it would be better if the pills were all the same size most likely. However then they would take a significant amount of space, and unnecessarily most of the time. Also the case that there's always the possibility there could be a number with more than 3 digits too, no matter how unlikely..

I think as a halfway in between, I would make the minimum width slightly larger, while allowing it to stretch in size as necessary. Perhaps size it for 2 digits in each column. That won't make the pill too much larger, and in most circumstances will result in pills being the same size.

**Comment by mindinsomnia** [comment]
![mockup3](https://user-images.githubusercontent.com/15921126/131289553-42f24dad-2209-4ce8-9e7e-4047d0650af5.jpg)
Mockup to illustrate

**Comment by david-allison-1** [comment]
Hmm... 3 digits are common, 4 are rare, but do occur.

Might be best to use Anki desktop's two counts (new/review) on the main screen, rather than showing all 3

**Comment by mindinsomnia** [comment]
More mockups of potential designs:

After vs Before:
![mockup-7](https://user-images.githubusercontent.com/15921126/131365462-20c6fffd-5478-4f22-8cdb-ea5c72bd1c85.png)

Animated slide on menu items:
![touch-slide-menu](https://user-images.githubusercontent.com/15921126/131365472-c8a1779f-89f2-4f86-b438-1b96cb27f51e.png)

**Comment by joshakaw** [comment]
Personally, I think the ultimate goal would be to provide an easy one-click option to either Study or view the Deck Menu. Adding a ... menu limits the horizontal space by a considerable amount, it's not a one-click option, and you have to repeat it for every single row. I disagree with that part.

But I do like the background idea, maybe we could have two states for that sort of thing:
1. Ready to Study - Blue outline, blue arrow, text in color.
2. Finished - All light gray (text, arrow, outline)
![image](https://user-images.githubusercontent.com/84877484/131397270-346d0aac-7b5a-46dd-a844-d2b992ed33c1.png)

**Comment by david-allison-1** [comment]
I've started work on this, but will leave it open for discussion before I continue

I like @mindinsomnia's concept (we've discussed this issue in private).

Definitions:
* Vertical nav: a button displaying "..." vertically
* Pill: A rounded rectangular background around the counts

My current thoughts:

* Our main issue is the discoverability of the long-press menu
  * Our aim here should be to offer an alternative interaction to open the menu
  * Removal of the long press is optional, I'd keep it unless we can replace it with something better
  * This issue seems more to do with reducing the interaction cost (in that a long press is too much?)
    * @joshakaw What are you doing which requires you to open the menu so often?
* The most common action that a user performs is to review the deck
  * This implies that clicking the deck should open the reviewer if screen space is limited
* I believe the second most common action will be to view the deck overview
  * This is possibly due to the first point
  * For now, we should keep this interaction mode easily accessible
    * I'd rather not move this to the "long press" menu, but this would potentially be viable if we find it's used less than opening the menu
* I believe that "custom study" & "deck options" are also candidates for common interaction
* Custom Study is also available by tapping a finished deck
* We don't want to massively encourage custom study and should improve messaging (cramming isn't efficient, increasing reviews is fine, increasing new cards is questionable)
* Using a **pill** is likely a non-starter due to the variation of widths.
  * If we have a pill, we want it to have a consistent width
  * A consistent width will be the maximum of all widths, causing deck name truncation
* Adding a **vertical nav** outside the deck counts is probably a non-starter (three interactions: menu, study and overview)
  * Accessibility means this will be 48x48dp
  * This reduces the amount of text in a deck name
* Including a **vertical nav**/arrow inside the counts won't take up much extra space, so is acceptable
* We could potentially add two more gestures for power users: swipe left, and swipe right

**Comment by david-allison-1** [comment]
Had a chat with @joshakaw 

This issue is a follow-on issue from #9043 and the following screenshot gives context for this change:

<img src="https://user-images.githubusercontent.com/62114487/131418161-fb4e0bd2-c4c6-44b4-b449-8008f6fbfb8f.png" height="300px" >

Brief summary, please correct me if you feel this isn't representative or needs expansion:

* Agreed on discoverability being bad
* **vertical nav**: takes up too much space in the above
* Swiping won't resolve this, it's also not discoverable and avoids the issue of the deck menu being requiring improvement, rather than fixing it
* The aim is to move the deck menu towards a dialog (see screenshot), other solutions may patch this up, without addressing the underlying issue
* The deck overview screen doesn't get much use outside of tablet mode
  * Remove it/replace functionality with a dialog
* "Review Completed" screen seems like a good idea

> I relate the deck overview to being in the deck

> Right now there's selected decks and it corresponds to what you see when you go to the other screens like Stats and Browse
which is kind of fidgety

**Me:**

* Each "concept" should have a screen, and I feel this is where we struggle
  * Deck Picker does too much
  * Deck Overview does too little - effectively a delay to pressing "study"
  * Custom Study doesn't have a home
* Our Deck Overview screen is the screen for a single deck, and it should see more use
  * If we flesh it out: "Browse Cards", "View Stats", "Edit Deck Options", "Custom Study", "Import CSV" etc... then it starts to have a purpose and isn't associated with starting a review
  * We can add the concepts in the above screenshot to the Deck Overview, it's still one click from the Deck Picker
* I've been informally thinking about a "Review Completed" screen, which can also include some of the options listed in the screenshot

Since AnkiDroid doesn't currently have any dialogs close to the complexity of the screenshot above, I feel it should be a screen - this is a point of discussion that hasn't been resolved

**Comment by mindinsomnia** [comment]
> 
> 
> Had a chat with @joshakaw
> 
> This issue is a follow-on issue from #9043 and the following screenshot gives context for this issue:
> 
> <img alt="" height="300px" src="https://user-images.githubusercontent.com/62114487/131418161-fb4e0bd2-c4c6-44b4-b449-8008f6fbfb8f.png">
> 

Quite like that popup concept, not sure if I prefer it over other options but it's worth messing with the idea.
I made a couple of tweaks to the mockup with some suggestions of my own:
![popup-mockup-sm](https://user-images.githubusercontent.com/15921126/131437002-bc743370-8706-4281-953c-03545a66c3fc.png)

Pros:
- I like the slick nature of it, an animated slide up popup is pretty neat, and tapping on the greyed out area could dismiss the popup for fast navigation.
- Gives quick access to the must-haves.
- Could work either as a secondary action attached to three dots next to each deck, or as a replacement for the main action when tapping on each deck itself.
- 
Cons:
 - A full screen would be better to show description and more information about the deck.
 - Very limited room for the name of the deck with the layout I proposed, but other layouts feel somewhat unbalanced (see original design and the menu floating in a row all of it's own at the top of the popup). Could move 'Play' button to separate row on it's own perhaps.

On the rest of David's comment, I agree with basically everything.

> Right now there's selected decks and it corresponds to what you see when you go to the other screens like Stats and Browse
which is kind of fidgety

110%
