### ISSUE TITLE
hebrew values-he folder from crowdin needs duplication into values-iw - both are apparently needed

### ISSUE THREAD

**Issue by ROOMBON** [ankidroid/Anki-Android#9451]
for working hebrew translation- please change the folder name of the hebrew translation in res to "values-iw". now it's dosn't works.
thanks

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Could you will out the debug information template: `Settings - AnkiDroid - Advanced - Copy Debug Info`

Thanks!

**Comment by ROOMBON** [comment]
i just try to rename the folder name with apktool and its work. before it- not.

**Comment by mikehardy** [comment]
This looks more subtle then just renaming. It apparently needs duplication https://stackoverflow.com/a/8843293/9910298
In other words, @ROOMBON what you did works for you, but what we have currently works for others. So to directly rename it would fix you but break others. It appears we need to add some smarts to the localization script to handle an incoming language code ("he" in this case I believe - but should be verified, whatever crowdin sends out) and maintain mappings to multiple outbound codes (in this case "he" and "iw") in order to work everywhere.

**Comment by ROOMBON** [comment]
There's no way it's working right now. This matter is global on Android.
To be on the safe side, feel free to find out if this works for anyone ...

**Comment by mikehardy** [comment]
I don't believe you read the above link, it indicates there definitely are devices that work with the existing code.
And in general if we don't do everything on the safe side, we have enough users that someone will log an issue about whatever corner case we have

**Comment by mikehardy** [comment]
If anyone takes this up: this is a permalink into the script that needs work, below the array on this link https://github.com/ankidroid/Anki-Android/blob/4587fedabec2dd36af9c77a6a2b5dc5fead1e5e4/tools/update-localizations.py#L38 I think we need a new "copyRegions" data structure that maps inbound region code to outbound region codes, with first mapping being he to iw and he, then latter in the actual copy phase here https://github.com/ankidroid/Anki-Android/blob/4587fedabec2dd36af9c77a6a2b5dc5fead1e5e4/tools/update-localizations.py#L190-L221 it needs to check if there is a copy mapping for each language, and if there is, make a new folder for each copy mapping

**Comment by kpdyer16** [comment]
Hi I'm new here, but I'd like to take on this issue.

**Comment by mikehardy** [comment]
@kpdyer16 that would be great. This one will be a little difficult to test because getting a copy of the raw file from crowdin may be difficult without the API key.

I'm attaching an ankidroid.zip file that *would be* the result of the download (referenced as "zipfile" in the update-localizations.py script) here for use during testing.

Note that the script requires python2.7 - and it behaves best under macOS - we use a macOS runner for it here in github actions and I use an OSX-KVM virtual machine (https://github.com/kholia/OSX-KVM) running on an ubuntu 21 linux host for local development.

I promise it all works though :-). Good luck !

[ankidroid.zip](https://github.com/ankidroid/Anki-Android/files/7186854/ankidroid.zip)

**Comment by mikehardy** [comment]
This is available for anyone to work on.

**Comment by Aditya13s** [comment]
@mikehardy Please assign me this.

**Comment by david-allison** [comment]
Thanks for your patience (and the reply!) saved us tons of time

**Comment by Aditya13s** [comment]
@david-allison can you please explain exactly what need to be done in this issue?

**Comment by david-allison** [comment]
Our CrowdIn download script needs to be extended to create both `iw` and `he` values folders from the CrowdIn sync process

**Comment by Aditya13s** [comment]
How can I do this?

**Comment by david-allison** [comment]
The code here already writes files on a download. It needs to be extended as above

https://github.com/ankidroid/Anki-Android/tree/main/tools/localization/src

**Comment by Aditya13s** [comment]
> Our CrowdIn download script needs to be extended to create both `iw` and `he` values folders from the CrowdIn sync process

How can I extend it?

**Comment by Aditya13s** [comment]
> The code here already writes files on a download. It needs to be extended as above
> 
> https://github.com/ankidroid/Anki-Android/tree/main/tools/localization/src

How can I extend it?

**Comment by david-allison** [comment]
Look into `update.ts`, find the relevant code and update it to match requirements

**Comment by Aditya13s** [comment]
@ROOMBON can you help me in this issue?

**Comment by kpdyer16** [comment]
@Aditya13s Do you mind if I take this on again? As for the other maintainers, my apologies. I won't ghost this time, I promise 😅

**Comment by david-allison** [comment]
@kpdyer16 The only problem is when issues are assigned, not being worked on, and blocking others from taking them on (especially 'Good First Issues')

Life takes priority, it's ALWAYS fine for Open Source to be put on hold, just let us know (and post a patch of where you got to)

Let's wait for a reply and see how things move from there

Cheers!

**Comment by Aditya13s** [comment]
Sorry @kpdyer16 , But currently I am working on this issue.

**Comment by kpdyer16** [comment]
@Aditya13s No worries! I'll see if there are other issues I can pick up.
Where I left off, I had a working solution, but the best I had for testing was just locally running it with that example `ankidroid.zip` file Mike posted.

I checked out your PR, but the approach should be to map `values-he` to both `values-heb` and `values-iw`. Take this with a grain of salt, but I think an appropriate solution without significant refactoring would be to change `androidLanguage` into an array, and setting it to `["heb","iw"]` in the switch statement.
https://github.com/ankidroid/Anki-Android/blob/1a5c8432d67eec36d7f717de1a8ae9625e5e52d3/tools/localization/src/update.ts#L183

You'd have to do a bit more than *just* that, but I highly recommend requesting a new zip of the current localizations stored on Crowdin so you can see how it works, since we don't have the API key to download a copy ourselves.

**Comment by Aditya13s** [comment]
@kpdyer16 How can i test it?

**Comment by Aditya13s** [comment]
@kpdyer16 if you know how to fix this issue, you can work on this.

**Comment by kpdyer16** [comment]
@Aditya13s Thank you, I'll pick this up.

**Comment by mikehardy** [comment]
The enhancement here will be present in 2.18beta3
