### ISSUE TITLE
[deprecation] Migrate away from setTargetFragment

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9452]
Migrate away from setTargetFragment

We aren't tracking this deprecation yet, I'll peel this comment to a new issue - used in Preferences.java

This contains a sketch of an implementation (note a link to a comment on an answer - the comment refines the answer in a necessary way I think):
https://stackoverflow.com/questions/64869501/how-to-replace-settargetfragment-now-that-it-is-deprecated#comment114721602_64869730 

Here's the deprecated API reference:
https://developer.android.com/reference/androidx/fragment/app/Fragment#setTargetFragment(androidx.fragment.app.Fragment,%20int)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/9444#r695165322_

**Comment by Arnold2381** [comment]
Commenting to keep it open. 
PS: I tried this, but couldn't implement it.

**Comment by BrayanDSO** [comment]
Currently, the only place `setTargetFragment` is used is on `Preferences.kt`

It is necessary to use it, because AndroidX `PreferenceDialogFragmentCompat` calls `getTargetFragment()`. If this happens without `setTargetFragment` getting called before, it leads to a crash, which means that we can't exchange it to [setFragmentResultListener](https://developer.android.com/reference/androidx/fragment/app/FragmentManager#setFragmentResultListener(java.lang.String,androidx.lifecycle.LifecycleOwner,androidx.fragment.app.FragmentResultListener)) as well.

This is definitely a upstream problem, and the current best course of action is to suppress the warning and give a +1 to these issues on Google issue tracker:
- https://issuetracker.google.com/issues/181793702
- https://issuetracker.google.com/issues/212905758
