### ISSUE TITLE
[Bug] Undo button on deck view doesn't work anymore

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#9490]
1) Finish a deck
2) on the deck list, tap the deck again so that the deck view shows up
3) tap the undo button on the top right

Result: nothing happens.

The undo button worked for years, so I can't say on which version it stopped working.

It's the only chance to undo the last card. So if you pressed the wrong answer button for the last card, there's currently no way to undo it.

AnkiDroid Version = 2.16alpha13

Android Version = 9

Manufacturer = HMD Global

Model = TA-1021

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; TA-1021 Build/PKQ1.181105.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4629.0 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison-1** [comment]
I can't reproduce this, but I have heard of this happening

* I have a deck with a single review card
* I select "Good"
* "Undo Last Review" is visible in the app bar menu
* I tap the deck/counts: "no cards available" 
* "Undo Last Review" is still visible

----

* I tap a different deck's counts
* I return
* Undo is no longer available

Is the above the issue?

**Comment by Anthropos888** [comment]
Ah, I see, there's "Undo last reviews" in the three dot menu in the deck list. I never saw that. So that would solve my problem.

The bug I described is that the undo button in deck details view no longer works. It's the top right button in the screenshot.
![upload_2021_09_04_00_24_40_702](https://user-images.githubusercontent.com/45192213/132070768-e5dfdc48-f2cf-4108-90f5-6de8976a8658.png)

**Comment by david-allison-1** [comment]
Oh! Makes complete sense. Thank you

**Comment by Arthur-Milchior** [comment]
@david-allison-1 you added reproduced. Do you have a regression test by any luck?

**Comment by Arthur-Milchior** [comment]
@Anthropos888 Normally, undo become unavailable when you switched to a new deck ? Is there a chance that it occured? For example if you have deck with subdeck, it can be possible that you selected a deck the first time and its subdeck later, or the reverse. 

Selecting a deck mean doing anything with it, so it can be touching it, changing its options, and so on.

The other cases where the undo list can be cleared is if you switched scheduler or synced. If you have an automate sync activated when you come back to the deck picker, it may explain the issue.



By any luck, does the problem occur soon after you synced another device? 
The other hypothesis I have (technical, mostly for other devs investigating) is that somehow curDeck and activeDecks are out of sync. So that the decks reviewed are not actually the child of the selected deck.
It seems impossible to do so with only AnkiDroid, at least the version under master. But it is not necessarily impossible to obtain this after a sync

**Comment by Anthropos888** [comment]
@Arthur-Milchior 
The problem is, that nothing happens when I tap the undo button after finishing the deck. 
It used to work just fine and I used this button for years. It doesn't seem to be related with the sync state. I didn't sync my device for months. For testing , I have synced my collection just now. Still the same behavior, nothing happens when I tap the button after finishing a deck. 

You're right, the button disappears when I start a new deck or when I close the app. Also the "Undo last review" function in the 3 dot menu is no longer available.

Actually this issues is not a big deal anymore for me, since I could use the 3 dot menu to undo the last review right after finishing a deck.

So maybe the easiest solution would be to remove that undo button from the deck details screen so that user's won't be confused.

**Comment by Arthur-Milchior** [comment]
Oh, so you mean that the buttons seems to be clickable (it's white and not grey)
Did you check whether really nothing occured?
I can imagine that the card goes back to review mode, but the app does not open the reviewer anymore. That would still mean that if you move to the deck picker, you'll see one card to review in the deck description.

that would be far less surprising to me. Because I do remember there was some recent change with the rule "should we reopen the reviewer anymore after an undo". I'm not sure I followed thoroughly, but I suspect that it might be related to your problem.


In case you are curious, the issue used to be something such as: if you suspend the last card of the deck, you go to DeckPicker. If you undo, you should open the reviewer with this card.
So we had this rule "undoing a suspend/bury will review the card again". However, you can also suspend a card from the browser, which caused unexpected behavior. The rule had to be changed and I'm not sure what exact change ocured at the time.

**Comment by Anthropos888** [comment]
@Arthur-Milchior 
Yes, the undo button is white and clickable. If you tap it you can see the normal tapping animation (short highlighting of the button). But nothing happens. I can tap the button several times. The button highlighting shows that my tapping is recognized, but besides that theres no action at all. The reviewer is not started, the deck dateils screen just stays as it is.

Does the button actually work on your device after you finished a deck?

**Comment by Anthropos888** [comment]
Ah, ok, I just saw that the "Undo last review" function in the 3 dot menu doesn't work properly.
It doesn't show me the last reviewed card but a random card that wasn't even review card of the just finished deck.

Seems that some more things are going on here.
Just tell me what I can do to determine the problem.

**Comment by akp660** [comment]
![132070768-e5dfdc48-f2cf-4108-90f5-6de8976a8658](https://user-images.githubusercontent.com/72183243/212945583-21fd84d9-2a4d-4621-9540-3db3fbc63029.png)

I want to try to fix this issue.

**Comment by dae** [comment]
If the issue exists when 2.17 alpha releases, please let us know.
