### ISSUE TITLE
Login Activity does not support closing the keyboard when clicking in the background.

### ISSUE THREAD

**Issue by cdhiraj40** [ankidroid/Anki-Android#9546]
**Is your feature request related to a problem? Please describe.**
It's always good to have the keyboard close when clicked on backgroud.

**Describe the solution you'd like**
I will add 2 methods:
1-hideKeyboard
2-hideKeyboardBackground

**Additional context**

https://user-images.githubusercontent.com/75211982/134555746-bea556d9-3d45-4878-a1c9-91d2ae54e8ff.mp4

**Comment by cdhiraj40** [comment]
if @david-allison-1 @mikehardy like this feature I can implement this at other places too. Thanks :)

**Comment by mikehardy** [comment]
If I'm correct, I think I noticed the same thing today. Is the video you posted already integrating the feature? Because when I tried to login today I noticed that I tapped out of the text box and the keyboard did not go away (so my password field was still obscured, which was annoying)

**Comment by david-allison-1** [comment]
This is a standard Android interaction. The keyboard is closed by the back button. Most apps only close it when scrolling

I don't personally see the benefit from changing this behaviour. I'm willing to be convinced, especially if you have a source from UX/UI guidelines

**Comment by cdhiraj40** [comment]
> If I'm correct, I think I noticed the same thing today. Is the video you posted already integrating the feature? Because when I tried to login today I noticed that I tapped out of the text box and the keyboard did not go away (so my password field was still obscured, which was annoying)

Yes I did this and then recorded the screen.

**Comment by cdhiraj40** [comment]
> This is a standard Android interaction. The keyboard is closed by the back button. Most apps only close it when scrolling
> 
> I don't personally see the benefit from changing this behaviour. I'm willing to be convinced, especially if you have a source from UX/UI guidelines

Sorry, currently I don't have any UX/UI guidelines. But it's really annoying as @mikehardy pointed out, users have to take their finger down to press the back button whereas the same can be done by just clicking on the screen which makes the user experience better (as an AnkiDroid user:) ).

**Comment by mikehardy** [comment]
@david-allison-1 interesting! So in react-native, most screens are actually implemented inside a scroll view container (because you never know if you're content really will fit on a single screen in a small device). And the scroll view container defaults to dismissing the keyboard on any non-text-field tap:

https://reactnative.dev/docs/next/scrollview#keyboardshouldpersisttaps

So in my professional experience (working on react-native things all over the place) I always tap out of the text field and just expect the keyboard to go away, personally :-)

Clearly this is opinion then. 

A counterexample is Flutter, which does not dismiss automatically like this and is closer to Google + Google's Android guidelines.

So even though I like it personally given it's a difference of opinion with no clear answer, I'm going to use the criteria of "which choice results in no change" as the tiebreak and say not adding a feature is better than adding a feature, in the absence of some legitimate reason, and say no on this one

If there's some UI/UX guideline I'm missing for Android that says otherwise, we can reopen
