### ISSUE TITLE
Fix Note Editor icons not appearing on Xiaomi

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9570]
This is because they don't invert the colors in their dark mode.

Thoughts:

* Add a border to the icons
* Disable Xiaomi dark mode inversion (I saw a comment a couple weeks ago)

Adding this as a separate issue because it's causing review pain

**Comment by mikehardy** [comment]
The dark mode disable looked gross - possible, but gross. I wonder if adding a border is sufficient to stop it :thinking: ? If so that seems easy

**Comment by david-allison-1** [comment]
> The dark mode disable looked gross - possible, but gross. I wonder if adding a border is sufficient to stop it 🤔 ? If so that seems easy

What was gross about it? I'll need to read up, but from memory it was an attribute in the style/attrs somewhere?

**Comment by Shidouuu** [comment]
Could you post a screenshot? I have a xiaomi and I'm not sure which icons you're talking about

**Comment by mikehardy** [comment]
@Shidouuu it would be excellent if you can reproduce this and help us test any possible fix!
Xioami has a "forced dark mode",
- if you make sure it is enabled, and specifically is enabled for AnkiDroid
- make sure AnkiDroid is not in "local dark mode" (that is, make sure that AnkiDroid *wants* to be in normal light mode

I think at this point AnkiDroid should be showing up in the MIUI forced dark mode - so it's a dark mode but not our theme.

Now if you go to edit a note, you should not see any paperclip icons next to the fields in the note editor screen - this is the main problem. We get all sorts of complaints from people saying "I can't attach sounds or images to my notes", because MIUI forced dark mode makes the icons black-on-black.

If you disable forced dark mode for AnkiDroid and then turn on AnkiDroid's dark mode, you should see a dark mode that does have paperclip icons.

How do we resolve this problem? That's the goal of the issue.

Here is the comment where I mention possible disable: https://github.com/ankidroid/Anki-Android/issues/6614#issuecomment-926010293

And on second glance at the linked https://stackoverflow.com/questions/65498309/detect-dark-mode-in-miui-xiaomi/65616633#65616633 - perhaps it really isn't that bad? We would just need to test it...

**Comment by Shidouuu** [comment]
Interestingly, it seems I do not even have a force dark mode:
![IMG_20210930_113357.jpg](https://user-images.githubusercontent.com/36283656/135486258-ca1fc1a6-28c5-4595-8aa5-036029e6631d.jpg)

On MIUI 11.0.3.0, Redmi Note 5. Apparently there's no updates available...

**Comment by mikehardy** [comment]
Oh that's a shame - it looks like you zeroed in *right* where it should be according to this https://youtu.be/ZUyqyR4xpgk?t=153

So that device won't be a valid test rig for this :shrug:  - we wait :-)

**Comment by david-allison-1** [comment]
User feedback: let's see if #9656 makes this better

![image](https://user-images.githubusercontent.com/62114487/137645031-c8d286cc-4725-4e61-8f61-7c329d813d06.png)

**Comment by david-allison-1** [comment]
![image](https://user-images.githubusercontent.com/62114487/137646436-d738c525-fd90-42cf-b60d-096b662fabf3.png)

**Comment by mikehardy** [comment]
I think that looks pretty good all things considered
