### ISSUE TITLE
[Bug] No deck highlighted in deck selection in note editor

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9755]
###### Reproduction Steps

1. Open note editor
2. click on the deck
3. scroll to current deck

###### Expected Result

Current deck is highlighted (and ideally, when opened, current deck is shown on the screen, instead of the top of the deck list)

###### Actual Result
No deck is highlighted. Actually in DeckSpinnerSelection.java `initializeNoteEditorDeckSpinner` `noteDeckAdapter`, the method is never called (I checked with the debugger). Which I honestly don't understand as it seems quite similar to NoteTypeSpinnerUtils.kt which work

###### Debug info
c6ef93c4fbaee244766e59ec2ce4a3846e4d8898

**Comment by codingtosh** [comment]
Hey @Arthur-Milchior , this took the whole night, but I was able to come up with a working solution. Please assign this to me, I'll be hitting the bed now but will upload the PR with detailed inspection/approach after I wake up. 

https://user-images.githubusercontent.com/81802035/139984302-d5f38815-6286-4fca-b978-4d9ebd5047b9.mp4

**Comment by Arthur-Milchior** [comment]
Be sure to rebate on master. Deck spinner was changed a lot earlier. I spent a lot of time trying to understand and simplify it's logic

Thanks a lot

**Comment by codingtosh** [comment]
Hey @Arthur-Milchior, sorry the delay, something came up, 
I have uploaded the PR, please take a look and let me know the approach should be changed/tweaked in any way.

**Comment by david-allison-1** [comment]
I've reopened this due to https://github.com/ankidroid/Anki-Android/issues/9914, and reverted the change which implements this: https://github.com/ankidroid/Anki-Android/pull/9917, as fixing the functionality was more complex than I anticipated. 

Proposed path to fix this:

* Add regression tests, ensuring that tapping on the deck selection dialog does not crash.
* The adapter's SelectedItem functionality seems to be flaky (crash if last item is selected): maybe an off-by-one if "all decks" isn't there, may be lifecycle based
* Determine if `DeckSpinnerSelection` is the correct abstraction
  * Add documentation if it is
  * HasSpinner is no longer necessary - always true
  * SelectedItem seems to either return the name, or Json of the deck object
* Pass in the name of the currently selected deck to `DeckSelectionDialog`, rather than depending on `getActivity`

**Comment by codingtosh** [comment]
Thanks @david-allison-1  for the suggested path. If this isn't high priority after the rollback, I'll look into this over the weekend if that's okay? I'll be working on the kotlin migration until then.

**Comment by david-allison-1** [comment]
Not high priority at all, whenever it suits you.
