### ISSUE TITLE
Triage: Corrupt `models`

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9764]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/f35a6fb2-ad36-4fb6-97fe-03e6a68903f3

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: com.ichi2.utils.JSONException: org.json.JSONException: Unterminated string at character 172024 of <snipped>
```

**Comment by david-allison-1** [comment]
@shiideyuuki, I haven't seen this one before, and it implies a corruption which shouldn't be possible.

* Are you using Anki Desktop, addons, or syncing successfully?
* Are you doing anything unexpected (editing files outside the app, using third party apps)?
* Does your Anki collection contain sensitive information that you wouldn't be comfortable sharing publicly?

**Comment by shiideyuuki** [comment]
> @shiideyuuki, I haven't seen this one before, and it implies a corruption which shouldn't be possible.
> 
> * Are you using Anki Desktop, addons, or syncing successfully?
I'm using Anki desktop, addons and its syncing successfully

> * Are you doing anything unexpected (editing files outside the app, using third party apps)?
No, (But I'm using an addon called "Auto Ease Factor" which uses a different algorithm than Anki currently has. This addon changes the deck's card's ease based on its said algorithm. I'm using this one since I think its more effective than Anki's and I also want it to be implemented to Anki if everyone doesn't mind. If you can consider this unexpected, then yes). I also have third party apps (android): "com.jkcarino.ankiankieditor" and "io.infinyte7.ankiankiimageocclusion." I haven't ever used the former, and the latter, it's been a long time since I used it (I use more the Anki Image occlusion addon in desktop).

> * Does your Anki collection contain sensitive information that you wouldn't be comfortable sharing publicly?
No, I'm also using anki to take notes in school and for some books I read. I don't think they contain personal information, but with an effort, someone might know some things about me but I don't consider them personal.

**Comment by david-allison-1** [comment]
Could you zip and upload the file at `AnkiDroid/collection.anki2` on your phone, then post it as a comment. 

This file contains all Anki data except images (and some preferences, such as syncing information), so if it's got any sensitive information in the cards (phone numbers), get in touch and we can access it privately.

AnkiDroid should not be experiencing this issue at the point that you send the file, so we can determine which (if any) of our actions are causing this to occur. 

I haven't seen this before, and it's vital to me that we ensure it doesn't happen again.

**Comment by shiideyuuki** [comment]
https://drive.google.com/file/d/1hBnlvuXcRVdjeny66M8q4wU0Zaz_HXyp/view?usp=drivesdk
