### ISSUE TITLE
Font very small

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#9934]
When you are studying the flashcards the font its very small compared to when you are editing and preview them
![Screenshot_20211119-222949](https://user-images.githubusercontent.com/73913963/142714489-d24c5a36-909a-498e-95bc-d0755934c6cf.png)
![Screenshot_20211119-223012](https://user-images.githubusercontent.com/73913963/142714490-d21a15b8-e3d9-4129-adc2-8fb779b5f555.png)

**Comment by divyansh2212** [comment]
@javiercl2020 Hey, I want to contribute to this issue. How can I start to do so?

**Comment by mikehardy** [comment]
This isn't an issue - this is a card template issue.
Each card is a tiny web page, with all the power of HTML and CSS.
It appears you have used (or downloaded a deck that uses) this power in the template, with results that you don't personally like
That's an issue with your data in your card template though, and you'll have to edit that in order to achieve the results you want

Here's our best information on that https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting

**Comment by javiercl2020** [comment]
Yes I understand I did change the font size to 50 px and still very small but when I edit them its huge only when I study them its small
