### ISSUE TITLE
Android 12 performance issues

### ISSUE THREAD

**Issue by av223119** [ankidroid/Anki-Android#9941]
###### Reproduction Steps

1. Install AnkiDroid 2.15.6 on Android12 system
2. Import a reasonably large deck (in my case ~6000 cards)
3. Learn

###### Expected Result
Reaction on the buttons should be immediate or almost immediate

###### Actual Result
Occasionally the program freezes for 3-5 seconds; during the freeze, it remains completely unresponsive and doesn't react on any actions, including back button/gesture.

###### Debug info
AnkiDroid Version = 2.15.6
Android Version = 12
Manufacturer = Google
Model = Pixel 4a
Hardware = sunfish
Webview User Agent = Mozilla/5.0 (Linux; Android 12; Pixel 4a Build/SP1A.211105.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36
ACRA UUID = 33731ecd-015a-4be9-a8a8-9a4507ddc284
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks for reporting this and including your system info @av223119 I appreciate it!

For interested parties: I have started hearing a few reports of this on play store reviews and on the mailing list for Android 12.

What is it? No idea unfortunately but here is the start of our troubleshooting info :point_up:

**Comment by mikehardy** [comment]
Interestingly I have a Pixel4a in the house but I don't think it's on Android 12 yet? It's the wife's phone and I am usually the updater but I have been busy. This doesn't look good at a first glance though: https://support.google.com/pixelphone/thread/132194325/battery-drain-after-updating-to-android-12-in-pixel-4a?hl=en - appears there is more than on gremlin in Android 12 still

**Comment by david-allison-1** [comment]
My Pixel 3A is offering me the Android 12 update. Haven't done it yet due to the potential need for testing scoped storage.

**Comment by av223119** [comment]
I believe the a12 update has been rolled out to Pixel users across the
globe cca one month ago. I haven't experienced any battery-related issues,
but of course YMMV.

po 22. 11. 2021 v 23:02 odesílatel Mike Hardy ***@***.***>
napsal:

**Comment by cburroughs** [comment]
I also have a pixel4a on Android 12 with  AnkiDroid 2.15.6.  My primary deck is about 14k cards, it may be relevant that I have a habit of switching between the subdecks of that large parent deck.  The experience on Android 12 is subjectively most frustrating.  At least in my case I primarily notice two kinds of pauses.

(A) After finishing (either because I completed all reviews or decided it was time to study something else) a sub-deck and trying to open a new one.  After finishing the deck the deck tree UI has *not* updated (if I had 20 reviews to do and just did them all, the UI still says 20 are pending).  After the UI freeze passes and counts are updated I can open a new deck again.

(B) After opening a deck, there is a freeze before the first card is displayed.   The UI "scaffolding" of deck title and answer buttons is there, but the card is all white.

Before writing this comment I spent ~5 minutes on reviews and got pauses of 5s, 12s, and >15s.  I can sit there with a stop watch and notepad more of that is helpful. I don't *think* I have experienced a long (> 10s) pause while doing reviews in the middle of a deck.

**Comment by mikehardy** [comment]
Thanks for reporting your experience with some stats. We definitely try to defer some of the count refresh / UI repaint to async threads in order to stop the UI from hard-freezing but the delays are not supposed to be that extreme of course.

This reminds me of this comment though: specifically that our current hypothesis is the scoped storage work which is currently in progress will solve it because *apparently* Android's enforcement of scoped storage has added what appears to be a large amount of overhead to filesystem work in the non-scoped storage directories. There's a possible workaround, examine: 

https://github.com/ankidroid/Anki-Android/issues/8925#issuecomment-976337268

> Fixed in #9249, it's writing to a "publicly visible" directory that's taking time.
> 
> Significantly faster if
> 
> Copy /AnkiDroid to /storage/emulated/0/android/data/com.ichi2.anki/col
> This requires a PC and USB
> Set Settings - Advanced - AnkiDroid Directory to /storage/emulated/0/android/data/com.ichi2.anki/col

**Comment by av223119** [comment]
Hello,

December a12 update (
https://support.google.com/pixelphone/thread/139017133/google-pixel-update-december-2021?hl=en)
released today includes one noticeable line in the changelog:
* Fix for stuck or frozen app UI in certain conditions

While it is probably too early to draw conclusions right now, I have to
report that I've gone through ~80 cards today after the upgrade without any
issues.

Regards,

po 22. 11. 2021 v 22:51 odesílatel Mike Hardy ***@***.***>
napsal:

**Comment by cburroughs** [comment]
I still experience both "types" of pauses with ` SQ1A.211205.008` on my Pixel 4a.

**Comment by cburroughs** [comment]
The barrel of molasses that Google dumped all over Android 12 is still sticky.

**Comment by mikehardy** [comment]
The amount of change they injected into their APIs in the migrations between 9/10, 10/11 and then 11/12 is cumulatively just a huge pile to deal with. I've got multiple chunks of software (not just AnkiDroid) that can't target API31 yet :weary:. Just a lot of work, yes

**Comment by grit780** [comment]
Interesting that the issue wasn't happening on the official Samsung android 12 ROM (One UI 4.0), but does happen on the custom ROM.

**Comment by grit780** [comment]
> [#8925 (comment)](https://github.com/ankidroid/Anki-Android/issues/8925#issuecomment-976337268)
> 
> > Fixed in #9249, it's writing to a "publicly visible" directory that's taking time.
> > Significantly faster if
> > Copy /AnkiDroid to /storage/emulated/0/android/data/com.ichi2.anki/col
> > This requires a PC and USB
> > Set Settings - Advanced - AnkiDroid Directory to /storage/emulated/0/android/data/com.ichi2.anki/col

Thanks a lot for this solution - it has fixed the issue for me.

**Comment by BrayanDSO** [comment]
Upgraded to Android 12 recently, got the same problem

> https://github.com/ankidroid/Anki-Android/issues/8925#issuecomment-976337268

> > Fixed in https://github.com/ankidroid/Anki-Android/pull/9249, it's writing to a "publicly visible" directory that's > > taking time.
> > Significantly faster if
> > Copy /AnkiDroid to /storage/emulated/0/android/data/com.ichi2.anki/col
> > This requires a PC and USB
> > Set Settings - Advanced - AnkiDroid Directory to /storage/emulated/0/android/data/com.ichi2.anki/col

Done this (though it didn't require a PC) and it's fixed now

**Comment by freMea** [comment]
> Upgraded to Android 12 recently, got the same problem
> 
> > https://github.com/ankidroid/Anki-Android/issues/8925#issuecomment-976337268
> 
> > > Fixed in https://github.com/ankidroid/Anki-Android/pull/9249, it's writing to a "publicly visible" directory that's > > taking time.
> > > Significantly faster if
> > > Copy /AnkiDroid to /storage/emulated/0/android/data/com.ichi2.anki/col
> > > This requires a PC and USB
> > > Set Settings - Advanced - AnkiDroid Directory to /storage/emulated/0/android/data/com.ichi2.anki/col
> 
> Done this (though it didn't require a PC) and it's fixed now

I confirm it fixed my issue on custom ROM A11. `/sdcard/Ankidroid` used to work fast in Android 9 but incredibly slow on A11.

Another thing is to allow write Anki database in app permission. If not allowed, it will lag even worse.
