### ISSUE TITLE
Multiple choice cloze test

### ISSUE THREAD

**Issue by octavo** [ankidroid/Anki-Android#9944]
Implement multiple choice cloze tests.

Man landed on the moon in [...] → "Man landed on the moon in 1969"
1 2000
2 1969
3 1970
4 2020

**Comment by david-allison-1** [comment]
Hi, thanks for the suggestion.

We don't implement multiple choice cards by default as they're not optimal for learning (unless you're specifically preparing for a test with the given choices): https://faqs.ankiweb.net/multiple-choice-questions.html

Instead, you should format your card as:

`Man landed on the moon in {{c1::1969}}`, 

You can optionally add a hint for the decade: 

`Man landed on the moon in {{c1::1969::196X}}`

If you still want a multiple choice cloze deletion template, you can likely find one by searching the [subreddit](https://www.reddit.com/r/Anki/), or the [forum](https://forums.ankiweb.net/)

----

I'm going to close the issue because it goes against Anki's design goals. 

The above links should help if you still want to do this. If Anki Desktop implements a multiple-choice card type, we'll add one.

Regardless, thanks again for the feature request!
