### ISSUE TITLE
[Bug] all of my photo are gone how can i return it back

### ISSUE THREAD

**Issue by Bedaryosif** [ankidroid/Anki-Android#9968]
- [ ] [######](url) Reproduction Steps

1. ### ### ### ### 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Bedaryosif** [comment]
![Screenshot_20211205-160911_AnkiDroid](https://user-images.githubusercontent.com/95573619/144747937-ba93dd91-1d8a-4378-ab57-d017f8970284.jpg)

**Comment by mikehardy** [comment]
There are many reasons this may happen, here are our best steps to determine the real reason, and help fix:
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid
Note that it may be sync just hasn't finished syncing media because it was stopped in the background or similar. Every time you sync, if it is syncing media it is getting slowly closer to being in sync though. Keep syncing until it's done:
https://github.com/ankidroid/Anki-Android/wiki/FAQ#sync-is-not-working

**Comment by Bedaryosif** [comment]
I have lost all my photos both in ankiweb and ankidroid
I have tried synchronization and its said its complete but my photos are
not returning
Please its absolutely necessary to fix that
Than you for you help

**Comment by mikehardy** [comment]
I understand the frustration.
I have, however, provided you with all the information we have to offer though - in the links above.
You will need to investigate your device to see if the media is actually there, as the docs direct you to do, restore from a backup of your device if they are not there (like, from https://f-droid.org/en/packages/org.amoradi.syncopoli/ - I use this to make backups) or perhaps take other actions depending on the root cause.

Our documentation really is our best information on the subject. Simply repeating a request will unfortunately not help.

**Comment by Bedaryosif** [comment]
Thank you
But I do not know how to make backup by syncopli
I have downloaded the app but I do not know how it works
Can tell me how to back up my media

**Comment by mikehardy** [comment]
No I cannot. Taking backups of your data is a personal task and instruction on same is out of scope for this repo.
I only used that app as an example of *how* you *might* take backups. Please understand if your data is gone, it's gone. If you don't already have a backup and it's gone, you have lost data.
That's why a backup system is important, but it's important prior to possible data loss
