### ISSUE TITLE
[Bug] The sync button badge doesn't light up when adjusting the number of today's study cards in custom study.

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#9978]
###### Reproduction Steps

1. Press and hold the deck to select custom study
2. Modify today's card limit.

###### Expected Result

A red badge appears on the sync button

###### Actual Result

A red badge does not appear on the sync button

###### Debug info
AnkiDroid Version = 2.16alpha34

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.92 Mobile Safari/537.36

ACRA UUID = f40502af-2f2d-46a1-89bc-6b86d7fa6380

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by RaidenCHEN** [comment]
Hi, I would like to work on this issue. Could I have this one? @david-allison

**Comment by david-allison** [comment]
> Hi, I would like to work on this issue. Could I have this one? @david-allison 

Sounds good to me!

**Comment by RaidenCHEN** [comment]
@david-allison @mikehardy  Hi! Right now, i have added the trans of syncstatus when choosing to modify "today's new card limit" or "today's review card limit". But the problem is, other options in Custom Study would trigger a page transform, which will cause a redraw of main menu calling the `onCreateOptionsMenu(menu: Menu)` function. The redrawing process performs like refresh, and thus the change of badge would appears. However, since  `Modify today's new/review card limit` just simply exit the dialog when pressing OK button, which not involving the `onCreateOptionsMenu` function and thus, i need to enter one deck and get out to let the badge lit.
I would like to know if there is any function that i may use for the refresh/redrawing of the menu? (`onCreateOptionsMenu` needs an input of Menu kind which i do not really know where to get.)

**Comment by david-allison** [comment]
`supportInvalidateOptionsMenu`?

It's recently got a deprecation, feel free to `@Suppress("deprecation")` to get it to compile

**Comment by yshubham8419** [comment]
Hi @david-allison , I want to work on this issue.

**Comment by mikehardy** [comment]
I think this is going to be a tough issue because of this - #11902 - no effort should be spent on the current implementation because of the new schema making it obsolete. That said if you want to take this up - for the new schema in general (11902 as well as this) that would be *awesome*

**Comment by dae** [comment]
#11902 should already be sorted for the new schema: https://github.com/ankitects/Anki-Android/commit/7c5da5a3297f66f29dbd018b0e496c5c8c1053cd

**Comment by yshubham8419** [comment]
Thanks for the information, I will find another issue.
